Dali::VideoPlayer
Dali::VideoPlayer::VideoPlayer()
Constructor. @SINCE_1_1.38.
Referenced by DownCast, New, New, New.
Dali::VideoPlayer::~VideoPlayer()
Destructor. @SINCE_1_1.38.
Dali::VideoPlayer::VideoPlayer(const VideoPlayer &player)
Copy constructor.
@SINCE_1_1.38 player VideoPlayer to copy. The copied player will point at the same implementation
VideoPlayer & Dali::VideoPlayer::operator=(const VideoPlayer &player)
Assignment operator.
@SINCE_1_1.38 player The VideoPlayer to assign from. The updated VideoPlayer.
Dali::VideoPlayer::VideoPlayer(VideoPlayer &&player) noexcept
Move constructor.
@SINCE_2_1.45 player VideoPlayer to move. The moved player will point at the same implementation
VideoPlayer & Dali::VideoPlayer::operator=(VideoPlayer &&player) noexcept
Move assignment operator.
@SINCE_2_1.45 player The VideoPlayer to move assign from. The updated VideoPlayer.
void Dali::VideoPlayer::SetUrl(const std::string &url)
Sets a URL of the video file to play.
@SINCE_1_1.38 url The url of video file
References Dali::GetImplementation.
std::string Dali::VideoPlayer::GetUrl()
Returns the URL of the video file. @SINCE_1_1.38.
Url of string type
References Dali::GetImplementation.
void Dali::VideoPlayer::SetLooping(bool looping)
Sets the player looping status. @SINCE_1_1.38.
looping The new looping status: true or false
References Dali::GetImplementation.
bool Dali::VideoPlayer::IsLooping()
Returns the player looping status. @SINCE_1_1.38.
True if player is looping, false otherwise.
References Dali::GetImplementation.
void Dali::VideoPlayer::Play()
Starts the video playback. @SINCE_1_1.38.
References Dali::GetImplementation.
void Dali::VideoPlayer::Pause()
Pauses the video playback. @SINCE_1_1.38.
References Dali::GetImplementation, Dali::Internal::Adaptor::SceneHolder::Pause.
void Dali::VideoPlayer::Stop()
Stops the video playback. @SINCE_1_1.38.
References Dali::GetImplementation.
void Dali::VideoPlayer::SetMute(bool mute)
Sets the player mute status. @SINCE_1_1.38.
mute The new mute status, true is mute.
References Dali::GetImplementation.
bool Dali::VideoPlayer::IsMuted()
Returns the player mute status. @SINCE_1_1.38.
True if player is mute.
References Dali::GetImplementation.
void Dali::VideoPlayer::SetVolume(float left, float right)
Sets the player volume. @SINCE_1_1.38.
left The left volume scalar right The right volume scalar
References Dali::GetImplementation.
void Dali::VideoPlayer::GetVolume(float &left, float &right)
Returns current volume factor. @SINCE_1_1.38.
left The current left volume scalar right The current right volume scalar
References Dali::GetImplementation.
void Dali::VideoPlayer::SetRenderingTarget(Any target)
Sets video rendering target. @SINCE_1_1.38.
target The target for video rendering, window surface or native image
References Dali::GetImplementation.
void Dali::VideoPlayer::SetPlayPosition(int millisecond)
Sets the position for playback. @SINCE_1_1.38.
millisecond The position for playback
References Dali::GetImplementation.
int Dali::VideoPlayer::GetPlayPosition()
Gets the current position in milliseconds. @SINCE_1_1.38.
The current position of playback
References Dali::GetImplementation.
void Dali::VideoPlayer::SetDisplayArea(DisplayArea area)
Sets the area of video display. @SINCE_1_2.46 param[in] area The left-top position and size of the video display area.
References Dali::GetImplementation.
void Dali::VideoPlayer::SetDisplayRotation(Dali::VideoPlayerPlugin::DisplayRotation rotation)
Sets video display rotation @SINCE_1_1.38.
rotation The rotation of display
References Dali::GetImplementation.
Dali::VideoPlayerPlugin::DisplayRotation Dali::VideoPlayer::GetDisplayRotation()
Returns rotation of current video display @SINCE_1_1.38.
The rotation of current display
References Dali::GetImplementation.
Dali::VideoPlayerPlugin::VideoPlayerSignalType & Dali::VideoPlayer::FinishedSignal()
Connect to this signal to be notified when a video playback have finished.
@SINCE_1_1.38 A signal object to connect with.
References Dali::GetImplementation.
Dali::VideoPlayerPlugin::VideoPlayerEventSignalType & Dali::VideoPlayer::EventSignal()
Connect to this signal to be notified when a video playback have evented.
A signal object to connect with.
References Dali::GetImplementation.
void Dali::VideoPlayer::Forward(int millisecond)
Seeks forward by the specified number of milliseconds.
@SINCE_1_2.46 millisecond The position for forward playback
References Dali::GetImplementation.
void Dali::VideoPlayer::Backward(int millisecond)
Seeks backward by the specified number of milliseconds.
@SINCE_1_2.46 millisecond The position for backward playback
References Dali::GetImplementation.
bool Dali::VideoPlayer::IsVideoTextureSupported()
Checks whether the video texture is supported.
True if supported, otherwise false.
References Dali::GetImplementation.
void Dali::VideoPlayer::SetCodecType(Dali::VideoPlayerPlugin::CodecType type)
Sets codec type.
type The VideoCodec::Type
References Dali::GetImplementation.
Dali::VideoPlayerPlugin::CodecType Dali::VideoPlayer::GetCodecType() const
Gets codec type.
VideoCodec::Type
References Dali::GetImplementation.
void Dali::VideoPlayer::SetDisplayMode(Dali::VideoPlayerPlugin::DisplayMode::Type mode)
Sets the display mode for playback.
mode of playback
References Dali::GetImplementation.
Dali::VideoPlayerPlugin::DisplayMode::Type Dali::VideoPlayer::GetDisplayMode() const
Gets display mode.
DisplayMode
References Dali::GetImplementation.
Any Dali::VideoPlayer::GetMediaPlayer()
Gets the media player of video player.
player The media player
References Dali::GetImplementation.
void Dali::VideoPlayer::StartSynchronization()
calls synchronization function in window system This function is called, the synchronization is started between UI(transparent hole) and video player.
References Dali::GetImplementation.
void Dali::VideoPlayer::FinishSynchronization()
calls desynchronization function in window system This function is called, the synchronization is ended between UI(transparent hole) and video player.
References Dali::GetImplementation.
void Dali::VideoPlayer::RaiseAbove(Dali::VideoPlayer target)
Raise the video player above the target video plaer.
target The target video player
References Dali::GetImplementation.
void Dali::VideoPlayer::LowerBelow(Dali::VideoPlayer target)
Lower the video player to below the target video player.
target The target video player
References Dali::GetImplementation.
void Dali::VideoPlayer::RaiseToTop()
Raise video player above all other sibling video players.
References Dali::GetImplementation.
void Dali::VideoPlayer::LowerToBottom()
Lower video player to the bottom of all other sibling video players.
References Dali::GetImplementation.
void Dali::VideoPlayer::SceneConnection()
Video View has video player is connected to Window's Scene.
References Dali::GetImplementation.
void Dali::VideoPlayer::SceneDisconnection()
Video View has video player is disconnected to Window's Scene.
References Dali::GetImplementation.
void Dali::VideoPlayer::SetAutoRotationEnabled(bool enable)
Sets auto rotation feature. If enabled, video will rotate automatically according to the video orientation.
References Dali::GetImplementation.
bool Dali::VideoPlayer::IsAutoRotationEnabled() const
Checks whether auto rotation feature is enabled.
References Dali::GetImplementation.
void Dali::VideoPlayer::SetLetterBoxEnabled(bool enable)
Sets letter box feature. If enabled, the video will play in the video player's aspect ratio.
References Dali::GetImplementation.
bool Dali::VideoPlayer::IsLetterBoxEnabled() const
Checks whether letter box feature is enabled.
References Dali::GetImplementation.
void Dali::VideoPlayer::SetFrameInterpolationInterval(float intervalSeconds)
Sets the frame interpolation interval for smooth video playback. @SINCE_2_4.39.
intervalSeconds The interpolation interval in seconds
References Dali::GetImplementation.
void Dali::VideoPlayer::EnableOffscreenFrameRendering(bool useOffScreenFrame, Dali::NativeImagePtr previousFrameBufferNativeImagePtr, Dali::NativeImagePtr currentFrameBufferNativeImagePtr)
Enables or disables offscreen frame rendering for video interpolation. @SINCE_2_4.39.
useOffScreenFrame True to enable offscreen frame rendering, false to disable previousFrameBufferNativeImagePtr Native image for previous frame buffer currentFrameBufferNativeImagePtr Native image for current frame buffer
References Dali::GetImplementation.
void Dali::VideoPlayer::SetVideoFrameBuffer(Dali::NativeImagePtr source)
Sets the video frame buffer for rendering. @SINCE_2_4.39.
source The video frame buffer source containing surface data
References Dali::GetImplementation.
VideoPlayer Dali::VideoPlayer::New()
Creates a new instance of a VideoPlayer. @SINCE_1_1.38.
References Dali::DISABLED, VideoPlayer.
VideoPlayer Dali::VideoPlayer::New(Dali::Actor actor, VideoSyncMode syncMode)
Creates a new instance of a VideoPlayer.
If you want the video player works with Ui synchronous when video player is resized/moved, put the video view actor and the enabled syncMode. actor video view's actor instance syncMode The synchronization mode between the UI (transparent hole) and VideoPlayer.
References VideoPlayer.
VideoPlayer Dali::VideoPlayer::New(Dali::Actor actor, Dali::VideoPlayerPlugin::PlayerHandle playerHandle, VideoSyncMode syncMode)
Creates a new instance of a VideoPlayer wrapper using an existing player handle with actor for synchronization.
actor video view's actor instance for synchronization playerHandle The externally created native player handle with type information syncMode The synchronization mode between the UI and VideoPlayer.
References VideoPlayer.
VideoPlayer Dali::VideoPlayer::DownCast(BaseHandle handle)
Downcast a handle to VideoPlayer handle.
If handle points to a VideoPlayer the downcast produces valid handle. If not the returned handle is left uninitialized. @SINCE_1_1.38 handle Handle to an object Handle to a VideoPlayer or an uninitialized handle
References VideoPlayer.
Dali::VideoPlayer::VideoPlayer(Internal::Adaptor::VideoPlayer *internal)
Internal constructor @SINCE_1_1.38.