Dali::Accessibility::ActorAccessible
Dali::WeakHandle<Dali::Actor> Dali::Accessibility::ActorAccessible::mSelf
std::vector<Accessible*> Dali::Accessibility::ActorAccessible::mChildren
bool Dali::Accessibility::ActorAccessible::mChildrenDirty
bool Dali::Accessibility::ActorAccessible::mIsBeingDestroyed
const uint32_t Dali::Accessibility::ActorAccessible::mActorId
std::map<State, int> Dali::Accessibility::ActorAccessible::mLastEmittedState
std::shared_ptr<Collection> Dali::Accessibility::ActorAccessible::mCollection
Dali::Accessibility::ActorAccessible::ActorAccessible()=delete
Dali::Accessibility::ActorAccessible::ActorAccessible(Actor actor)
References Dali::Accessibility::Accessible::GetFeature, OnChildrenChanged.
void Dali::Accessibility::ActorAccessible::ObjectDestroyed() override
References Dali::Accessibility::Bridge::GetCurrentBridge, Dali::Accessibility::Accessible::GetFeature.
Address Dali::Accessibility::ActorAccessible::GetAddress() const override
Gets unique address on accessibility bus.
The Address class containing address Dali::Accessibility::Address
References Dali::Accessibility::Accessible::GetFeature.
std::string Dali::Accessibility::ActorAccessible::GetName() const override
Gets accessibility name.
The string with name
References Dali::Accessibility::Accessible::GetFeature, Self.
std::string Dali::Accessibility::ActorAccessible::GetDescription() const override
Gets accessibility description.
The string with description
std::string Dali::Accessibility::ActorAccessible::GetValue() const override
Gets accessibility value.
The value text
Accessible * Dali::Accessibility::ActorAccessible::GetParent() final
Gets parent.
The handler to accessibility object
References Dali::Accessibility::Accessible::Get, Dali::Accessibility::Bridge::GetCurrentBridge, Dali::Accessibility::Accessible::GetFeature, GetParent, Dali::Accessibility::Accessible::IsOnRootLevel, Self.
Referenced by GetIndexInParent, GetParent.
std::size_t Dali::Accessibility::ActorAccessible::GetChildCount() const final
Gets the number of children.
The number of children
Referenced by GetChildAtIndex.
std::vector< Accessible * > Dali::Accessibility::ActorAccessible::GetChildren() final
Gets collection with all children.
The collection of accessibility objects
Referenced by NotifyAccessibilityStateChange.
Accessible * Dali::Accessibility::ActorAccessible::GetChildAtIndex(std::size_t index) final
Gets child of the index.
The child object
References GetChildCount, Dali::Accessibility::Accessible::GetFeature.
std::size_t Dali::Accessibility::ActorAccessible::GetIndexInParent() final
Gets index that current object has in its parent's children collection.
The index of the current object
References Dali::Accessibility::Accessible::GetFeature, GetParent.
Dali::Actor Dali::Accessibility::ActorAccessible::GetInternalActor() const final
Gets the Actor associated with this Accessible (if there is one).
The internal Actor
References Self.
std::string Dali::Accessibility::ActorAccessible::GetStringProperty(std::string propertyName) const override
Gets the stirng property.
propertyName The property name. The string property value. Empty string if property does not exist.
ComponentLayer Dali::Accessibility::ActorAccessible::GetLayer() const override
Gets layer current object is localized on.
The enumeration pointing layer Dali::Accessibility::ComponentLayer
References Dali::Accessibility::WINDOW.
std::int16_t Dali::Accessibility::ActorAccessible::GetMdiZOrder() const override
Gets value of z-order.
The value of z-order MDI means "Multi Document Interface" (https://en.wikipedia.org/wiki/Multiple-document_interface) which in short means that many stacked windows can be displayed within a single application. In such model, the concept of z-order of UI element became important to deal with element overlapping.
double Dali::Accessibility::ActorAccessible::GetAlpha() const override
Gets value of alpha channel.
The alpha channel value in range [0.0, 1.0]
bool Dali::Accessibility::ActorAccessible::IsScrollable() const override
Checks whether object can be scrolled.
true if object is scrollable, false otherwise Dali:Accessibility::State
Dali::Rect< float > Dali::Accessibility::ActorAccessible::GetExtents(CoordinateType type) const override
Gets rectangle describing size.
type The enumeration with type of coordinate systems Rect<float> object Dali::Rect<float>
References CanAcceptZeroSize, Dali::DevelWindow::Get, Dali::Accessibility::Accessible::GetFeature, Self, Dali::Accessibility::WINDOW.
std::vector< Accessible * > Dali::Accessibility::ActorAccessible::GetMatches(MatchRule rule, uint32_t sortBy, size_t maxCount) override
Gets the matching Accessible objects with MatchRule.
rule Collection::MatchRule sortBy SortOrder::CANONICAL or SortOrder::REVERSE_CANONICAL maxCount The maximum number of objects; returns all matches if 0 The matching Accessible objects
References Dali::Accessibility::Accessible::GetFeature.
std::vector< Accessible * > Dali::Accessibility::ActorAccessible::GetMatchesInMatches(MatchRule firstRule, MatchRule secondRule, uint32_t sortBy, int32_t firstCount, int32_t secondCount) override
Gets the matching Accessible objects with two MatchRules.
firstRule The initial Collection::MatchRule. secondRule An secondary Collection::MatchRule. sortBy SortOrder::CANONICAL or SortOrder::REVERSE_CANONICAL firstCount The maximum number of objects to return for the initial match.; returns all matches if 0 secondCount The maximum number of objects to return for the secondary match.; returns all matches if 0 The matching Accessible objects
References Dali::Accessibility::Accessible::GetFeature.
void Dali::Accessibility::ActorAccessible::OnChildrenChanged()
Notifies this object that its children have changed.
This is useful if you maintain a custom collection of children that are not derived from ActorAccessible and the contents or order of elements in that collection change. DoGetChildren()
Referenced by ActorAccessible.
void Dali::Accessibility::ActorAccessible::EmitActiveDescendantChanged(Accessible *child)
Helper function for emiting active-descendant-changed event.
child The child of the object
References Dali::Accessibility::Bridge::GetCurrentBridge, Dali::Accessibility::Accessible::GetFeature.
void Dali::Accessibility::ActorAccessible::EmitStateChanged(State state, int newValue, int reserved=0)
Helper function for emiting state-changed event.
state The accessibility state (SHOWING, HIGHLIGHTED, etc) newValue Whether the state value is changed to new value or not. reserved Reserved. (TODO : Currently, this argument is not implemented in dali) The second argument determines which value is depending on State. For instance, if the state is PRESSED, newValue means isPressed or isSelected. If the state is SHOWING, newValue means isShowing.
References Dali::Accessibility::CHECKED, Dali::Accessibility::Bridge::GetCurrentBridge, Dali::Accessibility::Accessible::GetFeature, Dali::Accessibility::SELECTED, Dali::Accessibility::SHOWING, Dali::Accessibility::VISIBLE.
Referenced by EmitFocused, EmitHighlighted, EmitShowing, EmitVisible, NotifyAccessibilityStateChange.
void Dali::Accessibility::ActorAccessible::EmitBoundsChanged(Rect< int > rect)
Helper function for emiting bounds-changed event.
rect The rectangle for changed bounds
References Dali::Accessibility::Bridge::GetCurrentBridge, Dali::Accessibility::Accessible::GetFeature.
void Dali::Accessibility::ActorAccessible::EmitShowing(bool isShowing)
Emits "showing" event. The method informs accessibility clients about "showing" state.
isShowing The flag pointing if object is showing
References EmitStateChanged, Dali::Accessibility::Accessible::GetFeature, Dali::Accessibility::SHOWING.
void Dali::Accessibility::ActorAccessible::EmitVisible(bool isVisible)
Emits "visible" event. The method informs accessibility clients about "visible" state.
isVisible The flag pointing if object is visible
References EmitStateChanged, Dali::Accessibility::Accessible::GetFeature, Dali::Accessibility::VISIBLE.
void Dali::Accessibility::ActorAccessible::EmitHighlighted(bool isHighlighted)
Emits "highlighted" event. The method informs accessibility clients about "highlighted" state.
isHighlighted The flag pointing if object is highlighted
References EmitStateChanged, Dali::Accessibility::Accessible::GetFeature, Dali::Accessibility::HIGHLIGHTED.
void Dali::Accessibility::ActorAccessible::EmitFocused(bool isFocused)
Emits "focused" event. The method informs accessibility clients about "focused" state.
isFocused The flag pointing if object is focused
References EmitStateChanged, Dali::Accessibility::FOCUSED, Dali::Accessibility::Accessible::GetFeature.
void Dali::Accessibility::ActorAccessible::EmitTextInserted(unsigned int position, unsigned int length, const std::string &content)
Emits "text inserted" event.
position The cursor position length The text length content The inserted text
References Dali::Accessibility::Bridge::GetCurrentBridge, Dali::Accessibility::Accessible::GetFeature, Dali::Accessibility::INSERTED.
void Dali::Accessibility::ActorAccessible::EmitTextDeleted(unsigned int position, unsigned int length, const std::string &content)
Emits "text deleted" event.
position The cursor position length The text length content The deleted text
References Dali::Accessibility::DELETED, Dali::Accessibility::Bridge::GetCurrentBridge, Dali::Accessibility::Accessible::GetFeature.
void Dali::Accessibility::ActorAccessible::EmitTextCursorMoved(unsigned int cursorPosition)
Emits "cursor moved" event.
cursorPosition The new cursor position
References Dali::Accessibility::Bridge::GetCurrentBridge, Dali::Accessibility::Accessible::GetFeature.
void Dali::Accessibility::ActorAccessible::EmitMovedOutOfScreen(ScreenRelativeMoveType type)
Emits "MoveOuted" event.
type moved out of screen type
References Dali::Accessibility::Bridge::GetCurrentBridge, Dali::Accessibility::Accessible::GetFeature.
void Dali::Accessibility::ActorAccessible::EmitScrollStarted()
Emits "ScrollStarted" event.
References Dali::Accessibility::Bridge::GetCurrentBridge, Dali::Accessibility::Accessible::GetFeature.
void Dali::Accessibility::ActorAccessible::EmitScrollFinished()
Emits "ScrollFinished" event.
References Dali::Accessibility::Bridge::GetCurrentBridge, Dali::Accessibility::Accessible::GetFeature.
void Dali::Accessibility::ActorAccessible::Emit(WindowEvent event, unsigned int detail=0)
Emits "highlighted" event.
event The enumerated window event detail The additional parameter which interpretation depends on chosen event
References Dali::Accessibility::Bridge::GetCurrentBridge, Dali::Accessibility::Accessible::GetFeature.
void Dali::Accessibility::ActorAccessible::Emit(ObjectPropertyChangeEvent event)
Emits property-changed event.
event Property changed event
References Dali::Accessibility::Bridge::GetCurrentBridge, Dali::Accessibility::Accessible::GetFeature.
void Dali::Accessibility::ActorAccessible::NotifyAccessibilityStateChange(Dali::Accessibility::States states, bool isRecursive)
Re-emits selected states of an Accessibility Object.
states The chosen states to re-emit isRecursive If true, all children of the Accessibility object will also re-emit the states
References EmitStateChanged, GetChildren, Dali::Accessibility::Accessible::GetFeature, Dali::Accessibility::Accessible::GetStates, Dali::Accessibility::IsUp, Dali::Accessibility::MAX_COUNT.
void Dali::Accessibility::ActorAccessible::ClearCache()
Clears internal cache data on bridge down.
bool Dali::Accessibility::ActorAccessible::CanAcceptZeroSize() const
Checks if the accessible object can be accepted even with zero size.
References Dali::Accessibility::Accessible::GetFeature, Self.
Referenced by GetExtents.
void Dali::Accessibility::ActorAccessible::InitDefaultFeatures() override
Initializes default accessibility features.
This pure virtual function must be implemented by derived classes to initialize the default set of accessibility features for the specific accessible object type. This function is called during the initialization of the accessible object to set up the basic accessibility features that are always available.
References Dali::Accessibility::Accessible::GetFeature.
Dali::Actor Dali::Accessibility::ActorAccessible::Self() const
Referenced by CanAcceptZeroSize, DoGetChildren, GetExtents, GetInternalActor, GetName, GetParent.
void Dali::Accessibility::ActorAccessible::DoGetChildren(std::vector< Accessible * > &children)
Populates the collection of children of this Accessible.
The default implementation retrieves the children from the Actor hierarchy. Override this if you want to report other objects as children, either instead of, or together with the dependent Actor-derived Accessibles. Remember to call OnChildrenChanged() if you want your implementation of DoGetChildren() to be called again (in case your custom collection of children changes). children The initially empty vector to insert children into GetChildCound(), GetChildren() and GetChildAtIndex() are not available for overriding, but they respect the children collection reported by this method. OnChildrenChanged() GetChildCount() GetChildren() GetChildAtIndex()
References Dali::Accessibility::Accessible::Get, Dali::Accessibility::Accessible::GetFeature, Self.
void Dali::Accessibility::ActorAccessible::OnChildrenChanged(Dali::Actor)
void Dali::Accessibility::ActorAccessible::UpdateChildren()