Dali::Accessibility::BitSet
using Dali::Accessibility::BitSet< N >::ReferenceType = Internal::BitReference
Dali::Accessibility::Internal::BitReference.
using Dali::Accessibility::BitSet< N >::ElementType = ReferenceType::ElementType
Dali::Accessibility::Internal::BitReference::ElementType.
using Dali::Accessibility::BitSet< N >::IndexType = ReferenceType::IndexType
Dali::Accessibility::Internal::BitReference::IndexType.
using Dali::Accessibility::BitSet< N >::ArrayType = std::array<ElementType, N>
An array of N integers that can store 32*N bits.
ArrayType Dali::Accessibility::BitSet< N >::mData
Dali::Accessibility::BitSet< N >::BitSet()=default
Constructor.
Dali::Accessibility::BitSet< N >::BitSet(const BitSet &)=default
Dali::Accessibility::BitSet< N >::BitSet(BitSet &&) noexcept=default
Dali::Accessibility::BitSet< N >::BitSet(const ArrayType &array)
Constructs a new BitSet with all bits inialized with values from the specified array.
Equivalent to the pseudocode: for(i=0;i<max;++i)bits[i]=(array[i/32]>>(i%32))&0x1; array Array with the initial values.
Dali::Accessibility::BitSet< N >::BitSet(const std::array< std::int32_t, N > &array)
Constructs a new BitSet with all bits inialized with values from the specified array.
Equivalent to the pseudocode: for(i=0;i<max;++i)bits[i]=(array[i/32]>>(i%32))&0x1; array Array with the initial values.
Dali::Accessibility::BitSet< N >::BitSet(std::uint32_t data)
Constructs a new BitSet with all bits initialized with bits from the specified integer.
This constructor is only available for BitSets with 32-bit capacity. Equivalent to the pseudocode: for(i=0;i<32;++i)bits[i]=(data>>i)&0x1; data 32-bit integer with the initial values.
Dali::Accessibility::BitSet< N >::BitSet(std::uint64_t data)
Constructs a new BitSet with all bits initialized with bits from the specified integer.
This constructor is only available for BitSets with 64-bit capacity. Equivalent to the pseudocode: for(i=0;i<64;++i)bits[i]=(data>>i)&0x1; data 64-bit integer with the initial values.
Dali::Accessibility::BitSet< N >::~BitSet() noexcept=default
BitSet & Dali::Accessibility::BitSet< N >::operator=(const BitSet &)=default
BitSet & Dali::Accessibility::BitSet< N >::operator=(BitSet &&) noexcept=default
Dali::Accessibility::BitSet< N >::operator bool() const
Checks whether any bits are set to 1.
Equivalent to the pseudocode: for(i=0;i<max;++i) if(bits[i]==1) returntrue; returnfalse; true if at least one bit is set to 1, false otherwise.
bool Dali::Accessibility::BitSet< N >::operator==(const BitSet &other) const
Compares two bitsets for equality.
Equivalent to the pseudocode: for(i=0;i<max;++i) if(bits[i]!=other.bits[i]) returnfalse; returntrue; other The other operand. true if all bits in the two bitsets have the same values, false otherwise.
bool Dali::Accessibility::BitSet< N >::operator!=(const BitSet &other) const
Compares two bitsets for inequality.
other The other operand. false if all bits in the two bitsets have the same values, true otherwise. BitSet::operator==(const BitSet&)
BitSet Dali::Accessibility::BitSet< N >::operator~() const
Computes the bitwise NOT of this bitset.
Equivalent to the pseudocode: for(i=0;i<max;++i)result.bits[i]=~bits[i] Result of the bitwise NOT operation.
Referenced by Dali::Accessibility::EnumBitSet< Enum, EnumMax, N >::operator~.
BitSet Dali::Accessibility::BitSet< N >::operator|(const BitSet &other) const
Computes the bitwise OR of two bitsets.
Equivalent to the pseudocode: for(i=0;i<max;++i)result.bits[i]=bits[i]|other.bits[i]; other The other operand. Result of the bitwise OR operation.
Referenced by Dali::Accessibility::EnumBitSet< Enum, EnumMax, N >::operator|.
BitSet Dali::Accessibility::BitSet< N >::operator&(const BitSet &other) const
Computes the bitwise AND of two bitsets.
Equivalent to the pseudocode: for(i=0;i<max;++i)result.bits[i]=bits[i]&other.bits[i]; other The other operand. Result of the bitwise AND operation.
Referenced by Dali::Accessibility::EnumBitSet< Enum, EnumMax, N >::operator&.
BitSet Dali::Accessibility::BitSet< N >::operator^(const BitSet &other) const
Computes the bitwise XOR of two bitsets.
Equivalent to the pseudocode: for(i=0;i<max;++i)result.bits[i]=bits[i]^other.bits[i]; other The other operand. Result of the bitwise XOR operation.
Referenced by Dali::Accessibility::EnumBitSet< Enum, EnumMax, N >::operator^.
bool Dali::Accessibility::BitSet< N >::operator[](IndexType index) const
Queries the value of the specified bit.
This operator is used in expressions like boolb=bitset[i]; index Index of the bit to query. true if the specified bit is set to 1, false if it is set to 0.
Referenced by Dali::Accessibility::EnumBitSet< Enum, EnumMax, N >::operator[], Dali::Accessibility::EnumBitSet< Enum, EnumMax, N >::operator[].
ReferenceType Dali::Accessibility::BitSet< N >::operator[](IndexType index)
Obtains a writable reference to the specified bit.
This operator is used in expressions like bitset[i]=true; index Index of the bit to query. A writable reference to the specified bit. BitSet::ReferenceType
ArrayType Dali::Accessibility::BitSet< N >::GetRawData() const
Obtains a copy of the internal storage.
A copy of the internal storage. BitSet::ArrayType BitSet::BitSet(const ArrayType&)
std::uint32_t Dali::Accessibility::BitSet< N >::GetRawData32() const
Obtains a copy of the internal storage serialized as a single integer.
This method is only available for BitSets with 32-bit capacity. A copy of the internal storage. BitSet::BitSet(std::uint32_t)
std::uint64_t Dali::Accessibility::BitSet< N >::GetRawData64() const
Obtains a copy of the internal storage serialized as a single integer.
This method is only available for BitSets with 64-bit capacity. A copy of the internal storage. BitSet::BitSet(std::uint64_t)
BitSet Dali::Accessibility::BitSet< N >::ApplyBinaryOperator(const BitSet &other, BinaryOperator binaryOperator) const