Dali::Capture
FinishState
Succeeded in saving the result after capture.
typedef Signal<void(Capture, Capture::FinishState)> Dali::Capture::CaptureFinishedSignalType
Typedef for finished signals sent by this class.
@SINCE_1_3_4
Dali::Capture::Capture()
Create an uninitialized Capture; this can be initialized with Actor::New().
@SINCE_1_3_4 Calling member functions with an uninitialized Dali::Object is not allowed.
Referenced by DownCast, New, New.
Dali::Capture::~Capture()
Dali::Actor is intended as a base class.
@SINCE_1_3_4 This is non-virtual since derived Handle types must not contain data or virtual methods.
Dali::Capture::Capture(const Capture &copy)
This copy constructor is required for (smart) pointer semantics.
@SINCE_1_3_4 copy A reference to the copied handle.
Capture & Dali::Capture::operator=(const Capture &rhs)
This assignment operator is required for (smart) pointer semantics.
@SINCE_1_3_4 rhs A reference to the copied handle. A reference to this.
Dali::Capture::Capture(Capture &&rhs) noexcept
Move constructor.
@SINCE_1_9.24 rhs A reference to the moved handle
Capture & Dali::Capture::operator=(Capture &&rhs) noexcept
Move assignment operator.
@SINCE_1_9.24 rhs A reference to the moved handle A reference to this handle
void Dali::Capture::Start(Actor source, const Vector2 &position, const Vector2 &size, const Dali::String &path, const Vector4 &clearColor)
Start capture and save the image as a file.
@SINCE_1_9.27 source source actor to be used for capture. This source must be added on the window in advance. position top-left position of area to be captured this position is defined in the window. size captured size. path image file path to be saved as a file. If path is empty string, the captured result is not be saved as a file. clearColor background color of captured scene suppose that we want to capture actor 'A'. And, the actor 'A' is overlapped by another actor 'B' that is not a child of 'A'. in this case, if source is root of scene, the captured image includes a part of actor 'B' on the 'A'. however, if source is just actor 'A', the result includes only 'A'.
References Start.
Referenced by Start.
void Dali::Capture::Start(Actor source, const Vector2 &size, const Dali::String &path, const Vector4 &clearColor, const uint32_t quality)
Start capture and save the image as a file.
@SINCE_1_9.12 source source actor to be used for capture. This source must be added on the window in advance. size captured size. path image file path to be saved as a file. If path is empty string, the captured result is not be saved as a file. clearColor background color of captured scene quality The value to control image quality for jpeg file format in the range [1, 100]
void Dali::Capture::Start(Actor source, const Vector2 &size, const Dali::String &path, const Vector4 &clearColor)
Start capture and save the image as a file.
@SINCE_1_3_4 source source actor to be used for capture. This source must be added on the window in advance. size captured size. path image file path to be saved as a file. If path is empty string, the captured result is not be saved as a file. clearColor background color of captured scene
void Dali::Capture::Start(Actor source, const Vector2 &size, const Dali::String &path)
Start capture and save the image as a file.
@SINCE_1_3_4 source source actor to be used for capture. This source must be added on the window in advance. size captured size. path image file path to be saved as a file. If path is empty string, the captured result is not be saved as a file. Clear color is transparent.
void Dali::Capture::SetImageQuality(uint32_t quality)
Set result image quality in case of jpeg.
quality The value to control image quality for jpeg file format in the range [1, 100]
void Dali::Capture::SetExclusive(bool exclusive)
Sets whether the capture source should not be render on Screen or not. @SINCE_2_3.35.
exclusive True if the source actors will only be rendered by this capture result
bool Dali::Capture::IsExclusive() const
Queries whether the Capture is exclusive or not. @SINCE_2_3.35.
True if the source actors will only be rendered by this capture result
Dali::NativeImagePtr Dali::Capture::GetNativeImage()
Get NativeImagePtr that is saved captured image.
@SINCE_2_5.13 NativeImagePtr Captured result that can be rendered with DALi GetNativeImage is only available inside FinishedSignal.
Dali::Texture Dali::Capture::GetTexture() const
Get Texture of captured image.
Texture Captured result GetTexture is only available inside FinishedSignal.
Capture::CaptureFinishedSignalType & Dali::Capture::FinishedSignal()
Get finished signal.
@SINCE_1_3_4 finished signal instance.
Capture Dali::Capture::New()
Create an initialized Capture.
@SINCE_1_3_4 A handle to a newly allocated Dali resource. Projection mode of default cameraActor is Dali::Camera::PERSPECTIVE_PROJECTION
References Capture.
Capture Dali::Capture::New(Dali::CameraActor cameraActor)
Create an initialized Capture.
@SINCE_1_3_4 cameraActor An initialized CameraActor. A handle to a newly allocated Dali resource.
References Capture.
Capture Dali::Capture::DownCast(BaseHandle handle)
Downcast an Object handle to Capture handle.
@SINCE_1_3_4 If handle points to a Capture object the downcast produces valid handle. If not the returned handle is left uninitialized. handle to An object. handle to a Capture object or an uninitialized handle.
References Capture.