Dali::WindowData
UniquePtr<Impl> Dali::WindowData::mImpl
Dali::WindowData::WindowData()
Creates a WindowData object.
Dali::WindowData::~WindowData()
Destructor.
void Dali::WindowData::SetPositionSize(Dali::Rect< int > &positionSize)
Sets the position and size.
@SINCE_2_2.23 positionSize Position and Size
Referenced by Dali::Window::New.
Dali::Rect< int > Dali::WindowData::GetPositionSize() const
Gets the PositionSize.
@SINCE_2_2.23 The position and size
void Dali::WindowData::SetTransparency(bool transparent)
Sets the transparency.
@SINCE_2_2.23 transparent transparency
Referenced by Dali::Application::New, Dali::Window::New.
bool Dali::WindowData::GetTransparency() const
Gets the transparency.
@SINCE_2_2.23 whether transparency
void Dali::WindowData::SetWindowType(WindowType type)
Sets the window type.
@SINCE_2_2.23 type the window type
Referenced by Dali::Window::New.
WindowType Dali::WindowData::GetWindowType() const
Gets the window type.
@SINCE_2_2.23 the window type
void Dali::WindowData::SetFrontBufferRendering(bool enable)
Sets the front buffer rendering.
@SINCE_2_2.51 enable whether to use front buffer rendering
bool Dali::WindowData::GetFrontBufferRendering() const
Gets the front buffer rendering.
@SINCE_2_2.51 whether front buffer rendering is enabled
void Dali::WindowData::SetScreen(const Dali::String &screen)
Sets the screen for the window It is base information from DevelWindowSystem::GetAvailableScreens.
This method sets the window to the specified screen. The window will be moved to the specified screen. @SINCE_2_4.35 screen The name of the screen to set
Dali::String Dali::WindowData::GetScreen() const
Gets the screen.
@SINCE_2_4.35 screen name