Dali::Internal::Adaptor::SceneHolder
uint32_t Dali::Internal::Adaptor::SceneHolder::mSceneHolderCounter
A counter to track the SceneHolder creation.
std::unique_ptr<SceneHolderLifeCycleObserver> Dali::Internal::Adaptor::SceneHolder::mLifeCycleObserver
The adaptor life cycle observer.
Dali::TouchEvent Dali::Internal::Adaptor::SceneHolder::mLastTouchEvent
Dali::HoverEvent Dali::Internal::Adaptor::SceneHolder::mLastHoverEvent
Dali::Integration::SceneHolder::FocusChangedGeneratedSignalType Dali::Internal::Adaptor::SceneHolder::mFocusChangedGeneratedSignal
uint32_t Dali::Internal::Adaptor::SceneHolder::mId
A unique ID to identify the SceneHolder starting from 0.
Referenced by GetId.
Dali::Integration::Scene Dali::Internal::Adaptor::SceneHolder::mScene
The Scene.
Referenced by Add, AddFramePresentedCallback, AddFrameRenderedCallback, CreateRenderTarget, FeedHoverEvent, FeedKeyEvent, FeedMouseFrameEvent, FeedTouchPoint, FeedWheelEvent, GetBackgroundColor, GetLastPanGestureState, GetNativeId, GetOverlayLayer, GetRenderTaskList, GetRootLayer, GetScene, IsGeometryHittestEnabled, Remove, RequestFullUpdate, Reset, SetAdaptor, SetForceRendering, SetGeometryHittestEnabled, SetRotationCompletedAcknowledgement, SetSurface, SurfaceResized, SurfaceRotated, ~SceneHolder.
std::string Dali::Internal::Adaptor::SceneHolder::mName
The name of the SceneHolder.
Referenced by GetName.
std::unique_ptr<Dali::Integration::RenderSurfaceInterface> Dali::Internal::Adaptor::SceneHolder::mSurface
The window rendering surface.
Referenced by CreateRenderTarget, GetSurface, SetAdaptor, SetSurface, SurfaceResized, ~SceneHolder.
Adaptor* Dali::Internal::Adaptor::SceneHolder::mAdaptor
The adaptor.
Referenced by FeedHoverEvent, FeedKeyEvent, FeedMouseFrameEvent, FeedTouchPoint, FeedWheelEvent, Reset, SetAdaptor, SetSurface, ~SceneHolder.
Dali::Integration::TouchEventCombiner Dali::Internal::Adaptor::SceneHolder::mCombiner
Combines multi-touch events.
Referenced by FeedTouchPoint, Reset.
Uint16Pair Dali::Internal::Adaptor::SceneHolder::mDpi
The DPI for this SceneHolder.
Referenced by GetDpi.
bool Dali::Internal::Adaptor::SceneHolder::mAdaptorStarted
Whether the adaptor has started or not.
Referenced by FeedHoverEvent, FeedKeyEvent, FeedMouseFrameEvent, FeedTouchPoint, FeedWheelEvent, GetLastPanGestureState, Reset, SetAdaptor, ~SceneHolder.
bool Dali::Internal::Adaptor::SceneHolder::mVisible
Whether the scene is visible or not.
Referenced by IsVisible.
bool Dali::Internal::Adaptor::SceneHolder::mHandledMultiTouch
Referenced by FeedMouseFrameEvent, FeedTouchPoint, Reset.
Integration::TouchEvent Dali::Internal::Adaptor::SceneHolder::mPreviousTouchEvent
Referenced by FeedMouseFrameEvent, FeedTouchPoint.
Integration::HoverEvent Dali::Internal::Adaptor::SceneHolder::mPreviousHoverEvent
Referenced by FeedMouseFrameEvent, FeedTouchPoint.
Integration::TouchEventCombiner::EventDispatchType Dali::Internal::Adaptor::SceneHolder::mPreviousType
Referenced by FeedMouseFrameEvent, FeedTouchPoint, Reset.
void Dali::Internal::Adaptor::SceneHolder::Add(Dali::Actor actor)
Adds a child Actor to the SceneHolder.
The child will be referenced. actor The child The actor has been initialized. The actor does not have a parent.
References mScene.
Referenced by Dali::Integration::SceneHolder::Add, Dali::Window::Add.
void Dali::Internal::Adaptor::SceneHolder::Remove(Dali::Actor actor)
Removes a child Actor from the SceneHolder.
The child will be unreferenced. actor The child The actor has been added to the SceneHolder.
References mScene.
Referenced by Dali::Integration::SceneHolder::Remove, Dali::Window::Remove.
Dali::Layer Dali::Internal::Adaptor::SceneHolder::GetRootLayer() const
Returns the Scene's Root Layer.
The root layer
References mScene.
Referenced by Dali::Integration::SceneHolder::GetRootLayer, Dali::Window::GetRootLayer.
Dali::Layer Dali::Internal::Adaptor::SceneHolder::GetOverlayLayer()
References mScene.
Referenced by Dali::Window::GetOverlayLayer.
std::string Dali::Internal::Adaptor::SceneHolder::GetName() const
Gets the window name.
The name of the window
References mName.
uint32_t Dali::Internal::Adaptor::SceneHolder::GetId() const
Retrieve the unique ID of the window.
The ID
References mId.
Dali::Integration::Scene Dali::Internal::Adaptor::SceneHolder::GetScene()
Retrieve the Scene.
The Scene
References mScene.
Uint16Pair Dali::Internal::Adaptor::SceneHolder::GetDpi() const
Retrieves the DPI of this sceneholder.
The DPI.
References mDpi.
Referenced by Dali::Window::GetDpi, Dali::TextAbstraction::FontClient::GetDpi.
void Dali::Internal::Adaptor::SceneHolder::SetSurface(Dali::Integration::RenderSurfaceInterface *surface)
Set the render surface.
surface The render surface
References CreateRenderTarget, Dali::Integration::RenderSurfaceInterface::GetPositionSize, mAdaptor, mScene, mSurface, SurfaceResized.
void Dali::Internal::Adaptor::SceneHolder::SurfaceResized(float width, float height)
Called when the surface set is resized.
width the resized window's width height the resized window's height
References CreateRenderTarget, mScene, mSurface.
Referenced by SetSurface.
Dali::Integration::RenderSurfaceInterface * Dali::Internal::Adaptor::SceneHolder::GetSurface() const
Get the render surface.
The render surface
References mSurface.
void Dali::Internal::Adaptor::SceneHolder::SetAdaptor(Dali::Adaptor &adaptor)
Set the adaptor to the scene holder.
adaptor An initialized adaptor
References CreateRenderTarget, mAdaptor, mAdaptorStarted, mScene, mSurface.
void Dali::Internal::Adaptor::SceneHolder::SetBackgroundColor(const Dali::Vector4 &color)
Sets the background color.
color The new background color
Referenced by Dali::Window::SetBackgroundColor, Dali::Integration::SceneHolder::SetBackgroundColor.
Vector4 Dali::Internal::Adaptor::SceneHolder::GetBackgroundColor() const
Gets the background color.
The background color
References mScene.
Referenced by Dali::Integration::SceneHolder::GetBackgroundColor, Dali::Window::GetBackgroundColor.
void Dali::Internal::Adaptor::SceneHolder::RequestFullUpdate()
Request to scene full update next render time.
References mScene.
Referenced by Resume.
void Dali::Internal::Adaptor::SceneHolder::SetForceRendering(uint32_t frameCount)
Requests forced rendering for this scene holder.
frameCount The number of frames to rendering forcibly.
References mScene.
Referenced by Dali::DevelWindow::SetForceRendering.
void Dali::Internal::Adaptor::SceneHolder::Pause()
Pause the rendering of the scene holder.
References Reset.
Referenced by Dali::TtsPlayer::Pause, Dali::VideoPlayer::Pause.
void Dali::Internal::Adaptor::SceneHolder::Resume()
Resume the rendering of the scene holder (from pause).
References RequestFullUpdate, Reset.
Referenced by Dali::TtsPlayer::Resume, Dali::WebEngine::Resume.
void Dali::Internal::Adaptor::SceneHolder::SurfaceRotated(float width, float height, int32_t windowOrientation, int32_t screenOrientation)
Informs the scene that the set surface has been rotated.
width The width of rotated surface height The height of rotated surface windowOrientation the current window orientation screenOrientation the current screen orientation
References mScene.
void Dali::Internal::Adaptor::SceneHolder::SetRotationCompletedAcknowledgement()
Send message to acknowledge window rotation with current window orientation. It is to send message to render thread for completing window rotation by user.
References mScene.
void Dali::Internal::Adaptor::SceneHolder::FeedTouchPoint(Dali::Integration::Point &point, int timeStamp)
Feed (Send) touch event to core.
point The touch point timeStamp The time stamp
References mAdaptor, mAdaptorStarted, mCombiner, mHandledMultiTouch, mPreviousHoverEvent, mPreviousTouchEvent, mPreviousType, mScene.
Referenced by Dali::Integration::SceneHolder::FeedTouchPoint, Dali::DevelWindow::FeedTouchPoint.
void Dali::Internal::Adaptor::SceneHolder::FeedMouseFrameEvent()
References mAdaptor, mAdaptorStarted, mHandledMultiTouch, mPreviousHoverEvent, mPreviousTouchEvent, mPreviousType, mScene.
const Dali::TouchEvent & Dali::Internal::Adaptor::SceneHolder::GetLastTouchEvent() const
Get the Last Touch Event.
Dali::TouchEvent
Referenced by Dali::DevelWindow::GetLastTouchEvent.
const Dali::HoverEvent & Dali::Internal::Adaptor::SceneHolder::GetLastHoverEvent() const
Get the Last Hover Event.
Dali::HoverEvent
Referenced by Dali::DevelWindow::GetLastHoverEvent.
Dali::GestureState Dali::Internal::Adaptor::SceneHolder::GetLastPanGestureState()
Gets the last pan gesture state.
Dali::GestureState
References mAdaptorStarted, mScene.
Referenced by Dali::DevelWindow::GetLastPanGestureState.
void Dali::Internal::Adaptor::SceneHolder::FeedWheelEvent(Dali::Integration::WheelEvent &wheelEvent)
Feed (Send) wheel event to core.
wheelEvent The wheel event
References mAdaptor, mAdaptorStarted, mScene.
Referenced by Dali::Integration::SceneHolder::FeedWheelEvent, Dali::DevelWindow::FeedWheelEvent.
void Dali::Internal::Adaptor::SceneHolder::FeedKeyEvent(Dali::Integration::KeyEvent &keyEvent)
Feed (Send) key event to core.
keyEvent The key event holding the key information.
References Dali::PhysicalKeyboard::Get, Dali::Internal::Adaptor::GetImplementation, mAdaptor, mAdaptorStarted, mScene.
Referenced by Dali::Integration::SceneHolder::FeedKeyEvent, Dali::DevelWindow::FeedKeyEvent.
void Dali::Internal::Adaptor::SceneHolder::FeedHoverEvent(Dali::Integration::Point &point)
Feed (Send) hover event to core.
point The touch point that create a hover event
References mAdaptor, mAdaptorStarted, mScene.
Referenced by Dali::Integration::SceneHolder::FeedHoverEvent, Dali::DevelWindow::FeedHoverEvent.
void Dali::Internal::Adaptor::SceneHolder::SetGeometryHittestEnabled(bool enabled)
Sets whether the processes using geometry event propagation touch and hover events.
enabled True if the processes using geometry event propagation touch and hover events.
References mScene.
Referenced by Dali::Integration::SceneHolder::SetGeometryHittestEnabled.
bool Dali::Internal::Adaptor::SceneHolder::IsGeometryHittestEnabled()
Queries whether the scene using geometry event propagation touch and hover events.
True if the scene using geometry event propagation touch and hover events.
References mScene.
Referenced by Dali::Integration::SceneHolder::IsGeometryHittestEnabled.
int32_t Dali::Internal::Adaptor::SceneHolder::GetNativeId() const
Gets the native window id.
The native window id
References mScene.
Referenced by Dali::Integration::SceneHolder::GetNativeId, Dali::DevelWindow::GetNativeId.
void Dali::Internal::Adaptor::SceneHolder::AddFrameRenderedCallback(std::unique_ptr< CallbackBase > callback, int32_t frameId)
Adds a callback that is called when the frame rendering is done by the graphics driver.
callback The function to call frameId The Id to specify the frame. It will be passed when the callback is called. A callback of the following type may be used: voidMyFunction(intframeId); This callback will be deleted once it is called. Ownership of the callback is passed onto this class.
References mScene.
Referenced by Dali::DevelWindow::AddFrameRenderedCallback.
void Dali::Internal::Adaptor::SceneHolder::AddFramePresentedCallback(std::unique_ptr< CallbackBase > callback, int32_t frameId)
Adds a callback that is called when the frame rendering is done by the graphics driver.
callback The function to call frameId The Id to specify the frame. It will be passed when the callback is called. A callback of the following type may be used: voidMyFunction(intframeId); This callback will be deleted once it is called. Ownership of the callback is passed onto this class.
References mScene.
Referenced by Dali::DevelWindow::AddFramePresentedCallback.
void Dali::Internal::Adaptor::SceneHolder::CreateRenderTarget()
Creates the render target for the surface when the surface is created/resized/replaced.
References mScene, mSurface.
Referenced by SetAdaptor, SetSurface, SurfaceResized.
Dali::RenderTaskList Dali::Internal::Adaptor::SceneHolder::GetRenderTaskList() const
Retrieves the list of render-tasks.
A valid handle to a RenderTaskList
References mScene.
Referenced by Dali::Integration::SceneHolder::GetRenderTaskList, Dali::Window::GetRenderTaskList.
Dali::Integration::SceneHolder::KeyEventSignalType & Dali::Internal::Adaptor::SceneHolder::KeyEventSignal()
This signal is emitted when key event is received.
A callback of the following type may be connected: voidYourCallbackName(constKeyEvent&event); The signal to connect to
Referenced by Dali::Integration::SceneHolder::KeyEventSignal, Dali::Window::KeyEventSignal.
Dali::Integration::SceneHolder::KeyEventGeneratedSignalType & Dali::Internal::Adaptor::SceneHolder::KeyEventGeneratedSignal()
This signal is emitted when key event is received.
A callback of the following type may be connected: boolYourCallbackName(constKeyEvent&event); The signal to connect to
Referenced by Dali::Integration::SceneHolder::KeyEventGeneratedSignal.
Dali::Integration::SceneHolder::KeyEventGeneratedSignalType & Dali::Internal::Adaptor::SceneHolder::InterceptKeyEventSignal()
This signal is emitted when key event is received. Intercepts KeyEvents in the window before dispatching KeyEvents to the control. If a KeyEvent is consumed, no KeyEvent is delivered to the control.
A callback of the following type may be connected: boolYourCallbackName(constKeyEvent&event); The signal to connect to
Referenced by Dali::Integration::SceneHolder::InterceptKeyEventSignal, Dali::DevelWindow::InterceptKeyEventSignal.
Dali::Integration::SceneHolder::KeyEventSignalType & Dali::Internal::Adaptor::SceneHolder::KeyEventMonitorSignal()
This signal is emitted when key event is received.
A callback of the following type may be connected: voidYourCallbackName(constKeyEvent&event); The signal to connect to
Referenced by Dali::Integration::SceneHolder::KeyEventMonitorSignal, Dali::DevelWindow::KeyEventMonitorSignal.
Dali::Integration::SceneHolder::TouchEventSignalType & Dali::Internal::Adaptor::SceneHolder::TouchedSignal()
This signal is emitted when the screen is touched and when the touch ends (i.e. the down & up touch events only).
If there are multiple touch points, then this will be emitted when the first touch occurs and then when the last finger is lifted. An interrupted event will also be emitted (if it occurs). A callback of the following type may be connected: voidYourCallbackName(TouchEventevent); The touch signal to connect to Motion events are not emitted.
Referenced by Dali::Integration::SceneHolder::TouchedSignal, Dali::Window::TouchedSignal.
Dali::Integration::SceneHolder::WheelEventSignalType & Dali::Internal::Adaptor::SceneHolder::WheelEventSignal()
This signal is emitted when wheel event is received.
A callback of the following type may be connected: voidYourCallbackName(constWheelEvent&event); The signal to connect to
Referenced by Dali::Integration::SceneHolder::WheelEventSignal, Dali::DevelWindow::WheelEventSignal.
Dali::Integration::SceneHolder::WheelEventGeneratedSignalType & Dali::Internal::Adaptor::SceneHolder::WheelEventGeneratedSignal()
This signal is emitted to KeyboardFocusManager when a custom wheel type event is received. When a custom wheel event occurs, it need to process the focused actor first.
Therefore, KeyboardFocusManager first checks whether WheelEvent is generated as WheelEventGeneratedSignal. This is only valid for custom wheel events. A callback of the following type may be connected: boolYourCallbackName(constWheelEvent&event); The signal to connect to
Referenced by Dali::Integration::SceneHolder::WheelEventGeneratedSignal.
Dali::Integration::SceneHolder::FocusChangedGeneratedSignalType & Dali::Internal::Adaptor::SceneHolder::FocusChangedGeneratedSignal()
This signal is emitted when the window focus changes.
Although there is already a focus change signal in the window, it has been added to the scene-holder to ensure that the keyboardFocusManager processes the focus change signal after all window focus change signals have been handled. A callback of the following type may be connected: voidYourCallbackName(Dali::Integration::SceneHoldersceneHolder,boolfocusIn); The signal to connect to
Referenced by Dali::Integration::SceneHolder::FocusChangedGeneratedSignal.
void Dali::Internal::Adaptor::SceneHolder::FocusChanged(bool focusIn)
bool Dali::Internal::Adaptor::SceneHolder::IsVisible() const
Returns whether the Scene is visible or not.
True if the Scene is visible, false otherwise.
References mVisible.
Referenced by Dali::Clipboard::IsVisible, Dali::Window::IsVisible.
virtual Dali::Any Dali::Internal::Adaptor::SceneHolder::GetNativeHandle() const =0
Gets the native handle.
When users call this function, it wraps the actual type used by the underlying system. The native handle or an empty handle
Referenced by Dali::Integration::SceneHolder::GetNativeHandle, Dali::Window::GetNativeHandle.
Dali::Integration::SceneHolder Dali::Internal::Adaptor::SceneHolder::Get(Dali::Actor actor)
Retrieve the SceneHolder that the given actor is added to.
actor The actor The SceneHolder the actor is added to or an empty handle if the actor is not added to any SceneHolder.
Referenced by Dali::Integration::SceneHolder::Get.
Dali::Internal::Adaptor::SceneHolder::SceneHolder()
Dali::Internal::Adaptor::SceneHolder::SceneHolder(const SceneHolder &)=delete
SceneHolder & Dali::Internal::Adaptor::SceneHolder::operator=(const SceneHolder &rhs)=delete
Dali::Internal::Adaptor::SceneHolder::~SceneHolder() override
virtual destructor
References mAdaptor, mAdaptorStarted, mScene, mSurface.
void Dali::Internal::Adaptor::SceneHolder::Reset()
Resets the event handling.
References mAdaptor, mAdaptorStarted, mCombiner, mHandledMultiTouch, mPreviousType, mScene.
Referenced by Pause, Resume.
virtual void Dali::Internal::Adaptor::SceneHolder::OnAdaptorSet(Dali::Adaptor &adaptor)
Called by the base class to inform deriving classes that the adaptor has been set.
adaptor The adaptor
virtual void Dali::Internal::Adaptor::SceneHolder::OnSurfaceSet(Dali::Integration::RenderSurfaceInterface *surface)
Called by the base class to inform deriving classes that a new surface has been set.
surface The new render surface
virtual void Dali::Internal::Adaptor::SceneHolder::OnPause()
Called by the base class to inform deriving classes that we are being paused.
virtual void Dali::Internal::Adaptor::SceneHolder::OnResume()
Called by the base class to inform deriving classes that we are resuming from a paused state.
virtual Vector2 Dali::Internal::Adaptor::SceneHolder::RecalculatePosition(const Vector2 &position)
Recalculate the position if required position The screen position converted position by oriention
void Dali::Internal::Adaptor::SceneHolder::InitializeDpi()
Initializes the DPI for this object.