Dali::Window
using Dali::Window::WindowSize = Uint16Pair
Window size type @SINCE_1_2.60.
using Dali::Window::WindowPosition = Int32Pair
Window position type @SINCE_2_1.45.
using Dali::Window::FocusChangeSignalType = Signal<void(Window, bool)>
Window focus signal type @SINCE_1_4.35.
using Dali::Window::ResizeSignalType = Signal<void(Window, WindowSize)>
Window resized signal type @SINCE_1_4.35.
using Dali::Window::KeyEventSignalType = Signal<void(const KeyEvent&)>
Key event signal type @SINCE_1_9.21.
using Dali::Window::TouchEventSignalType = Signal<void(const TouchEvent&)>
Touch signal type @SINCE_1_9.28.
Window Dali::Window::New(PositionSize windowPosition, const Dali::String &name, bool isTransparent=false)
Creates an initialized handle to a new Window. @SINCE_1_0.0.
windowPosition The position and size of the Window name The Window title isTransparent Whether Window is transparent A new window This creates an extra window in addition to the default main window
References New, Dali::NORMAL, Dali::WindowData::SetPositionSize, Dali::WindowData::SetTransparency, Dali::WindowData::SetWindowType.
Referenced by New.
Window Dali::Window::New(const Dali::String &name, const Dali::String &className, const WindowData &windowData)
Creates an initialized handle to a new Window. @SINCE_2_2.33.
name The Window title className The Window class name windowData The window data This creates an extra window in addition to the default main window A new Window
References Dali::Adaptor::IsAvailable, Window.
Window Dali::Window::DownCast(BaseHandle handle)
Downcast sceneHolder to window.
@SINCE_2_1.46 handle The handle need to downcast Whether it's a valid window or not
References Window.
Dali::Window::Window()
Creates an uninitialized handle.
This can be initialized using Dali::Application::GetWindow() or Dali::Window::New(). @SINCE_1_0.0
Referenced by DownCast, New.
Dali::Window::~Window()
Destructor.
This is non-virtual since derived Handle types must not contain data or virtual methods. @SINCE_1_0.0
Dali::Window::Window(const Window &handle)
This copy constructor is required for (smart) pointer semantics.
@SINCE_1_0.0 handle A reference to the copied handle
Window & Dali::Window::operator=(const Window &rhs)
This assignment operator is required for (smart) pointer semantics.
@SINCE_1_0.0 rhs A reference to the copied handle A reference to this
Dali::Window::Window(Window &&rhs) noexcept
Move constructor.
@SINCE_1_9.24 rhs A reference to the moved handle
Window & Dali::Window::operator=(Window &&rhs) noexcept
Move assignment operator.
@SINCE_1_9.24 rhs A reference to the moved handle A reference to this handle
void Dali::Window::Add(Actor actor)
Adds a child Actor to the Window.
The child will be referenced. @SINCE_1_4.19 actor The child The actor has been initialized. The actor does not have a parent.
References Dali::Internal::Adaptor::SceneHolder::Add, Dali::GetImplementation.
void Dali::Window::Remove(Actor actor)
Removes a child Actor from the Window.
The child will be unreferenced. @SINCE_1_4.19 actor The child The actor has been added to the stage.
References Dali::GetImplementation, Dali::Internal::Adaptor::SceneHolder::Remove.
void Dali::Window::SetBackgroundColor(const Vector4 &color)
Sets the background color of the Window.
@SINCE_1_4.19 color The new background color If this window is transparent, the color is converted premultiplied alpha format internally.
References Dali::GetImplementation, Dali::Internal::Adaptor::SceneHolder::SetBackgroundColor.
Vector4 Dali::Window::GetBackgroundColor() const
Gets the background color of the Window.
@SINCE_1_4.19 The background color
References Dali::Internal::Adaptor::SceneHolder::GetBackgroundColor, Dali::GetImplementation.
Layer Dali::Window::GetRootLayer() const
Returns the root Layer of the Window.
@SINCE_1_4.19 The root layer
References Dali::GetImplementation, Dali::Internal::Adaptor::SceneHolder::GetRootLayer.
Layer Dali::Window::GetOverlayLayer()
Returns the overlay Layer of the Window. If there isn't overlay layer yet, this method create overlay layer and exclusive render task internally.
@SINCE_2_2.10 The root layer
References Dali::GetImplementation, Dali::Internal::Adaptor::SceneHolder::GetOverlayLayer.
uint32_t Dali::Window::GetLayerCount() const
Queries the number of on-scene layers in the Window.
Note that a default layer is always provided (count >= 1). @SINCE_1_4.19 The number of layers
References Dali::GetImplementation.
Layer Dali::Window::GetLayer(uint32_t depth) const
Retrieves the layer at a specified depth in the Window.
@SINCE_1_4.19 depth The depth The layer found at the given depth Depth is less than layer count; see GetLayerCount().
References Dali::GetImplementation.
Uint16Pair Dali::Window::GetDpi() const
Retrieves the DPI of the window.
@SINCE_1_9.21 The DPI of the window
References Dali::Internal::Adaptor::SceneHolder::GetDpi, Dali::GetImplementation.
void Dali::Window::SetClass(Dali::String name, Dali::String klass)
Sets the window name and class string. @SINCE_1_0.0.
name The name of the window klass The class of the window
References Dali::GetImplementation.
void Dali::Window::Raise()
Raises window to the top of Window stack. @SINCE_1_0.0.
References Dali::GetImplementation.
void Dali::Window::Lower()
Lowers window to the bottom of Window stack. @SINCE_1_0.0.
References Dali::GetImplementation.
void Dali::Window::Activate()
Activates window to the top of Window stack even it is iconified. @SINCE_1_0.0.
References Dali::GetImplementation.
void Dali::Window::AddAvailableOrientation(WindowOrientation orientation)
Adds an orientation to the list of available orientations. @SINCE_1_0.0.
orientation The available orientation to add
References Dali::GetImplementation.
void Dali::Window::RemoveAvailableOrientation(WindowOrientation orientation)
Removes an orientation from the list of available orientations. @SINCE_1_0.0.
orientation The available orientation to remove
References Dali::GetImplementation.
void Dali::Window::SetPreferredOrientation(WindowOrientation orientation)
Sets a preferred orientation. @SINCE_1_0.0.
orientation The preferred orientation Orientation is in the list of available orientations. To unset the preferred orientation, orientation should be set NO_ORIENTATION_PREFERENCE.
References Dali::GetImplementation.
WindowOrientation Dali::Window::GetPreferredOrientation()
Gets the preferred orientation. @SINCE_1_0.0.
The preferred orientation if previously set, or none
References Dali::GetImplementation.
Any Dali::Window::GetNativeHandle() const
Gets the native handle of the window.
When users call this function, it wraps the actual type used by the underlying window system. @SINCE_1_0.0 The native handle of the Window or an empty handle
References Dali::GetImplementation, Dali::Internal::Adaptor::SceneHolder::GetNativeHandle.
void Dali::Window::SetAcceptFocus(bool accept)
Sets whether window accepts focus or not.
@SINCE_1_2.60 accept If focus is accepted or not. Default is true.
References Dali::GetImplementation.
bool Dali::Window::IsFocusAcceptable() const
Returns whether window accepts focus or not.
@SINCE_1_2.60 True if the window accept focus, false otherwise
References Dali::GetImplementation.
void Dali::Window::Show()
Shows the window if it is hidden. @SINCE_1_2.60.
References Dali::GetImplementation.
void Dali::Window::Hide()
Hides the window if it is showing. @SINCE_1_2.60.
References Dali::GetImplementation.
bool Dali::Window::IsVisible() const
Returns whether the window is visible or not. @SINCE_1_2.60.
True if the window is visible, false otherwise.
References Dali::GetImplementation, Dali::Internal::Adaptor::SceneHolder::IsVisible.
unsigned int Dali::Window::GetSupportedAuxiliaryHintCount() const
Gets the count of supported auxiliary hints of the window. @SINCE_1_2.60.
The number of supported auxiliary hints. The window auxiliary hint is the value which is used to decide which actions should be made available to the user by the window manager. If you want to set specific hint to your window, then you should check whether it exists in the supported auxiliary hints.
References Dali::GetImplementation.
Dali::String Dali::Window::GetSupportedAuxiliaryHint(unsigned int index) const
Gets the supported auxiliary hint string of the window. @SINCE_1_2.60.
index The index of the supported auxiliary hint lists The auxiliary hint string of the index. The window auxiliary hint is the value which is used to decide which actions should be made available to the user by the window manager. If you want to set specific hint to your window, then you should check whether it exists in the supported auxiliary hints.
References Dali::GetImplementation.
unsigned int Dali::Window::AddAuxiliaryHint(const Dali::String &hint, const Dali::String &value)
Creates an auxiliary hint of the window. @SINCE_1_2.60.
hint The auxiliary hint string. value The value string. The ID of created auxiliary hint, or 0 on failure.
References Dali::GetImplementation.
bool Dali::Window::RemoveAuxiliaryHint(unsigned int id)
Removes an auxiliary hint of the window. @SINCE_1_2.60.
id The ID of the auxiliary hint. True if no error occurred, false otherwise.
References Dali::GetImplementation.
bool Dali::Window::SetAuxiliaryHintValue(unsigned int id, const Dali::String &value)
Changes a value of the auxiliary hint. @SINCE_1_2.60.
id The auxiliary hint ID. value The value string to be set. True if no error occurred, false otherwise.
References Dali::GetImplementation.
Dali::String Dali::Window::GetAuxiliaryHintValue(unsigned int id) const
Gets a value of the auxiliary hint. @SINCE_1_2.60.
id The auxiliary hint ID. The string value of the auxiliary hint ID, or an empty string if none exists.
References Dali::GetImplementation.
unsigned int Dali::Window::GetAuxiliaryHintId(const Dali::String &hint) const
Gets a ID of the auxiliary hint string. @SINCE_1_2.60.
hint The auxiliary hint string. The ID of the auxiliary hint string, or 0 if none exists.
References Dali::GetImplementation.
void Dali::Window::SetInputRegion(const Rect< int > &inputRegion)
Sets a region to accept input events. @SINCE_1_2.60.
inputRegion The region to accept input events.
References Dali::GetImplementation.
void Dali::Window::SetType(WindowType type)
Sets a window type. @SINCE_2_0.0.
type The window type. The default window type is NORMAL.
References Dali::GetImplementation.
WindowType Dali::Window::GetType() const
Gets a window type. @SINCE_2_0.0.
A window type.
References Dali::GetImplementation.
WindowOperationResult Dali::Window::SetNotificationLevel(WindowNotificationLevel level)
Sets a priority level for the specified notification window. @SINCE_2_0.0.
level The notification window level. The result of the window operation. @PRIVLEVEL_PUBLIC @PRIVILEGE_WINDOW_PRIORITY This can be used for a notification type window only. The default level is NotificationLevel::NONE.
References Dali::GetImplementation.
WindowNotificationLevel Dali::Window::GetNotificationLevel() const
Gets a priority level for the specified notification window. @SINCE_2_0.0.
The notification window level. This can be used for a notification type window only.
References Dali::GetImplementation.
void Dali::Window::SetOpaqueState(bool opaque)
Sets a transparent window's visual state to opaque.
If a visual state of a transparent window is opaque, then the window manager could handle it as an opaque window when calculating visibility. @SINCE_1_2.60 opaque Whether the window's visual state is opaque. This will have no effect on an opaque window. It doesn't change transparent window to opaque window but lets the window manager know the visual state of the window.
References Dali::GetImplementation.
bool Dali::Window::IsOpaqueState() const
Returns whether a transparent window's visual state is opaque or not. @SINCE_1_2.60.
True if the window's visual state is opaque, false otherwise. The return value has no meaning on an opaque window.
References Dali::GetImplementation.
WindowOperationResult Dali::Window::SetScreenOffMode(WindowScreenOffMode screenOffMode)
Sets a window's screen off mode.
This API is useful when the application needs to keep the display turned on. If the application sets the screen mode to #Dali::WindowScreenOffMode::NEVER to its window and the window is shown, the window manager requests the display system to keep the display on as long as the window is shown. If the window is no longer shown, then the window manager requests the display system to go back to normal operation. @SINCE_2_0.0 screenOffMode The screen mode. The result of the window operation. @PRIVLEVEL_PUBLIC @PRIVILEGE_DISPLAY
References Dali::GetImplementation.
WindowScreenOffMode Dali::Window::GetScreenOffMode() const
Gets a screen off mode of the window. @SINCE_2_0.0.
The screen off mode.
References Dali::GetImplementation.
WindowOperationResult Dali::Window::SetBrightness(int brightness)
Sets preferred brightness of the window.
This API is useful when the application needs to change the brightness of the screen when it is appeared on the screen. If the brightness has been set and the window is shown, the window manager requests the display system to change the brightness to the provided value. If the window is no longer shown, then the window manager requests the display system to go back to default brightness. A value less than 0 results in default brightness and a value greater than 100 results in maximum brightness. @SINCE_1_2.60 brightness The preferred brightness (0 to 100). The result of the window operation. @PRIVLEVEL_PUBLIC @PRIVILEGE_DISPLAY
References Dali::GetImplementation.
int Dali::Window::GetBrightness() const
Gets preferred brightness of the window. @SINCE_1_2.60.
The preferred brightness.
References Dali::GetImplementation.
void Dali::Window::SetSize(WindowSize size)
Sets a size of the window.
@SINCE_1_2.60 size The new window size
References Dali::GetImplementation.
Window::WindowSize Dali::Window::GetSize() const
Gets a size of the window.
@SINCE_1_2.60 The size of the window
References Dali::GetImplementation.
void Dali::Window::SetPosition(WindowPosition position)
Sets a position of the window.
@SINCE_1_2.60 position The new window position
References Dali::GetImplementation.
Dali::Window::WindowPosition Dali::Window::GetPosition() const
Gets a position of the window.
@SINCE_1_2.60 The position of the window
References Dali::GetImplementation.
void Dali::Window::SetLayout(unsigned int numCols, unsigned int numRows, unsigned int column, unsigned int row, unsigned int colSpan, unsigned int rowSpan)
Sets the layout of the window.
This method sets the layout of the window based on the specified number of columns and rows, as well as the position and size of the window within that layout. numCols The number of columns in the layout. numRows The number of rows in the layout. column The column number of the window within the layout. row The row number of the window within the layout. colSpan The number of columns the window should span within the layout. rowSpan The number of rows the window should span within the layout. @SINCE_2_2.20
References Dali::GetImplementation.
void Dali::Window::SetTransparency(bool transparent)
Sets whether the window is transparent or not.
@SINCE_1_2.60 transparent Whether the window is transparent
References Dali::GetImplementation.
Dali::RenderTaskList Dali::Window::GetRenderTaskList()
Retrieves the list of render-tasks in the window.
@SINCE_1_9.21 A valid handle to a RenderTaskList
References Dali::GetImplementation, Dali::Internal::Adaptor::SceneHolder::GetRenderTaskList.
void Dali::Window::KeepRendering(float durationSeconds)
Keeps rendering for at least the given amount of time.
By default, Dali will stop rendering when no Actor positions are being set, and when no animations are running etc. This method is useful to force screen refreshes. @SINCE_2_2.29 durationSeconds Time to keep rendering, 0 means render at least one more frame
References Dali::GetImplementation.
void Dali::Window::SetPartialUpdateEnabled(bool enabled)
Sets whether the window will update partial area or full area.
@SINCE_2_2.33 enabled True if the window should update partial area This doesn't change the global value which is set by the environment variable. This works when partial update is enabled by the environment variable. If the partial update is disabled by the environment variable, it changes nothing.
References Dali::GetImplementation.
bool Dali::Window::IsPartialUpdateEnabled() const
Queries whether the window will update partial area.
@SINCE_2_2.33 True if the window should update partial area
References Dali::GetImplementation.
Window::FocusChangeSignalType & Dali::Window::FocusChangeSignal()
The user should connect to this signal to get a timing when window gains focus or loses focus.
A callback of the following type may be connected: voidYourCallbackName(Windowwindow,boolfocusIn); The parameter is true if window gains focus, otherwise false. and window means this signal was called from what window @SINCE_1_4.35 The signal to connect to
References Dali::GetImplementation.
Window::ResizeSignalType & Dali::Window::ResizeSignal()
This signal is emitted when the window is resized.
A callback of the following type may be connected: voidYourCallbackName(Windowwindow,intwidth,intheight); The parameters are the resized width and height. and window means this signal was called from what window @SINCE_1_4.35 The signal to connect to
References Dali::GetImplementation.
Window::KeyEventSignalType & Dali::Window::KeyEventSignal()
This signal is emitted when key event is received.
A callback of the following type may be connected: voidYourCallbackName(constKeyEvent&event); @SINCE_1_9.21 The signal to connect to
References Dali::GetImplementation, Dali::Internal::Adaptor::SceneHolder::KeyEventSignal.
Window::TouchEventSignalType & Dali::Window::TouchedSignal()
This signal is emitted when the screen is touched and when the touch ends (i.e. the down & up touch events only).
If there are multiple touch points, then this will be emitted when the first touch occurs and then when the last finger is lifted. An interrupted event will also be emitted (if it occurs). A callback of the following type may be connected: voidYourCallbackName(constTouchEvent&event); @SINCE_1_9.28 The touch signal to connect to Motion events are not emitted.
References Dali::GetImplementation, Dali::Internal::Adaptor::SceneHolder::TouchedSignal.