Dali::Adaptor
typedef Signal<void(Adaptor&)> Dali::Adaptor::AdaptorSignalType
Generic Type for adaptor signals.
typedef Signal<void(Dali::Integration::SceneHolder&)> Dali::Adaptor::WindowCreatedSignalType
SceneHolder created signal type.
typedef Signal<void(std::string)> Dali::Adaptor::LocaleChangedSignalType
Locale changed signal type.
using Dali::Adaptor::SurfaceSize = Uint16Pair
Surface size type.
Internal::Adaptor::Adaptor* Dali::Adaptor::mImpl
Implementation object.
friend class Internal::Adaptor::Adaptor
static Adaptor & Dali::Adaptor::New(Window window)
Create a new adaptor using the window.
window The window to draw onto a reference to the adaptor handle
static Adaptor & Dali::Adaptor::New(Window window, const Dali::Integration::RenderSurfaceInterface &surface)
Create a new adaptor using render surface.
window The window to draw onto surface The surface to draw onto a reference to the adaptor handle
static Adaptor & Dali::Adaptor::New(Dali::Integration::SceneHolder sceneHolder)
Create a new adaptor using the SceneHolder.
sceneHolder The SceneHolder to draw onto a reference to the adaptor handle
static Adaptor & Dali::Adaptor::New(Dali::Integration::SceneHolder sceneHolder, const Dali::Integration::RenderSurfaceInterface &surface)
Create a new adaptor using render surface.
sceneHolder The SceneHolder to draw onto surface The surface to draw onto a reference to the adaptor handle
static Adaptor & Dali::Adaptor::Get()
Returns a reference to the instance of the adaptor used by the current thread.
A reference to the adaptor. The adaptor has been initialised. This is only valid in the main thread.
Referenced by Dali::EventFeeder::FeedKeyEvent, Dali::EventFeeder::FeedTouchPoint, Dali::EventFeeder::FeedWheelEvent, Dali::TtsPlayer::Get, Dali::GraphicsCapabilities::GetMaxCombinedTextureUnits.
static bool Dali::Adaptor::IsAvailable()
Checks whether the adaptor is available.
true, if it is available, false otherwise.
Referenced by Dali::DevelApplication::CustomCommandReceivedSignal, Dali::EventFeeder::FeedKeyEvent, Dali::EventFeeder::FeedTouchPoint, Dali::EventFeeder::FeedWheelEvent, Dali::TtsPlayer::Get, Dali::OffscreenWindow::New, Dali::Window::New.
virtual Dali::Adaptor::~Adaptor()
Virtual Destructor.
void Dali::Adaptor::Start()
Starts the Adaptor.
void Dali::Adaptor::Pause()
Pauses the Adaptor.
void Dali::Adaptor::Resume()
Resumes the Adaptor, if previously paused.
If the adaptor is not paused, this does not do anything.
void Dali::Adaptor::Stop()
Stops the Adaptor.
bool Dali::Adaptor::AddIdle(CallbackBase *callback, bool hasReturnValue)
Ensures that the function passed in is called from the main loop when it is idle.
Function must be called from the main event thread only. Callbacks of the following types may be used: voidMyFunction(); This callback will be deleted once it is called. boolMyFunction(); This callback will be called repeatedly as long as it returns true. A return of 0 deletes this callback. callback The function to call. hasReturnValue Sould be set to true if the callback function has a return value. true if added successfully, false otherwise Ownership of the callback is passed onto this class.
bool Dali::Adaptor::AddWindow(Dali::Integration::SceneHolder childWindow)
Adds a new Window instance to the Adaptor.
childWindow The child window instance
void Dali::Adaptor::RemoveIdle(CallbackBase *callback)
Removes a previously added callback.
Function must be called from the main event thread only. Does nothing if the callback doesn't exist. callback The callback to be removed.
void Dali::Adaptor::ProcessIdle()
Processes the idle callbacks.
This function is intended to be used in the case there is no instance of a Dali::Application i.e. DALi is used in a implementation of a plugin of an application.
void Dali::Adaptor::ReplaceSurface(Window window, Dali::Integration::RenderSurfaceInterface &surface)
Replaces the rendering surface.
window The window to replace the surface for surface to use
void Dali::Adaptor::ReplaceSurface(Dali::Integration::SceneHolder sceneHolder, Dali::Integration::RenderSurfaceInterface &surface)
Replaces the rendering surface.
sceneHolder The SceneHolder to replace the surface for surface to use
Dali::Integration::RenderSurfaceInterface & Dali::Adaptor::GetSurface()
Get the render surface the adaptor is using to render to.
reference to current render surface
Any Dali::Adaptor::GetNativeWindowHandle()
Gets native window handle.
Native window handle
Any Dali::Adaptor::GetNativeWindowHandle(Actor actor)
Retrieve native window handle that the given actor is added to.
actor The actor native window handle
Any Dali::Adaptor::GetGraphicsDisplay()
Get the native display associated with the graphics backend.
A handle to the native display
void Dali::Adaptor::ReleaseSurfaceLock()
Release any locks the surface may hold.
For example, after compositing an offscreen surface, use this method to allow rendering to continue.
void Dali::Adaptor::SetRenderRefreshRate(unsigned int numberOfVSyncsPerRender)
Set the number of frames per render.
This enables an application to deliberately render with a reduced FPS. numberOfVSyncsPerRender The number of vsyncs between successive renders. Suggest this is a power of two: 1 - render each vsync frame 2 - render every other vsync frame 4 - render every fourth vsync frame 8 - render every eighth vsync frame
void Dali::Adaptor::SetMaximumRenderFrameRate(float maximumRenderFrameRate)
Set the maximum value of frames per seconds.
Each frame will render multiple of given maximum render frame rate. For example, if maximumRenderFrameRate = 50.0f, each elapse time could be 20ms, 40ms, 60ms, and so on. maximumRenderFrameRate The maximum fps for this adaptor system.
void Dali::Adaptor::SetPreRenderCallback(CallbackBase *callback)
The callback is called from the Update/Render thread prior to rendering.
callback The function to call The function is called from the Update thread, so should do as little processing as possible. It is not possible to call any DALi event side APIs from within the callback; doing so will cause instability. Only 1 callback is supported. Setting the callback to NULL will remove the current callback. A callback of the following type should be used: boolMyFunction(); This callback will be called repeatedly as long as it returns true. A return of 0 deletes this callback.
void Dali::Adaptor::NotifySceneCreated()
Call this method to notify Dali when scene is created and initialized.
Notify Adaptor that the scene has been created.
void Dali::Adaptor::NotifyLanguageChanged(const std::string &language)
Call this method to notify Dali when the system language changes.
Use this only when NOT using Dali::Application, As Application created using Dali::Application will automatically receive notification of language change. When Dali::Application is not used, the application developer should use app-core to receive language change notifications and should update Dali by calling this method.
void Dali::Adaptor::FeedTouchPoint(TouchPoint &point, int timeStamp)
Feed a touch point to the adaptor.
point touch point timeStamp time value of event
void Dali::Adaptor::FeedWheelEvent(WheelEvent &wheelEvent)
Feed a wheel event to the adaptor.
wheelEvent wheel event
void Dali::Adaptor::FeedKeyEvent(KeyEvent &keyEvent)
Feed a key event to the adaptor.
keyEvent The key event holding the key information.
void Dali::Adaptor::SceneCreated()
void Dali::Adaptor::SurfaceResizePrepare(Dali::Integration::RenderSurfaceInterface *surface, SurfaceSize surfaceSize)
Informs core the surface size has changed.
surface The current render surface surfaceSize The new surface size
void Dali::Adaptor::SurfaceResizeComplete(Dali::Integration::RenderSurfaceInterface *surface, SurfaceSize surfaceSize)
Informs ThreadController the surface size has changed.
surface The current render surface surfaceSize The new surface size
void Dali::Adaptor::UpdateOnce()
Update once. It will not wake up the update thread if we're paused.
Will not work if the window is hidden.
void Dali::Adaptor::RenderOnce()
Renders once more even if we're paused.
void Dali::Adaptor::FlushUpdateMessages()
Relayout and ensure all pending operations are flushed to the update thread.
void Dali::Adaptor::RequestProcessEventsOnIdle()
Requests a future call to Dali::Integration::Core::ProcessEvents(), when the application is idle.
const LogFactoryInterface & Dali::Adaptor::GetLogFactory()
The log factory allows installation of a logger function in worker threads.
An interface to a logging factory
const TraceFactoryInterface & Dali::Adaptor::GetTraceFactory()
The trace factory allows installation of a trace function in worker threads.
An interface to a tracing factory
void Dali::Adaptor::RegisterProcessor(Integration::Processor &processor, bool postProcessor=false)
Register a processor implementing the Integration::Processor interface with dali-core.
processor the Processor to register postProcessor set this processor required to be called after size negotiation. Default is false. using this api does not maintain the processor's lifecycle, must be done elsewhere.
void Dali::Adaptor::UnregisterProcessor(Integration::Processor &processor, bool postProcessor=false)
Unregister a previously registered processor from dali-core.
processor the Processor to unregister postProcessor True if the processor to be unregister is for post processor.
void Dali::Adaptor::RegisterProcessorOnce(Integration::Processor &processor, bool postProcessor=false)
Register a processor implementing the Integration::Processor interface with dali-core.
processor the Processor to register postProcessor set this processor required to be called after size negotiation. Default is false. registered processor will be unregistered automatically after process.
void Dali::Adaptor::UnregisterProcessorOnce(Integration::Processor &processor, bool postProcessor=false)
Unregister a previously registered once processor from dali-core.
processor the Processor to unregister postProcessor True if the processor to be unregister is for post processor.
Dali::WindowContainer Dali::Adaptor::GetWindows() const
Get the list of windows created.
The list of windows
SceneHolderList Dali::Adaptor::GetSceneHolders() const
Get the list of scene holders.
The list of scene holers
Dali::ObjectRegistry Dali::Adaptor::GetObjectRegistry() const
Gets the Object registry.
The object registry
void Dali::Adaptor::OnWindowShown()
Called when the window becomes fully or partially visible.
void Dali::Adaptor::OnWindowHidden()
Called when the window is fully hidden.
int32_t Dali::Adaptor::GetRenderThreadId() const
Gets the render thread ID of DALi.
The render thread ID. Returns a valid thread ID only if the render thread has started and the system supports thread ID retrieval. Otherwise, returns 0.
int32_t Dali::Adaptor::GetUiThreadId() const
Gets the UI thread ID of DALi.
The UI thread ID. Returns a valid thread ID only if the adaptor has been initialized and the system supports thread ID retrieval. Otherwise, returns 0.
int32_t Dali::Adaptor::GetMainThreadId() const
Gets the main thread ID of DALi.
The main thread ID. Returns a valid thread ID only if the system supports thread ID retrieval. Otherwise, returns 0.
AdaptorSignalType & Dali::Adaptor::ResizedSignal()
The user should connect to this signal if they need to perform any special activities when the surface Dali is being rendered on is resized.
The signal to connect to
AdaptorSignalType & Dali::Adaptor::LanguageChangedSignal()
This signal is emitted when the language is changed on the device.
The signal to connect to
WindowCreatedSignalType & Dali::Adaptor::WindowCreatedSignal()
This signal is emitted when a new window (scene holder) is created.
The signal to connect to
LocaleChangedSignalType & Dali::Adaptor::LocaleChangedSignal()
This signal is emitted when the system locale is changed.
The signal to connect to
Dali::Adaptor::Adaptor(const Adaptor &)
Adaptor & Dali::Adaptor::operator=(Adaptor &)
Dali::Adaptor::Adaptor()
Create an uninitialized Adaptor.