Dali::InputMethodContext
TextDirection
EventType
No event.
State
Unknown state.
KeyboardType
Software keyboard (Virtual keyboard) is default.
InputPanelLanguage
IME Language automatically set depending on the system display.
InputPanelAlign
The top-left corner.
PreeditStyle
None style.
typedef Signal<void(InputMethodContext&)> Dali::InputMethodContext::ActivatedSignalType
Keyboard actived signal.
typedef Signal<CallbackData(InputMethodContext&, const EventData&)> Dali::InputMethodContext::KeyboardEventSignalType
keyboard events
typedef Signal<void()> Dali::InputMethodContext::VoidSignalType
typedef Signal<void(bool)> Dali::InputMethodContext::StatusSignalType
typedef Signal<void(KeyboardType)> Dali::InputMethodContext::KeyboardTypeSignalType
keyboard type
typedef Signal<void(int)> Dali::InputMethodContext::KeyboardResizedSignalType
Keyboard resized signal.
typedef Signal<void(int)> Dali::InputMethodContext::LanguageChangedSignalType
Language changed signal.
typedef Signal<void(const std::string&, const std::string&, const std::string&)> Dali::InputMethodContext::ContentReceivedSignalType
Content received signal.
using Dali::InputMethodContext::PreEditAttributeDataContainer = Vector<Dali::InputMethodContext::PreeditAttributeData>
Dali::InputMethodContext::InputMethodContext()
Constructor.
Referenced by DownCast, New.
Dali::InputMethodContext::~InputMethodContext()
Destructor.
This is non-virtual since derived Handle types must not contain data or virtual methods.
Dali::InputMethodContext::InputMethodContext(const InputMethodContext &inputMethodContext)
Copy constructor.
inputMethodContext InputMethodContext to copy. The copied inputMethodContext will point at the same implementation.
InputMethodContext & Dali::InputMethodContext::operator=(const InputMethodContext &inputMethodContext)
Assignment operator.
inputMethodContext The InputMethodContext to assign from. The updated InputMethodContext.
void Dali::InputMethodContext::Finalize()
Finalize the InputMethodContext.
It means that the context will be deleted.
void Dali::InputMethodContext::Activate()
Activate the InputMethodContext.
It means that the text editing is started at somewhere. If the H/W keyboard isn't connected then it will show the virtual keyboard.
void Dali::InputMethodContext::Deactivate()
Deactivate the InputMethodContext.
It means that the text editing is finished at somewhere.
bool Dali::InputMethodContext::RestoreAfterFocusLost() const
Get the restoration status, which controls if the keyboard is restored after the focus lost then regained.
If true then keyboard will be restored (activated) after focus is regained. restoration status.
void Dali::InputMethodContext::SetRestoreAfterFocusLost(bool toggle)
Set status whether the InputMethodContext has to restore the keyboard after losing focus.
toggle True means that keyboard should be restored after focus lost and regained.
void Dali::InputMethodContext::Reset()
Send message reset the pred-edit state / InputMethodContext module.
Used to interupt pre-edit state maybe due to a touch input.
void Dali::InputMethodContext::NotifyCursorPosition()
Notifies InputMethodContext that the cursor position has changed, required for features like auto-capitalisation.
void Dali::InputMethodContext::SetCursorPosition(unsigned int cursorPosition)
Sets cursor position stored in VirtualKeyboard, this is required by the InputMethodContext.
cursorPosition position of cursor
References SetCursorPosition.
Referenced by SetCursorPosition.
unsigned int Dali::InputMethodContext::GetCursorPosition() const
Gets cursor position stored in VirtualKeyboard, this is required by the InputMethodContext.
current position of cursor
void Dali::InputMethodContext::SetSurroundingText(const std::string &text)
Method to store the string required by the InputMethodContext, this is used to provide predictive word suggestions.
text The text string surrounding the current cursor point.
const std::string & Dali::InputMethodContext::GetSurroundingText() const
Gets current text string set within the InputMethodContext, this is used to offer predictive suggestions.
current position of cursor
void Dali::InputMethodContext::NotifyTextInputMultiLine(bool multiLine)
Notifies InputMethodContext that text input is set to multi line or not.
multiLine True if multiline text input is used
InputMethodContext::TextDirection Dali::InputMethodContext::GetTextDirection()
Returns text direction of the keyboard's current input language.
The direction of the text.
Rect< int > Dali::InputMethodContext::GetInputMethodArea()
Provides size and position of keyboard.
Position is relative to whether keyboard is visible or not. If keyboard is not visible then position will be off the screen. If keyboard is not being shown when this method is called the keyboard is partially setup (IMFContext) to get the values then taken down. So ideally GetInputMethodArea() should be called after Show(). rect which is keyboard panel x, y, width, height
void Dali::InputMethodContext::ApplyOptions(const InputMethodOptions &options)
Set one or more of the Input Method options.
options The options to be applied
void Dali::InputMethodContext::SetInputPanelData(const std::string &data)
Sets up the input-panel specific data.
data The specific data to be set to the input panel
void Dali::InputMethodContext::GetInputPanelData(std::string &data)
Gets the specific data of the current active input panel.
Input Panel Data is not always the data which is set by SetInputPanelData(). Data can be changed internally in the input panel. It is just used to get a specific data from the input panel to an application. data The specific data to be got from the input panel
Dali::InputMethodContext::State Dali::InputMethodContext::GetInputPanelState()
Gets the state of the current active input panel.
The state of the input panel.
void Dali::InputMethodContext::SetReturnKeyState(bool visible)
Sets the return key on the input panel to be visible or invisible.
The default is true. visible True if the return key is visible(enabled), false otherwise.
void Dali::InputMethodContext::AutoEnableInputPanel(bool enabled)
Enable to show the input panel automatically when focused.
enabled If true, the input panel will be shown when focused
void Dali::InputMethodContext::ShowInputPanel()
Shows the input panel.
void Dali::InputMethodContext::HideInputPanel()
Hides the input panel.
Dali::InputMethodContext::KeyboardType Dali::InputMethodContext::GetKeyboardType()
Gets the keyboard type.
The default keyboard type is SOFTWARE_KEYBOARD. The keyboard type
std::string Dali::InputMethodContext::GetInputPanelLocale()
Gets the current language locale of the input panel.
ex) en_US, en_GB, en_PH, fr_FR, ... The current language locale of the input panel
void Dali::InputMethodContext::SetContentMIMETypes(const std::string &mimeTypes)
Sets the allowed MIME Types to deliver to the input panel.
ex) std::string mimeTypes = "text/plain,image/png,image/gif,application/pdf"; You can receive a media content URI and its MIME type from ContentReceivedSignal(). ContentReceivedSignal mimeTypes The allowed MIME types
bool Dali::InputMethodContext::FilterEventKey(const Dali::KeyEvent &keyEvent)
Process event key down or up, whether filter a key to isf.
keyEvent The event key to be handled. Whether the event key is handled.
void Dali::InputMethodContext::AllowTextPrediction(bool prediction)
Sets whether the IM context should allow to use the text prediction.
prediction Whether to allow text prediction or not.
bool Dali::InputMethodContext::IsTextPredictionAllowed() const
Gets whether the IM context allow to use the text prediction.
Whether the IM allow text prediction or not.
void Dali::InputMethodContext::SetFullScreenMode(bool fullScreen)
Sets whether the IM context should be shown in fullscreen mode.
fullScreen Whether to fullscreen mode or not.
bool Dali::InputMethodContext::IsFullScreenMode() const
Gets whether the IM context should be shown in fullscreen mode.
Whether the IM fullscreen mode or not.
void Dali::InputMethodContext::SetInputPanelLanguage(InputPanelLanguage language)
Sets the language of the input panel.
This method can be used when you want to show the English keyboard. language The language to be set to the input panel
Dali::InputMethodContext::InputPanelLanguage Dali::InputMethodContext::GetInputPanelLanguage() const
Gets the language of the input panel.
The language of the input panel
void Dali::InputMethodContext::SetInputPanelPosition(unsigned int x, unsigned int y)
Sets the x,y coordinates of the input panel.
x The top-left x coordinate of the input panel y The top-left y coordinate of the input panel
bool Dali::InputMethodContext::SetInputPanelPositionAlign(int x, int y, InputPanelAlign align)
Sets the alignment and its x, y coordinates of the input panel.
Regardless of the rotation degree, the x, y values of the top-left corner on the screen are based on 0, 0. When the IME size is changed, its size will change according to the set alignment. x The x coordinate of the InputPanelAlign value. y The y coordinate of the InputPanelAlign value. align one of the InputPanelAlign values specifying the desired alignment. true on success, false otherwise. This API can be used to set the alignment of a floating IME.
void Dali::InputMethodContext::GetPreeditStyle(PreEditAttributeDataContainer &attrs) const
Gets the preedit attributes data.
attrs The preedit attributes data.
InputMethodContext::ActivatedSignalType & Dali::InputMethodContext::ActivatedSignal()
This is emitted when the virtual keyboard is connected to or the hardware keyboard is activated.
The InputMethodContext Activated signal.
InputMethodContext::KeyboardEventSignalType & Dali::InputMethodContext::EventReceivedSignal()
This is emitted when the InputMethodContext receives an event from the InputMethodContext.
This signal is the same as KeyboardEventReceivedSignal(). This signal is bound to dali-csharp-binder and can be used in external apps. The Event signal containing the event data.
InputMethodContext::KeyboardEventSignalType & Dali::InputMethodContext::KeyboardEventReceivedSignal()
This is emitted when the InputMethodContext receives an event from the InputMethodContext.
This signal is the same as EventReceivedSignal(). This signal is only used by dali. The EventReceivedSignal combines different kinds of events triggered by the IMF into a single signal, which it then emits. These events often happen during text entry through S/W keyboard and Applications depend on this signal to perform various actions. There exists a situation where further emissions take place inside the emitted signal. Unfortunately, these events are already exposed publicly and cannot be segregated separately. As a workaround, we keep the original signal intact but separate signals meant exclusively for usage within dali. The Event signal containing the event data.
InputMethodContext::StatusSignalType & Dali::InputMethodContext::StatusChangedSignal()
Connect to this signal to be notified when the virtual keyboard is shown or hidden.
A callback of the following type may be connected: voidYourCallbackName(boolkeyboardShown); If the parameter keyboardShown is true, then the keyboard has just shown, if it is false, then it has just been hidden. The signal to connect to.
InputMethodContext::KeyboardResizedSignalType & Dali::InputMethodContext::ResizedSignal()
Connect to this signal to be notified when the virtual keyboard is resized.
A callback of the following type may be connected: voidYourCallbackName(intresolvedResize); The parameter sends the resolved resize defined by the InputMethodContext. User can get changed size by using GetInputMethodArea() in the callback The signal to connect to.
InputMethodContext::LanguageChangedSignalType & Dali::InputMethodContext::LanguageChangedSignal()
Connect to this signal to be notified when the virtual keyboard's language is changed.
A callback of the following type may be connected: voidYourCallbackName(intresolvedLanguage); The parameter sends the resolved language defined by the InputMethodContext. User can get the text direction of the language by calling GetTextDirection() in the callback. The signal to connect to.
InputMethodContext::KeyboardTypeSignalType & Dali::InputMethodContext::KeyboardTypeChangedSignal()
Connect to this signal to be notified when the keyboard type is changed.
A callback of the following type may be connected: voidYourCallbackName(KeyboardTypekeyboard); The signal to connect to.
InputMethodContext::ContentReceivedSignalType & Dali::InputMethodContext::ContentReceivedSignal()
Connect to this signal to be notified when the content, such as images, of input method is received.
A callback of the following type may be connected: voidYourCallbackName(conststd::string&contentUri,conststd::string&description,conststd::string&contentMIMEType); The signal to connect to.
Dali::InputMethodContext::InputMethodContext(Internal::Adaptor::InputMethodContext *inputMethodContext)
This constructor is used by InputMethodContext::New().
inputMethodContext A pointer to the InputMethodContext.
InputMethodContext Dali::InputMethodContext::New()
Create a new instance of an InputMethodContext.
References New.
Referenced by New.
InputMethodContext Dali::InputMethodContext::New(Actor actor)
Create a new instance of an InputMethodContext.
actor The actor that uses the new InputMethodContext instance.
References InputMethodContext.
InputMethodContext Dali::InputMethodContext::DownCast(BaseHandle handle)
Downcast a handle to InputMethodContext handle.
If handle points to an InputMethodContext the downcast produces valid handle. If not the returned handle is left uninitialized. handle Handle to an object. Handle to an InputMethodContext or an uninitialized handle.
References InputMethodContext.