Dali::EncodedImageBuffer
ImageType
using Dali::EncodedImageBuffer::RawBufferType = Dali::Vector<uint8_t>
EncodedImageBuffer Dali::EncodedImageBuffer::New(const RawBufferType &buffer)
Create a new EncodedImageBuffer. ImageType will be setted as DEFAULT.
@SINCE_2_0.34 buffer The encoded raw buffer A handle to a new EncodedImageBuffer.
References DEFAULT, New.
Referenced by New, New.
EncodedImageBuffer Dali::EncodedImageBuffer::New(RawBufferType &&buffer)
Create a new EncodedImageBuffer. ImageType will be setted as DEFAULT.
@SINCE_2_0.34 buffer The encoded raw buffer as moved A handle to a new EncodedImageBuffer.
References DEFAULT, New.
EncodedImageBuffer Dali::EncodedImageBuffer::New(const RawBufferType &buffer, ImageType type)
Create a new EncodedImageBuffer with ImageType.
@SINCE_2_2.51 buffer The encoded raw buffer type The type hint of encoded raw buffer A handle to a new EncodedImageBuffer.
References EncodedImageBuffer.
EncodedImageBuffer Dali::EncodedImageBuffer::New(RawBufferType &&buffer, ImageType type)
Create a new EncodedImageBuffer with ImageType.
@SINCE_2_2.51 buffer The encoded raw buffer as moved type The type hint of encoded raw buffer A handle to a new EncodedImageBuffer.
References EncodedImageBuffer.
Dali::EncodedImageBuffer::EncodedImageBuffer()
Create an empty handle.
@SINCE_2_0.34 Calling member functions of an empty handle is not allowed.
Referenced by New, New.
Dali::EncodedImageBuffer::~EncodedImageBuffer()
Destructor.
This is non-virtual since derived Handle types must not contain data or virtual methods. @SINCE_2_0.34
Dali::EncodedImageBuffer::EncodedImageBuffer(const EncodedImageBuffer &handle)
This copy constructor is required for (smart) pointer semantics.
@SINCE_2_0.34 handle A reference to the copied handle
EncodedImageBuffer & Dali::EncodedImageBuffer::operator=(const EncodedImageBuffer &handle)
This assignment operator is required for (smart) pointer semantics.
@SINCE_2_0.34 handle A reference to the copied handle A reference to this
Dali::EncodedImageBuffer::EncodedImageBuffer(EncodedImageBuffer &&handle) noexcept
This move constructor is required for (smart) pointer semantics.
@SINCE_2_0.34 handle A reference to the moved handle
EncodedImageBuffer & Dali::EncodedImageBuffer::operator=(EncodedImageBuffer &&handle) noexcept
This move assignment operator is required for (smart) pointer semantics.
@SINCE_2_0.34 handle A reference to the moved handle A reference to this
const EncodedImageBuffer::RawBufferType & Dali::EncodedImageBuffer::GetRawBuffer() const
Get raw buffer data.
@SINCE_2_0.34 this method return const value. Mean, you cannot change raw buffer A RawBufferType this buffer have
References Dali::GetImplementation.
std::size_t Dali::EncodedImageBuffer::GetHash() const
Get the hash value of raw buffer.
@SINCE_2_1.20 A hash value of raw buffer.
References Dali::GetImplementation.
void Dali::EncodedImageBuffer::SetImageType(ImageType type)
Set type of raw buffer.
@SINCE_2_2.51 type A ImageType for this buffer
References Dali::GetImplementation.
EncodedImageBuffer::ImageType Dali::EncodedImageBuffer::GetImageType() const
Get type of raw buffer.
@SINCE_2_2.51 A ImageType this buffer have
References Dali::GetImplementation.
Dali::EncodedImageBuffer::EncodedImageBuffer(Internal::EncodedImageBuffer *impl)