Dali::TextAbstraction::FontClient
const PointSize26Dot6 Dali::TextAbstraction::FontClient::DEFAULT_POINT_SIZE
The default point size.
const float Dali::TextAbstraction::FontClient::DEFAULT_ITALIC_ANGLE
The default software italic angle in radians.
Referenced by Dali::TextAbstraction::TransformToArc.
const bool Dali::TextAbstraction::FontClient::DEFAULT_ATLAS_LIMITATION_ENABLED
The default behavior of whether atlas limitation is enabled in dali.
const uint32_t Dali::TextAbstraction::FontClient::DEFAULT_TEXT_ATLAS_WIDTH
The default width of text-atlas-block.
const uint32_t Dali::TextAbstraction::FontClient::DEFAULT_TEXT_ATLAS_HEIGHT
The default height of text-atlas-block.
const Size Dali::TextAbstraction::FontClient::DEFAULT_TEXT_ATLAS_SIZE
The default size(width, height) of text-atlas-block.
const uint32_t Dali::TextAbstraction::FontClient::MAX_TEXT_ATLAS_WIDTH
The maximum width of text-atlas-block.
const uint32_t Dali::TextAbstraction::FontClient::MAX_TEXT_ATLAS_HEIGHT
The maximum height of text-atlas-block.
const Size Dali::TextAbstraction::FontClient::MAX_TEXT_ATLAS_SIZE
The maximum height of text-atlas-block.
const uint16_t Dali::TextAbstraction::FontClient::PADDING_TEXT_ATLAS_BLOCK
Padding per edge. How much the block size (width, height) less than the text-atlas-block size (width, height).
const Size Dali::TextAbstraction::FontClient::MAX_SIZE_FIT_IN_ATLAS
The maximum block's size fit into text-atlas-block.
const uint32_t Dali::TextAbstraction::FontClient::NUMBER_OF_POINTS_PER_ONE_UNIT_OF_POINT_SIZE
Factor multiply point-size in toolkit.
uint32_t Dali::TextAbstraction::FontClient::GetPerformanceLogThresholdTime()
Return performance log threshold time in miliseconds for debug.
References Dali::EnvironmentVariable::GetEnvironmentVariable, Dali::TextAbstraction::TEXT_PERFORMANCE_LOG_SET, Dali::TextAbstraction::TEXT_PERFORMANCE_LOG_THRESHOLD_TIME, Dali::TextAbstraction::TEXT_PERFORMANCE_LOG_THRESHOLD_TIME_ENV.
Referenced by IsPerformanceLogEnabled.
bool Dali::TextAbstraction::FontClient::IsPerformanceLogEnabled()
Whether performance log is enabled.
References GetPerformanceLogThresholdTime.
FontClient Dali::TextAbstraction::FontClient::Get()
Retrieve a handle to the FontClient instance.
A handle to the FontClient A reference to the singleton instance of FontClient.
FontClient Dali::TextAbstraction::FontClient::New()
Create a handle to the new FontClient instance.
A handle to the FontClient All functions of this are not thread-safe, so create new handles for each worker thread to utilize them.
References FontClient.
FontClient Dali::TextAbstraction::FontClient::New(uint32_t horizontalDpi, uint32_t verticalDpi)
Create a handle to the new FontClient instance.
horizontalDpi The horizontal resolution in DPI. verticalDpi The vertical resolution in DPI. A handle to the FontClient All functions of this are not thread-safe, so create new handles for each worker thread to utilize them.
References FontClient.
Dali::TextAbstraction::FontClient::FontClient()
Create an uninitialized TextAbstraction handle.
Referenced by New, New.
Dali::TextAbstraction::FontClient::~FontClient()
Destructor.
This is non-virtual since derived Handle types must not contain data or virtual methods.
Dali::TextAbstraction::FontClient::FontClient(const FontClient &handle)
This copy constructor is required for (smart) pointer semantics.
handle A reference to the copied handle.
FontClient & Dali::TextAbstraction::FontClient::operator=(const FontClient &handle)
This assignment operator is required for (smart) pointer semantics.
handle A reference to the copied handle. A reference to this.
Dali::TextAbstraction::FontClient::FontClient(FontClient &&handle) noexcept
This move constructor is required for (smart) pointer semantics.
handle A reference to the moved handle.
FontClient & Dali::TextAbstraction::FontClient::operator=(FontClient &&handle) noexcept
This move assignment operator is required for (smart) pointer semantics.
handle A reference to the moved handle. A reference to this.
void Dali::TextAbstraction::FontClient::ClearCache()
Clear all caches in FontClient.
References Dali::GetImplementation.
void Dali::TextAbstraction::FontClient::ClearCacheOnLocaleChanged()
Clear caches in FontClient when Locale Changed.
This function only clears caches that needs to be cleared.
References Dali::GetImplementation.
void Dali::TextAbstraction::FontClient::SetDpi(unsigned int horizontalDpi, unsigned int verticalDpi)
Set the DPI of the target window.
Multiple windows are not currently supported. horizontalDpi The horizontal resolution in DPI. verticalDpi The vertical resolution in DPI.
References Dali::GetImplementation.
void Dali::TextAbstraction::FontClient::SetDpiFromWindowSystem()
Sets the DPI of the FontClient based on the current window's DPI.
Multiple windows are not currently supported.
References Dali::GetImplementation.
void Dali::TextAbstraction::FontClient::GetDpi(unsigned int &horizontalDpi, unsigned int &verticalDpi)
Retrieves the DPI previously set to the target window.
Multiple windows are not currently supported. horizontalDpi The horizontal resolution in DPI. verticalDpi The vertical resolution in DPI.
References Dali::Internal::Adaptor::SceneHolder::GetDpi, Dali::GetImplementation.
int Dali::TextAbstraction::FontClient::GetDefaultFontSize()
Called by Dali to retrieve the default font size for the platform.
This is an accessibility size, which is mapped to a UI Control specific point-size in stylesheets. For example if zero the smallest size, this could potentially map to TextLabel point-size 8. The default font size.
References Dali::GetImplementation.
void Dali::TextAbstraction::FontClient::ResetSystemDefaults()
Called when the user changes the system defaults.
Previously cached system defaults are removed.
References Dali::GetImplementation.
void Dali::TextAbstraction::FontClient::GetDefaultFonts(FontList &defaultFonts)
Retrieve the list of default fonts supported by the system.
defaultFonts A list of default font paths, family, width, weight and slant.
References Dali::GetImplementation.
void Dali::TextAbstraction::FontClient::InitDefaultFontDescription()
Initializes and caches default font from the system.
References Dali::GetImplementation.
void Dali::TextAbstraction::FontClient::GetDefaultPlatformFontDescription(FontDescription &fontDescription)
Retrieve the active default font from the system.
fontDescription font structure describing the default font.
References Dali::GetImplementation.
void Dali::TextAbstraction::FontClient::GetSystemFonts(FontList &systemFonts)
Retrieve the list of fonts supported by the system.
systemFonts A list of font paths, family, width, weight and slant.
References Dali::GetImplementation.
void Dali::TextAbstraction::FontClient::GetDescription(FontId fontId, FontDescription &fontDescription)
Retrieves the font description of a given font fontId.
fontId The font identifier. fontDescription The path, family & style (width, weight and slant) describing the font.
References Dali::GetImplementation.
PointSize26Dot6 Dali::TextAbstraction::FontClient::GetPointSize(FontId fontId)
Retrieves the font point size of a given font fontId.
fontId The font identifier. The point size in 26.6 fractional points.
References Dali::GetImplementation.
bool Dali::TextAbstraction::FontClient::IsCharacterSupportedByFont(FontId fontId, Character character)
Whether the given character is supported by the font.
fontId The id of the font. character The character. true if the character is supported by the font.
References Dali::GetImplementation.
FontId Dali::TextAbstraction::FontClient::FindDefaultFont(Character charcode, PointSize26Dot6 requestedPointSize=DEFAULT_POINT_SIZE, bool preferColor=false)
Find the default font for displaying a UTF-32 character.
This is useful when localised strings are provided for multiple languages i.e. when a single default font does not work for all languages. charcode The character for which a font is needed. requestedPointSize The point size in 26.6 fractional points; the default point size is 12*64. preferColor true if a color font is preferred. A valid font identifier, or zero if the font does not exist.
References Dali::GetImplementation.
FontId Dali::TextAbstraction::FontClient::FindFallbackFont(Character charcode, const FontDescription &preferredFontDescription, PointSize26Dot6 requestedPointSize=DEFAULT_POINT_SIZE, bool preferColor=false)
Find a fallback-font for displaying a UTF-32 character.
This is useful when localised strings are provided for multiple languages i.e. when a single default font does not work for all languages. charcode The character for which a font is needed. preferredFontDescription Description of the preferred font which may not provide a glyph for charcode. The fallback-font will be the closest match to preferredFontDescription, which does support the required glyph. requestedPointSize The point size in 26.6 fractional points; the default point size is 12*64. preferColor true if a color font is preferred. A valid font identifier, or zero if the font does not exist.
References Dali::GetImplementation.
FontId Dali::TextAbstraction::FontClient::GetFontId(const FontPath &path, PointSize26Dot6 requestedPointSize=DEFAULT_POINT_SIZE, FaceIndex faceIndex=0)
Retrieve the unique identifier for a font.
path The path to a font file. requestedPointSize The point size in 26.6 fractional points; the default point size is 12*64. faceIndex The index of the font face (optional). A valid font identifier, or zero if the font does not exist.
References Dali::GetImplementation.
FontId Dali::TextAbstraction::FontClient::GetFontId(const FontDescription &preferredFontDescription, PointSize26Dot6 requestedPointSize=DEFAULT_POINT_SIZE, FaceIndex faceIndex=0, Property::Map *variationsMapPtr=nullptr)
Retrieves a unique font identifier for a given description.
preferredFontDescription Description of the preferred font. The font will be the closest match to preferredFontDescription. requestedPointSize The point size in 26.6 fractional points; the default point size is 12*64. faceIndex The index of the font face (optional). variationsMapPtr The variations used in variable fonts (optional). A valid font identifier, or zero if no font is found.
References Dali::GetImplementation.
FontId Dali::TextAbstraction::FontClient::GetFontId(const BitmapFont &bitmapFont)
Retrieves a unique font identifier for a given bitmap font. If the font is not present, it will cache the given font, and give it a new font id.
bitmapFont A bitmap font. A valid font identifier.
References Dali::GetImplementation.
bool Dali::TextAbstraction::FontClient::IsScalable(const FontPath &path)
Check to see if a font is scalable.
path The path to a font file. true if scalable.
References Dali::GetImplementation.
bool Dali::TextAbstraction::FontClient::IsScalable(const FontDescription &fontDescription)
Check to see if a font is scalable.
It the font style is not empty, it will be used instead the font weight and font slant slant. fontDescription A font description. true if scalable
References Dali::GetImplementation.
void Dali::TextAbstraction::FontClient::GetFixedSizes(const FontPath &path, Dali::Vector< PointSize26Dot6 > &sizes)
Get a list of sizes available for a fixed size font.
path The path to a font file. sizes A list of the available sizes, if no sizes available will return empty.
References Dali::GetImplementation.
void Dali::TextAbstraction::FontClient::GetFixedSizes(const FontDescription &fontDescription, Dali::Vector< PointSize26Dot6 > &sizes)
Get a list of sizes available for a fixed size font.
It the font style is not empty, it will be used instead the font weight and font slant slant. fontDescription A font description. sizes A list of the available sizes, if no sizes available will return empty.
References Dali::GetImplementation.
bool Dali::TextAbstraction::FontClient::HasItalicStyle(FontId fontId) const
Whether the font has Italic style.
fontId The font identifier. true if the font has italic style.
References Dali::GetImplementation.
void Dali::TextAbstraction::FontClient::GetFontMetrics(FontId fontId, FontMetrics &metrics)
Query the metrics for a font.
fontId The identifier of the font for the required glyph. metrics The font metrics.
References Dali::GetImplementation.
GlyphIndex Dali::TextAbstraction::FontClient::GetGlyphIndex(FontId fontId, Character charcode)
Retrieve the glyph index for a UTF-32 character code.
fontId The identifier of the font for the required glyph. charcode The UTF-32 character code. The glyph index, or zero if the character code is undefined.
References Dali::GetImplementation.
GlyphIndex Dali::TextAbstraction::FontClient::GetGlyphIndex(FontId fontId, Character charcode, Character variantSelector)
Return the glyph index of a given character code as modified by the variation selector.
fontId The identifier of the font for the required glyph. charcode The UTF-32 character code. variantSelector The UTF-32 character code point of the variation selector. The glyph index, or zero if the character code is undefined.
References Dali::GetImplementation.
bool Dali::TextAbstraction::FontClient::GetGlyphMetrics(GlyphInfo *array, uint32_t size, GlyphType type, bool horizontal=true)
Retrieve the metrics for a series of glyphs.
array An array of glyph-info structures with initialized FontId & GlyphIndex values. It may contain the advance and an offset set into the bearing from the shaping tool. On return, the glyph's size value will be initialized. The bearing value will be updated by adding the font's glyph bearing to the one set by the shaping tool. size The size of the array. type The type of glyphs used for rendering; either bitmaps or vectors. horizontal True for horizontal layouts (set to false for vertical layouting). true if all of the requested metrics were found.
References Dali::GetImplementation.
void Dali::TextAbstraction::FontClient::CreateBitmap(FontId fontId, GlyphIndex glyphIndex, bool isItalicRequired, bool isBoldRequired, GlyphBufferData &data, int outlineWidth)
Create a bitmap representation of a glyph.
The caller is responsible for deallocating the bitmap data data.buffer using delete[]. fontId The identifier of the font. glyphIndex The index of a glyph within the specified font. isItalicRequired Whether the glyph requires italic style. isBoldRequired Whether the glyph requires bold style. data The bitmap data. outlineWidth The width of the glyph outline in pixels.
References Dali::GetImplementation.
PixelData Dali::TextAbstraction::FontClient::CreateBitmap(FontId fontId, GlyphIndex glyphIndex, int outlineWidth)
Create a bitmap representation of a glyph.
fontId The identifier of the font. glyphIndex The index of a glyph within the specified font. outlineWidth The width of the glyph outline in pixels. A valid PixelData, or an empty handle if the glyph could not be rendered.
References Dali::GetImplementation.
void Dali::TextAbstraction::FontClient::CreateVectorBlob(FontId fontId, GlyphIndex glyphIndex, VectorBlob *&blob, unsigned int &blobLength, unsigned int &nominalWidth, unsigned int &nominalHeight)
Create a vector representation of a glyph.
This feature requires highp shader support and is not available on all platforms fontId The identifier of the font. glyphIndex The index of a glyph within the specified font. blob A blob of data; this is owned by FontClient and should be copied by the caller of CreateVectorData(). blobLength The length of the blob data, or zero if the blob creation failed. nominalWidth The width of the blob. nominalHeight The height of the blob.
References Dali::GetImplementation.
const GlyphInfo & Dali::TextAbstraction::FontClient::GetEllipsisGlyph(PointSize26Dot6 requestedPointSize)
Retrieves the ellipsis glyph for a requested point size.
requestedPointSize The requested point size. The ellipsis glyph.
References Dali::GetImplementation.
bool Dali::TextAbstraction::FontClient::IsColorGlyph(FontId fontId, GlyphIndex glyphIndex)
Whether the given glyph glyphIndex is a color glyph.
fontId The font id. glyphIndex The glyph index. true if the glyph is a color one.
References Dali::GetImplementation.
bool Dali::TextAbstraction::FontClient::IsColorFont(FontId fontId)
Whether the given glyph font is a color.
fontId The font id. true if the font is a color one.
References Dali::GetImplementation.
bool Dali::TextAbstraction::FontClient::AddCustomFontDirectory(const FontPath &path)
Add custom fonts directory.
path to the fonts directory true if the fonts can be added.
References Dali::GetImplementation.
const FontPathList & Dali::TextAbstraction::FontClient::GetCustomFontDirectories()
Gets the custom fonts directories.
list of the custom font paths.
References Dali::GetImplementation.
CustomFontAddedSignalType & Dali::TextAbstraction::FontClient::CustomFontAddedSignal()
Signal emitted when a custom font directory is successfully added.
The signal signature is: void CustomFontAddedSignal(const std::string& path) The signal to connect to.
References Dali::GetImplementation.
GlyphIndex Dali::TextAbstraction::FontClient::CreateEmbeddedItem(const EmbeddedItemDescription &description, Pixel::Format &pixelFormat)
Creates and stores an embedded item and it's metrics.
If in the description there is a non empty url, it calls Dali::LoadImageFromFile() internally. If in the description there is a url and width or height are zero it stores the default size. Otherwise the image is resized. If the url in the description is empty it stores the size. description The description of the embedded item. pixelFormat The pixel format of the image. return The index within the vector of embedded items.
References Dali::GetImplementation.
void Dali::TextAbstraction::FontClient::EnableAtlasLimitation(bool enabled)
true to enable Atlas-Limitation.
Used default configuration. enabled The on/off value to enable/disable Atlas-Limitation.
References Dali::GetImplementation.
bool Dali::TextAbstraction::FontClient::IsAtlasLimitationEnabled() const
Check Atlas-Limitation is enabled or disabled.
Used default configuration. return true if Atlas-Limitation is enabled, otherwise false.
References Dali::GetImplementation.
Size Dali::TextAbstraction::FontClient::GetMaximumTextAtlasSize() const
retrieve the maximum allowed width and height for text-atlas-block.
Used default configuration. return the maximum width and height of text-atlas-block.
References Dali::GetImplementation.
Size Dali::TextAbstraction::FontClient::GetDefaultTextAtlasSize() const
retrieve the default width and height for text-atlas-block.
Used default configuration. return the default width and height of text-atlas-block.
References Dali::GetImplementation.
Size Dali::TextAbstraction::FontClient::GetCurrentMaximumBlockSizeFitInAtlas() const
retrieve the current maximum width and height for text-atlas-block.
Used default configuration. return the current maximum width and height of text-atlas-block.
References Dali::GetImplementation.
bool Dali::TextAbstraction::FontClient::SetCurrentMaximumBlockSizeFitInAtlas(const Size &currentMaximumBlockSizeFitInAtlas)
set the achieved size (width and height) for text-atlas-block. If currentMaximumBlockSizeFitInAtlas larger than the current maximum text atlas then store, otherwise ignore.
Used default configuration. return true if the current maximum text atlas size is changed, otherwise false.
References Dali::GetImplementation.
uint32_t Dali::TextAbstraction::FontClient::GetNumberOfPointsPerOneUnitOfPointSize() const
retrieve the number of points to scale-up one unit of point-size.
Used default configuration. return the number of points per one unit of point-size
References Dali::GetImplementation.
Dali::TextAbstraction::FontClient::FontClient(Internal::FontClient *fontClient)
This constructor is used by FontClient::Get().
fontClient A pointer to the internal fontClient object.