Dali::Accessibility::Accessible
DumpDetailLevel
friend class Bridge
AtspiInterfaces Dali::Accessibility::Accessible::mInterfaces
AtspiEvents Dali::Accessibility::Accessible::mSuppressedEvents
bool Dali::Accessibility::Accessible::mIsOnRootLevel
std::unordered_map<std::type_index, std::weak_ptr<IAccessibilityFeature> > Dali::Accessibility::Accessible::mFeatures
virtual Dali::Accessibility::Accessible::~Accessible() noexcept=default
virtual std::string Dali::Accessibility::Accessible::GetName() const =0
Gets accessibility name.
The string with name
virtual std::string Dali::Accessibility::Accessible::GetDescription() const =0
Gets accessibility description.
The string with description
virtual std::string Dali::Accessibility::Accessible::GetValue() const =0
Gets accessibility value.
The value text
virtual Accessible * Dali::Accessibility::Accessible::GetParent()=0
Gets parent.
The handler to accessibility object
virtual std::size_t Dali::Accessibility::Accessible::GetChildCount() const =0
Gets the number of children.
The number of children
virtual std::vector< Accessible * > Dali::Accessibility::Accessible::GetChildren()=0
Gets collection with all children.
The collection of accessibility objects
virtual Accessible * Dali::Accessibility::Accessible::GetChildAtIndex(std::size_t index)=0
Gets child of the index.
The child object
virtual std::size_t Dali::Accessibility::Accessible::GetIndexInParent()=0
Gets index that current object has in its parent's children collection.
The index of the current object
virtual Role Dali::Accessibility::Accessible::GetRole() const =0
Gets accessibility role.
Role enumeration Dali::Accessibility::Role
Referenced by GetRoleName.
std::string Dali::Accessibility::Accessible::GetRoleName() const
Gets name of accessibility role.
The string with human readable role converted from enumeration Dali::Accessibility::Role Accessibility::Accessible::GetRole
References Dali::Accessibility::ACCELERATOR_LABEL, Dali::Accessibility::ALERT, Dali::Accessibility::ANIMATION, Dali::Accessibility::APPLICATION, Dali::Accessibility::ARROW, Dali::Accessibility::ARTICLE, Dali::Accessibility::AUDIO, Dali::Accessibility::AUTOCOMPLETE, Dali::Accessibility::BLOCK_QUOTE, Dali::Accessibility::CALENDAR, Dali::Accessibility::CANVAS, Dali::Accessibility::CAPTION, Dali::Accessibility::CHART, Dali::Accessibility::CHECK_BOX, Dali::Accessibility::CHECK_MENU_ITEM, Dali::Accessibility::COLOR_CHOOSER, Dali::Accessibility::COLUMN_HEADER, Dali::Accessibility::COMBO_BOX, Dali::Accessibility::COMMENT, Dali::Accessibility::DATE_EDITOR, Dali::Accessibility::DEFINITION, Dali::Accessibility::DESKTOP_FRAME, Dali::Accessibility::DESKTOP_ICON, Dali::Accessibility::DIAL, Dali::Accessibility::DIALOG, Dali::Accessibility::DIRECTORY_PANE, Dali::Accessibility::DOCUMENT_EMAIL, Dali::Accessibility::DOCUMENT_FRAME, Dali::Accessibility::DOCUMENT_PRESENTATION, Dali::Accessibility::DOCUMENT_SPREADSHEET, Dali::Accessibility::DOCUMENT_TEXT, Dali::Accessibility::DOCUMENT_WEB, Dali::Accessibility::DRAWING_AREA, Dali::Accessibility::EDITBAR, Dali::Accessibility::EMBEDDED, Dali::Accessibility::ENTRY, Dali::Accessibility::EXTENDED, Dali::Accessibility::FILE_CHOOSER, Dali::Accessibility::FILLER, Dali::Accessibility::FOCUS_TRAVERSABLE, Dali::Accessibility::FONT_CHOOSER, Dali::Accessibility::FOOTER, Dali::Accessibility::FORM, Dali::Accessibility::FRAME, GetRole, Dali::Accessibility::GLASS_PANE, Dali::Accessibility::GROUPING, Dali::Accessibility::HEADER, Dali::Accessibility::HEADING, Dali::Accessibility::HTML_CONTAINER, Dali::Accessibility::ICON, Dali::Accessibility::IMAGE, Dali::Accessibility::IMAGE_MAP, Dali::Accessibility::INFO_BAR, Dali::Accessibility::INPUT_METHOD_WINDOW, Dali::Accessibility::INTERNAL_FRAME, Dali::Accessibility::INVALID, Dali::Accessibility::LABEL, Dali::Accessibility::LANDMARK, Dali::Accessibility::LAYERED_PANE, Dali::Accessibility::LEVEL_BAR, Dali::Accessibility::LINK, Dali::Accessibility::LIST, Dali::Accessibility::LIST_BOX, Dali::Accessibility::LIST_ITEM, Dali::Accessibility::LOG, Dali::Accessibility::MARQUEE, Dali::Accessibility::MATH, Dali::Accessibility::MATH_FRACTION, Dali::Accessibility::MATH_ROOT, Dali::Accessibility::MENU, Dali::Accessibility::MENU_BAR, Dali::Accessibility::MENU_ITEM, Dali::Accessibility::NOTIFICATION, Dali::Accessibility::OPTION_PANE, Dali::Accessibility::PAGE, Dali::Accessibility::PAGE_TAB, Dali::Accessibility::PAGE_TAB_LIST, Dali::Accessibility::PANEL, Dali::Accessibility::PARAGRAPH, Dali::Accessibility::PASSWORD_TEXT, Dali::Accessibility::POPUP_MENU, Dali::Accessibility::PROGRESS_BAR, Dali::Accessibility::PUSH_BUTTON, Dali::Accessibility::RADIO_BUTTON, Dali::Accessibility::RADIO_MENU_ITEM, Dali::Accessibility::RATING, Dali::Accessibility::REDUNDANT_OBJECT, Dali::Accessibility::ROOT_PANE, Dali::Accessibility::ROW_HEADER, Dali::Accessibility::RULER, Dali::Accessibility::SCROLL_BAR, Dali::Accessibility::SCROLL_PANE, Dali::Accessibility::SECTION, Dali::Accessibility::SEPARATOR, Dali::Accessibility::SLIDER, Dali::Accessibility::SPIN_BUTTON, Dali::Accessibility::SPLIT_PANE, Dali::Accessibility::STATIC, Dali::Accessibility::STATUS_BAR, Dali::Accessibility::SUBSCRIPT, Dali::Accessibility::SUPERSCRIPT, Dali::Accessibility::TABLE, Dali::Accessibility::TABLE_CELL, Dali::Accessibility::TABLE_COLUMN_HEADER, Dali::Accessibility::TABLE_ROW, Dali::Accessibility::TABLE_ROW_HEADER, Dali::Accessibility::TEAROFF_MENU_ITEM, Dali::Accessibility::TERMINAL, Dali::Accessibility::TEXT, Dali::Accessibility::TIMER, Dali::Accessibility::TITLE_BAR, Dali::Accessibility::TOGGLE_BUTTON, Dali::Accessibility::TOOL_BAR, Dali::Accessibility::TOOL_TIP, Dali::Accessibility::TREE, Dali::Accessibility::TREE_ITEM, Dali::Accessibility::TREE_TABLE, Dali::Accessibility::UNKNOWN, Dali::Accessibility::VIDEO, Dali::Accessibility::VIEWPORT, Dali::Accessibility::WINDOW.
Referenced by GetLocalizedRoleName.
std::string Dali::Accessibility::Accessible::GetLocalizedRoleName() const
Gets localized name of accessibility role.
The string with human readable role translated according to current translation domain Dali::Accessibility::Role Accessibility::Accessible::GetRole Accessibility::Accessible::GetRoleName translation is not supported in this version
References GetRoleName.
virtual States Dali::Accessibility::Accessible::GetStates()=0
Gets accessibility states.
The collection of states States class is instatation of ArrayBitset template class Dali::Accessibility::State Dali::Accessibility::ArrayBitset
Referenced by Dali::Accessibility::ActorAccessible::NotifyAccessibilityStateChange.
virtual Attributes Dali::Accessibility::Accessible::GetAttributes() const =0
Gets accessibility attributes.
The map of attributes and their values
virtual bool Dali::Accessibility::Accessible::IsHidden() const
Checks if this is hidden.
True if this is hidden Hidden means not present in the AT-SPI tree.
virtual bool Dali::Accessibility::Accessible::IsProxy() const
Checks if this is proxy.
True if this is proxy
bool Dali::Accessibility::Accessible::IsHighlighted() const
Checks if this is highlighted.
True if highlighted, false otherwise
References GetCurrentlyHighlightedActor, GetFeature, GetInternalActor.
virtual Address Dali::Accessibility::Accessible::GetAddress() const =0
Gets unique address on accessibility bus.
The Address class containing address Dali::Accessibility::Address
virtual bool Dali::Accessibility::Accessible::DoGesture(const GestureInfo &gestureInfo)=0
Deputes an object to perform provided gesture.
gestureInfo The structure describing the gesture true on success, false otherwise Dali::Accessibility::GestureInfo
virtual std::vector< Relation > Dali::Accessibility::Accessible::GetRelationSet()=0
Gets information about current object and all relations that connects it with other accessibility objects.
The iterable collection of Relation objects Dali::Accessibility::Relation
virtual Dali::Actor Dali::Accessibility::Accessible::GetInternalActor() const =0
Gets the Actor associated with this Accessible (if there is one).
The internal Actor
Referenced by IsHighlighted.
virtual void Dali::Accessibility::Accessible::SetListenPostRender(bool enabled)
Sets whether to listen for post render callback.
enabled If ture, registration post render callback, false otherwise
virtual std::string Dali::Accessibility::Accessible::GetStringProperty(std::string propertyName) const =0
Gets the stirng property.
propertyName The property name. The string property value. Empty string if property does not exist.
AtspiInterfaces Dali::Accessibility::Accessible::GetInterfaces() const
Gets all implemented interfaces.
Override DoGetInterfaces() to customize the return value of this method. The collection of implemented interfaces DoGetInterfaces()
References DoGetInterfaces.
Referenced by GetInterfacesAsStrings.
std::vector< std::string > Dali::Accessibility::Accessible::GetInterfacesAsStrings() const
Gets all implemented interfaces.
Converts all interfaces returned by GetInterfaces() to their DBus names using GetInterfaceName(). The collection of names of implemented interfaces GetInterfaces() GetInterfaceName()
References GetInterfaceName, GetInterfaces, Dali::Accessibility::MAX_COUNT.
bool Dali::Accessibility::Accessible::IsOnRootLevel() const
Checks if object is on root level.
Whether object is on root level or not
Referenced by Dali::Accessibility::ActorAccessible::GetParent.
AtspiEvents Dali::Accessibility::Accessible::GetSuppressedEvents() const
Gets all suppressed events.
All suppressed events
AtspiEvents & Dali::Accessibility::Accessible::GetSuppressedEvents()
Gets all suppressed events.
All suppressed events
std::string Dali::Accessibility::Accessible::DumpTree(DumpDetailLevel detailLevel)
Dumps tree structure of accessible objects starting from self.
detailLevel Detail level of dumped json output.
virtual Accessible * Dali::Accessibility::Accessible::GetAccessibleAtPoint(Point point, CoordinateType type) override
Gets Accessible object containing given point.
point The two-dimensional point type The enumeration with type of coordinate system The handle to last child of current object which contains given point Dali::Accessibility::Point
virtual bool Dali::Accessibility::Accessible::IsAccessibleContainingPoint(Point point, CoordinateType type) const override
Checks if the current object contains the given point inside.
point The two-dimensional point type The enumeration with type of coordinate system True if accessible contains in point, otherwise false. This method is Contains in DBus method. Dali::Accessibility::Point
void Dali::Accessibility::Accessible::AddFeature(std::shared_ptr< Accessible > accessible)
Adds an existing feature instance.
This template function registers an existing feature instance. The feature type T must inherit from IAccessibilityFeature. T The feature type accessible Shared pointer to the existing feature instance
std::shared_ptr< T > Dali::Accessibility::Accessible::GetFeature() const
Gets a feature of type T.
This template function retrieves a previously registered feature instance. The feature type T must inherit from IAccessibilityFeature. T The feature type to retrieve Shared pointer to the feature instance, or nullptr if not found Returns nullptr if the feature has not been registered or if the dynamic cast to type T fails.
Referenced by Dali::Accessibility::ActorAccessible::ActorAccessible, Dali::Accessibility::ActorAccessible::CanAcceptZeroSize, Dali::Accessibility::ActorAccessible::DoGetChildren, DoGetInterfaces, Dali::Accessibility::ActorAccessible::Emit, Dali::Accessibility::ActorAccessible::Emit, Dali::Accessibility::ActorAccessible::EmitActiveDescendantChanged, Dali::Accessibility::ActorAccessible::EmitBoundsChanged, Dali::Accessibility::ActorAccessible::EmitFocused, Dali::Accessibility::ActorAccessible::EmitHighlighted, Dali::Accessibility::ActorAccessible::EmitMovedOutOfScreen, Dali::Accessibility::ActorAccessible::EmitScrollFinished, Dali::Accessibility::ActorAccessible::EmitScrollStarted, Dali::Accessibility::ActorAccessible::EmitShowing, Dali::Accessibility::ActorAccessible::EmitStateChanged, Dali::Accessibility::ActorAccessible::EmitTextCursorMoved, Dali::Accessibility::ActorAccessible::EmitTextDeleted, Dali::Accessibility::ActorAccessible::EmitTextInserted, Dali::Accessibility::ActorAccessible::EmitVisible, Get, Dali::Accessibility::ActorAccessible::GetAddress, Dali::Accessibility::ActorAccessible::GetChildAtIndex, Dali::Accessibility::ActorAccessible::GetExtents, Dali::Accessibility::ActorAccessible::GetIndexInParent, GetInterfaceName, Dali::Accessibility::ActorAccessible::GetMatches, Dali::Accessibility::ActorAccessible::GetMatchesInMatches, Dali::Accessibility::ActorAccessible::GetName, GetOwningPtr, Dali::Accessibility::ActorAccessible::GetParent, Dali::Accessibility::ActorAccessible::InitDefaultFeatures, IsHighlighted, Dali::Accessibility::ActorAccessible::NotifyAccessibilityStateChange, Dali::Accessibility::ActorAccessible::ObjectDestroyed, RegisterExternalAccessibleGetter, SetCurrentlyHighlightedActor, SetHighlightActor.
virtual void Dali::Accessibility::Accessible::InitDefaultFeatures()=0
Initializes default accessibility features.
This pure virtual function must be implemented by derived classes to initialize the default set of accessibility features for the specific accessible object type. This function is called during the initialization of the accessible object to set up the basic accessibility features that are always available.
Dali::Accessibility::Accessible::Accessible()=default
Dali::Accessibility::Accessible::Accessible(const Accessible &)=delete
Dali::Accessibility::Accessible::Accessible(Accessible &&)=delete
Accessible & Dali::Accessibility::Accessible::operator=(const Accessible &)=delete
Accessible & Dali::Accessibility::Accessible::operator=(Accessible &&)=delete
AtspiInterfaces Dali::Accessibility::Accessible::DoGetInterfaces() const
Returns the collection of AT-SPI interfaces implemented by this Accessible.
This method is called only once and its return value is cached. Must override this and fill interface if you determine which interfaces are implemented. The collection of implemented interfaces GetInterfaces() GetInterfaceName()
References Dali::Accessibility::ACCESSIBLE, Dali::Accessibility::ACTION, Dali::Accessibility::APPLICATION, Dali::Accessibility::COLLECTION, Dali::Accessibility::COMPONENT, Dali::Accessibility::EDITABLE_TEXT, GetFeature, Dali::Accessibility::HYPERLINK, Dali::Accessibility::HYPERTEXT, Dali::Accessibility::SELECTION, Dali::Accessibility::SOCKET, Dali::Accessibility::TABLE, Dali::Accessibility::TABLE_CELL, Dali::Accessibility::TEXT, Dali::Accessibility::VALUE.
Referenced by GetInterfaces.
Dali::Actor Dali::Accessibility::Accessible::GetHighlightActor()
Gets the highlight actor.
This method is to get the highlight itself. The highlight actor
References Dali::Accessibility::Bridge::GetCurrentBridge, Dali::Accessibility::IsUp.
void Dali::Accessibility::Accessible::SetHighlightActor(Dali::Actor actor)
Sets the highlight actor.
This method is to set the highlight itself. actor The highlight actor
References Dali::Accessibility::Bridge::GetCurrentBridge, GetFeature, Dali::Accessibility::IsUp.
Dali::Actor Dali::Accessibility::Accessible::GetCurrentlyHighlightedActor()
Gets the currently highlighted actor.
The current highlighted actor
References Dali::Accessibility::Bridge::GetCurrentBridge, Dali::Accessibility::IsUp.
Referenced by Dali::Accessibility::Bridge::ForceDown, IsHighlighted.
void Dali::Accessibility::Accessible::SetCurrentlyHighlightedActor(Dali::Actor actor)
Sets currently highlighted actor.
actor The highlight actor
References Dali::Accessibility::Bridge::GetCurrentBridge, GetFeature, Dali::Accessibility::IsUp.
void Dali::Accessibility::Accessible::RegisterExternalAccessibleGetter(std::function< std::pair< std::shared_ptr< Accessible >, bool >(Dali::Actor)> functor)
The method registers functor resposible for converting Actor into Accessible.
functor The returning Accessible handle from Actor object
References GetFeature.
Accessible * Dali::Accessibility::Accessible::Get(Dali::Actor actor)
Acquires Accessible object from Actor object.
actor Actor object The raw pointer to Accessible object
References GetFeature, GetOwningPtr.
Referenced by Dali::Accessibility::ActorAccessible::DoGetChildren, Dali::Accessibility::Bridge::ForceDown, Dali::Accessibility::ActorAccessible::GetParent.
std::shared_ptr< Accessible > Dali::Accessibility::Accessible::GetOwningPtr(Dali::Actor actor)
Acquires Accessible object from Actor object.
actor Actor object The owning pointer to Accessible object
References Dali::Accessibility::Bridge::GetCurrentBridge, GetFeature.
Referenced by Get.
std::string Dali::Accessibility::Accessible::GetInterfaceName(AtspiInterface interface)
Obtains the DBus interface name for the specified AT-SPI interface.
interface AT-SPI interface identifier (e.g. AtspiInterface::ACCESSIBLE) AT-SPI interface name (e.g. "org.a11y.atspi.Accessible")
References Dali::Accessibility::ACCESSIBLE, Dali::Accessibility::ACTION, Dali::Accessibility::APPLICATION, Dali::Accessibility::CACHE, Dali::Accessibility::COLLECTION, Dali::Accessibility::COMPONENT, Dali::Accessibility::DEVICE_EVENT_CONTROLLER, Dali::Accessibility::DEVICE_EVENT_LISTENER, Dali::Accessibility::DOCUMENT, Dali::Accessibility::EDITABLE_TEXT, Dali::Accessibility::EVENT_DOCUMENT, Dali::Accessibility::EVENT_FOCUS, Dali::Accessibility::EVENT_KEYBOARD, Dali::Accessibility::EVENT_MOUSE, Dali::Accessibility::EVENT_OBJECT, Dali::Accessibility::EVENT_TERMINAL, Dali::Accessibility::EVENT_WINDOW, GetFeature, Dali::Accessibility::HYPERLINK, Dali::Accessibility::HYPERTEXT, Dali::Accessibility::IMAGE, Dali::Accessibility::REGISTRY, Dali::Accessibility::SELECTION, Dali::Accessibility::SOCKET, Dali::Accessibility::TABLE, Dali::Accessibility::TABLE_CELL, Dali::Accessibility::TEXT, Dali::Accessibility::VALUE.
Referenced by GetInterfacesAsStrings.