Dali::Internal::Adaptor
typedef IntrusivePtr<Widget> Dali::Internal::Adaptor::WidgetPtr
using Dali::Internal::Adaptor::SceneHolderPtr = typedef IntrusivePtr<SceneHolder>
DALI_ADAPTOR_API Internal::Adaptor::Widget & Dali::Internal::Adaptor::GetImplementation(Dali::Widget &widget)
Gets implementation from the handle.
@SINCE_1_3_5 handle Implementation handle is initialized and points to a widget
Referenced by Dali::OffscreenWindow::Add, Dali::Application::AddIdle, Dali::UiContext::AddIdle, Dali::DevelApplication::AddIdleWithReturnValue, Dali::PerformanceLogger::AddMarker, Dali::OffscreenWindow::AddPostRenderAsyncCallback, Dali::OffscreenWindow::AddPostRenderSyncCallback, Dali::Application::AppControlSignal, Dali::Orientation::ChangedSignal, Dali::Application::DeviceOrientationChangedSignal, Dali::PerformanceLogger::EnableLogging, Dali::Internal::Adaptor::SceneHolder::FeedKeyEvent, Dali::UiContext::FlushUpdateMessages, Dali::DevelApplication::FlushUpdateMessages, Dali::OffscreenWindow::GetBackgroundColor, Dali::UiContext::GetDefaultWindow, Dali::Orientation::GetDegrees, Dali::Timer::GetInterval, Dali::Application::GetLanguage, Dali::DevelApplication::GetMainThreadId, Dali::OffscreenWindow::GetNativeImage, Dali::Application::GetObjectRegistry, Dali::Orientation::GetRadians, Dali::Application::GetRegion, Dali::DevelApplication::GetRenderThreadId, Dali::OffscreenWindow::GetRootLayer, Dali::OffscreenWindow::GetSize, Dali::DevelApplication::GetUiThreadId, Dali::OffscreenApplication::GetWindow, Dali::Application::GetWindow, Dali::Application::InitSignal, Dali::Timer::IsRunning, Dali::Application::LanguageChangedSignal, Dali::Application::LowBatterySignal, Dali::Application::Lower, Dali::Application::LowMemorySignal, Dali::Application::MainLoop, Dali::Timer::Pause, Dali::Application::PauseSignal, Dali::ApplicationController::PostInitialize, Dali::ApplicationController::PostPause, Dali::ApplicationController::PostResume, Dali::ApplicationController::PostTerminate, Dali::ApplicationController::PreInitialize, Dali::ApplicationController::PreLanguageChanged, Dali::ApplicationController::PrePause, Dali::ApplicationController::PreResume, Dali::ApplicationController::PreTerminate, Dali::Application::Quit, Dali::Application::RegionChangedSignal, Dali::WidgetApplication::RegisterWidgetCreatingFunction, Dali::OffscreenWindow::Remove, Dali::OffscreenApplication::RenderOnce, Dali::Application::ResetSignal, Dali::Timer::Resume, Dali::Application::ResumeSignal, Dali::DevelApplication::SetApplicationLocale, Dali::UiContext::SetApplicationLocale, Dali::OffscreenWindow::SetBackgroundColor, Dali::PerformanceLogger::SetLoggingFrequency, Dali::OffscreenWindow::SetNativeImage, Dali::OffscreenApplication::Start, Dali::Timer::Start, Dali::Timer::Stop, Dali::Application::TaskAppControlSignal, Dali::Application::TaskDeviceOrientationChangedSignal, Dali::Application::TaskInitSignal, Dali::Application::TaskLanguageChangedSignal, Dali::Application::TaskLowBatterySignal, Dali::Application::TaskLowMemorySignal, Dali::Application::TaskRegionChangedSignal, Dali::Application::TaskTerminateSignal, Dali::OffscreenApplication::Terminate, Dali::Application::TerminateSignal, Dali::Timer::TickSignal.
DALI_ADAPTOR_API const Internal::Adaptor::Widget & Dali::Internal::Adaptor::GetImplementation(const Dali::Widget &widget)
Gets implementation from the handle.
@SINCE_1_3_5 handle Implementation Handle is initialized and points to a widget.