Dali::Accessibility
ScreenRelativeMoveType
Object moves outside of the screen.
RelationType
Null Relation.
CoordinateType
Screen.
ComponentLayer
Invalid.
Role
State
TextChangedState
ObjectPropertyChangeEvent
WindowEvent
WindowRestoreType
TextBoundary
Gesture
GestureState
ReadingInfoType
AtspiInterface
AtspiEvent
ActionType
using Dali::Accessibility::AtspiInterfaces = typedef EnumBitSet<AtspiInterface, AtspiInterface::MAX_COUNT>
using Dali::Accessibility::AtspiEvents = typedef EnumBitSet<AtspiEvent, AtspiEvent::MAX_COUNT>
using Dali::Accessibility::ReadingInfoTypes = typedef EnumBitSet<ReadingInfoType, ReadingInfoType::MAX_COUNT>
using Dali::Accessibility::States = typedef EnumBitSet<State, State::MAX_COUNT>
using Dali::Accessibility::Attributes = typedef std::unordered_map<std::string, std::string>
using Dali::Accessibility::AtspiInterfaceType = typedef typename Internal::AtspiInterfaceTypeHelper<I>::Type
Resolves to the native C++ type that represents the given AT-SPI interface.
For example, AtspiInterfaceType<AtspiInterface::ACCESSIBLE> is the same as Dali::Accessibility::Accessible . Not all AT-SPI interfaces have native C++ representations (in which case, such an expression will not compile). I Enumeration value indicating the requested AT-SPI interface.
bool Dali::Accessibility::IsUp()
Checks if ATSPI is activated or not.
True if ATSPI is activated.
References Dali::Accessibility::Bridge::GetCurrentBridge, Dali::Accessibility::Bridge::IsTerminated.
Referenced by Dali::Accessibility::Accessible::GetCurrentlyHighlightedActor, Dali::Accessibility::Accessible::GetHighlightActor, Dali::AtspiAccessibility::IsEnabled, Dali::Accessibility::ActorAccessible::NotifyAccessibilityStateChange, Dali::Accessibility::Accessible::SetCurrentlyHighlightedActor, Dali::Accessibility::Accessible::SetHighlightActor.