Dali
WindowOrientation
Portrait orientation. The height of the display area is greater than the width. @SINCE_2_0.0.
WindowType
A default window type. Indicates a normal, top-level window. Almost every window will be created with this type. @SINCE_2_0.0.
WindowNotificationLevel
No notification level. Default level. This value makes the notification window place in the layer of the normal window. @SINCE_2_0.0.
WindowScreenOffMode
The mode which turns the screen off after a timeout. @SINCE_2_0.0.
WindowEffectState
None state. @SINCE_2_0.0.
WindowEffectType
None type. @SINCE_2_0.0.
WindowOperationResult
Failed for unknown reason.
WindowResizeDirection
Start resizing window to the top-left edge.
WindowInsetsPartType
Status bar.
WindowInsetsPartState
Invisible.
WindowBlurType
default value for blur disable
WindowInsetsPartFlags
VideoSyncMode
using Dali::AsyncTaskPtr = typedef IntrusivePtr<AsyncTask>
typedef Dali::Rect< int > Dali::DisplayArea
using Dali::GlWindowImpl = typedef Internal::Adaptor::GlWindow
using Dali::WebEngineRequestInterceptorPtr = typedef Dali::IntrusivePtr<WebEngineRequestInterceptor>
using Dali::WindowContainer = typedef std::vector<Window>
using Dali::SceneHolderList = typedef std::vector<Dali::Integration::SceneHolder>
typedef Dali::IntrusivePtr<Dali::NativeImageSurface> Dali::NativeImageSurfacePtr
Pointer to Dali::NativeImageSurface.
using Dali::SurfaceSize = typedef Uint16Pair
DALI_ADAPTOR_API const unsigned int Dali::ADAPTOR_MAJOR_VERSION
The major version number of the Adaptor.
DALI_ADAPTOR_API const unsigned int Dali::ADAPTOR_MINOR_VERSION
The minor version number of the Adaptor.
DALI_ADAPTOR_API const unsigned int Dali::ADAPTOR_MICRO_VERSION
The micro version number of the Adaptor.
DALI_ADAPTOR_API const char *const Dali::ADAPTOR_BUILD_DATE
The date/time the Adaptor library was built.
constexpr uint32_t Dali::DEFAULT_JPG_QUALITY
Referenced by EncodeToFile.
bool Dali::IsKey(const KeyEvent &keyEvent, KEY daliKey)
WindowInsetsPartFlags Dali::operator|(WindowInsetsPartFlags a, WindowInsetsPartFlags b)
WindowInsetsPartFlags Dali::operator&(WindowInsetsPartFlags a, WindowInsetsPartFlags b)
bool Dali::HasFlag(WindowInsetsPartFlags value, WindowInsetsPartFlags flag)
DALI_ADAPTOR_API bool Dali::EncodeToFile(const unsigned char *const pixelBuffer, const std::string &filename, const Pixel::Format pixelFormat, const std::size_t width, const std::size_t height)
Store the given pixel data to a file. The suffix of the filename determines what type of file will be stored, currently only jpeg and png formats are supported. pixelBuffer Pointer to the pixel data filename Filename to save pixelFormat The format of the buffer's pixels width The width of the image in pixels height The height of the image in pixels true if the file was saved
References DEFAULT_JPG_QUALITY, EncodeToFile.
Referenced by EncodeToFile.
DALI_ADAPTOR_API bool Dali::EncodeToFile(const unsigned char *const pixelBuffer, const std::string &filename, const Pixel::Format pixelFormat, const std::size_t width, const std::size_t height, const uint32_t quality)
Store the given pixel data to a file. The suffix of the filename determines what type of file will be stored, currently only jpeg and png formats are supported. pixelBuffer Pointer to the pixel data filename Filename to save pixelFormat The format of the buffer's pixels width The width of the image in pixels height The height of the image in pixels quality The value to control image quality for jpeg file format in the range [1, 100] true if the file was saved
DALI_ADAPTOR_API Devel::PixelBuffer Dali::LoadImageFromFile(const std::string &url, ImageDimensions size=ImageDimensions(0, 0), FittingMode::Type fittingMode=FittingMode::DEFAULT, SamplingMode::Type samplingMode=SamplingMode::BOX_THEN_LINEAR, bool orientationCorrection=true)
Load an image synchronously from local file.
This method is thread safe, i.e. can be called from any thread. url The URL of the image file to load. size The width and height to fit the loaded image to, 0.0 means whole image fittingMode The method used to fit the shape of the image before loading to the shape defined by the size parameter. samplingMode The filtering method used when sampling pixels from the input image while fitting it to desired size. orientationCorrection Reorient the image to respect any orientation metadata in its header. handle to the loaded PixelBuffer object or an empty handle in case loading failed.
DALI_ADAPTOR_API void Dali::LoadImagePlanesFromFile(const std::string &url, std::vector< Devel::PixelBuffer > &buffers, ImageDimensions size=ImageDimensions(0, 0), FittingMode::Type fittingMode=FittingMode::DEFAULT, SamplingMode::Type samplingMode=SamplingMode::BOX_THEN_LINEAR, bool orientationCorrection=true)
Load an image and save each plane to a separate buffer synchronously from local file.
This method is thread safe, i.e. can be called from any thread. If the image file doesn't support to load planes, this method returns a bitmap image instead. url The URL of the image file to load. buffers The loaded PixelBuffer object list or an empty list in case loading failed. size The width and height to fit the loaded image to, 0.0 means whole image fittingMode The method used to fit the shape of the image before loading to the shape defined by the size parameter. samplingMode The filtering method used when sampling pixels from the input image while fitting it to desired size. orientationCorrection Reorient the image to respect any orientation metadata in its header.
DALI_ADAPTOR_API Devel::PixelBuffer Dali::LoadImageFromBuffer(const Dali::Vector< uint8_t > &buffer, ImageDimensions size=ImageDimensions(0, 0), FittingMode::Type fittingMode=FittingMode::DEFAULT, SamplingMode::Type samplingMode=SamplingMode::BOX_THEN_LINEAR, bool orientationCorrection=true)
Load an image synchronously from encoded buffer.
This method is thread safe, i.e. can be called from any thread. buffer The encoded buffer of the image to load. The buffer is not owned by FileStream and must be valid for entire lifetime of FileStream size The width and height to fit the loaded image to, 0.0 means whole image fittingMode The method used to fit the shape of the image before loading to the shape defined by the size parameter. samplingMode The filtering method used when sampling pixels from the input image while fitting it to desired size. orientationCorrection Reorient the image to respect any orientation metadata in its header. handle to the loaded PixelBuffer object or an empty handle in case loading failed.
DALI_ADAPTOR_API Devel::PixelBuffer Dali::LoadImageFromBuffer(uint8_t *buffer, size_t bufferSize, ImageDimensions size=ImageDimensions(0, 0), FittingMode::Type fittingMode=FittingMode::DEFAULT, SamplingMode::Type samplingMode=SamplingMode::BOX_THEN_LINEAR, bool orientationCorrection=true)
Load an image synchronously from encoded buffer.
This method is thread safe, i.e. can be called from any thread. buffer The encoded buffer of the image to load. The buffer is not owned by FileStream and must be valid for entire lifetime of FileStream bufferSize Size of the encoded buffer. size The width and height to fit the loaded image to, 0.0 means whole image fittingMode The method used to fit the shape of the image before loading to the shape defined by the size parameter. samplingMode The filtering method used when sampling pixels from the input image while fitting it to desired size. orientationCorrection Reorient the image to respect any orientation metadata in its header. handle to the loaded PixelBuffer object or an empty handle in case loading failed.
DALI_ADAPTOR_API ImageDimensions Dali::GetClosestImageSize(const std::string &filename, ImageDimensions size=ImageDimensions(0, 0), FittingMode::Type fittingMode=FittingMode::DEFAULT, SamplingMode::Type samplingMode=SamplingMode::BOX_THEN_LINEAR, bool orientationCorrection=true)
Determine the size of an image that LoadImageFromFile will provide when given the same image loading parameters.
This is a synchronous request. This function is used to determine the size of an image before it has loaded. filename name of the image. size The requested size for the image. fittingMode The method to use to map the source image to the desired dimensions. samplingMode The image filter to use if the image needs to be downsampled to the requested size. orientationCorrection Whether to use image metadata to rotate or flip the image, e.g., from portrait to landscape. dimensions that image will have if it is loaded with given parameters.
References GetMaxTextureSize.
DALI_ADAPTOR_API ImageDimensions Dali::GetOriginalImageSize(const std::string &filename, bool orientationCorrection=true)
Get the size of an original image. this method will respect any rotation of image.
filename name of the image. orientationCorrection Reorient the image to respect any orientation metadata in its header. dimensions to original image
References Dali::SamplingMode::BOX_THEN_LINEAR, Dali::FittingMode::DEFAULT.
DALI_ADAPTOR_API Devel::PixelBuffer Dali::DownloadImageSynchronously(const std::string &url, ImageDimensions size=ImageDimensions(0, 0), FittingMode::Type fittingMode=FittingMode::DEFAULT, SamplingMode::Type samplingMode=SamplingMode::BOX_THEN_LINEAR, bool orientationCorrection=true)
Load an image synchronously from a remote resource.
url The URL of the image file to load. size The width and height to fit the loaded image to, 0.0 means whole image fittingMode The method used to fit the shape of the image before loading to the shape defined by the size parameter. samplingMode The filtering method used when sampling pixels from the input image while fitting it to desired size. orientationCorrection Reorient the image to respect any orientation metadata in its header. handle to the loaded PixelBuffer object or an empty handle in case downloading or decoding failed.
DALI_ADAPTOR_API unsigned int Dali::GetMaxTextureSize()
get the maximum texture size.
The maximum texture size
Referenced by GetClosestImageSize.
DALI_ADAPTOR_API void Dali::SetThreadName(const std::string &threadName)
Set the thread name.
threadName The name of thread. The name can be up to 16 bytes long, and should be null-terminated if it contains fewer bytes.
NativeRenderSurface * Dali::CreateNativeSurface(SurfaceSize surfaceSize, Any surface, bool isTransparent)
Factory function for native surface A native surface is created. surfaceSize the size of the surface to create surface the native surface handle of your platform. If you don't pass this, a native surface will be created. isTransparent Whether the surface has an alpha channel
Internal::Adaptor::SceneHolder & Dali::GetImplementation(Dali::Integration::SceneHolder &sceneHolder)
Referenced by Dali::DevelWindow::AccessibilityHighlightSignal, Dali::GlWindow::Activate, Dali::Window::Activate, Dali::WebEngine::ActivateAccessibility, Dali::Integration::SceneHolder::Add, Dali::Window::Add, Dali::Window::AddAuxiliaryHint, Dali::GlWindow::AddAuxiliaryHint, Dali::Window::AddAvailableOrientation, Dali::TextAbstraction::FontClient::AddCustomFontDirectory, Dali::WebEngine::AddCustomHeader, Dali::CanvasRenderer::AddDrawable, Dali::WebEngine::AddDynamicCertificatePath, Dali::DevelWindow::AddFramePresentedCallback, Dali::DevelWindow::AddFrameRenderedCallback, Dali::WebEngine::AddJavaScriptEntireMessageHandler, Dali::WebEngine::AddJavaScriptMessageHandler, Dali::DragAndDrop::AddListener, Dali::DragAndDrop::AddListener, Dali::VectorAnimationRenderer::AddPropertyValueCallback, Dali::AsyncTaskManager::AddTask, Dali::Devel::PixelBuffer::ApplyGaussianBlur, Dali::Devel::PixelBuffer::ApplyMask, Dali::DevelWindow::AuxiliaryMessageSignal, Dali::VideoPlayer::Backward, Dali::TextAbstraction::FontFileManager::CacheFontFile, Dali::WebEngine::CanGoBack, Dali::WebEngine::CanGoForward, Dali::WebEngine::ChangeOrientation, Dali::WebEngine::CheckVideoPlayingAsynchronously, Dali::WebEngine::ClearAllTilesResources, Dali::TextAbstraction::FontClient::ClearCache, Dali::TextAbstraction::FontFileManager::ClearCache, Dali::TextAbstraction::FontClient::ClearCacheOnLocaleChanged, Dali::WebEngine::ClearHistory, Dali::WebEngine::ClearTilesWhenHidden, Dali::CanvasRenderer::Commit, Dali::Devel::PixelBuffer::Convert, Dali::WebEngine::Create, Dali::WebEngine::Create, Dali::TextAbstraction::FontClient::CreateBitmap, Dali::TextAbstraction::FontClient::CreateBitmap, Dali::TextAbstraction::FontClient::CreateEmbeddedItem, Dali::WebEngine::CreateHitTest, Dali::WebEngine::CreateHitTestAsynchronously, Dali::TextAbstraction::BidirectionalSupport::CreateInfo, Dali::Devel::PixelBuffer::CreatePixelData, Dali::TextAbstraction::FontClient::CreateVectorBlob, Dali::Devel::PixelBuffer::Crop, Dali::DevelWindow::CursorVisibleSet, Dali::TextAbstraction::FontClient::CustomFontAddedSignal, Dali::Clipboard::DataReceivedSignal, Dali::Clipboard::DataSelectedSignal, Dali::Clipboard::DataSentSignal, Dali::WebEngine::Destroy, Dali::TextAbstraction::BidirectionalSupport::DestroyInfo, Dali::TextAbstraction::FontClient::EnableAtlasLimitation, Dali::WebEngine::EnableCursorByClient, Dali::DevelWindow::EnableFloatingMode, Dali::WebEngine::EnableKeyEvents, Dali::WebEngine::EnableMouseEvents, Dali::VideoPlayer::EnableOffscreenFrameRendering, Dali::WebEngine::EnableVideoHole, Dali::StyleMonitor::EnsureFontClientCreated, Dali::WebEngine::EvaluateJavaScript, Dali::DevelWindow::EventProcessingFinishedSignal, Dali::VideoPlayer::EventSignal, Dali::DevelWindow::ExcludeInputRegion, Dali::WebEngine::ExitFullscreen, Dali::Integration::SceneHolder::FeedHoverEvent, Dali::DevelWindow::FeedHoverEvent, Dali::Integration::SceneHolder::FeedKeyEvent, Dali::DevelWindow::FeedKeyEvent, Dali::WebEngine::FeedMouseWheel, Dali::Integration::SceneHolder::FeedTouchPoint, Dali::DevelWindow::FeedTouchPoint, Dali::Integration::SceneHolder::FeedWheelEvent, Dali::DevelWindow::FeedWheelEvent, Dali::VectorAnimationRenderer::Finalize, Dali::TextAbstraction::FontClient::FindDefaultFont, Dali::TextAbstraction::FontClient::FindFallbackFont, Dali::TextAbstraction::FontFileManager::FindFontFile, Dali::TextAbstraction::FontFileManager::FindFontFile, Dali::VideoPlayer::FinishedSignal, Dali::VideoPlayer::FinishSynchronization, Dali::Integration::SceneHolder::FocusChangedGeneratedSignal, Dali::GlWindow::FocusChangeSignal, Dali::Window::FocusChangeSignal, Dali::VideoPlayer::Forward, Dali::Devel::TextureUploadManager::GenerateTexture2D, Dali::WebEngine::GetAccessibilityAddress, Dali::Window::GetAuxiliaryHintId, Dali::GlWindow::GetAuxiliaryHintId, Dali::GlWindow::GetAuxiliaryHintValue, Dali::Window::GetAuxiliaryHintValue, Dali::WebEngine::GetBackForwardList, Dali::Integration::SceneHolder::GetBackgroundColor, Dali::Window::GetBackgroundColor, Dali::DevelWindow::GetBlur, Dali::Devel::PixelBuffer::GetBrightness, Dali::Window::GetBrightness, Dali::Devel::PixelBuffer::GetBuffer, Dali::Devel::PixelBuffer::GetBuffer, Dali::TextAbstraction::BidirectionalSupport::GetCharactersDirection, Dali::VideoPlayer::GetCodecType, Dali::WebEngine::GetContentSize, Dali::TextAbstraction::FontClient::GetCurrentMaximumBlockSizeFitInAtlas, Dali::GlWindow::GetCurrentOrientation, Dali::DevelWindow::GetCurrentOrientation, Dali::TextAbstraction::FontClient::GetCustomFontDirectories, Dali::Clipboard::GetData, Dali::StyleMonitor::GetDefaultFontFamily, Dali::TextAbstraction::FontClient::GetDefaultFonts, Dali::TextAbstraction::FontClient::GetDefaultFontSize, Dali::StyleMonitor::GetDefaultFontSize, Dali::StyleMonitor::GetDefaultFontStyle, Dali::TextAbstraction::FontClient::GetDefaultPlatformFontDescription, Dali::VectorAnimationRenderer::GetDefaultSize, Dali::VectorImageRenderer::GetDefaultSize, Dali::TextAbstraction::FontClient::GetDefaultTextAtlasSize, Dali::TextAbstraction::FontClient::GetDescription, Dali::TextAbstraction::Hyphenation::GetDictionaryEncoding, Dali::VideoPlayer::GetDisplayMode, Dali::VideoPlayer::GetDisplayRotation, Dali::Window::GetDpi, Dali::TextAbstraction::FontClient::GetDpi, Dali::TextAbstraction::FontClient::GetEllipsisGlyph, Dali::WebEngine::GetFavicon, Dali::TextAbstraction::FontClient::GetFixedSizes, Dali::TextAbstraction::FontClient::GetFixedSizes, Dali::TextAbstraction::FontClient::GetFontId, Dali::TextAbstraction::FontClient::GetFontId, Dali::TextAbstraction::FontClient::GetFontId, Dali::TextAbstraction::FontClient::GetFontMetrics, Dali::AnimatedImageLoading::GetFrameInterval, Dali::VectorAnimationRenderer::GetFrameRate, Dali::DevelWindow::GetFrontBufferRendering, Dali::DevelWindow::GetFullScreen, Dali::TextAbstraction::FontClient::GetGlyphIndex, Dali::TextAbstraction::FontClient::GetGlyphIndex, Dali::TextAbstraction::FontClient::GetGlyphMetrics, Dali::TextAbstraction::Shaping::GetGlyphs, Dali::EncodedImageBuffer::GetHash, Dali::Devel::PixelBuffer::GetHeight, Dali::AnimatedImageLoading::GetImageCount, Dali::AnimatedImageLoading::GetImageSize, Dali::EncodedImageBuffer::GetImageType, Dali::DevelWindow::GetInsets, Dali::DevelWindow::GetInsets, Dali::DevelWindow::GetLastHoverEvent, Dali::DevelWindow::GetLastKeyEvent, Dali::DevelWindow::GetLastPanGestureState, Dali::DevelWindow::GetLastTouchEvent, Dali::Window::GetLayer, Dali::Window::GetLayerCount, Dali::VectorAnimationRenderer::GetLayerInfo, Dali::TextAbstraction::Segmentation::GetLineBreakPositions, Dali::TextAbstraction::Segmentation::GetLineBreakPositionsUtf8, Dali::WebEngine::GetLoadProgressPercentage, Dali::VectorAnimationRenderer::GetMarkerInfo, Dali::VectorAnimationRenderer::GetMarkerInfo, Dali::TextAbstraction::FontClient::GetMaximumTextAtlasSize, Dali::VideoPlayer::GetMediaPlayer, Dali::Devel::PixelBuffer::GetMetadata, Dali::TextAbstraction::BidirectionalSupport::GetMirroredText, Dali::DevelWindow::GetNativeBuffer, Dali::Integration::SceneHolder::GetNativeHandle, Dali::Window::GetNativeHandle, Dali::Integration::SceneHolder::GetNativeId, Dali::DevelWindow::GetNativeId, Dali::WebEngine::GetNativeImage, Dali::Window::GetNotificationLevel, Dali::TextAbstraction::FontClient::GetNumberOfPointsPerOneUnitOfPointSize, Dali::Window::GetOverlayLayer, Dali::WebEngine::GetPageZoomFactor, Dali::TextAbstraction::BidirectionalSupport::GetParagraphDirection, Dali::DevelWindow::GetParent, Dali::DevelWindow::GetPhysicalOrientation, Dali::TiltSensor::GetPitch, Dali::Devel::PixelBuffer::GetPixelFormat, Dali::WebEngine::GetPlainTextAsynchronously, Dali::VideoPlayer::GetPlayPosition, Dali::WebEngine::GetPlugin, Dali::TextAbstraction::FontClient::GetPointSize, Dali::Window::GetPosition, Dali::GlWindow::GetPositionSize, Dali::Window::GetPreferredOrientation, Dali::CanvasRenderer::GetRasterizedTexture, Dali::EncodedImageBuffer::GetRawBuffer, Dali::GlWindow::GetRenderingMode, Dali::Integration::SceneHolder::GetRenderTaskList, Dali::Window::GetRenderTaskList, Dali::TiltSensor::GetRoll, Dali::Integration::SceneHolder::GetRootLayer, Dali::Window::GetRootLayer, Dali::TiltSensor::GetRotation, Dali::TiltSensor::GetRotationThreshold, Dali::WebEngine::GetScaleFactor, Dali::DevelWindow::GetScreen, Dali::Window::GetScreenOffMode, Dali::WebEngine::GetScreenshot, Dali::WebEngine::GetScreenshotAsynchronously, Dali::WebEngine::GetScrollPosition, Dali::WebEngine::GetScrollSize, Dali::WebEngine::GetSelectedText, Dali::WebEngine::GetSettings, Dali::CanvasRenderer::GetSize, Dali::Window::GetSize, Dali::TtsPlayer::GetState, Dali::Devel::PixelBuffer::GetStride, Dali::Devel::PixelBuffer::GetStrideBytes, Dali::GlWindow::GetSupportedAuxiliaryHint, Dali::Window::GetSupportedAuxiliaryHint, Dali::GlWindow::GetSupportedAuxiliaryHintCount, Dali::Window::GetSupportedAuxiliaryHintCount, Dali::TextAbstraction::FontClient::GetSystemFonts, Dali::WebEngine::GetTextZoomFactor, Dali::StyleMonitor::GetTheme, Dali::WebEngine::GetTitle, Dali::VectorAnimationRenderer::GetTotalFrameNumber, Dali::Window::GetType, Dali::TiltSensor::GetUpdateFrequency, Dali::VideoPlayer::GetUrl, Dali::AnimatedImageLoading::GetUrl, Dali::WebEngine::GetUrl, Dali::WebEngine::GetUserAgent, Dali::CanvasRenderer::GetViewBox, Dali::VideoPlayer::GetVolume, Dali::Devel::PixelBuffer::GetWidth, Dali::TextAbstraction::Segmentation::GetWordBreakPositions, Dali::TextAbstraction::Segmentation::GetWordBreakPositionsUtf8, Dali::TextAbstraction::Hyphenation::GetWordHyphens, Dali::WebEngine::GoBack, Dali::WebEngine::GoForward, Dali::TextAbstraction::FontClient::HasItalicStyle, Dali::AnimatedImageLoading::HasLoadingSucceeded, Dali::Clipboard::HasType, Dali::GlWindow::Hide, Dali::Window::Hide, Dali::Clipboard::HideClipboard, Dali::WebEngine::HighlightText, Dali::DevelWindow::IncludeInputRegion, Dali::TextAbstraction::FontClient::InitDefaultFontDescription, Dali::LifecycleController::InitSignal, Dali::DevelWindow::InsetsChangedSignal, Dali::Integration::SceneHolder::InterceptKeyEventSignal, Dali::DevelWindow::InterceptKeyEventSignal, Dali::VectorAnimationRenderer::InvalidateBuffer, Dali::Devel::PixelBuffer::IsAlphaPreMultiplied, Dali::DevelWindow::IsAlwaysOnTop, Dali::TextAbstraction::FontClient::IsAtlasLimitationEnabled, Dali::PhysicalKeyboard::IsAttached, Dali::VideoPlayer::IsAutoRotationEnabled, Dali::DevelWindow::IsBottom, Dali::CanvasRenderer::IsCanvasChanged, Dali::TextAbstraction::FontClient::IsCharacterSupportedByFont, Dali::TextAbstraction::FontClient::IsColorFont, Dali::TextAbstraction::FontClient::IsColorGlyph, Dali::DevelWindow::IsFloatingModeEnabled, Dali::Window::IsFocusAcceptable, Dali::Integration::SceneHolder::IsGeometryHittestEnabled, Dali::WebEngine::IsIncognito, Dali::VideoPlayer::IsLetterBoxEnabled, Dali::VectorImageRenderer::IsLoaded, Dali::VideoPlayer::IsLooping, Dali::DevelWindow::IsMaximized, Dali::DevelWindow::IsMinimized, Dali::DevelWindow::IsModal, Dali::VideoPlayer::IsMuted, Dali::GlWindow::IsOpaqueState, Dali::Window::IsOpaqueState, Dali::Window::IsPartialUpdateEnabled, Dali::TextAbstraction::FontClient::IsScalable, Dali::TextAbstraction::FontClient::IsScalable, Dali::TiltSensor::IsStarted, Dali::VideoPlayer::IsVideoTextureSupported, Dali::Clipboard::IsVisible, Dali::Window::IsVisible, Dali::DevelWindow::IsWindowRotating, Dali::WebEngine::JavaScriptAlertReply, Dali::WebEngine::JavaScriptConfirmReply, Dali::WebEngine::JavaScriptPromptReply, Dali::VectorAnimationRenderer::KeepRasterizedBuffer, Dali::Window::KeepRendering, Dali::DevelWindow::KeyboardGrab, Dali::DevelWindow::KeyboardRepeatSettingsChangedSignal, Dali::DevelWindow::KeyboardUnGrab, Dali::Integration::SceneHolder::KeyEventGeneratedSignal, Dali::Integration::SceneHolder::KeyEventMonitorSignal, Dali::DevelWindow::KeyEventMonitorSignal, Dali::GlWindow::KeyEventSignal, Dali::Integration::SceneHolder::KeyEventSignal, Dali::Window::KeyEventSignal, Dali::LifecycleController::LanguageChangedSignal, Dali::VectorAnimationRenderer::Load, Dali::VectorAnimationRenderer::Load, Dali::VectorImageRenderer::Load, Dali::WebEngine::LoadContents, Dali::FeedbackPlayer::LoadFile, Dali::AnimatedImageLoading::LoadFrame, Dali::AnimatedImageLoading::LoadFramePlanes, Dali::WebEngine::LoadHtmlString, Dali::WebEngine::LoadHtmlStringOverrideCurrentEntry, Dali::StyleMonitor::LoadThemeFile, Dali::WebEngine::LoadUrl, Dali::DevelWindow::LockedPointerCursorPositionHintSet, Dali::DevelWindow::LockedPointerRegionSet, Dali::GlWindow::Lower, Dali::Window::Lower, Dali::VideoPlayer::LowerBelow, Dali::VideoPlayer::LowerToBottom, Dali::DevelWindow::Maximize, Dali::DevelWindow::MaximizeWithRestoreSize, Dali::DevelWindow::Minimize, Dali::DevelWindow::MouseInOutEventSignal, Dali::DevelWindow::MouseRelativeEventSignal, Dali::DevelWindow::MoveCompletedSignal, Dali::DevelWindow::MovedSignal, Dali::Devel::PixelBuffer::MultiplyColorByAlpha, Dali::AsyncTaskManager::NotifyToTaskReady, Dali::Clipboard::NumberOfItems, Dali::DevelWindow::OrientationChangedSignal, Dali::TtsPlayer::Pause, Dali::VideoPlayer::Pause, Dali::LifecycleController::PauseSignal, Dali::VideoPlayer::Play, Dali::TtsPlayer::Play, Dali::FeedbackPlayer::PlayFeedbackPattern, Dali::FeedbackPlayer::PlayFile, Dali::FeedbackPlayer::PlayMonotone, Dali::FeedbackPlayer::PlaySound, Dali::SoundPlayer::PlaySound, Dali::DevelWindow::PointerConstraintsLock, Dali::DevelWindow::PointerConstraintsSignal, Dali::DevelWindow::PointerConstraintsUnlock, Dali::DevelWindow::PointerWarp, Dali::LifecycleController::PreInitSignal, Dali::GlWindow::Raise, Dali::Window::Raise, Dali::VideoPlayer::RaiseAbove, Dali::VideoPlayer::RaiseToTop, Dali::CanvasRenderer::Rasterize, Dali::VectorImageRenderer::Rasterize, Dali::WebEngine::RegisterCertificateConfirmedCallback, Dali::WebEngine::RegisterConsoleMessageReceivedCallback, Dali::WebEngine::RegisterContextMenuHiddenCallback, Dali::WebEngine::RegisterContextMenuShownCallback, Dali::WebEngine::RegisterDeviceConnectionChangedCallback, Dali::WebEngine::RegisterDeviceListGetCallback, Dali::WebEngine::RegisterFileChooserRequestedCallback, Dali::WebEngine::RegisterFormRepostDecidedCallback, Dali::WebEngine::RegisterFrameRenderedCallback, Dali::WebEngine::RegisterFullscreenEnteredCallback, Dali::WebEngine::RegisterFullscreenExitedCallback, Dali::WebEngine::RegisterGeolocationPermissionCallback, Dali::GlWindow::RegisterGlCallbacks, Dali::WebEngine::RegisterHttpAuthHandlerCallback, Dali::WebEngine::RegisterJavaScriptAlertCallback, Dali::WebEngine::RegisterJavaScriptConfirmCallback, Dali::WebEngine::RegisterJavaScriptPromptCallback, Dali::WebEngine::RegisterNavigationPolicyDecidedCallback, Dali::WebEngine::RegisterNewWindowCreatedCallback, Dali::WebEngine::RegisterNewWindowPolicyDecidedCallback, Dali::WebEngine::RegisterOverScrolledCallback, Dali::WebEngine::RegisterPageLoadErrorCallback, Dali::WebEngine::RegisterPageLoadFinishedCallback, Dali::WebEngine::RegisterPageLoadInProgressCallback, Dali::WebEngine::RegisterPageLoadStartedCallback, Dali::WebEngine::RegisterResponsePolicyDecidedCallback, Dali::WebEngine::RegisterScrollEdgeReachedCallback, Dali::WebEngine::RegisterSslCertificateChangedCallback, Dali::WebEngine::RegisterTextFoundCallback, Dali::WebEngine::RegisterUrlChangedCallback, Dali::WebEngine::RegisterUserMediaPermissionRequestCallback, Dali::WebEngine::RegisterWebAuthDisplayQRCallback, Dali::WebEngine::RegisterWebAuthResponseCallback, Dali::WebEngine::RegisterWebProcessCrashedCallback, Dali::DevelWindow::RelativeMotionGrab, Dali::DevelWindow::RelativeMotionUnGrab, Dali::WebEngine::Reload, Dali::WebEngine::ReloadWithoutCache, Dali::Integration::SceneHolder::Remove, Dali::Window::Remove, Dali::CanvasRenderer::RemoveAllDrawables, Dali::GlWindow::RemoveAuxiliaryHint, Dali::Window::RemoveAuxiliaryHint, Dali::Window::RemoveAvailableOrientation, Dali::AsyncTaskManager::RemoveCompletedCallback, Dali::WebEngine::RemoveCustomHeader, Dali::CanvasRenderer::RemoveDrawable, Dali::DragAndDrop::RemoveListener, Dali::DragAndDrop::RemoveListener, Dali::AsyncTaskManager::RemoveTask, Dali::TextAbstraction::TextRenderer::Render, Dali::VectorAnimationRenderer::Render, Dali::GlWindow::RenderOnce, Dali::VectorAnimationRenderer::RenderStopped, Dali::TextAbstraction::BidirectionalSupport::Reorder, Dali::DevelWindow::RequestMoveToServer, Dali::DevelWindow::RequestResizeToServer, Dali::Devel::TextureUploadManager::RequestUpload, Dali::LifecycleController::ResetSignal, Dali::TextAbstraction::FontClient::ResetSystemDefaults, Dali::Devel::PixelBuffer::Resize, Dali::DevelWindow::ResizeCompletedSignal, Dali::GlWindow::ResizeSignal, Dali::Window::ResizeSignal, Dali::Devel::TextureUploadManager::ResourceUpload, Dali::TtsPlayer::Resume, Dali::WebEngine::Resume, Dali::WebEngine::ResumeNetworkLoading, Dali::LifecycleController::ResumeSignal, Dali::Devel::PixelBuffer::Rotate, Dali::VideoPlayer::SceneConnection, Dali::VideoPlayer::SceneDisconnection, Dali::WebEngine::ScrollBy, Dali::WebEngine::ScrollEdgeBy, Dali::WebEngine::SendHoverEvent, Dali::WebEngine::SendKeyEvent, Dali::DevelWindow::SendRotationCompletedAcknowledgement, Dali::WebEngine::SendTouchEvent, Dali::WebEngine::SendWheelEvent, Dali::Window::SetAcceptFocus, Dali::DevelWindow::SetAlwaysOnTop, Dali::VideoPlayer::SetAutoRotationEnabled, Dali::Window::SetAuxiliaryHintValue, Dali::GlWindow::SetAuxiliaryHintValue, Dali::GlWindow::SetAvailableOrientations, Dali::DevelWindow::SetAvailableOrientations, Dali::Window::SetBackgroundColor, Dali::Integration::SceneHolder::SetBackgroundColor, Dali::DevelWindow::SetBlur, Dali::DevelWindow::SetBottom, Dali::Window::SetBrightness, Dali::CameraPlayer::SetCameraPlayer, Dali::Window::SetClass, Dali::VideoPlayer::SetCodecType, Dali::AsyncTaskManager::SetCompletedCallback, Dali::TextAbstraction::FontClient::SetCurrentMaximumBlockSizeFitInAtlas, Dali::WebEngine::SetCursorThemeName, Dali::Clipboard::SetData, Dali::CameraPlayer::SetDisplayArea, Dali::VideoPlayer::SetDisplayArea, Dali::VideoPlayer::SetDisplayMode, Dali::VideoPlayer::SetDisplayRotation, Dali::WebEngine::SetDocumentBackgroundColor, Dali::TextAbstraction::FontClient::SetDpi, Dali::TextAbstraction::FontClient::SetDpiFromWindowSystem, Dali::WebEngine::SetFocus, Dali::DevelWindow::SetForceRendering, Dali::VideoPlayer::SetFrameInterpolationInterval, Dali::DevelWindow::SetFrontBufferRendering, Dali::DevelWindow::SetFullScreen, Dali::Integration::SceneHolder::SetGeometryHittestEnabled, Dali::GlWindow::SetGraphicsConfig, Dali::EncodedImageBuffer::SetImageType, Dali::WebEngine::SetImePositionAndAlignment, Dali::GlWindow::SetInputRegion, Dali::Window::SetInputRegion, Dali::Window::SetLayout, Dali::VideoPlayer::SetLetterBoxEnabled, Dali::VideoPlayer::SetLooping, Dali::DevelWindow::SetMaximumSize, Dali::DevelWindow::SetMimimumSize, Dali::DevelWindow::SetModal, Dali::VideoPlayer::SetMute, Dali::CameraPlayer::SetNativeImageRenderingTarget, Dali::DevelWindow::SetNeedsRotationCompletedAcknowledgement, Dali::Window::SetNotificationLevel, Dali::GlWindow::SetOpaqueState, Dali::Window::SetOpaqueState, Dali::WebEngine::SetPageZoomFactor, Dali::DevelWindow::SetParent, Dali::DevelWindow::SetParent, Dali::Window::SetPartialUpdateEnabled, Dali::VideoPlayer::SetPlayPosition, Dali::Window::SetPosition, Dali::GlWindow::SetPositionSize, Dali::DevelWindow::SetPositionSize, Dali::DevelWindow::SetPositionSizeWithOrientation, Dali::GlWindow::SetPreferredOrientation, Dali::Window::SetPreferredOrientation, Dali::VectorAnimationRenderer::SetRenderer, Dali::GlWindow::SetRenderingMode, Dali::VideoPlayer::SetRenderingTarget, Dali::TiltSensor::SetRotationThreshold, Dali::WebEngine::SetScaleFactor, Dali::DevelWindow::SetScreen, Dali::Window::SetScreenOffMode, Dali::WebEngine::SetScrollPosition, Dali::VectorAnimationRenderer::SetSize, Dali::WebEngine::SetSize, Dali::CanvasRenderer::SetSize, Dali::Window::SetSize, Dali::WebEngine::SetTextZoomFactor, Dali::StyleMonitor::SetTheme, Dali::WebEngine::SetTileCoverAreaMultiplier, Dali::Window::SetTransparency, Dali::Window::SetType, Dali::TiltSensor::SetUpdateFrequency, Dali::VideoPlayer::SetUrl, Dali::WebEngine::SetUserAgent, Dali::VideoPlayer::SetVideoFrameBuffer, Dali::WebEngine::SetVideoHole, Dali::CanvasRenderer::SetViewBox, Dali::WebEngine::SetVisibility, Dali::VideoPlayer::SetVolume, Dali::CameraPlayer::SetWindowRenderingTarget, Dali::TextAbstraction::Shaping::Shape, Dali::GlWindow::Show, Dali::Window::Show, Dali::Clipboard::ShowClipboard, Dali::SoundPlayer::SoundPlayFinishedSignal, Dali::TiltSensor::Start, Dali::DragAndDrop::StartDragAndDrop, Dali::WebEngine::StartInspectorServer, Dali::VideoPlayer::StartSynchronization, Dali::TtsPlayer::StateChangedSignal, Dali::PhysicalKeyboard::StatusChangedSignal, Dali::FeedbackPlayer::Stop, Dali::TiltSensor::Stop, Dali::TtsPlayer::Stop, Dali::VideoPlayer::Stop, Dali::SoundPlayer::Stop, Dali::WebEngine::StopInspectorServer, Dali::WebEngine::StopLoading, Dali::FeedbackPlayer::StopSound, Dali::StyleMonitor::StyleChangeSignal, Dali::WebEngine::Suspend, Dali::WebEngine::SuspendNetworkLoading, Dali::LifecycleController::TerminateSignal, Dali::StyleMonitor::ThemeChangedBeforeAdaptorInit, Dali::TiltSensor::TiltedSignal, Dali::GlWindow::TouchedSignal, Dali::Integration::SceneHolder::TouchedSignal, Dali::Window::TouchedSignal, Dali::DevelWindow::TransitionEffectEventSignal, Dali::DevelWindow::Unparent, Dali::WebEngine::UpdateDisplayArea, Dali::TextAbstraction::ICU::UpdateLineBreakInfoByLocale, Dali::VectorAnimationRenderer::UploadCompletedSignal, Dali::GlWindow::VisibilityChangedSignal, Dali::DevelWindow::VisibilityChangedSignal, Dali::WebEngine::WebAuthenticationCancel, Dali::Integration::SceneHolder::WheelEventGeneratedSignal, Dali::Integration::SceneHolder::WheelEventSignal, Dali::DevelWindow::WheelEventSignal.
const Internal::Adaptor::SceneHolder & Dali::GetImplementation(const Dali::Integration::SceneHolder &sceneHolder)