Dali::TextAbstraction
Script
Valid for all scripts. i.e white space or ' '.
Text must be broken into a new line.
Text can be broken into a new word.
GlyphType
Glyph stored as pixels.
ColorBlendingMode
No blend.
using Dali::TextAbstraction::CustomFontAddedSignalType = typedef Signal<void(const std::string&)>
typedef std::string Dali::TextAbstraction::FontPath
typedef std::string Dali::TextAbstraction::FontFamily
typedef std::string Dali::TextAbstraction::FontStyle
typedef std::vector<FontFamily> Dali::TextAbstraction::FontFamilyList
typedef std::vector<FontPath> Dali::TextAbstraction::FontPathList
typedef std::vector<FontDescription> Dali::TextAbstraction::FontList
typedef uint32_t Dali::TextAbstraction::FontId
The unique identifier for a font face (generated by FontClient)
typedef uint32_t Dali::TextAbstraction::PointSize26Dot6
The point size in 26.6 fractional points.
typedef uint32_t Dali::TextAbstraction::FaceIndex
Used with fonts which allow several font faces.
typedef uint32_t Dali::TextAbstraction::GlyphIndex
Uniquely identifies a glyph within a particular font.
typedef uint32_t Dali::TextAbstraction::Character
A UTF-32 representation of a character.
typedef uint32_t Dali::TextAbstraction::CharacterIndex
An index into an array of characters.
typedef uint32_t Dali::TextAbstraction::Length
The length of an array.
typedef uint32_t Dali::TextAbstraction::BidiInfoIndex
Index to the bidirectional info for a paragraph.
typedef char Dali::TextAbstraction::LineBreakInfo
Line break info (must break, allow break, no break).
typedef char Dali::TextAbstraction::WordBreakInfo
Word break info (break, no break).
typedef bool Dali::TextAbstraction::CharacterDirection
The character's direction: false is left to right, true is right to left.
typedef uint32_t Dali::TextAbstraction::ColorIndex
An index into an array of colors.
constexpr unsigned int Dali::TextAbstraction::CHAR_COMBINING_ENCLOSING_KEYCAP
Combining Enclosing Keycap. https://unicode-table.com/en/1F1E6/.
Referenced by IsCombiningEnclosingKeycap.
constexpr unsigned int Dali::TextAbstraction::CHAR_EMOJI_COMPONENT_BALD
Emoji CompOnent Bald. https://unicode-table.com/en/1F9B2/.
Referenced by IsEmojiComponent.
constexpr unsigned int Dali::TextAbstraction::CHAR_EMOJI_COMPONENT_RED_HAIR
Emoji CompOnent Red Hair. https://unicode-table.com/en/1F9B0/.
Referenced by IsEmojiComponent.
constexpr unsigned int Dali::TextAbstraction::CHAR_EMOJI_COMPONENT_CURLY_HAIR
Emoji CompOnent Curly Hair. https://unicode-table.com/en/1F9B1/.
Referenced by IsEmojiComponent.
constexpr unsigned int Dali::TextAbstraction::CHAR_EMOJI_COMPONENT_WHITE_HAIR
Emoji CompOnent White Hair. https://unicode-table.com/en/1F9B3/.
Referenced by IsEmojiComponent.
constexpr unsigned int Dali::TextAbstraction::CHAR_REGIONAL_INDICATOR_SYMBOL_LETTER_A
Regional Indicator Symbol Letter A. https://unicode-table.com/en/1F1E6/.
Referenced by IsRegionalIndicator.
constexpr unsigned int Dali::TextAbstraction::CHAR_REGIONAL_INDICATOR_SYMBOL_LETTER_Z
Regional Indicator Symbol Letter Z. https://unicode-table.com/en/1F1FF/.
Referenced by IsRegionalIndicator.
constexpr unsigned int Dali::TextAbstraction::CHAR_VARIATION_SELECTOR_15
Variation Selector-15. https://unicode-table.com/en/FE0E/.
Referenced by IsTextPresentationSelector.
constexpr unsigned int Dali::TextAbstraction::CHAR_VARIATION_SELECTOR_16
Variation Selector-16. https://unicode-table.com/en/FE0F/.
Referenced by IsEmojiPresentationSelector.
constexpr unsigned int Dali::TextAbstraction::CHAR_CANCEL_TAG
Stateful tag terminator: Cancel Tag. https://unicode-table.com/en/E007F/.
Referenced by IsTagEnd.
constexpr unsigned int Dali::TextAbstraction::CHAR_TAG_SPACE
Tag components: Tag Space. The first tag in tag_spec https://unicode-table.com/en/E0020/.
Referenced by IsTagSpec.
constexpr unsigned int Dali::TextAbstraction::CHAR_TAG_TILDE
Tag components: Tag Tilde. The last tag in tag_spec https://unicode-table.com/en/E007E/.
Referenced by IsTagSpec.
constexpr unsigned int Dali::TextAbstraction::CHAR_EMOJI_MODIFIER_FITZPATRICK_TYPE_1_2
Emoji Modifier Fitzpatrick Type-1-2 (Light Skin Tone). https://unicode-table.com/en/1F3FB/.
Referenced by IsEmojiModifier.
constexpr unsigned int Dali::TextAbstraction::CHAR_EMOJI_MODIFIER_FITZPATRICK_TYPE_3
Emoji Modifier Fitzpatrick Type-3 (Medium-Light Skin Tone). https://unicode-table.com/en/1F3FC/.
constexpr unsigned int Dali::TextAbstraction::CHAR_EMOJI_MODIFIER_FITZPATRICK_TYPE_4
Emoji Modifier Fitzpatrick Type-4 (Medium Skin Tone). https://unicode-table.com/en/1F3FD/.
constexpr unsigned int Dali::TextAbstraction::CHAR_EMOJI_MODIFIER_FITZPATRICK_TYPE_5
Emoji Modifier Fitzpatrick Type-5 (Medium-Dark Skin Tone). https://unicode-table.com/en/1F3FE/.
constexpr unsigned int Dali::TextAbstraction::CHAR_EMOJI_MODIFIER_FITZPATRICK_TYPE_6
Emoji Modifier Fitzpatrick Type-6 (Dark Skin Tone). https://unicode-table.com/en/1F3FF/.
Referenced by IsEmojiModifier.
constexpr unsigned int Dali::TextAbstraction::CHAR_NORTH_EAST_WHITE_ARROW
North East White Arrow. https://unicode-table.com/en/2B00/.
Referenced by IsMiscellaneousSymbolsAndArrowsEmoji.
constexpr unsigned int Dali::TextAbstraction::CHAR_HELLSCHREIBER_PAUSE_SYMBOL
Hellschreiber Pause Symbol . https://unicode-table.com/en/2BFF/.
Referenced by IsMiscellaneousSymbolsAndArrowsEmoji.
constexpr unsigned int Dali::TextAbstraction::CHAR_BLACK_SAFETY_SCISSORS
Black Safety Scissors. https://unicode-table.com/en/2700/.
Referenced by IsDingbatsEmoji.
constexpr unsigned int Dali::TextAbstraction::CHAR_DOUBLE_CURLY_LOOP_EMOJI
Double Curly Loop Emoji . https://unicode-table.com/en/27BF/.
Referenced by IsDingbatsEmoji.
constexpr unsigned int Dali::TextAbstraction::CHAR_NUMBER_SIGN
Number Sign. https://unicode-table.com/en/0023/
constexpr unsigned int Dali::TextAbstraction::CHAR_ASTERISK
Asterisk. https://unicode-table.com/en/002A/
constexpr unsigned int Dali::TextAbstraction::CHAR_ASCII_DIGIT_0
0 Digit Zero. https://unicode-table.com/en/0030/
Referenced by IsASCIIDigits.
constexpr unsigned int Dali::TextAbstraction::CHAR_ASCII_DIGIT_9
9 Digit Nine. https://unicode-table.com/en/0039/
Referenced by IsASCIIDigits.
constexpr unsigned int Dali::TextAbstraction::CHAR_ASCII_SPACE
Space. https://unicode-table.com/en/0020/.
constexpr unsigned int Dali::TextAbstraction::CHAR_ASCII_SOLIDUS
/ Solidus. https://unicode-table.com/en/002F/
constexpr unsigned int Dali::TextAbstraction::CHAR_ASCII_COLON
: Colon. https://unicode-table.com/en/003A/
constexpr unsigned int Dali::TextAbstraction::CHAR_ASCII_COMMERCIAL_AT
@ Commercial At. https://unicode-table.com/en/0040/
constexpr unsigned int Dali::TextAbstraction::CHAR_ASCII_LEFT_SQUARE_BRACKET
[ Left Square Bracket. https://unicode-table.com/en/005B/
constexpr unsigned int Dali::TextAbstraction::CHAR_ASCII_GRAVE_ACCENT
` Grave Accent. https://unicode-table.com/en/0060/
constexpr unsigned int Dali::TextAbstraction::CHAR_ASCII_LEFT_CURLY_BRACKET
{ Left Curly Bracket. https://unicode-table.com/en/007B/
constexpr unsigned int Dali::TextAbstraction::CHAR_ASCII_TILDE
~ Tilde. https://unicode-table.com/en/007E/
constexpr unsigned int Dali::TextAbstraction::CHAR_ZWS
Zero width space.
Referenced by GetUnicodeForInvisibleGlyph, IsZeroWidthSpace.
bool Dali::TextAbstraction::TEXT_PERFORMANCE_LOG_SET
Referenced by Dali::TextAbstraction::FontClient::GetPerformanceLogThresholdTime.
uint32_t Dali::TextAbstraction::TEXT_PERFORMANCE_LOG_THRESHOLD_TIME
Referenced by Dali::TextAbstraction::FontClient::GetPerformanceLogThresholdTime.
constexpr auto Dali::TextAbstraction::TEXT_PERFORMANCE_LOG_THRESHOLD_TIME_ENV
Referenced by Dali::TextAbstraction::FontClient::GetPerformanceLogThresholdTime.
const char* const Dali::TextAbstraction::ScriptName[][]
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsEmojiComponent(Character character)
Whether the character is emoji component. Emoji Properties and Data Files: https://www.unicode.org/reports/tr51/#Emoji_Properties_and_Data_Files.
True for characters used in emoji sequences that normally do not appear on emoji keyboards as separate choices, such as keycap base characters or Regional_Indicator characters. character The character. true if the character is emoji component.
References CHAR_EMOJI_COMPONENT_BALD, CHAR_EMOJI_COMPONENT_CURLY_HAIR, CHAR_EMOJI_COMPONENT_RED_HAIR, CHAR_EMOJI_COMPONENT_WHITE_HAIR.
Referenced by IsEmojiItem.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsEmojiModifier(Character character)
Whether the character is emoji modifier. Emoji Properties and Data Files: https://www.unicode.org/reports/tr51/#Emoji_Properties_and_Data_Files.
character The character. true if the character is emoji modifier.
References CHAR_EMOJI_MODIFIER_FITZPATRICK_TYPE_1_2, CHAR_EMOJI_MODIFIER_FITZPATRICK_TYPE_6.
Referenced by IsEmojiItem.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsCombiningEnclosingKeycap(Character character)
Whether the character is COMBINING ENCLOSING KEYCAP. Combining Enclosing Keycap: https://emojipedia.org/combining-enclosing-keycap/.
The Codepoint of COMBINING ENCLOSING KEYCAP is {U+20E3} character The character. true if the character is COMBINING ENCLOSING KEYCAP.
References CHAR_COMBINING_ENCLOSING_KEYCAP.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsRegionalIndicator(Character character)
Whether the character is Regional Indicator. Regional Indicator Symbol Letter A: https://emojipedia.org/regional-indicator-symbol-letter-a/ Regional Indicator Symbol Letter Z: https://emojipedia.org/regional-indicator-symbol-letter-z/.
The Codepoints of Regional Indicator Symbol Letters [A-Z] are [U+1F1E6 - U+1F1FF] character The character. true if the character is Regional Indicator.
References CHAR_REGIONAL_INDICATOR_SYMBOL_LETTER_A, CHAR_REGIONAL_INDICATOR_SYMBOL_LETTER_Z.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsTextPresentationSelector(Character character)
Whether the character is text presentation selector (VARIATION SELECTOR-15). Text Presentation Selector: https://www.unicode.org/reports/tr51/#def_text_presentation_selector.
The character U+FE0E VARIATION SELECTOR-15 (VS15), used to request a text presentation for an emoji character. Also known as text variation selector. character The character. true if the character is text presentation selector (VARIATION SELECTOR-15).
References CHAR_VARIATION_SELECTOR_15.
Referenced by GetCharacterScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsEmojiPresentationSelector(Character character)
Whether the character is emoji variation selector (VARIATION SELECTOR-16). Emoji Presentation Selector: https://www.unicode.org/reports/tr51/#def_emoji_presentation_selector.
The character U+FE0F VARIATION SELECTOR-16 (VS16), used to request an emoji presentation for an emoji character. Also known as emoji variation selector. character The character. true if the character is emoji presentation selector (VARIATION SELECTOR-16).
References CHAR_VARIATION_SELECTOR_16.
Referenced by GetCharacterScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsTagSpec(Character character)
Whether the character is tag spec. Emoji Tag Sequence (ETS): https://www.unicode.org/reports/tr51/#def_emoji_tag_sequence.
The tag_spec consists of all characters from U+E0020 TAG SPACE to U+E007E TAG TILDE. Each tag_spec defines a particular visual variant to be applied to the tag_base character(s). Though tag_spec includes the values U+E0041 TAG LATIN CAPITAL LETTER A .. U+E005A TAG LATIN CAPITAL LETTER Z, they are not used currently and are reserved for future extensions. character The character. true if the character is tag spec.
References CHAR_TAG_SPACE, CHAR_TAG_TILDE.
Referenced by IsEmojiItem.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsTagEnd(Character character)
Whether the character is tag end. Emoji Tag Sequence (ETS): https://www.unicode.org/reports/tr51/#def_emoji_tag_sequence.
The tag_end consists of the character U+E007F CANCEL TAG, and must be used to terminate the tag sequence. character The character. true if the character is tag end.
References CHAR_CANCEL_TAG.
Referenced by IsEmojiItem.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsEmojiItem(Character character)
Whether the character is emoji-component | emoji-modifier | COMBINING-ENCLOSING-KEYCAP | regional-indicator | TextPresentationSelector | EmojiPresentationSelector | TagSpec | TagEnd.
character The character true if the character is emoji-component | emoji-modifier | COMBINING-ENCLOSING-KEYCAP | regional-indicator | TextPresentationSelector | EmojiPresentationSelector | TagSpec | TagEnd.
References IsEmojiComponent, IsEmojiModifier, IsTagEnd, IsTagSpec.
Referenced by GetCharacterScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsMiscellaneousSymbolsAndArrowsEmoji(Character character)
Whether the character is Miscellaneous Symbols and Arrows emoji. Miscellaneous Symbols and Arrows emoji: https://unicode-table.com/en/blocks/miscellaneous-symbols-and-arrows/.
The Range is 2B00—2BFF and the quantity of characters is 256. character The character. true if the character is Miscellaneous Symbols and Arrows emoji.
References CHAR_HELLSCHREIBER_PAUSE_SYMBOL, CHAR_NORTH_EAST_WHITE_ARROW.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsDingbatsEmoji(Character character)
Whether the character is Dingbats emoji. Dingbats emoji: https://unicode-table.com/en/blocks/dingbats/.
The Range is 2700—27BF and the quantity of characters is 192. character The character. true if the character is Dingbats emoji.
References CHAR_BLACK_SAFETY_SCISSORS, CHAR_DOUBLE_CURLY_LOOP_EMOJI.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsASCIIDigits(Character character)
Whether the character is ASCII digits. ASCII digits: https://unicode-table.com/en/blocks/basic-latin/.
The Range is 0030—0039 and the quantity of characters is 10. character The character. true if the character is ASCII digits.
References CHAR_ASCII_DIGIT_0, CHAR_ASCII_DIGIT_9.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsASCIIPS(Character character)
Whether the character is ASCII PS. ASCII PS: https://unicode-table.com/en/blocks/basic-latin/.
The Range is 0020-007E character The character. true if the character is ASCII PS.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsEmojiVariationSequences(Character character)
Whether the character is emoji-variation-sequences. Emoji Variation Sequences for UTS #51: https://www.unicode.org/Public/14.0.0/ucd/emoji/emoji-variation-sequences.txt.
character The character. true if the character is emoji-variation-sequences.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsNegativeSquaredLatinCapitalLetter(Character character)
Whether the character is Negative Squared Latin Capital Letter. Read more at White on black squared Latin letters: https://unicode-table.com/en/blocks/enclosed-alphanumeric-supplement/.
character The character. true if the character is Negative Squared Latin Capital Letter.
Referenced by GetCharacterScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsSymbolScript(const TextAbstraction::Script &script)
Whether the script is symbol.
Check whether the script is in [SYMBOLS1, SYMBOLS2, SYMBOLS3, SYMBOLS4, SYMBOLS5] script The script. true if the script is symbol.
References SYMBOLS1, SYMBOLS2, SYMBOLS3, SYMBOLS4, SYMBOLS5, SYMBOLS_NSLCL.
Referenced by IsSymbolOrEmojiOrTextScript, IsSymbolOrEmojiScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsEmojiScript(const TextAbstraction::Script &script)
Whether the script is EMOJI.
script The script. true if the script is EMOJI.
References EMOJI.
Referenced by IsOneOfEmojiScripts, IsSymbolOrEmojiScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsEmojiTextScript(const TextAbstraction::Script &script)
Whether the script is EMOJI_TEXT.
script The script. true if the script is EMOJI_TEXT.
References EMOJI_TEXT.
Referenced by IsOneOfEmojiScripts.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsEmojiColorScript(const TextAbstraction::Script &script)
Whether the script is EMOJI_COLOR.
script The script. true if the script is EMOJI_COLOR.
References EMOJI_COLOR.
Referenced by IsOneOfEmojiScripts.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsOneOfEmojiScripts(const TextAbstraction::Script &script)
Whether the script is EMOJI | EMOJI_COLOR| EMOJI_TEXT.
script The script. true if the script is EMOJI | EMOJI_COLOR| EMOJI_TEXT.
References IsEmojiColorScript, IsEmojiScript, IsEmojiTextScript.
Referenced by IsSymbolOrEmojiOrTextScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsSymbolOrEmojiScript(const TextAbstraction::Script &script)
Whether the script is symbol or emoji.
At least one of IsSymbol and IsEmoji is true. script The script. true if the script is symbol or emoji.
References IsEmojiScript, IsSymbolScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsSymbolOrEmojiOrTextScript(const TextAbstraction::Script &script)
Whether the script is SYMBOL | EMOJI | TEXT.
At least one of IsSymbol and IsEmoji and IsText is true. script The script. true if the script is SYMBOL | EMOJI | EMOJI_COLOR| EMOJI_TEXT.
References IsOneOfEmojiScripts, IsSymbolScript.
DALI_ADAPTOR_API Character Dali::TextAbstraction::GetUnicodeForInvisibleGlyph()
Retrieve the unicode for invisible glyphs.
Used CHAR_ZWS it is the unicode for Zero Width Space character Retrieve the unicode for Zero Width Space character
References CHAR_ZWS.
DALI_ADAPTOR_API FontClient Dali::TextAbstraction::FontClientPreInitialize()
This is used to improve application launch performance.
A pre-initialized FontClient
DALI_ADAPTOR_API void Dali::TextAbstraction::FontClientPreCache(const FontFamilyList &fallbackFamilyList, const FontFamilyList &extraFamilyList, const FontFamily &localeFamily, bool useThread, bool syncCreation)
This is used to pre-cache FontConfig in order to improve the runtime performance of the application.
fallbackFamilyList A list of fallback font families to be pre-cached. extraFamilyList A list of additional font families to be pre-cached. localeFamily A locale font family to be pre-cached. useThread True if the font client should create thread and perform pre-caching, false otherwise. syncCreation True if thread creation guarantees syncronization with the main thread, false async creation.
DALI_ADAPTOR_API void Dali::TextAbstraction::FontClientFontPreLoad(const FontPathList &fontPathList, const FontPathList &memoryFontPathList, bool useThread, bool syncCreation)
This is used to pre-load FreeType font face in order to improve the runtime performance of the application.
fontPathList A list of font paths to be pre-loaded. memoryFontPathList A list of memory font paths to be pre-loaded. useThread True if the font client should create thread and perform font pre-loading, false otherwise. syncCreation True if thread creation guarantees syncronization with the main thread, false async creation. The fonts in the fontPathList perform FT_New_Face during pre-loading, which can provide some performace benefits. The fonts in the memoryFontPathList read the font file and cache the buffer in memory during pre-load. This enables the use of FT_New_Memory_Face during runtime and provides a performance boost. It requires memory equivalent to the size of each font file.
DALI_ADAPTOR_API void Dali::TextAbstraction::FontClientJoinFontThreads()
Joins font threads, waiting for their execution to complete.
DALI_ADAPTOR_API void Dali::TextAbstraction::EnsureLocale()
Ensure the locale of the font client.
If there is no locale information, update it using setlocale().
DALI_ADAPTOR_API const std::string & Dali::TextAbstraction::GetLocale()
Gets the current language.
Returns the language code. (e.g., "en") The current language.
DALI_ADAPTOR_API const std::string & Dali::TextAbstraction::GetLocaleFull()
Gets the current locale identifier.
Returns the locale identifier. (e.g., "en_US") The current locale identifier.
DALI_ADAPTOR_API void Dali::TextAbstraction::SetLocale(const std::string &locale)
Sets the current locale.
Update language and locale identifier. locale The current locale.
DALI_ADAPTOR_API void Dali::TextAbstraction::EnableDesignCompatibility()
Enable font specific design compatibility mode globally.
When enabled, FontMetrics will adjust ascender/descender values at construction to ensure design compatibility rules. This is a one-way switch. Once enabled, it cannot be disabled again during the lifetime of the process. This function must be called before any text is rendered.
DALI_ADAPTOR_API bool Dali::TextAbstraction::DesignCompatibilityEnabled()
Whether DesignCompatibility is enabled or not.
Referenced by Dali::TextAbstraction::FontMetrics::FontMetrics.
DALI_ADAPTOR_API std::ostream & Dali::TextAbstraction::operator<<(std::ostream &o, const FontList &fontList)
References Dali::TextAbstraction::FontDescription::path, Dali::TextAbstraction::FontDescription::slant, Dali::TextAbstraction::FontDescription::weight, Dali::TextAbstraction::FontDescription::width.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsRightToLeftScript(Script script)
Whether the script is a right to left script.
script The script. true if the script is right to left.
References ARABIC, HEBREW.
DALI_ADAPTOR_API Script Dali::TextAbstraction::GetCharacterScript(Character character)
Retrieves a character's script.
character The character. The chraracter's script.
References COMMON, EMOJI, EMOJI_COLOR, EMOJI_TEXT, IsCommonScript, IsEmojiItem, IsEmojiPresentationSelector, IsNegativeSquaredLatinCapitalLetter, IsTextPresentationSelector, SYMBOLS_NSLCL, UNKNOWN.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsWhiteSpace(Character character)
Whether the character is a white space.
character The character. true if the character is a white space.
Referenced by IsCommonScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsSpace(Character character)
Whether the character is a space.
character The character. true if the character is a space.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsNewParagraph(Character character)
Whether the character is a new paragraph character.
character The character. true if the character is a new paragraph character.
Referenced by IsCommonScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsZeroWidthNonJoiner(Character character)
Whether the character is a zero width non joiner.
character The character. true if the character is a zero width non joiner.
Referenced by IsCommonScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsZeroWidthJoiner(Character character)
Whether the character is a zero width joiner.
character The character. true if the character is a zero width joiner.
Referenced by IsCommonScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsZeroWidthSpace(Character character)
Whether the character is a zero width space.
character The character. true if the character is a zero width space.
References CHAR_ZWS.
Referenced by IsCommonScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsLeftToRightMark(Character character)
Whether the character is a left to right mark.
character The character. true if the character is a left to right mark.
Referenced by IsCommonScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsRightToLeftMark(Character character)
Whether the character is a right to left mark.
character The character. true if the character is a right to left mark.
Referenced by IsCommonScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsThinSpace(Character character)
Whether the character is a thin space.
character The character. true if the character is a thin space.
Referenced by IsCommonScript.
bool Dali::TextAbstraction::IsByteOrderMark(Character character)
Referenced by IsCommonScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsCommonScript(Character character)
Whether the character is common within all scripts.
character The character. true if the character is common within all scripts.
References IsByteOrderMark, IsCombiningDiacriticalMarks, IsLeftToRightMark, IsNewParagraph, IsRightToLeftMark, IsThinSpace, IsWhiteSpace, IsZeroWidthJoiner, IsZeroWidthNonJoiner, IsZeroWidthSpace.
Referenced by GetCharacterScript.
DALI_ADAPTOR_API bool Dali::TextAbstraction::HasLigatureMustBreak(Script script)
Whether the script contains ligatures that must be 'broken' for selection or cursor position.
i.e The latin script has the 'ff' or 'fi' ligatures that need to be broken to position the cursor between the two characters. Equally the arabic script has the 'ﻻ' ligature that needs to be broken. script The script. true if the script has ligatures that must be 'broken'.
References ARABIC, LATIN.
DALI_ADAPTOR_API Length Dali::TextAbstraction::GetNumberOfScripts()
Get the number of elements in enum Script.
returns the number of Scripts
References SYMBOLS_NSLCL.
DALI_ADAPTOR_API bool Dali::TextAbstraction::IsCombiningDiacriticalMarks(Character character)
Whether the character is a combining diacritical marks.
character The character. true if the character is a combining diacritical marks.
Referenced by IsCommonScript.
DALI_ADAPTOR_API void Dali::TextAbstraction::TransformToArc(const CircularTextParameters &parameters, double &x, double &y)
Transforms a vertex to wrap a circular path.
parameters The parameters of the circular path. x The 'x' coordinate of the vertex. y The 'y' coordinate of the vertex.
References Dali::TextAbstraction::CircularTextParameters::beginAngle, Dali::TextAbstraction::CircularTextParameters::centerX, Dali::TextAbstraction::CircularTextParameters::centerY, Dali::TextAbstraction::FontClient::DEFAULT_ITALIC_ANGLE, Dali::TextAbstraction::CircularTextParameters::invRadius, Dali::TextAbstraction::CircularTextParameters::isClockwise, Dali::TextAbstraction::CircularTextParameters::radius, Dali::TextAbstraction::CircularTextParameters::synthesizeItalic.