Dali::Accessibility::Bridge
ForceUpResult
AutoInitState
std::shared_ptr<Data> Dali::Accessibility::Bridge::mData
Referenced by ForceDown.
friend class Accessible
AutoInitState Dali::Accessibility::Bridge::mAutoInitState
bool Dali::Accessibility::Bridge::mBridgeInitialized
Become true if bridge creation API called at least 1 time.
bool Dali::Accessibility::Bridge::mBridgeTerminated
Become false if bridge destruction API called at least 1 time.
Signal<void()> Dali::Accessibility::Bridge::mEnabledSignal
Signal<void()> Dali::Accessibility::Bridge::mDisabledSignal
Signal<void()> Dali::Accessibility::Bridge::mScreenReaderEnabledSignal
Signal<void()> Dali::Accessibility::Bridge::mScreenReaderDisabledSignal
Dali::Accessibility::Bridge::Bridge()
Constructor.
virtual Dali::Accessibility::Bridge::~Bridge()
Destructor.
virtual bool Dali::Accessibility::Bridge::AddAccessible(uint32_t actorId, std::shared_ptr< Accessible > accessible)=0
Adds the accessible object associated with given actorId to the brige.
actorId The actorId assosiated with the accessible accessible The accessible object true if given accessible is added to the bridge
virtual void Dali::Accessibility::Bridge::RemoveAccessible(uint32_t actorId)=0
Removed the accessible object associated with given actorId from the brige.
virtual std::shared_ptr< Accessible > Dali::Accessibility::Bridge::GetAccessible(Actor actor) const =0
Gets the accessible object associated with given actor from the bridge.
virtual std::shared_ptr< Accessible > Dali::Accessibility::Bridge::GetAccessible(const std::string &path) const =0
Gets the accessible object associated with given path from the bridge.
virtual bool Dali::Accessibility::Bridge::ShouldIncludeHidden() const =0
Returns true if GetChildren should include hidden objects; false otherwise.
virtual const std::string & Dali::Accessibility::Bridge::GetBusName() const =0
Gets bus name which bridge is initialized on.
The bus name
virtual void Dali::Accessibility::Bridge::AddTopLevelWindow(Accessible *object)=0
Registers top level window.
Hierarchy of objects visible for accessibility clients is based on tree-like structure created from Actors objects. This method allows to connect chosen object as direct ancestor of application and therefore make it visible for accessibility clients. object The accessible object
virtual void Dali::Accessibility::Bridge::RemoveTopLevelWindow(Accessible *object)=0
Removes top level window.
Hierarchy of objects visible for accessibility clients is based on tree-like structure created from Actors objects. This method removes previously added window from visible accessibility objects. object The accessible object
virtual void Dali::Accessibility::Bridge::RegisterDefaultLabel(Dali::Actor actor)=0
Adds object on the top of the stack of "default label" sourcing objects.
GetDefaultLabel actor The actor to set a default label
virtual void Dali::Accessibility::Bridge::UnregisterDefaultLabel(Dali::Actor actor)=0
Removes object from the stack of "default label" sourcing objects.
GetDefaultLabel actor The actor to unset a default label
virtual Accessible * Dali::Accessibility::Bridge::GetDefaultLabel(Accessible *root)=0
Gets the top-most object from the stack of "default label" sourcing objects.
The "default label" is a reading material (text) derived from an accesibility object that could be read by screen-reader immediately after the navigation context has changed (window activates, popup shows up, tab changes) and before first UI element is highlighted. root The root of the navigation context for which to retrieve the default label. The handler to accessibility object This is a Tizen only feature not present in upstream ATSPI. Feature can be enabled/disabled for particular context root object by setting value of its accessibility attribute "default_label". Following strings are valid values for "default_label" attribute: "enabled", "disabled". Any other value will be interpreted as "enabled".
virtual void Dali::Accessibility::Bridge::SetApplicationName(std::string name)=0
Sets name of current application which will be visible on accessibility bus.
name The application name
virtual void Dali::Accessibility::Bridge::SetToolkitName(std::string_view toolkitName)=0
Sets the name of the GUI toolkit that AT-SPI clients can query.
The default name is "dali". toolkitName The toolkit name
virtual Accessible * Dali::Accessibility::Bridge::GetApplication() const =0
Gets object being root of accessibility tree.
handler to accessibility object
virtual Accessible * Dali::Accessibility::Bridge::FindByPath(const std::string &path) const =0
Finds an object in accessibility tree.
path The path to object The handler to accessibility object
virtual void Dali::Accessibility::Bridge::WindowCreated(Window window)=0
Notifies accessibility dbus that window has just been created.
window The window to be created
virtual void Dali::Accessibility::Bridge::WindowShown(Window window)=0
Notifies accessibility dbus that window has just been shown.
window The window to be shown
virtual void Dali::Accessibility::Bridge::WindowHidden(Window window)=0
Notifies accessibility dbus that window has just been hidden.
window The window to be hidden
virtual void Dali::Accessibility::Bridge::WindowFocused(Window window)=0
Notifies accessibility dbus that window has just been focused.
window The window to be focused
virtual void Dali::Accessibility::Bridge::WindowUnfocused(Window window)=0
Notifies accessibility dbus that window has just been out of focus.
window The window to be out of focus
virtual void Dali::Accessibility::Bridge::WindowMinimized(Window window)=0
Notifies accessibility dbus that window has just been minimized.
window The window to be minimized
virtual void Dali::Accessibility::Bridge::WindowRestored(Window window, WindowRestoreType detail)=0
Notifies accessibility dbus that window has just been restored.
window The window to be restored detail Restored window state
virtual void Dali::Accessibility::Bridge::WindowMaximized(Window window)=0
Notifies accessibility dbus that window has just been maximized.
window The window to be maximized
virtual void Dali::Accessibility::Bridge::ApplicationPaused()=0
Tells the bridge that the application is not running.
virtual void Dali::Accessibility::Bridge::ApplicationResumed()=0
Tells the bridge that the application is running.
virtual void Dali::Accessibility::Bridge::Initialize()=0
Initializes accessibility bus.
virtual void Dali::Accessibility::Bridge::Terminate()=0
Terminates accessibility bus.
virtual ForceUpResult Dali::Accessibility::Bridge::ForceUp()
This method is called, when bridge is being activated.
void Dali::Accessibility::Bridge::ForceDown()=0
This method is called, when bridge is being deactivated.
References Dali::Accessibility::Accessible::Get, Dali::Accessibility::Accessible::GetCurrentlyHighlightedActor, mData.
bool Dali::Accessibility::Bridge::IsUp() const
Checks if bridge is activated or not.
True if brige is activated.
virtual void Dali::Accessibility::Bridge::EmitCursorMoved(Accessible *obj, unsigned int cursorPosition)=0
Emits cursor-moved event on at-spi bus.
obj The accessible object cursorPosition The new cursor position
virtual void Dali::Accessibility::Bridge::EmitActiveDescendantChanged(Accessible *obj, Accessible *child)=0
Emits active-descendant-changed event on at-spi bus.
obj The accessible object child The child of the object
virtual void Dali::Accessibility::Bridge::EmitTextChanged(Accessible *obj, TextChangedState state, unsigned int position, unsigned int length, const std::string &content)=0
Emits text-changed event on at-spi bus.
obj The accessible object state The changed state for text, such as Inserted or Deleted position The cursor position length The text length content The changed text
virtual void Dali::Accessibility::Bridge::EmitMovedOutOfScreen(Accessible *obj, ScreenRelativeMoveType type)=0
Emits MoveOuted event on at-spi bus.
obj Accessible object type Direction type when an Accessible object moves out of screen
virtual void Dali::Accessibility::Bridge::EmitScrollStarted(Accessible *obj)=0
Emits ScrollStarted event on at-spi bus.
obj Accessible Object
virtual void Dali::Accessibility::Bridge::EmitScrollFinished(Accessible *obj)=0
Emits ScrollFinished event on at-spi bus.
obj Accessible Object
virtual void Dali::Accessibility::Bridge::EmitStateChanged(std::shared_ptr< Accessible > obj, State state, int newValue, int reserved=0)=0
Emits state-changed event on at-spi bus.
obj The accessible object state The accessibility state (SHOWING, HIGHLIGHTED, etc) newValue Whether the state value is changed to new value or not. reserved Reserved. (Currently, this argument is not implemented in dali)
virtual void Dali::Accessibility::Bridge::Emit(Accessible *obj, WindowEvent event, unsigned int detail=0)=0
Emits window event on at-spi bus.
obj The accessible object event The enumerated window event detail The additional parameter which interpretation depends on chosen event
virtual void Dali::Accessibility::Bridge::Emit(std::shared_ptr< Accessible > obj, ObjectPropertyChangeEvent event)=0
Emits property-changed event on at-spi bus.
obj The accessible object event Property changed event
virtual void Dali::Accessibility::Bridge::EmitBoundsChanged(std::shared_ptr< Accessible > obj, Rect< int > rect)=0
Emits bounds-changed event on at-spi bus.
obj The accessible object rect The rectangle for changed bounds
virtual void Dali::Accessibility::Bridge::EmitPostRender(std::shared_ptr< Accessible > obj)=0
Emits org.a11y.atspi.Event.Window.PostRender on the AT-SPI bus.
obj The Accessible sender object The sender of this event is expected to be an Accessible object that represents a top-level window. The actual number of events emitted during a given time interval may be smaller than the number of calls to this method, but at least one is guaranteed.
virtual bool Dali::Accessibility::Bridge::EmitKeyEvent(Dali::KeyEvent keyEvent, std::function< void(Dali::KeyEvent, bool)> callback)=0
Emits key event on at-spi bus.
Screen-reader might receive this event and reply, that given keycode is consumed. In that case further processing of the keycode should be ignored. keyEvent The key event callback Notification if the event was consumed true if the event was emitted
virtual void Dali::Accessibility::Bridge::Say(const std::string &text, bool discardable, std::function< void(std::string)> callback)=0
Reads given text by screen reader.
text The text to read discardable If TRUE, reading can be discarded by subsequent reading requests, if FALSE the reading must finish before next reading request can be started callback the callback function that is called on reading signals emitted during processing of this reading request. Callback can be one of the following signals: ReadingCancelled, ReadingStopped, ReadingSkipped
virtual void Dali::Accessibility::Bridge::Pause()=0
Force accessibility client to pause.
virtual void Dali::Accessibility::Bridge::Resume()=0
Force accessibility client to resume.
virtual void Dali::Accessibility::Bridge::StopReading(bool alsoNonDiscardable)=0
Cancels anything screen-reader is reading / has queued to read.
alsoNonDiscardable whether to cancel non-discardable readings as well
virtual void Dali::Accessibility::Bridge::SuppressScreenReader(bool suppress)=0
Suppresses reading of screen-reader.
suppress whether to suppress reading of screen-reader
virtual bool Dali::Accessibility::Bridge::GetScreenReaderEnabled()=0
Gets screen reader status.
True if screen reader is enabled
virtual bool Dali::Accessibility::Bridge::IsEnabled()=0
Gets ATSPI status.
True if ATSPI is enabled
virtual Address Dali::Accessibility::Bridge::EmbedSocket(const Address &plug, const Address &socket)=0
Calls socket.Embed(plug) via D-Bus.
plug The plug socket The socket Address returned by the D-Bus call. Remote object pointed to by 'socket' must implement 'org.a11y.atspi.Socket'. UnembedSocket()
virtual void Dali::Accessibility::Bridge::UnembedSocket(const Address &plug, const Address &socket)=0
Calls socket.Unmbed(plug) via D-Bus.
plug The plug socket The socket Remote object pointed to by 'socket' must implement 'org.a11y.atspi.Socket'. EmbedSocket()
virtual void Dali::Accessibility::Bridge::SetSocketOffset(ProxyAccessible *socket, std::int32_t x, std::int32_t y)=0
Calls socket.SetOffset(x, y) via D-Bus.
The "SetOffset" D-Bus method is a DALi extension. It can be used to inform a DALi widget about its position on the screen. socket The socket x Horizontal offset y Vertical offset Remote object pointed to by 'socket' must implement 'org.a11y.atspi.Socket'. EmbedSocket() SetExtentsOffset()
virtual void Dali::Accessibility::Bridge::SetExtentsOffset(std::int32_t x, std::int32_t y)=0
Sets the global extents offset.
This offset will be added during serialization of GetExtents() return value to D-Bus. Local calls to GetExtents() are unaffected. x Horizontal offset y Vertical offset SetSocketOffset() Dali::Accessibility::Component::GetExtents()
virtual void Dali::Accessibility::Bridge::SetPreferredBusName(std::string_view preferredBusName)=0
Sets the preferred bus name.
If the Bridge is enabled, it will immediately release the previous name and request the new one. Otherwise, the Bridge will request this name on AT-SPI activation (and release it on deactivation). It is up to the caller to determine whether a given name will be available in the system. preferredBusName The preferred bus name
static std::shared_ptr< Bridge > Dali::Accessibility::Bridge::GetCurrentBridge()
Returns instance of bridge singleton object.
The current bridge object
Referenced by Dali::Accessibility::ActorAccessible::Emit, Dali::Accessibility::ActorAccessible::Emit, Dali::Accessibility::ActorAccessible::EmitActiveDescendantChanged, Dali::Accessibility::ActorAccessible::EmitBoundsChanged, Dali::Accessibility::ActorAccessible::EmitMovedOutOfScreen, Dali::Accessibility::ActorAccessible::EmitScrollFinished, Dali::Accessibility::ActorAccessible::EmitScrollStarted, Dali::Accessibility::ActorAccessible::EmitStateChanged, Dali::Accessibility::ActorAccessible::EmitTextCursorMoved, Dali::Accessibility::ActorAccessible::EmitTextDeleted, Dali::Accessibility::ActorAccessible::EmitTextInserted, Dali::Accessibility::Address::GetBus, Dali::Accessibility::Accessible::GetCurrentlyHighlightedActor, Dali::Accessibility::Accessible::GetHighlightActor, Dali::Accessibility::Accessible::GetOwningPtr, Dali::Accessibility::ActorAccessible::GetParent, Dali::AtspiAccessibility::IsScreenReaderEnabled, Dali::Accessibility::IsUp, Dali::Accessibility::ActorAccessible::ObjectDestroyed, Dali::AtspiAccessibility::Pause, Dali::AtspiAccessibility::Resume, Dali::AtspiAccessibility::Say, Dali::Accessibility::Accessible::SetCurrentlyHighlightedActor, Dali::Accessibility::Accessible::SetHighlightActor, Dali::AtspiAccessibility::StopReading, Dali::AtspiAccessibility::SuppressScreenReader.
static void Dali::Accessibility::Bridge::DisableAutoInit()
Blocks auto-initialization of AT-SPI bridge.
Use this only if your application starts before DBus does, and call it early in main() (before GetCurrentBridge() is called by anyone). GetCurrentBridge() will then return an instance of DummyBridge. When DBus is ready, call EnableAutoInit(). Please note that GetCurrentBridge() may still return an instance of DummyBridge if AT-SPI was disabled at compile time or using an environment variable, or if creating the real bridge failed. Dali::Accessibility::DummyBridge Dali::Accessibility::Bridge::EnableAutoInit
static void Dali::Accessibility::Bridge::EnableAutoInit()
Re-enables auto-initialization of AT-SPI bridge.
Normal applications do not have to call this function. GetCurrentBridge() tries to initialize the AT-SPI bridge when it is called for the first time. Dali::Accessibility::Bridge::DisableAutoInit Dali::Accessibility::Bridge::AddTopLevelWindow Dali::Accessibility::Bridge::SetApplicationName
static std::string Dali::Accessibility::Bridge::MakeBusNameForWidget(std::string_view widgetInstanceId, int widgetProcessId)
Encodes a widget ID as a usable bus name.
widgetInstanceId The instance ID of a widget widgetProcessId The process ID (PID) of the widget std::string Encoded bus name SetPreferredBusName
static Signal< void()> & Dali::Accessibility::Bridge::EnabledSignal()
static Signal< void()> & Dali::Accessibility::Bridge::DisabledSignal()
static Signal< void()> & Dali::Accessibility::Bridge::ScreenReaderEnabledSignal()
static Signal< void()> & Dali::Accessibility::Bridge::ScreenReaderDisabledSignal()
static bool Dali::Accessibility::Bridge::IsTerminated()
Referenced by Dali::Accessibility::IsUp.
void Dali::Accessibility::Bridge::SetIsOnRootLevel(Accessible *owner)
Tells bridge, that given object is considered root (doesn't have any parents).
All root objects will have the same parent - application object. Application object is controlled by bridge and private. owner The accessible object