Dali::Ui::Callback< void()>
UniquePtr<CallbackBase> Dali::Ui::Callback< void()>::mCallback
Dali::Ui::Callback< void()>::Callback()=default
Dali::Ui::Callback< void()>::Callback(Callback &&) noexcept=default
Callback & Dali::Ui::Callback< void()>::operator=(Callback &&) noexcept=default
Dali::Ui::Callback< void()>::Callback(const Callback &)=delete
Callback & Dali::Ui::Callback< void()>::operator=(const Callback &)=delete
Dali::Ui::Callback< void()>::operator bool() const
void Dali::Ui::Callback< void()>::Invoke()
const CallbackBase & Dali::Ui::Callback< void()>::Get() const
CallbackBase * Dali::Ui::Callback< void()>::Release()
Referenced by Dali::Ui::Integration::WebViewImpl::RegisterFrameRenderedCallback, Dali::Ui::Integration::WebViewImpl::RegisterFullscreenEnteredCallback, Dali::Ui::Integration::WebViewImpl::RegisterFullscreenExitedCallback, Dali::Ui::Integration::WebViewImpl::RegisterWebProcessCrashedCallback.
static Callback< void()> Dali::Ui::Callback< void()>::New(void(*func)())
static Callback< void()> Dali::Ui::Callback< void()>::New(T *obj, void(T::*func)())
Dali::Ui::Callback< void()>::Callback(CallbackBase *cb)