Dali::Ui::Integration::LayoutImpl
LayoutImplPtr Dali::Ui::Integration::LayoutImpl::New()
Creates a new Layout implementation without a LayoutManager.
An IntrusivePtr to the new LayoutImpl
References LayoutImpl.
Referenced by Dali::Ui::Layout::New.
LayoutManager * Dali::Ui::Integration::LayoutImpl::GetLayoutManager() const
Gets the layout manager from the LayoutManager trait.
Pointer to the layout manager, or nullptr if not set
Referenced by Dali::Ui::Integration::GridLayoutImpl::AddColumnDefinition, Dali::Ui::Integration::GridLayoutImpl::AddRowDefinition, Dali::Ui::Integration::GridLayoutImpl::ClearColumnDefinitions, Dali::Ui::Integration::GridLayoutImpl::ClearRowDefinitions, Dali::Ui::Integration::FlexLayoutImpl::GetAlignContent, Dali::Ui::Integration::FlexLayoutImpl::GetAlignItems, Dali::Ui::Integration::GridLayoutImpl::GetColumnCount, Dali::Ui::Integration::GridLayoutImpl::GetColumnDefinitions, Dali::Ui::Integration::GridLayoutImpl::GetColumnSpacing, Dali::Ui::Integration::FlexLayoutImpl::GetDirection, Dali::Ui::Integration::FlexLayoutImpl::GetJustifyContent, Dali::Ui::Integration::StackLayoutImpl::GetOrientation, Dali::Ui::Integration::GridLayoutImpl::GetRowCount, Dali::Ui::Integration::GridLayoutImpl::GetRowDefinitions, Dali::Ui::Integration::GridLayoutImpl::GetRowSpacing, Dali::Ui::Integration::StackLayoutImpl::GetSpacing, Dali::Ui::Integration::FlexLayoutImpl::GetWrap, HasLayoutManager, OnArrange, OnMeasure, Dali::Ui::Integration::FlexLayoutImpl::SetAlignContent, Dali::Ui::Integration::FlexLayoutImpl::SetAlignItems, Dali::Ui::Integration::GridLayoutImpl::SetColumnDefinitions, Dali::Ui::Integration::GridLayoutImpl::SetColumnSpacing, Dali::Ui::Integration::FlexLayoutImpl::SetDirection, Dali::Ui::Integration::FlexLayoutImpl::SetJustifyContent, Dali::Ui::Integration::StackLayoutImpl::SetOrientation, Dali::Ui::Integration::GridLayoutImpl::SetRowDefinitions, Dali::Ui::Integration::GridLayoutImpl::SetRowSpacing, Dali::Ui::Integration::StackLayoutImpl::SetSpacing, Dali::Ui::Integration::FlexLayoutImpl::SetWrap.
bool Dali::Ui::Integration::LayoutImpl::HasLayoutManager() const
Checks if this layout has a layout manager.
True if a layout manager is set
References GetLayoutManager.
Referenced by SetLayoutManager.
MeasuredSize Dali::Ui::Integration::LayoutImpl::OnMeasure(float widthConstraint, float heightConstraint) override
Called during measure pass. Override to implement custom measurement.
References Dali::Ui::View::DownCast, GetLayoutManager, Dali::Ui::ViewImpl::GetMeasureCallback, Dali::Ui::ViewImpl::GetMinimumHeight, Dali::Ui::ViewImpl::GetMinimumWidth, Dali::Ui::ViewImpl::GetPadding, Dali::Ui::ViewImpl::GetRequestedHeight, Dali::Ui::ViewImpl::GetRequestedWidth, Dali::Ui::MeasuredSize::height, Dali::Ui::MATCH_PARENT, Dali::Ui::LayoutManager::Measure, Dali::Ui::ViewImpl::OnMeasure, Dali::Ui::MeasuredSize::width.
MeasuredSize Dali::Ui::Integration::LayoutImpl::OnArrange(const LayoutRect &bounds) override
Called during arrange pass. Override to implement custom arrangement.
References Dali::Ui::LayoutManager::ArrangeChildren, Dali::Ui::View::DownCast, Dali::Ui::ViewImpl::GetArrangeCallback, GetLayoutManager, Dali::Ui::ViewImpl::GetPadding, Dali::Ui::LayoutRect::height, Dali::Ui::ViewImpl::OnArrange, Dali::Ui::LayoutRect::width, Dali::Ui::LayoutRect::x, Dali::Ui::LayoutRect::y.
bool Dali::Ui::Integration::LayoutImpl::IsLayout() const override
Returns whether this view acts as a layout container.
True if this view has a LayoutManager attached
Dali::Ui::Integration::LayoutImpl::~LayoutImpl()
A reference counted object may only be deleted by calling Unreference()
Dali::Ui::Integration::LayoutImpl::LayoutImpl()
LayoutImpl constructor.
Referenced by New.
void Dali::Ui::Integration::LayoutImpl::SetLayoutManager(LayoutManager *layoutManager)
Attaches a LayoutManager as a trait to this Layout.
Must be called in OnInitialize() of derived classes, not in constructors (Self() is not available during construction). layoutManager The layout manager (ownership transferred)
References HasLayoutManager, Dali::Ui::Integration::ReservedTraitId::LAYOUT_MANAGER, Dali::Ui::ViewImpl::SetTrait.
Referenced by Dali::Ui::Integration::AbsoluteLayoutImpl::OnInitialize, Dali::Ui::Integration::FlexLayoutImpl::OnInitialize, Dali::Ui::Integration::GridLayoutImpl::OnInitialize, Dali::Ui::Integration::StackLayoutImpl::OnInitialize, Dali::Ui::Integration::ScrollViewImpl::OnInitialize.
Internal::LayoutManagerTraitImpl * Dali::Ui::Integration::LayoutImpl::GetLayoutManagerTrait() const
Dali::Ui::Integration::LayoutImpl::LayoutImpl(const LayoutImpl &)=delete
Dali::Ui::Integration::LayoutImpl::LayoutImpl(LayoutImpl &&)=delete
LayoutImpl & Dali::Ui::Integration::LayoutImpl::operator=(const LayoutImpl &)=delete
LayoutImpl & Dali::Ui::Integration::LayoutImpl::operator=(LayoutImpl &&)=delete