Dali::Ui::InputEvent
Dali::Ui::InputEvent::InputEvent()=default
Creates an uninitialized InputEvent handle.
Referenced by New, New, New, New, New, New.
Dali::Ui::InputEvent::~InputEvent()=default
Destructor.
Dali::Ui::InputEvent::InputEvent(const InputEvent &handle)=default
Copy constructor.
handle Handle to copy
Dali::Ui::InputEvent::InputEvent(InputEvent &&rhs) noexcept=default
Move constructor.
rhs Handle to move
InputEvent & Dali::Ui::InputEvent::operator=(const InputEvent &handle)=default
Copy assignment operator.
handle Object to assign this to Reference to this
InputEvent & Dali::Ui::InputEvent::operator=(InputEvent &&rhs) noexcept=default
Move assignment operator.
rhs Object to assign this to Reference to this
InputEventType Dali::Ui::InputEvent::GetInputEventType() const
Get the type of this event.
The type of the input event
References Dali::Ui::GetImpl.
const TouchEvent & Dali::Ui::InputEvent::GetTouchEvent() const
References Dali::Ui::GetImpl.
const KeyEvent & Dali::Ui::InputEvent::GetKeyEvent() const
References Dali::Ui::GetImpl.
const TapGesture & Dali::Ui::InputEvent::GetTapGesture() const
References Dali::Ui::GetImpl.
const LongPressGesture & Dali::Ui::InputEvent::GetLongPressGesture() const
References Dali::Ui::GetImpl.
const WheelEvent & Dali::Ui::InputEvent::GetWheelEvent() const
References Dali::Ui::GetImpl.
Dali::Ui::InputEvent::InputEvent(Internal::InputEventImpl *impl)
This constructor is used by InputEvent::New() methods.
impl The implementation of the input event
InputEvent Dali::Ui::InputEvent::New()
Creates a new InputEvent with NONE type, representing a programmatic (non-input) change.
The returned event has InputEventType::NONE. Use this when emitting signals that do not originate from user input (e.g. programmatic state changes). A handle to the new InputEvent
References InputEvent.
Referenced by None, Dali::Ui::Integration::InteractiveTraitImpl::OnKeyEvent, Dali::Ui::Integration::InteractiveTraitImpl::OnTap, Dali::Ui::Integration::InteractiveTraitImpl::OnTouch.
const InputEvent & Dali::Ui::InputEvent::None()
Returns a shared NONE-type InputEvent instance.
No heap allocation on each call. Use this wherever a valid InputEvent with InputEventType::NONE is needed without per-call cost. A const reference to the shared NONE InputEvent
References New.
Referenced by Dali::Ui::Integration::InteractiveTraitImpl::OnEnabledChanged, Dali::Ui::Integration::InteractiveTraitImpl::OnFocusedChanged, Dali::Ui::Integration::InteractiveTraitImpl::SetPseudoDisabled, Dali::Ui::Integration::SelectableTraitImpl::SetSelected.
InputEvent Dali::Ui::InputEvent::New(const TouchEvent &originEvent)
Creates a new InputEvent from a touch event.
originEvent The originating touch event A handle to the new InputEvent
References InputEvent.
InputEvent Dali::Ui::InputEvent::New(const KeyEvent &originEvent)
Creates a new InputEvent from a key event.
originEvent The originating key event A handle to the new InputEvent
References InputEvent.
InputEvent Dali::Ui::InputEvent::New(const TapGesture &originEvent)
Creates a new InputEvent from a tap gesture.
originEvent The originating tap gesture A handle to the new InputEvent
References InputEvent.
InputEvent Dali::Ui::InputEvent::New(const LongPressGesture &originEvent)
Creates a new InputEvent from a long-press gesture.
originEvent The originating long-press gesture A handle to the new InputEvent
References InputEvent.
InputEvent Dali::Ui::InputEvent::New(const WheelEvent &originEvent)
Creates a new InputEvent from a wheel event.
originEvent The originating wheel event A handle to the new InputEvent
References InputEvent.