Dali::Ui::Visual::Base
Dali::Ui::Visual::Base::Base()
Create an empty Visual Handle.
Dali::Ui::Visual::Base::~Base()
Destructor.
This is non-virtual since derived Handle types must not contain data or virtual methods.
Dali::Ui::Visual::Base::Base(const Base &handle)
This copy constructor is required for (smart) pointer semantics.
handle A reference to the copied handle.
Visual::Base & Dali::Ui::Visual::Base::operator=(const Base &handle)
This assignment operator is required for (smart) pointer semantics.
handle A reference to the copied handle. A reference to this.
void Dali::Ui::Visual::Base::SetName(const std::string &name)
Set the name of the visual.
Used by the styling system to animate properties name The name to give the visual
const std::string & Dali::Ui::Visual::Base::GetName() const
Get the name of the visual.
Used by the styling system to animate properties The name of the visual
void Dali::Ui::Visual::Base::SetTransformAndSize(const Dali::Property::Map &transform, Size controlSize)
Sets the transform and the control size.
transform A property map describing the transform controlSize The size of the parent control for visuals that need to scale internally.
Referenced by Dali::Ui::Integration::LabelImpl::OnRelayout.
float Dali::Ui::Visual::Base::GetHeightForWidth(float width)
Returns the height for a given width.
width Width to use. The height based on the width.
float Dali::Ui::Visual::Base::GetWidthForHeight(float height)
Returns the width for a given height.
height Height to use. The width based on the height.
void Dali::Ui::Visual::Base::GetNaturalSize(Vector2 &naturalSize)
Return the natural size of the visual.
Deriving classes stipulate the natural size and by default a visual has a ZERO natural size. A visual may not actually have a natural size until it has been placed on stage and acquired all it's resources. naturalSize The visual's natural size
void Dali::Ui::Visual::Base::SetDepthIndex(int index)
Set the depth index of this visual.
Depth-index controls draw-order for overlapping visuals. Visuals with higher depth indices are rendered in front of other visual with smaller values. The value of index will be clamped between DepthIndex::Ranges::MINIMUM_DEPTH_INDEX and DepthIndex::Ranges::MAXIMUM_DEPTH_INDEX. If we call this API at least 1 time, we cannot set as DepthIndex::AUTO_INDEX after. index The depth index of this visual.
int Dali::Ui::Visual::Base::GetDepthIndex() const
Get the depth index of this visual which clamped between DepthIndex::Ranges::MINIMUM_DEPTH_INDEX and DepthIndex::Ranges::MAXIMUM_DEPTH_INDEX. Or DepthIndex::Ranges::AUTO_INDEX if we never set depth index before.
The depth index of this visual.
void Dali::Ui::Visual::Base::CreatePropertyMap(Dali::Property::Map &map) const
Create the property map representing this visual.
map The visual property map.
Referenced by Dali::Ui::Integration::LottieAnimationViewImpl::GetContentInfo, Dali::Ui::Integration::AnimatedImageViewImpl::GetCurrentFrame, Dali::Ui::Integration::LottieAnimationViewImpl::GetCurrentFrame, Dali::Ui::Integration::LottieAnimationViewImpl::GetMarkerInfo, Dali::Ui::Integration::AnimatedImageViewImpl::GetPlayState, Dali::Ui::Integration::LottieAnimationViewImpl::GetPlayState, Dali::Ui::Integration::AnimatedImageViewImpl::GetTotalFrame, Dali::Ui::Integration::LottieAnimationViewImpl::GetTotalFrame.
void Dali::Ui::Visual::Base::DoAction(const Dali::Property::Index actionId, const Dali::Property::Value &attributes)
Performs an action on the visual with the given action id and attributes.
actionId The id of the action to perform this API only takes an Index attributes The list of attributes for the action. ( optional for this data structure to have content )
Referenced by Dali::Ui::Integration::AnimatedImageViewImpl::SetImageColor, Dali::Ui::Integration::ImageViewImpl::SetImageColor, Dali::Ui::Integration::LottieAnimationViewImpl::SetImageColor, Dali::Ui::Integration::AnimatedImageViewImpl::SetPixelArea.
void Dali::Ui::Visual::Base::DoActionExtension(const Dali::Property::Index actionId, const Dali::Any &attributes)
Performs an action on the visual with the given action id and attributes.
actionId The id of the action to perform this API only takes an Index attributes The list of attributes for the action. ( optional for this data structure to have content )
Visual::Type Dali::Ui::Visual::Base::GetType() const
Get the type of this visual.
The the type of this visual.
Dali::Property Dali::Ui::Visual::Base::GetPropertyObject(Dali::Property::Key key)
Retrieve the property object associated with the property key.
key The Property key of the visual. The Property object
void Dali::Ui::Visual::Base::SetProperties(const Dali::Property::Map &properties)
Set the properties of the visual.
properties The properties to set
void Dali::Ui::Visual::Base::SetOnScene(Actor &actor)
Attach the visual to an actor.
actor The actor to attach the visual to
Dali::VisualRenderer Dali::Ui::Visual::Base::GetRenderer() const
Get the main renderer of the visual uses.
The visual renderer for the visual.
Dali::Ui::Visual::Base::Base(Internal::Visual::Base *impl)