Dali::Ui::Integration::UiThemeManagerImpl
using Dali::Ui::Integration::UiThemeManagerImpl::ThemeChangedSignalType = Signal<void()>
ThemeLoaderInterface* Dali::Ui::Integration::UiThemeManagerImpl::mLoader
ThemeChangedSignalType Dali::Ui::Integration::UiThemeManagerImpl::mThemeChangedSignal
SlotDelegate<UiThemeManagerImpl> Dali::Ui::Integration::UiThemeManagerImpl::mSlotDelegate
UiThemeManager Dali::Ui::Integration::UiThemeManagerImpl::Get()
Returns the singleton UiThemeManager handle.
A UiThemeManager handle wrapping the singleton impl
References UiThemeManagerImpl.
Referenced by Dali::Ui::UiThemeManager::Get.
void Dali::Ui::Integration::UiThemeManagerImpl::EnsureThemeLoader()
Ensures the ThemeLoaderInterface is created.
On the first call, creates the loader via UiConfigImpl::CreateThemeLoader(). If CreateThemeLoader() returns nullptr, a built-in DefaultThemeLoader is used. Subsequent calls are no-ops. UiConfigManager must be initialized. Triggers assertion failure otherwise.
References Dali::Ui::Integration::UiConfigManager::Get, Dali::Ui::ThemeLoaderInterface::ThemeChangedSignal.
Referenced by GetLoader.
ThemeLoaderInterface & Dali::Ui::Integration::UiThemeManagerImpl::GetLoader()
Returns the ThemeLoaderInterface instance, creating it if necessary.
UiConfigManager must be initialized. Triggers assertion failure otherwise. A reference to the ThemeLoaderInterface
References EnsureThemeLoader.
String Dali::Ui::Integration::UiThemeManagerImpl::GetCurrentThemeId() const
Returns the identifier of the current theme.
The theme identifier, or an empty string if no theme is active
References Dali::Ui::ThemeLoaderInterface::GetCurrentThemeId.
UiThemeManagerImpl::ThemeChangedSignalType & Dali::Ui::Integration::UiThemeManagerImpl::ThemeChangedSignal()
Returns the signal emitted when the theme changes.
A reference to the theme-changed signal
Dali::Ui::Integration::UiThemeManagerImpl::UiThemeManagerImpl()
Constructor. Used internally to create the singleton impl.
Referenced by Get.
Dali::Ui::Integration::UiThemeManagerImpl::~UiThemeManagerImpl() override
Destructor.
Dali::Ui::Integration::UiThemeManagerImpl::UiThemeManagerImpl(const UiThemeManagerImpl &)=delete
Dali::Ui::Integration::UiThemeManagerImpl::UiThemeManagerImpl(UiThemeManagerImpl &&)=delete
UiThemeManagerImpl & Dali::Ui::Integration::UiThemeManagerImpl::operator=(const UiThemeManagerImpl &)=delete
UiThemeManagerImpl & Dali::Ui::Integration::UiThemeManagerImpl::operator=(UiThemeManagerImpl &&)=delete
void Dali::Ui::Integration::UiThemeManagerImpl::OnLoaderThemeChanged()