Dali::Ui::AbsoluteLayoutParams
Dali::Ui::AbsoluteLayoutParams::AbsoluteLayoutParams()
Creates an uninitialized handle.
Referenced by DownCast, New, New.
Dali::Ui::AbsoluteLayoutParams::AbsoluteLayoutParams(const AbsoluteLayoutParams &handle)
Copy constructor.
handle Handle to copy
Dali::Ui::AbsoluteLayoutParams::~AbsoluteLayoutParams()
Destructor.
AbsoluteLayoutParams & Dali::Ui::AbsoluteLayoutParams::SetBounds(const LayoutRect &bounds)
Sets the absolute position and size of the child within the layout.
bounds The layout bounds (x, y, width, height) Reference to this for chaining
References Dali::Ui::GetImpl.
LayoutRect Dali::Ui::AbsoluteLayoutParams::GetBounds() const
Gets the absolute position and size of the child within the layout.
The layout bounds
References Dali::Ui::GetImpl.
AbsoluteLayoutParams & Dali::Ui::AbsoluteLayoutParams::SetX(float x)
Sets the X position of the child within the layout.
x The X position Reference to this for chaining
References Dali::Ui::GetImpl.
float Dali::Ui::AbsoluteLayoutParams::GetX() const
Gets the X position of the child within the layout.
The X position
References Dali::Ui::GetImpl.
AbsoluteLayoutParams & Dali::Ui::AbsoluteLayoutParams::SetY(float y)
Sets the Y position of the child within the layout.
y The Y position Reference to this for chaining
References Dali::Ui::GetImpl.
float Dali::Ui::AbsoluteLayoutParams::GetY() const
Gets the Y position of the child within the layout.
The Y position
References Dali::Ui::GetImpl.
AbsoluteLayoutParams & Dali::Ui::AbsoluteLayoutParams::SetWidth(float width)
Sets the width of the child within the layout.
width The width (-1 means use View's own size) Reference to this for chaining
References Dali::Ui::GetImpl.
float Dali::Ui::AbsoluteLayoutParams::GetWidth() const
Gets the width of the child within the layout.
The width
References Dali::Ui::GetImpl.
AbsoluteLayoutParams & Dali::Ui::AbsoluteLayoutParams::SetHeight(float height)
Sets the height of the child within the layout.
height The height (-1 means use View's own size) Reference to this for chaining
References Dali::Ui::GetImpl.
float Dali::Ui::AbsoluteLayoutParams::GetHeight() const
Gets the height of the child within the layout.
The height
References Dali::Ui::GetImpl.
AbsoluteLayoutParams & Dali::Ui::AbsoluteLayoutParams::SetFlags(AbsoluteLayoutFlags flags)
Sets the layout flags that control proportional sizing behavior.
flags The absolute layout flags Reference to this for chaining
References Dali::Ui::GetImpl.
AbsoluteLayoutFlags Dali::Ui::AbsoluteLayoutParams::GetFlags() const
Gets the layout flags that control proportional sizing behavior.
The absolute layout flags
References Dali::Ui::GetImpl.
AbsoluteLayoutParams Dali::Ui::AbsoluteLayoutParams::New()
Creates a new AbsoluteLayoutParams with default values.
A handle to a newly allocated AbsoluteLayoutParams
References AbsoluteLayoutParams.
AbsoluteLayoutParams Dali::Ui::AbsoluteLayoutParams::New(const AbsoluteLayoutParams &other)
Creates a new AbsoluteLayoutParams by copying values from an existing one.
other The params to copy from A handle to a newly allocated AbsoluteLayoutParams with copied values
References AbsoluteLayoutParams, Dali::Ui::GetImpl.
AbsoluteLayoutParams Dali::Ui::AbsoluteLayoutParams::DownCast(BaseHandle handle)
Downcasts a handle to AbsoluteLayoutParams.
handle Handle to an object A valid handle or an uninitialized handle
References AbsoluteLayoutParams.
LayoutParamsType Dali::Ui::AbsoluteLayoutParams::GetLayoutParamsType()
Returns the layout params type identifier.
LayoutParamsType::ABSOLUTE
References Dali::Ui::ABSOLUTE.