Dali::Ui::View
PropertyRange
Start index is used by the property registration macro.
OffScreenRenderingType
using Dali::Ui::View::StateChangedSignalType = Signal<void(View, const StateEvent&)>
typedef Signal<bool(View, const KeyEvent&)> Dali::Ui::View::KeyEventSignalType
Key Event signal type.
typedef Signal<void(View, bool)> Dali::Ui::View::FocusChangedSignalType
Focus changed signal type.
typedef Signal<void(View)> Dali::Ui::View::ResourceReadySignalType
ResourceReady signal type.
typedef Signal<void(View)> Dali::Ui::View::OffScreenRenderingFinishedSignalType
Offscreen rendering finished signal type.
typedef Signal<void()> Dali::Ui::View::AccessibilityActivateSignalType
AccessibilityActivate signal type.
typedef Signal<void()> Dali::Ui::View::AccessibilityReadingSkippedSignalType
AccessibilityReadingSkipped signal type.
typedef Signal<void()> Dali::Ui::View::AccessibilityReadingPausedSignalType
AccessibilityReadingPaused signal type.
typedef Signal<void()> Dali::Ui::View::AccessibilityReadingResumedSignalType
AccessibilityReadingResumed signal type.
typedef Signal<void()> Dali::Ui::View::AccessibilityReadingCancelledSignalType
AccessibilityReadingCancelled signal type.
typedef Signal<void()> Dali::Ui::View::AccessibilityReadingStoppedSignalType
AccessibilityReadingStopped signal type.
typedef Signal<void(Dali::String&)> Dali::Ui::View::AccessibilityGetNameSignalType
AccessibilityGetName signal type.
typedef Signal<void(Dali::String&)> Dali::Ui::View::AccessibilityGetDescriptionSignalType
AccessibilityGetDescription signal type.
typedef Signal<void(bool)> Dali::Ui::View::AccessibilityHighlightedSignalType
AccessibilityHighlighted signal type.
bool highlighted true if View is highlighted, false if highlight is removed.
typedef Signal<void(View, Dali::Property::Index, Dali::Property::Index)> Dali::Ui::View::VisualEventSignalType
Visual Event signal type.
Dali::Ui::View::View()
Creates an uninitialized View handle.
Only derived versions can be instantiated. Calling member functions with an uninitialized Dali::Object is not allowed.
Dali::Ui::View::View(const View &view)
Copy constructor.
Creates another handle that points to the same real object. view Handle to copy
Dali::Ui::View::View(View &&rhs) noexcept
Move constructor.
rhs Handle to move
Dali::Ui::View::~View()
Destructor.
This is non-virtual since derived Handle types must not contain data or virtual methods.
View & Dali::Ui::View::operator=(const View &handle)=default
Copy assignment operator.
Changes this handle to point to another real object. handle Object to assign this to Reference to this
Referenced by Dali::Ui::DummyComponent::operator=, Dali::Ui::InputField::operator=, Dali::Ui::Label::operator=, Dali::Ui::Layout::operator=, Dali::Ui::ScrollView::operator=, Dali::Ui::DummyComponent::operator=, Dali::Ui::InputField::operator=, Dali::Ui::Label::operator=, Dali::Ui::Layout::operator=, Dali::Ui::ScrollView::operator=.
View & Dali::Ui::View::operator=(View &&rhs) noexcept=default
Move assignment operator.
rhs Object to assign this to Reference to this
MeasuredSize Dali::Ui::View::Measure(float widthConstraint, float heightConstraint)
Measures the view with the given constraints.
This method implements caching to avoid redundant calculations. It calls OnMeasure internally (Template Method pattern). widthConstraint The width constraint for measurement heightConstraint The height constraint for measurement The measured size
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::Measure, VerifyCustomActorPointer.
MeasuredSize Dali::Ui::View::Arrange(const LayoutRect &bounds)
Arranges the view within the given bounds.
This method calls OnArrange internally (Template Method pattern). bounds The bounds to arrange the view in The final arranged size
References Dali::Ui::ViewImpl::Arrange, Dali::Ui::GetImpl, VerifyCustomActorPointer.
void Dali::Ui::View::InvalidateMeasure()
Invalidates the measure of this view.
This propagates to the parent layout while one exists, until the layout root is reached (no parent Layout).
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::InvalidateMeasure.
void Dali::Ui::View::InvalidateArrange()
Invalidates the arrange of this view.
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::InvalidateArrange.
MeasuredSize Dali::Ui::View::GetMeasuredSize() const
Gets the measured size from the last Measure() pass.
The measured size
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetMeasuredSize.
void Dali::Ui::View::SetMeasureCallback(MeasureCallback callback)
Sets a custom measure callback for this View.
When set, the callback replaces the default measurement behavior during the layout pass. Pass a default-constructed callback to remove. callback The measure callback (ownership transferred) //Memberfunction view.SetMeasureCallback(MeasureCallback::New(this,&MyClass::OnMeasure)); //Staticfunction view.SetMeasureCallback(MeasureCallback::New(&MyMeasure)); //Removecallback view.SetMeasureCallback({});
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetMeasureCallback.
void Dali::Ui::View::SetArrangeCallback(ArrangeCallback callback)
Sets a custom arrange callback for this View.
When set, the callback replaces the default arrangement behavior during the layout pass. Pass a default-constructed callback to remove. callback The arrange callback (ownership transferred) //Memberfunction view.SetArrangeCallback(ArrangeCallback::New(this,&MyClass::OnArrange)); //Staticfunction view.SetArrangeCallback(ArrangeCallback::New(&MyArrange)); //Removecallback view.SetArrangeCallback({});
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetArrangeCallback.
float Dali::Ui::View::GetScaleX() const
Gets the x scale factor applied to the view.
The x scale factor
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetScaleX.
View & Dali::Ui::View::SetScaleX(float scaleX)
Sets the x scale factor applied to the view.
scaleX The X scale factor to set
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetScaleX, VerifyCustomActorPointer.
Referenced by SetScale.
float Dali::Ui::View::GetScaleY() const
Gets the y scale factor applied to the view.
The y scale factor
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetScaleY.
View & Dali::Ui::View::SetScaleY(float scaleY)
Sets the y scale factor applied to the view.
scaleY The Y scale factor to set
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetScaleY, VerifyCustomActorPointer.
Referenced by SetScale.
View & Dali::Ui::View::SetScale(float scaleX, float scaleY)
Sets the y scale factor applied to the view.
scaleX The X scale factor to set scaleY The Y scale factor to set
References SetScaleX, SetScaleY, VerifyCustomActorPointer.
bool Dali::Ui::View::IsVisible() const
Checks if the view is visible.
True if the view is visible, false otherwise
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::IsVisible.
View & Dali::Ui::View::SetVisibility(bool visibility)
Sets the visibility of the view.
visibility True to make the view visible, false to hide it Reference to this View for fluent chaining
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetVisibility, VerifyCustomActorPointer.
float Dali::Ui::View::GetOpacity() const
Gets the opacity of the view.
The opacity value (0.0 to 1.0)
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetOpacity.
View & Dali::Ui::View::SetOpacity(float opacity)
Sets the opacity of the view.
opacity The opacity value to set (0.0 to 1.0) Reference to this View for fluent chaining
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetOpacity, VerifyCustomActorPointer.
MeasuredSize Dali::Ui::View::GetSize() const
Gets the actual rendered size of this View after layout.
This is a read-only result of the layout system's Measure/Arrange passes. To set the desired size, use SetRequestedWidth() / SetRequestedHeight(). The actual size (width, height) as set by the layout system
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetSize.
View & Dali::Ui::View::SetPositionX(float x)
Sets the X position of the View.
x The X position to set
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetPositionX.
float Dali::Ui::View::GetPositionX() const
Gets the X position of the View.
The X position of the View
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetPositionX.
View & Dali::Ui::View::SetPositionY(float y)
Sets the Y position of the View.
y The Y position to set
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetPositionY.
float Dali::Ui::View::GetPositionY() const
Gets the Y position of the View.
The Y position of the View
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetPositionY.
View & Dali::Ui::View::SetParentOrigin(const Vector3 &point)
Sets the parent origin of the View.
point The parent origin to set
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetParentOrigin, VerifyCustomActorPointer.
Vector3 Dali::Ui::View::GetParentOrigin() const
Gets the parent origin of the View.
The parent origin of the View
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetParentOrigin.
View & Dali::Ui::View::SetPivot(const Vector3 &point)
Sets the pivot of the View.
point The pivot to set
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetPivot, VerifyCustomActorPointer.
Vector3 Dali::Ui::View::GetPivot() const
Gets the pivot of the View.
The pivot of the View
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetPivot.
View & Dali::Ui::View::SetRequestedWidth(float width)
Sets the requested width.
A positive value sets a fixed width. WRAP_CONTENT (-1): sizes to content (default). MATCH_PARENT (-2): fills the parent container. width The requested width
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetRequestedWidth.
float Dali::Ui::View::GetRequestedWidth() const
Gets the requested width.
The requested width
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetRequestedWidth.
View & Dali::Ui::View::SetRequestedHeight(float height)
Sets the requested height.
A positive value sets a fixed height. WRAP_CONTENT (-1): sizes to content (default). MATCH_PARENT (-2): fills the parent container. height The requested height
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetRequestedHeight.
float Dali::Ui::View::GetRequestedHeight() const
Gets the requested height.
The requested height
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetRequestedHeight.
View & Dali::Ui::View::SetMinimumWidth(float width)
Sets the minimum width.
width The minimum width
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetMinimumWidth.
float Dali::Ui::View::GetMinimumWidth() const
Gets the minimum width.
The minimum width
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetMinimumWidth.
View & Dali::Ui::View::SetMinimumHeight(float height)
Sets the minimum height.
height The minimum height
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetMinimumHeight.
float Dali::Ui::View::GetMinimumHeight() const
Gets the minimum height.
The minimum height
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetMinimumHeight.
View & Dali::Ui::View::SetMaximumWidth(float width)
Sets the maximum width.
width The maximum width
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetMaximumWidth.
float Dali::Ui::View::GetMaximumWidth() const
Gets the maximum width.
The maximum width
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetMaximumWidth.
View & Dali::Ui::View::SetMaximumHeight(float height)
Sets the maximum height.
height The maximum height
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetMaximumHeight.
float Dali::Ui::View::GetMaximumHeight() const
Gets the maximum height.
The maximum height
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetMaximumHeight.
View & Dali::Ui::View::SetMargin(const Extents &margin)
Sets the view margin.
margin The margin to set
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetMargin, VerifyCustomActorPointer.
Extents Dali::Ui::View::GetMargin() const
Gets the view margin.
The view margin
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetMargin.
View & Dali::Ui::View::SetPadding(const Extents &padding)
Sets the view padding.
padding The padding to set
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetPadding, VerifyCustomActorPointer.
Extents Dali::Ui::View::GetPadding() const
Gets the view padding.
The view padding
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetPadding.
View & Dali::Ui::View::SetLayoutMode(LayoutMode mode)
Sets the layout mode of this View.
LayoutMode::DEFAULT (default) lets the parent container's layout system manage this View's size and position normally. LayoutMode::STANDALONE excludes this View from the parent's accumulation, spacing and index calculations. The View's size is still measured normally (so MATCH_PARENT, WRAP_CONTENT and explicit RequestedWidth/Height all work), but its position is taken from SetPositionX/SetPositionY instead of being decided by the parent layout. This is useful for floating overlays, drag previews, tooltips and absolute positioning inside any LayoutManager. Standalone children ignore the parent's padding entirely. Their measured size is the parent's full inner size minus the child's own margin, and their final position is SetPositionX/SetPositionY plus the child's own margin in the parent's coordinate space. This keeps size and position consistent: a Standalone child with MATCH_PARENT fills the parent edge to edge regardless of parent padding, and any margin set on the child shifts it inward in both axes. mode The layout mode to set
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetLayoutMode, VerifyCustomActorPointer.
LayoutMode Dali::Ui::View::GetLayoutMode() const
Gets the layout mode of this View.
The layout mode
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetLayoutMode.
bool Dali::Ui::View::IsFocusable() const
Gets whether the actor should be focusable by keyboard navigation.
True if it is focusable
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::IsFocusable.
View & Dali::Ui::View::SetFocusable(bool focusable)
Sets whether the actor should be focusable by keyboard navigation.
focusable True if it is focusable
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetFocusable, VerifyCustomActorPointer.
Referenced by Dali::Ui::Integration::InteractiveTraitImpl::OnAttached.
bool Dali::Ui::View::IsTouchFocusable() const
Gets whether the actor should be focused when touched.
True if it is focused when touched
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::IsTouchFocusable.
View & Dali::Ui::View::SetTouchFocusable(bool touchFocusable)
Sets whether the actor should be focused when touched.
touchFocusable True if it gets focused when touched
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetTouchFocusable, VerifyCustomActorPointer.
Referenced by Dali::Ui::Integration::InteractiveTraitImpl::OnAttached.
View & Dali::Ui::View::SetLeftFocusableView(View view)
Sets the left focusable View for keyboard navigation.
view The View to focus when navigating left
References Dali::Ui::View::Property::LEFT_FOCUSABLE_ACTOR_ID.
View & Dali::Ui::View::SetRightFocusableView(View view)
Sets the right focusable View for keyboard navigation.
view The View to focus when navigating right
References Dali::Ui::View::Property::RIGHT_FOCUSABLE_ACTOR_ID.
View & Dali::Ui::View::SetUpFocusableView(View view)
Sets the up focusable View for keyboard navigation.
view The View to focus when navigating up
References Dali::Ui::View::Property::UP_FOCUSABLE_ACTOR_ID.
View & Dali::Ui::View::SetDownFocusableView(View view)
Sets the down focusable View for keyboard navigation.
view The View to focus when navigating down
References Dali::Ui::View::Property::DOWN_FOCUSABLE_ACTOR_ID.
View & Dali::Ui::View::SetClockwiseFocusableView(View view)
Sets the clockwise focusable View for keyboard navigation.
view The View to focus when navigating clockwise
References Dali::Ui::View::Property::CLOCKWISE_FOCUSABLE_ACTOR_ID.
View & Dali::Ui::View::SetCounterClockwiseFocusableView(View view)
Sets the counter-clockwise focusable View for keyboard navigation.
view The View to focus when navigating counter-clockwise
References Dali::Ui::View::Property::COUNTER_CLOCKWISE_FOCUSABLE_ACTOR_ID.
UiColor Dali::Ui::View::GetBackgroundColor()
Gets the background color.
The background color
References Dali::Ui::ViewImpl::GetBackgroundColor, Dali::Ui::GetImpl.
View & Dali::Ui::View::SetBackgroundColor(const UiColor &color)
Sets the background color.
If the UiColor has a color ID, it is resolved from the current theme and a binding is registered so the color is automatically refreshed when the theme changes. If the UiColor has direct RGBA values, it is applied immediately and any previous ID-based binding for this property is removed. color The UiColor to apply
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetBackgroundColor, VerifyCustomActorPointer.
bool Dali::Ui::View::IsEnabled() const
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::IsEnabled.
Referenced by Dali::Ui::Integration::InteractiveTraitImpl::OnTouch.
View & Dali::Ui::View::SetEnabled(bool enabled)
Sets whether the view is enabled.
A disabled view does not receive user interaction. Setting this to false adds the Disabled state and emits StateChangedSignal. enabled True to enable, false to disable
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetEnabled, VerifyCustomActorPointer.
Vector4 Dali::Ui::View::GetCornerRadius() const
Gets the corner radius of the view.
The corner radius as Vector4 (topLeft, topRight, bottomRight, bottomLeft)
References Dali::Ui::ViewImpl::GetCornerRadius, Dali::Ui::GetImpl.
View & Dali::Ui::View::SetCornerRadius(float radius)
Sets a uniform corner radius for all four corners.
radius The corner radius to apply to all corners
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetCornerRadius, VerifyCustomActorPointer.
View & Dali::Ui::View::SetCornerRadius(float topLeft, float topRight, float bottomRight, float bottomLeft)
Sets individual corner radii for all four corners.
topLeft The radius for the top-left corner topRight The radius for the top-right corner bottomRight The radius for the bottom-right corner bottomLeft The radius for the bottom-left corner
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetCornerRadius, VerifyCustomActorPointer.
View & Dali::Ui::View::SetCornerRadius(const Vector4 &radius)
Sets corner radii from a Vector4.
radius Corner radii as Vector4 (x=topLeft, y=topRight, z=bottomRight, w=bottomLeft)
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetCornerRadius, VerifyCustomActorPointer.
CornerRadiusPolicy Dali::Ui::View::GetCornerRadiusPolicy() const
Gets the corner radius policy.
The corner radius policy
References Dali::Ui::ViewImpl::GetCornerRadiusPolicy, Dali::Ui::GetImpl.
View & Dali::Ui::View::SetCornerRadiusPolicy(CornerRadiusPolicy policy)
Sets the corner radius policy.
policy ABSOLUTE for world-unit values (default), RELATIVE for percentage [0.0, 0.5] of the shorter side
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetCornerRadiusPolicy, VerifyCustomActorPointer.
View & Dali::Ui::View::SetCornerRadiusPolicyRelative()
Shortcut to set the corner radius policy to RELATIVE.
Equivalent to SetCornerRadiusPolicy(CornerRadiusPolicy::RELATIVE).
References Dali::Ui::GetImpl, Dali::Ui::RELATIVE, Dali::Ui::ViewImpl::SetCornerRadiusPolicy.
bool Dali::Ui::View::IsCornerRadiusPolicyRelative() const
Returns true if the corner radius policy is RELATIVE.
True if the policy is RELATIVE, false if ABSOLUTE
References Dali::Ui::ViewImpl::GetCornerRadiusPolicy, Dali::Ui::GetImpl, Dali::Ui::RELATIVE.
Vector4 Dali::Ui::View::GetCornerSquareness() const
Gets the corner squareness of the view.
The corner squareness as Vector4 (x=topLeft, y=topRight, z=bottomRight, w=bottomLeft)
References Dali::Ui::ViewImpl::GetCornerSquareness, Dali::Ui::GetImpl.
View & Dali::Ui::View::SetCornerSquareness(float squareness)
Sets a uniform corner squareness for all four corners.
squareness The squareness value to apply to all corners
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetCornerSquareness, VerifyCustomActorPointer.
View & Dali::Ui::View::SetCornerSquareness(float topLeft, float topRight, float bottomRight, float bottomLeft)
Sets individual corner squareness values for all four corners.
topLeft The squareness for the top-left corner topRight The squareness for the top-right corner bottomRight The squareness for the bottom-right corner bottomLeft The squareness for the bottom-left corner
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetCornerSquareness, VerifyCustomActorPointer.
View & Dali::Ui::View::SetCornerSquareness(const Vector4 &squareness)
Sets corner squareness from a Vector4.
squareness Squareness values as Vector4 (x=topLeft, y=topRight, z=bottomRight, w=bottomLeft)
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetCornerSquareness, VerifyCustomActorPointer.
float Dali::Ui::View::GetBorderlineWidth() const
Gets the borderline width of the view.
The borderline width
References Dali::Ui::ViewImpl::GetBorderlineWidth, Dali::Ui::GetImpl.
View & Dali::Ui::View::SetBorderlineWidth(float width)
Sets the borderline width of the view.
width The borderline width to set
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetBorderlineWidth.
UiColor Dali::Ui::View::GetBorderlineColor()
Gets the borderline color of the view.
The borderline color
References Dali::Ui::ViewImpl::GetBorderlineColor, Dali::Ui::GetImpl.
View & Dali::Ui::View::SetBorderlineColor(const UiColor &color)
Sets the borderline color of the view.
If the UiColor has a color ID, it is resolved from the current theme and a binding is registered so the color is automatically refreshed when the theme changes. color The UiColor to apply
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetBorderlineColor, VerifyCustomActorPointer.
float Dali::Ui::View::GetBorderlineOffset() const
Gets the borderline offset of the view.
The borderline offset
References Dali::Ui::ViewImpl::GetBorderlineOffset, Dali::Ui::GetImpl.
View & Dali::Ui::View::SetBorderlineOffset(float offset)
Sets the borderline offset of the view.
offset The borderline offset to set
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetBorderlineOffset, VerifyCustomActorPointer.
Dali::String Dali::Ui::View::GetName() const
Gets the name of the view.
The name
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetName.
View & Dali::Ui::View::SetName(const Dali::String &name)
Sets the name of this view.
name The name to set
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetName, VerifyCustomActorPointer.
bool Dali::Ui::View::IsEffectivelyEnabled() const
Returns true if this view and all its View ancestors are enabled.
Unlike IsEnabled(), which only reflects the view's own state, this method walks up the scene hierarchy and returns false if any ancestor View carries ViewState::DISABLED. True if neither the view nor any ancestor is disabled
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::IsEffectivelyEnabled.
bool Dali::Ui::View::IsEffectivelyFocused() const
Returns true if this view or any of its View ancestors is focused.
Unlike the Focused bit in GetState(), this method walks up the scene hierarchy and returns true if any ancestor View carries ViewState::FOCUSED. True if the view itself or at least one ancestor is focused
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::IsEffectivelyFocused.
View & Dali::Ui::View::AsInteractive()
Attaches the interaction trait to this View.
Reference to this View for fluent chaining
View & Dali::Ui::View::AsInteractive(F &&configure)
Attaches the interaction trait to this View and configures it.
configure Callable with signature void(InteractiveTrait&) Reference to this View for fluent chaining
View & Dali::Ui::View::AsSelectable()
Attaches the selectable trait to this View.
A View can have at most one selectable trait. If the View already has a SelectableTrait (e.g. from a previous AsSelectable call), the existing trait is reused. Reference to this View for fluent chaining
View & Dali::Ui::View::AsSelectable(F &&configure)
Attaches the selectable trait to this View and configures it.
A View can have at most one selectable trait. If the View already has a SelectableTrait (e.g. from a previous AsSelectable call), the existing trait is used and the configure callback is invoked with it. configure Callable with signature void(SelectableTrait&) Reference to this View for fluent chaining
View & Dali::Ui::View::As(View &self)
Assigns this View instance to a target variable. This method is useful for capturing a reference to a View created within a declarative UI tree for later use.
View & Dali::Ui::View::With(F &&action)
Executes a custom action on this View instance.
Useful for performing additional setup (e.g. signal connections, predefined style application) without breaking the method chain. action A callable (lambda or free function) invoked with a reference to this instance. Reference to this View for fluent chaining.
View & Dali::Ui::View::SetLayoutParams(LayoutParams params)
Sets layout parameters on this View.
The params handle is stored on the View as-is, and the View's measure cache is invalidated. params The layout parameters to attach to this View Reference to this View for fluent chaining child.SetLayoutParams( AbsoluteLayoutParams::New() .SetBounds(LayoutRect(10,20,100,200)) .SetFlags(AbsoluteLayoutFlags::POSITION_PROPORTIONAL));
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetLayoutParams, VerifyCustomActorPointer.
View & Dali::Ui::View::Children(std::initializer_list< View > children)
Adds a list of children to this View in a declarative way. This method allows for a hierarchical UI tree construction by passing a brace-enclosed initializer list of View objects.
children The initializer list containing child View handles to be added.
void Dali::Ui::View::Insert(uint32_t index, View child)
Inserts a child at the specified index.
index The index where to insert child The child to insert
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::Insert, VerifyCustomActorPointer.
void Dali::Ui::View::RemoveAllChildren()
Removes all children from this View.
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::RemoveAllChildren.
uint32_t Dali::Ui::View::GetChildCount() const
Gets the number of child views.
The child count
References Dali::Ui::ViewImpl::GetChildCount, Dali::Ui::GetImpl.
View Dali::Ui::View::GetChildAt(uint32_t index) const
Gets the child view at the specified index.
index The child index The child view at the index
References Dali::Ui::ViewImpl::GetChildAt, Dali::Ui::GetImpl, VerifyCustomActorPointer.
int32_t Dali::Ui::View::IndexOfChild(View view) const
Returns the index of the given child view, or -1 if not found.
view The child view to find Index of the view, or -1 if not a child
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::IndexOfChild.
void Dali::Ui::View::Raise(LayoutOrderPolicy policy)
Raises this view one step above its immediate next sibling in the parent's children list.
policy UPDATE also reorders the parent layout's children; PRESERVE keeps layout order unchanged and affects only visual z-order. The View has been parented.
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::Raise, VerifyCustomActorPointer.
void Dali::Ui::View::Lower(LayoutOrderPolicy policy)
Lowers this view one step below its immediate previous sibling in the parent's children list.
policy UPDATE also reorders the parent layout's children; PRESERVE keeps layout order unchanged and affects only visual z-order. The View has been parented.
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::Lower, VerifyCustomActorPointer.
void Dali::Ui::View::RaiseToTop(LayoutOrderPolicy policy)
Raises this view to the top of its sibling list.
policy UPDATE also reorders the parent layout's children; PRESERVE keeps layout order unchanged and affects only visual z-order. The View has been parented.
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::RaiseToTop, VerifyCustomActorPointer.
void Dali::Ui::View::LowerToBottom(LayoutOrderPolicy policy)
Lowers this view to the bottom of its sibling list.
policy UPDATE also reorders the parent layout's children; PRESERVE keeps layout order unchanged and affects only visual z-order. The View has been parented.
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::LowerToBottom, VerifyCustomActorPointer.
Referenced by Dali::Ui::Integration::ScrollViewImpl::SetContent.
void Dali::Ui::View::RaiseAbove(View target, LayoutOrderPolicy policy)
Raises this view above the given target sibling.
target The target sibling view to raise above. policy UPDATE also reorders the parent layout's children; PRESERVE keeps layout order unchanged and affects only visual z-order. The View has been parented. The target view is a sibling.
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::RaiseAbove, VerifyCustomActorPointer.
void Dali::Ui::View::LowerBelow(View target, LayoutOrderPolicy policy)
Lowers this view below the given target sibling.
target The target sibling view to lower below. policy UPDATE also reorders the parent layout's children; PRESERVE keeps layout order unchanged and affects only visual z-order. The View has been parented. The target view is a sibling.
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::LowerBelow, VerifyCustomActorPointer.
T Dali::Ui::View::GetLayoutParams() const
Retrieves the layout parameters of a specific type attached to this View.
Returns the stored handle. Modifying the returned handle directly changes the internal data. Call InvalidateMeasure() afterwards if the layout needs to be recalculated. T The concrete LayoutParams type (e.g. AbsoluteLayoutParams, FlexLayoutParams). T must provide static GetLayoutParamsType() and static DownCast(BaseHandle). A valid handle if the params are attached, or an uninitialized handle autoparams=view.GetLayoutParams<AbsoluteLayoutParams>(); if(params) { params.SetWidth(200.0f); view.InvalidateMeasure(); }
const ViewState & Dali::Ui::View::GetState() const
Gets the current state of this View.
The current ViewState (may contain multiple combined states)
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetState.
View::StateChangedSignalType & Dali::Ui::View::StateChangedSignal()
Returns the state changed signal.
Emitted whenever the view's ViewState changes. view.StateChangedSignal().Connect(tracker,[](Viewv,constStateEvent&e){ if(e.Added(ViewState::FOCUSED)){...} }); The StateChangedSignal
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::StateChangedSignal.
InteractiveTrait Dali::Ui::View::EnsureInteractiveTrait()
Ensures this View has an interaction trait and returns it.
If no interaction trait is set, an InteractiveTrait is attached and returned. If an InteractiveTrait is already attached, it is returned. If a different interaction trait is set, an assertion may fire and an empty handle is returned. InteractiveTrait handle, or an uninitialized handle on error
References Dali::Ui::ViewImpl::EnsureInteractiveTrait, Dali::Ui::GetImpl.
bool Dali::Ui::View::IsInteractive() const
Returns whether this View has an interaction trait attached.
True if this View has an InteractiveTrait
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::IsInteractive.
SelectableTrait Dali::Ui::View::EnsureSelectableTrait()
Ensures this View has a selectable trait and returns it.
If no selectable trait is set, a SelectableTrait is attached and returned. If a SelectableTrait is already attached, it is returned. If a different selectable trait type is set, an assertion may fire and an empty handle is returned. SelectableTrait handle, or an uninitialized handle on error
References Dali::Ui::ViewImpl::EnsureSelectableTrait, Dali::Ui::GetImpl.
bool Dali::Ui::View::IsSelectable() const
Returns whether this View has a selectable trait attached.
True if this View has a SelectableTrait
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::IsSelectable.
View & Dali::Ui::View::SetInteractionEffect(Trait effect)
Sets an interaction effect on this view.
The effect is applied when the view becomes interactive (via AsInteractive()). If the view is already interactive, the effect is applied immediately. The effect is frozen at set time — subsequent modifications to the original handle do not affect this view. Pass Trait{} to remove the current effect. If this method is called before AsInteractive(), the explicitly set effect takes priority over the UiConfig default. effect A Trait implementing InteractionEffectInterface, or Trait{} to remove Reference to this View for method chaining
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetInteractionEffect, VerifyCustomActorPointer.
void Dali::Ui::View::ClearBackground()
Clears the background.
References Dali::Ui::ViewImpl::ClearBackground, Dali::Ui::GetImpl.
void Dali::Ui::View::SetRenderEffect(Ui::RenderEffect effect)
Sets RenderEffect to this View.
effect RenderEffect to add. Every effect inherits RenderEffect.
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetRenderEffect, VerifyCustomActorPointer.
Referenced by Dali::Ui::Integration::LabelImpl::SetMaskEffect.
Ui::RenderEffect Dali::Ui::View::GetRenderEffect() const
Retrieves View's render effect.
RenderEffect set on this View
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetRenderEffect.
void Dali::Ui::View::ClearRenderEffect()
Clears RenderEffect of this View, if exists.
References Dali::Ui::ViewImpl::ClearRenderEffect, Dali::Ui::GetImpl.
Referenced by Dali::Ui::Integration::LabelImpl::ClearMaskEffect.
bool Dali::Ui::View::IsResourceReady() const
Query if all resources required by a View are loaded and ready.
Most resources are only loaded when the View is placed on stage. true if the resources are loaded and ready, false otherwise
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::IsResourceReady.
bool Dali::Ui::View::IsOnScene() const
Checks whether the view is connected to the scene.
true if the view is on scene, false otherwise
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::IsOnScene.
View::ResourceReadySignalType & Dali::Ui::View::ResourceReadySignal()
This signal is emitted after all resources required by a View are loaded and ready.
Most resources are only loaded when the View is placed on stage. If resources are shared between ImageViews, they are cached. In this case, the ResourceReady signal may be sent before there is an object to connect to. To protect against this, IsResourceReady() can be checked first. autonewView=View::New(); newView.SetResource(resourceUrl); if(newView.IsResourceReady()) { //dosomething } else { newView.ResourceReadySignal.Connect(....) } A callback of the following type may be connected: voidYourCallbackName(Viewview); The signal to connect to A RelayoutRequest is queued by View before this signal is emitted
References Dali::Ui::GetImpl, VerifyCustomActorPointer.
Referenced by Dali::Ui::AnimatedImageView::ResourceReadySignal, Dali::Ui::ImageView::ResourceReadySignal, Dali::Ui::LottieAnimationView::ResourceReadySignal.
View::OffScreenRenderingFinishedSignalType & Dali::Ui::View::OffScreenRenderingFinishedSignal()
This signal is emitted when offscreen rendering is finished.
A callback of the following type may be connected: voidYourCallbackName(Viewview); The signal to connect to The View has been initialized. This signal is emitted when the offscreen rendering task is completed. This signal is only emitted when OffScreenRenderingType is set to RENDER_ONCE.
References Dali::Ui::GetImpl, VerifyCustomActorPointer.
View::KeyEventSignalType & Dali::Ui::View::KeyEventSignal()
This signal is emitted when key event is received.
A callback of the following type may be connected: boolYourCallbackName(Viewview,constKeyEvent&event); The return value of True, indicates that the event should be consumed. Otherwise the signal will be emitted on the next parent of the actor. The signal to connect to The View has been initialized.
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::KeyEventSignal.
View::FocusChangedSignalType & Dali::Ui::View::FocusChangedSignal()
This signal is emitted when the view gets or loses focus.
A callback of the following type may be connected: boolYourCallbackName(Viewview,boolfocused); The signal to connect to The View has been initialized.
References Dali::Ui::ViewImpl::FocusChangedSignal, Dali::Ui::GetImpl.
ViewAnimationBridge Dali::Ui::View::Animate(Animation animation)
Creates a ViewAnimationBridge for this View.
Returns a lightweight, stack-allocated proxy that applies animations directly to the given Animation for this View. autoanim=Animation::New(); view.Animate(anim).Opacity(0.5f,300_ms); anim.Play(); animation The Animation to apply to A ViewAnimationBridge
References VerifyCustomActorPointer.
void Dali::Ui::View::VerifyCustomActorPointer(Dali::Internal::CustomActor *internal)
Template to allow deriving Views to verify whether the Internal::CustomActor* is actually an implementation of their class.
I The implementation class internal Pointer to the Internal::CustomActor
Referenced by Dali::Ui::WebView::AddCustomHeader, Dali::Ui::WebView::AddJavaScriptMessageHandler, Dali::Ui::Label::Animate, Animate, Arrange, Dali::Ui::AnimatedImageView::DownCast, Dali::Ui::ImageView::DownCast, Dali::Ui::InputField::DownCast, Dali::Ui::InteractiveView::DownCast, Dali::Ui::Label::DownCast, Dali::Ui::AbsoluteLayout::DownCast, Dali::Ui::FlexLayout::DownCast, Dali::Ui::GridLayout::DownCast, Dali::Ui::Layout::DownCast, Dali::Ui::StackLayout::DownCast, Dali::Ui::LottieAnimationView::DownCast, Dali::Ui::ScrollView::DownCast, DownCast, Dali::Ui::WebView::DownCast, Dali::Ui::WebView::EvaluateJavaScript, Dali::Ui::WebView::EvaluateJavaScript, Dali::Ui::WebView::FeedMouseWheel, GetChildAt, Dali::Ui::WebView::GetScreenshot, Dali::Ui::WebView::GetScreenshotAsynchronously, Insert, Dali::Ui::WebView::JavaScriptConfirmReply, Dali::Ui::WebView::JavaScriptPromptReply, Dali::Ui::AnimatedImageView::JumpToFrame, Dali::Ui::LottieAnimationView::JumpToFrame, Dali::Ui::WebView::LoadContents, Dali::Ui::WebView::LoadHtmlString, Dali::Ui::WebView::LoadHtmlStringOverrideCurrentEntry, Dali::Ui::WebView::LoadUrl, Lower, LowerBelow, LowerToBottom, Measure, Dali::Ui::ImageView::New, Dali::Ui::InputField::New, Dali::Ui::InteractiveView::New, Dali::Ui::Label::New, Dali::Ui::AbsoluteLayout::New, Dali::Ui::FlexLayout::New, Dali::Ui::GridLayout::New, Dali::Ui::Layout::New, Dali::Ui::ScrollView::New, New, Dali::Ui::WebView::New, Dali::Ui::Label::New, Dali::Ui::ImageView::New, Dali::Ui::WebView::New, Dali::Ui::AnimatedImageView::New, Dali::Ui::LottieAnimationView::New, Dali::Ui::StackLayout::New, OffScreenRenderingFinishedSignal, Dali::Ui::AbsoluteLayout::operator=, Dali::Ui::FlexLayout::operator=, Dali::Ui::GridLayout::operator=, Dali::Ui::InputField::operator=, Dali::Ui::Label::operator=, Dali::Ui::Layout::operator=, Dali::Ui::ScrollView::operator=, Dali::Ui::StackLayout::operator=, Raise, RaiseAbove, RaiseToTop, Dali::Ui::WebView::RemoveCustomHeader, ResourceReadySignal, Dali::Ui::WebView::ScrollBy, Dali::Ui::WebView::ScrollEdgeBy, Dali::Ui::ScrollView::ScrollTo, Dali::Ui::ScrollView::ScrollTo, Dali::Ui::ScrollView::ScrollToX, Dali::Ui::ScrollView::ScrollToY, Dali::Ui::FlexLayout::SetAlignContent, Dali::Ui::FlexLayout::SetAlignItems, Dali::Ui::AnimatedImageView::SetAlphaMaskUrl, Dali::Ui::ImageView::SetAlphaMaskUrl, Dali::Ui::Label::SetAnchorClickedColor, Dali::Ui::Label::SetAnchorColor, Dali::Ui::Label::SetAsyncRendering, SetBackgroundColor, Dali::Ui::AnimatedImageView::SetBatchSize, Dali::Ui::Label::SetBevel, SetBorderlineColor, SetBorderlineOffset, Dali::Ui::AnimatedImageView::SetCacheSize, Dali::Ui::InteractiveView::SetClickable, Dali::Ui::GridLayout::SetColumnDefinitions, Dali::Ui::ScrollView::SetContent, SetCornerRadius, SetCornerRadius, SetCornerRadius, SetCornerRadiusPolicy, SetCornerSquareness, SetCornerSquareness, SetCornerSquareness, Dali::Ui::AnimatedImageView::SetCropToMask, Dali::Ui::ImageView::SetCropToMask, Dali::Ui::InputField::SetCursorBlinkEnabled, Dali::Ui::InputField::SetCursorBlinkInterval, Dali::Ui::InputField::SetCursorColor, Dali::Ui::WebView::SetCursorEnabledByClient, Dali::Ui::InputField::SetCursorPosition, Dali::Ui::Label::SetCutoutEnabled, Dali::Ui::ScrollView::SetDecelerationRate, Dali::Ui::AnimatedImageView::SetDepthIndex, Dali::Ui::ImageView::SetDepthIndex, Dali::Ui::LottieAnimationView::SetDepthIndex, Dali::Ui::FlexLayout::SetDirection, Dali::Ui::WebView::SetDocumentBackgroundColor, Dali::Ui::LottieAnimationView::SetDynamicProperty, SetEnabled, Dali::Ui::LottieAnimationView::SetEnableFrameCache, Dali::Ui::ImageView::SetFastTrackUpload, Dali::Ui::AnimatedImageView::SetFittingMode, Dali::Ui::ImageView::SetFittingMode, Dali::Ui::ScrollView::SetFlingSensitivity, SetFocusable, Dali::Ui::InputField::SetFontFamily, Dali::Ui::Label::SetFontFamily, Dali::Ui::InputField::SetFontSize, Dali::Ui::Label::SetFontSize, Dali::Ui::InputField::SetFontSizeScale, Dali::Ui::Label::SetFontSizeScale, Dali::Ui::InputField::SetFontSlant, Dali::Ui::Label::SetFontSlant, Dali::Ui::InputField::SetFontVariation, Dali::Ui::Label::SetFontVariation, Dali::Ui::InputField::SetFontVariation, Dali::Ui::Label::SetFontVariation, Dali::Ui::InputField::SetFontWeight, Dali::Ui::Label::SetFontWeight, Dali::Ui::AnimatedImageView::SetFrameDelay, Dali::Ui::AnimatedImageView::SetFrameSpeedFactor, Dali::Ui::LottieAnimationView::SetFrameSpeedFactor, Dali::Ui::ScrollView::SetHorizontalScrollBarVisibility, Dali::Ui::InputField::SetHorizontalTextAlignment, Dali::Ui::Label::SetHorizontalTextAlignment, Dali::Ui::AnimatedImageView::SetImageColor, Dali::Ui::ImageView::SetImageColor, Dali::Ui::LottieAnimationView::SetImageColor, Dali::Ui::AnimatedImageView::SetImageLoadWithViewSize, Dali::Ui::ImageView::SetImageLoadWithViewSize, SetInteractionEffect, Dali::Ui::FlexLayout::SetJustifyContent, Dali::Ui::InteractiveView::SetKeyClickPolicy, Dali::Ui::WebView::SetKeyEventsEnabled, Dali::Ui::InputField::SetLayoutDirectionMode, Dali::Ui::Label::SetLayoutDirectionMode, SetLayoutMode, SetLayoutParams, Dali::Ui::Label::SetLineHeight, Dali::Ui::Label::SetLineHeightMode, Dali::Ui::InputField::SetLineThrough, Dali::Ui::Label::SetLineThrough, Dali::Ui::Label::SetLineWrapMode, Dali::Ui::AnimatedImageView::SetLoadPolicy, Dali::Ui::ImageView::SetLoadPolicy, Dali::Ui::AnimatedImageView::SetLoopCount, Dali::Ui::LottieAnimationView::SetLoopCount, Dali::Ui::LottieAnimationView::SetLoopingMode, SetMargin, Dali::Ui::Label::SetMarkupEnabled, Dali::Ui::Label::SetMarqueeGap, Dali::Ui::Label::SetMarqueeLoopCount, Dali::Ui::Label::SetMarqueeLoopDelay, Dali::Ui::Label::SetMarqueeOrientation, Dali::Ui::Label::SetMarqueeSpeed, Dali::Ui::Label::SetMarqueeStopMode, Dali::Ui::Label::SetMarqueeTriggerPolicy, Dali::Ui::AnimatedImageView::SetMaskingMode, Dali::Ui::ImageView::SetMaskingMode, Dali::Ui::ScrollView::SetMaxFlingDistance, Dali::Ui::ScrollView::SetMaximumFlingDuration, Dali::Ui::InputField::SetMaximumFontSizeScale, Dali::Ui::Label::SetMaximumFontSizeScale, Dali::Ui::InputField::SetMaximumLength, Dali::Ui::ScrollView::SetMinimumFlingDuration, Dali::Ui::InputField::SetMinimumFontSizeScale, Dali::Ui::Label::SetMinimumFontSizeScale, Dali::Ui::LottieAnimationView::SetMinMaxFrame, Dali::Ui::LottieAnimationView::SetMinMaxFrameByMarker, Dali::Ui::WebView::SetMouseEventsEnabled, Dali::Ui::Label::SetMultiLine, SetName, Dali::Ui::LottieAnimationView::SetNotifyAfterRasterization, Dali::Ui::ImageView::SetNPatchBorder, Dali::Ui::ImageView::SetNPatchBorderOnly, SetOpacity, Dali::Ui::StackLayout::SetOrientation, Dali::Ui::ImageView::SetOrientationCorrection, Dali::Ui::InputField::SetOutline, Dali::Ui::Label::SetOutline, Dali::Ui::InputField::SetOverflowMode, Dali::Ui::Label::SetOverflowMode, Dali::Ui::ScrollView::SetOverScrollMode, SetPadding, Dali::Ui::WebView::SetPageZoomFactor, SetParentOrigin, SetPivot, Dali::Ui::AnimatedImageView::SetPixelArea, Dali::Ui::ImageView::SetPixelArea, Dali::Ui::InputField::SetPlaceholder, Dali::Ui::InputField::SetPlaceholderColor, Dali::Ui::AnimatedImageView::SetPlaceholderUrl, Dali::Ui::ImageView::SetPlaceholderUrl, Dali::Ui::LottieAnimationView::SetPlaceholderUrl, Dali::Ui::AnimatedImageView::SetPreMultipliedAlpha, Dali::Ui::ImageView::SetPreMultipliedAlpha, Dali::Ui::LottieAnimationView::SetPreMultipliedAlpha, Dali::Ui::InteractiveView::SetPseudoDisabled, Dali::Ui::LottieAnimationView::SetRedrawOnScaleDown, Dali::Ui::LottieAnimationView::SetRedrawOnScaleUp, Dali::Ui::AnimatedImageView::SetReleasePolicy, Dali::Ui::ImageView::SetReleasePolicy, Dali::Ui::LottieAnimationView::SetReleasePolicy, SetRenderEffect, Dali::Ui::Label::SetRenderScale, Dali::Ui::LottieAnimationView::SetRenderScale, Dali::Ui::AnimatedImageView::SetResourceUrl, Dali::Ui::ImageView::SetResourceUrl, Dali::Ui::LottieAnimationView::SetResourceUrl, Dali::Ui::AnimatedImageView::SetResourceUrls, Dali::Ui::GridLayout::SetRowDefinitions, Dali::Ui::AnimatedImageView::SetSamplingMode, Dali::Ui::ImageView::SetSamplingMode, SetScale, Dali::Ui::WebView::SetScaleFactor, SetScaleX, SetScaleY, Dali::Ui::ScrollView::SetScrollDirection, Dali::Ui::ScrollView::SetScrollPosition, Dali::Ui::InputField::SetSelectionColor, Dali::Ui::InputField::SetShadow, Dali::Ui::Label::SetShadow, Dali::Ui::InputField::SetShowPlaceholderOnFocus, Dali::Ui::AnimatedImageView::SetStopBehavior, Dali::Ui::LottieAnimationView::SetStopBehavior, Dali::Ui::AnimatedImageView::SetSynchronousLoading, Dali::Ui::ImageView::SetSynchronousLoading, Dali::Ui::LottieAnimationView::SetSynchronousLoading, Dali::Ui::InputField::SetSystemFontSizeScaleEnabled, Dali::Ui::Label::SetSystemFontSizeScaleEnabled, Dali::Ui::InputField::SetText, Dali::Ui::Label::SetText, Dali::Ui::InputField::SetTextBackgroundColor, Dali::Ui::Label::SetTextBackgroundColor, Dali::Ui::InputField::SetTextColor, Dali::Ui::Label::SetTextColor, Dali::Ui::Label::SetTextFit, Dali::Ui::Label::SetTextFit, Dali::Ui::WebView::SetTextZoomFactor, Dali::Ui::WebView::SetTileCoverAreaMultiplier, Dali::Ui::WebView::SetTilesClearedWhenHidden, SetTouchFocusable, Dali::Ui::InputField::SetUnderline, Dali::Ui::Label::SetUnderline, Dali::Ui::WebView::SetUserAgent, Dali::Ui::ScrollView::SetVerticalScrollBarVisibility, Dali::Ui::InputField::SetVerticalTextAlignment, Dali::Ui::Label::SetVerticalTextAlignment, Dali::Ui::WebView::SetVideoHoleEnabled, SetVisibility, Dali::Ui::FlexLayout::SetWrap.
View Dali::Ui::View::New()
Creates an initialized View.
A handle to a newly allocated Dali resource
References Dali::Ui::ViewImpl::New, VerifyCustomActorPointer.
View Dali::Ui::View::DownCast(BaseHandle handle)
Downcasts a handle to View handle.
If handle points to a View, the downcast produces valid handle. If not, the returned handle is left uninitialized. handle Handle to an object A handle to a View or an uninitialized handle
References VerifyCustomActorPointer.
Referenced by Dali::Ui::ViewAccessible::ClearHighlight, Dali::Ui::ViewImpl::ClearKeyInputFocus, Dali::Ui::Integration::LabelImpl::ClearMaskEffect, Dali::Ui::ViewAccessible::DoGesture, Dali::Ui::DummyComponent::DownCast, Dali::Ui::ViewAccessible::GetAttributes, Dali::Ui::ViewAccessible::GetDescription, Dali::Ui::ViewAccessible::GetName, Dali::Ui::ViewImpl::GetParentView, Dali::Ui::Integration::InputFieldImpl::GetProperty, Dali::Ui::Integration::LabelImpl::GetProperty, Dali::Ui::ViewAccessible::GetRelationSet, Dali::Ui::Integration::ScrollViewImpl::GetScrollPositionForChild, Dali::Ui::ViewAccessible::GrabHighlight, Dali::Ui::ViewAccessible::IsHidden, Dali::Ui::ViewImpl::Lower, Dali::Ui::ViewImpl::LowerBelow, Dali::Ui::ViewImpl::LowerToBottom, Dali::Ui::Integration::LayoutImpl::OnArrange, Dali::Ui::ViewImpl::OnChildAdd, Dali::Ui::ViewImpl::OnChildRemove, Dali::Ui::ViewImpl::OnFocusChanged, Dali::Ui::Integration::InputFieldImpl::OnInitialize, Dali::Ui::Integration::LabelImpl::OnInitialize, Dali::Ui::ViewImpl::OnKeyEvent, Dali::Ui::Integration::LayoutImpl::OnMeasure, Dali::Ui::ViewImpl::OnPropertySet, Dali::Ui::ViewImpl::Raise, Dali::Ui::ViewImpl::RaiseAbove, Dali::Ui::ViewImpl::RaiseToTop, Dali::Ui::ViewAccessible::RegisterPositionPropertyNotification, Dali::Ui::ViewAccessible::RegisterPropertySetSignal, Dali::Ui::Integration::LayoutControllerImpl::RequestLayout, Dali::Ui::ViewAccessible::ScrollToChild, Dali::Ui::ViewImpl::SetKeyInputFocus, Dali::Ui::Integration::LabelImpl::SetMaskEffect, Dali::Ui::Integration::InputFieldImpl::SetProperty, Dali::Ui::Integration::LabelImpl::SetProperty, Dali::Ui::ViewImpl::SetState, Dali::Ui::ViewAccessible::UnregisterPositionPropertyNotification, Dali::Ui::ViewAccessible::UnregisterPropertySetSignal.
ViewAnimationSpec Dali::Ui::View::NewAnimationSpec()
Creates a new ViewAnimationSpec.
autospec=View::NewAnimationSpec() .Opacity(1.0f,300_ms); spec.ApplyTo(anim,view); A new ViewAnimationSpec
References Dali::Ui::ViewAnimationSpec::New.
static T Dali::Ui::View::DownCast(BaseHandle handle)
Template to allow deriving Views to DownCast handles to deriving handle classes.
T The handle class I The implementation class handle Handle to an object Handle to a class T or an uninitialized handle DownCast(BaseHandle)
BaseHandle Dali::Ui::View::GetLayoutParamsInternal(LayoutParamsType type) const
Retrieves a layout params trait by LayoutParamsType.
type The layout params type identifier The trait as a BaseHandle, or an empty handle if not found