Dali::Ui::ViewAnimationSpec
Dali::Ui::ViewAnimationSpec::ViewAnimationSpec()
Referenced by New.
Dali::Ui::ViewAnimationSpec::ViewAnimationSpec(const ViewAnimationSpec &other)
Dali::Ui::ViewAnimationSpec::ViewAnimationSpec(ViewAnimationSpec &&rhs) noexcept
Dali::Ui::ViewAnimationSpec::~ViewAnimationSpec()
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::operator=(const ViewAnimationSpec &other)
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::operator=(ViewAnimationSpec &&rhs) noexcept
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::BackgroundColor(const UiColor &target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the background color.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::UiColor::Resolve.
Referenced by Dali::Ui::LabelAnimationSpec::BackgroundColor.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::BackgroundColorBy(const UiColor &relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the background color by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::UiColor::Resolve.
Referenced by Dali::Ui::LabelAnimationSpec::BackgroundColorBy.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::SizeWidth(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the size width.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
Referenced by Dali::Ui::LabelAnimationSpec::SizeWidth.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::SizeWidthBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the size width by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
Referenced by Dali::Ui::LabelAnimationSpec::SizeWidthBy.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::SizeHeight(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the size height.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
Referenced by Dali::Ui::LabelAnimationSpec::SizeHeight.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::SizeHeightBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the size height by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
Referenced by Dali::Ui::LabelAnimationSpec::SizeHeightBy.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::ScaleX(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the scale x.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
Referenced by Dali::Ui::LabelAnimationSpec::ScaleX.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::ScaleXBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the scale x by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
Referenced by Dali::Ui::LabelAnimationSpec::ScaleXBy.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::ScaleY(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the scale y.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
Referenced by Dali::Ui::LabelAnimationSpec::ScaleY.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::ScaleYBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the scale y by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
Referenced by Dali::Ui::LabelAnimationSpec::ScaleYBy.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::Opacity(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the opacity.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
Referenced by Dali::Ui::LabelAnimationSpec::Opacity.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::OpacityBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the opacity by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
Referenced by Dali::Ui::LabelAnimationSpec::OpacityBy.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::PositionX(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the position x.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
Referenced by Dali::Ui::LabelAnimationSpec::PositionX.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::PositionXBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the position x by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
Referenced by Dali::Ui::LabelAnimationSpec::PositionXBy.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::PositionY(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the position y.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
Referenced by Dali::Ui::LabelAnimationSpec::PositionY.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::PositionYBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the position y by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
Referenced by Dali::Ui::LabelAnimationSpec::PositionYBy.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::CornerRadius(const Vector4 &target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the corner radius.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::CORNER_RADIUS.
Referenced by Dali::Ui::LabelAnimationSpec::CornerRadius.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::CornerRadiusBy(const Vector4 &relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the corner radius by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::CORNER_RADIUS.
Referenced by Dali::Ui::LabelAnimationSpec::CornerRadiusBy.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::CornerSquareness(const Vector4 &target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the corner squareness.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::CORNER_SQUARENESS.
Referenced by Dali::Ui::LabelAnimationSpec::CornerSquareness.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::CornerSquarenessBy(const Vector4 &relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the corner squareness by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::CORNER_SQUARENESS.
Referenced by Dali::Ui::LabelAnimationSpec::CornerSquarenessBy.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::BorderlineWidth(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the borderline width.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::BORDERLINE_WIDTH.
Referenced by Dali::Ui::LabelAnimationSpec::BorderlineWidth.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::BorderlineWidthBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the borderline width by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::BORDERLINE_WIDTH.
Referenced by Dali::Ui::LabelAnimationSpec::BorderlineWidthBy.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::BorderlineColor(const UiColor &target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the borderline color.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::BORDERLINE_COLOR, Dali::Ui::UiColor::Resolve.
Referenced by Dali::Ui::LabelAnimationSpec::BorderlineColor.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::BorderlineColorBy(const UiColor &relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the borderline color by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::BORDERLINE_COLOR, Dali::Ui::UiColor::Resolve.
Referenced by Dali::Ui::LabelAnimationSpec::BorderlineColorBy.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::BorderlineOffset(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the borderline offset.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::BORDERLINE_OFFSET.
Referenced by Dali::Ui::LabelAnimationSpec::BorderlineOffset.
ViewAnimationSpec & Dali::Ui::ViewAnimationSpec::BorderlineOffsetBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the borderline offset by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::BORDERLINE_OFFSET.
Referenced by Dali::Ui::LabelAnimationSpec::BorderlineOffsetBy.
void Dali::Ui::ViewAnimationSpec::ApplyTo(Animation animation, View view) const
Applies all stored entries to the given Animation and View.
animation The Animation to apply to view The target View
ViewAnimationSpec Dali::Ui::ViewAnimationSpec::New()
References ViewAnimationSpec.
Referenced by Dali::Ui::View::NewAnimationSpec.