Dali::Ui::Integration::UiConfigManager
UiConfigManager Dali::Ui::Integration::UiConfigManager::Get()
Returns the singleton UiConfigManager instance.
The singleton instance
References Dali::Ui::GetImpl, Dali::Ui::Integration::UiConfigManagerImpl::New, UiConfigManager.
Referenced by Dali::Ui::UiConfig::Apply, Dali::Ui::Integration::InputFieldImpl::ApplyInitialConfig, Dali::Ui::Integration::LabelImpl::ApplyInitialConfig, Dali::Ui::ViewImpl::EnsureInteractiveTrait, Dali::Ui::Integration::UiThemeManagerImpl::EnsureThemeLoader, Dali::Ui::Integration::LabelImpl::GetMarqueeGap, Dali::Ui::Integration::LabelImpl::GetMarqueeLoopCount, Dali::Ui::Integration::LabelImpl::GetMarqueeLoopDelay, Dali::Ui::Integration::LabelImpl::GetMarqueeOrientation, Dali::Ui::Integration::LabelImpl::GetMarqueeSpeed, Dali::Ui::Integration::LabelImpl::GetMarqueeStopMode, Dali::Ui::Integration::InteractiveTraitImpl::InteractiveTraitImpl, Dali::Ui::Integration::InteractiveTraitImpl::IsExecutionKey, Dali::Ui::operator""_dp, Dali::Ui::operator""_dp, Dali::Ui::operator""_sdp, Dali::Ui::operator""_sdp, Dali::Ui::operator""_spx, Dali::Ui::operator""_spx.
Dali::Ui::Integration::UiConfigManager::UiConfigManager()
Create a UiConfigManager handle.
Calling member functions with an uninitialised handle is not allowed.
Referenced by Get.
Dali::Ui::Integration::UiConfigManager::~UiConfigManager()
Destructor.
This is non-virtual since derived Handle types must not contain data or virtual methods.
Dali::Ui::Integration::UiConfigManager::UiConfigManager(const UiConfigManager &rhs)
This copy constructor is required for (smart) pointer semantics.
rhs A reference to the copied handle
UiConfigManager & Dali::Ui::Integration::UiConfigManager::operator=(const UiConfigManager &rhs)
This assignment operator is required for (smart) pointer semantics.
It makes this handle use the same BaseObject as the copied handle rhs A reference to the copied handle A reference to this handle
Dali::Ui::Integration::UiConfigManager::UiConfigManager(UiConfigManager &&rhs) noexcept
Move constructor.
rhs A reference to the moved handle
UiConfigManager & Dali::Ui::Integration::UiConfigManager::operator=(UiConfigManager &&rhs) noexcept
Move assignment operator.
rhs A reference to the moved handle A reference to this handle
void Dali::Ui::Integration::UiConfigManager::Initialize(const UiConfig &config)
Initializes the manager with the given UiConfig.
This method must be called exactly once before the application main loop starts. After this call, the UiConfig is frozen and its setter methods can no longer be used. Calling Initialize() more than once triggers an assertion failure. config The UiConfig to use globally
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::Initialize.
Referenced by Dali::Ui::UiConfig::Apply.
bool Dali::Ui::Integration::UiConfigManager::IsInitialized() const
Returns whether Initialize() has been called.
True if the manager has been initialized
References Dali::Ui::GetImpl.
const UiConfig & Dali::Ui::Integration::UiConfigManager::GetConfig() const
Returns the global UiConfig instance.
Initialize() must have been called. Triggers assertion failure otherwise. The global UiConfig handle
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::Integration::InputFieldImpl::ApplyInitialConfig, Dali::Ui::Integration::LabelImpl::ApplyInitialConfig, Dali::Ui::ViewImpl::EnsureInteractiveTrait, Dali::Ui::Integration::LabelImpl::GetMarqueeGap, Dali::Ui::Integration::LabelImpl::GetMarqueeLoopCount, Dali::Ui::Integration::LabelImpl::GetMarqueeLoopDelay, Dali::Ui::Integration::LabelImpl::GetMarqueeOrientation, Dali::Ui::Integration::LabelImpl::GetMarqueeSpeed, Dali::Ui::Integration::LabelImpl::GetMarqueeStopMode, Dali::Ui::Integration::InteractiveTraitImpl::IsExecutionKey, Dali::Ui::operator""_dp, Dali::Ui::operator""_dp, Dali::Ui::operator""_sdp, Dali::Ui::operator""_sdp, Dali::Ui::operator""_spx, Dali::Ui::operator""_spx.
ThemeLoaderInterface * Dali::Ui::Integration::UiConfigManager::CreateThemeLoader()
References Dali::Ui::GetImpl.
Dali::Ui::Integration::UiConfigManager::UiConfigManager(UiConfigManagerImpl *impl)