Dali::Ui::UiColorManager
Dali::Ui::UiColorManager::UiColorManager()
Creates an uninitialized UiColorManager handle.
Dali::Ui::UiColorManager::~UiColorManager()=default
Destructor.
Dali::Ui::UiColorManager::UiColorManager(const UiColorManager &handle)=default
Copy constructor.
handle Handle to copy
Dali::Ui::UiColorManager::UiColorManager(UiColorManager &&rhs) noexcept=default
Move constructor.
rhs Handle to move
UiColorManager & Dali::Ui::UiColorManager::operator=(const UiColorManager &handle)=default
Copy assignment operator.
handle Object to assign this to Reference to this
UiColorManager & Dali::Ui::UiColorManager::operator=(UiColorManager &&rhs) noexcept=default
Move assignment operator.
rhs Object to assign this to Reference to this
Vector4 Dali::Ui::UiColorManager::GetColor(StringView colorId) const
Looks up a single color by its identifier.
colorId The color identifier The resolved RGBA value, or Vector4::ZERO if not found
References Dali::Ui::GetImpl.
bool Dali::Ui::UiColorManager::GetColor(StringView colorId, Vector4 &outColor) const
Looks up a color by its identifier.
colorId The color identifier outColor The resolved RGBA value if found True if the color was found
References Dali::Ui::GetImpl.
void Dali::Ui::UiColorManager::RegisterBinding(BaseHandle view, StringView bindingId, ColorCallback callback)
Registers a named color binding for an object.
Associates callback with the given bindingId. The callback is invoked whenever the theme changes and a color has been set via UpdateBinding(). If a binding with the same bindingId already exists, it is replaced. Does not invoke the callback immediately. Ownership of callback is transferred to the manager. view The target object bindingId A caller-defined identifier for this binding (e.g. "BackgroundColor") callback A ColorCallback created via ColorCallback::New(), invoked on color table change to apply the resolved color manager.RegisterBinding(Self(),"BackgroundColor",ColorCallback::New(this,&MyImpl::SetBg));
References Dali::Ui::GetImpl.
bool Dali::Ui::UiColorManager::GetBindingColor(BaseHandle view, StringView bindingId, UiColor &outColor) const
Retrieves the UiColor associated with a named binding.
view The target object bindingId The binding identifier used in UpdateBinding outColor The bound UiColor if found true if a binding was found, false otherwise
References Dali::Ui::GetImpl.
bool Dali::Ui::UiColorManager::HasBinding(BaseHandle view, StringView bindingId) const
Returns whether a named binding exists for an object.
view The target object bindingId The binding identifier true if a binding with the given id is registered
References Dali::Ui::GetImpl.
void Dali::Ui::UiColorManager::SetBindingColor(BaseHandle view, StringView bindingId, const UiColor &color)
Sets the color for an existing named binding.
Stores color so the callback is invoked with the resolved value on theme change. If no binding with bindingId exists, this call is a no-op. view The target object bindingId The binding identifier used in RegisterBinding color The new UiColor to store (must have a color ID)
References Dali::Ui::GetImpl.
void Dali::Ui::UiColorManager::ClearBinding(BaseHandle view, StringView bindingId)
Removes a named binding.
view The target object bindingId The binding identifier used in UpdateBinding
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::ViewImpl::ClearBackground, Dali::Ui::Integration::LabelImpl::ClearBevel, Dali::Ui::Integration::InputFieldImpl::ClearLineThrough, Dali::Ui::Integration::LabelImpl::ClearLineThrough, Dali::Ui::Integration::InputFieldImpl::ClearOutline, Dali::Ui::Integration::LabelImpl::ClearOutline, Dali::Ui::Integration::InputFieldImpl::ClearShadow, Dali::Ui::Integration::LabelImpl::ClearShadow, Dali::Ui::Integration::InputFieldImpl::ClearTextBackgroundColor, Dali::Ui::Integration::LabelImpl::ClearTextBackgroundColor, Dali::Ui::Integration::InputFieldImpl::ClearUnderline, Dali::Ui::Integration::LabelImpl::ClearUnderline.
void Dali::Ui::UiColorManager::ClearBindings(BaseHandle view)
Removes all bindings associated with a given object.
view The target object to unbind completely
References Dali::Ui::GetImpl.
void Dali::Ui::UiColorManager::SetColorOverride(ColorOverrideFunc func)
Sets a function that overrides theme color lookups.
When set, this function is invoked before querying the theme loader for every color lookup. If the function returns true, the output color is used and the theme loader is skipped. If it returns false, the normal theme lookup proceeds. Setting the override immediately refreshes all existing View bindings so that the overridden colors are applied without delay. This parameter is a plain function pointer (ColorOverrideFunc). Lambdas with captures and member function pointers are not accepted. Only free functions or stateless lambdas may be used. Passing nullptr clears the override, equivalent to calling ClearColorOverride(). All View bindings are refreshed to use theme values. The function may be called on any thread that invokes GetColor() or triggers a theme change. The implementation must be thread-safe if colors are queried from multiple threads. func A function pointer matching the ColorOverrideFunc signature, or nullptr to clear the override boolMyOverride(StringViewid,Vector4&out){ if(id=="Primary"){out=Vector4(1,0,0,1);returntrue;} returnfalse; } UiColorManager::Get().SetColorOverride(MyOverride);
References Dali::Ui::GetImpl.
void Dali::Ui::UiColorManager::ClearColorOverride()
Clears the color override callback.
All View bindings are immediately refreshed to use the theme values.
References Dali::Ui::GetImpl.
UiColorManager Dali::Ui::UiColorManager::Get()
Returns the singleton UiColorManager instance.
Creates the instance on first call. A handle to the UiColorManager singleton
Referenced by Dali::Ui::ViewImpl::ClearBackground, Dali::Ui::Integration::LabelImpl::ClearBevel, Dali::Ui::Integration::InputFieldImpl::ClearLineThrough, Dali::Ui::Integration::LabelImpl::ClearLineThrough, Dali::Ui::Integration::InputFieldImpl::ClearOutline, Dali::Ui::Integration::LabelImpl::ClearOutline, Dali::Ui::Integration::InputFieldImpl::ClearShadow, Dali::Ui::Integration::LabelImpl::ClearShadow, Dali::Ui::Integration::InputFieldImpl::ClearTextBackgroundColor, Dali::Ui::Integration::LabelImpl::ClearTextBackgroundColor, Dali::Ui::Integration::InputFieldImpl::ClearUnderline, Dali::Ui::Integration::LabelImpl::ClearUnderline, Dali::Ui::Integration::LabelImpl::GetAnchorClickedColor, Dali::Ui::Integration::LabelImpl::GetAnchorColor, Dali::Ui::ViewImpl::GetBackgroundColor, Dali::Ui::ViewImpl::GetBorderlineColor, Dali::Ui::Integration::InputFieldImpl::GetCursorColor, Dali::Ui::Integration::InputFieldImpl::GetPlaceholderColor, Dali::Ui::Integration::InputFieldImpl::GetSelectionColor, Dali::Ui::Integration::InputFieldImpl::GetTextBackgroundColor, Dali::Ui::Integration::LabelImpl::GetTextBackgroundColor, Dali::Ui::Integration::InputFieldImpl::GetTextColor, Dali::Ui::Integration::LabelImpl::GetTextColor, Dali::Ui::UiColor::Resolve, Dali::Ui::ViewImpl::~ViewImpl.
UiColorManager Dali::Ui::UiColorManager::DownCast(BaseHandle handle)
Downcasts a handle to a UiColorManager handle.
handle Handle to an object A handle to a UiColorManager or an uninitialized handle