Dali::Ui::Integration::AnimatedImageViewImpl
Ui::Visual::Base Dali::Ui::Integration::AnimatedImageViewImpl::mVisual
The main image visual.
Dali::String Dali::Ui::Integration::AnimatedImageViewImpl::mUrl
Dali::String Dali::Ui::Integration::AnimatedImageViewImpl::mAlphaMaskUrl
Dali::String Dali::Ui::Integration::AnimatedImageViewImpl::mPlaceholderUrl
Dali::Vector<Dali::String> Dali::Ui::Integration::AnimatedImageViewImpl::mUrls
Vector4 Dali::Ui::Integration::AnimatedImageViewImpl::mPixelArea
UiColor Dali::Ui::Integration::AnimatedImageViewImpl::mImageColor
AnimatedImageViewStopBehavior::Type Dali::Ui::Integration::AnimatedImageViewImpl::mStopBehavior
Ui::FittingMode::Type Dali::Ui::Integration::AnimatedImageViewImpl::mFittingMode
Ui::SamplingMode::Type Dali::Ui::Integration::AnimatedImageViewImpl::mSamplingMode
Ui::MaskingType::Type Dali::Ui::Integration::AnimatedImageViewImpl::mMaskingMode
Ui::LoadPolicy::Type Dali::Ui::Integration::AnimatedImageViewImpl::mLoadPolicy
Ui::ReleasePolicy::Type Dali::Ui::Integration::AnimatedImageViewImpl::mReleasePolicy
int Dali::Ui::Integration::AnimatedImageViewImpl::mLoopCount
int Dali::Ui::Integration::AnimatedImageViewImpl::mBatchSize
int Dali::Ui::Integration::AnimatedImageViewImpl::mCacheSize
int Dali::Ui::Integration::AnimatedImageViewImpl::mFrameDelay
int Dali::Ui::Integration::AnimatedImageViewImpl::mDesiredWidth
int Dali::Ui::Integration::AnimatedImageViewImpl::mDesiredHeight
int Dali::Ui::Integration::AnimatedImageViewImpl::mDepthIndex
float Dali::Ui::Integration::AnimatedImageViewImpl::mFrameSpeedFactor
bool Dali::Ui::Integration::AnimatedImageViewImpl::mPreMultipliedAlpha
bool Dali::Ui::Integration::AnimatedImageViewImpl::mImageLoadWithViewSize
bool Dali::Ui::Integration::AnimatedImageViewImpl::mCropToMask
bool Dali::Ui::Integration::AnimatedImageViewImpl::mSynchronousLoading
bool Dali::Ui::Integration::AnimatedImageViewImpl::mVisualDirty
True when a property changed and the visual needs rebuilding on the next measure pass.
Dali::Signal<void(Dali::Ui::View)> Dali::Ui::Integration::AnimatedImageViewImpl::mAnimationFinishedSignal
Dali::Ui::Integration::AnimatedImageViewImpl::AnimatedImageViewImpl()
AnimatedImageViewImpl constructor.
Referenced by New.
Dali::Ui::Integration::AnimatedImageViewImpl::~AnimatedImageViewImpl()
A reference counted object may only be deleted by calling Unreference().
AnimatedImageViewImplPtr Dali::Ui::Integration::AnimatedImageViewImpl::New()
Creates a new AnimatedImageViewImpl.
An intrusive pointer to the newly allocated AnimatedImageViewImpl
References AnimatedImageViewImpl.
Referenced by Dali::Ui::AnimatedImageView::New.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetResourceUrl(const Dali::String &url)
Sets the URL of the animated image resource to display.
url The URL of the image resource Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetResourceUrl, Dali::Ui::ImageView::SetResourceUrl, Dali::Ui::LottieAnimationView::SetResourceUrl.
Dali::String Dali::Ui::Integration::AnimatedImageViewImpl::GetResourceUrl() const
Gets the URL of the animated image resource.
The URL of the image resource
Referenced by Dali::Ui::AnimatedImageView::GetResourceUrl, Dali::Ui::ImageView::GetResourceUrl, Dali::Ui::LottieAnimationView::GetResourceUrl.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetResourceUrls(const Dali::Vector< Dali::String > &urls)
Sets an array of image URLs for frame-by-frame animation.
Setting this overrides any single URL set via SetResourceUrl(). The images are played in sequence as animation frames. urls Array of image URLs Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetResourceUrls.
const Dali::Vector< Dali::String > & Dali::Ui::Integration::AnimatedImageViewImpl::GetResourceUrls() const
Gets the array of image URLs.
The current array of image URLs, or empty if not set
Referenced by Dali::Ui::AnimatedImageView::GetResourceUrls.
void Dali::Ui::Integration::AnimatedImageViewImpl::Play()
Starts or resumes playback of the animation.
Reference to this for fluent chaining
References Dali::Ui::Integration::AnimatedImageViewImpl::Property::IMAGE, Dali::Ui::DevelAnimatedImageVisual::Action::PLAY.
Referenced by Dali::Ui::AnimatedImageView::Play, Dali::Ui::LottieAnimationView::Play.
void Dali::Ui::Integration::AnimatedImageViewImpl::Pause()
Pauses playback of the animation.
Reference to this for fluent chaining
References Dali::Ui::Integration::AnimatedImageViewImpl::Property::IMAGE, Dali::Ui::DevelAnimatedImageVisual::Action::PAUSE.
Referenced by Dali::Ui::AnimatedImageView::Pause, Dali::Ui::LottieAnimationView::Pause.
void Dali::Ui::Integration::AnimatedImageViewImpl::Stop()
Stops playback of the animation and resets to the first frame.
Reference to this for fluent chaining
References Dali::Ui::Integration::AnimatedImageViewImpl::Property::IMAGE, Dali::Ui::DevelAnimatedImageVisual::Action::STOP.
Referenced by Dali::Ui::AnimatedImageView::Stop, Dali::Ui::LottieAnimationView::Stop.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetLoopCount(int count)
Sets the number of times the animation should loop.
A value of -1 means infinite looping. A value of 0 means the animation will not play. A positive value specifies an exact loop count. count The loop count (-1 for infinite) Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetLoopCount, Dali::Ui::LottieAnimationView::SetLoopCount.
int Dali::Ui::Integration::AnimatedImageViewImpl::GetLoopCount() const
Gets the current loop count.
The loop count, or -1 for infinite looping
Referenced by Dali::Ui::AnimatedImageView::GetLoopCount, Dali::Ui::LottieAnimationView::GetLoopCount.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetImageColor(const UiColor &color)
Sets the color applied to the image.
color The color to apply Reference to this for fluent chaining
References Dali::Ui::Visual::Base::DoAction, Dali::Ui::ViewImpl::InvalidateMeasure, Dali::Ui::Visual::Property::MIX_COLOR, Dali::Ui::UiColor::Resolve, Dali::Ui::DevelVisual::Action::UPDATE_PROPERTY.
Referenced by Dali::Ui::AnimatedImageView::SetImageColor, Dali::Ui::ImageView::SetImageColor, Dali::Ui::LottieAnimationView::SetImageColor.
UiColor Dali::Ui::Integration::AnimatedImageViewImpl::GetImageColor() const
Gets the color applied to the image.
The current image color
Referenced by Dali::Ui::AnimatedImageView::GetImageColor, Dali::Ui::ImageView::GetImageColor, Dali::Ui::LottieAnimationView::GetImageColor.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetFittingMode(Ui::FittingMode::Type fittingMode)
Sets how the image is fitted within the view bounds.
The default fitting mode is Ui::FittingMode::FILL (stretch to fill). fittingMode The fitting mode to use Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetFittingMode, Dali::Ui::ImageView::SetFittingMode.
Ui::FittingMode::Type Dali::Ui::Integration::AnimatedImageViewImpl::GetFittingMode() const
Gets the fitting mode.
The current fitting mode (default: FILL)
Referenced by Dali::Ui::AnimatedImageView::GetFittingMode, Dali::Ui::ImageView::GetFittingMode.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetSamplingMode(Ui::SamplingMode::Type samplingMode)
Sets the sampling mode used when scaling the image.
samplingMode The sampling mode to use Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetSamplingMode, Dali::Ui::ImageView::SetSamplingMode.
Ui::SamplingMode::Type Dali::Ui::Integration::AnimatedImageViewImpl::GetSamplingMode() const
Gets the sampling mode.
The current sampling mode
Referenced by Dali::Ui::AnimatedImageView::GetSamplingMode, Dali::Ui::ImageView::GetSamplingMode.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetImageLoadWithViewSize(bool enabled)
Sets whether the image is loaded synchronously at the current view size.
enabled True to enable loading image with view size Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetImageLoadWithViewSize, Dali::Ui::ImageView::SetImageLoadWithViewSize.
bool Dali::Ui::Integration::AnimatedImageViewImpl::IsImageLoadWithViewSizeEnabled() const
Gets whether the image is loaded with the view size.
True if loading image with view size is enabled
Referenced by Dali::Ui::AnimatedImageView::IsImageLoadWithViewSizeEnabled, Dali::Ui::ImageView::IsImageLoadWithViewSizeEnabled.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetAlphaMaskUrl(const Dali::String &maskUrl)
Sets the URL of an alpha mask image.
maskUrl The URL of the alpha mask image Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetAlphaMaskUrl, Dali::Ui::ImageView::SetAlphaMaskUrl.
Dali::String Dali::Ui::Integration::AnimatedImageViewImpl::GetAlphaMaskUrl() const
Gets the alpha mask image URL.
The URL of the alpha mask image, or empty string if not set
Referenced by Dali::Ui::AnimatedImageView::GetAlphaMaskUrl, Dali::Ui::ImageView::GetAlphaMaskUrl.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetCropToMask(bool cropToMask)
Sets whether the image should be cropped to the mask bounds.
cropToMask True to crop the image to the mask Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetCropToMask, Dali::Ui::ImageView::SetCropToMask.
bool Dali::Ui::Integration::AnimatedImageViewImpl::IsCropToMask() const
Gets whether crop-to-mask is enabled.
True if crop-to-mask is enabled
Referenced by Dali::Ui::AnimatedImageView::IsCropToMask, Dali::Ui::ImageView::IsCropToMask.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetMaskingMode(Ui::MaskingType::Type maskingMode)
Sets the masking mode.
maskingMode The masking mode to use Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetMaskingMode, Dali::Ui::ImageView::SetMaskingMode.
Ui::MaskingType::Type Dali::Ui::Integration::AnimatedImageViewImpl::GetMaskingMode() const
Gets the masking mode.
The current masking mode
Referenced by Dali::Ui::AnimatedImageView::GetMaskingMode, Dali::Ui::ImageView::GetMaskingMode.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetPlaceholderUrl(const Dali::String &url)
Sets the URL of a placeholder image shown while loading.
url The URL of the placeholder image Reference to this for fluent chaining
Referenced by Dali::Ui::AnimatedImageView::SetPlaceholderUrl, Dali::Ui::ImageView::SetPlaceholderUrl, Dali::Ui::LottieAnimationView::SetPlaceholderUrl.
Dali::String Dali::Ui::Integration::AnimatedImageViewImpl::GetPlaceholderUrl() const
Gets the placeholder image URL.
The URL of the placeholder image, or empty string if not set
Referenced by Dali::Ui::AnimatedImageView::GetPlaceholderUrl, Dali::Ui::ImageView::GetPlaceholderUrl, Dali::Ui::LottieAnimationView::GetPlaceholderUrl.
void Dali::Ui::Integration::AnimatedImageViewImpl::JumpToFrame(int frame)
Jumps to the specified frame number.
frame The frame index to jump to Reference to this for fluent chaining
References Dali::Ui::Integration::AnimatedImageViewImpl::Property::IMAGE, Dali::Ui::DevelAnimatedImageVisual::Action::JUMP_TO.
Referenced by Dali::Ui::AnimatedImageView::JumpToFrame, Dali::Ui::LottieAnimationView::JumpToFrame.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetStopBehavior(AnimatedImageViewStopBehavior::Type behavior)
Sets the behavior of the animation when it is stopped.
behavior The stop behavior (CURRENT_FRAME, FIRST_FRAME, or LAST_FRAME) Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetStopBehavior, Dali::Ui::LottieAnimationView::SetStopBehavior.
AnimatedImageViewStopBehavior::Type Dali::Ui::Integration::AnimatedImageViewImpl::GetStopBehavior() const
Gets the current stop behavior.
The current stop behavior
Referenced by Dali::Ui::AnimatedImageView::GetStopBehavior, Dali::Ui::LottieAnimationView::GetStopBehavior.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetFrameSpeedFactor(float factor)
Sets the speed factor for animation playback.
Values between [0, 1] slow down the animation; values above 1 speed it up. The actual clamping to [0.01, 100.0] is handled by the underlying animation renderer. factor The speed multiplier (default: 1.0) Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetFrameSpeedFactor, Dali::Ui::LottieAnimationView::SetFrameSpeedFactor.
float Dali::Ui::Integration::AnimatedImageViewImpl::GetFrameSpeedFactor() const
Gets the current frame speed factor.
The frame speed factor
Referenced by Dali::Ui::AnimatedImageView::GetFrameSpeedFactor, Dali::Ui::LottieAnimationView::GetFrameSpeedFactor.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetBatchSize(int size)
Sets the number of frames to pre-load in each batch.
size The batch size (default: 1) Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetBatchSize.
int Dali::Ui::Integration::AnimatedImageViewImpl::GetBatchSize() const
Gets the current batch size.
The batch size
Referenced by Dali::Ui::AnimatedImageView::GetBatchSize.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetCacheSize(int size)
Sets the number of frames to keep in cache.
size The cache size (default: 1) Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetCacheSize.
int Dali::Ui::Integration::AnimatedImageViewImpl::GetCacheSize() const
Gets the current cache size.
The cache size
Referenced by Dali::Ui::AnimatedImageView::GetCacheSize.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetFrameDelay(int milliseconds)
Sets the delay in milliseconds between each frame.
Overrides the frame delay embedded in the image file. milliseconds The delay between frames in milliseconds Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetFrameDelay.
int Dali::Ui::Integration::AnimatedImageViewImpl::GetFrameDelay() const
Gets the current frame delay override.
The frame delay in milliseconds, or -1 if not overridden
Referenced by Dali::Ui::AnimatedImageView::GetFrameDelay.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetPixelArea(const Vector4 &pixelArea)
Sets the pixel area used to display a sub-region of the image.
The area is specified as normalized coordinates: (x, y, width, height) where each component is in the range [0, 1]. pixelArea The normalized sub-region of the image to display Reference to this for fluent chaining
References Dali::Ui::Visual::Base::DoAction, Dali::Ui::ImageVisual::Property::PIXEL_AREA, Dali::Ui::DevelVisual::Action::UPDATE_PROPERTY.
Referenced by Dali::Ui::AnimatedImageView::SetPixelArea, Dali::Ui::ImageView::SetPixelArea.
Vector4 Dali::Ui::Integration::AnimatedImageViewImpl::GetPixelArea() const
Gets the pixel area.
The current pixel area as normalized coordinates
Referenced by Dali::Ui::AnimatedImageView::GetPixelArea, Dali::Ui::ImageView::GetPixelArea.
AnimatedImageViewPlayState::Type Dali::Ui::Integration::AnimatedImageViewImpl::GetPlayState() const
Gets the current playback state of the animation.
The current PlayState
References Dali::Ui::Visual::Base::CreatePropertyMap, Dali::Ui::DevelImageVisual::Property::PLAY_STATE, Dali::Ui::AnimatedImageViewPlayState::STOPPED.
Referenced by Dali::Ui::AnimatedImageView::GetPlayState, Dali::Ui::LottieAnimationView::GetPlayState.
int Dali::Ui::Integration::AnimatedImageViewImpl::GetCurrentFrame() const
Gets the current frame number being displayed.
The current frame index
References Dali::Ui::Visual::Base::CreatePropertyMap, Dali::Ui::DevelImageVisual::Property::CURRENT_FRAME_NUMBER.
Referenced by Dali::Ui::AnimatedImageView::GetCurrentFrame, Dali::Ui::LottieAnimationView::GetCurrentFrame.
int Dali::Ui::Integration::AnimatedImageViewImpl::GetTotalFrame() const
Gets the total number of frames in the animation.
The total frame count
References Dali::Ui::Visual::Base::CreatePropertyMap, Dali::Ui::DevelImageVisual::Property::TOTAL_FRAME_NUMBER.
Referenced by Dali::Ui::AnimatedImageView::GetTotalFrame, Dali::Ui::LottieAnimationView::GetTotalFrame.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetDesiredWidth(int width)
Sets the desired image width used as a hint for the image loader.
width The desired width in pixels (0 to use natural size) Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetDesiredWidth, Dali::Ui::ImageView::SetDesiredWidth, Dali::Ui::LottieAnimationView::SetDesiredWidth.
int Dali::Ui::Integration::AnimatedImageViewImpl::GetDesiredWidth() const
Gets the desired image width hint.
The desired width in pixels, or 0 if not set
Referenced by Dali::Ui::AnimatedImageView::GetDesiredWidth, Dali::Ui::ImageView::GetDesiredWidth, Dali::Ui::LottieAnimationView::GetDesiredWidth.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetDesiredHeight(int height)
Sets the desired image height used as a hint for the image loader.
height The desired height in pixels (0 to use natural size) Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetDesiredHeight, Dali::Ui::ImageView::SetDesiredHeight, Dali::Ui::LottieAnimationView::SetDesiredHeight.
int Dali::Ui::Integration::AnimatedImageViewImpl::GetDesiredHeight() const
Gets the desired image height hint.
The desired height in pixels, or 0 if not set
Referenced by Dali::Ui::AnimatedImageView::GetDesiredHeight, Dali::Ui::ImageView::GetDesiredHeight, Dali::Ui::LottieAnimationView::GetDesiredHeight.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetLoadPolicy(Ui::LoadPolicy::Type loadPolicy)
Sets the load policy for the image resource.
loadPolicy The load policy to use Reference to this for fluent chaining
References Dali::Ui::LoadPolicy::IMMEDIATE, Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetLoadPolicy, Dali::Ui::ImageView::SetLoadPolicy.
Ui::LoadPolicy::Type Dali::Ui::Integration::AnimatedImageViewImpl::GetLoadPolicy() const
Gets the load policy.
The current load policy
Referenced by Dali::Ui::AnimatedImageView::GetLoadPolicy, Dali::Ui::ImageView::GetLoadPolicy.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetReleasePolicy(Ui::ReleasePolicy::Type releasePolicy)
Sets the release policy for the image resource.
releasePolicy The release policy to use Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetReleasePolicy, Dali::Ui::ImageView::SetReleasePolicy, Dali::Ui::LottieAnimationView::SetReleasePolicy.
Ui::ReleasePolicy::Type Dali::Ui::Integration::AnimatedImageViewImpl::GetReleasePolicy() const
Gets the release policy.
The current release policy
Referenced by Dali::Ui::AnimatedImageView::GetReleasePolicy, Dali::Ui::ImageView::GetReleasePolicy, Dali::Ui::LottieAnimationView::GetReleasePolicy.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetSynchronousLoading(bool synchronous)
Sets whether the image is loaded synchronously.
synchronous True to load the image on the main thread synchronously Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetSynchronousLoading, Dali::Ui::ImageView::SetSynchronousLoading, Dali::Ui::LottieAnimationView::SetSynchronousLoading.
bool Dali::Ui::Integration::AnimatedImageViewImpl::IsSynchronousLoading() const
Gets whether synchronous loading is enabled.
True if synchronous loading is enabled
Referenced by Dali::Ui::AnimatedImageView::IsSynchronousLoading, Dali::Ui::ImageView::IsSynchronousLoading, Dali::Ui::LottieAnimationView::IsSynchronousLoading.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetPreMultipliedAlpha(bool preMultiplied)
Sets whether the image uses pre-multiplied alpha.
preMultiplied True if the image has pre-multiplied alpha Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::AnimatedImageView::SetPreMultipliedAlpha, Dali::Ui::ImageView::SetPreMultipliedAlpha, Dali::Ui::LottieAnimationView::SetPreMultipliedAlpha.
bool Dali::Ui::Integration::AnimatedImageViewImpl::IsPreMultipliedAlpha() const
Gets whether pre-multiplied alpha is enabled.
True if pre-multiplied alpha is enabled
Referenced by Dali::Ui::AnimatedImageView::IsPreMultipliedAlpha, Dali::Ui::ImageView::IsPreMultipliedAlpha, Dali::Ui::LottieAnimationView::IsPreMultipliedAlpha.
void Dali::Ui::Integration::AnimatedImageViewImpl::SetDepthIndex(int depthIndex)
Sets the depth index for the image.
depthIndex The depth index to set Reference to this for fluent chaining
References Dali::Ui::Integration::AnimatedImageViewImpl::Property::IMAGE.
Referenced by Dali::Ui::AnimatedImageView::SetDepthIndex, Dali::Ui::ImageView::SetDepthIndex, Dali::Ui::LottieAnimationView::SetDepthIndex.
Ui::Visual::ResourceStatus Dali::Ui::Integration::AnimatedImageViewImpl::GetLoadingStatus() const
Gets the current loading status of the image.
The current ResourceStatus of the image visual
References Dali::Ui::Integration::AnimatedImageViewImpl::Property::IMAGE.
Referenced by Dali::Ui::AnimatedImageView::GetLoadingStatus, Dali::Ui::ImageView::GetLoadingStatus, Dali::Ui::LottieAnimationView::GetLoadingStatus.
Dali::Signal< void(Dali::Ui::View)> & Dali::Ui::Integration::AnimatedImageViewImpl::AnimationFinishedSignal()
Returns the signal emitted when the animation finishes all loops.
A reference to the AnimationFinished signal
Referenced by Dali::Ui::AnimatedImageView::AnimationFinishedSignal, Dali::Ui::LottieAnimationView::AnimationFinishedSignal.
void Dali::Ui::Integration::AnimatedImageViewImpl::OnInitialize() override
Called after the actor has been initialized.
MeasuredSize Dali::Ui::Integration::AnimatedImageViewImpl::OnMeasure(float widthConstraint, float heightConstraint) override
Called during measure pass. Override to implement custom measurement.
MeasuredSize Dali::Ui::Integration::AnimatedImageViewImpl::OnArrange(const LayoutRect &bounds) override
Called during arrange pass. Override to implement custom arrangement.
void Dali::Ui::Integration::AnimatedImageViewImpl::UpdateVisual()
Rebuilds and re-registers the image visual from current property values.
void Dali::Ui::Integration::AnimatedImageViewImpl::UpdatePlaceholderVisual()
Rebuilds and re-registers the placeholder visual.
void Dali::Ui::Integration::AnimatedImageViewImpl::ApplyFittingMode(const Vector2 &size)
Applies the current fitting mode to the visual.
size The size of the view
void Dali::Ui::Integration::AnimatedImageViewImpl::OnVisualEvent(View view, Dali::Property::Index visualIndex, Dali::Property::Index signalId)
Called when a visual event signal is emitted.
Used to intercept ANIMATION_FINISHED and forward it as AnimationFinishedSignal.
void Dali::Ui::Integration::AnimatedImageViewImpl::OnViewResourceReady(Ui::View view)
Called when the view's resource becomes ready.
Used to remove placeholder when main image is loaded.
Dali::Ui::Integration::AnimatedImageViewImpl::AnimatedImageViewImpl(const AnimatedImageViewImpl &)=delete
Dali::Ui::Integration::AnimatedImageViewImpl::AnimatedImageViewImpl(AnimatedImageViewImpl &&)=delete
AnimatedImageViewImpl & Dali::Ui::Integration::AnimatedImageViewImpl::operator=(const AnimatedImageViewImpl &)=delete
AnimatedImageViewImpl & Dali::Ui::Integration::AnimatedImageViewImpl::operator=(AnimatedImageViewImpl &&)=delete