Dali::Ui::Text::FitRange
Impl* Dali::Ui::Text::FitRange::mImpl
Dali::Ui::Text::FitRange::FitRange()
Creates a fit range with default values.
Dali::Ui::Text::FitRange::FitRange(float minimumFontSize, float maximumFontSize, float fontSizeStep)
Creates a fit range with given parameters.
minimumFontSize The minimum font size in pixels. maximumFontSize The maximum font size in pixels. fontSizeStep The font size step in pixels.
Dali::Ui::Text::FitRange::FitRange(const FitRange &rhs)
Creates a fit range by copying another fit range.
rhs The fit range to copy.
References DALI_ASSERT_VALID_FIT_RANGE.
Dali::Ui::Text::FitRange::FitRange(FitRange &&rhs) noexcept
Creates a fit range by moving another fit range.
rhs The fit range to move.
FitRange & Dali::Ui::Text::FitRange::operator=(const FitRange &rhs)
Copies another fit range to this object.
rhs The fit range to copy. A reference to this fit range.
References DALI_ASSERT_VALID_FIT_RANGE.
FitRange & Dali::Ui::Text::FitRange::operator=(FitRange &&rhs) noexcept
Moves another fit range to this object.
rhs The fit range to move. A reference to this fit range.
Dali::Ui::Text::FitRange::~FitRange()
Destructor.
FitRange & Dali::Ui::Text::FitRange::SetMinimumFontSize(float size)
Sets the minimum font size.
size The minimum font size in pixels. A reference to this fit range.
References DALI_ASSERT_VALID_FIT_RANGE, Dali::Ui::Text::FitRange::Impl::mMinimumFontSize.
float Dali::Ui::Text::FitRange::GetMinimumFontSize() const
Returns the minimum font size.
The minimum font size in pixels.
References DALI_ASSERT_VALID_FIT_RANGE, Dali::Ui::Text::FitRange::Impl::mMinimumFontSize.
Referenced by Dali::Ui::Integration::LabelImpl::SetTextFit.
FitRange & Dali::Ui::Text::FitRange::SetMaximumFontSize(float size)
Sets the maximum font size.
size The maximum font size in pixels. A reference to this fit range.
References DALI_ASSERT_VALID_FIT_RANGE, Dali::Ui::Text::FitRange::Impl::mMaximumFontSize.
float Dali::Ui::Text::FitRange::GetMaximumFontSize() const
Returns the maximum font size.
The maximum font size in pixels.
References DALI_ASSERT_VALID_FIT_RANGE, Dali::Ui::Text::FitRange::Impl::mMaximumFontSize.
Referenced by Dali::Ui::Integration::LabelImpl::SetTextFit.
FitRange & Dali::Ui::Text::FitRange::SetFontSizeStep(float step)
Sets the font size step.
The text fit algorithm decreases the font size by this step when searching for the largest fitting size. step The font size step in pixels. A reference to this fit range.
References DALI_ASSERT_VALID_FIT_RANGE, Dali::Ui::Text::FitRange::Impl::mFontSizeStep.
float Dali::Ui::Text::FitRange::GetFontSizeStep() const
Returns the font size step.
The font size step in pixels.
References DALI_ASSERT_VALID_FIT_RANGE, Dali::Ui::Text::FitRange::Impl::mFontSizeStep.
Referenced by Dali::Ui::Integration::LabelImpl::SetTextFit.