Dali::Ui::MaskEffect
MaskMode
Uses the alpha channel of the mask texture. (Default)
MaskEffect Dali::Ui::MaskEffect::New(Ui::View maskView)
Creates an initialized MaskEffect with view, using default settings. The default settings are:
maskMode = MaskMode::ALPHA maskPosition = Vector2(0.f, 0.f) maskScale = Vector2(1.f, 1.f) maskView The source View to affect mask. A handle to a newly allocated Dali resource
References MaskEffect.
Referenced by Dali::Ui::Integration::LabelImpl::SetMaskEffect.
MaskEffect Dali::Ui::MaskEffect::New(Ui::View maskView, MaskMode maskMode, Vector2 maskPosition, Vector2 maskScale)
Creates an initialized MaskEffect.
maskView The source View to affect mask. maskMode Defines pixel data type (alpha, luminance) used as the mask source. maskPosition The Position of mask source. maskScale The Scale of mask source. A handle to a newly allocated Dali resource
References MaskEffect.
Dali::Ui::MaskEffect::MaskEffect()
Creates an uninitialized mask effect.
Referenced by New, New.
Dali::Ui::MaskEffect::MaskEffect(const MaskEffect &handle)
Copy constructor.
Dali::Ui::MaskEffect::~MaskEffect()
Destructor.
void Dali::Ui::MaskEffect::SetTargetMaskOnce(bool targetMaskOnce)
Set whether the target should be rendered once(true) or every frame(false).
targetMaskOnce If true, renders target once, else updates every frame.
bool Dali::Ui::MaskEffect::GetTargetMaskOnce() const
Retrives whether the target should be rendered once(true) or every frame(false).
void Dali::Ui::MaskEffect::SetSourceMaskOnce(bool sourceMaskOnce)
Set whether the source should be rendered once(true) or every frame(false).
sourceMaskOnce If true, renders source once, else updates every frame.
bool Dali::Ui::MaskEffect::GetSourceMaskOnce() const
Retrives whether the source should be rendered once(true) or every frame(false).