Dali::Ui::ViewImpl
ViewBehaviour
Default behaviour: Size negotiation is enabled & listens to Style Change signal, but doesn't receive event callbacks.
using Dali::Ui::ViewImpl::ChildContainer = Dali::Vector<ChildData>
using Dali::Ui::ViewImpl::StateChangedSignalType = Signal<void(Ui::View, const StateEvent&)>
typedef Signal<void(std::pair<Dali::Accessibility::GestureInfo, bool>&)> Dali::Ui::ViewImpl::AccessibilityDoGestureSignalType
AccessibilityDoGesture signal type.
typedef Signal<bool(const Dali::Accessibility::ActionInfo&)> Dali::Ui::ViewImpl::AccessibilityActionSignalType
AccessibilityAction signal type.
const int Dali::Ui::ViewImpl::VIEW_BEHAVIOUR_FLAG_COUNT
Total count of flags.
friend class Internal::ViewDataImpl
Pimpl body.
Referenced by IsResourceReady, SetResourceReady.
Internal::ViewDataImpl* Dali::Ui::ViewImpl::mImpl
void Dali::Ui::ViewImpl::OnInitialize()
Called after the actor has been initialized.
Referenced by Initialize, Dali::Ui::Integration::InputFieldImpl::OnInitialize, Dali::Ui::Integration::InteractiveViewImpl::OnInitialize, Dali::Ui::Integration::LabelImpl::OnInitialize, Dali::Ui::Integration::AbsoluteLayoutImpl::OnInitialize, Dali::Ui::Integration::FlexLayoutImpl::OnInitialize, Dali::Ui::Integration::GridLayoutImpl::OnInitialize, Dali::Ui::Integration::StackLayoutImpl::OnInitialize, Dali::Ui::Integration::ScrollViewImpl::OnInitialize.
bool Dali::Ui::ViewImpl::OnKeyEvent(const Dali::KeyEvent &event)
Called when a key event is received.
event The key event True if the event is consumed
References Dali::Ui::View::DownCast.
bool Dali::Ui::ViewImpl::IsResourceReady() const
Query if all resources required by a View are loaded and ready.
Most resources are only loaded when the View is placed on stage. true if the resources are loaded and ready, false otherwise
References Internal::ViewDataImpl.
Referenced by Dali::Ui::View::IsResourceReady.
bool Dali::Ui::ViewImpl::IsLayout() const
Returns whether this view acts as a layout container.
True if this view has a LayoutManager attached
Referenced by Dali::Ui::Integration::AbsoluteLayoutManager::Measure, OnRelayout.
bool Dali::Ui::ViewImpl::OnAccessibilityActivated()
This method is called when the view is accessibility activated.
true if this view can perform accessibility activation
References Dali::Ui::FocusManager::Get, OnKeyboardEnter.
bool Dali::Ui::ViewImpl::OnAccessibilityPan(PanGesture gesture)
Called when accessibility pan gesture is received.
gesture The pan gesture true if the pan gesture has been consumed by this view
bool Dali::Ui::ViewImpl::OnAccessibilityValueChange(bool isIncrease)
Called for accessibility value change (e.g. slider up/down).
isIncrease Whether the value should be increased or decreased true if the value changed action has been consumed by this view
bool Dali::Ui::ViewImpl::OnAccessibilityZoom()
Called for accessibility zoom action.
true if the zoom action has been consumed by this view
ViewAccessible * Dali::Ui::ViewImpl::CreateAccessibleObject()
Creates a custom Accessible object for this view.
The AT-SPI infrastructure is responsible for destroying the returned object. The newly created Accessible object GetAccessibleObject()
Actor Dali::Ui::ViewImpl::GetNextFocusableActor(Actor currentFocusedActor, Ui::FocusDirection direction, bool loopEnabled)
Gets the next focusable actor in this view towards the given direction.
A view needs to override this function in order to support two dimensional key navigation. currentFocusedActor The current focused actor direction The direction to move the focus towards loopEnabled Whether the focus movement should be looped within the view The next focusable actor in this view or an empty handle if no actor can be focused
void Dali::Ui::ViewImpl::OnFocusChangeCommitted(Actor committedFocusableActor)
Informs this view that its chosen focusable actor will be focused.
committedFocusableActor The committed focusable actor
bool Dali::Ui::ViewImpl::OnKeyboardEnter()
Called when the view has enter pressed on it.
true if this view supported this action
Referenced by OnAccessibilityActivated.
Dali::Actor Dali::Ui::ViewImpl::GetOffScreenRenderableSourceActor()
Retrieves SourceActor of the OffScreenRenderable.
SourceActor of the OffScreenRenderable.
bool Dali::Ui::ViewImpl::IsOffScreenRenderTaskExclusive()
Retrieves whether the OffScreen RenderTasks is exclusive or not.
True if the RenderTask is exclusive.
virtual Extension * Dali::Ui::ViewImpl::GetViewExtension()
Retrieves the extension for this view.
The extension if available, NULL otherwise
void Dali::Ui::ViewImpl::Initialize()
Second phase initialization.
References DISABLE_VISUALS, OnInitialize, REQUIRES_KEY_NAVIGATION_SUPPORT, SetKeyNavigationSupport.
Referenced by Dali::Ui::Integration::UiConfigManager::Initialize.
const ViewState & Dali::Ui::ViewImpl::GetState() const
Gets the current state of this View.
The current ViewState (may contain multiple combined states)
Referenced by Dali::Ui::View::GetState.
bool Dali::Ui::ViewImpl::IsEnabled() const
Referenced by Dali::Ui::View::IsEnabled, SetState.
void Dali::Ui::ViewImpl::SetEnabled(bool enabled)
Sets whether the view is enabled.
A disabled view does not receive user interaction. Setting this to false adds the Disabled state and emits StateChangedSignal. enabled True to enable, false to disable
Referenced by Dali::Ui::View::SetEnabled.
bool Dali::Ui::ViewImpl::IsEffectivelyEnabled() const
Returns true if this view and all its View ancestors are enabled.
Unlike IsEnabled(), which only reflects the view's own state, this method walks up the scene hierarchy and returns false if any ancestor View carries ViewState::DISABLED. True if neither the view nor any ancestor is disabled
Referenced by Dali::Ui::View::IsEffectivelyEnabled.
bool Dali::Ui::ViewImpl::IsEffectivelyFocused() const
Returns true if this view or any of its View ancestors is focused.
Unlike the Focused bit in GetState(), this method walks up the scene hierarchy and returns true if any ancestor View carries ViewState::FOCUSED. True if the view itself or at least one ancestor is focused
Referenced by Dali::Ui::View::IsEffectivelyFocused.
ViewImpl::StateChangedSignalType & Dali::Ui::ViewImpl::StateChangedSignal()
Returns the state changed signal.
Emitted whenever the view's ViewState changes. view.StateChangedSignal().Connect(tracker,[](Viewv,constStateEvent&e){ if(e.Added(ViewState::FOCUSED)){...} }); The StateChangedSignal
Referenced by Dali::Ui::View::StateChangedSignal.
void Dali::Ui::ViewImpl::WhenStateChanged(const Dali::String &id, X *obj, void(X::*func)(Ui::View, const StateEvent &))
Registers a named state-change handler using a member function.
id Unique identifier for this handler obj Object whose member function will be called func Member function with signature void(View, const StateEvent&)
void Dali::Ui::ViewImpl::WhenStateChanged(const Dali::String &id, Dali::ConnectionTrackerInterface *tracker, F &&func)
Registers a named state-change handler using a callable (e.g. lambda).
id Unique identifier for this handler tracker ConnectionTrackerInterface for automatic lifetime management func Callable with signature void(View, const StateEvent&)
bool Dali::Ui::ViewImpl::UnsetStateHandler(const Dali::String &id)
Removes a named state-change handler.
id The handler identifier to remove True if a handler was found and removed
References Dali::Ui::GetImpl, GetTrait, Dali::Ui::Integration::ReservedTraitId::STATE_HANDLER_TRAIT.
bool Dali::Ui::ViewImpl::UnsetStateHandlerWhenNotProcessing(const Dali::String &id)
Removes a named state-change handler only if it is not currently being processed.
id The handler identifier to remove True if removed, false if currently processing or not found
References Dali::Ui::GetImpl, GetTrait, Dali::Ui::Integration::ReservedTraitId::STATE_HANDLER_TRAIT.
void Dali::Ui::ViewImpl::SetState(ViewState state, bool on, InputEvent cause=InputEvent::None())
Updates a state bit in the view's ViewState and emits StateChangedSignal.
state The state to set or clear on True to add the state, false to remove it cause Input event that triggered the change; leave default if programmatic
References Dali::Ui::ViewState::DISABLED, Dali::Ui::View::DownCast, Dali::Ui::ViewState::FOCUSED, Dali::Ui::ViewState::IsAnyDisabled, IsEnabled, Dali::Ui::ViewState::PRESSED.
Referenced by OnFocusChanged, OnPropertySet, Dali::Ui::Integration::InteractiveTraitImpl::SetPseudoDisabled.
void Dali::Ui::ViewImpl::NotifyFocusChanged(bool focused)
Notifies this view that its focus state has changed.
Called by focus managers. Invokes the protected virtual OnFocusChanged() and emits the FocusChanged signal. focused True if the view gained focus, false if lost
References OnFocusChanged.
float Dali::Ui::ViewImpl::GetScaleX() const
Gets the x scale factor applied to the view.
The x scale factor
Referenced by Dali::Ui::View::GetScaleX.
void Dali::Ui::ViewImpl::SetScaleX(float scaleX)
Sets the x scale factor applied to the view.
scaleX The X scale factor to set
Referenced by Dali::Ui::View::SetScaleX.
float Dali::Ui::ViewImpl::GetScaleY() const
Gets the y scale factor applied to the view.
The y scale factor
Referenced by Dali::Ui::View::GetScaleY.
void Dali::Ui::ViewImpl::SetScaleY(float scaleY)
Sets the y scale factor applied to the view.
scaleY The Y scale factor to set
Referenced by Dali::Ui::View::SetScaleY.
bool Dali::Ui::ViewImpl::IsVisible() const
Checks if the view is visible.
True if the view is visible, false otherwise
Referenced by Dali::Ui::View::IsVisible.
void Dali::Ui::ViewImpl::SetVisibility(bool visibility)
Sets the visibility of the view.
visibility True to make the view visible, false to hide it Reference to this View for fluent chaining
Referenced by Dali::Ui::View::SetVisibility.
float Dali::Ui::ViewImpl::GetOpacity() const
Gets the opacity of the view.
The opacity value (0.0 to 1.0)
Referenced by Dali::Ui::View::GetOpacity.
void Dali::Ui::ViewImpl::SetOpacity(float opacity)
Sets the opacity of the view.
opacity The opacity value to set (0.0 to 1.0) Reference to this View for fluent chaining
Referenced by Dali::Ui::View::SetOpacity.
MeasuredSize Dali::Ui::ViewImpl::GetSize() const
Gets the actual rendered size of this View after layout.
This is a read-only result of the layout system's Measure/Arrange passes. To set the desired size, use SetRequestedWidth() / SetRequestedHeight(). The actual size (width, height) as set by the layout system
Referenced by Dali::Ui::View::GetSize.
float Dali::Ui::ViewImpl::GetPositionX() const
Gets the X position of the View.
The X position of the View
Referenced by Dali::Ui::View::GetPositionX, OnMeasure.
void Dali::Ui::ViewImpl::SetPositionX(float x)
Sets the X position of the View.
x The X position to set
Referenced by Dali::Ui::View::SetPositionX.
float Dali::Ui::ViewImpl::GetPositionY() const
Gets the Y position of the View.
The Y position of the View
Referenced by Dali::Ui::View::GetPositionY, OnMeasure.
void Dali::Ui::ViewImpl::SetPositionY(float y)
Sets the Y position of the View.
y The Y position to set
Referenced by Dali::Ui::View::SetPositionY.
Vector3 Dali::Ui::ViewImpl::GetParentOrigin() const
Gets the parent origin of the View.
The parent origin of the View
Referenced by Dali::Ui::View::GetParentOrigin.
void Dali::Ui::ViewImpl::SetParentOrigin(const Vector3 &point)
Sets the parent origin of the View.
point The parent origin to set
Referenced by Dali::Ui::View::SetParentOrigin.
Vector3 Dali::Ui::ViewImpl::GetPivot() const
Gets the pivot of the View.
The pivot of the View
Referenced by Dali::Ui::View::GetPivot.
void Dali::Ui::ViewImpl::SetPivot(const Vector3 &point)
Sets the pivot of the View.
point The pivot to set
Referenced by Dali::Ui::View::SetPivot.
bool Dali::Ui::ViewImpl::IsFocusable() const
Gets whether the actor should be focusable by keyboard navigation.
True if it is focusable
Referenced by Dali::Ui::View::IsFocusable.
void Dali::Ui::ViewImpl::SetFocusable(bool focusable)
Sets whether the actor should be focusable by keyboard navigation.
focusable True if it is focusable
Referenced by Dali::Ui::View::SetFocusable.
bool Dali::Ui::ViewImpl::IsTouchFocusable() const
Gets whether the actor should be focused when touched.
True if it is focused when touched
Referenced by Dali::Ui::View::IsTouchFocusable.
void Dali::Ui::ViewImpl::SetTouchFocusable(bool touchFocusable)
Sets whether the actor should be focused when touched.
touchFocusable True if it gets focused when touched
Referenced by Dali::Ui::View::SetTouchFocusable.
UiColor Dali::Ui::ViewImpl::GetBackgroundColor()
Gets the background color.
The background color
References Dali::Ui::UiColorManager::Get.
Referenced by Dali::Ui::View::GetBackgroundColor.
void Dali::Ui::ViewImpl::SetBackgroundColor(const UiColor &color)
Sets the background color.
If the UiColor has a color ID, it is resolved from the current theme and a binding is registered so the color is automatically refreshed when the theme changes. If the UiColor has direct RGBA values, it is applied immediately and any previous ID-based binding for this property is removed. color The UiColor to apply
References SetColorBinding.
Referenced by Dali::Ui::View::SetBackgroundColor.
Vector4 Dali::Ui::ViewImpl::GetCornerRadius() const
Gets the corner radius of the view.
The corner radius as Vector4 (topLeft, topRight, bottomRight, bottomLeft)
References Dali::Ui::View::Property::CORNER_RADIUS.
Referenced by Dali::Ui::View::GetCornerRadius.
void Dali::Ui::ViewImpl::SetCornerRadius(const Vector4 &radius)
Sets a uniform corner radius for all four corners.
radius The corner radius to apply to all corners
References Dali::Ui::View::Property::CORNER_RADIUS.
Referenced by Dali::Ui::View::SetCornerRadius, Dali::Ui::View::SetCornerRadius, Dali::Ui::View::SetCornerRadius.
CornerRadiusPolicy Dali::Ui::ViewImpl::GetCornerRadiusPolicy() const
Gets the corner radius policy.
The corner radius policy
References Dali::Ui::View::Property::CORNER_RADIUS_POLICY.
Referenced by Dali::Ui::View::GetCornerRadiusPolicy, Dali::Ui::View::IsCornerRadiusPolicyRelative.
void Dali::Ui::ViewImpl::SetCornerRadiusPolicy(CornerRadiusPolicy policy)
Sets the corner radius policy.
policy ABSOLUTE for world-unit values (default), RELATIVE for percentage [0.0, 0.5] of the shorter side
References Dali::Ui::View::Property::CORNER_RADIUS_POLICY.
Referenced by Dali::Ui::View::SetCornerRadiusPolicy, Dali::Ui::View::SetCornerRadiusPolicyRelative.
Vector4 Dali::Ui::ViewImpl::GetCornerSquareness() const
Gets the corner squareness of the view.
The corner squareness as Vector4 (x=topLeft, y=topRight, z=bottomRight, w=bottomLeft)
References Dali::Ui::View::Property::CORNER_SQUARENESS.
Referenced by Dali::Ui::View::GetCornerSquareness.
void Dali::Ui::ViewImpl::SetCornerSquareness(const Vector4 &squareness)
Sets a uniform corner squareness for all four corners.
squareness The squareness value to apply to all corners
References Dali::Ui::View::Property::CORNER_SQUARENESS.
Referenced by Dali::Ui::View::SetCornerSquareness, Dali::Ui::View::SetCornerSquareness, Dali::Ui::View::SetCornerSquareness.
float Dali::Ui::ViewImpl::GetBorderlineWidth() const
Gets the borderline width of the view.
The borderline width
References Dali::Ui::View::Property::BORDERLINE_WIDTH.
Referenced by Dali::Ui::View::GetBorderlineWidth.
void Dali::Ui::ViewImpl::SetBorderlineWidth(float width)
Sets the borderline width of the view.
width The borderline width to set
References Dali::Ui::View::Property::BORDERLINE_WIDTH.
Referenced by Dali::Ui::View::SetBorderlineWidth.
UiColor Dali::Ui::ViewImpl::GetBorderlineColor()
Gets the borderline color of the view.
The borderline color
References Dali::Ui::View::Property::BORDERLINE_COLOR, Dali::Ui::UiColorManager::Get.
Referenced by Dali::Ui::View::GetBorderlineColor.
void Dali::Ui::ViewImpl::SetBorderlineColor(const UiColor &color)
Sets the borderline color of the view.
If the UiColor has a color ID, it is resolved from the current theme and a binding is registered so the color is automatically refreshed when the theme changes. color The UiColor to apply
References SetColorBinding.
Referenced by Dali::Ui::View::SetBorderlineColor.
float Dali::Ui::ViewImpl::GetBorderlineOffset() const
Gets the borderline offset of the view.
The borderline offset
References Dali::Ui::View::Property::BORDERLINE_OFFSET.
Referenced by Dali::Ui::View::GetBorderlineOffset.
void Dali::Ui::ViewImpl::SetBorderlineOffset(float offset)
Sets the borderline offset of the view.
offset The borderline offset to set
References Dali::Ui::View::Property::BORDERLINE_OFFSET.
Referenced by Dali::Ui::View::SetBorderlineOffset.
Dali::String Dali::Ui::ViewImpl::GetName() const
Gets the name of the view.
The name
Referenced by Dali::Ui::View::GetName.
void Dali::Ui::ViewImpl::SetName(const Dali::String &name)
Sets the name of this view.
name The name to set
Referenced by Dali::Ui::View::SetName.
void Dali::Ui::ViewImpl::SetBackground(const Property::Map &map)
Sets the background with a property map.
map The background property map
References Dali::Ui::View::Property::BACKGROUND.
void Dali::Ui::ViewImpl::ClearBackground()
Clears the background.
References Dali::Ui::View::Property::BACKGROUND, Dali::Ui::UiColorManager::ClearBinding, Dali::Ui::UiColorManager::Get.
Referenced by Dali::Ui::View::ClearBackground.
void Dali::Ui::ViewImpl::SetRenderEffect(Ui::RenderEffect effect)
Sets RenderEffect to this View.
effect RenderEffect to add. Every effect inherits RenderEffect.
References ClearRenderEffect.
Referenced by Dali::Ui::View::SetRenderEffect.
RenderEffect Dali::Ui::ViewImpl::GetRenderEffect() const
Retrieves View's render effect.
RenderEffect set on this View
Referenced by Dali::Ui::View::GetRenderEffect.
void Dali::Ui::ViewImpl::ClearRenderEffect()
Clears RenderEffect of this View, if exists.
Referenced by Dali::Ui::View::ClearRenderEffect, SetRenderEffect, ~ViewImpl.
void Dali::Ui::ViewImpl::SetTrait(TraitId id, Trait &trait)
Referenced by EnsureInteractiveTrait, EnsureSelectableTrait, SetInteractionEffect, Dali::Ui::Integration::LayoutImpl::SetLayoutManager, SetLayoutParams.
Trait Dali::Ui::ViewImpl::GetTrait(TraitId id) const
Referenced by EnsureInteractiveTrait, EnsureSelectableTrait, GetLayoutParams, IsInteractive, IsSelectable, UnsetStateHandler, UnsetStateHandlerWhenNotProcessing.
bool Dali::Ui::ViewImpl::RemoveTrait(TraitId id)
Referenced by Dali::Ui::Integration::ExclusiveTraitImpl::OnBeforeAttached, SetInteractionEffect.
Ui::InteractiveTrait Dali::Ui::ViewImpl::EnsureInteractiveTrait()
Ensures this View has an interaction trait and returns it.
If no interaction trait is set, an InteractiveTrait is attached and returned. If an InteractiveTrait is already attached, it is returned. If a different interaction trait is set, an assertion may fire and an empty handle is returned. InteractiveTrait handle, or an uninitialized handle on error
References Dali::Ui::InteractiveTrait::DownCast, Dali::Ui::Integration::UiConfigManager::Get, Dali::Ui::Integration::UiConfigManager::GetConfig, Dali::Ui::UiConfig::GetDefaultInteractionEffect, GetTrait, Dali::Ui::Integration::ReservedTraitId::INTERACTION_EFFECT, Dali::Ui::Integration::ReservedTraitId::INTERACTION_TRAIT, Dali::Ui::InteractiveTrait::New, SetTrait.
Referenced by Dali::Ui::View::EnsureInteractiveTrait, Dali::Ui::Integration::InteractiveViewImpl::OnInitialize.
bool Dali::Ui::ViewImpl::IsInteractive() const
Returns whether this View has an interaction trait attached.
True if this View has an InteractiveTrait
References GetTrait, Dali::Ui::Integration::ReservedTraitId::INTERACTION_TRAIT.
Referenced by Dali::Ui::View::IsInteractive.
Ui::SelectableTrait Dali::Ui::ViewImpl::EnsureSelectableTrait()
Ensures this View has a selectable trait and returns it.
If no selectable trait is set, a SelectableTrait is attached and returned. If a SelectableTrait is already attached, it is returned. If a different selectable trait type is set, an assertion may fire and an empty handle is returned. SelectableTrait handle, or an uninitialized handle on error
References Dali::Ui::SelectableTrait::DownCast, GetTrait, Dali::Ui::SelectableTrait::New, Dali::Ui::Integration::ReservedTraitId::SELECTABLE_TRAIT, SetTrait.
Referenced by Dali::Ui::View::EnsureSelectableTrait.
bool Dali::Ui::ViewImpl::IsSelectable() const
Returns whether this View has a selectable trait attached.
True if this View has a SelectableTrait
References GetTrait, Dali::Ui::Integration::ReservedTraitId::SELECTABLE_TRAIT.
Referenced by Dali::Ui::View::IsSelectable.
void Dali::Ui::ViewImpl::SetInteractionEffect(Trait effect)
Sets an interaction effect on this view.
The effect is applied when the view becomes interactive (via AsInteractive()). If the view is already interactive, the effect is applied immediately. The effect is frozen at set time — subsequent modifications to the original handle do not affect this view. Pass Trait{} to remove the current effect. If this method is called before AsInteractive(), the explicitly set effect takes priority over the UiConfig default. effect A Trait implementing InteractionEffectInterface, or Trait{} to remove Reference to this View for method chaining
References Dali::Ui::Integration::ReservedTraitId::INTERACTION_EFFECT, RemoveTrait, SetTrait.
Referenced by Dali::Ui::View::SetInteractionEffect.
MeasuredSize Dali::Ui::ViewImpl::Measure(float widthConstraint, float heightConstraint)
Measures the view with the given constraints.
This method implements caching to avoid redundant calculations. It calls OnMeasure internally (Template Method pattern). widthConstraint The width constraint for measurement heightConstraint The height constraint for measurement The measured size
References OnMeasure.
Referenced by Dali::Ui::Integration::AbsoluteLayoutManager::ArrangeChildren, Dali::Ui::Integration::ScrollViewLayoutManager::ArrangeChildren, Dali::Ui::Integration::StackLayoutManager::ArrangeChildren, Dali::Ui::View::Measure, Dali::Ui::Integration::AbsoluteLayoutManager::Measure, Dali::Ui::Integration::FlexLayoutManager::Measure, Dali::Ui::Integration::ScrollViewLayoutManager::Measure, Dali::Ui::Integration::StackLayoutManager::Measure, Dali::Ui::LayoutManager::MeasureChild, OnArrange, OnMeasure.
MeasuredSize Dali::Ui::ViewImpl::Arrange(const LayoutRect &bounds)
Arranges the view within the given bounds.
This method calls OnArrange internally (Template Method pattern). bounds The bounds to arrange the view in The final arranged size
References OnArrange.
Referenced by Dali::Ui::View::Arrange, Dali::Ui::LayoutManager::ArrangeChild, Dali::Ui::Integration::AbsoluteLayoutManager::ArrangeChildren, Dali::Ui::Integration::ScrollViewLayoutManager::ArrangeChildren, Dali::Ui::Integration::StackLayoutManager::ArrangeChildren, OnArrange.
void Dali::Ui::ViewImpl::InvalidateMeasure()
Invalidates the measure of this view.
This propagates to the parent layout while one exists, until the layout root is reached (no parent Layout).
References Dali::Ui::GetImpl, GetParentLayout, GetParentView, InvalidateMeasure.
Referenced by Dali::Ui::Integration::GridLayoutImpl::AddColumnDefinition, Dali::Ui::Integration::GridLayoutImpl::AddRowDefinition, Dali::Ui::Integration::GridLayoutImpl::ClearColumnDefinitions, Dali::Ui::Integration::GridLayoutImpl::ClearRowDefinitions, Insert, InvalidateMeasure, Dali::Ui::View::InvalidateMeasure, Dali::Ui::Integration::InputFieldImpl::InvalidateTextMeasure, Dali::Ui::Integration::LabelImpl::InvalidateTextMeasure, OnChildAdd, OnChildRemove, RemoveAllChildren, Dali::Ui::Integration::AnimatedImageViewImpl::SetAlphaMaskUrl, Dali::Ui::Integration::ImageViewImpl::SetAlphaMaskUrl, Dali::Ui::Integration::AnimatedImageViewImpl::SetBatchSize, Dali::Ui::Integration::AnimatedImageViewImpl::SetCacheSize, Dali::Ui::Integration::GridLayoutImpl::SetColumnDefinitions, Dali::Ui::Integration::GridLayoutImpl::SetColumnSpacing, Dali::Ui::Integration::AnimatedImageViewImpl::SetCropToMask, Dali::Ui::Integration::ImageViewImpl::SetCropToMask, Dali::Ui::Integration::AnimatedImageViewImpl::SetDesiredHeight, Dali::Ui::Integration::ImageViewImpl::SetDesiredHeight, Dali::Ui::Integration::LottieAnimationViewImpl::SetDesiredHeight, Dali::Ui::Integration::AnimatedImageViewImpl::SetDesiredWidth, Dali::Ui::Integration::ImageViewImpl::SetDesiredWidth, Dali::Ui::Integration::LottieAnimationViewImpl::SetDesiredWidth, Dali::Ui::Integration::FlexLayoutImpl::SetDirection, Dali::Ui::Integration::LottieAnimationViewImpl::SetEnableFrameCache, Dali::Ui::Integration::ImageViewImpl::SetFastTrackUpload, Dali::Ui::Integration::AnimatedImageViewImpl::SetFittingMode, Dali::Ui::Integration::ImageViewImpl::SetFittingMode, Dali::Ui::Integration::AnimatedImageViewImpl::SetFrameDelay, Dali::Ui::Integration::AnimatedImageViewImpl::SetFrameSpeedFactor, Dali::Ui::Integration::LottieAnimationViewImpl::SetFrameSpeedFactor, Dali::Ui::Integration::AnimatedImageViewImpl::SetImageColor, Dali::Ui::Integration::ImageViewImpl::SetImageColor, Dali::Ui::Integration::LottieAnimationViewImpl::SetImageColor, Dali::Ui::Integration::AnimatedImageViewImpl::SetImageLoadWithViewSize, Dali::Ui::Integration::ImageViewImpl::SetImageLoadWithViewSize, SetLayoutParams, Dali::Ui::Integration::AnimatedImageViewImpl::SetLoadPolicy, Dali::Ui::Integration::ImageViewImpl::SetLoadPolicy, Dali::Ui::Integration::AnimatedImageViewImpl::SetLoopCount, Dali::Ui::Integration::LottieAnimationViewImpl::SetLoopCount, Dali::Ui::Integration::LottieAnimationViewImpl::SetLoopingMode, Dali::Ui::Integration::AnimatedImageViewImpl::SetMaskingMode, Dali::Ui::Integration::ImageViewImpl::SetMaskingMode, Dali::Ui::Integration::LottieAnimationViewImpl::SetMinMaxFrame, Dali::Ui::Integration::LottieAnimationViewImpl::SetMinMaxFrameByMarker, Dali::Ui::Integration::LottieAnimationViewImpl::SetNotifyAfterRasterization, Dali::Ui::Integration::ImageViewImpl::SetNPatchBorder, Dali::Ui::Integration::ImageViewImpl::SetNPatchBorderOnly, Dali::Ui::Integration::StackLayoutImpl::SetOrientation, Dali::Ui::Integration::ImageViewImpl::SetOrientationCorrection, Dali::Ui::Integration::AnimatedImageViewImpl::SetPreMultipliedAlpha, Dali::Ui::Integration::ImageViewImpl::SetPreMultipliedAlpha, Dali::Ui::Integration::LottieAnimationViewImpl::SetPreMultipliedAlpha, Dali::Ui::Integration::LottieAnimationViewImpl::SetRedrawOnScaleDown, Dali::Ui::Integration::LottieAnimationViewImpl::SetRedrawOnScaleUp, Dali::Ui::Integration::AnimatedImageViewImpl::SetReleasePolicy, Dali::Ui::Integration::ImageViewImpl::SetReleasePolicy, Dali::Ui::Integration::LottieAnimationViewImpl::SetReleasePolicy, Dali::Ui::Integration::LottieAnimationViewImpl::SetRenderScale, Dali::Ui::Integration::AnimatedImageViewImpl::SetResourceUrl, Dali::Ui::Integration::ImageViewImpl::SetResourceUrl, Dali::Ui::Integration::LottieAnimationViewImpl::SetResourceUrl, Dali::Ui::Integration::AnimatedImageViewImpl::SetResourceUrls, Dali::Ui::Integration::GridLayoutImpl::SetRowDefinitions, Dali::Ui::Integration::GridLayoutImpl::SetRowSpacing, Dali::Ui::Integration::AnimatedImageViewImpl::SetSamplingMode, Dali::Ui::Integration::ImageViewImpl::SetSamplingMode, Dali::Ui::Integration::StackLayoutImpl::SetSpacing, Dali::Ui::Integration::AnimatedImageViewImpl::SetStopBehavior, Dali::Ui::Integration::LottieAnimationViewImpl::SetStopBehavior, Dali::Ui::Integration::AnimatedImageViewImpl::SetSynchronousLoading, Dali::Ui::Integration::ImageViewImpl::SetSynchronousLoading, Dali::Ui::Integration::LottieAnimationViewImpl::SetSynchronousLoading, Dali::Ui::Integration::FlexLayoutImpl::SetWrap.
void Dali::Ui::ViewImpl::InvalidateArrange()
Invalidates the arrange of this view.
References Dali::Ui::GetImpl, GetParentLayout, GetParentView, InvalidateArrange.
Referenced by InvalidateArrange, Dali::Ui::View::InvalidateArrange, Dali::Ui::Integration::FlexLayoutImpl::SetAlignContent, Dali::Ui::Integration::FlexLayoutImpl::SetAlignItems, Dali::Ui::Integration::FlexLayoutImpl::SetJustifyContent.
MeasuredSize Dali::Ui::ViewImpl::GetMeasuredSize() const
Gets the measured size from the last Measure() pass.
The measured size
Referenced by Dali::Ui::View::GetMeasuredSize.
void Dali::Ui::ViewImpl::SetRequestedWidth(float width)
Sets the requested width.
A positive value sets a fixed width. WRAP_CONTENT (-1): sizes to content (default). MATCH_PARENT (-2): fills the parent container. width The requested width
References Dali::Ui::View::Property::REQUESTED_WIDTH.
Referenced by Dali::Ui::View::SetRequestedWidth.
float Dali::Ui::ViewImpl::GetRequestedWidth() const
Gets the requested width.
The requested width
Referenced by Dali::Ui::Integration::AbsoluteLayoutManager::ArrangeChildren, Dali::Ui::Integration::ScrollViewLayoutManager::ArrangeChildren, Dali::Ui::Integration::StackLayoutManager::ArrangeChildren, Dali::Ui::View::GetRequestedWidth, Dali::Ui::Integration::InputFieldImpl::InvalidateTextMeasure, Dali::Ui::Integration::LabelImpl::InvalidateTextMeasure, Dali::Ui::Integration::GridLayoutManager::Measure, Dali::Ui::Integration::ScrollViewLayoutManager::Measure, Dali::Ui::Integration::StackLayoutManager::Measure, OnArrange, Dali::Ui::Integration::InputFieldImpl::OnMeasure, Dali::Ui::Integration::LabelImpl::OnMeasure, Dali::Ui::Integration::LayoutImpl::OnMeasure.
void Dali::Ui::ViewImpl::SetRequestedHeight(float height)
Sets the requested height.
A positive value sets a fixed height. WRAP_CONTENT (-1): sizes to content (default). MATCH_PARENT (-2): fills the parent container. height The requested height
References Dali::Ui::View::Property::REQUESTED_HEIGHT.
Referenced by Dali::Ui::View::SetRequestedHeight.
float Dali::Ui::ViewImpl::GetRequestedHeight() const
Gets the requested height.
The requested height
Referenced by Dali::Ui::Integration::AbsoluteLayoutManager::ArrangeChildren, Dali::Ui::Integration::ScrollViewLayoutManager::ArrangeChildren, Dali::Ui::Integration::StackLayoutManager::ArrangeChildren, Dali::Ui::View::GetRequestedHeight, Dali::Ui::Integration::InputFieldImpl::InvalidateTextMeasure, Dali::Ui::Integration::LabelImpl::InvalidateTextMeasure, Dali::Ui::Integration::GridLayoutManager::Measure, Dali::Ui::Integration::ScrollViewLayoutManager::Measure, Dali::Ui::Integration::StackLayoutManager::Measure, OnArrange, Dali::Ui::Integration::InputFieldImpl::OnMeasure, Dali::Ui::Integration::LabelImpl::OnMeasure, Dali::Ui::Integration::LayoutImpl::OnMeasure.
void Dali::Ui::ViewImpl::SetMinimumWidth(float width)
Sets the minimum width.
width The minimum width
References Dali::Ui::View::Property::MINIMUM_WIDTH.
Referenced by Dali::Ui::View::SetMinimumWidth.
float Dali::Ui::ViewImpl::GetMinimumWidth() const
Gets the minimum width.
The minimum width
Referenced by Dali::Ui::Integration::LabelImpl::GetLineCount, Dali::Ui::View::GetMinimumWidth, Dali::Ui::Integration::GridLayoutManager::Measure, Dali::Ui::Integration::StackLayoutManager::Measure, Dali::Ui::Integration::InputFieldImpl::OnMeasure, Dali::Ui::Integration::LabelImpl::OnMeasure, Dali::Ui::Integration::LayoutImpl::OnMeasure.
void Dali::Ui::ViewImpl::SetMinimumHeight(float height)
Sets the minimum height.
height The minimum height
References Dali::Ui::View::Property::MINIMUM_HEIGHT.
Referenced by Dali::Ui::View::SetMinimumHeight.
float Dali::Ui::ViewImpl::GetMinimumHeight() const
Gets the minimum height.
The minimum height
Referenced by Dali::Ui::View::GetMinimumHeight, Dali::Ui::Integration::GridLayoutManager::Measure, Dali::Ui::Integration::StackLayoutManager::Measure, Dali::Ui::Integration::InputFieldImpl::OnMeasure, Dali::Ui::Integration::LabelImpl::OnMeasure, Dali::Ui::Integration::LayoutImpl::OnMeasure.
void Dali::Ui::ViewImpl::SetMaximumWidth(float width)
Sets the maximum width.
width The maximum width
References Dali::Ui::View::Property::MAXIMUM_WIDTH.
Referenced by Dali::Ui::View::SetMaximumWidth.
float Dali::Ui::ViewImpl::GetMaximumWidth() const
Gets the maximum width.
The maximum width
Referenced by Dali::Ui::Integration::LabelImpl::GetLineCount, Dali::Ui::View::GetMaximumWidth, Dali::Ui::Integration::InputFieldImpl::OnMeasure, Dali::Ui::Integration::LabelImpl::OnMeasure.
void Dali::Ui::ViewImpl::SetMaximumHeight(float height)
Sets the maximum height.
height The maximum height
References Dali::Ui::View::Property::MAXIMUM_HEIGHT.
Referenced by Dali::Ui::View::SetMaximumHeight.
float Dali::Ui::ViewImpl::GetMaximumHeight() const
Gets the maximum height.
The maximum height
Referenced by Dali::Ui::View::GetMaximumHeight, Dali::Ui::Integration::InputFieldImpl::OnMeasure, Dali::Ui::Integration::LabelImpl::OnMeasure.
void Dali::Ui::ViewImpl::SetLayoutParams(Ui::LayoutParams params)
Sets layout parameters on this View.
The params handle is stored on the View as-is, and the View's measure cache is invalidated. params The layout parameters to attach to this View Reference to this View for fluent chaining child.SetLayoutParams( AbsoluteLayoutParams::New() .SetBounds(LayoutRect(10,20,100,200)) .SetFlags(AbsoluteLayoutFlags::POSITION_PROPORTIONAL));
References Dali::Ui::GetImpl, InvalidateMeasure, SetTrait.
Referenced by Dali::Ui::View::SetLayoutParams.
BaseHandle Dali::Ui::ViewImpl::GetLayoutParams(LayoutParamsType type) const
Retrieves a layout params trait by LayoutParamsType.
type The layout params type The layout params handle
References GetTrait.
void Dali::Ui::ViewImpl::SetMargin(const Extents &margin)
Sets the view margin.
margin The margin to set
References Dali::Ui::View::Property::MARGIN.
Referenced by Dali::Ui::View::SetMargin.
Extents Dali::Ui::ViewImpl::GetMargin() const
Gets the view margin.
The view margin
Referenced by Dali::Ui::Integration::AbsoluteLayoutManager::ArrangeChildren, Dali::Ui::Integration::StackLayoutManager::ArrangeChildren, Dali::Ui::View::GetMargin, Dali::Ui::Integration::AbsoluteLayoutManager::Measure, Dali::Ui::Integration::FlexLayoutManager::Measure, Dali::Ui::Integration::StackLayoutManager::Measure, OnArrange, OnMeasure.
void Dali::Ui::ViewImpl::SetPadding(const Extents &padding)
Sets the view padding.
padding The padding to set
References Dali::Ui::View::Property::PADDING.
Referenced by Dali::Ui::View::SetPadding.
Extents Dali::Ui::ViewImpl::GetPadding() const
Gets the view padding.
The view padding
Referenced by Dali::Ui::Integration::LabelImpl::AsyncRenderFinished, Dali::Ui::Integration::LabelImpl::AsyncSizeComputed, Dali::Ui::Integration::ScrollViewImpl::ContentPositionToScrollPosition, Dali::Ui::Integration::InputFieldImpl::GetHeightForWidth, Dali::Ui::Integration::LabelImpl::GetHeightForWidth, Dali::Ui::Integration::LabelImpl::GetLineCount, Dali::Ui::Integration::InputFieldImpl::GetNaturalSize, Dali::Ui::Integration::LabelImpl::GetNaturalSize, Dali::Ui::View::GetPadding, Dali::Ui::Integration::GridLayoutManager::Measure, Dali::Ui::Integration::StackLayoutManager::Measure, Dali::Ui::Integration::LayoutImpl::OnArrange, Dali::Ui::Integration::InputFieldImpl::OnMeasure, Dali::Ui::Integration::LayoutImpl::OnMeasure, Dali::Ui::Integration::InputFieldImpl::OnRelayout, Dali::Ui::Integration::LabelImpl::OnRelayout, Dali::Ui::Integration::LabelImpl::RequestAsyncHeightForWidth, Dali::Ui::Integration::LabelImpl::RequestAsyncNaturalSize, Dali::Ui::Integration::LabelImpl::RequestAsyncRenderWithConstraints, Dali::Ui::Integration::LabelImpl::RequestAsyncRenderWithFixedHeight, Dali::Ui::Integration::LabelImpl::RequestAsyncRenderWithFixedSize, Dali::Ui::Integration::LabelImpl::RequestAsyncRenderWithFixedWidth.
void Dali::Ui::ViewImpl::SetLayoutMode(Ui::LayoutMode mode)
Sets the layout mode of this View.
LayoutMode::DEFAULT (default) lets the parent container's layout system manage this View's size and position normally. LayoutMode::STANDALONE excludes this View from the parent's accumulation, spacing and index calculations. The View's size is still measured normally (so MATCH_PARENT, WRAP_CONTENT and explicit RequestedWidth/Height all work), but its position is taken from SetPositionX/SetPositionY instead of being decided by the parent layout. This is useful for floating overlays, drag previews, tooltips and absolute positioning inside any LayoutManager. Standalone children ignore the parent's padding entirely. Their measured size is the parent's full inner size minus the child's own margin, and their final position is SetPositionX/SetPositionY plus the child's own margin in the parent's coordinate space. This keeps size and position consistent: a Standalone child with MATCH_PARENT fills the parent edge to edge regardless of parent padding, and any margin set on the child shifts it inward in both axes. mode The layout mode to set
References Dali::Ui::View::Property::LAYOUT_MODE.
Referenced by Dali::Ui::View::SetLayoutMode.
Ui::LayoutMode Dali::Ui::ViewImpl::GetLayoutMode() const
Gets the layout mode of this View.
The layout mode
Referenced by Dali::Ui::View::GetLayoutMode.
bool Dali::Ui::ViewImpl::IsLayoutModeStandalone() const
Convenience: returns true if LayoutMode is Standalone.
True if the view's layout mode is Standalone
References Dali::Ui::STANDALONE.
Referenced by Dali::Ui::Integration::AbsoluteLayoutManager::ArrangeChildren, Dali::Ui::Integration::StackLayoutManager::ArrangeChildren, Dali::Ui::Integration::AbsoluteLayoutManager::Measure, Dali::Ui::Integration::FlexLayoutManager::Measure, Dali::Ui::Integration::StackLayoutManager::Measure, OnArrange, OnMeasure.
Ui::Layout Dali::Ui::ViewImpl::GetParentLayout() const
Gets the parent layout of this view, if any.
The parent Layout handle, or empty if none
References Dali::Ui::Layout::DownCast.
Referenced by InvalidateArrange, InvalidateMeasure, OnRelayout.
Ui::View Dali::Ui::ViewImpl::GetParentView() const
Gets the parent view in the layout hierarchy.
The parent View handle, or empty if none
References Dali::Ui::View::DownCast.
Referenced by InvalidateArrange, InvalidateMeasure, OnRelayout, OnSceneConnection.
void Dali::Ui::ViewImpl::SetMeasureCallback(MeasureCallback callback)
Sets a custom measure callback for this View.
When set, the callback replaces the default measurement behavior during the layout pass. Pass a default-constructed callback to remove. callback The measure callback (ownership transferred) //Memberfunction view.SetMeasureCallback(MeasureCallback::New(this,&MyClass::OnMeasure)); //Staticfunction view.SetMeasureCallback(MeasureCallback::New(&MyMeasure)); //Removecallback view.SetMeasureCallback({});
Referenced by Dali::Ui::View::SetMeasureCallback.
void Dali::Ui::ViewImpl::SetArrangeCallback(ArrangeCallback callback)
Sets a custom arrange callback for this View.
When set, the callback replaces the default arrangement behavior during the layout pass. Pass a default-constructed callback to remove. callback The arrange callback (ownership transferred) //Memberfunction view.SetArrangeCallback(ArrangeCallback::New(this,&MyClass::OnArrange)); //Staticfunction view.SetArrangeCallback(ArrangeCallback::New(&MyArrange)); //Removecallback view.SetArrangeCallback({});
Referenced by Dali::Ui::View::SetArrangeCallback.
void Dali::Ui::ViewImpl::Insert(uint32_t index, Ui::View child)
Inserts a child at the specified index.
index The index where to insert child The child to insert
References InvalidateMeasure.
Referenced by Dali::Ui::View::Insert.
void Dali::Ui::ViewImpl::RemoveAllChildren()
Removes all children from this View.
References Dali::Ui::GetImpl, InvalidateMeasure.
Referenced by Dali::Ui::View::RemoveAllChildren.
uint32_t Dali::Ui::ViewImpl::GetChildCount() const
Gets the number of child views.
The child count
Referenced by Dali::Ui::View::GetChildCount, OnRelayout.
Ui::View Dali::Ui::ViewImpl::GetChildAt(uint32_t index) const
Gets the child view at the specified index.
index The child index The child view at the index
Referenced by Dali::Ui::View::GetChildAt.
int32_t Dali::Ui::ViewImpl::IndexOfChild(Ui::View view) const
Returns the index of the given child view, or -1 if not found.
view The child view to find Index of the view, or -1 if not a child
Referenced by Dali::Ui::View::IndexOfChild.
void Dali::Ui::ViewImpl::Raise(Ui::LayoutOrderPolicy policy)
Raises this view one step above its immediate next sibling in the parent's children list.
policy UPDATE also reorders the parent layout's children; PRESERVE keeps layout order unchanged and affects only visual z-order. The View has been parented.
References Dali::Ui::View::DownCast, Dali::Ui::GetImpl, Dali::Ui::PRESERVE.
Referenced by Dali::Ui::View::Raise.
void Dali::Ui::ViewImpl::Lower(Ui::LayoutOrderPolicy policy)
Lowers this view one step below its immediate previous sibling in the parent's children list.
policy UPDATE also reorders the parent layout's children; PRESERVE keeps layout order unchanged and affects only visual z-order. The View has been parented.
References Dali::Ui::View::DownCast, Dali::Ui::GetImpl, Dali::Ui::PRESERVE.
Referenced by Dali::Ui::View::Lower.
void Dali::Ui::ViewImpl::RaiseToTop(Ui::LayoutOrderPolicy policy)
Raises this view to the top of its sibling list.
policy UPDATE also reorders the parent layout's children; PRESERVE keeps layout order unchanged and affects only visual z-order. The View has been parented.
References Dali::Ui::View::DownCast, Dali::Ui::GetImpl, Dali::Ui::PRESERVE.
Referenced by Dali::Ui::View::RaiseToTop.
void Dali::Ui::ViewImpl::LowerToBottom(Ui::LayoutOrderPolicy policy)
Lowers this view to the bottom of its sibling list.
policy UPDATE also reorders the parent layout's children; PRESERVE keeps layout order unchanged and affects only visual z-order. The View has been parented.
References Dali::Ui::View::DownCast, Dali::Ui::GetImpl, Dali::Ui::PRESERVE.
Referenced by Dali::Ui::View::LowerToBottom.
void Dali::Ui::ViewImpl::RaiseAbove(Ui::View target, Ui::LayoutOrderPolicy policy)
Raises this view above the given target sibling.
target The target sibling view to raise above. policy UPDATE also reorders the parent layout's children; PRESERVE keeps layout order unchanged and affects only visual z-order. The View has been parented. The target view is a sibling.
References Dali::Ui::View::DownCast, Dali::Ui::GetImpl, Dali::Ui::PRESERVE.
Referenced by Dali::Ui::View::RaiseAbove.
void Dali::Ui::ViewImpl::LowerBelow(Ui::View target, Ui::LayoutOrderPolicy policy)
Lowers this view below the given target sibling.
target The target sibling view to lower below. policy UPDATE also reorders the parent layout's children; PRESERVE keeps layout order unchanged and affects only visual z-order. The View has been parented. The target view is a sibling.
References Dali::Ui::View::DownCast, Dali::Ui::GetImpl, Dali::Ui::PRESERVE.
Referenced by Dali::Ui::View::LowerBelow.
ViewImpl::ChildContainer & Dali::Ui::ViewImpl::GetChildren()
Gets the children container for layout manager access.
Reference to the children container
Referenced by Dali::Ui::LayoutManager::GetChildren.
const ViewImpl::ChildContainer & Dali::Ui::ViewImpl::GetChildren() const
Gets the children container for layout manager access.
Reference to the children container
std::shared_ptr< Ui::ViewAccessible > Dali::Ui::ViewImpl::GetAccessibleObject()
Gets the Accessible object that represents this view.
The Accessible object CreateAccessibleObject()
Referenced by OnRelayout.
Dali::Vector< Accessibility::Relation > Dali::Ui::ViewImpl::GetAccessibilityRelations()
Gets the accessibility relations of this view.
The list of accessibility relations
Referenced by Dali::Ui::ViewAccessible::GetRelationSet.
void Dali::Ui::ViewImpl::SetKeyNavigationSupport(bool isSupported)
Sets whether this view supports two dimensional key navigation.
isSupported True to support key navigation
References Dali::Ui::View::Property::KEY_NAVIGATION_SUPPORT.
Referenced by Initialize.
bool Dali::Ui::ViewImpl::IsKeyNavigationSupported()
Gets whether this view supports two dimensional key navigation.
True if key navigation is supported
void Dali::Ui::ViewImpl::SetKeyInputFocus()
Sets this view to receive key input focus.
References Dali::Ui::View::DownCast.
Referenced by Dali::Ui::Integration::InputFieldImpl::PasteText, Dali::Ui::Integration::InputFieldImpl::SelectText, Dali::Ui::Integration::InputFieldImpl::SelectWholeText, Dali::Ui::Integration::InputFieldImpl::SetCursorPosition, Dali::Ui::Integration::InputFieldImpl::SetTextSelectionRange.
bool Dali::Ui::ViewImpl::HasKeyInputFocus()
Checks whether this view has key input focus.
True if the view has key input focus
Referenced by Dali::Ui::Integration::InputFieldImpl::SetCursorPosition.
void Dali::Ui::ViewImpl::ClearKeyInputFocus()
Clears key input focus from this view.
References Dali::Ui::View::DownCast.
void Dali::Ui::ViewImpl::SetAsFocusGroup(bool isFocusGroup)
Sets whether this view acts as a focus group boundary.
isFocusGroup True to set as focus group
References Dali::Ui::View::Property::FOCUS_GROUP.
Referenced by Dali::Ui::FocusManager::SetAsFocusGroup.
bool Dali::Ui::ViewImpl::IsFocusGroup()
Gets whether this view acts as a focus group boundary.
True if the view is a focus group
References Dali::Ui::FocusManager::Get, Dali::Ui::FocusManager::IsFocusGroup.
Referenced by Dali::Ui::FocusManager::IsFocusGroup.
Ui::View::KeyEventSignalType & Dali::Ui::ViewImpl::KeyEventSignal()
This signal is emitted when key event is received.
A callback of the following type may be connected: boolYourCallbackName(Viewview,constKeyEvent&event); The return value of True, indicates that the event should be consumed. Otherwise the signal will be emitted on the next parent of the actor. The signal to connect to The View has been initialized.
Referenced by Dali::Ui::View::KeyEventSignal.
Ui::View::FocusChangedSignalType & Dali::Ui::ViewImpl::FocusChangedSignal()
This signal is emitted when the view gets or loses focus.
A callback of the following type may be connected: boolYourCallbackName(Viewview,boolfocused); The signal to connect to The View has been initialized.
Referenced by Dali::Ui::FocusManager::FocusChangedSignal, Dali::Ui::View::FocusChangedSignal.
bool Dali::Ui::ViewImpl::IsOnScene() const
Checks whether the view is connected to the scene.
true if the view is on scene, false otherwise
Referenced by Dali::Ui::View::IsOnScene.
Internal::ViewDataImpl & Dali::Ui::ViewImpl::GetViewDataImpl() const
Retrieves the internal data implementation of the view.
Reference to the internal data implementation
ViewImplPtr Dali::Ui::ViewImpl::New()
Creates a new View.
References ViewImpl.
Referenced by Dali::Ui::View::New, Dali::Ui::StackLayout::New.
Dali::Ui::ViewImpl::~ViewImpl()
Destructor. A reference counted object may only be deleted by calling Unreference().
References ClearRenderEffect, Dali::Ui::UiColorManager::Get, Dali::Ui::GetImpl, Dali::Ui::LayoutController::UnregisterFromAll.
MeasuredSize Dali::Ui::ViewImpl::OnMeasure(float widthConstraint, float heightConstraint)
Called during measure pass. Override to implement custom measurement.
References Dali::Ui::GetImpl, GetMargin, GetPositionX, GetPositionY, Dali::Ui::MeasuredSize::height, IsLayoutModeStandalone, Dali::Ui::MATCH_PARENT, Measure, Dali::Ui::MeasuredSize::width.
Referenced by Measure, Dali::Ui::Integration::LayoutImpl::OnMeasure.
MeasuredSize Dali::Ui::ViewImpl::OnArrange(const LayoutRect &bounds)
Called during arrange pass. Override to implement custom arrangement.
References Arrange, Dali::Ui::GetImpl, GetMargin, GetRequestedHeight, GetRequestedWidth, Dali::Ui::LayoutRect::height, IsLayoutModeStandalone, Dali::Ui::MATCH_PARENT, Measure, Dali::Ui::LayoutRect::width, Dali::Ui::LayoutRect::x, Dali::Ui::LayoutRect::y.
Referenced by Arrange, Dali::Ui::Integration::LayoutImpl::OnArrange.
void Dali::Ui::ViewImpl::OnFocusChanged(bool focused)
Called when the view's focus state changes. Override to add custom focus handling. Call the base class at the end of the override to preserve default state management.
focused True if the view gained focus, false if lost
References Dali::Ui::View::DownCast, Dali::Ui::ViewState::FOCUSED, Dali::Ui::FocusManager::Get, Dali::Ui::GetImpl, SetState.
Referenced by NotifyFocusChanged.
void Dali::Ui::ViewImpl::OnSceneConnection(int depth) override
References GetParentView.
void Dali::Ui::ViewImpl::OnSceneDisconnection() override
void Dali::Ui::ViewImpl::OnRelayout(const Vector2 &size, RelayoutContainer &container) override
References GetAccessibleObject, GetChildCount, GetParentLayout, GetParentView, IsLayout.
void Dali::Ui::ViewImpl::OnChildAdd(Actor &child) override
References Dali::Ui::ViewImpl::ChildData::arrangedBounds, Dali::Ui::View::DownCast, Dali::Ui::GetImpl, InvalidateMeasure, Dali::Ui::ViewImpl::ChildData::measuredSize, Dali::Ui::ViewImpl::ChildData::view.
void Dali::Ui::ViewImpl::OnChildRemove(Actor &child) override
References Dali::Ui::View::DownCast, Dali::Ui::GetImpl, InvalidateMeasure.
void Dali::Ui::ViewImpl::OnPropertySet(Property::Index index, const Property::Value &propertyValue) override
References Dali::Ui::FocusManager::ClearFocus, Dali::Ui::ViewState::DISABLED, Dali::Ui::View::DownCast, Dali::Ui::FocusManager::Get, Dali::Ui::FocusManager::GetCurrentFocusActor, SetState.
Referenced by Dali::Ui::Integration::InputFieldImpl::OnPropertySet, Dali::Ui::Integration::LabelImpl::OnPropertySet.
void Dali::Ui::ViewImpl::OnSizeSet(const Vector3 &targetSize) override
References Dali::Ui::View::Property::BACKGROUND.
void Dali::Ui::ViewImpl::OnSizeAnimation(Animation &animation, const Vector3 &targetSize) override
void Dali::Ui::ViewImpl::OnAnimateAnimatableProperty(Animation &animation, Property::Index index, Dali::Animation::State state) override
Referenced by Dali::Ui::Integration::LabelImpl::OnAnimateAnimatableProperty.
void Dali::Ui::ViewImpl::OnConstraintAnimatableProperty(Constraint &constraint, Property::Index index, bool applied) override
Referenced by Dali::Ui::Integration::LabelImpl::OnConstraintAnimatableProperty.
void Dali::Ui::ViewImpl::GetOffScreenRenderTasks(Dali::Vector< Dali::RenderTask > &tasks, bool isForward) override
void Dali::Ui::ViewImpl::OnSetResizePolicy(ResizePolicy::Type policy, Dimension::Type dimension) override
Vector3 Dali::Ui::ViewImpl::GetNaturalSize() override
References Dali::Ui::View::Property::BACKGROUND.
float Dali::Ui::ViewImpl::CalculateChildSize(const Dali::Actor &child, Dimension::Type dimension) override
float Dali::Ui::ViewImpl::GetHeightForWidth(float width) override
float Dali::Ui::ViewImpl::GetWidthForHeight(float height) override
bool Dali::Ui::ViewImpl::RelayoutDependentOnChildren(Dimension::Type dimension=Dimension::ALL_DIMENSIONS) override
void Dali::Ui::ViewImpl::OnCalculateRelayoutSize(Dimension::Type dimension) override
void Dali::Ui::ViewImpl::OnLayoutNegotiated(float size, Dimension::Type dimension) override
void Dali::Ui::ViewImpl::SignalConnected(SlotObserver *slotObserver, CallbackBase *callback) override
void Dali::Ui::ViewImpl::SignalDisconnected(SlotObserver *slotObserver, CallbackBase *callback) override
Dali::Ui::ViewImpl::ViewImpl()
Default constructor.
References VIEW_BEHAVIOUR_DEFAULT.
Referenced by New.
Dali::Ui::ViewImpl::ViewImpl(ViewBehaviour behaviourFlags)
Constructor with behaviour flags.
behaviourFlags Behavioural flags from ViewBehaviour enum
Dali::Texture Dali::Ui::ViewImpl::GetOffScreenRenderingOutput() const
Gets texture output of offscreen rendering.
The offscreen rendering output texture Valid only inside OffScreenRenderingFinishedSignal() with RENDER_ONCE type.
References Dali::Ui::View::REFRESH_ONCE.
void Dali::Ui::ViewImpl::SetResourceReady()
Marks this view's resources as ready (does not request relayout).
References Internal::ViewDataImpl.
void Dali::Ui::ViewImpl::SetColorBinding(StringView bindingId, const UiColor &color, T *inst, void(T::*setter)(const Vector4 &))
Registers a color binding for theme-aware color updates.
T Type of the instance (ViewImpl or a derived class) bindingId Caller-defined identifier for this binding color The UiColor to apply inst The object whose setter will be used as the callback setter Member function called both immediately and on theme change
References Dali::Ui::UiColor::HasColorId, Dali::Ui::UiColor::Resolve.
Referenced by Dali::Ui::Integration::LabelImpl::SetAnchorClickedColor, Dali::Ui::Integration::LabelImpl::SetAnchorColor, SetBackgroundColor, Dali::Ui::Integration::LabelImpl::SetBevel, SetBorderlineColor, Dali::Ui::Integration::InputFieldImpl::SetCursorColor, Dali::Ui::Integration::InputFieldImpl::SetLineThrough, Dali::Ui::Integration::LabelImpl::SetLineThrough, Dali::Ui::Integration::InputFieldImpl::SetOutline, Dali::Ui::Integration::LabelImpl::SetOutline, Dali::Ui::Integration::InputFieldImpl::SetPlaceholderColor, Dali::Ui::Integration::InputFieldImpl::SetSelectionColor, Dali::Ui::Integration::InputFieldImpl::SetShadow, Dali::Ui::Integration::LabelImpl::SetShadow, Dali::Ui::Integration::InputFieldImpl::SetTextBackgroundColor, Dali::Ui::Integration::LabelImpl::SetTextBackgroundColor, Dali::Ui::Integration::InputFieldImpl::SetTextColor, Dali::Ui::Integration::LabelImpl::SetTextColor, Dali::Ui::Integration::InputFieldImpl::SetUnderline, Dali::Ui::Integration::LabelImpl::SetUnderline.
MeasureCallback * Dali::Ui::ViewImpl::GetMeasureCallback()
Gets the measure callback, if set.
Pointer to the MeasureCallback, or nullptr if not set
Referenced by Dali::Ui::Integration::LayoutImpl::OnMeasure.
ArrangeCallback * Dali::Ui::ViewImpl::GetArrangeCallback()
Gets the arrange callback, if set.
Pointer to the ArrangeCallback, or nullptr if not set
Referenced by Dali::Ui::Integration::LayoutImpl::OnArrange.
void Dali::Ui::ViewImpl::EmitFocusChangedSignal(bool focusGained)
MeasuredSize Dali::Ui::ViewImpl::ApplyConstraints(const MeasuredSize &size) const
void Dali::Ui::ViewImpl::RegisterWithLayoutController()
void Dali::Ui::ViewImpl::MeasureStandaloneChildren(float effectiveWidth, float effectiveHeight)
void Dali::Ui::ViewImpl::ArrangeStandaloneChildren(const LayoutRect &bounds)
Dali::Ui::ViewImpl::ViewImpl(const ViewImpl &)=delete
Dali::Ui::ViewImpl::ViewImpl(ViewImpl &&)=delete
ViewImpl & Dali::Ui::ViewImpl::operator=(const ViewImpl &)=delete
ViewImpl & Dali::Ui::ViewImpl::operator=(ViewImpl &&)=delete
void Dali::Ui::ViewImpl::SetBackgroundColorInternal(const Vector4 &color)
void Dali::Ui::ViewImpl::SetBorderlineColorInternal(const Vector4 &color)
void Dali::Ui::ViewImpl::OnChildOrderChanged(Actor orderChangedChild)
void Dali::Ui::ViewImpl::SetNamedStateHandler(const Dali::String &id, Dali::ConnectionTrackerInterface *tracker, CallbackBase *callback)