Dali::Ui::Integration::WebViewImpl
using Dali::Ui::Integration::WebViewImpl::PageLoadCallback = Callback<void(const Dali::String&)>
Callback type for page load events.
using Dali::Ui::Integration::WebViewImpl::ScrollEdgeReachedCallback = Callback<void(WebViewScrollEdge)>
Callback type for scroll edge reached events.
using Dali::Ui::Integration::WebViewImpl::OverScrolledCallback = Callback<void(WebViewOverScrolled)>
Callback type for over-scrolled events.
using Dali::Ui::Integration::WebViewImpl::UrlChangedCallback = Callback<void(const Dali::String&)>
Callback type for URL changed events.
using Dali::Ui::Integration::WebViewImpl::FrameRenderedCallback = Callback<void()>
Callback type for frame rendered events.
using Dali::Ui::Integration::WebViewImpl::FullscreenCallback = Callback<void()>
Callback type for fullscreen events.
using Dali::Ui::Integration::WebViewImpl::TextFoundCallback = Callback<void(uint32_t)>
Callback type for text found events.
using Dali::Ui::Integration::WebViewImpl::GeolocationPermissionCallback = Callback<bool(const Dali::String&, const Dali::String&)>
Callback type for geolocation permission requests.
using Dali::Ui::Integration::WebViewImpl::WebProcessCrashedCallback = Callback<void()>
Callback type for web process crashed events.
Ui::Visual::Base Dali::Ui::Integration::WebViewImpl::mVisual
Current image visual showing the web content.
Dali::Size Dali::Ui::Integration::WebViewImpl::mWebViewSize
Current web view size (width, height)
Dali::Rect<int32_t> Dali::Ui::Integration::WebViewImpl::mWebViewArea
Last known display area in screen coordinates.
uint32_t Dali::Ui::Integration::WebViewImpl::mLastRenderedNativeImageWidth
Width of the last uploaded NativeImage texture.
uint32_t Dali::Ui::Integration::WebViewImpl::mLastRenderedNativeImageHeight
Height of the last uploaded NativeImage texture.
bool Dali::Ui::Integration::WebViewImpl::mVisualChangeRequired
True when the visual must be re-created on next frame.
bool Dali::Ui::Integration::WebViewImpl::mVideoHoleEnabled
Video hole rendering enabled.
bool Dali::Ui::Integration::WebViewImpl::mMouseEventsEnabled
Mouse events forwarded to web content.
bool Dali::Ui::Integration::WebViewImpl::mKeyEventsEnabled
Key events forwarded to web content.
Dali::PropertyNotification Dali::Ui::Integration::WebViewImpl::mPositionUpdateNotification
Fires on world-position change.
Dali::PropertyNotification Dali::Ui::Integration::WebViewImpl::mSizeUpdateNotification
Fires on size change.
Dali::PropertyNotification Dali::Ui::Integration::WebViewImpl::mScaleUpdateNotification
Fires on world-scale change.
Dali::WebEngine Dali::Ui::Integration::WebViewImpl::mWebEngine
The underlying dali-adaptor web engine instance.
std::function<void(Dali::Ui::ImageView)> Dali::Ui::Integration::WebViewImpl::mPendingScreenshotCallback
Dali::WebEnginePlugin::WebEnginePageLoadCallback Dali::Ui::Integration::WebViewImpl::mPageLoadStartedCallback
Dali::WebEnginePlugin::WebEnginePageLoadCallback Dali::Ui::Integration::WebViewImpl::mPageLoadInProgressCallback
Dali::WebEnginePlugin::WebEnginePageLoadCallback Dali::Ui::Integration::WebViewImpl::mPageLoadFinishedCallback
Dali::WebEnginePlugin::WebEngineScrollEdgeReachedCallback Dali::Ui::Integration::WebViewImpl::mScrollEdgeReachedCallback
Dali::WebEnginePlugin::WebEngineOverScrolledCallback Dali::Ui::Integration::WebViewImpl::mOverScrolledCallback
Dali::WebEnginePlugin::WebEngineUrlChangedCallback Dali::Ui::Integration::WebViewImpl::mUrlChangedCallback
Dali::WebEnginePlugin::WebEngineFrameRenderedCallback Dali::Ui::Integration::WebViewImpl::mFrameRenderedCallback
Dali::WebEnginePlugin::WebEngineFullscreenEnteredCallback Dali::Ui::Integration::WebViewImpl::mFullscreenEnteredCallback
Dali::WebEnginePlugin::WebEngineFullscreenExitedCallback Dali::Ui::Integration::WebViewImpl::mFullscreenExitedCallback
Dali::WebEnginePlugin::WebEngineTextFoundCallback Dali::Ui::Integration::WebViewImpl::mTextFoundCallback
Dali::WebEnginePlugin::GeolocationPermissionCallback Dali::Ui::Integration::WebViewImpl::mGeolocationPermissionCallback
Dali::WebEnginePlugin::WebEngineWebProcessCrashedCallback Dali::Ui::Integration::WebViewImpl::mWebProcessCrashedCallback
Dali::WebEnginePlugin::JavaScriptAlertCallback Dali::Ui::Integration::WebViewImpl::mJavaScriptAlertCallback
Dali::WebEnginePlugin::JavaScriptConfirmCallback Dali::Ui::Integration::WebViewImpl::mJavaScriptConfirmCallback
Dali::WebEnginePlugin::JavaScriptPromptCallback Dali::Ui::Integration::WebViewImpl::mJavaScriptPromptCallback
WebView::PageLoadStartedSignalType Dali::Ui::Integration::WebViewImpl::mPageLoadStartedSignal
WebView::PageLoadInProgressSignalType Dali::Ui::Integration::WebViewImpl::mPageLoadInProgressSignal
WebView::PageLoadFinishedSignalType Dali::Ui::Integration::WebViewImpl::mPageLoadFinishedSignal
WebView::ScrollEdgeReachedSignalType Dali::Ui::Integration::WebViewImpl::mScrollEdgeReachedSignal
WebView::OverScrolledSignalType Dali::Ui::Integration::WebViewImpl::mOverScrolledSignal
WebView::UrlChangedSignalType Dali::Ui::Integration::WebViewImpl::mUrlChangedSignal
WebView::FrameRenderedSignalType Dali::Ui::Integration::WebViewImpl::mFrameRenderedSignal
WebView::FullscreenEnteredSignalType Dali::Ui::Integration::WebViewImpl::mFullscreenEnteredSignal
WebView::FullscreenExitedSignalType Dali::Ui::Integration::WebViewImpl::mFullscreenExitedSignal
WebView::TextFoundSignalType Dali::Ui::Integration::WebViewImpl::mTextFoundSignal
WebView::GeolocationPermissionSignalType Dali::Ui::Integration::WebViewImpl::mGeolocationPermissionSignal
WebView::WebProcessCrashedSignalType Dali::Ui::Integration::WebViewImpl::mWebProcessCrashedSignal
Dali::Ui::Integration::WebViewImpl::WebViewImpl()
WebViewImpl constructor.
Referenced by New.
Dali::Ui::Integration::WebViewImpl::~WebViewImpl()
A reference counted object may only be deleted by calling Unreference().
WebViewImplPtr Dali::Ui::Integration::WebViewImpl::New()
Creates a new WebViewImpl with no engine arguments.
An intrusive pointer to the newly allocated WebViewImpl
References WebViewImpl.
Referenced by Dali::Ui::WebView::New, Dali::Ui::WebView::New.
Dali::String Dali::Ui::Integration::WebViewImpl::GetUrl() const
Gets the current URL.
The current URL
void Dali::Ui::Integration::WebViewImpl::SetUserAgent(const Dali::String &userAgent)
Sets the user agent string.
userAgent The user agent string Reference to this for fluent chaining
Dali::String Dali::Ui::Integration::WebViewImpl::GetUserAgent() const
Gets the user agent string.
The user agent string
void Dali::Ui::Integration::WebViewImpl::LoadUrl(const Dali::String &url)
Loads the specified URL.
url The URL to load Reference to this for fluent chaining
void Dali::Ui::Integration::WebViewImpl::LoadHtmlString(const Dali::String &htmlString)
Loads the specified HTML string.
htmlString The HTML string to load Reference to this for fluent chaining
bool Dali::Ui::Integration::WebViewImpl::LoadHtmlStringOverrideCurrentEntry(const Dali::String &html, const Dali::String &basicUri, const Dali::String &unreachableUrl)
Loads HTML string with override current entry.
html The HTML string basicUri The base URI unreachableUrl The unreachable URL True on success
bool Dali::Ui::Integration::WebViewImpl::LoadContents(const int8_t *contents, uint32_t contentSize, const Dali::String &mimeType, const Dali::String &encoding, const Dali::String &baseUri)
Loads contents.
contents The content data contentSize The size of content data mimeType The MIME type encoding The encoding baseUri The base URI True on success
void Dali::Ui::Integration::WebViewImpl::Reload()
Reloads the current page.
Reference to this for fluent chaining
bool Dali::Ui::Integration::WebViewImpl::ReloadWithoutCache()
Reloads without cache.
True on success
void Dali::Ui::Integration::WebViewImpl::StopLoading()
Stops loading the current page.
Reference to this for fluent chaining
void Dali::Ui::Integration::WebViewImpl::Suspend()
Suspends the web view.
Reference to this for fluent chaining
void Dali::Ui::Integration::WebViewImpl::Resume()
Resumes the web view.
Reference to this for fluent chaining
void Dali::Ui::Integration::WebViewImpl::SuspendNetworkLoading()
Suspends network loading.
void Dali::Ui::Integration::WebViewImpl::ResumeNetworkLoading()
Resumes network loading.
float Dali::Ui::Integration::WebViewImpl::GetLoadProgressPercentage() const
Gets the load progress percentage.
The load progress percentage (0.0 - 100.0)
bool Dali::Ui::Integration::WebViewImpl::AddCustomHeader(const Dali::String &name, const Dali::String &value)
Adds a custom header.
name The header name value The header value True on success
bool Dali::Ui::Integration::WebViewImpl::RemoveCustomHeader(const Dali::String &name)
Removes a custom header.
name The header name True on success
Dali::Vector2 Dali::Ui::Integration::WebViewImpl::GetScrollPosition() const
Gets the scroll position.
The current scroll position
Dali::Vector2 Dali::Ui::Integration::WebViewImpl::GetScrollSize() const
Gets the scroll size.
The scroll size
Dali::Vector2 Dali::Ui::Integration::WebViewImpl::GetContentSize() const
Gets the content size.
The content size
void Dali::Ui::Integration::WebViewImpl::ScrollBy(int32_t deltaX, int32_t deltaY)
Scrolls by the specified delta.
deltaX The horizontal scroll delta deltaY The vertical scroll delta
bool Dali::Ui::Integration::WebViewImpl::ScrollEdgeBy(int32_t deltaX, int32_t deltaY)
Scrolls by edge delta.
deltaX The horizontal scroll delta deltaY The vertical scroll delta True on success
bool Dali::Ui::Integration::WebViewImpl::CanGoForward()
Checks if forward navigation is possible.
True if can go forward
void Dali::Ui::Integration::WebViewImpl::GoForward()
Navigates forward in history.
Reference to this for fluent chaining
bool Dali::Ui::Integration::WebViewImpl::CanGoBack()
Checks if backward navigation is possible.
True if can go back
void Dali::Ui::Integration::WebViewImpl::GoBack()
Navigates backward in history.
Reference to this for fluent chaining
void Dali::Ui::Integration::WebViewImpl::ClearHistory()
Clears the navigation history.
Reference to this for fluent chaining
void Dali::Ui::Integration::WebViewImpl::ClearAllTilesResources()
Clears all tiles resources.
void Dali::Ui::Integration::WebViewImpl::ExitFullscreen()
Exits fullscreen mode.
void Dali::Ui::Integration::WebViewImpl::EvaluateJavaScript(const Dali::String &script)
Evaluates JavaScript code.
script The JavaScript code to evaluate
void Dali::Ui::Integration::WebViewImpl::EvaluateJavaScript(const Dali::String &script, WebView::JavaScriptCallback callback)
void Dali::Ui::Integration::WebViewImpl::AddJavaScriptMessageHandler(const Dali::String &exposedObjectName, WebView::JavaScriptCallback callback)
Adds a JavaScript message handler.
exposedObjectName The exposed object name callback The callback to handle messages
void Dali::Ui::Integration::WebViewImpl::RegisterJavaScriptAlertCallback(WebView::JavaScriptAlertCallback callback)
Registers a JavaScript alert callback.
callback The callback for alert dialogs
void Dali::Ui::Integration::WebViewImpl::JavaScriptAlertReply()
Replies to a JavaScript alert.
void Dali::Ui::Integration::WebViewImpl::RegisterJavaScriptConfirmCallback(WebView::JavaScriptConfirmCallback callback)
Registers a JavaScript confirm callback.
callback The callback for confirm dialogs
void Dali::Ui::Integration::WebViewImpl::JavaScriptConfirmReply(bool confirmed)
Replies to a JavaScript confirm.
confirmed The confirmation result
void Dali::Ui::Integration::WebViewImpl::RegisterJavaScriptPromptCallback(WebView::JavaScriptPromptCallback callback)
Registers a JavaScript prompt callback.
callback The callback for prompt dialogs
void Dali::Ui::Integration::WebViewImpl::JavaScriptPromptReply(const Dali::String &result)
Replies to a JavaScript prompt.
result The prompt result
void Dali::Ui::Integration::WebViewImpl::SetScaleFactor(float scaleFactor, Dali::Vector2 point)
Sets the scale factor at a point.
scaleFactor The scale factor point The point to scale around
float Dali::Ui::Integration::WebViewImpl::GetScaleFactor() const
Gets the scale factor.
The scale factor
float Dali::Ui::Integration::WebViewImpl::GetPageZoomFactor() const
Gets the page zoom factor.
The page zoom factor
void Dali::Ui::Integration::WebViewImpl::SetPageZoomFactor(float zoomFactor)
Sets the page zoom factor.
zoomFactor The zoom factor Reference to this for fluent chaining
float Dali::Ui::Integration::WebViewImpl::GetTextZoomFactor() const
Gets the text zoom factor.
The text zoom factor
void Dali::Ui::Integration::WebViewImpl::SetTextZoomFactor(float zoomFactor)
Sets the text zoom factor.
zoomFactor The zoom factor Reference to this for fluent chaining
Dali::Ui::ImageView Dali::Ui::Integration::WebViewImpl::GetScreenshot(Dali::Rect< int32_t > viewArea, float scaleFactor)
Gets a screenshot.
viewArea The view area scaleFactor The scale factor An ImageView containing the screenshot
bool Dali::Ui::Integration::WebViewImpl::GetScreenshotAsynchronously(Dali::Rect< int32_t > viewArea, float scaleFactor, WebView::ScreenshotCapturedCallback callback)
Gets a screenshot asynchronously.
viewArea The view area scaleFactor The scale factor callback The callback to receive the screenshot True if the operation started successfully
Dali::String Dali::Ui::Integration::WebViewImpl::GetTitle() const
Gets the page title.
The page title
Dali::Ui::ImageView Dali::Ui::Integration::WebViewImpl::GetFavicon() const
Gets the favicon.
An ImageView containing the favicon
Dali::String Dali::Ui::Integration::WebViewImpl::GetSelectedText() const
Gets the currently selected text.
The selected text
void Dali::Ui::Integration::WebViewImpl::GetPlainTextAsynchronously(WebView::PlainTextCallback callback)
Gets plain text asynchronously.
callback The callback to receive the plain text
void Dali::Ui::Integration::WebViewImpl::SetDocumentBackgroundColor(const Dali::Vector4 &color)
Sets the document background color.
color The background color Reference to this for fluent chaining
void Dali::Ui::Integration::WebViewImpl::SetTilesClearedWhenHidden(bool cleared)
Sets whether tiles are cleared when hidden.
cleared True to clear tiles when hidden Reference to this for fluent chaining
void Dali::Ui::Integration::WebViewImpl::SetTileCoverAreaMultiplier(float multiplier)
Sets the tile cover area multiplier.
multiplier The multiplier value Reference to this for fluent chaining
void Dali::Ui::Integration::WebViewImpl::SetCursorEnabledByClient(bool enabled)
Sets whether cursor is enabled by client.
enabled True to enable cursor by client Reference to this for fluent chaining
void Dali::Ui::Integration::WebViewImpl::SetMouseEventsEnabled(bool enabled)
Sets whether mouse events are enabled.
enabled True to enable mouse events Reference to this for fluent chaining
bool Dali::Ui::Integration::WebViewImpl::GetMouseEventsEnabled() const
Gets whether mouse events are enabled.
True if mouse events are enabled
void Dali::Ui::Integration::WebViewImpl::SetKeyEventsEnabled(bool enabled)
Sets whether key events are enabled.
enabled True to enable key events Reference to this for fluent chaining
bool Dali::Ui::Integration::WebViewImpl::GetKeyEventsEnabled() const
Gets whether key events are enabled.
True if key events are enabled
void Dali::Ui::Integration::WebViewImpl::FeedMouseWheel(bool yDirection, int step, int x, int y)
Feeds mouse wheel event.
yDirection True for Y direction step The wheel step x The X coordinate y The Y coordinate
void Dali::Ui::Integration::WebViewImpl::SetVideoHole(bool enabled, bool isWaylandWindow)
Referenced by SetVideoHoleEnabled.
void Dali::Ui::Integration::WebViewImpl::SetVideoHoleEnabled(bool enabled)
Sets whether video hole is enabled.
enabled True to enable video hole Reference to this for fluent chaining
References SetVideoHole.
bool Dali::Ui::Integration::WebViewImpl::GetVideoHoleEnabled() const
Gets whether video hole is enabled.
True if video hole is enabled
bool Dali::Ui::Integration::WebViewImpl::CheckVideoPlayingAsynchronously(WebView::VideoPlayingCallback callback)
Checks if video is playing asynchronously.
callback The callback to receive the result True if the operation started successfully
void Dali::Ui::Integration::WebViewImpl::RegisterPageLoadStartedCallback(PageLoadCallback callback)
void Dali::Ui::Integration::WebViewImpl::RegisterPageLoadInProgressCallback(PageLoadCallback callback)
void Dali::Ui::Integration::WebViewImpl::RegisterPageLoadFinishedCallback(PageLoadCallback callback)
void Dali::Ui::Integration::WebViewImpl::RegisterScrollEdgeReachedCallback(ScrollEdgeReachedCallback callback)
void Dali::Ui::Integration::WebViewImpl::RegisterOverScrolledCallback(OverScrolledCallback callback)
void Dali::Ui::Integration::WebViewImpl::RegisterUrlChangedCallback(UrlChangedCallback callback)
void Dali::Ui::Integration::WebViewImpl::RegisterFrameRenderedCallback(FrameRenderedCallback callback)
References Dali::Ui::Callback< void()>::Release.
void Dali::Ui::Integration::WebViewImpl::RegisterFullscreenEnteredCallback(FullscreenCallback callback)
References Dali::Ui::Callback< void()>::Release.
void Dali::Ui::Integration::WebViewImpl::RegisterFullscreenExitedCallback(FullscreenCallback callback)
References Dali::Ui::Callback< void()>::Release.
void Dali::Ui::Integration::WebViewImpl::RegisterTextFoundCallback(TextFoundCallback callback)
void Dali::Ui::Integration::WebViewImpl::RegisterGeolocationPermissionCallback(GeolocationPermissionCallback callback)
void Dali::Ui::Integration::WebViewImpl::RegisterWebProcessCrashedCallback(WebProcessCrashedCallback callback)
References Dali::Ui::Callback< void()>::Release.
void Dali::Ui::Integration::WebViewImpl::EmitPageLoadStarted(const Dali::String &url)
Emits the PageLoadStartedSignal.
void Dali::Ui::Integration::WebViewImpl::EmitPageLoadInProgress(const Dali::String &url)
Emits the PageLoadInProgressSignal.
void Dali::Ui::Integration::WebViewImpl::EmitPageLoadFinished(const Dali::String &url)
Emits the PageLoadFinishedSignal.
void Dali::Ui::Integration::WebViewImpl::EmitScrollEdgeReached(WebViewScrollEdge edge)
Emits the ScrollEdgeReachedSignal.
void Dali::Ui::Integration::WebViewImpl::EmitOverScrolled(WebViewOverScrolled overScrolled)
Emits the OverScrolledSignal.
void Dali::Ui::Integration::WebViewImpl::EmitUrlChanged(const Dali::String &url)
Emits the UrlChangedSignal.
void Dali::Ui::Integration::WebViewImpl::EmitFrameRendered()
Emits the FrameRenderedSignal.
void Dali::Ui::Integration::WebViewImpl::EmitFullscreenEntered()
Emits the FullscreenEnteredSignal.
void Dali::Ui::Integration::WebViewImpl::EmitFullscreenExited()
Emits the FullscreenExitedSignal.
void Dali::Ui::Integration::WebViewImpl::EmitTextFound(uint32_t count)
Emits the TextFoundSignal.
bool Dali::Ui::Integration::WebViewImpl::EmitGeolocationPermission(const Dali::String &host, const Dali::String &protocol)
Emits the GeolocationPermissionSignal and returns the result.
void Dali::Ui::Integration::WebViewImpl::EmitWebProcessCrashed()
Emits the WebProcessCrashedSignal.
void Dali::Ui::Integration::WebViewImpl::OnInitialize() override
Called after the actor has been initialized.
MeasuredSize Dali::Ui::Integration::WebViewImpl::OnMeasure(float widthConstraint, float heightConstraint) override
Called during measure pass. Override to implement custom measurement.
MeasuredSize Dali::Ui::Integration::WebViewImpl::OnArrange(const LayoutRect &bounds) override
Called during arrange pass. Override to implement custom arrangement.
void Dali::Ui::Integration::WebViewImpl::OnFrameRendered()
Called by the web engine each time a new frame is ready.
Creates or updates the image visual from the latest NativeImage texture.
void Dali::Ui::Integration::WebViewImpl::OnDisplayAreaUpdated(Dali::PropertyNotification &source)
Called when a position, size, or scale PropertyNotification fires.
Re-calculates the screen display area and forwards it to the web engine.
void Dali::Ui::Integration::WebViewImpl::SetDisplayArea(const Dali::Rect< int32_t > &displayArea)
Applies a new display area to the web engine and updates the visual if needed.
displayArea The new display rectangle in screen coordinates
void Dali::Ui::Integration::WebViewImpl::EnableBlendMode(bool blend)
Enables or disables alpha blending on the web content actor.
blend true to enable blending (default), false to disable (video hole mode)
Dali::Ui::Integration::WebViewImpl::WebViewImpl(const WebViewImpl &)=delete
Dali::Ui::Integration::WebViewImpl::WebViewImpl(WebViewImpl &&)=delete
WebViewImpl & Dali::Ui::Integration::WebViewImpl::operator=(const WebViewImpl &)=delete
WebViewImpl & Dali::Ui::Integration::WebViewImpl::operator=(WebViewImpl &&)=delete
Dali::Ui::ImageView Dali::Ui::Integration::WebViewImpl::CreateImageViewFromPixelData(Dali::PixelData pixelData)
Wraps a PixelData in an ImageView for use as a favicon or screenshot thumbnail.
pixelData The pixel data to wrap An ImageView showing the pixel data, or an uninitialized handle if pixelData is invalid
std::string Dali::Ui::Integration::WebViewImpl::ToStdString(const Dali::String &str)
Converts a Dali::String to a std::string for dali-adaptor interop.
str The Dali::String to convert The corresponding std::string
Dali::String Dali::Ui::Integration::WebViewImpl::ToDaliString(const std::string &str)
Converts a std::string from dali-adaptor to a Dali::String.
str The std::string to convert The corresponding Dali::String
WebViewScrollEdge Dali::Ui::Integration::WebViewImpl::ToUiScrollEdge(Dali::WebEnginePlugin::ScrollEdge edge)
Converts a WebEnginePlugin::ScrollEdge to Dali::Ui::WebViewScrollEdge.
WebViewOverScrolled Dali::Ui::Integration::WebViewImpl::ToUiOverScrolled(Dali::WebEnginePlugin::OverScrolled overScrolled)
Converts a WebEnginePlugin::OverScrolled to Dali::Ui::WebViewOverScrolled.
Dali::WebEnginePlugin::FindOption Dali::Ui::Integration::WebViewImpl::ToEngineFindOption(WebViewFindOption options)
Converts a WebViewFindOption to WebEnginePlugin::FindOption.