Dali::Ui::Duration
float Dali::Ui::Duration::mSeconds
constexpr Dali::Ui::Duration::Duration()
Constructs a Duration of zero seconds.
constexpr Dali::Ui::Duration::Duration(float seconds)
Constructs a Duration from seconds.
seconds The duration in seconds
constexpr float Dali::Ui::Duration::InSeconds() const
Returns the duration in seconds.
The duration value in seconds
Referenced by Dali::Ui::ViewAnimationBridge::BorderlineColor, Dali::Ui::ViewAnimationBridge::BorderlineColorBy, Dali::Ui::ViewAnimationBridge::BorderlineOffset, Dali::Ui::ViewAnimationBridge::BorderlineOffsetBy, Dali::Ui::ViewAnimationBridge::BorderlineWidth, Dali::Ui::ViewAnimationBridge::BorderlineWidthBy, Dali::Ui::ViewAnimationBridge::CornerRadius, Dali::Ui::ViewAnimationBridge::CornerRadiusBy, Dali::Ui::ViewAnimationBridge::CornerSquareness, Dali::Ui::ViewAnimationBridge::CornerSquarenessBy, Dali::Ui::ViewAnimationBridge::ExtendIfNeeded, Dali::Ui::ViewAnimationBridge::Opacity, Dali::Ui::ViewAnimationBridge::OpacityBy, Dali::Ui::ViewAnimationBridge::PositionX, Dali::Ui::ViewAnimationBridge::PositionXBy, Dali::Ui::ViewAnimationBridge::PositionY, Dali::Ui::ViewAnimationBridge::PositionYBy, Dali::Ui::ViewAnimationBridge::ScaleX, Dali::Ui::ViewAnimationBridge::ScaleXBy, Dali::Ui::ViewAnimationBridge::ScaleY, Dali::Ui::ViewAnimationBridge::ScaleYBy, Dali::Ui::LabelAnimationBridge::TextColor, Dali::Ui::LabelAnimationBridge::TextColorBy.
constexpr float Dali::Ui::Duration::InMilliseconds() const
Returns the duration in milliseconds.
The duration value in milliseconds