Dali::Ui::Integration::FlexLayoutManager
FlexDirection Dali::Ui::Integration::FlexLayoutManager::mDirection
Referenced by GetDirection, IsMainAxisHorizontal, IsMainAxisReversed, SetDirection.
FlexWrap Dali::Ui::Integration::FlexLayoutManager::mWrap
Referenced by ArrangeChildren, GetWrap, Measure, SetWrap.
FlexJustify Dali::Ui::Integration::FlexLayoutManager::mJustifyContent
Referenced by ArrangeChildren, GetJustifyContent, SetJustifyContent.
FlexAlign Dali::Ui::Integration::FlexLayoutManager::mAlignItems
Referenced by ArrangeChildren, GetAlignItems, SetAlignItems.
FlexAlign Dali::Ui::Integration::FlexLayoutManager::mAlignContent
Referenced by ArrangeChildren, GetAlignContent, SetAlignContent.
Dali::Ui::Integration::FlexLayoutManager::FlexLayoutManager(FlexDirection direction, FlexWrap wrap, FlexJustify justify, FlexAlign alignItems, FlexAlign alignContent)
Dali::Ui::Integration::FlexLayoutManager::~FlexLayoutManager() override
void Dali::Ui::Integration::FlexLayoutManager::SetDirection(FlexDirection direction)
References mDirection.
Referenced by Dali::Ui::Integration::FlexLayoutImpl::SetDirection.
FlexDirection Dali::Ui::Integration::FlexLayoutManager::GetDirection() const
References mDirection.
void Dali::Ui::Integration::FlexLayoutManager::SetWrap(FlexWrap wrap)
References mWrap.
Referenced by Dali::Ui::Integration::FlexLayoutImpl::SetWrap.
FlexWrap Dali::Ui::Integration::FlexLayoutManager::GetWrap() const
References mWrap.
void Dali::Ui::Integration::FlexLayoutManager::SetJustifyContent(FlexJustify justify)
References mJustifyContent.
Referenced by Dali::Ui::Integration::FlexLayoutImpl::SetJustifyContent.
FlexJustify Dali::Ui::Integration::FlexLayoutManager::GetJustifyContent() const
References mJustifyContent.
void Dali::Ui::Integration::FlexLayoutManager::SetAlignItems(FlexAlign align)
References mAlignItems.
Referenced by Dali::Ui::Integration::FlexLayoutImpl::SetAlignItems.
FlexAlign Dali::Ui::Integration::FlexLayoutManager::GetAlignItems() const
References mAlignItems.
void Dali::Ui::Integration::FlexLayoutManager::SetAlignContent(FlexAlign align)
References mAlignContent.
Referenced by Dali::Ui::Integration::FlexLayoutImpl::SetAlignContent.
FlexAlign Dali::Ui::Integration::FlexLayoutManager::GetAlignContent() const
References mAlignContent.
bool Dali::Ui::Integration::FlexLayoutManager::IsMainAxisHorizontal() const
References mDirection, Dali::Ui::ROW, Dali::Ui::ROW_REVERSE.
Referenced by ArrangeChildren, Measure.
bool Dali::Ui::Integration::FlexLayoutManager::IsMainAxisReversed() const
References Dali::Ui::COLUMN_REVERSE, mDirection, Dali::Ui::ROW_REVERSE.
Referenced by ArrangeChildren.
MeasuredSize Dali::Ui::Integration::FlexLayoutManager::Measure(ViewImpl *view, float widthConstraint, float heightConstraint) override
Measures the view and its children.
This method calculates the desired size of the view based on the constraints and the sizes of its children. view The internal view to measure widthConstraint The available width constraint heightConstraint The available height constraint The measured size
References Dali::Ui::LayoutManager::GetChildren, Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetMargin, Dali::Ui::MeasuredSize::height, Dali::Ui::ViewImpl::IsLayoutModeStandalone, IsMainAxisHorizontal, Dali::Ui::ViewImpl::Measure, mWrap, Dali::Ui::NO_WRAP, Dali::Ui::MeasuredSize::width.
MeasuredSize Dali::Ui::Integration::FlexLayoutManager::ArrangeChildren(ViewImpl *view, const LayoutRect &bounds) override
Arranges the children within the view bounds.
This method positions and sizes the children within the given bounds according to the layout algorithm. view The internal view whose children to arrange bounds The available bounds for arranging children The final arranged size
References Dali::Ui::AUTO, Dali::Ui::BASELINE, Dali::Ui::CENTER, crossSize, Dali::Ui::FLEX_END, Dali::Ui::FLEX_START, Dali::Ui::LayoutManager::GetChildren, Dali::Ui::GetImpl, Dali::Ui::LayoutRect::height, IsMainAxisHorizontal, IsMainAxisReversed, mainOffset, mAlignContent, mAlignItems, mJustifyContent, mWrap, Dali::Ui::NO_WRAP, Dali::Ui::STRETCH, Dali::Ui::LayoutRect::width, Dali::Ui::WRAP_REVERSE.