Dali::Ui::UiConfig
BrokenImageType
Broken image for small-sized views.
Dali::Ui::UiConfig::UiConfig()=default
Creates an uninitialized UiConfig handle.
Referenced by DownCast.
Dali::Ui::UiConfig::~UiConfig()=default
Destructor.
Dali::Ui::UiConfig::UiConfig(const UiConfig &handle)=default
Copy constructor.
handle Handle to copy
Dali::Ui::UiConfig::UiConfig(UiConfig &&rhs) noexcept=default
Move constructor.
rhs Handle to move
UiConfig & Dali::Ui::UiConfig::operator=(const UiConfig &handle)=default
Copy assignment operator.
handle Object to assign this to Reference to this
UiConfig & Dali::Ui::UiConfig::operator=(UiConfig &&rhs) noexcept=default
Move assignment operator.
rhs Object to assign this to Reference to this
void Dali::Ui::UiConfig::Apply()
Applies the UiConfig as the global configuration for given application.
This must be called exactly once, typically in main() before the application main loop starts. After this call, the config is frozen and its setter methods can no longer be used. Unit literals (_spx, _dp, _sdp) require this to be called before they can be used. Calling Apply() more than once triggers an assertion failure.
References Dali::Ui::Integration::UiConfigManager::Get, Dali::Ui::Integration::UiConfigManager::Initialize.
UiConfig & Dali::Ui::UiConfig::SetScalingFactor(float scalingFactor)
Sets the scaling factor applied to spx and sdp units.
The config must not be frozen (i.e. not yet call UiConfig::Apply()). scalingFactor The scaling factor value
References Dali::Ui::GetImpl.
float Dali::Ui::UiConfig::GetScalingFactor() const
Retrieves the scaling factor.
The scaling factor applied to spx and sdp units
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::operator""_spx, Dali::Ui::operator""_spx.
float Dali::Ui::UiConfig::GetDpiFactor() const
Retrieves the DPI factor (dpi / baselineDpi).
The config must be frozen (i.e. Apply() must have been called). The computed DPI factor
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::operator""_dp, Dali::Ui::operator""_dp.
float Dali::Ui::UiConfig::GetScaledDpiFactor() const
Retrieves the scaled DPI factor (dpiFactor * scalingFactor).
The config must be frozen (i.e. Apply() must have been called). The computed scaled DPI factor
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::operator""_sdp, Dali::Ui::operator""_sdp.
UiConfig & Dali::Ui::UiConfig::SetDpi(int dpi)
Sets the screen DPI used for dp and sdp unit calculations.
The config must not be frozen. dpi The dots-per-inch value of the target display
References Dali::Ui::GetImpl.
int Dali::Ui::UiConfig::GetDpi() const
Retrieves the screen DPI.
The dots-per-inch value of the target display
References Dali::Ui::GetImpl.
UiConfig & Dali::Ui::UiConfig::SetBaselineDpi(int baselineDpi)
Sets the baseline DPI used as the reference for dp calculations.
The config must not be frozen. baselineDpi The baseline dots-per-inch value
References Dali::Ui::GetImpl.
int Dali::Ui::UiConfig::GetBaselineDpi() const
Retrieves the baseline DPI.
The baseline dots-per-inch used as the reference for dp calculations
References Dali::Ui::GetImpl.
UiConfig & Dali::Ui::UiConfig::SetKeyClickPolicy(KeyClickPolicy policy)
Sets the default key click policy for clickable views.
The config must not be frozen. policy The key click policy
References Dali::Ui::GetImpl.
KeyClickPolicy Dali::Ui::UiConfig::GetKeyClickPolicy() const
Retrieves the default key click policy.
The key click policy
References Dali::Ui::GetImpl.
UiConfig & Dali::Ui::UiConfig::SetExecutionKeyPredicate(ExecutionKeyPredicate predicate)
Sets the predicate used to determine whether a key event triggers click execution (e.g. "Return", "KP_Enter").
When a key event is received by a clickable View, this predicate is called with the key name. If it returns true, the View treats the key as a click execution key and fires the click action. The default predicate matches "Return" only. This parameter is a plain function pointer (ExecutionKeyPredicate). Lambdas with captures and member function pointers are not accepted. Only free functions or stateless lambdas may be used. Passing nullptr restores the default predicate that matches "Return". The config must not be frozen (i.e. Apply() must not have been called). Calling this method after Apply() triggers an assert in debug builds and is ignored in release builds. predicate A function pointer matching the ExecutionKeyPredicate signature, or nullptr to restore the default Reference to this UiConfig for method chaining boolMyKeyPredicate(constDali::String&keyName){ returnkeyName=="Return"||keyName=="KP_Enter"; } UiConfig::New() .SetExecutionKeyPredicate(MyKeyPredicate) .Apply();
References Dali::Ui::GetImpl.
ExecutionKeyPredicate Dali::Ui::UiConfig::GetExecutionKeyPredicate() const
Retrieves the execution key predicate.
The current execution key predicate function pointer
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::Integration::InteractiveTraitImpl::IsExecutionKey.
UiConfig & Dali::Ui::UiConfig::SetKeyLongPressThreshold(uint32_t threshold)
Sets the threshold for recognizing a key long-press.
When a key is held down, the system generates repeated key press events. This threshold defines how many consecutive key press events must be received before the input is recognized as a long-press action. The config must not be frozen. threshold The minimum number of consecutive key press events required to trigger a long-press
References Dali::Ui::GetImpl.
uint32_t Dali::Ui::UiConfig::GetKeyLongPressThreshold() const
Retrieves the threshold for recognizing a key long-press.
The minimum number of consecutive key press events required to trigger a long-press
References Dali::Ui::GetImpl.
UiConfig & Dali::Ui::UiConfig::SetTapRecognizerTime(uint32_t timeMs)
Sets the tap recognizer time limit in milliseconds.
The config must not be frozen. timeMs The time limit in milliseconds
References Dali::Ui::GetImpl.
uint32_t Dali::Ui::UiConfig::GetTapRecognizerTime() const
Retrieves the tap recognizer time limit.
The time limit in milliseconds
References Dali::Ui::GetImpl.
UiConfig & Dali::Ui::UiConfig::SetBrokenImageUrl(BrokenImageType brokenImageType, const Dali::String &brokenImageUrl)
Sets an image to be displayed when image loading fails.
This method configures a broken image that will be shown in image views (e.g., ImageView) when the requested image fails to load properly. Using different broken image types allows for appropriate broken images based on the target view size. The config must not be frozen. brokenImageType The type of broken image (SMALL, NORMAL, or LARGE) brokenImageUrl The URL of the broken image to use
References Dali::Ui::GetImpl.
const Dali::String & Dali::Ui::UiConfig::GetBrokenImageUrl(BrokenImageType brokenImageType) const
Gets the image URL to be displayed when image loading fails.
Retrieves the broken image URL that was previously set for the specified broken image type. This image will be shown in image views when the requested image fails to load. brokenImageType The type of broken image (SMALL, NORMAL, or LARGE) A reference to the broken image URL string
References Dali::Ui::GetImpl.
UiConfig & Dali::Ui::UiConfig::EnableFocusClearOnEscape(bool enable)
Sets whether to clear focus when the Escape key is pressed.
The config must not be frozen. enable True to enable focus clearing on Escape key Reference to this for method chaining
References Dali::Ui::GetImpl.
bool Dali::Ui::UiConfig::IsFocusClearOnEscapeEnabled() const
Retrieves whether to clear focus when the Escape key is pressed.
True if focus clearing on Escape key is enabled
References Dali::Ui::GetImpl.
UiConfig & Dali::Ui::UiConfig::SetAlwaysShowFocus(bool alwaysShow)
Sets whether to always show the keyboard focus indicator.
The config must not be frozen. alwaysShow True to always show focus indicator Reference to this for method chaining
References Dali::Ui::GetImpl.
bool Dali::Ui::UiConfig::IsFocusIndicatorAlwaysShown() const
Retrieves whether to always show the keyboard focus indicator.
True if focus indicator is always shown
References Dali::Ui::GetImpl.
UiConfig & Dali::Ui::UiConfig::SetDefaultFontSize(float fontSize)
Sets the default font point-size for text elements.
The config must not be frozen. fontSize The default font size in points
References Dali::Ui::GetImpl.
float Dali::Ui::UiConfig::GetDefaultFontSize() const
Retrieves the default font point-size.
The default font size in points
References Dali::Ui::GetImpl.
UiConfig & Dali::Ui::UiConfig::SetDefaultTextColor(const Vector4 &color)
Sets the default text color for text elements.
The config must not be frozen. color The default text color
References Dali::Ui::GetImpl.
Vector4 Dali::Ui::UiConfig::GetDefaultTextColor() const
Retrieves the default text color.
The default text color
References Dali::Ui::GetImpl.
UiConfig & Dali::Ui::UiConfig::SetDefaultPlaceholderTextColor(const Vector4 &color)
Sets the default placeholder text color.
The config must not be frozen. color The default placeholder text color.
References Dali::Ui::GetImpl.
Vector4 Dali::Ui::UiConfig::GetDefaultPlaceholderTextColor() const
Returns the default placeholder text color.
The default placeholder text color.
References Dali::Ui::GetImpl.
UiConfig & Dali::Ui::UiConfig::SetShowPlaceholderTextOnFocus(bool enabled)
Sets whether the placeholder text is shown when the control has focus.
The config must not be frozen. enabled True to show the placeholder text when focused, false otherwise.
References Dali::Ui::GetImpl.
bool Dali::Ui::UiConfig::IsPlaceholderTextShownOnFocus() const
Returns whether the placeholder text is shown when the control has focus.
True if the placeholder text is shown when focused, false otherwise.
References Dali::Ui::GetImpl.
UiConfig & Dali::Ui::UiConfig::SetMarqueeSpeed(int speed)
Sets the marquee speed in pixels per second.
The config must not be frozen. speed The marquee speed in pixels per second
References Dali::Ui::GetImpl.
int Dali::Ui::UiConfig::GetMarqueeSpeed() const
Retrieves the marquee speed.
The marquee speed in pixels per second
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::Integration::LabelImpl::GetMarqueeSpeed.
UiConfig & Dali::Ui::UiConfig::SetMarqueeLoopCount(int loopCount)
Sets the number of complete loops for marquee.
The config must not be frozen. loopCount The number of loops
References Dali::Ui::GetImpl.
int Dali::Ui::UiConfig::GetMarqueeLoopCount() const
Retrieves the number of complete loops for marquee.
The number of loops
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::Integration::LabelImpl::GetMarqueeLoopCount.
UiConfig & Dali::Ui::UiConfig::SetMarqueeLoopDelay(float delay)
Sets the amount of time to delay the start of marquee and further loops.
The config must not be frozen. delay The delay time in seconds
References Dali::Ui::GetImpl.
float Dali::Ui::UiConfig::GetMarqueeLoopDelay() const
Retrieves the amount of time to delay the start of marquee and further loops.
The delay time in seconds
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::Integration::LabelImpl::GetMarqueeLoopDelay.
UiConfig & Dali::Ui::UiConfig::SetMarqueeGap(float gap)
Sets the gap before marquee wraps.
The config must not be frozen. gap The gap in pixels
References Dali::Ui::GetImpl.
float Dali::Ui::UiConfig::GetMarqueeGap() const
Retrieves the gap before marquee wraps.
The gap in pixels
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::Integration::LabelImpl::GetMarqueeGap.
UiConfig & Dali::Ui::UiConfig::SetMarqueeStopMode(Text::MarqueeStopMode stopMode)
Sets the marquee stop behaviour.
The config must not be frozen. stopMode The marquee stop mode
References Dali::Ui::GetImpl.
Text::MarqueeStopMode Dali::Ui::UiConfig::GetMarqueeStopMode() const
Retrieves the marquee stop behaviour.
The marquee stop mode
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::Integration::LabelImpl::GetMarqueeStopMode.
UiConfig & Dali::Ui::UiConfig::SetMarqueeOrientation(Text::MarqueeOrientation orientation)
Sets the marquee orientation.
The config must not be frozen. orientation The marquee orientation
References Dali::Ui::GetImpl.
Text::MarqueeOrientation Dali::Ui::UiConfig::GetMarqueeOrientation() const
Retrieves the marquee orientation.
The marquee orientation
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::Integration::LabelImpl::GetMarqueeOrientation.
UiConfig & Dali::Ui::UiConfig::SetLabelAsyncRendering(bool asyncRendering)
Sets whether Label uses asynchronous text rendering by default.
The config must not be frozen. asyncRendering True to enable asynchronous rendering for Label by default, false to use synchronous rendering.
References Dali::Ui::GetImpl.
bool Dali::Ui::UiConfig::IsLabelAsyncRendering() const
Retrieves whether Label uses asynchronous text rendering by default.
True if asynchronous rendering is enabled for Label by default
References Dali::Ui::GetImpl.
UiConfig & Dali::Ui::UiConfig::SetDefaultInteractionEffect(Trait effect)
Sets the default interaction effect applied to views when AsInteractive() is called.
The config must not be frozen. effect A Trait implementing InteractionEffectInterface, or Trait{} to disable the default Reference to this for method chaining
References Dali::Ui::GetImpl.
Trait Dali::Ui::UiConfig::GetDefaultInteractionEffect() const
Returns the default interaction effect.
The default interaction effect handle, or an uninitialized Trait if none is set
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::ViewImpl::EnsureInteractiveTrait.
Dali::Ui::UiConfig::UiConfig(Integration::UiConfigImpl *impl)
This constructor is used internally to wrap an implementation object.
impl A pointer to the internal UiConfig implementation
UiConfig Dali::Ui::UiConfig::New()
Creates a new UiConfig with default values.
Default: scalingFactor=1.0f, dpi=160, baselineDpi=160. An initialized UiConfig handle
References Dali::Ui::Integration::UiConfigImpl::New.
UiConfig Dali::Ui::UiConfig::DownCast(BaseHandle handle)
Downcasts a handle to a UiConfig handle.
If handle points to a UiConfig, the downcast produces a valid handle. If not, the returned handle is left uninitialized. handle Handle to an object A handle to a UiConfig or an uninitialized handle
References UiConfig.