Dali::Ui::ImageUrl
Dali::Ui::ImageUrl::ImageUrl()
Default Constructor. Resulting URL is not valid
Referenced by DownCast, New, New.
Dali::Ui::ImageUrl::~ImageUrl()
Destructor
Dali::Ui::ImageUrl::ImageUrl(const ImageUrl &url)
Copy constructor url The url to copy
ImageUrl & Dali::Ui::ImageUrl::operator=(const ImageUrl &url)
Assignment operator url The url to copy
Dali::Ui::ImageUrl::ImageUrl(ImageUrl &&rhs) noexcept
Move constructor.
rhs A reference to the moved handle
ImageUrl & Dali::Ui::ImageUrl::operator=(ImageUrl &&rhs) noexcept
Move assignment operator.
rhs A reference to the moved handle A reference to this handle
const Dali::String & Dali::Ui::ImageUrl::GetUrl() const
Get the url Returns url's string
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::ImageUrlUtils::GenerateUrl.
ImageUrl Dali::Ui::ImageUrl::New(Texture &texture, bool preMultiplied=false)
Create an initialized ImageUrl.
texture The texture url is got from external buffer. preMultiplied Whether this external texture preMultiplied or not. Default as false. A handle to a newly allocated Dali resource.
References ImageUrl.
Referenced by Dali::Ui::ImageUrlUtils::GenerateDepthUrl, Dali::Ui::ImageUrlUtils::GenerateUrl, Dali::Ui::ImageUrlUtils::GenerateUrl, Dali::Ui::ImageUrlUtils::GenerateUrl, Dali::Ui::ImageUrlUtils::GenerateUrl, Dali::Ui::ImageUrlUtils::GenerateUrl.
ImageUrl Dali::Ui::ImageUrl::New(const EncodedImageBuffer &encodedImageBuffer)
Create an initialized ImageUrl.
encodedImageBuffer The encoded image buffer url is got from external buffer. A handle to a newly allocated Dali resource.
References ImageUrl.
ImageUrl Dali::Ui::ImageUrl::DownCast(BaseHandle handle)
Downcast an Object handle to ImageUrl handle.
If handle points to a ImageUrl object the downcast produces valid handle. If not the returned handle is left uninitialized. handle to An object. handle to a ImageUrl object or an uninitialized handle.
References ImageUrl.