Dali::Ui::UiColor
Type
AlphaMode
const UiColor Dali::Ui::UiColor::PRIMARY
const UiColor Dali::Ui::UiColor::BACKGROUND
const UiColor Dali::Ui::UiColor::OUTLINE
uint8_t Dali::Ui::UiColor::mData[24][24]
Dali::Ui::UiColor::UiColor()
Creates a default UiColor (transparent black, no ID).
Dali::Ui::UiColor::UiColor(float r, float g, float b, float a=1.0f)
Creates a UiColor with explicit RGBA components.
r Red component (0.0 ~ 1.0) g Green component (0.0 ~ 1.0) b Blue component (0.0 ~ 1.0) a Alpha component (0.0 ~ 1.0), defaults to 1.0
Dali::Ui::UiColor::UiColor(const Vector4 &color)
Creates a UiColor from a Vector4.
color The RGBA color as Vector4
Dali::Ui::UiColor::UiColor(const String &colorId)
Creates a UiColor with a string identifier.
The actual RGBA value is resolved from the current theme when Resolve() is called. colorId The color identifier string
Dali::Ui::UiColor::UiColor(String &&colorId)
Creates a UiColor with a string identifier (rvalue overload).
The actual RGBA value is resolved from the current theme when Resolve() is called. This overload enables moving the string into the internal token registry to avoid an extra copy when the caller provides an rvalue. colorId The color identifier string
Dali::Ui::UiColor::UiColor(uint32_t rgb, float a=1.0f)
Creates a UiColor from a hex RGB value.
rgb 0xRRGGBB format hex color a Alpha component (0.0 ~ 1.0), defaults to 1.0
Dali::Ui::UiColor::~UiColor()=default
Dali::Ui::UiColor::UiColor(const UiColor &)=default
Dali::Ui::UiColor::UiColor(UiColor &&) noexcept=default
UiColor & Dali::Ui::UiColor::operator=(const UiColor &)=default
UiColor & Dali::Ui::UiColor::operator=(UiColor &&) noexcept=default
bool Dali::Ui::UiColor::HasColorId() const
Returns whether this UiColor holds a string color ID.
True if this UiColor was constructed with a color ID
Referenced by Dali::Ui::ViewImpl::SetColorBinding.
String Dali::Ui::UiColor::GetColorId() const
Returns the color ID string.
The color ID, or an empty string if this is a direct RGBA color
Vector4 Dali::Ui::UiColor::Resolve() const
Resolves and returns the RGBA value as a Vector4.
If this UiColor has a color ID, the value is looked up from the current theme. If the ID is not found, returns the fallback mColor value (default transparent black). If this UiColor has direct RGBA values, returns them as-is. The resolved RGBA color
References Dali::Ui::UiColorManager::Get.
Referenced by Dali::Ui::ViewAnimationBridge::BackgroundColor, Dali::Ui::ViewAnimationSpec::BackgroundColor, Dali::Ui::ViewAnimationBridge::BackgroundColorBy, Dali::Ui::ViewAnimationSpec::BackgroundColorBy, Dali::Ui::ViewAnimationBridge::BorderlineColor, Dali::Ui::ViewAnimationSpec::BorderlineColor, Dali::Ui::ViewAnimationBridge::BorderlineColorBy, Dali::Ui::ViewAnimationSpec::BorderlineColorBy, Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty, Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty, Dali::Ui::ViewImpl::SetColorBinding, Dali::Ui::Integration::AnimatedImageViewImpl::SetImageColor, Dali::Ui::Integration::ImageViewImpl::SetImageColor, Dali::Ui::Integration::LottieAnimationViewImpl::SetImageColor, Dali::Ui::LabelAnimationBridge::TextColor, Dali::Ui::LabelAnimationSpec::TextColor, Dali::Ui::LabelAnimationBridge::TextColorBy, Dali::Ui::LabelAnimationSpec::TextColorBy.
Dali::Ui::UiColor::operator Vector4() const
Implicit conversion to Vector4.
Equivalent to calling Resolve().
UiColor Dali::Ui::UiColor::ScaleAlpha(float factor) const
Returns a UiColor with alpha scaled by the given factor.
RGBA: out.a = in.a * factor Token: the resolved alpha is scaled by factor
UiColor Dali::Ui::UiColor::WithAlpha(float alpha) const
Returns a UiColor with alpha replaced by the given value.
RGBA: out.a = alpha Token: the resolved alpha is replaced with alpha
UiColor::Type Dali::Ui::UiColor::GetType() const
void Dali::Ui::UiColor::SetType(Type type)
UiColor::AlphaMode Dali::Ui::UiColor::GetAlphaMode() const
void Dali::Ui::UiColor::SetAlphaMode(AlphaMode mode)
Vector4 Dali::Ui::UiColor::GetRgba() const
void Dali::Ui::UiColor::SetRgba(const Vector4 &rgba)
uint32_t Dali::Ui::UiColor::GetTokenId() const
void Dali::Ui::UiColor::SetTokenId(uint32_t tokenId)
float Dali::Ui::UiColor::GetTokenAlpha() const
void Dali::Ui::UiColor::SetTokenAlpha(float alpha)