Dali::Ui::StackLayoutParams
Dali::Ui::StackLayoutParams::StackLayoutParams()
Creates an uninitialized handle.
Referenced by DownCast, New, New.
Dali::Ui::StackLayoutParams::StackLayoutParams(const StackLayoutParams &handle)
Copy constructor.
handle Handle to copy
Dali::Ui::StackLayoutParams::~StackLayoutParams()
Destructor.
StackLayoutParams & Dali::Ui::StackLayoutParams::SetWeight(float weight)
Sets the weight for proportional space distribution along the stack axis.
When 0, the child is measured normally using its LayoutWidth/LayoutHeight. When > 0, the child's main-axis size is determined entirely by its weight proportion of the remaining space (the main-axis LayoutWidth/LayoutHeight is ignored). weight The layout weight Reference to this for chaining
References Dali::Ui::GetImpl.
float Dali::Ui::StackLayoutParams::GetWeight() const
Gets the layout weight.
The weight value
References Dali::Ui::GetImpl.
StackLayoutParams & Dali::Ui::StackLayoutParams::SetAlignment(LayoutAlignment alignment)
Sets the cross-axis alignment for this child within the stack.
In a vertical stack this controls horizontal placement; in a horizontal stack this controls vertical placement. alignment FILL, START (default), CENTER, or END Reference to this for chaining
References Dali::Ui::GetImpl.
LayoutAlignment Dali::Ui::StackLayoutParams::GetAlignment() const
Gets the cross-axis alignment.
The cross-axis alignment
References Dali::Ui::GetImpl.
StackLayoutParams Dali::Ui::StackLayoutParams::New()
Creates a new StackLayoutParams with default values.
A handle to a newly allocated StackLayoutParams
References StackLayoutParams.
StackLayoutParams Dali::Ui::StackLayoutParams::New(const StackLayoutParams &other)
Creates a new StackLayoutParams by copying values from an existing one.
other The params to copy from A handle to a newly allocated StackLayoutParams with copied values
References Dali::Ui::GetImpl, StackLayoutParams.
StackLayoutParams Dali::Ui::StackLayoutParams::DownCast(BaseHandle handle)
Downcasts a handle to StackLayoutParams.
handle Handle to an object A valid handle or an uninitialized handle
References StackLayoutParams.
LayoutParamsType Dali::Ui::StackLayoutParams::GetLayoutParamsType()
Returns the layout params type identifier.
LayoutParamsType::STACK
References Dali::Ui::STACK.