Dali::Ui::SelectableTrait
Dali::Ui::SelectableTrait::SelectableTrait()
Creates an uninitialized Trait handle.
Referenced by DownCast, New.
Dali::Ui::SelectableTrait::SelectableTrait(const SelectableTrait &selectableTrait)
Copy constructor.
Creates another handle that points to the same real object. selectableTrait Handle to copy
Dali::Ui::SelectableTrait::~SelectableTrait()
Destructor.
This is non-virtual since derived Handle types must not contain data or virtual methods.
Signal< void(View, bool, const InputEvent &)> & Dali::Ui::SelectableTrait::SelectionChangedSignal()
Emitted when the selection state changes.
This signal is emitted when the View's selected state changes, either programmatically via SetSelected() or through toggle-by-click interaction. The callback signature is: void YourCallbackName(View view, bool selected) The selection changed signal
References Dali::Ui::GetImpl.
bool Dali::Ui::SelectableTrait::IsSelected() const
Returns whether this View is currently selected.
True if the View is selected
References Dali::Ui::GetImpl.
void Dali::Ui::SelectableTrait::SetSelected(bool selected)
Sets the selection state of this View.
If the new state differs from the current state, the SelectionChangedSignal is emitted. Subclass implementations (e.g. GroupSelectable) may veto or modify the state change. selected True to select, false to deselect
References Dali::Ui::GetImpl.
bool Dali::Ui::SelectableTrait::IsToggleByClickEnabled() const
Returns whether toggle-by-click is enabled.
When enabled, clicking the owner View toggles the selected state. True if toggle-by-click is enabled
References Dali::Ui::GetImpl.
void Dali::Ui::SelectableTrait::EnableToggleByClick(bool enabled=true)
Enables or disables toggle-by-click.
When enabled, the SelectableTrait listens to the owner View's ClickedSignal and toggles the selected state on each click. If the owner View does not already have a InteractiveTrait, one is automatically created and attached. enabled True to enable toggle-by-click, false to disable
References Dali::Ui::GetImpl.
Dali::Ui::SelectableTrait::SelectableTrait(Integration::SelectableTraitImpl *implementation)
Creates a handle using the Internal implementation.
implementation The implementation
SelectableTrait Dali::Ui::SelectableTrait::New()
Creates an initialized SelectableTrait.
A handle to a newly allocated Dali resource
References SelectableTrait.
Referenced by Dali::Ui::ViewImpl::EnsureSelectableTrait.
SelectableTrait Dali::Ui::SelectableTrait::DownCast(BaseHandle handle)
Downcasts a handle to SelectableTrait handle.
If the handle refers to a SelectableTrait (e.g. a trait from GetTrait), the downcast produces a valid handle. Otherwise the returned handle is uninitialized. handle Handle to an object (e.g. Trait from View's selectable trait) A handle to SelectableTrait or an uninitialized handle
References SelectableTrait.
Referenced by Dali::Ui::ViewImpl::EnsureSelectableTrait.