Dali::Ui::ViewState
const ViewState Dali::Ui::ViewState::ALL
Represents all possible states.
const ViewState Dali::Ui::ViewState::NORMAL
No state (0)
const ViewState Dali::Ui::ViewState::FOCUSED
View has keyboard focus.
Referenced by Dali::Ui::ViewImpl::OnFocusChanged, Dali::Ui::ViewImpl::SetState.
const ViewState Dali::Ui::ViewState::PRESSED
View is being pressed (touch or key)
Referenced by Dali::Ui::ViewImpl::SetState.
const ViewState Dali::Ui::ViewState::DISABLED
View is disabled.
Referenced by Dali::Ui::ViewImpl::OnPropertySet, Dali::Ui::ViewImpl::SetState.
const ViewState Dali::Ui::ViewState::PSEUDO_DISABLED
View appears disabled but still interactive.
Referenced by Dali::Ui::Integration::InteractiveTraitImpl::SetPseudoDisabled.
const ViewState Dali::Ui::ViewState::SELECTED
View is selected.
const ViewState Dali::Ui::ViewState::SELECTED_PRESSED
SELECTED + PRESSED.
const ViewState Dali::Ui::ViewState::DISABLED_SELECTED
DISABLED + SELECTED.
const ViewState Dali::Ui::ViewState::SELECTED_FOCUSED
SELECTED + FOCUSED.
constexpr int Dali::Ui::ViewState::MAX_BITS
uint64_t Dali::Ui::ViewState::mBits
constexpr Dali::Ui::ViewState::ViewState()
Creates a Normal state (no bits set).
Referenced by Create.
bool Dali::Ui::ViewState::Contains(const ViewState &other) const
Checks if this state fully contains the specified state.
other The state to check for True if all bits of other are set in this state
Referenced by WasAdded, WasRemoved.
bool Dali::Ui::ViewState::HasIntersectionWith(const ViewState &other) const
Checks if there is any overlap between this and the other state.
other The state to check against True if any common bit is set
bool Dali::Ui::ViewState::IsNormal() const
Checks if this is the Normal state (no bits set).
True if no state bits are set
bool Dali::Ui::ViewState::IsAnyDisabled() const
Checks if this state contains DISABLED or PSEUDO_DISABLED.
True if either DISABLED or PSEUDO_DISABLED is set
References Dali::Ui::DISABLED.
Referenced by Dali::Ui::ViewImpl::SetState.
String Dali::Ui::ViewState::ToString() const
Returns a human-readable string representation for debugging.
A string like "Focused, Pressed" or "Normal"
bool Dali::Ui::ViewState::WasAdded(const ViewState &prev, const ViewState &cur) const
Checks if this state was newly added (not in prev, present in cur).
References Contains.
bool Dali::Ui::ViewState::WasRemoved(const ViewState &prev, const ViewState &cur) const
Checks if this state was removed (present in prev, not in cur).
References Contains.
bool Dali::Ui::ViewState::WasChanged(const ViewState &prev, const ViewState &cur) const
Checks if this state was either added or removed.
bool Dali::Ui::ViewState::AnyChanged(const ViewState &prev, const ViewState &cur) const
Checks if any bit in this state changed between prev and cur.
Unlike WasChanged(), this works with composite states — it returns true if any constituent bit was toggled.
ViewState Dali::Ui::ViewState::operator+(const ViewState &rhs) const
ViewState Dali::Ui::ViewState::operator-(const ViewState &rhs) const
ViewState Dali::Ui::ViewState::operator|(const ViewState &rhs) const
ViewState Dali::Ui::ViewState::operator&(const ViewState &rhs) const
ViewState Dali::Ui::ViewState::operator^(const ViewState &rhs) const
ViewState Dali::Ui::ViewState::operator~() const
bool Dali::Ui::ViewState::operator==(const ViewState &rhs) const
bool Dali::Ui::ViewState::operator!=(const ViewState &rhs) const
Dali::Ui::ViewState::operator bool() const
ViewState Dali::Ui::ViewState::Create(StringView name)
Registers and creates a custom state with the given name.
If the name was already registered, the same bitmask is returned. "Normal" always returns zero, "All" always returns full mask. name The unique name for the state The ViewState with the assigned bitmask DaliException if no more bits are available (max 62 custom states)
References ViewState.
constexpr Dali::Ui::ViewState::ViewState(uint64_t bits)
uint64_t Dali::Ui::ViewState::Register(StringView name)