Dali::Ui::Integration::GridLayoutManager
Dali::Vector<GridLength> Dali::Ui::Integration::GridLayoutManager::mRowDefinitions
Referenced by ArrangeChildren, GetRowDefinitions, Measure, SetRowDefinitions.
Dali::Vector<GridLength> Dali::Ui::Integration::GridLayoutManager::mColumnDefinitions
Referenced by ArrangeChildren, GetColumnDefinitions, Measure, SetColumnDefinitions.
float Dali::Ui::Integration::GridLayoutManager::mRowSpacing
Referenced by ArrangeChildren, GetRowSpacing, Measure, SetRowSpacing.
float Dali::Ui::Integration::GridLayoutManager::mColumnSpacing
Referenced by ArrangeChildren, GetColumnSpacing, Measure, SetColumnSpacing.
Dali::Ui::Integration::GridLayoutManager::GridLayoutManager(const Dali::Vector< GridLength > &rows, const Dali::Vector< GridLength > &columns, float rowSpacing, float columnSpacing)
Dali::Ui::Integration::GridLayoutManager::~GridLayoutManager() override
void Dali::Ui::Integration::GridLayoutManager::SetRowDefinitions(const Dali::Vector< GridLength > &rows)
References mRowDefinitions.
const Dali::Vector< GridLength > & Dali::Ui::Integration::GridLayoutManager::GetRowDefinitions() const
References mRowDefinitions.
Referenced by Dali::Ui::Integration::GridLayoutImpl::AddRowDefinition.
void Dali::Ui::Integration::GridLayoutManager::SetColumnDefinitions(const Dali::Vector< GridLength > &columns)
References mColumnDefinitions.
const Dali::Vector< GridLength > & Dali::Ui::Integration::GridLayoutManager::GetColumnDefinitions() const
References mColumnDefinitions.
Referenced by Dali::Ui::Integration::GridLayoutImpl::AddColumnDefinition.
void Dali::Ui::Integration::GridLayoutManager::SetRowSpacing(float spacing)
References mRowSpacing, spacing.
Referenced by Dali::Ui::Integration::GridLayoutImpl::SetRowSpacing.
float Dali::Ui::Integration::GridLayoutManager::GetRowSpacing() const
References mRowSpacing.
void Dali::Ui::Integration::GridLayoutManager::SetColumnSpacing(float spacing)
References mColumnSpacing, spacing.
Referenced by Dali::Ui::Integration::GridLayoutImpl::SetColumnSpacing.
float Dali::Ui::Integration::GridLayoutManager::GetColumnSpacing() const
References mColumnSpacing.
MeasuredSize Dali::Ui::Integration::GridLayoutManager::Measure(ViewImpl *view, float widthConstraint, float heightConstraint) override
Measures the view and its children.
This method calculates the desired size of the view based on the constraints and the sizes of its children. view The internal view to measure widthConstraint The available width constraint heightConstraint The available height constraint The measured size
References Dali::Ui::LayoutManager::GetChildren, Dali::Ui::GetImpl, Dali::Ui::ViewImpl::GetMinimumHeight, Dali::Ui::ViewImpl::GetMinimumWidth, Dali::Ui::ViewImpl::GetPadding, Dali::Ui::ViewImpl::GetRequestedHeight, Dali::Ui::ViewImpl::GetRequestedWidth, Dali::Ui::MATCH_PARENT, mColumnDefinitions, mColumnSpacing, mRowDefinitions, mRowSpacing, Dali::Ui::STAR.
MeasuredSize Dali::Ui::Integration::GridLayoutManager::ArrangeChildren(ViewImpl *view, const LayoutRect &bounds) override
Arranges the children within the view bounds.
This method positions and sizes the children within the given bounds according to the layout algorithm. view The internal view whose children to arrange bounds The available bounds for arranging children The final arranged size
References Dali::Ui::LayoutManager::GetChildren, Dali::Ui::GetImpl, Dali::Ui::LayoutRect::height, mColumnDefinitions, mColumnSpacing, mRowDefinitions, mRowSpacing, Dali::Ui::LayoutRect::width.