Dali::Ui::InteractiveTrait
Dali::Ui::InteractiveTrait::InteractiveTrait()
Creates an uninitialized Trait handle.
Referenced by DownCast, New.
Dali::Ui::InteractiveTrait::InteractiveTrait(const InteractiveTrait &interactiveTrait)
Copy constructor.
Creates another handle that points to the same real object. interactiveTrait Handle to copy
Dali::Ui::InteractiveTrait::~InteractiveTrait()
Destructor.
This is non-virtual since derived Handle types must not contain data or virtual methods.
Signal< void(View, bool, const InputEvent &)> & Dali::Ui::InteractiveTrait::PressedChangedSignal()
Emitted when the pressed state changes.
This signal is emitted when the view's pressed state changes due to touch or keyboard input. The pressed state is true when the user is interacting with the view (e.g., pressing down), and false when the interaction ends (e.g., releasing the touch or key). The pressed changed signal
References Dali::Ui::GetImpl.
Signal< void(View, bool)> & Dali::Ui::InteractiveTrait::PseudoDisabledChangedSignal()
Emitted when the pseudo disabled state changes.
This signal is emitted when the pseudo disabled state is changed via SetPseudoDisabled(). The view is visually presented as disabled when in pseudo disabled state, but it still accepts user interaction to provide guidance or an alternative flow. The pseudo disabled changed signal
References Dali::Ui::GetImpl.
Signal< void(View, const InputEvent &)> & Dali::Ui::InteractiveTrait::ClickedSignal()
Emitted when the view is clicked.
This signal is emitted when the view receives a tap gesture, indicating a click action. The click action is triggered when the user taps on the view. This signal may not be emitted if the one of LongPressed signal handler consumes the event (returns true). The clicked signal
References Dali::Ui::GetImpl.
Signal< bool(View, const InputEvent &)> & Dali::Ui::InteractiveTrait::LongPressedSignal()
Emitted when the view receives a long press gesture.
This signal is emitted when the user performs a long press on the view. A long press is detected when the user presses and holds on the view for a specified duration. If the handler returns true to consume the event, the Clicked signal will not be emitted. This signal is not emitted when ClickedKeyType is set to PRESS. The long pressed signal
References Dali::Ui::GetImpl.
bool Dali::Ui::InteractiveTrait::IsPressed() const
The boolean flag for pressed state.
True if the object is pressed
References Dali::Ui::GetImpl.
bool Dali::Ui::InteractiveTrait::IsPseudoDisabled() const
Checks if the view is pseudo disabled state. The view is visually presented as disabled, but it still accepts user interaction in order to provide guidance or an alternative flow.
True if the object is pseudo disabled
References Dali::Ui::GetImpl.
void Dali::Ui::InteractiveTrait::SetPseudoDisabled(bool pseudoDisabled)
Sets the pseudo disabled state to the view. The view is visually presented as disabled, but it still accepts user interaction in order to provide guidance or an alternative flow.
pseudoDisabled True if the object is pseudo disabled
References Dali::Ui::GetImpl.
bool Dali::Ui::InteractiveTrait::IsClickable() const
Checks if clicking is currently allowed (not blocked).
True if clicking is allowed, false if clicking is blocked
References Dali::Ui::GetImpl.
void Dali::Ui::InteractiveTrait::SetClickable(bool clickable)
Sets whether clicking is allowed.
clickable True to allow clicking, false to block clicking
References Dali::Ui::GetImpl.
KeyClickPolicy Dali::Ui::InteractiveTrait::GetKeyClickPolicy() const
Retrieves the current key click policy.
The active KeyClickPolicy for this button.
References Dali::Ui::GetImpl.
void Dali::Ui::InteractiveTrait::SetKeyClickPolicy(KeyClickPolicy policy)
Configures the trigger timing for key-driven click events.
policy The KeyClickPolicy to be applied (OnRelease, OnPress, or Disabled).
References Dali::Ui::GetImpl.
void Dali::Ui::InteractiveTrait::ConnectClickedSignal(T *obj, Func func)
Connects a handler to ClickedSignal.
Multiple calls accumulate — each call adds an additional handler. If obj implements ConnectionTrackerInterface (e.g. inherits ConnectionTracker), the connection is automatically removed when obj is destroyed. Supports member functions and stateless lambdas: view.ConnectClickedSignal(this,&MyClass::OnButtonClicked); view.ConnectClickedSignal(this,[](Viewv,constInputEvent&e){...}); obj The object to connect to (must implement ConnectionTrackerInterface for auto-disconnect) func Member function pointer or functor with signature void(View, const InputEvent&) Reference to this for method chaining
void Dali::Ui::InteractiveTrait::ConnectPressedChangedSignal(T *obj, Func func)
Connects a handler to PressedChangedSignal.
Multiple calls accumulate — each call adds an additional handler. The handler is called with pressed=true on press-down and pressed=false on release. If obj implements ConnectionTrackerInterface, the connection is auto-removed on obj destruction. obj The object to connect to func Member function pointer or functor with signature void(View, bool, const InputEvent&) Reference to this for method chaining
void Dali::Ui::InteractiveTrait::ConnectLongPressedSignal(T *obj, Func func)
Connects a handler to LongPressedSignal.
Multiple calls accumulate — each call adds an additional handler. Long press fires once when the gesture is detected (on press-down after the time threshold). Press release is reported separately via PressedChangedSignal. The handler must return bool: return true to suppress the subsequent click event, or false to allow it. If obj implements ConnectionTrackerInterface, the connection is auto-removed on obj destruction. obj The object to connect to func Member function pointer or functor with signature bool(View, const InputEvent&) Reference to this for method chaining
Dali::Ui::InteractiveTrait::InteractiveTrait(Integration::InteractiveTraitImpl *implementation)
Creates a handle using the Internal implementation.
implementation The implementation
InteractiveTrait Dali::Ui::InteractiveTrait::New()
Creates an initialized Trait.
A handle to a newly allocated Dali resource
References InteractiveTrait.
Referenced by Dali::Ui::ViewImpl::EnsureInteractiveTrait.
InteractiveTrait Dali::Ui::InteractiveTrait::DownCast(BaseHandle handle)
Downcasts a handle to InteractiveTrait handle.
If the handle refers to a InteractiveTrait (e.g. a trait from GetTrait), the downcast produces a valid handle. Otherwise the returned handle is uninitialized. handle Handle to an object (e.g. Trait from View's interaction trait) A handle to InteractiveTrait or an uninitialized handle
References InteractiveTrait.
Referenced by Dali::Ui::ViewImpl::EnsureInteractiveTrait.