Dali::Ui::AccessibilityHighlightOverlay
bool Dali::Ui::AccessibilityHighlightOverlay::mHasOverlayActor
OverlayHighlightMode Dali::Ui::AccessibilityHighlightOverlay::mOverlayMode
Vector2 Dali::Ui::AccessibilityHighlightOverlay::mManualPosition
Vector2 Dali::Ui::AccessibilityHighlightOverlay::mManualSize
Dali::WeakHandle<Dali::Actor> Dali::Ui::AccessibilityHighlightOverlay::mOverlayActor
Dali::Ui::AccessibilityHighlightOverlay::AccessibilityHighlightOverlay()
void Dali::Ui::AccessibilityHighlightOverlay::SetCustomHighlight(Vector2 position, Vector2 size)
Function to set a custom highlight overlay.
This function sets a custom highlight overlay at the specified position and size. position A Vector2 representing the position of the overlay size A Vector2 representing the size of the overlay
References Dali::Ui::MANUAL.
Referenced by Dali::Ui::ViewAccessible::SetCustomHighlightOverlay.
void Dali::Ui::AccessibilityHighlightOverlay::ResetCustomHighlight()
Function to reset the custom highlight overlay.
This function resets the custom highlight overlay.
References Dali::Ui::AUTO.
Referenced by Dali::Ui::ViewAccessible::ResetCustomHighlightOverlay.
void Dali::Ui::AccessibilityHighlightOverlay::UpdateOverlay(Dali::Actor &activeHighlight)
Updates the currently active highlight overlay. If no overlay exists, it creates a new one.
activeHighlight The currently active highlight actor.
Referenced by Dali::Ui::ViewAccessible::GrabHighlight.
void Dali::Ui::AccessibilityHighlightOverlay::HideOverlay()
Hides the currently displayed highlight overlay.
Referenced by Dali::Ui::ViewAccessible::ClearHighlight.
void Dali::Ui::AccessibilityHighlightOverlay::SetOverlayMode(OverlayHighlightMode mode)
Sets the currently overlay mode.
mode The currently OverlayHighlightMode to set.
OverlayHighlightMode Dali::Ui::AccessibilityHighlightOverlay::GetOverlayMode() const
Gets the currently overlay mode.
Dali::Actor Dali::Ui::AccessibilityHighlightOverlay::FindParentSceneView(Dali::Actor current)
Finds the parent SceneView of the given actor and returns the SceneView along with a boolean indicating whether the parent contains a model.
current The current actor. Returns the SceneView containing the current object. If the current object is not a child of any SceneView, returns null.
void Dali::Ui::AccessibilityHighlightOverlay::CreateOverlay(Dali::Actor &sceneView)
Creates a highlight overlay for the given SceneView.
sceneView The SceneView for which the highlight overlay will be created.
void Dali::Ui::AccessibilityHighlightOverlay::UpdateOverlayPosition(Dali::Actor &sceneView, Dali::Actor &highlight)
Updates the position of the highlight based on the given SceneView and the previous highlight actor.
sceneView The SceneView for which the highlight position will be updated. highlight The previously used highlight actor.
Rect< float > Dali::Ui::AccessibilityHighlightOverlay::GetOverlayExtents(Dali::Actor &sceneView, Dali::Actor &highlight)
Returns the size and position of the screen overlay based on the given SceneView and the previous highlight actor.
sceneView The SceneView for which the screen overlay extents will be calculated. highlight The previously used highlight actor. A Rect<float> representing the extents of the screen overlay.