Dali::Ui::Integration::UiConfigManagerImpl
UiConfig Dali::Ui::Integration::UiConfigManagerImpl::mConfig
bool Dali::Ui::Integration::UiConfigManagerImpl::mUiConfigInitialized
bool Dali::Ui::Integration::UiConfigManagerImpl::mApplicationCreated
bool Dali::Ui::Integration::UiConfigManagerImpl::mLifecycleControllerCallbackConnected
UiConfigManagerImplPtr Dali::Ui::Integration::UiConfigManagerImpl::New()
Referenced by Dali::Ui::Integration::UiConfigManager::Get.
void Dali::Ui::Integration::UiConfigManagerImpl::Initialize(const UiConfig &config)
< Method from UiConfigManager
Initializes the manager with the given UiConfig. This method must be called exactly once before the application main loop starts. After this call, the UiConfig is frozen and its setter methods can no longer be used. Calling Initialize() more than once triggers an assertion failure. config The UiConfig to use globally
References Dali::Ui::UiThemeManager::Get, Dali::Ui::GetImpl.
bool Dali::Ui::Integration::UiConfigManagerImpl::IsInitialized() const
Returns whether Initialize() has been called.
True if the manager has been initialized
const UiConfig & Dali::Ui::Integration::UiConfigManagerImpl::GetConfig() const
Returns the global UiConfig instance.
Initialize() must have been called. Triggers assertion failure otherwise. The global UiConfig handle
ThemeLoaderInterface * Dali::Ui::Integration::UiConfigManagerImpl::CreateThemeLoader()
References Dali::Ui::GetImpl.
bool Dali::Ui::Integration::UiConfigManagerImpl::RegisterLifecycleControllerCallback()
< Internal API for UiConfigManager
Register callbacks to LifecycleController. It could be failed if we try to register too ealy timing, like before Core::New(). True if register successed, or already registered. False if register failed.
References OnApplicationCreated.
Referenced by UiConfigManagerImpl.
Dali::Ui::Integration::UiConfigManagerImpl::UiConfigManagerImpl()
Constructor. Used internally to create the singleton impl.
References RegisterLifecycleControllerCallback.
Dali::Ui::Integration::UiConfigManagerImpl::~UiConfigManagerImpl() override
Destructor.
void Dali::Ui::Integration::UiConfigManagerImpl::OnApplicationCreated()
References Dali::Ui::GetImpl.
Referenced by RegisterLifecycleControllerCallback.
Dali::Ui::Integration::UiConfigManagerImpl::UiConfigManagerImpl(const UiConfigManagerImpl &)=delete
Dali::Ui::Integration::UiConfigManagerImpl::UiConfigManagerImpl(UiConfigManagerImpl &&)=delete
UiConfigManagerImpl & Dali::Ui::Integration::UiConfigManagerImpl::operator=(const UiConfigManagerImpl &)=delete
UiConfigManagerImpl & Dali::Ui::Integration::UiConfigManagerImpl::operator=(UiConfigManagerImpl &&)=delete