Dali::Ui::ViewAnimationBridge
Animation Dali::Ui::ViewAnimationBridge::mAnimation
Referenced by BackgroundColor, BackgroundColorBy, BorderlineColor, BorderlineColorBy, BorderlineOffset, BorderlineOffsetBy, BorderlineWidth, BorderlineWidthBy, CornerRadius, CornerRadiusBy, CornerSquareness, CornerSquarenessBy, Opacity, OpacityBy, PositionX, PositionXBy, PositionY, PositionYBy, ScaleX, ScaleXBy, ScaleY, ScaleYBy, SizeHeight, SizeHeightBy, SizeWidth, SizeWidthBy.
View Dali::Ui::ViewAnimationBridge::mView
Referenced by BackgroundColor, BackgroundColorBy, BorderlineColor, BorderlineColorBy, BorderlineOffset, BorderlineOffsetBy, BorderlineWidth, BorderlineWidthBy, CornerRadius, CornerRadiusBy, CornerSquareness, CornerSquarenessBy, Opacity, OpacityBy, PositionX, PositionXBy, PositionY, PositionYBy, ScaleX, ScaleXBy, ScaleY, ScaleYBy, SizeHeight, SizeHeightBy, SizeWidth, SizeWidthBy.
void* Dali::Ui::ViewAnimationBridge::mReserved
Reserved for future use.
friend class View
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::BackgroundColor(const UiColor &target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the background color.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References ExtendIfNeeded, mAnimation, mView, Dali::Ui::UiColor::Resolve.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::BackgroundColorBy(const UiColor &relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the background color by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References ExtendIfNeeded, mAnimation, mView, Dali::Ui::UiColor::Resolve.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::SizeWidth(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the size width.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References ExtendIfNeeded, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::SizeWidthBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the size width by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References ExtendIfNeeded, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::SizeHeight(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the size height.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References ExtendIfNeeded, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::SizeHeightBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the size height by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References ExtendIfNeeded, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::ScaleX(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the scale x.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::ScaleXBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the scale x by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::ScaleY(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the scale y.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::ScaleYBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the scale y by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::Opacity(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the opacity.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::OpacityBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the opacity by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::PositionX(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the position x.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::PositionXBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the position x by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::PositionY(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the position y.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::PositionYBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the position y by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::CornerRadius(const Vector4 &target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the corner radius.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::CORNER_RADIUS, ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::CornerRadiusBy(const Vector4 &relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the corner radius by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::CORNER_RADIUS, ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::CornerSquareness(const Vector4 &target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the corner squareness.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::CORNER_SQUARENESS, ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::CornerSquarenessBy(const Vector4 &relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the corner squareness by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::CORNER_SQUARENESS, ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::BorderlineWidth(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the borderline width.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::BORDERLINE_WIDTH, ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::BorderlineWidthBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the borderline width by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::BORDERLINE_WIDTH, ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::BorderlineColor(const UiColor &target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the borderline color.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::BORDERLINE_COLOR, ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView, Dali::Ui::UiColor::Resolve.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::BorderlineColorBy(const UiColor &relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the borderline color by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::BORDERLINE_COLOR, ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView, Dali::Ui::UiColor::Resolve.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::BorderlineOffset(float target, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the borderline offset.
target The target value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::BORDERLINE_OFFSET, ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
ViewAnimationBridge & Dali::Ui::ViewAnimationBridge::BorderlineOffsetBy(float relative, Duration duration, AlphaFunction alpha=AlphaFunction(), Duration delay=Duration())
Animates the borderline offset by a relative amount.
relative The relative value duration The animation duration alpha The alpha function (default: linear) delay The delay before starting (default: 0)
References Dali::Ui::View::Property::BORDERLINE_OFFSET, ExtendIfNeeded, Dali::Ui::Duration::InSeconds, mAnimation, mView.
Dali::Ui::ViewAnimationBridge::ViewAnimationBridge(Animation animation, View view)
void Dali::Ui::ViewAnimationBridge::ExtendIfNeeded(Duration delay, Duration duration)
References Dali::Ui::Duration::InSeconds.
Referenced by BackgroundColor, BackgroundColorBy, BorderlineColor, BorderlineColorBy, BorderlineOffset, BorderlineOffsetBy, BorderlineWidth, BorderlineWidthBy, CornerRadius, CornerRadiusBy, CornerSquareness, CornerSquarenessBy, Opacity, OpacityBy, PositionX, PositionXBy, PositionY, PositionYBy, ScaleX, ScaleXBy, ScaleY, ScaleYBy, SizeHeight, SizeHeightBy, SizeWidth, SizeWidthBy.