Dali::Ui::LayoutManager
Dali::Ui::LayoutManager::~LayoutManager()
Virtual destructor.
Dali::Ui::LayoutManager::LayoutManager()
Default constructor.
virtual MeasuredSize Dali::Ui::LayoutManager::Measure(ViewImpl *view, float widthConstraint, float heightConstraint)=0
Measures the view and its children.
This method calculates the desired size of the view based on the constraints and the sizes of its children. view The internal view to measure widthConstraint The available width constraint heightConstraint The available height constraint The measured size
Referenced by Dali::Ui::Integration::LayoutImpl::OnMeasure.
virtual MeasuredSize Dali::Ui::LayoutManager::ArrangeChildren(ViewImpl *view, const LayoutRect &bounds)=0
Arranges the children within the view bounds.
This method positions and sizes the children within the given bounds according to the layout algorithm. view The internal view whose children to arrange bounds The available bounds for arranging children The final arranged size
Referenced by Dali::Ui::Integration::LayoutImpl::OnArrange.
MeasuredSize Dali::Ui::LayoutManager::MeasureChild(ViewImpl *child, float widthConstraint, float heightConstraint)
Measures a child view.
Helper method for derived classes to measure a child view. child The child to measure widthConstraint The width constraint for the child heightConstraint The height constraint for the child The measured size of the child
References Dali::Ui::ViewImpl::Measure.
MeasuredSize Dali::Ui::LayoutManager::ArrangeChild(ViewImpl *child, const LayoutRect &bounds)
Arranges a child view within the given bounds.
Helper method for derived classes to arrange a child view. child The child to arrange bounds The bounds for the child The final arranged size
References Dali::Ui::ViewImpl::Arrange.
ViewImpl::ChildContainer & Dali::Ui::LayoutManager::GetChildren(ViewImpl *view)
Gets the children container from a view.
Helper method for derived classes to access children. view The view to get children from Reference to the children container
References Dali::Ui::ViewImpl::GetChildren.
Referenced by Dali::Ui::Integration::AbsoluteLayoutManager::ArrangeChildren, Dali::Ui::Integration::FlexLayoutManager::ArrangeChildren, Dali::Ui::Integration::GridLayoutManager::ArrangeChildren, Dali::Ui::Integration::ScrollViewLayoutManager::ArrangeChildren, Dali::Ui::Integration::StackLayoutManager::ArrangeChildren, Dali::Ui::Integration::AbsoluteLayoutManager::Measure, Dali::Ui::Integration::FlexLayoutManager::Measure, Dali::Ui::Integration::GridLayoutManager::Measure, Dali::Ui::Integration::ScrollViewLayoutManager::Measure, Dali::Ui::Integration::StackLayoutManager::Measure.
Dali::Ui::LayoutManager::LayoutManager(const LayoutManager &)=delete
Dali::Ui::LayoutManager::LayoutManager(LayoutManager &&)=delete
LayoutManager & Dali::Ui::LayoutManager::operator=(const LayoutManager &)=delete
LayoutManager & Dali::Ui::LayoutManager::operator=(LayoutManager &&)=delete