Dali::Ui::Integration::FlexLayoutImpl
FlexLayoutImplPtr Dali::Ui::Integration::FlexLayoutImpl::New()
Creates a new FlexLayout implementation.
An IntrusivePtr to the new FlexLayoutImpl
References FlexLayoutImpl.
Referenced by Dali::Ui::FlexLayout::New.
Dali::Ui::Integration::FlexLayoutImpl::~FlexLayoutImpl()
void Dali::Ui::Integration::FlexLayoutImpl::OnInitialize() override
Called after the actor has been initialized.
References Dali::Ui::FLEX_START, Dali::Ui::NO_WRAP, Dali::Ui::ViewImpl::OnInitialize, Dali::Ui::ROW, Dali::Ui::Integration::LayoutImpl::SetLayoutManager, Dali::Ui::STRETCH.
Dali::Ui::Integration::FlexLayoutImpl::FlexLayoutImpl()
Referenced by New.
void Dali::Ui::Integration::FlexLayoutImpl::SetDirection(FlexDirection direction)
References Dali::Ui::Integration::LayoutImpl::GetLayoutManager, Dali::Ui::ViewImpl::InvalidateMeasure, Dali::Ui::Integration::FlexLayoutManager::SetDirection.
FlexDirection Dali::Ui::Integration::FlexLayoutImpl::GetDirection() const
References GetDirection, Dali::Ui::Integration::LayoutImpl::GetLayoutManager.
Referenced by GetDirection.
void Dali::Ui::Integration::FlexLayoutImpl::SetWrap(FlexWrap wrap)
References Dali::Ui::Integration::LayoutImpl::GetLayoutManager, Dali::Ui::ViewImpl::InvalidateMeasure, Dali::Ui::Integration::FlexLayoutManager::SetWrap.
FlexWrap Dali::Ui::Integration::FlexLayoutImpl::GetWrap() const
References Dali::Ui::Integration::LayoutImpl::GetLayoutManager, GetWrap.
Referenced by GetWrap.
void Dali::Ui::Integration::FlexLayoutImpl::SetJustifyContent(FlexJustify justify)
References Dali::Ui::Integration::LayoutImpl::GetLayoutManager, Dali::Ui::ViewImpl::InvalidateArrange, Dali::Ui::Integration::FlexLayoutManager::SetJustifyContent.
FlexJustify Dali::Ui::Integration::FlexLayoutImpl::GetJustifyContent() const
References GetJustifyContent, Dali::Ui::Integration::LayoutImpl::GetLayoutManager.
Referenced by GetJustifyContent.
void Dali::Ui::Integration::FlexLayoutImpl::SetAlignItems(FlexAlign align)
References Dali::Ui::Integration::LayoutImpl::GetLayoutManager, Dali::Ui::ViewImpl::InvalidateArrange, Dali::Ui::Integration::FlexLayoutManager::SetAlignItems.
FlexAlign Dali::Ui::Integration::FlexLayoutImpl::GetAlignItems() const
References GetAlignItems, Dali::Ui::Integration::LayoutImpl::GetLayoutManager.
Referenced by GetAlignItems.
void Dali::Ui::Integration::FlexLayoutImpl::SetAlignContent(FlexAlign align)
References Dali::Ui::Integration::LayoutImpl::GetLayoutManager, Dali::Ui::ViewImpl::InvalidateArrange, Dali::Ui::Integration::FlexLayoutManager::SetAlignContent.
FlexAlign Dali::Ui::Integration::FlexLayoutImpl::GetAlignContent() const
References GetAlignContent, Dali::Ui::Integration::LayoutImpl::GetLayoutManager.
Referenced by GetAlignContent.
Dali::Ui::Integration::FlexLayoutImpl::FlexLayoutImpl(const FlexLayoutImpl &)=delete
Dali::Ui::Integration::FlexLayoutImpl::FlexLayoutImpl(FlexLayoutImpl &&)=delete
FlexLayoutImpl & Dali::Ui::Integration::FlexLayoutImpl::operator=(const FlexLayoutImpl &)=delete
FlexLayoutImpl & Dali::Ui::Integration::FlexLayoutImpl::operator=(FlexLayoutImpl &&)=delete