Dali::Ui::JsonParser
JsonParser Dali::Ui::JsonParser::New()
References JsonParser.
JsonParser Dali::Ui::JsonParser::New(const TreeNode &tree)
References JsonParser.
JsonParser Dali::Ui::JsonParser::DownCast(BaseHandle handle)
Downcast an Object handle to JsonParser if it is a JsonParser. handle Handle to an object A handle to a JsonParser or an uninitialized handle
References JsonParser.
Dali::Ui::JsonParser::JsonParser()
Referenced by DownCast, New, New.
Dali::Ui::JsonParser::~JsonParser()
Destructor.
This is non-virtual since derived Handle types must not contain data or virtual methods.
bool Dali::Ui::JsonParser::Parse(const std::string &source)
void Dali::Ui::JsonParser::Pack(void)
const TreeNode * Dali::Ui::JsonParser::GetRoot() const
bool Dali::Ui::JsonParser::ParseError() const
int Dali::Ui::JsonParser::GetErrorPosition() const
std::string Dali::Ui::JsonParser::GetErrorDescription() const
int Dali::Ui::JsonParser::GetErrorLineNumber() const
int Dali::Ui::JsonParser::GetErrorColumn() const
void Dali::Ui::JsonParser::Write(std::ostream &output, int indent) const
Dali::Ui::JsonParser::JsonParser(Internal::JsonParser *parser)
This constructor is used by Dali New() methods parser A pointer to a newly allocated Dali resource