Dali::Ui::Integration::GridLayoutImpl
GridLayoutImplPtr Dali::Ui::Integration::GridLayoutImpl::New()
Creates a new GridLayout implementation.
An IntrusivePtr to the new GridLayoutImpl
References GridLayoutImpl.
Referenced by Dali::Ui::GridLayout::New.
Dali::Ui::Integration::GridLayoutImpl::~GridLayoutImpl()
void Dali::Ui::Integration::GridLayoutImpl::OnInitialize() override
Called after the actor has been initialized.
References Dali::Ui::ViewImpl::OnInitialize, Dali::Ui::Integration::LayoutImpl::SetLayoutManager.
Dali::Ui::Integration::GridLayoutImpl::GridLayoutImpl()
Referenced by New.
void Dali::Ui::Integration::GridLayoutImpl::AddRowDefinition(GridLength height)
References Dali::Ui::Integration::LayoutImpl::GetLayoutManager, Dali::Ui::Integration::GridLayoutManager::GetRowDefinitions, Dali::Ui::ViewImpl::InvalidateMeasure.
void Dali::Ui::Integration::GridLayoutImpl::AddColumnDefinition(GridLength width)
References Dali::Ui::Integration::GridLayoutManager::GetColumnDefinitions, Dali::Ui::Integration::LayoutImpl::GetLayoutManager, Dali::Ui::ViewImpl::InvalidateMeasure.
void Dali::Ui::Integration::GridLayoutImpl::SetRowDefinitions(const Dali::Vector< GridLength > &rows)
References Dali::Ui::Integration::LayoutImpl::GetLayoutManager, Dali::Ui::ViewImpl::InvalidateMeasure, SetRowDefinitions.
Referenced by ClearRowDefinitions, SetRowDefinitions.
void Dali::Ui::Integration::GridLayoutImpl::SetColumnDefinitions(const Dali::Vector< GridLength > &columns)
References Dali::Ui::Integration::LayoutImpl::GetLayoutManager, Dali::Ui::ViewImpl::InvalidateMeasure, SetColumnDefinitions.
Referenced by ClearColumnDefinitions, SetColumnDefinitions.
Dali::Vector< GridLength > Dali::Ui::Integration::GridLayoutImpl::GetRowDefinitions() const
References Dali::Ui::Integration::LayoutImpl::GetLayoutManager, GetRowDefinitions.
Referenced by GetRowCount, GetRowDefinitions.
Dali::Vector< GridLength > Dali::Ui::Integration::GridLayoutImpl::GetColumnDefinitions() const
References GetColumnDefinitions, Dali::Ui::Integration::LayoutImpl::GetLayoutManager.
Referenced by GetColumnCount, GetColumnDefinitions.
uint32_t Dali::Ui::Integration::GridLayoutImpl::GetRowCount() const
References Dali::Ui::Integration::LayoutImpl::GetLayoutManager, GetRowDefinitions.
uint32_t Dali::Ui::Integration::GridLayoutImpl::GetColumnCount() const
References GetColumnDefinitions, Dali::Ui::Integration::LayoutImpl::GetLayoutManager.
void Dali::Ui::Integration::GridLayoutImpl::ClearRowDefinitions()
References Dali::Ui::Integration::LayoutImpl::GetLayoutManager, Dali::Ui::ViewImpl::InvalidateMeasure, SetRowDefinitions.
void Dali::Ui::Integration::GridLayoutImpl::ClearColumnDefinitions()
References Dali::Ui::Integration::LayoutImpl::GetLayoutManager, Dali::Ui::ViewImpl::InvalidateMeasure, SetColumnDefinitions.
void Dali::Ui::Integration::GridLayoutImpl::SetRowSpacing(float spacing)
References Dali::Ui::Integration::LayoutImpl::GetLayoutManager, Dali::Ui::ViewImpl::InvalidateMeasure, Dali::Ui::Integration::GridLayoutManager::SetRowSpacing, spacing.
float Dali::Ui::Integration::GridLayoutImpl::GetRowSpacing() const
References Dali::Ui::Integration::LayoutImpl::GetLayoutManager, GetRowSpacing.
Referenced by GetRowSpacing.
void Dali::Ui::Integration::GridLayoutImpl::SetColumnSpacing(float spacing)
References Dali::Ui::Integration::LayoutImpl::GetLayoutManager, Dali::Ui::ViewImpl::InvalidateMeasure, Dali::Ui::Integration::GridLayoutManager::SetColumnSpacing, spacing.
float Dali::Ui::Integration::GridLayoutImpl::GetColumnSpacing() const
References GetColumnSpacing, Dali::Ui::Integration::LayoutImpl::GetLayoutManager.
Referenced by GetColumnSpacing.
Dali::Ui::Integration::GridLayoutImpl::GridLayoutImpl(const GridLayoutImpl &)=delete
Dali::Ui::Integration::GridLayoutImpl::GridLayoutImpl(GridLayoutImpl &&)=delete
GridLayoutImpl & Dali::Ui::Integration::GridLayoutImpl::operator=(const GridLayoutImpl &)=delete
GridLayoutImpl & Dali::Ui::Integration::GridLayoutImpl::operator=(GridLayout &&)=delete