Dali::Ui::GridLayoutParams
Dali::Ui::GridLayoutParams::GridLayoutParams()
Creates an uninitialized handle.
Referenced by DownCast, New, New.
Dali::Ui::GridLayoutParams::GridLayoutParams(const GridLayoutParams &handle)
Copy constructor.
handle Handle to copy
Dali::Ui::GridLayoutParams::~GridLayoutParams()
Destructor.
GridLayoutParams & Dali::Ui::GridLayoutParams::SetRow(uint32_t row)
Sets the row index for this child in the grid.
row Zero-based row index Reference to this for chaining
References Dali::Ui::GetImpl.
uint32_t Dali::Ui::GridLayoutParams::GetRow() const
Gets the row index for this child in the grid.
The row index
References Dali::Ui::GetImpl.
GridLayoutParams & Dali::Ui::GridLayoutParams::SetColumn(uint32_t column)
Sets the column index for this child in the grid.
column Zero-based column index Reference to this for chaining
References Dali::Ui::GetImpl.
uint32_t Dali::Ui::GridLayoutParams::GetColumn() const
Gets the column index for this child in the grid.
The column index
References Dali::Ui::GetImpl.
GridLayoutParams & Dali::Ui::GridLayoutParams::SetRowSpan(uint32_t span)
Sets how many rows this child spans.
span Number of rows to span (minimum 1) Reference to this for chaining
References Dali::Ui::GetImpl.
uint32_t Dali::Ui::GridLayoutParams::GetRowSpan() const
Gets how many rows this child spans.
The row span count
References Dali::Ui::GetImpl.
GridLayoutParams & Dali::Ui::GridLayoutParams::SetColumnSpan(uint32_t span)
Sets how many columns this child spans.
span Number of columns to span (minimum 1) Reference to this for chaining
References Dali::Ui::GetImpl.
uint32_t Dali::Ui::GridLayoutParams::GetColumnSpan() const
Gets how many columns this child spans.
The column span count
References Dali::Ui::GetImpl.
GridLayoutParams & Dali::Ui::GridLayoutParams::SetHorizontalAlignment(LayoutAlignment alignment)
Sets the horizontal alignment within the grid cell.
alignment FILL, START, CENTER, or END Reference to this for chaining
References Dali::Ui::GetImpl.
LayoutAlignment Dali::Ui::GridLayoutParams::GetHorizontalAlignment() const
Gets the horizontal alignment.
The horizontal alignment
References Dali::Ui::GetImpl.
GridLayoutParams & Dali::Ui::GridLayoutParams::SetVerticalAlignment(LayoutAlignment alignment)
Sets the vertical alignment within the grid cell.
alignment FILL, START, CENTER, or END Reference to this for chaining
References Dali::Ui::GetImpl.
LayoutAlignment Dali::Ui::GridLayoutParams::GetVerticalAlignment() const
Gets the vertical alignment.
The vertical alignment
References Dali::Ui::GetImpl.
GridLayoutParams Dali::Ui::GridLayoutParams::New()
Creates a new GridLayoutParams with default values.
A handle to a newly allocated GridLayoutParams
References GridLayoutParams.
GridLayoutParams Dali::Ui::GridLayoutParams::New(const GridLayoutParams &other)
Creates a new GridLayoutParams by copying values from an existing one.
other The params to copy from A handle to a newly allocated GridLayoutParams with copied values
References Dali::Ui::GetImpl, GridLayoutParams.
GridLayoutParams Dali::Ui::GridLayoutParams::DownCast(BaseHandle handle)
Downcasts a handle to GridLayoutParams.
handle Handle to an object A valid handle or an uninitialized handle
References GridLayoutParams.
LayoutParamsType Dali::Ui::GridLayoutParams::GetLayoutParamsType()
Returns the layout params type identifier.
LayoutParamsType::GRID
References Dali::Ui::GRID.