Dali::Ui::FlexLayoutParams
Dali::Ui::FlexLayoutParams::FlexLayoutParams()
Creates an uninitialized handle.
Referenced by DownCast, New, New.
Dali::Ui::FlexLayoutParams::FlexLayoutParams(const FlexLayoutParams &handle)
Copy constructor.
handle Handle to copy
Dali::Ui::FlexLayoutParams::~FlexLayoutParams()
Destructor.
FlexLayoutParams & Dali::Ui::FlexLayoutParams::SetFlexGrow(float grow)
Sets the flex grow factor for distributing remaining space.
grow The grow factor (0 means no growing) Reference to this for chaining
References Dali::Ui::GetImpl.
float Dali::Ui::FlexLayoutParams::GetFlexGrow() const
Gets the flex grow factor.
The grow factor
References Dali::Ui::GetImpl.
FlexLayoutParams & Dali::Ui::FlexLayoutParams::SetFlexShrink(float shrink)
Sets the flex shrink factor for distributing negative space.
shrink The shrink factor (1 means proportional shrinking) Reference to this for chaining
References Dali::Ui::GetImpl.
float Dali::Ui::FlexLayoutParams::GetFlexShrink() const
Gets the flex shrink factor.
The shrink factor
References Dali::Ui::GetImpl.
FlexLayoutParams & Dali::Ui::FlexLayoutParams::SetFlexBasis(float basis)
Sets the initial main size of the flex item before grow/shrink.
basis The flex basis value (use WRAP_CONTENT for auto) Reference to this for chaining
References Dali::Ui::GetImpl.
float Dali::Ui::FlexLayoutParams::GetFlexBasis() const
Gets the flex basis value.
The flex basis
References Dali::Ui::GetImpl.
FlexLayoutParams & Dali::Ui::FlexLayoutParams::SetAlignSelf(FlexAlign align)
Sets the cross-axis alignment override for this child.
align The alignment (AUTO defers to parent's alignItems) Reference to this for chaining
References Dali::Ui::GetImpl.
FlexAlign Dali::Ui::FlexLayoutParams::GetAlignSelf() const
Gets the cross-axis alignment override for this child.
The align-self value
References Dali::Ui::GetImpl.
FlexLayoutParams Dali::Ui::FlexLayoutParams::New()
Creates a new FlexLayoutParams with default values.
A handle to a newly allocated FlexLayoutParams
References FlexLayoutParams.
FlexLayoutParams Dali::Ui::FlexLayoutParams::New(const FlexLayoutParams &other)
Creates a new FlexLayoutParams by copying values from an existing one.
other The params to copy from A handle to a newly allocated FlexLayoutParams with copied values
References FlexLayoutParams, Dali::Ui::GetImpl.
FlexLayoutParams Dali::Ui::FlexLayoutParams::DownCast(BaseHandle handle)
Downcasts a handle to FlexLayoutParams.
handle Handle to an object A valid handle or an uninitialized handle
References FlexLayoutParams.
LayoutParamsType Dali::Ui::FlexLayoutParams::GetLayoutParamsType()
Returns the layout params type identifier.
LayoutParamsType::FLEX
References Dali::Ui::FLEX.