Dali::Ui::VisualFactory
CreationOptions
VisualFactory Dali::Ui::VisualFactory::Get()
Create or retrieve VisualFactory singleton.
A handle to the VisualFactory control.
References VisualFactory.
Referenced by Dali::Ui::TextureManager::AddTexture, Dali::Ui::Integration::LabelImpl::OnInitialize, Dali::Ui::TextureManager::RemoveTexture.
Dali::Ui::VisualFactory::VisualFactory()
Create a VisualFactory handle.
Calling member functions with an uninitialised handle is not allowed.
Referenced by Get.
Dali::Ui::VisualFactory::~VisualFactory()
Destructor.
This is non-virtual since derived Handle types must not contain data or virtual methods.
Dali::Ui::VisualFactory::VisualFactory(const VisualFactory &handle)
This copy constructor is required for (smart) pointer semantics.
handle A reference to the copied handle.
VisualFactory & Dali::Ui::VisualFactory::operator=(const VisualFactory &handle)
This assignment operator is required for (smart) pointer semantics.
handle A reference to the copied handle. A reference to this.
Visual::Base Dali::Ui::VisualFactory::CreateVisual(const Property::Map &propertyMap)
Request the visual.
propertyMap The map contains the properties required by the visual. The content of the map determines the type of visual that will be returned. The handle to the created visual
Referenced by Dali::Ui::Integration::LabelImpl::OnInitialize.
Visual::Base Dali::Ui::VisualFactory::CreateVisual(const Property::Map &propertyMap, CreationOptions creationOptions)
Request the visual with some options.
propertyMap The map contains the properties required by the visual. The content of the map determines the type of visual that will be returned. creationOptions The creation option. The handle to the created visual
Visual::Base Dali::Ui::VisualFactory::CreateVisual(const std::string &url, ImageDimensions size)
Request the visual to render the given resource at the url.
url The URL to the resource to be rendered. size The width and height to fit the loaded image to. The pointer pointing to the visual
Visual::Base Dali::Ui::VisualFactory::CreateVisual(const std::string &url, ImageDimensions size, CreationOptions creationOptions)
Request the visual to render the given resource at the url with some options.
url The URL to the resource to be rendered. size The width and height to fit the loaded image to. creationOptions The creation option. The pointer pointing to the visual
Dali::Geometry Dali::Ui::VisualFactory::GetDefaultQuadGeometry()
Get the default quad geometry which general visuals be used.
The default quad geometry for visual factory.
void Dali::Ui::VisualFactory::SetPreMultiplyOnLoad(bool preMultiply)
Enable or disable premultiplying alpha in images and image visuals.
The default is to enable pre-multiplication on load. Applications that have assets with pre-multiplied alpha already applied should turn this option off. preMultiply True if loaded images for image visuals should have alpha multiplied into the color channels.
bool Dali::Ui::VisualFactory::GetPreMultiplyOnLoad() const
Get the setting for automatically pre-multiplying image visual images on load.
True if loaded images have pre-multiplied alpha applied on load, false otherwise.
void Dali::Ui::VisualFactory::SetDefaultCreationOptions(CreationOptions creationOptions)
Set the default creation options when we skip the creation options parameter.
creationOptions The default creation options for the visual factory.
VisualFactory::CreationOptions Dali::Ui::VisualFactory::GetDefaultCreationOptions() const
Get the default creation options when we skip the creation options parameter.
The default creation options for the visual factory.
void Dali::Ui::VisualFactory::DiscardVisual(Visual::Base visual)
Discard visual base. It will keep reference of visual until idle callback called.
visual Discarded visual base.
bool Dali::Ui::VisualFactory::AddPrecompileShader(const Property::Map &map)
Adds a list of pre-compiled shaders to the visual factory.
This function allows you to add the desired precompile shader to the list. you can set it through PropertyMap. you need to know the values for setting well to use them, so please refer to the explanation below. shaderType: Set the desired shader type. dali provides these type: "image","text","color","3d" and "custom" shaderOption: Set the desired shader option. dali provides these flag: dali provides a lot of shader options, so user need to check proper shader option. vertexShader: Set the vertext shader that user want. this is for custom shader. fragmentShader: Set the fragment shader that user want. this is for custom shader. shaderName: if user want to set shader name, use this. this is for custom shader.(optional) (example) // Precompile image and Custom shader // Image Case Property::Map imageShader; imageShader["shaderType"] = "image"; imageShader["shaderOption"] = Property::Map().Add("YUV_AND_RGB", true); imageShader["shaderName"] = "IMAGE_SHADER_ROUNDED_CORNER_YUV_TO_RGB"; // Text Case Property::Map textShader; textShader["shaderType"] = "text"; textShader["shaderOption"] = Property::Map() .Add("MULTI_COLOR", true) .Add("OVERLAY", true); // Color Case Property::Map colorShader; colorShader["shaderType"] = "color"; colorShader["shaderOption"] = Property::Map() .Add("CUTOUT", true) .Add("BORDERLINE", true); // Custom Case Property::Map customShader; customShader["shaderType"] = "custom"; customShader["vertexShader"] = "..."; // input vertexShader code customShader["fragementShader"] = "..."; // input fragementShader code customShader["shaderName"] = "MyCustomShader"; // Add to Precompile Shader VisualFactory factory = VisualFactory::Get(); factory.AddPrecompileShader(imageShader); factory.AddPrecompileShader(textShader); factory.AddPrecompileShader(colorShader); factory.AddPrecompileShader(customShader); factory.UsePreCompiledShader(); If you want to detail information about shader option. please refer to precompil-shader-option.h. map The shader information for precompile True if shader is successfully added to the precompiled list, false otherwise.
void Dali::Ui::VisualFactory::UsePreCompiledShader()
Compile the visual shader in advance. Afterwards, when a visual using a new shader is requested, the pre-compiled shader is used.
It is recommended that this method be called at the top of the application code. Using precompiled shaders is helpful when the application is complex and uses many different styles of visual options. On the other hand,if most visuals are the same and the application is simple, it may use memory unnecessarily or slow down the application launching speed.
Dali::Geometry Dali::Ui::VisualFactory::CreateGridGeometry(Dali::Uint16Pair gridSize, bool normalized)
Create the grid geometry.
This function creates a grid geometry for use in custom controls and visuals. gridSize The size of the grid (number of cells in x and y directions). normalized Make the attribute values normalized as [-0.5f ~ 0.5f]. If false, attribute values have [0 ~ gridSize) integer values (Usually used for NPatch images). The created grid geometry.
Dali::Ui::VisualFactory::VisualFactory(Internal::VisualFactory *impl)