Dali::Ui::Integration::ImageViewImpl
Ui::Visual::Base Dali::Ui::Integration::ImageViewImpl::mVisual
Dali::String Dali::Ui::Integration::ImageViewImpl::mUrl
Dali::String Dali::Ui::Integration::ImageViewImpl::mPlaceholderUrl
Dali::String Dali::Ui::Integration::ImageViewImpl::mAlphaMaskUrl
Vector4 Dali::Ui::Integration::ImageViewImpl::mPixelArea
Vector4 Dali::Ui::Integration::ImageViewImpl::mNPatchBorder
UiColor Dali::Ui::Integration::ImageViewImpl::mImageColor
Ui::SamplingMode::Type Dali::Ui::Integration::ImageViewImpl::mSamplingMode
Ui::FittingMode::Type Dali::Ui::Integration::ImageViewImpl::mFittingMode
Ui::MaskingType::Type Dali::Ui::Integration::ImageViewImpl::mMaskingMode
Ui::LoadPolicy::Type Dali::Ui::Integration::ImageViewImpl::mLoadPolicy
Ui::ReleasePolicy::Type Dali::Ui::Integration::ImageViewImpl::mReleasePolicy
int Dali::Ui::Integration::ImageViewImpl::mDesiredWidth
int Dali::Ui::Integration::ImageViewImpl::mDesiredHeight
int Dali::Ui::Integration::ImageViewImpl::mDepthIndex
bool Dali::Ui::Integration::ImageViewImpl::mPreMultipliedAlpha
bool Dali::Ui::Integration::ImageViewImpl::mImageLoadWithViewSize
bool Dali::Ui::Integration::ImageViewImpl::mCropToMask
bool Dali::Ui::Integration::ImageViewImpl::mSynchronousLoading
bool Dali::Ui::Integration::ImageViewImpl::mFastTrackUploading
bool Dali::Ui::Integration::ImageViewImpl::mOrientationCorrection
bool Dali::Ui::Integration::ImageViewImpl::mNPatchBorderOnly
bool Dali::Ui::Integration::ImageViewImpl::mVisualDirty
Dali::Ui::Integration::ImageViewImpl::ImageViewImpl()
ImageViewImpl constructor.
Referenced by New.
Dali::Ui::Integration::ImageViewImpl::~ImageViewImpl()
A reference counted object may only be deleted by calling Unreference().
ImageViewImplPtr Dali::Ui::Integration::ImageViewImpl::New()
Creates a new ImageViewImpl.
An intrusive pointer to the newly allocated ImageViewImpl
References ImageViewImpl.
Referenced by Dali::Ui::ImageView::New, Dali::Ui::ImageView::New.
void Dali::Ui::Integration::ImageViewImpl::SetResourceUrl(const Dali::String &url)
Sets the resource URL of the image to display.
The image is loaded asynchronously. Use ResourceReadySignal() to be notified when loading completes. url The URL of the image resource Reference to this for fluent chaining
References Dali::Ui::LoadPolicy::IMMEDIATE, Dali::Ui::ViewImpl::InvalidateMeasure.
Dali::String Dali::Ui::Integration::ImageViewImpl::GetResourceUrl() const
Gets the current image URL.
The URL of the image currently set on this view
void Dali::Ui::Integration::ImageViewImpl::Reload()
Reloads the current image from its URL.
Has no effect if no image URL has been set.
References Dali::Ui::Integration::ImageViewImpl::Property::IMAGE, Dali::Ui::DevelImageVisual::Action::RELOAD.
void Dali::Ui::Integration::ImageViewImpl::SetPlaceholderUrl(const Dali::String &url)
Sets the URL of a placeholder image shown while the main image is loading.
url The URL of the placeholder image resource Reference to this for fluent chaining
Dali::String Dali::Ui::Integration::ImageViewImpl::GetPlaceholderUrl() const
Gets the placeholder image URL.
The URL of the placeholder image, or an empty string if not set
void Dali::Ui::Integration::ImageViewImpl::SetImageColor(const UiColor &color)
Sets the color multiplier applied to the image.
Accepts both direct RGBA values and theme color tokens via UiColor. color The color to multiply with the image Reference to this for fluent chaining
References Dali::Ui::Visual::Base::DoAction, Dali::Ui::ViewImpl::InvalidateMeasure, Dali::Ui::Visual::Property::MIX_COLOR, Dali::Ui::UiColor::Resolve, Dali::Ui::DevelVisual::Action::UPDATE_PROPERTY.
UiColor Dali::Ui::Integration::ImageViewImpl::GetImageColor() const
Gets the color multiplier applied to the image.
The current image color
void Dali::Ui::Integration::ImageViewImpl::SetPixelArea(const Vector4 &pixelArea)
Sets the pixel area used to display a sub-region of the image.
The area is specified as normalized coordinates: (x, y, width, height) where each component is in the range [0, 1]. pixelArea The normalized sub-region of the image to display Reference to this for fluent chaining
Vector4 Dali::Ui::Integration::ImageViewImpl::GetPixelArea() const
Gets the pixel area.
The current pixel area as normalized coordinates
void Dali::Ui::Integration::ImageViewImpl::SetSamplingMode(Ui::SamplingMode::Type samplingMode)
Sets the sampling mode used when scaling the image.
samplingMode The sampling mode to use Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Ui::SamplingMode::Type Dali::Ui::Integration::ImageViewImpl::GetSamplingMode() const
Gets the sampling mode.
The current sampling mode
void Dali::Ui::Integration::ImageViewImpl::SetFittingMode(Ui::FittingMode::Type fittingMode)
Sets how the image is fitted within the view bounds.
The default fitting mode is Ui::FittingMode::FILL (stretch to fill). fittingMode The fitting mode to use Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Ui::FittingMode::Type Dali::Ui::Integration::ImageViewImpl::GetFittingMode() const
Gets the fitting mode.
The current fitting mode (default: FILL)
void Dali::Ui::Integration::ImageViewImpl::SetDesiredWidth(int width)
Sets the desired rasterization width as a hint for the image loader.
width The desired width in pixels (0 to use natural size) Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
int Dali::Ui::Integration::ImageViewImpl::GetDesiredWidth() const
Gets the desired rasterization width hint.
The desired width in pixels, or 0 if not set
void Dali::Ui::Integration::ImageViewImpl::SetDesiredHeight(int height)
Sets the desired rasterization height as a hint for the image loader.
height The desired height in pixels (0 to use natural size) Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
int Dali::Ui::Integration::ImageViewImpl::GetDesiredHeight() const
Gets the desired rasterization height hint.
The desired height in pixels, or 0 if not set
void Dali::Ui::Integration::ImageViewImpl::SetImageLoadWithViewSize(bool enabled)
Sets whether the image is loaded synchronously at the current view size.
When enabled, the image is (re)loaded at the view's resolved layout size each time the view size changes. This avoids loading the full-resolution image when only a smaller display size is needed, saving memory and decode time. Direction: view size → image load size. Do NOT use together with aspect-ratio layout on the same ImageView. ImageLoadWithViewSize causes GetNaturalSize to return the current view size instead of the true image dimensions, making aspect-ratio adjustment ineffective. enabled True to enable loading image with view size Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
bool Dali::Ui::Integration::ImageViewImpl::IsImageLoadWithViewSizeEnabled() const
Gets whether the image is loaded with the view size.
True if loading image with view size is enabled
void Dali::Ui::Integration::ImageViewImpl::SetPreMultipliedAlpha(bool preMultiplied)
Sets whether the image uses pre-multiplied alpha.
preMultiplied True if the image has pre-multiplied alpha Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
bool Dali::Ui::Integration::ImageViewImpl::IsPreMultipliedAlpha() const
Gets whether pre-multiplied alpha is enabled.
True if pre-multiplied alpha is enabled
void Dali::Ui::Integration::ImageViewImpl::SetAlphaMaskUrl(const Dali::String &maskUrl)
Sets the URL of an alpha mask image.
When set, the alpha channel of the mask image is applied to the main image. maskUrl The URL of the alpha mask image Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Dali::String Dali::Ui::Integration::ImageViewImpl::GetAlphaMaskUrl() const
Gets the alpha mask image URL.
The URL of the alpha mask image, or an empty string if not set
void Dali::Ui::Integration::ImageViewImpl::SetCropToMask(bool cropToMask)
Sets whether the image should be cropped to the mask bounds.
cropToMask True to crop the image to the mask Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
bool Dali::Ui::Integration::ImageViewImpl::IsCropToMask() const
Gets whether crop-to-mask is enabled.
True if crop-to-mask is enabled
void Dali::Ui::Integration::ImageViewImpl::SetMaskingMode(Ui::MaskingType::Type maskingMode)
Sets the masking mode.
maskingMode The masking mode to use Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Ui::MaskingType::Type Dali::Ui::Integration::ImageViewImpl::GetMaskingMode() const
Gets the masking mode.
The current masking mode
void Dali::Ui::Integration::ImageViewImpl::SetLoadPolicy(Ui::LoadPolicy::Type loadPolicy)
Sets the load policy for the image resource.
Determines whether the image is loaded immediately when the view is created (IMMEDIATE), or deferred until the view is attached to the scene (ATTACHED). loadPolicy The load policy to use Reference to this for fluent chaining
References Dali::Ui::LoadPolicy::IMMEDIATE, Dali::Ui::ViewImpl::InvalidateMeasure.
Ui::LoadPolicy::Type Dali::Ui::Integration::ImageViewImpl::GetLoadPolicy() const
Gets the load policy.
The current load policy
void Dali::Ui::Integration::ImageViewImpl::SetReleasePolicy(Ui::ReleasePolicy::Type releasePolicy)
Sets the release policy for the image resource.
Controls when the image texture is released from memory. releasePolicy The release policy to use Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Ui::ReleasePolicy::Type Dali::Ui::Integration::ImageViewImpl::GetReleasePolicy() const
Gets the release policy.
The current release policy
void Dali::Ui::Integration::ImageViewImpl::SetSynchronousLoading(bool synchronous)
Sets whether the image is loaded synchronously.
synchronous True to load the image on the main thread synchronously Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
bool Dali::Ui::Integration::ImageViewImpl::IsSynchronousLoading() const
Gets whether synchronous loading is enabled.
True if synchronous loading is enabled
void Dali::Ui::Integration::ImageViewImpl::SetFastTrackUpload(bool fastTrack)
Sets whether fast-track uploading is enabled.
When enabled, the image is uploaded to the GPU on a background thread to reduce main-thread stalls. fastTrack True to enable fast-track uploading Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
bool Dali::Ui::Integration::ImageViewImpl::IsFastTrackUploadEnabled() const
Gets whether fast-track uploading is enabled.
True if fast-track uploading is enabled
void Dali::Ui::Integration::ImageViewImpl::SetOrientationCorrection(bool orientationCorrection)
Sets whether EXIF orientation metadata is applied automatically.
orientationCorrection True to apply orientation correction Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
bool Dali::Ui::Integration::ImageViewImpl::IsOrientationCorrectionEnabled() const
Gets whether orientation correction is enabled.
True if orientation correction is enabled
void Dali::Ui::Integration::ImageViewImpl::SetNPatchBorder(const Vector4 &border)
Sets the N-patch border insets.
The border is specified as (left, top, right, bottom) pixel values. Setting a non-zero border activates N-patch rendering. border The border insets as (left, top, right, bottom) Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
Vector4 Dali::Ui::Integration::ImageViewImpl::GetNPatchBorder() const
Gets the N-patch border insets.
The current border as (left, top, right, bottom)
void Dali::Ui::Integration::ImageViewImpl::SetNPatchBorderOnly(bool borderOnly)
Sets whether only the N-patch border regions are rendered.
When enabled, the center region of the N-patch is not rendered. borderOnly True to render only the border regions Reference to this for fluent chaining
References Dali::Ui::ViewImpl::InvalidateMeasure.
bool Dali::Ui::Integration::ImageViewImpl::IsNPatchBorderOnly() const
Gets whether border-only rendering is enabled.
True if only the border regions are rendered
void Dali::Ui::Integration::ImageViewImpl::SetDepthIndex(int depthIndex)
Sets the depth index of the image visual.
The depth index controls the rendering order of visuals within the same layer. Higher values are rendered on top. depthIndex The depth index to assign to the image visual Reference to this for fluent chaining
References Dali::Ui::Integration::ImageViewImpl::Property::IMAGE.
Ui::Visual::ResourceStatus Dali::Ui::Integration::ImageViewImpl::GetLoadingStatus() const
Gets the current loading status of the image.
The current ResourceStatus of the image visual
References Dali::Ui::Integration::ImageViewImpl::Property::IMAGE.
void Dali::Ui::Integration::ImageViewImpl::OnInitialize() override
Called after the actor has been initialized.
MeasuredSize Dali::Ui::Integration::ImageViewImpl::OnMeasure(float widthConstraint, float heightConstraint) override
Called during measure pass. Override to implement custom measurement.
MeasuredSize Dali::Ui::Integration::ImageViewImpl::OnArrange(const LayoutRect &bounds) override
Called during arrange pass. Override to implement custom arrangement.
void Dali::Ui::Integration::ImageViewImpl::UpdateVisual()
Rebuilds and re-registers the image visual from current property values.
void Dali::Ui::Integration::ImageViewImpl::UpdatePlaceholderVisual()
Rebuilds and re-registers the placeholder visual.
void Dali::Ui::Integration::ImageViewImpl::ApplyFittingMode(const Vector2 &size)
Applies the current fitting mode transform to the visual for the given size.
size The allocated size of the view
void Dali::Ui::Integration::ImageViewImpl::OnViewResourceReady(Ui::View view)
Callback invoked when the view's resource becomes ready.
view The view whose resource became ready
Dali::Ui::Integration::ImageViewImpl::ImageViewImpl(const ImageViewImpl &)=delete
Dali::Ui::Integration::ImageViewImpl::ImageViewImpl(ImageViewImpl &&)=delete
ImageViewImpl & Dali::Ui::Integration::ImageViewImpl::operator=(const ImageViewImpl &)=delete
ImageViewImpl & Dali::Ui::Integration::ImageViewImpl::operator=(ImageViewImpl &&)=delete