Dali::Ui::FocusManager
typedef Signal<Actor(Actor, Actor, Ui::FocusDirection)> Dali::Ui::FocusManager::PreFocusChangeSignalType
Pre focus change signal.
typedef Signal<void(Actor, Actor)> Dali::Ui::FocusManager::FocusChangedSignalType
Focus changed signal.
typedef Signal<void(Actor, bool)> Dali::Ui::FocusManager::FocusGroupChangedSignalType
Focus group changed signal.
typedef Signal<void(Actor)> Dali::Ui::FocusManager::FocusedActorEnterKeySignalType
Focused actor has the enter key pressed signal.
Dali::Ui::FocusManager::FocusManager()
Creates a FocusManager handle; this can be initialized with FocusManager::New().
Calling member functions with an uninitialized handle is not allowed.
Dali::Ui::FocusManager::~FocusManager()
Destructor.
This is non-virtual since derived Handle types must not contain data or virtual methods.
bool Dali::Ui::FocusManager::SetCurrentFocusActor(Actor actor)
Moves the focus to the given actor.
Only one actor can be focused at the same time. The actor must be in the stage already and focusable. actor The actor to be focused Whether the focus is successful or not The FocusManager has been initialized. The Actor has been initialized. If the parent of this actor has the KEYBOARD FOCUSABLE CHILDREN property set to false, it will not be focused.
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::ViewAccessible::GrabFocus.
Actor Dali::Ui::FocusManager::GetCurrentFocusActor()
Gets the current focused actor.
A handle to the current focused actor or an empty handle if no actor is focused The FocusManager has been initialized.
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::ViewAccessible::CalculateStates, Dali::Ui::ViewImpl::OnPropertySet.
bool Dali::Ui::FocusManager::MoveFocus(FocusDirection direction)
Moves the focus to the next focusable actor in the focus chain in the given direction (according to the focus traversal order).
direction The direction of focus movement true if the movement was successful The FocusManager has been initialized.
References Dali::Ui::GetImpl.
void Dali::Ui::FocusManager::ClearFocus()
Clears the focus from the current focused actor if any, so that no actor is focused in the focus chain.
It will emit focus changed signal without current focused actor. The FocusManager has been initialized.
References Dali::Ui::GetImpl.
Referenced by Dali::Ui::ViewImpl::OnPropertySet.
void Dali::Ui::FocusManager::SetFocusGroupLoop(bool enabled)
Sets whether the focus movement should be looped within the same focus group.
The focus movement is not looped by default. enabled Whether the focus movement should be looped The FocusManager has been initialized.
References Dali::Ui::GetImpl.
bool Dali::Ui::FocusManager::GetFocusGroupLoop() const
Gets whether the focus movement should be looped within the same focus group.
Whether the focus movement should be looped The FocusManager has been initialized.
References Dali::Ui::GetImpl.
void Dali::Ui::FocusManager::SetAsFocusGroup(Actor actor, bool isFocusGroup)
Sets whether an actor is a focus group that can limit the scope of focus movement to its child actors in the focus chain.
Layout views set themselves as focus groups by default. actor The actor to be set as a focus group isFocusGroup Whether to set the actor as a focus group or not The FocusManager has been initialized. The Actor has been initialized.
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::SetAsFocusGroup.
bool Dali::Ui::FocusManager::IsFocusGroup(Actor actor) const
Checks whether the actor is set as a focus group or not.
actor The actor to be checked Whether the actor is set as a focus group The FocusManager has been initialized. The Actor has been initialized.
References Dali::Ui::GetImpl, Dali::Ui::ViewImpl::IsFocusGroup.
Referenced by Dali::Ui::ViewImpl::IsFocusGroup.
Actor Dali::Ui::FocusManager::GetFocusGroup(Actor actor)
Returns the closest ancestor of the given actor that is a focus group.
actor The actor to be checked for its focus group The focus group the given actor belongs to or an empty handle if the given actor doesn't belong to any focus group
References Dali::Ui::GetImpl.
void Dali::Ui::FocusManager::SetFocusIndicatorActor(View indicator)
Sets the focus indicator actor.
This will replace the default focus indicator actor in FocusManager and will be added to the focused actor as a highlight. indicator The indicator view to be added The FocusManager has been initialized. The indicator view has been initialized.
References Dali::Ui::GetImpl.
Actor Dali::Ui::FocusManager::GetFocusIndicatorActor()
Gets the focus indicator actor.
A handle to the focus indicator actor The FocusManager has been initialized.
References Dali::Ui::GetImpl.
void Dali::Ui::FocusManager::MoveFocusBackward()
Move the focus to prev focused actor.
References Dali::Ui::GetImpl.
FocusDevice Dali::Ui::FocusManager::GetLastFocusChangeDevice() const
Gets the device of the last focus change.
This method returns what caused the most recent focus change, allowing applications to differentiate between different input methods. The device of the last focus change The FocusManager has been initialized.
References Dali::Ui::GetImpl.
const Dali::String & Dali::Ui::FocusManager::GetLastFocusChangeDeviceName() const
Gets the device name that caused the last focus change.
This method returns the name of the input device that caused the most recent focus change. For non-device inputs (like programmatic focus changes), an empty string may be returned. The device name that caused the last focus change The FocusManager has been initialized.
References Dali::Ui::GetImpl.
void Dali::Ui::FocusManager::SetClearFocusOnWindowFocusLost(bool enabled)
Sets whether to clear focus when window loses focus.
By default, this is enabled. When disabled, the focus state is preserved even when the window loses focus, enabled Whether to clear focus when window loses focus
References Dali::Ui::GetImpl.
bool Dali::Ui::FocusManager::GetClearFocusOnWindowFocusLost() const
Gets whether to clear focus when window loses focus.
Whether clear focus is enabled when window loses focus
References Dali::Ui::GetImpl.
FocusManager::PreFocusChangeSignalType & Dali::Ui::FocusManager::PreFocusChangeSignal()
This signal is emitted before the focus is going to be changed.
FocusManager makes the best guess for which actor to focus towards the given direction, but applications might want to change that. By connecting with this signal, they can check the proposed actor to focus and return a different actor if they wish. This signal is only emitted when the navigation key is pressed and FocusManager tries to move the focus automatically. It won't be emitted for focus movement by calling SetCurrentFocusActor directly. A callback of the following type may be connected: ActorYourCallbackName(ActorcurrentFocusedActor,ActorproposedActorToFocus,FocusDirection::Directiondirection); The signal to connect to The Object has been initialized.
References Dali::Ui::GetImpl.
FocusManager::FocusChangedSignalType & Dali::Ui::FocusManager::FocusChangedSignal()
This signal is emitted after the current focused actor has been changed.
A callback of the following type may be connected: voidYourCallbackName(ActororiginalFocusedActor,ActorcurrentFocusedActor); The signal to connect to The Object has been initialized.
References Dali::Ui::ViewImpl::FocusChangedSignal, Dali::Ui::GetImpl.
FocusManager::FocusGroupChangedSignalType & Dali::Ui::FocusManager::FocusGroupChangedSignal()
This signal is emitted when the focus group has been changed.
If the current focus group has a parent layout view, FocusManager will make the best guess for the next focus group to move the focus to in the given direction (forward or backward). If not, the application has to set the new focus. A callback of the following type may be connected: voidYourCallbackName(ActorcurrentFocusedActor,boolforward); The signal to connect to The Object has been initialized.
References Dali::Ui::GetImpl.
FocusManager::FocusedActorEnterKeySignalType & Dali::Ui::FocusManager::FocusedActorEnterKeySignal()
This signal is emitted when the current focused actor has the enter key pressed on it.
A callback of the following type may be connected: voidYourCallbackName(ActorenterPressedActor); The signal to connect to The Object has been initialized.
References Dali::Ui::GetImpl.
FocusManager Dali::Ui::FocusManager::Get()
Gets the singleton of FocusManager object.
A handle to the FocusManager view
Referenced by Dali::Ui::ViewAccessible::CalculateStates, Dali::Ui::ViewAccessible::GrabFocus, Dali::Ui::ViewImpl::IsFocusGroup, Dali::Ui::ViewImpl::OnAccessibilityActivated, Dali::Ui::Integration::UiConfigImpl::OnApplicationCreated, Dali::Ui::ViewImpl::OnFocusChanged, Dali::Ui::ViewImpl::OnPropertySet.