Dali::Ui
InputEventType
The input event is originated from the manual API call.
KeyClickPolicy
Trigger click when the key is released.
LayoutAlignment
Fill the available space.
LayoutMode
Managed by the parent container's layout (default).
StackOrientation
Vertical stacking (top to bottom)
FlexDirection
Left to right.
FlexWrap
No wrapping.
FlexJustify
Align to start.
FlexAlign
Auto alignment.
GridLengthType
Absolute pixel value.
AbsoluteLayoutFlags
No flags set.
LayoutParamsType
ScrollDirection
Vertical scrolling only.
ScrollBarVisibility
Show scroll bar only when scrolling.
ScrollToPosition
Scroll to start of view.
OverScrollMode
Never allow over-scrolling.
ConstraintTagRanges
AccessibilityState
AccessibilityRole
FocusDirection
Move keyboard focus towards the left direction.
FocusDevice
Unknown device.
CornerRadiusPolicy
Relative to the view size (percentage [0.0, 0.5] of the shorter side)
LayoutOrderPolicy
Also reorder layout children to match the new sibling order.
WebViewScrollEdge
Left edge reached.
WebViewOverScrolled
Left over-scrolled.
WebViewFindOption
DevelPropertyRanges
Layout Group Property Start Index.
OverlayHighlightMode
using Dali::Ui::MeasureCallback = typedef Callback<MeasuredSize(View, float, float)>
Move-only callback for custom layout measurement.
view.SetMeasureCallback(MeasureCallback::New(this,&MyClass::OnMeasure)); Signature: MeasuredSize(View view, float widthConstraint, float heightConstraint)
using Dali::Ui::ArrangeCallback = typedef Callback<MeasuredSize(View, const LayoutRect&)>
Move-only callback for custom layout arrangement.
view.SetArrangeCallback(ArrangeCallback::New(this,&MyClass::OnArrange)); Signature: MeasuredSize(View view, const LayoutRect& bounds)
using Dali::Ui::ColorOverrideFunc = typedef bool (*)(StringView colorId, Vector4& outColor)
Function pointer type for overriding theme color lookups.
When registered via SetColorOverride(), this function is called before querying the theme loader for every color lookup. If the function returns true, the output color is used and the theme loader is skipped. If it returns false, the normal theme lookup proceeds. colorId The color identifier being looked up outColor The overridden RGBA value (only used when returning true) true if the color is overridden, false to fall through to the theme
using Dali::Ui::ColorCallback = typedef Callback<void(const Vector4&)>
Typed callback for applying a resolved color to a View.
Pass to UpdateBinding() to register a binding between a UiColor and a View. manager.UpdateBinding(color,view,ColorCallback::New(this,&MyImpl::SetColor));
using Dali::Ui::ExecutionKeyPredicate = typedef bool (*)(const Dali::String& keyName)
Function pointer type for determining whether a key triggers click execution.
keyName The name of the key True if the key should trigger click execution
using Dali::Ui::ViewImplPtr = typedef IntrusivePtr<ViewImpl>
using Dali::Ui::StringGetterDelegate = typedef void (*)(void* obj, const char* propertyName, std::string* result)
using Dali::Ui::AccessibilityStates = typedef Accessibility::EnumBitSet<AccessibilityState, AccessibilityState::MAX_COUNT>
constexpr float Dali::Ui::WRAP_CONTENT
Constant representing wrap-content sizing.
When RequestedWidth or RequestedHeight is set to this value (the default), the View sizes to fit its content (natural size or children bounding box).
Referenced by Dali::Ui::Integration::StackLayoutManager::ArrangeChildren, Dali::Ui::Integration::InputFieldImpl::InvalidateTextMeasure, Dali::Ui::Integration::LabelImpl::InvalidateTextMeasure, Dali::Ui::Integration::LabelImpl::OnMeasure.
constexpr float Dali::Ui::MATCH_PARENT
Constant representing match-parent sizing.
When RequestedWidth or RequestedHeight is set to this value, the View fills the parent container's available space on that axis.
Referenced by Dali::Ui::Integration::AbsoluteLayoutManager::ArrangeChildren, Dali::Ui::Integration::ScrollViewLayoutManager::ArrangeChildren, Dali::Ui::Integration::StackLayoutManager::ArrangeChildren, Dali::Ui::Integration::GridLayoutManager::Measure, Dali::Ui::Integration::ScrollViewLayoutManager::Measure, Dali::Ui::Integration::StackLayoutManager::Measure, Dali::Ui::ViewImpl::OnArrange, Dali::Ui::ViewImpl::OnMeasure, Dali::Ui::Integration::InputFieldImpl::OnMeasure, Dali::Ui::Integration::LabelImpl::OnMeasure, Dali::Ui::Integration::LayoutImpl::OnMeasure.
constexpr const uint32_t Dali::Ui::ROLE_START_INDEX
Integration::AnimatedImageViewImpl & Dali::Ui::GetImpl(AnimatedImageView &animatedImageView)
Referenced by Dali::Ui::Builder::AddActors, Dali::Ui::Builder::AddActors, Dali::Ui::GridLayout::AddColumnDefinition, Dali::Ui::Builder::AddConstant, Dali::Ui::Builder::AddConstants, Dali::Ui::WebView::AddCustomHeader, Dali::Ui::WebView::AddJavaScriptMessageHandler, Dali::Ui::GridLayout::AddRowDefinition, Dali::Ui::Label::AnchorClickedSignal, Dali::Ui::AnimatedImageView::AnimationFinishedSignal, Dali::Ui::LottieAnimationView::AnimationFinishedSignal, Dali::Ui::Builder::ApplyFromJson, Dali::Ui::Builder::ApplyStyle, Dali::Ui::View::Arrange, Dali::Ui::Integration::AbsoluteLayoutManager::ArrangeChildren, Dali::Ui::Integration::FlexLayoutManager::ArrangeChildren, Dali::Ui::Integration::GridLayoutManager::ArrangeChildren, Dali::Ui::Integration::ScrollViewLayoutManager::ArrangeChildren, Dali::Ui::Integration::StackLayoutManager::ArrangeChildren, Dali::Ui::Label::AsyncHeightForWidthComputedSignal, Dali::Ui::Label::AsyncNaturalSizeComputedSignal, Dali::Ui::Label::AsyncRenderFinishedSignal, Dali::Ui::WebView::CanGoBack, Dali::Ui::WebView::CanGoForward, Dali::Ui::WebView::CheckVideoPlayingAsynchronously, Dali::Ui::WebView::ClearAllTilesResources, Dali::Ui::View::ClearBackground, Dali::Ui::Label::ClearBevel, Dali::Ui::UiColorManager::ClearBinding, Dali::Ui::UiColorManager::ClearBindings, Dali::Ui::UiColorManager::ClearColorOverride, Dali::Ui::GridLayout::ClearColumnDefinitions, Dali::Ui::FocusManager::ClearFocus, Dali::Ui::InputField::ClearFontVariation, Dali::Ui::Label::ClearFontVariation, Dali::Ui::WebView::ClearHistory, Dali::Ui::InputField::ClearLineThrough, Dali::Ui::Label::ClearLineThrough, Dali::Ui::Label::ClearMaskEffect, Dali::Ui::InputField::ClearOutline, Dali::Ui::Label::ClearOutline, Dali::Ui::View::ClearRenderEffect, Dali::Ui::GridLayout::ClearRowDefinitions, Dali::Ui::InputField::ClearShadow, Dali::Ui::Label::ClearShadow, Dali::Ui::InputField::ClearTextBackgroundColor, Dali::Ui::Label::ClearTextBackgroundColor, Dali::Ui::Label::ClearTextFit, Dali::Ui::InputField::ClearUnderline, Dali::Ui::Label::ClearUnderline, Dali::Ui::InteractiveTrait::ClickedSignal, Dali::Ui::InteractiveView::ClickedSignal, Dali::Ui::Builder::Create, Dali::Ui::Builder::Create, Dali::Ui::Builder::CreateAnimation, Dali::Ui::Builder::CreateAnimation, Dali::Ui::Builder::CreateAnimation, Dali::Ui::Builder::CreateAnimation, Dali::Ui::Builder::CreateFromJson, Dali::Ui::Builder::CreateRenderTask, Dali::Ui::Integration::UiConfigManagerImpl::CreateThemeLoader, Dali::Ui::Integration::UiConfigManager::CreateThemeLoader, Dali::Ui::InputField::CursorPositionChangedSignal, Dali::Ui::ViewAccessible::DoGesture, Dali::Ui::ScrollView::DragFinishedSignal, Dali::Ui::ScrollView::DraggingSignal, Dali::Ui::ScrollView::DragStartedSignal, Dali::Ui::DevelFocusManager::EnableDefaultAlgorithm, Dali::Ui::UiConfig::EnableFocusClearOnEscape, Dali::Ui::DevelFocusManager::EnableFocusIndicator, Dali::Ui::Integration::InteractiveViewImpl::EnableLongPressDetection, Dali::Ui::SelectableTrait::EnableToggleByClick, Dali::Ui::View::EnsureInteractiveTrait, Dali::Ui::View::EnsureSelectableTrait, Dali::Ui::WebView::EvaluateJavaScript, Dali::Ui::WebView::EvaluateJavaScript, Dali::Ui::WebView::ExitFullscreen, Dali::Ui::WebView::FeedMouseWheel, Dali::Ui::FocusManager::FocusChangedSignal, Dali::Ui::View::FocusChangedSignal, Dali::Ui::FocusManager::FocusedActorEnterKeySignal, Dali::Ui::FocusManager::FocusGroupChangedSignal, Dali::Ui::WebView::FrameRenderedSignal, Dali::Ui::WebView::FullscreenEnteredSignal, Dali::Ui::WebView::FullscreenExitedSignal, Dali::Ui::WebView::GeolocationPermissionSignal, Dali::Ui::Integration::UiConfigManager::Get, Dali::Ui::InputField::GetAdjustedFontSizeScale, Dali::Ui::Label::GetAdjustedFontSizeScale, Dali::Ui::FlexLayout::GetAlignContent, Dali::Ui::FlexLayout::GetAlignItems, Dali::Ui::StackLayoutParams::GetAlignment, Dali::Ui::FlexLayoutParams::GetAlignSelf, Dali::Ui::AnimatedImageView::GetAlphaMaskUrl, Dali::Ui::ImageView::GetAlphaMaskUrl, Dali::Ui::Label::GetAnchorClickedColor, Dali::Ui::Label::GetAnchorColor, Dali::Ui::Label::GetAsyncLineCount, Dali::Ui::View::GetBackgroundColor, Dali::Ui::UiConfig::GetBaselineDpi, Dali::Ui::AnimatedImageView::GetBatchSize, Dali::Ui::UiColorManager::GetBindingColor, Dali::Ui::View::GetBorderlineColor, Dali::Ui::View::GetBorderlineOffset, Dali::Ui::View::GetBorderlineWidth, Dali::Ui::AbsoluteLayoutParams::GetBounds, Dali::Ui::UiConfig::GetBrokenImageUrl, Dali::Ui::AnimatedImageView::GetCacheSize, Dali::Ui::StateEvent::GetCause, Dali::Ui::View::GetChildAt, Dali::Ui::View::GetChildCount, Dali::Ui::FocusManager::GetClearFocusOnWindowFocusLost, Dali::Ui::UiColorManager::GetColor, Dali::Ui::UiColorManager::GetColor, Dali::Ui::GridLayoutParams::GetColumn, Dali::Ui::GridLayout::GetColumnCount, Dali::Ui::GridLayout::GetColumnDefinitions, Dali::Ui::GridLayout::GetColumnSpacing, Dali::Ui::GridLayoutParams::GetColumnSpan, Dali::Ui::Integration::UiConfigManager::GetConfig, Dali::Ui::Builder::GetConfigurations, Dali::Ui::Builder::GetConstant, Dali::Ui::Builder::GetConstants, Dali::Ui::ScrollView::GetContent, Dali::Ui::LottieAnimationView::GetContentInfo, Dali::Ui::WebView::GetContentSize, Dali::Ui::View::GetCornerRadius, Dali::Ui::View::GetCornerRadiusPolicy, Dali::Ui::View::GetCornerSquareness, Dali::Ui::StateEvent::GetCurrent, Dali::Ui::FocusManager::GetCurrentFocusActor, Dali::Ui::AnimatedImageView::GetCurrentFrame, Dali::Ui::LottieAnimationView::GetCurrentFrame, Dali::Ui::UiThemeManager::GetCurrentThemeId, Dali::Ui::InputField::GetCursorBlinkInterval, Dali::Ui::InputField::GetCursorColor, Dali::Ui::InputField::GetCursorPosition, Dali::Ui::InputField::GetCursorWidth, Dali::Ui::ScrollView::GetDecelerationRate, Dali::Ui::UiConfig::GetDefaultFontSize, Dali::Ui::UiConfig::GetDefaultInteractionEffect, Dali::Ui::UiConfig::GetDefaultPlaceholderTextColor, Dali::Ui::UiConfig::GetDefaultTextColor, Dali::Ui::ViewAccessible::GetDescription, Dali::Ui::AnimatedImageView::GetDesiredHeight, Dali::Ui::ImageView::GetDesiredHeight, Dali::Ui::LottieAnimationView::GetDesiredHeight, Dali::Ui::AnimatedImageView::GetDesiredWidth, Dali::Ui::ImageView::GetDesiredWidth, Dali::Ui::LottieAnimationView::GetDesiredWidth, Dali::Ui::FlexLayout::GetDirection, Dali::Ui::UiConfig::GetDpi, Dali::Ui::UiConfig::GetDpiFactor, Dali::Ui::UiConfig::GetExecutionKeyPredicate, Dali::Ui::WebView::GetFavicon, Dali::Ui::AnimatedImageView::GetFittingMode, Dali::Ui::ImageView::GetFittingMode, Dali::Ui::AbsoluteLayoutParams::GetFlags, Dali::Ui::FlexLayoutParams::GetFlexBasis, Dali::Ui::FlexLayoutParams::GetFlexGrow, Dali::Ui::FlexLayoutParams::GetFlexShrink, Dali::Ui::ScrollView::GetFlingSensitivity, Dali::Ui::FocusManager::GetFocusGroup, Dali::Ui::FocusManager::GetFocusGroupLoop, Dali::Ui::FocusManager::GetFocusIndicatorActor, Dali::Ui::InputField::GetFontFamily, Dali::Ui::Label::GetFontFamily, Dali::Ui::InputField::GetFontSize, Dali::Ui::Label::GetFontSize, Dali::Ui::InputField::GetFontSizeScale, Dali::Ui::Label::GetFontSizeScale, Dali::Ui::InputField::GetFontSlant, Dali::Ui::Label::GetFontSlant, Dali::Ui::InputField::GetFontVariation, Dali::Ui::Label::GetFontVariation, Dali::Ui::InputField::GetFontWeight, Dali::Ui::Label::GetFontWeight, Dali::Ui::InputField::GetFontWidth, Dali::Ui::Label::GetFontWidth, Dali::Ui::AnimatedImageView::GetFrameDelay, Dali::Ui::AnimatedImageView::GetFrameSpeedFactor, Dali::Ui::LottieAnimationView::GetFrameSpeedFactor, Dali::Ui::AbsoluteLayoutParams::GetHeight, Dali::Ui::GridLayoutParams::GetHorizontalAlignment, Dali::Ui::ScrollView::GetHorizontalScrollBarVisibility, Dali::Ui::InputField::GetHorizontalTextAlignment, Dali::Ui::Label::GetHorizontalTextAlignment, Dali::Ui::AnimatedImageView::GetImageColor, Dali::Ui::ImageView::GetImageColor, Dali::Ui::LottieAnimationView::GetImageColor, Dali::Ui::InputEvent::GetInputEventType, Dali::Ui::StateEvent::GetInputEventType, Dali::Ui::FlexLayout::GetJustifyContent, Dali::Ui::InteractiveTrait::GetKeyClickPolicy, Dali::Ui::InteractiveView::GetKeyClickPolicy, Dali::Ui::UiConfig::GetKeyClickPolicy, Dali::Ui::InputEvent::GetKeyEvent, Dali::Ui::StateEvent::GetKeyEvent, Dali::Ui::WebView::GetKeyEventsEnabled, Dali::Ui::UiConfig::GetKeyLongPressThreshold, Dali::Ui::FocusManager::GetLastFocusChangeDevice, Dali::Ui::FocusManager::GetLastFocusChangeDeviceName, Dali::Ui::InputField::GetLayoutDirectionMode, Dali::Ui::Label::GetLayoutDirectionMode, Dali::Ui::View::GetLayoutMode, Dali::Ui::Builder::GetLinearConstrainer, Dali::Ui::Label::GetLineCount, Dali::Ui::Label::GetLineCount, Dali::Ui::Label::GetLineHeight, Dali::Ui::Label::GetLineHeightMode, Dali::Ui::Label::GetLineWrapMode, Dali::Ui::AnimatedImageView::GetLoadingStatus, Dali::Ui::ImageView::GetLoadingStatus, Dali::Ui::LottieAnimationView::GetLoadingStatus, Dali::Ui::AnimatedImageView::GetLoadPolicy, Dali::Ui::ImageView::GetLoadPolicy, Dali::Ui::WebView::GetLoadProgressPercentage, Dali::Ui::InputEvent::GetLongPressGesture, Dali::Ui::StateEvent::GetLongPressGesture, Dali::Ui::AnimatedImageView::GetLoopCount, Dali::Ui::LottieAnimationView::GetLoopCount, Dali::Ui::LottieAnimationView::GetLoopingMode, Dali::Ui::View::GetMargin, Dali::Ui::LottieAnimationView::GetMarkerInfo, Dali::Ui::Label::GetMarqueeGap, Dali::Ui::UiConfig::GetMarqueeGap, Dali::Ui::Label::GetMarqueeLoopCount, Dali::Ui::UiConfig::GetMarqueeLoopCount, Dali::Ui::Label::GetMarqueeLoopDelay, Dali::Ui::UiConfig::GetMarqueeLoopDelay, Dali::Ui::Label::GetMarqueeOrientation, Dali::Ui::UiConfig::GetMarqueeOrientation, Dali::Ui::Label::GetMarqueeSpeed, Dali::Ui::UiConfig::GetMarqueeSpeed, Dali::Ui::Label::GetMarqueeStopMode, Dali::Ui::UiConfig::GetMarqueeStopMode, Dali::Ui::Label::GetMarqueeTriggerPolicy, Dali::Ui::AnimatedImageView::GetMaskingMode, Dali::Ui::ImageView::GetMaskingMode, Dali::Ui::ScrollView::GetMaxFlingDistance, Dali::Ui::ScrollView::GetMaximumFlingDuration, Dali::Ui::InputField::GetMaximumFontSizeScale, Dali::Ui::Label::GetMaximumFontSizeScale, Dali::Ui::View::GetMaximumHeight, Dali::Ui::InputField::GetMaximumLength, Dali::Ui::View::GetMaximumWidth, Dali::Ui::View::GetMeasuredSize, Dali::Ui::ScrollView::GetMinimumFlingDuration, Dali::Ui::InputField::GetMinimumFontSizeScale, Dali::Ui::Label::GetMinimumFontSizeScale, Dali::Ui::View::GetMinimumHeight, Dali::Ui::View::GetMinimumWidth, Dali::Ui::WebView::GetMouseEventsEnabled, Dali::Ui::View::GetName, Dali::Ui::ViewAccessible::GetName, Dali::Ui::ImageView::GetNPatchBorder, Dali::Ui::View::GetOpacity, Dali::Ui::StackLayout::GetOrientation, Dali::Ui::InputField::GetOverflowMode, Dali::Ui::Label::GetOverflowMode, Dali::Ui::ScrollView::GetOverScrollMode, Dali::Ui::View::GetPadding, Dali::Ui::WebView::GetPageZoomFactor, Dali::Ui::View::GetParentOrigin, Dali::Ui::Builder::GetPath, Dali::Ui::Builder::GetPathConstrainer, Dali::Ui::View::GetPivot, Dali::Ui::AnimatedImageView::GetPixelArea, Dali::Ui::ImageView::GetPixelArea, Dali::Ui::InputField::GetPlaceholder, Dali::Ui::InputField::GetPlaceholderColor, Dali::Ui::AnimatedImageView::GetPlaceholderUrl, Dali::Ui::ImageView::GetPlaceholderUrl, Dali::Ui::LottieAnimationView::GetPlaceholderUrl, Dali::Ui::WebView::GetPlainTextAsynchronously, Dali::Ui::AnimatedImageView::GetPlayState, Dali::Ui::LottieAnimationView::GetPlayState, Dali::Ui::View::GetPositionX, Dali::Ui::View::GetPositionY, Dali::Ui::StateEvent::GetPrev, Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty, Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty, Dali::Ui::ViewAccessible::GetRelationSet, Dali::Ui::AnimatedImageView::GetReleasePolicy, Dali::Ui::ImageView::GetReleasePolicy, Dali::Ui::LottieAnimationView::GetReleasePolicy, Dali::Ui::View::GetRenderEffect, Dali::Ui::Label::GetRenderScale, Dali::Ui::LottieAnimationView::GetRenderScale, Dali::Ui::View::GetRequestedHeight, Dali::Ui::View::GetRequestedWidth, Dali::Ui::AnimatedImageView::GetResourceUrl, Dali::Ui::ImageView::GetResourceUrl, Dali::Ui::LottieAnimationView::GetResourceUrl, Dali::Ui::AnimatedImageView::GetResourceUrls, Dali::Ui::GridLayoutParams::GetRow, Dali::Ui::GridLayout::GetRowCount, Dali::Ui::GridLayout::GetRowDefinitions, Dali::Ui::GridLayout::GetRowSpacing, Dali::Ui::GridLayoutParams::GetRowSpan, Dali::Ui::AnimatedImageView::GetSamplingMode, Dali::Ui::ImageView::GetSamplingMode, Dali::Ui::UiConfig::GetScaledDpiFactor, Dali::Ui::WebView::GetScaleFactor, Dali::Ui::View::GetScaleX, Dali::Ui::View::GetScaleY, Dali::Ui::UiConfig::GetScalingFactor, Dali::Ui::WebView::GetScreenshot, Dali::Ui::WebView::GetScreenshotAsynchronously, Dali::Ui::ScrollView::GetScrollDirection, Dali::Ui::ScrollView::GetScrollPosition, Dali::Ui::WebView::GetScrollPosition, Dali::Ui::WebView::GetScrollSize, Dali::Ui::WebView::GetSelectedText, Dali::Ui::InputField::GetSelectionColor, Dali::Ui::View::GetSize, Dali::Ui::StackLayout::GetSpacing, Dali::Ui::View::GetState, Dali::Ui::AnimatedImageView::GetStopBehavior, Dali::Ui::LottieAnimationView::GetStopBehavior, Dali::Ui::InputEvent::GetTapGesture, Dali::Ui::StateEvent::GetTapGesture, Dali::Ui::UiConfig::GetTapRecognizerTime, Dali::Ui::InputField::GetText, Dali::Ui::Label::GetText, Dali::Ui::InputField::GetTextBackgroundColor, Dali::Ui::Label::GetTextBackgroundColor, Dali::Ui::InputField::GetTextColor, Dali::Ui::Label::GetTextColor, Dali::Ui::WebView::GetTextZoomFactor, Dali::Ui::WebView::GetTitle, Dali::Ui::AnimatedImageView::GetTotalFrame, Dali::Ui::LottieAnimationView::GetTotalFrame, Dali::Ui::InputEvent::GetTouchEvent, Dali::Ui::StateEvent::GetTouchEvent, Dali::Ui::ImageUrl::GetUrl, Dali::Ui::WebView::GetUrl, Dali::Ui::WebView::GetUserAgent, Dali::Ui::GridLayoutParams::GetVerticalAlignment, Dali::Ui::ScrollView::GetVerticalScrollBarVisibility, Dali::Ui::InputField::GetVerticalTextAlignment, Dali::Ui::Label::GetVerticalTextAlignment, Dali::Ui::WebView::GetVideoHoleEnabled, Dali::Ui::StackLayoutParams::GetWeight, Dali::Ui::InputEvent::GetWheelEvent, Dali::Ui::StateEvent::GetWheelEvent, Dali::Ui::AbsoluteLayoutParams::GetWidth, Dali::Ui::FlexLayout::GetWrap, Dali::Ui::AbsoluteLayoutParams::GetX, Dali::Ui::AbsoluteLayoutParams::GetY, Dali::Ui::WebView::GoBack, Dali::Ui::WebView::GoForward, Dali::Ui::UiColorManager::HasBinding, Dali::Ui::View::IndexOfChild, Dali::Ui::Integration::UiConfigManagerImpl::Initialize, Dali::Ui::Integration::UiConfigManager::Initialize, Dali::Ui::View::Insert, Dali::Ui::ViewImpl::InvalidateArrange, Dali::Ui::View::InvalidateArrange, Dali::Ui::ViewImpl::InvalidateMeasure, Dali::Ui::View::InvalidateMeasure, Dali::Ui::Label::IsAsyncRendering, Dali::Ui::InteractiveTrait::IsClickable, Dali::Ui::InteractiveView::IsClickable, Dali::Ui::View::IsCornerRadiusPolicyRelative, Dali::Ui::AnimatedImageView::IsCropToMask, Dali::Ui::ImageView::IsCropToMask, Dali::Ui::InputField::IsCursorBlinkEnabled, Dali::Ui::Label::IsCutoutEnabled, Dali::Ui::DevelFocusManager::IsDefaultAlgorithmEnabled, Dali::Ui::View::IsEffectivelyEnabled, Dali::Ui::View::IsEffectivelyFocused, Dali::Ui::View::IsEnabled, Dali::Ui::ImageView::IsFastTrackUploadEnabled, Dali::Ui::View::IsFocusable, Dali::Ui::UiConfig::IsFocusClearOnEscapeEnabled, Dali::Ui::FocusManager::IsFocusGroup, Dali::Ui::UiConfig::IsFocusIndicatorAlwaysShown, Dali::Ui::DevelFocusManager::IsFocusIndicatorEnabled, Dali::Ui::LottieAnimationView::IsFrameCacheEnabled, Dali::Ui::ViewAccessible::IsHidden, Dali::Ui::AnimatedImageView::IsImageLoadWithViewSizeEnabled, Dali::Ui::ImageView::IsImageLoadWithViewSizeEnabled, Dali::Ui::Integration::UiConfigManager::IsInitialized, Dali::Ui::View::IsInteractive, Dali::Ui::UiConfig::IsLabelAsyncRendering, Dali::Ui::Label::IsMarkupEnabled, Dali::Ui::Label::IsMarqueeRunning, Dali::Ui::Label::IsMultiLine, Dali::Ui::LottieAnimationView::IsNotifyAfterRasterizationEnabled, Dali::Ui::ImageView::IsNPatchBorderOnly, Dali::Ui::View::IsOnScene, Dali::Ui::ImageView::IsOrientationCorrectionEnabled, Dali::Ui::InputField::IsPlaceholderShownOnFocus, Dali::Ui::UiConfig::IsPlaceholderTextShownOnFocus, Dali::Ui::AnimatedImageView::IsPreMultipliedAlpha, Dali::Ui::ImageView::IsPreMultipliedAlpha, Dali::Ui::LottieAnimationView::IsPreMultipliedAlpha, Dali::Ui::InteractiveTrait::IsPressed, Dali::Ui::InteractiveView::IsPressed, Dali::Ui::InteractiveTrait::IsPseudoDisabled, Dali::Ui::InteractiveView::IsPseudoDisabled, Dali::Ui::LottieAnimationView::IsRedrawOnScaleDown, Dali::Ui::LottieAnimationView::IsRedrawOnScaleUp, Dali::Ui::View::IsResourceReady, Dali::Ui::ScrollView::IsScrolling, Dali::Ui::View::IsSelectable, Dali::Ui::SelectableTrait::IsSelected, Dali::Ui::AnimatedImageView::IsSynchronousLoading, Dali::Ui::ImageView::IsSynchronousLoading, Dali::Ui::LottieAnimationView::IsSynchronousLoading, Dali::Ui::InputField::IsSystemFontSizeScaleEnabled, Dali::Ui::Label::IsSystemFontSizeScaleEnabled, Dali::Ui::SelectableTrait::IsToggleByClickEnabled, Dali::Ui::View::IsTouchFocusable, Dali::Ui::View::IsVisible, Dali::Ui::WebView::JavaScriptAlertReply, Dali::Ui::WebView::JavaScriptConfirmReply, Dali::Ui::WebView::JavaScriptPromptReply, Dali::Ui::AnimatedImageView::JumpToFrame, Dali::Ui::LottieAnimationView::JumpToFrame, Dali::Ui::View::KeyEventSignal, Dali::Ui::WebView::LoadContents, Dali::Ui::Builder::LoadFromString, Dali::Ui::WebView::LoadHtmlString, Dali::Ui::WebView::LoadHtmlStringOverrideCurrentEntry, Dali::Ui::WebView::LoadUrl, Dali::Ui::InteractiveTrait::LongPressedSignal, Dali::Ui::InteractiveView::LongPressedSignal, Dali::Ui::View::Lower, Dali::Ui::ViewImpl::Lower, Dali::Ui::ViewImpl::LowerBelow, Dali::Ui::View::LowerBelow, Dali::Ui::View::LowerToBottom, Dali::Ui::ViewImpl::LowerToBottom, Dali::Ui::InputField::MaximumLengthReachedSignal, Dali::Ui::View::Measure, Dali::Ui::Integration::AbsoluteLayoutManager::Measure, Dali::Ui::Integration::FlexLayoutManager::Measure, Dali::Ui::Integration::GridLayoutManager::Measure, Dali::Ui::Integration::ScrollViewLayoutManager::Measure, Dali::Ui::Integration::StackLayoutManager::Measure, Dali::Ui::FocusManager::MoveFocus, Dali::Ui::DevelFocusManager::MoveFocus, Dali::Ui::FocusManager::MoveFocusBackward, Dali::Ui::AbsoluteLayoutParams::New, Dali::Ui::FlexLayoutParams::New, Dali::Ui::GridLayoutParams::New, Dali::Ui::StackLayoutParams::New, Dali::Ui::View::OffScreenRenderingFinishedSignal, Dali::Ui::Integration::UiConfigImpl::OnApplicationCreated, Dali::Ui::Integration::UiConfigManagerImpl::OnApplicationCreated, Dali::Ui::ViewImpl::OnArrange, Dali::Ui::Integration::ExclusiveTraitImpl::OnBeforeAttached, Dali::Ui::ViewImpl::OnChildAdd, Dali::Ui::ViewImpl::OnChildRemove, Dali::Ui::Integration::InteractiveTraitImpl::OnClicked, Dali::Ui::ViewImpl::OnFocusChanged, Dali::Ui::Integration::InputFieldImpl::OnInitialize, Dali::Ui::Integration::LabelImpl::OnInitialize, Dali::Ui::Integration::InteractiveTraitImpl::OnLongPressed, Dali::Ui::ViewImpl::OnMeasure, Dali::Ui::Integration::InteractiveTraitImpl::OnPressedChanged, Dali::Ui::WebView::OverScrolledSignal, Dali::Ui::WebView::PageLoadFinishedSignal, Dali::Ui::WebView::PageLoadInProgressSignal, Dali::Ui::WebView::PageLoadStartedSignal, Dali::Ui::AnimatedImageView::Pause, Dali::Ui::LottieAnimationView::Pause, Dali::Ui::AnimatedImageView::Play, Dali::Ui::LottieAnimationView::Play, Dali::Ui::FocusManager::PreFocusChangeSignal, Dali::Ui::InteractiveTrait::PressedChangedSignal, Dali::Ui::InteractiveView::PressedChangedSignal, Dali::Ui::InteractiveTrait::PseudoDisabledChangedSignal, Dali::Ui::InteractiveView::PseudoDisabledChangedSignal, Dali::Ui::Builder::QuitSignal, Dali::Ui::View::Raise, Dali::Ui::ViewImpl::Raise, Dali::Ui::ViewImpl::RaiseAbove, Dali::Ui::View::RaiseAbove, Dali::Ui::View::RaiseToTop, Dali::Ui::ViewImpl::RaiseToTop, Dali::Ui::UiColorManager::RegisterBinding, Dali::Ui::WebView::RegisterJavaScriptAlertCallback, Dali::Ui::WebView::RegisterJavaScriptConfirmCallback, Dali::Ui::WebView::RegisterJavaScriptPromptCallback, Dali::Ui::ViewAccessible::RegisterPositionPropertyNotification, Dali::Ui::ViewAccessible::RegisterPropertySetSignal, Dali::Ui::ImageView::Reload, Dali::Ui::WebView::Reload, Dali::Ui::WebView::ReloadWithoutCache, Dali::Ui::ViewImpl::RemoveAllChildren, Dali::Ui::View::RemoveAllChildren, Dali::Ui::WebView::RemoveCustomHeader, Dali::Ui::Label::RequestAsyncHeightForWidth, Dali::Ui::Label::RequestAsyncNaturalSize, Dali::Ui::DevelFocusManager::ResetFocusFinderRootActor, Dali::Ui::View::ResourceReadySignal, Dali::Ui::WebView::Resume, Dali::Ui::WebView::ResumeNetworkLoading, Dali::Ui::WebView::ScrollBy, Dali::Ui::WebView::ScrollEdgeBy, Dali::Ui::WebView::ScrollEdgeReachedSignal, Dali::Ui::ScrollView::ScrollFinishedSignal, Dali::Ui::ScrollView::ScrollingSignal, Dali::Ui::ScrollView::ScrollStartedSignal, Dali::Ui::ScrollView::ScrollTo, Dali::Ui::ScrollView::ScrollTo, Dali::Ui::ScrollView::ScrollToX, Dali::Ui::ScrollView::ScrollToY, Dali::Ui::SelectableTrait::SelectionChangedSignal, Dali::Ui::FlexLayout::SetAlignContent, Dali::Ui::FlexLayout::SetAlignItems, Dali::Ui::StackLayoutParams::SetAlignment, Dali::Ui::FlexLayoutParams::SetAlignSelf, Dali::Ui::AnimatedImageView::SetAlphaMaskUrl, Dali::Ui::ImageView::SetAlphaMaskUrl, Dali::Ui::UiConfig::SetAlwaysShowFocus, Dali::Ui::Label::SetAnchorClickedColor, Dali::Ui::Label::SetAnchorColor, Dali::Ui::View::SetArrangeCallback, Dali::Ui::FocusManager::SetAsFocusGroup, Dali::Ui::Label::SetAsyncRendering, Dali::Ui::View::SetBackgroundColor, Dali::Ui::UiConfig::SetBaselineDpi, Dali::Ui::AnimatedImageView::SetBatchSize, Dali::Ui::Label::SetBevel, Dali::Ui::UiColorManager::SetBindingColor, Dali::Ui::View::SetBorderlineColor, Dali::Ui::View::SetBorderlineOffset, Dali::Ui::View::SetBorderlineWidth, Dali::Ui::AbsoluteLayoutParams::SetBounds, Dali::Ui::UiConfig::SetBrokenImageUrl, Dali::Ui::AnimatedImageView::SetCacheSize, Dali::Ui::FocusManager::SetClearFocusOnWindowFocusLost, Dali::Ui::InteractiveTrait::SetClickable, Dali::Ui::InteractiveView::SetClickable, Dali::Ui::UiColorManager::SetColorOverride, Dali::Ui::GridLayoutParams::SetColumn, Dali::Ui::GridLayout::SetColumnDefinitions, Dali::Ui::GridLayout::SetColumnSpacing, Dali::Ui::GridLayoutParams::SetColumnSpan, Dali::Ui::ScrollView::SetContent, Dali::Ui::View::SetCornerRadius, Dali::Ui::View::SetCornerRadius, Dali::Ui::View::SetCornerRadius, Dali::Ui::View::SetCornerRadiusPolicy, Dali::Ui::View::SetCornerRadiusPolicyRelative, Dali::Ui::View::SetCornerSquareness, Dali::Ui::View::SetCornerSquareness, Dali::Ui::View::SetCornerSquareness, Dali::Ui::AnimatedImageView::SetCropToMask, Dali::Ui::ImageView::SetCropToMask, Dali::Ui::FocusManager::SetCurrentFocusActor, Dali::Ui::InputField::SetCursorBlinkEnabled, Dali::Ui::InputField::SetCursorBlinkInterval, Dali::Ui::InputField::SetCursorColor, Dali::Ui::WebView::SetCursorEnabledByClient, Dali::Ui::InputField::SetCursorPosition, Dali::Ui::InputField::SetCursorWidth, Dali::Ui::DevelFocusManager::SetCustomAlgorithm, Dali::Ui::Label::SetCutoutEnabled, Dali::Ui::ScrollView::SetDecelerationRate, Dali::Ui::UiConfig::SetDefaultFontSize, Dali::Ui::UiConfig::SetDefaultInteractionEffect, Dali::Ui::UiConfig::SetDefaultPlaceholderTextColor, Dali::Ui::UiConfig::SetDefaultTextColor, Dali::Ui::AnimatedImageView::SetDepthIndex, Dali::Ui::ImageView::SetDepthIndex, Dali::Ui::LottieAnimationView::SetDepthIndex, Dali::Ui::AnimatedImageView::SetDesiredHeight, Dali::Ui::ImageView::SetDesiredHeight, Dali::Ui::LottieAnimationView::SetDesiredHeight, Dali::Ui::AnimatedImageView::SetDesiredWidth, Dali::Ui::ImageView::SetDesiredWidth, Dali::Ui::LottieAnimationView::SetDesiredWidth, Dali::Ui::FlexLayout::SetDirection, Dali::Ui::WebView::SetDocumentBackgroundColor, Dali::Ui::UiConfig::SetDpi, Dali::Ui::LottieAnimationView::SetDynamicProperty, Dali::Ui::View::SetEnabled, Dali::Ui::LottieAnimationView::SetEnableFrameCache, Dali::Ui::UiConfig::SetExecutionKeyPredicate, Dali::Ui::ImageView::SetFastTrackUpload, Dali::Ui::AnimatedImageView::SetFittingMode, Dali::Ui::ImageView::SetFittingMode, Dali::Ui::AbsoluteLayoutParams::SetFlags, Dali::Ui::FlexLayoutParams::SetFlexBasis, Dali::Ui::FlexLayoutParams::SetFlexGrow, Dali::Ui::FlexLayoutParams::SetFlexShrink, Dali::Ui::ScrollView::SetFlingSensitivity, Dali::Ui::View::SetFocusable, Dali::Ui::DevelFocusManager::SetFocusFinderRootActor, Dali::Ui::FocusManager::SetFocusGroupLoop, Dali::Ui::FocusManager::SetFocusIndicatorActor, Dali::Ui::InputField::SetFontFamily, Dali::Ui::Label::SetFontFamily, Dali::Ui::InputField::SetFontSize, Dali::Ui::Label::SetFontSize, Dali::Ui::InputField::SetFontSizeScale, Dali::Ui::Label::SetFontSizeScale, Dali::Ui::InputField::SetFontSlant, Dali::Ui::Label::SetFontSlant, Dali::Ui::InputField::SetFontVariation, Dali::Ui::Label::SetFontVariation, Dali::Ui::InputField::SetFontVariation, Dali::Ui::Label::SetFontVariation, Dali::Ui::InputField::SetFontWeight, Dali::Ui::Label::SetFontWeight, Dali::Ui::InputField::SetFontWidth, Dali::Ui::Label::SetFontWidth, Dali::Ui::AnimatedImageView::SetFrameDelay, Dali::Ui::AnimatedImageView::SetFrameSpeedFactor, Dali::Ui::LottieAnimationView::SetFrameSpeedFactor, Dali::Ui::AbsoluteLayoutParams::SetHeight, Dali::Ui::GridLayoutParams::SetHorizontalAlignment, Dali::Ui::ScrollView::SetHorizontalScrollBarVisibility, Dali::Ui::InputField::SetHorizontalTextAlignment, Dali::Ui::Label::SetHorizontalTextAlignment, Dali::Ui::AnimatedImageView::SetImageColor, Dali::Ui::ImageView::SetImageColor, Dali::Ui::LottieAnimationView::SetImageColor, Dali::Ui::AnimatedImageView::SetImageLoadWithViewSize, Dali::Ui::ImageView::SetImageLoadWithViewSize, Dali::Ui::View::SetInteractionEffect, Dali::Ui::FlexLayout::SetJustifyContent, Dali::Ui::InteractiveTrait::SetKeyClickPolicy, Dali::Ui::InteractiveView::SetKeyClickPolicy, Dali::Ui::UiConfig::SetKeyClickPolicy, Dali::Ui::WebView::SetKeyEventsEnabled, Dali::Ui::UiConfig::SetKeyLongPressThreshold, Dali::Ui::UiConfig::SetLabelAsyncRendering, Dali::Ui::InputField::SetLayoutDirectionMode, Dali::Ui::Label::SetLayoutDirectionMode, Dali::Ui::View::SetLayoutMode, Dali::Ui::View::SetLayoutParams, Dali::Ui::ViewImpl::SetLayoutParams, Dali::Ui::Label::SetLineHeight, Dali::Ui::Label::SetLineHeightMode, Dali::Ui::InputField::SetLineThrough, Dali::Ui::Label::SetLineThrough, Dali::Ui::Label::SetLineWrapMode, Dali::Ui::AnimatedImageView::SetLoadPolicy, Dali::Ui::ImageView::SetLoadPolicy, Dali::Ui::AnimatedImageView::SetLoopCount, Dali::Ui::LottieAnimationView::SetLoopCount, Dali::Ui::LottieAnimationView::SetLoopingMode, Dali::Ui::View::SetMargin, Dali::Ui::Label::SetMarkupEnabled, Dali::Ui::UiConfig::SetMarqueeGap, Dali::Ui::Label::SetMarqueeGap, Dali::Ui::Label::SetMarqueeLoopCount, Dali::Ui::UiConfig::SetMarqueeLoopCount, Dali::Ui::Label::SetMarqueeLoopDelay, Dali::Ui::UiConfig::SetMarqueeLoopDelay, Dali::Ui::Label::SetMarqueeOrientation, Dali::Ui::UiConfig::SetMarqueeOrientation, Dali::Ui::Label::SetMarqueeSpeed, Dali::Ui::UiConfig::SetMarqueeSpeed, Dali::Ui::Label::SetMarqueeStopMode, Dali::Ui::UiConfig::SetMarqueeStopMode, Dali::Ui::Label::SetMarqueeTriggerPolicy, Dali::Ui::Label::SetMaskEffect, Dali::Ui::AnimatedImageView::SetMaskingMode, Dali::Ui::ImageView::SetMaskingMode, Dali::Ui::ScrollView::SetMaxFlingDistance, Dali::Ui::ScrollView::SetMaximumFlingDuration, Dali::Ui::InputField::SetMaximumFontSizeScale, Dali::Ui::Label::SetMaximumFontSizeScale, Dali::Ui::View::SetMaximumHeight, Dali::Ui::InputField::SetMaximumLength, Dali::Ui::View::SetMaximumWidth, Dali::Ui::View::SetMeasureCallback, Dali::Ui::ScrollView::SetMinimumFlingDuration, Dali::Ui::InputField::SetMinimumFontSizeScale, Dali::Ui::Label::SetMinimumFontSizeScale, Dali::Ui::View::SetMinimumHeight, Dali::Ui::View::SetMinimumWidth, Dali::Ui::LottieAnimationView::SetMinMaxFrame, Dali::Ui::LottieAnimationView::SetMinMaxFrameByMarker, Dali::Ui::WebView::SetMouseEventsEnabled, Dali::Ui::Label::SetMultiLine, Dali::Ui::View::SetName, Dali::Ui::LottieAnimationView::SetNotifyAfterRasterization, Dali::Ui::ImageView::SetNPatchBorder, Dali::Ui::ImageView::SetNPatchBorderOnly, Dali::Ui::View::SetOpacity, Dali::Ui::StackLayout::SetOrientation, Dali::Ui::ImageView::SetOrientationCorrection, Dali::Ui::InputField::SetOutline, Dali::Ui::Label::SetOutline, Dali::Ui::InputField::SetOverflowMode, Dali::Ui::Label::SetOverflowMode, Dali::Ui::ScrollView::SetOverScrollMode, Dali::Ui::View::SetPadding, Dali::Ui::WebView::SetPageZoomFactor, Dali::Ui::View::SetParentOrigin, Dali::Ui::View::SetPivot, Dali::Ui::AnimatedImageView::SetPixelArea, Dali::Ui::ImageView::SetPixelArea, Dali::Ui::InputField::SetPlaceholder, Dali::Ui::InputField::SetPlaceholderColor, Dali::Ui::AnimatedImageView::SetPlaceholderUrl, Dali::Ui::ImageView::SetPlaceholderUrl, Dali::Ui::LottieAnimationView::SetPlaceholderUrl, Dali::Ui::View::SetPositionX, Dali::Ui::View::SetPositionY, Dali::Ui::AnimatedImageView::SetPreMultipliedAlpha, Dali::Ui::ImageView::SetPreMultipliedAlpha, Dali::Ui::LottieAnimationView::SetPreMultipliedAlpha, Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty, Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty, Dali::Ui::Integration::InteractiveTraitImpl::SetPseudoDisabled, Dali::Ui::InteractiveTrait::SetPseudoDisabled, Dali::Ui::InteractiveView::SetPseudoDisabled, Dali::Ui::LottieAnimationView::SetRedrawOnScaleDown, Dali::Ui::LottieAnimationView::SetRedrawOnScaleUp, Dali::Ui::AnimatedImageView::SetReleasePolicy, Dali::Ui::ImageView::SetReleasePolicy, Dali::Ui::LottieAnimationView::SetReleasePolicy, Dali::Ui::View::SetRenderEffect, Dali::Ui::Label::SetRenderScale, Dali::Ui::LottieAnimationView::SetRenderScale, Dali::Ui::View::SetRequestedHeight, Dali::Ui::View::SetRequestedWidth, Dali::Ui::AnimatedImageView::SetResourceUrl, Dali::Ui::ImageView::SetResourceUrl, Dali::Ui::LottieAnimationView::SetResourceUrl, Dali::Ui::AnimatedImageView::SetResourceUrls, Dali::Ui::GridLayoutParams::SetRow, Dali::Ui::GridLayout::SetRowDefinitions, Dali::Ui::GridLayout::SetRowSpacing, Dali::Ui::GridLayoutParams::SetRowSpan, Dali::Ui::AnimatedImageView::SetSamplingMode, Dali::Ui::ImageView::SetSamplingMode, Dali::Ui::WebView::SetScaleFactor, Dali::Ui::View::SetScaleX, Dali::Ui::View::SetScaleY, Dali::Ui::UiConfig::SetScalingFactor, Dali::Ui::ScrollView::SetScrollDirection, Dali::Ui::ScrollView::SetScrollPosition, Dali::Ui::SelectableTrait::SetSelected, Dali::Ui::InputField::SetSelectionColor, Dali::Ui::InputField::SetShadow, Dali::Ui::Label::SetShadow, Dali::Ui::InputField::SetShowPlaceholderOnFocus, Dali::Ui::UiConfig::SetShowPlaceholderTextOnFocus, Dali::Ui::StackLayout::SetSpacing, Dali::Ui::AnimatedImageView::SetStopBehavior, Dali::Ui::LottieAnimationView::SetStopBehavior, Dali::Ui::AnimatedImageView::SetSynchronousLoading, Dali::Ui::ImageView::SetSynchronousLoading, Dali::Ui::LottieAnimationView::SetSynchronousLoading, Dali::Ui::InputField::SetSystemFontSizeScaleEnabled, Dali::Ui::Label::SetSystemFontSizeScaleEnabled, Dali::Ui::UiConfig::SetTapRecognizerTime, Dali::Ui::InputField::SetText, Dali::Ui::Label::SetText, Dali::Ui::InputField::SetTextBackgroundColor, Dali::Ui::Label::SetTextBackgroundColor, Dali::Ui::InputField::SetTextColor, Dali::Ui::Label::SetTextColor, Dali::Ui::Label::SetTextFit, Dali::Ui::Label::SetTextFit, Dali::Ui::WebView::SetTextZoomFactor, Dali::Ui::WebView::SetTileCoverAreaMultiplier, Dali::Ui::WebView::SetTilesClearedWhenHidden, Dali::Ui::View::SetTouchFocusable, Dali::Ui::InputField::SetUnderline, Dali::Ui::Label::SetUnderline, Dali::Ui::WebView::SetUserAgent, Dali::Ui::GridLayoutParams::SetVerticalAlignment, Dali::Ui::ScrollView::SetVerticalScrollBarVisibility, Dali::Ui::InputField::SetVerticalTextAlignment, Dali::Ui::Label::SetVerticalTextAlignment, Dali::Ui::WebView::SetVideoHoleEnabled, Dali::Ui::View::SetVisibility, Dali::Ui::StackLayoutParams::SetWeight, Dali::Ui::AbsoluteLayoutParams::SetWidth, Dali::Ui::FlexLayout::SetWrap, Dali::Ui::AbsoluteLayoutParams::SetX, Dali::Ui::AbsoluteLayoutParams::SetY, Dali::Ui::Label::StartMarquee, Dali::Ui::View::StateChangedSignal, Dali::Ui::AnimatedImageView::Stop, Dali::Ui::LottieAnimationView::Stop, Dali::Ui::WebView::StopLoading, Dali::Ui::Label::StopMarquee, Dali::Ui::WebView::Suspend, Dali::Ui::WebView::SuspendNetworkLoading, Dali::Ui::InputField::TextChangedSignal, Dali::Ui::WebView::TextFoundSignal, Dali::Ui::UiThemeManager::ThemeChangedSignal, Dali::Ui::ViewAccessible::UnregisterPositionPropertyNotification, Dali::Ui::ViewAccessible::UnregisterPropertySetSignal, Dali::Ui::ViewImpl::UnsetStateHandler, Dali::Ui::ViewImpl::UnsetStateHandlerWhenNotProcessing, Dali::Ui::WebView::UrlChangedSignal, Dali::Ui::WebView::WebProcessCrashedSignal, Dali::Ui::ViewImpl::~ViewImpl.
const Integration::AnimatedImageViewImpl & Dali::Ui::GetImpl(const AnimatedImageView &animatedImageView)
constexpr Duration Dali::Ui::operator""_ms(unsigned long long value)
User-defined literal for milliseconds (integer).
Durationd=300_ms;//0.3seconds
constexpr Duration Dali::Ui::operator""_ms(long double value)
User-defined literal for milliseconds (floating-point).
Durationd=300.0_ms;//0.3seconds
constexpr Duration Dali::Ui::operator""_s(unsigned long long value)
User-defined literal for seconds (integer).
Durationd=2_s;//2.0seconds
constexpr Duration Dali::Ui::operator""_s(long double value)
User-defined literal for seconds (floating-point).
Durationd=1.5_s;//1.5seconds
Integration::ImageViewImpl & Dali::Ui::GetImpl(ImageView &imageView)
const Integration::ImageViewImpl & Dali::Ui::GetImpl(const ImageView &imageView)
Integration::InputFieldImpl & Dali::Ui::GetImpl(InputField &inputField)
const Integration::InputFieldImpl & Dali::Ui::GetImpl(const InputField &inputField)
Integration::LabelImpl & Dali::Ui::GetImpl(Label &label)
const Integration::LabelImpl & Dali::Ui::GetImpl(const Label &label)
AbsoluteLayoutFlags Dali::Ui::operator|(AbsoluteLayoutFlags lhs, AbsoluteLayoutFlags rhs)
Bitwise OR operator for AbsoluteLayoutFlags.
AbsoluteLayoutFlags Dali::Ui::operator&(AbsoluteLayoutFlags lhs, AbsoluteLayoutFlags rhs)
Bitwise AND operator for AbsoluteLayoutFlags.
Integration::LottieAnimationViewImpl & Dali::Ui::GetImpl(LottieAnimationView &lottieAnimationView)
const Integration::LottieAnimationViewImpl & Dali::Ui::GetImpl(const LottieAnimationView &lottieAnimationView)
Integration::ScrollViewImpl & Dali::Ui::GetImpl(ScrollView &scrollView)
const Integration::ScrollViewImpl & Dali::Ui::GetImpl(const ScrollView &scrollView)
DALI_UI_API float Dali::Ui::operator""_spx(unsigned long long int v)
Converts an integer spx value to a float pixel value.
The input value is multiplied by a scaling-factor configured via UiConfig. UiConfigManager::Init() must have been called before using this operator. An assertion failure is triggered if UiConfig has not been initialized. Do NOT use this operator to initialize static or global variables. Static initialization order is undefined across translation units, so UiConfigManager::Init() may not have been called yet at that point. Use lazy initialization or compute values at first access instead. v The value in spx (e.g. 35_spx) The calculated physical pixels as a float.
References Dali::Ui::Integration::UiConfigManager::Get, Dali::Ui::Integration::UiConfigManager::GetConfig, Dali::Ui::UiConfig::GetScalingFactor.
DALI_UI_API float Dali::Ui::operator""_spx(long double v)
Converts a floating-point spx value to a float pixel value.
The input value is multiplied by a scaling-factor configured via UiConfig. UiConfigManager::Init() must have been called before using this operator. An assertion failure is triggered if UiConfig has not been initialized. Do NOT use this operator to initialize static or global variables. Static initialization order is undefined across translation units, so UiConfigManager::Init() may not have been called yet at that point. Use lazy initialization or compute values at first access instead. v The value in spx (e.g. 35.0_spx) The calculated physical pixels as a float.
References Dali::Ui::Integration::UiConfigManager::Get, Dali::Ui::Integration::UiConfigManager::GetConfig, Dali::Ui::UiConfig::GetScalingFactor.
DALI_UI_API float Dali::Ui::operator""_dp(unsigned long long int v)
Converts an integer dp value to a float pixel value.
The input value is computed with dpi and baseline-dpi configured via UiConfig. UiConfigManager::Init() must have been called before using this operator. An assertion failure is triggered if UiConfig has not been initialized. Do NOT use this operator to initialize static or global variables. Static initialization order is undefined across translation units, so UiConfigManager::Init() may not have been called yet at that point. Use lazy initialization or compute values at first access instead. v The value in dp (e.g. 35_dp) The calculated physical pixels as a float.
References Dali::Ui::Integration::UiConfigManager::Get, Dali::Ui::Integration::UiConfigManager::GetConfig, Dali::Ui::UiConfig::GetDpiFactor.
DALI_UI_API float Dali::Ui::operator""_dp(long double v)
Converts a floating-point dp value to a float pixel value.
The input value is computed with dpi and baseline-dpi configured via UiConfig. UiConfigManager::Init() must have been called before using this operator. An assertion failure is triggered if UiConfig has not been initialized. Do NOT use this operator to initialize static or global variables. Static initialization order is undefined across translation units, so UiConfigManager::Init() may not have been called yet at that point. Use lazy initialization or compute values at first access instead. v The value in dp (e.g. 35.0_dp) The calculated physical pixels as a float.
References Dali::Ui::Integration::UiConfigManager::Get, Dali::Ui::Integration::UiConfigManager::GetConfig, Dali::Ui::UiConfig::GetDpiFactor.
DALI_UI_API float Dali::Ui::operator""_sdp(unsigned long long int v)
Converts an integer sdp value to a float pixel value.
The input value is computed with dpi, baseline-dpi and scaling-factor configured via UiConfig. UiConfigManager::Init() must have been called before using this operator. An assertion failure is triggered if UiConfig has not been initialized. Do NOT use this operator to initialize static or global variables. Static initialization order is undefined across translation units, so UiConfigManager::Init() may not have been called yet at that point. Use lazy initialization or compute values at first access instead. v The value in sdp (e.g. 35_sdp) The calculated physical pixels as a float.
References Dali::Ui::Integration::UiConfigManager::Get, Dali::Ui::Integration::UiConfigManager::GetConfig, Dali::Ui::UiConfig::GetScaledDpiFactor.
DALI_UI_API float Dali::Ui::operator""_sdp(long double v)
Converts a floating-point sdp value to a float pixel value.
The input value is computed with dpi, baseline-dpi and scaling-factor configured via UiConfig. UiConfigManager::Init() must have been called before using this operator. An assertion failure is triggered if UiConfig has not been initialized. Do NOT use this operator to initialize static or global variables. Static initialization order is undefined across translation units, so UiConfigManager::Init() may not have been called yet at that point. Use lazy initialization or compute values at first access instead. v The value in sdp (e.g. 35.0_sdp) The calculated physical pixels as a float.
References Dali::Ui::Integration::UiConfigManager::Get, Dali::Ui::Integration::UiConfigManager::GetConfig, Dali::Ui::UiConfig::GetScaledDpiFactor.
DALI_UI_API ViewImpl & Dali::Ui::GetImpl(Ui::View &view)
DALI_UI_API const ViewImpl & Dali::Ui::GetImpl(const Ui::View &view)
DALI_UI_API void Dali::Ui::PropertyBridgeRegisterStringGetter(StringGetterDelegate getter)
Register String Getter.
DALI_UI_API Property::Map Dali::Ui::CreateAlphaDiscardEffect()
Creates a new Alpha discard effect.
Alpha discard effect is used to discard fragments when the alpha colour value is below a threshold. This is useful for stenciling. Usage example: ImageView actor = ImageView::New( EXAMPLE_IMAGE_PATH ); Property::Map alphaDiscardEffect = CreateAlphaDiscardEffect(); actor.SetProperty( ImageView::Property::IMAGE, alphaDiscardEffect ); A property map of the required shaders.
References Dali::Ui::Visual::Shader::Property::FRAGMENT_SHADER, Dali::Ui::Visual::Property::SHADER.
DALI_UI_API void Dali::Ui::DissolveEffectSetCentralLine(Actor &actor, const Vector2 &position, const Vector2 &displacement, float initialProgress)
Set the dissolve central line.
Use one point (position) and one direction ( displacement ) vector to define this line As we use the texture coordinate as pixel position to calculate random offset, the line should passing through rectangle {(0,0),(0,1),(1,0),(1,1)}, so make the position parameter with two component values between 0.0 to 1.0 actor The actor that registers the uniform properties position The point ( locates within rectangle {(0,0),(0,1),(1,0),(1,1)} ) passed through by the central line displacement The direction of the central line initialProgress The normalised initial progress of the shader
DALI_UI_API Property::Map Dali::Ui::CreateDissolveEffect(bool useHighPrecision=true)
Create a new Dissolve effect.
DissolveEffect is a custom shader effect to achieve Dissolve effects in image views. Animatable/Constrainable uniforms: "uPercentage" - This value is proportional to the distortion applied; a value of zero means no distortion. useHighPrecision True if using high precision in fragment shader for fully random noise, false otherwise The newly created Property::Map with the dissolve effect
References Dali::Ui::Visual::Shader::Property::FRAGMENT_SHADER, Dali::Ui::Visual::Shader::Property::HINTS, Dali::Ui::Visual::Property::SHADER, Dali::Ui::Visual::Shader::Property::SUBDIVIDE_GRID_X, Dali::Ui::Visual::Shader::Property::SUBDIVIDE_GRID_Y, Dali::Ui::Visual::Shader::Property::VERTEX_SHADER.
DALI_UI_API Dali::Property::Map Dali::Ui::CreateDistanceFieldEffect()
Creates a new DistanceFieldEffect DistanceFieldEffect is a custom shader effect to achieve distance field on Image actors Animatable/Constrainable uniforms - These will need to be registered to the actor as a custom property to take into effect: "uDoGlow" - The glow state. If true, glow is enabled "uGlowBoundary" - The glow boundary factor "uGlowColor" - The glow color multiplier "uDoShadow" - The shadow state. If true, shadows is enabled. Cannot be used with glow/and or outline "uShadowColor" - The shadow color multiplier "uShadowOffset" - The shadow offset "uDoOutline" - The outline state. If true, outline is enabled "uOutlineColor" - The outline color multiplier "uOutlineParams"- Thickness of outline. The outline thickness is determined by two values. First value [0-1] Specifies the distance field value for the center of the outline. Second value [0-1] Specifies the softness/width/anti-aliasing of the outlines inner edge. The newly created Property::Map with the distance field effect
References Dali::Ui::Visual::Shader::Property::FRAGMENT_SHADER, Dali::Ui::Visual::Shader::Property::HINTS, Dali::Ui::Visual::Property::SHADER.
DALI_UI_API Property::Map Dali::Ui::CreateImageRegionEffect()
Creates a new ImageRegionEffect.
ImageRegionEffect is a custom shader effect to show only a region of an Image actor. Animatable/Constrainable uniforms: "uTopLeft" - The top-left corner of the image region. The coordinates are in percentage, (0,0) being the top-left and (1,1) the bottom right of the original image "uBottomRight" - The bottom-right corner of the image region. The coordinates are in percentage, (0,0) being the top-left and (1,1) the bottom right of the original image A property map of the required shader
References Dali::Ui::Visual::Property::SHADER, Dali::Ui::Visual::Shader::Property::VERTEX_SHADER.
DALI_UI_API void Dali::Ui::SetMotionBlurProperties(Actor &actor, unsigned int numBlurSamples=8)
Set the properties for the motion blur.
actor The actor that registers the uniform properties numBlurSamples Number of samples used by the shader
DALI_UI_API Property::Map Dali::Ui::CreateMotionBlurEffect()
Create a new MotionBlurEffect.
Motion blur shader works on a per object basis. Objects will blur when they move, or if the camera moves. Animatable/Constrainable uniforms: "uBlurTexCoordScale" - This scales the offset for texture samples along the motion velocity vector. A smaller value means the samples will be spaced closer, larger value further apart. User should use this to get the blur to look contiguous, i.e. the blur texels should not be too widely spread, with gaps in between. Default 0.125. "uGeometryStretchFactor" - This scales the amount the geometry stretches backwards along the motion velocity vector. A smaller value means the geometry stretches less, larger it stretches more. User should use this to get the blur to 'bleed' into areas outside the physical bounds of the actor. We need this as the blur is only applied inside the bounds of the actor, but you would expect motion blur trails where the actor was previously but is there no longer. Default 0.05. "uSpeedScalingFactor" - This takes the magnitude of the motion velocity vector and scales it to produce a value which is used to fade the blur in / out with the speed that the actor is moving. As the blur fades in, more of the blur is visible and less of the original actor, and viceversa. This value is also used to control how much to fade the actor near the edges, based on the speed the actor is moving. When the actor is at rest this is not applied. Default 0.5. "uObjectFadeStart" - The displacement from the centre of the actor that the actor will start to fade towards its edges. This is used to prevent an unsightly hard edge between the blurred actor and the scene. Depends on the values of the vertices in the vertex stream. When the actor is at rest this is not applied. Default 0.25, which is half way towards the edge for an ImageVisual::QUAD. "uObjectFadeEnd" - The displacement from the centre of the actor that the actor will finish fading towards its edges. This is used to prevent an unsightly hard edge between the blurred actor and the scene. Depends on the values of the vertices in the vertex stream. When the actor is at rest this is not applied.Default 0.5, which is all the way towards the edge for an ImageVisual::QUAD. "uAlphaScale" - Global scaler applied to the alpha of the actor. Used to make the blurred actor a bit more subtle (helps to hide discontinuities due to limited number of texture samples) and reveal a bit of the background behind it as it moves. When the actor is at rest this is not applied. Default 0.75. "uNumSamples" - The number of texture samples to be taken. Increasing the number of samples provides better quality at the cost of performance. "uModelLastFrame" - The model to world space transformation matrix of the actor in the previous frame. The newly created Property::Map with the motion blur effect
References Dali::Ui::Visual::Shader::Property::FRAGMENT_SHADER, Dali::Ui::Visual::Shader::Property::HINTS, Dali::Ui::Visual::Property::SHADER, Dali::Ui::Visual::Shader::Property::SUBDIVIDE_GRID_X, Dali::Ui::Visual::Shader::Property::SUBDIVIDE_GRID_Y, Dali::Ui::Visual::Shader::Property::VERTEX_SHADER.
DALI_UI_API void Dali::Ui::SetMotionStretchProperties(Actor &actor)
Set the properties for the motion stretch.
DALI_UI_API Property::Map Dali::Ui::CreateMotionStretchEffect()
Creates a new MotionStretchEffect.
Motion stretch shader works on a per object basis. Objects will stretch in the direction of motion when they move, or if the camera moves. Animatable/Constrainable uniforms: "uGeometryStretchFactor" - This scales the amount the geometry stretches along the motion velocity vector. A smaller value means the geometry stretches less, larger it stretches more. Default 0.5. "uSpeedScalingFactor" - This value is used to control how much to fade the actor near the edges, based on the speed the actor is moving. When the actor is at rest this is not applied. Default 0.5. "uObjectFadeStart" - The displacement from the centre of the actor that the actor will start to fade towards its edges. This is used to prevent an unsightly hard edge between the stretched actor and the scene. Depends on the values of the vertices in the vertex stream. When the actor is at rest this is not applied. Default Vector2(0.25, 0.25), which is half way towards the edge for an ImageVisual::QUAD. "uObjectFadeEnd" - The displacement from the centre of the actor that the actor will finish fading towards its edges. This is used to prevent an unsightly hard edge between the stretched actor and the scene. Depends on the values of the vertices in the vertex stream. When the actor is at rest this is not applied. Default 0.5, which is all the way towards the edge for an ImageVisual::QUAD. "uAlphaScale" - Global scaler applied to the alpha of the actor. Used to make the stretched actor a bit more subtle and reveal a bit of the background behind it as it moves. When the actor is at rest this is not applied. Default 0.75. "uModelLastFrame" - The model to world space transformation matrix of the actor in the previous frame. The newly created Property::Map with the motion stretch effect
References Dali::Ui::Visual::Shader::Property::FRAGMENT_SHADER, Dali::Ui::Visual::Shader::Property::HINTS, Dali::Ui::Visual::Property::SHADER, Dali::Ui::Visual::Shader::Property::SUBDIVIDE_GRID_X, Dali::Ui::Visual::Shader::Property::SUBDIVIDE_GRID_Y, Dali::Ui::Visual::Shader::Property::VERTEX_SHADER.
DALI_UI_API Integration::InteractiveTraitImpl & Dali::Ui::GetImpl(InteractiveTrait &obj)
DALI_UI_API const Integration::InteractiveTraitImpl & Dali::Ui::GetImpl(const InteractiveTrait &obj)
DALI_UI_API Integration::InteractiveViewImpl & Dali::Ui::GetImpl(InteractiveView &view)
DALI_UI_API const Integration::InteractiveViewImpl & Dali::Ui::GetImpl(const InteractiveView &view)
DALI_UI_API Integration::AbsoluteLayoutImpl & Dali::Ui::GetImpl(AbsoluteLayout &layout)
const DALI_UI_API Integration::AbsoluteLayoutImpl & Dali::Ui::GetImpl(const AbsoluteLayout &layout)
DALI_UI_API Integration::FlexLayoutImpl & Dali::Ui::GetImpl(FlexLayout &layout)
DALI_UI_API const Integration::FlexLayoutImpl & Dali::Ui::GetImpl(const FlexLayout &layout)
DALI_UI_API Integration::GridLayoutImpl & Dali::Ui::GetImpl(GridLayout &layout)
DALI_UI_API const Integration::GridLayoutImpl & Dali::Ui::GetImpl(const GridLayout &layout)
DALI_UI_API Integration::LayoutImpl & Dali::Ui::GetImpl(Layout &layout)
DALI_UI_API const Integration::LayoutImpl & Dali::Ui::GetImpl(const Layout &layout)
DALI_UI_API Integration::StackLayoutImpl & Dali::Ui::GetImpl(StackLayout &layout)
DALI_UI_API const Integration::StackLayoutImpl & Dali::Ui::GetImpl(const StackLayout &layout)
DALI_UI_API Integration::SelectableTraitImpl & Dali::Ui::GetImpl(SelectableTrait &obj)
DALI_UI_API const Integration::SelectableTraitImpl & Dali::Ui::GetImpl(const SelectableTrait &obj)
DALI_UI_API Integration::TraitImpl & Dali::Ui::GetImpl(Trait &obj)
DALI_UI_API const Integration::TraitImpl & Dali::Ui::GetImpl(const Trait &obj)
Integration::UiConfigImpl & Dali::Ui::GetImpl(UiConfig &obj)
Retrieves the UiConfigImpl from a UiConfig handle.
obj The UiConfig handle A reference to the internal implementation
const Integration::UiConfigImpl & Dali::Ui::GetImpl(const UiConfig &obj)
Retrieves the UiConfigImpl from a const UiConfig handle.
obj The UiConfig handle A const reference to the internal implementation
Integration::UiConfigManagerImpl & Dali::Ui::GetImpl(Integration::UiConfigManager &obj)
Retrieves the UiConfigManagerImpl from a UiConfigManager handle.
const Integration::UiConfigManagerImpl & Dali::Ui::GetImpl(const Integration::UiConfigManager &obj)
Retrieves the UiConfigManagerImpl from a const UiConfigManager handle.
Integration::UiThemeManagerImpl & Dali::Ui::GetImpl(UiThemeManager &obj)
Retrieves the UiThemeManagerImpl from a UiThemeManager handle.
const Integration::UiThemeManagerImpl & Dali::Ui::GetImpl(const UiThemeManager &obj)
Retrieves the UiThemeManagerImpl from a const UiThemeManager handle.
Integration::UiComponentConfigImpl & Dali::Ui::GetImpl(UiComponentConfig &obj)
Retrieves the UiComponentConfigImpl from a UiComponentConfig handle.
obj The UiComponentConfig handle A reference to the internal implementation
const Integration::UiComponentConfigImpl & Dali::Ui::GetImpl(const UiComponentConfig &obj)
Retrieves the UiComponentConfigImpl from a const UiComponentConfig handle.
obj The UiComponentConfig handle A const reference to the internal implementation