Dali::Ui::ViewAccessible
Vector2 Dali::Ui::ViewAccessible::mLastPosition
Referenced by GetLastPosition, SetLastPosition.
Dali::WeakHandle<Dali::Actor> Dali::Ui::ViewAccessible::mCurrentHighlightActor
Referenced by ClearHighlight, GrabHighlight.
AccessibilityStates Dali::Ui::ViewAccessible::mStatesSnapshot
Grabs snapshot of previous state when the view is highlighted.
AccessibilityHighlightOverlay Dali::Ui::ViewAccessible::mHighlightOverlay
void Dali::Ui::ViewAccessible::ScrollToSelf()
References ScrollToChild.
Referenced by GrabHighlight.
void Dali::Ui::ViewAccessible::RegisterPositionPropertyNotification()
Register property notification to check highlighted object position.
References Dali::Ui::View::DownCast, Dali::Ui::GetImpl.
Referenced by GrabHighlight.
void Dali::Ui::ViewAccessible::UnregisterPositionPropertyNotification()
Remove property notification added by RegisterPropertyNotification.
References Dali::Ui::View::DownCast, Dali::Ui::GetImpl.
Referenced by ClearHighlight.
void Dali::Ui::ViewAccessible::RegisterPropertySetSignal()
Registers PropertySet signal to notify when ACCESSIBILITY_NAME or ACCESSIBILITY_DESCRIPTION is changed. Note that those two signals only need for highlighted view. So, let us ensure to connect PropertySet signal only if view has been grabbed.
References Dali::Ui::View::DownCast, Dali::Ui::GetImpl.
Referenced by GrabHighlight.
void Dali::Ui::ViewAccessible::UnregisterPropertySetSignal()
Unregisters PropertySet signal to notify when ACCESSIBILITY_NAME or ACCESSIBILITY_DESCRIPTION is changed.
References Dali::Ui::View::DownCast, Dali::Ui::GetImpl.
Referenced by ClearHighlight.
bool Dali::Ui::ViewAccessible::IsShowing()
Check if the actor is showing.
True if the actor is showing
Referenced by CalculateStates.
Dali::Ui::ViewAccessible::ViewAccessible(Dali::Actor self)
std::string Dali::Ui::ViewAccessible::GetName() const override
References Dali::Ui::View::DownCast, Dali::Ui::GetImpl, GetNameRaw.
std::pair< std::string, bool > Dali::Ui::ViewAccessible::GetNameRaw() const
Returns the actor's name in the absence of ACCESSIBILITY_NAME property.
A pair containing the name and a boolean indicating if empty names are allowed
Referenced by GetName.
std::string Dali::Ui::ViewAccessible::GetDescription() const override
References Dali::Ui::View::DownCast, GetDescriptionRaw, Dali::Ui::GetImpl.
std::string Dali::Ui::ViewAccessible::GetDescriptionRaw() const
Returns the actor's description in the absence of ACCESSIBILITY_DESCRIPTION property.
Referenced by GetDescription.
std::string Dali::Ui::ViewAccessible::GetValue() const override
References Dali::Ui::View::Property::ACCESSIBILITY_VALUE.
Dali::Accessibility::Role Dali::Ui::ViewAccessible::GetRole() const override
References Dali::Ui::View::Property::ACCESSIBILITY_ROLE.
std::string Dali::Ui::ViewAccessible::GetLocalizedRoleName() const override
Dali::Accessibility::States Dali::Ui::ViewAccessible::GetStates() override
References CalculateStates.
Dali::Accessibility::Attributes Dali::Ui::ViewAccessible::GetAttributes() const override
References Dali::Ui::View::Property::ACCESSIBILITY_ATTRIBUTES, Dali::Ui::View::Property::AUTOMATION_ID, Dali::Ui::ImageView::DownCast, Dali::Ui::View::DownCast.
void Dali::Ui::ViewAccessible::InitDefaultFeatures() override
bool Dali::Ui::ViewAccessible::IsHidden() const override
References Dali::Ui::View::DownCast, Dali::Ui::GetImpl.
bool Dali::Ui::ViewAccessible::GrabFocus() override
References Dali::Ui::FocusManager::Get, Dali::Ui::FocusManager::SetCurrentFocusActor.
bool Dali::Ui::ViewAccessible::GrabHighlight() override
References Dali::Ui::View::DownCast, mCurrentHighlightActor, RegisterPositionPropertyNotification, RegisterPropertySetSignal, ScrollToSelf, Dali::Ui::AccessibilityHighlightOverlay::UpdateOverlay.
bool Dali::Ui::ViewAccessible::ClearHighlight() override
References Dali::Ui::View::DownCast, Dali::Ui::AccessibilityHighlightOverlay::HideOverlay, mCurrentHighlightActor, UnregisterPositionPropertyNotification, UnregisterPropertySetSignal.
std::string Dali::Ui::ViewAccessible::GetActionName(size_t index) const override
References GetActionCount.
Referenced by DoAction, GetLocalizedActionName.
std::string Dali::Ui::ViewAccessible::GetLocalizedActionName(size_t index) const override
References GetActionName.
std::string Dali::Ui::ViewAccessible::GetActionDescription(size_t index) const override
size_t Dali::Ui::ViewAccessible::GetActionCount() const override
Referenced by GetActionName.
std::string Dali::Ui::ViewAccessible::GetActionKeyBinding(size_t index) const override
bool Dali::Ui::ViewAccessible::DoAction(size_t index) override
References GetActionName.
bool Dali::Ui::ViewAccessible::DoAction(const std::string &name) override
bool Dali::Ui::ViewAccessible::DoGesture(const Dali::Accessibility::GestureInfo &gestureInfo) override
References Dali::Ui::View::DownCast, Dali::Ui::GetImpl.
std::vector< Dali::Accessibility::Relation > Dali::Ui::ViewAccessible::GetRelationSet() override
References Dali::Ui::View::DownCast, Dali::Ui::ViewImpl::GetAccessibilityRelations, Dali::Ui::GetImpl.
std::string Dali::Ui::ViewAccessible::GetStringProperty(std::string propertyName) const override
References Dali::Ui::PropertyBridge::Get, Dali::Ui::PropertyBridge::GetStringProperty.
bool Dali::Ui::ViewAccessible::IsScrollable() const override
References Dali::Ui::View::Property::ACCESSIBILITY_SCROLLABLE.
void Dali::Ui::ViewAccessible::SetCustomHighlightOverlay(Vector2 position, Vector2 size)
Function to set a custom highlight overlay.
This function sets a custom highlight overlay at the specified position and size. position A Vector2 representing the position of the overlay size A Vector2 representing the size of the overlay
References Dali::Ui::AccessibilityHighlightOverlay::SetCustomHighlight.
void Dali::Ui::ViewAccessible::ResetCustomHighlightOverlay()
Function to reset the custom highlight overlay.
This function resets the custom highlight overlay.
References Dali::Ui::AccessibilityHighlightOverlay::ResetCustomHighlight.
Dali::Accessibility::States Dali::Ui::ViewAccessible::CalculateStates()
References Dali::Ui::FocusManager::Get, Dali::Ui::FocusManager::GetCurrentFocusActor, IsShowing, states.
Referenced by GetStates.
bool Dali::Ui::ViewAccessible::ScrollToChild(Actor child)
Makes sure that a given child (descendant) of this container (e.g. ItemView) is visible.
false if scrolling is not supported or child is already visible
References Dali::Ui::View::DownCast.
Referenced by ScrollToSelf.
Dali::Property::Index Dali::Ui::ViewAccessible::GetNamePropertyIndex()
Returns the index of the property that represents this actor's name.
Dali::Property::Index Dali::Ui::ViewAccessible::GetDescriptionPropertyIndex()
Returns the index of the property that represents this actor's description.
void Dali::Ui::ViewAccessible::SetLastPosition(Vector2 position)
Sets last object position.
position Last object position
References mLastPosition.
Vector2 Dali::Ui::ViewAccessible::GetLastPosition() const
Gets last object position.
The Last object position
References mLastPosition.
void Dali::Ui::ViewAccessible::OnStatePropertySet(AccessibilityStates newStates)
Handles AcessibilityState property change; Only called when the view is highlighted.
References Dali::Ui::View::Property::ACCESSIBILITY_ROLE, Dali::Ui::BUTTON, Dali::Ui::CHECK_BOX, Dali::Ui::CHECKED, Dali::Ui::LIST_ITEM, Dali::Ui::MENU_ITEM, Dali::Ui::RADIO_BUTTON, Dali::Ui::SCROLL_BAR, Dali::Ui::SELECTED, Dali::Ui::TAB, Dali::Ui::TOGGLE_BUTTON.
bool Dali::Ui::ViewAccessible::IsModal(Actor actor)
Returns true if given actor is considered as modal by propeties set.
References Dali::Ui::View::Property::ACCESSIBILITY_IS_MODAL, Dali::Ui::View::Property::ACCESSIBILITY_ROLE.
bool Dali::Ui::ViewAccessible::IsScene3D(Actor actor)
Returns true if given actor is considered as 3D scene view by propeties set.
References Dali::Ui::View::Property::ACCESSIBILITY_ROLE, Dali::Ui::MAX_COUNT.
void Dali::Ui::ViewAccessible::ApplyAccessibilityProps(Dali::Accessibility::States &states)
Appliys relavant accessibility properties to AT-SPI states.