Dali::Integration::AddOnManager
AddOnManager * Dali::Integration::AddOnManager::mSingleton
Singleton storing an instance of AddOnManager.
Referenced by AddOnManager, Get.
Dali::Integration::AddOnManager::AddOnManager()
Constructor, initialised by the Adaptor.
References mSingleton.
Dali::Integration::AddOnManager::~AddOnManager()
Destructor.
virtual std::vector< std::string > Dali::Integration::AddOnManager::EnumerateAddOns()=0
Retrieves list of the available AddOns.
List of AddOn names
virtual bool Dali::Integration::AddOnManager::GetAddOnInfo(const std::string &name, AddOnInfo &info)=0
Returns AddOnInfo structure for specified AddOn name.
name Name of AddOn info Output reference True on success, False if extension info cannot be retrieved
Referenced by Dali::AddOn::AddOnBinder::AddOnBinder, Dali::AddOn::AddOnBinder::AddOnBinder.
virtual std::vector< AddOnLibrary > Dali::Integration::AddOnManager::LoadAddOns(const std::vector< std::string > &addonNames)=0
Loads and initialises specified extensions.
extensionNames Array of extension names vector of initialised extension handles
virtual AddOnLibrary Dali::Integration::AddOnManager::LoadAddOn(const std::string &addonName, const std::string &libraryName)=0
Loads the specified addon from the specified library if it's not already cached.
addonName Name of the AddOn to acquire libraryName Name of the library to load the AddOn from Returns a valid handle or nullptr
Referenced by Dali::AddOn::AddOnBinder::AddOnBinder.
AddOnLibrary Dali::Integration::AddOnManager::GetAddOn(const std::string &addonName)
Loads AddOn with specified name.
addOnName Name of AddOn to be acquired Returns a valid handle or nullptr
Referenced by Dali::AddOn::AddOnBinder::AddOnBinder.
virtual void * Dali::Integration::AddOnManager::GetGlobalProc(const Dali::AddOnLibrary &addOnLibrary, const char *procName)=0
Returns AddOn global function pointer.
addOnLibrary valid AddOn library object procName Name of the function to retrieve Pointer to the function or null if function doesn't exist
Referenced by Dali::AddOn::AddOnBinder::ConvertFunction, Dali::AddOn::AddOnBinder::GetGlobalProc.
virtual void * Dali::Integration::AddOnManager::GetInstanceProc(const Dali::AddOnLibrary &addOnLibrary, const char *procName)=0
Returns addon instance function pointer.
addOnLibrary valid AddOn library object procName Name of the function to retrieve Pointer to the function or null if function doesn't exist
Referenced by Dali::AddOn::AddOnBinder::GetInstanceProc.
std::function< T > Dali::Integration::AddOnManager::GetGlobalProc(const Dali::AddOnLibrary &addonlibrary, const char *procName)
Returns addon global function of specified type.
addOnLibrary valid AddOn library object procName Name of the function to retrieve std::function object or null if function doesn't exist
std::function< T > Dali::Integration::AddOnManager::GetInstanceProc(const Dali::AddOnLibrary &addOnLibrary, const char *procName)
Returns AddOn instance function of specified type.
addOnLibrary valid AddOn library object procName Name of the function to retrieve std::function object or null if function doesn't exist
R Dali::Integration::AddOnManager::InvokeGlobalProc(AddOnLibrary addOnLibrary, const char *functionName, Args &&... args)
Invokes global function by name.
addOnLibrary valid AddOn library object functionName Name of function to be called args[in] Arguments Result of called function
virtual void Dali::Integration::AddOnManager::Pause()=0
Lifecycle pause function.
virtual void Dali::Integration::AddOnManager::Resume()=0
Lifecycle resume function.
virtual void Dali::Integration::AddOnManager::Start()=0
Lifecycle start function.
virtual void Dali::Integration::AddOnManager::Stop()=0
Lifecycle stop function.
virtual void Dali::Integration::AddOnManager::RegisterAddOnDispatchTable(const AddOnDispatchTable *dispatchTable)=0
Registers the dispatch table with AddOnManager.
The function must be called by the AddOn in order to self-register and add the dispatch table. The platform-dependent implementation must override it in order to store the dispatch table. The way the dispatch table is stored depends on the implementation. dispatchTable Pointer to the valid dispatch table
Referenced by Dali::AddOns::AddOnConstructorInternal.
AddOnManager * Dali::Integration::AddOnManager::Get()
Retrieves AddOnManager singleton.
pointer to the AddOnManager
References mSingleton.
Referenced by Dali::AddOn::AddOnBinder::AddOnBinder, Dali::AddOn::AddOnBinder::AddOnBinder, Dali::AddOns::AddOnConstructorInternal.