Dali::ConnectionTracker
Impl* Dali::ConnectionTracker::mCacheImpl
Private internal extra data.
Dali::ConnectionTracker::ConnectionTracker()
Constructor. @SINCE_1_0.0.
Dali::ConnectionTracker::~ConnectionTracker() override
Virtual destructor. @SINCE_1_0.0.
References DisconnectAll.
void Dali::ConnectionTracker::DisconnectAll()
Disconnects all signals from this object. @SINCE_1_0.0.
References Dali::ConnectionTracker::Impl::DisconnectAllAndReset.
Referenced by Dali::SlotDelegate< Slot >::DisconnectAll, ~ConnectionTracker.
void Dali::ConnectionTracker::SignalConnected(SlotObserver *slotObserver, CallbackBase *callback) override
Called when a signal is connected.
@SINCE_1_0.0 slotObserver The slot observer i.e. a signal. Ownership is not passed callback The call back. Ownership is not passed
References Dali::ConnectionTracker::Impl::Insert.
void Dali::ConnectionTracker::SignalDisconnected(SlotObserver *slotObserver, CallbackBase *callback) override
This method is called when the signal is disconnecting.
@SINCE_1_0.0 slotObserver The signal that has disconnected callback The callback attached to the signal disconnected
References DALI_ABORT, Dali::ConnectionTracker::Impl::Erase.
uint32_t Dali::ConnectionTracker::GetConnectionCount() const
Returns the connection count. @SINCE_1_0.0.
The connection count
References Dali::ConnectionTracker::Impl::GetSize.
Referenced by Dali::SlotDelegate< Slot >::GetConnectionCount.
Dali::ConnectionTracker::ConnectionTracker(const ConnectionTracker &)=delete
Deleted copy constructor. @SINCE_1_0.0.
Dali::ConnectionTracker::ConnectionTracker(ConnectionTracker &&)=delete
Deleted move constructor. @SINCE_1_9.25.
ConnectionTracker & Dali::ConnectionTracker::operator=(const ConnectionTracker &)=delete
Deleted copy assignment operator. @SINCE_1_0.0.
ConnectionTracker & Dali::ConnectionTracker::operator=(ConnectionTracker &&)=delete
Deleted move assignment operator. @SINCE_1_9.25.