Dali::VectorBase
using Dali::VectorBase::SizeType = uint32_t
using Dali::VectorBase::MemMoveFunctionType = void* (*)(void*, const void*, SizeType)
constexpr uint32_t Dali::VectorBase::SHRINK_REQUIRED_RATIO
The ratio of auto shrink to fit calling. @SINCE_2_3.22.
Referenced by Dali::Vector< T, IsTrivialType >::ShrinkToFitIfNeeded.
void* Dali::VectorBase::mData
Pointer to the data.
Referenced by Dali::Vector< T, IsTrivialType >::Back, Dali::Vector< T, IsTrivialType >::Begin, Capacity, Copy, Dali::Vector< T, IsTrivialType >::End, Erase, Erase, Dali::Vector< T, IsTrivialType >::Front, Dali::Vector< T, IsTrivialType >::operator[], Release, ReserveWithCustomMoveFunction, SetCount, ShrinkToFit, Swap.
Dali::VectorBase::VectorBase()
Default constructor. Does not allocate space. @SINCE_1_0.0.
Dali::VectorBase::~VectorBase()
Destructor.
Does not release the space. Derived class needs to call Release. Not virtual as this should not be called directly and we do not want a vtable for this class as it would unnecessarily increase size. @SINCE_1_0.0
void Dali::VectorBase::SetCount(SizeType count)
Helper to set the count.
@SINCE_1_0.0 count Number of elements in the vector
References mData.
Referenced by Dali::Vector< T, IsTrivialType >::Erase, Erase, Erase, Dali::Vector< T, IsTrivialType >::PushBack, Dali::Vector< T, IsTrivialType >::PushBack, Dali::Vector< T, IsTrivialType >::Remove, Dali::Vector< T, IsTrivialType >::Resize, Dali::Vector< T, IsTrivialType >::ResizeUninitialized.
void Dali::VectorBase::Reserve(SizeType count, SizeType elementSize)
Reserves space in the vector.
@SINCE_1_0.0 count Count of elements to reserve elementSize Size of a single element
References ReserveWithCustomMoveFunction.
void Dali::VectorBase::ReserveWithCustomMoveFunction(SizeType count, SizeType elementSize, MemMoveFunctionType memMoveFunction)
Reserves space in the vector with custom memmove.
@SINCE_2_5.10 count Count of elements to reserve elementSize Size of a single element memMoveFunction Custom memory move function when we allocate new memory
References Capacity, Count, DALI_ASSERT_ALWAYS, mData, Replace.
Referenced by Reserve.
void Dali::VectorBase::Copy(const VectorBase &vector, SizeType elementSize)
Copy a vector.
@SINCE_1_0.0 vector Vector to copy from elementSize Size of a single element
References Capacity, DALI_ASSERT_ALWAYS, mData, Replace.
void Dali::VectorBase::Swap(VectorBase &vector)
Swaps the contents of two vectors.
@SINCE_1_0.0 vector Vector to swap with
References mData.
Referenced by Dali::OwnerContainer< T >::MoveFrom, Dali::Vector< T, IsTrivialType >::Swap.
void Dali::VectorBase::Erase(uint8_t *address, SizeType elementSize)
Erases an element.
Does not change capacity. @SINCE_1_0.0 address Address to erase from elementSize Size to erase Last element cannot be erased as there is nothing to move.
References Count, mData, SetCount.
uint8_t * Dali::VectorBase::Erase(uint8_t *first, uint8_t *last, SizeType elementSize)
Erases a range of elements.
Does not change capacity. @SINCE_1_0.0 first Address to the first element to be erased last Address to the last element to be erased elementSize Size of one of the elements to be erased Address pointing to the next element of the last one
References Count, mData, SetCount.
void Dali::VectorBase::CopyMemory(uint8_t *destination, const uint8_t *source, SizeType numberOfBytes)
Copies a number of bytes from source to destination.
source and destination must not overlap. @SINCE_1_0.0 destination Pointer to the destination address source Pointer to the source address numberOfBytes The number of bytes to be copied
void Dali::VectorBase::Replace(void *newData) noexcept
Replace the data as new data address. After replace, release the old data.
It will be used when we want to keep the mData integrity. Does not call destructors on objects held. newData new data address to be replaced
Referenced by Copy, ReserveWithCustomMoveFunction.
void Dali::VectorBase::ShrinkToFit(SizeType elementSize)
Fit the capacity of vector as item counts. It will be used when we want to remove unused memory.
@SINCE_2_3.22 elementSize Size of a single element
References Capacity, Count, DALI_ASSERT_VECTOR, mData, Release.
Referenced by Dali::Vector< T, IsTrivialType >::ShrinkToFit, Dali::Vector< T, IsTrivialType >::ShrinkToFitIfNeeded.
SizeType Dali::VectorBase::Count() const
This method is inlined as it's needed frequently for Vector::End() iterator.
@SINCE_1_0.0 The count of elements in this vector
Referenced by Dali::Vector< T, IsTrivialType >::Back, Dali::Vector< T, IsTrivialType >::End, Dali::Vector< T, IsTrivialType >::Erase, Erase, Erase, Dali::OwnerContainer< T >::IsEmpty, Dali::OwnerContainer< T >::MoveFrom, Dali::Vector< T, IsTrivialType >::operator[], Dali::Vector< T, IsTrivialType >::PushBack, Dali::Vector< T, IsTrivialType >::PushBack, Dali::Vector< T, IsTrivialType >::Remove, ReserveWithCustomMoveFunction, Dali::Vector< T, IsTrivialType >::Resize, Dali::OwnerContainer< T >::Resize, ShrinkToFit, Dali::Vector< T, IsTrivialType >::ShrinkToFitIfNeeded.
SizeType Dali::VectorBase::Size() const
Gets the count of elements in this vector. @SINCE_1_0.0.
The count of elements in this vector
bool Dali::VectorBase::Empty() const
@ return if the vector is empty. @SINCE_1_0.0
True if the count of elements is empty
VectorBase::SizeType Dali::VectorBase::Capacity() const
Gets the capacity of this vector. @SINCE_1_0.0.
The capacity of this vector
References mData.
Referenced by Copy, Dali::Vector< T, IsTrivialType >::PushBack, Dali::Vector< T, IsTrivialType >::PushBack, ReserveWithCustomMoveFunction, ShrinkToFit, Dali::Vector< T, IsTrivialType >::ShrinkToFitIfNeeded.
void Dali::VectorBase::Release()
Releases the data.
Does not call destructors on objects held. @SINCE_1_0.0
References mData.
Referenced by ShrinkToFit, Dali::OwnerContainer< T >::~OwnerContainer.
Dali::VectorBase::VectorBase(const VectorBase &)=delete
Deleted copy constructor. @SINCE_1_0.0.
VectorBase & Dali::VectorBase::operator=(const VectorBase &)=delete
Deleted copy assignment operator. @SINCE_1_0.0.
Dali::VectorBase::VectorBase(VectorBase &&)=delete
Deleted move constructor. @SINCE_1_9.25.
VectorBase & Dali::VectorBase::operator=(VectorBase &&)=delete
Deleted copy assignment operator. @SINCE_1_9.25.