Dali::Renderer
Renderer Dali::Renderer::New(Geometry &geometry, Shader &shader)
Creates a new Renderer object.
@SINCE_1_1.43 geometry Geometry to be used by this renderer shader Shader to be used by this renderer A handle to the Renderer
References Dali::GetImplementation, Renderer.
Renderer Dali::Renderer::New(RenderCallback &renderCallback)
Creates a new Renderer object with RenderCallback.
@SINCE_2_1.18 renderCallback Valid RenderCallback A handle to the Renderer
References Renderer.
Renderer Dali::Renderer::New()
Creates a new Renderer object without geometry and shader.
We should set Geometry and Shader before attach to actor. If not, exception throwed. @SINCE_2_4.9 A handle to the Renderer
References Renderer.
Renderer Dali::Renderer::DownCast(BaseHandle handle)
Downcasts to a renderer handle. If not, a renderer the returned renderer handle is left uninitialized.
@SINCE_1_1.43 handle Handle to an object Renderer handle or an uninitialized handle
References Dali::BaseHandle::GetObjectPtr, Renderer.
Dali::Renderer::Renderer()
Default constructor, creates an empty handle.
@SINCE_1_1.43
Referenced by DownCast, New, New, New.
Dali::Renderer::~Renderer()
Destructor.
@SINCE_1_1.43
Dali::Renderer::Renderer(const Renderer &handle)
Copy constructor, creates a new handle to the same object.
@SINCE_1_1.43 handle Handle to an object
References Dali::DownCast.
Renderer & Dali::Renderer::operator=(const Renderer &handle)
Assignment operator, changes this handle to point at the same object.
@SINCE_1_1.43 handle Handle to an object Reference to the assigned object
Dali::Renderer::Renderer(Renderer &&rhs) noexcept
Move constructor.
@SINCE_1_9.22 rhs A reference to the moved handle
Renderer & Dali::Renderer::operator=(Renderer &&rhs) noexcept
Move assignment operator.
@SINCE_1_9.22 rhs A reference to the moved handle A reference to this handle
void Dali::Renderer::SetGeometry(Geometry &geometry)
Sets the geometry to be used by this renderer.
@SINCE_1_1.43 geometry The geometry to be used by this renderer
References DALI_ASSERT_ALWAYS, Dali::GetImplementation.
Geometry Dali::Renderer::GetGeometry() const
Gets the geometry used by this renderer.
@SINCE_1_1.43 The geometry used by the renderer
References Dali::GetImplementation.
void Dali::Renderer::RemoveGeometry()
Remove the geometry used by this renderer.
@SINCE_2_5.10
References Dali::GetImplementation.
void Dali::Renderer::SetIndexRange(int firstElement, int elementsCount)
Sets effective range of indices to draw from bound index buffer.
@SINCE_1_1.43 firstElement The First element to draw elementsCount The number of elements to draw
void Dali::Renderer::SetTextures(TextureSet &textureSet)
Sets the texture set to be used by this renderer.
@SINCE_1_1.43 textureSet The texture set to be used by this renderer
References DALI_ASSERT_ALWAYS, Dali::GetImplementation.
TextureSet Dali::Renderer::GetTextures() const
Gets the texture set used by this renderer.
@SINCE_1_1.43 The texture set used by the renderer
References Dali::GetImplementation.
void Dali::Renderer::RemoveTextures()
Remove the texture set used by this renderer.
@SINCE_2_5.10
References Dali::GetImplementation.
void Dali::Renderer::SetShader(Shader &shader)
Sets the shader used by this renderer.
@SINCE_1_1.43 shader The shader to be used by this renderer
References DALI_ASSERT_ALWAYS, Dali::GetImplementation.
Shader Dali::Renderer::GetShader() const
Gets the shader used by this renderer.
@SINCE_1_1.43 The shader used by the renderer
References Dali::GetImplementation.
void Dali::Renderer::RemoveShader()
Remove the shader used by this renderer.
@SINCE_2_5.10
References Dali::GetImplementation.
void Dali::Renderer::SetRenderCallback(RenderCallback *callback)
Sets RenderCallback to be used for native rendering.
@SINCE_2_1.15 callback Pointer to a valid RenderCallback object
References Dali::GetImplementation.
void Dali::Renderer::TerminateRenderCallback(bool invokeCallback)
Remove RenderCallback used for native rendering.
@SINCE_2_4.35 invokeCallback Invoke render callbacks forcibly if we need to catch terminate case at callback.
References Dali::GetImplementation.