Dali::Actor
using Dali::Actor::TouchEventSignalType = Signal<bool(Actor, const TouchEvent&)>
Touch signal type @SINCE_1_1.37.
using Dali::Actor::HoverSignalType = Signal<bool(Actor, const HoverEvent&)>
Hover signal type @SINCE_1_0.0.
using Dali::Actor::WheelEventSignalType = Signal<bool(Actor, const WheelEvent&)>
Wheel signal type @SINCE_1_0.0.
using Dali::Actor::OnSceneSignalType = Signal<void(Actor)>
Scene connection signal type @SINCE_1_9.24.
using Dali::Actor::OffSceneSignalType = Signal<void(Actor)>
Scene disconnection signal type @SINCE_1_9.24.
using Dali::Actor::OnRelayoutSignalType = Signal<void(Actor)>
Called when the actor is relaid out @SINCE_1_0.0.
using Dali::Actor::LayoutDirectionChangedSignalType = Signal<void(Actor, LayoutDirection::Type)>
Layout direction changes signal type. @SINCE_1_2.60.
using Dali::Actor::InheritedVisibilityChangedSignalType = Signal<void(Actor, bool)>
Signal type of InheritedVisibilityChangedSignalType. @SINCE_2_3.22.
Dali::Actor::Actor()
Creates an uninitialized Actor; this can be initialized with Actor::New().
Calling member functions with an uninitialized Actor handle is not allowed. @SINCE_1_0.0
References Dali::DownCast.
Referenced by DownCast, FindChildById, FindChildByName, GetChildAt, GetParent, New.
Dali::Actor::~Actor()
Dali::Actor is intended as a base class.
This is non-virtual since derived Handle types must not contain data or virtual methods. @SINCE_1_0.0
Dali::Actor::Actor(const Actor &copy)
Copy constructor.
@SINCE_1_0.0 copy The actor to copy
Actor & Dali::Actor::operator=(const Actor &rhs)
Assignment operator.
@SINCE_1_0.0 rhs The actor to copy A reference to this
Dali::Actor::Actor(Actor &&rhs) noexcept
Move constructor.
@SINCE_1_9.22 rhs A reference to the actor to move
Actor & Dali::Actor::operator=(Actor &&rhs) noexcept
Move assignment operator.
@SINCE_1_9.22 rhs A reference to the actor to move A reference to this
Layer Dali::Actor::GetLayer()
Gets the layer in which the actor is present.
@SINCE_1_0.0 The layer, which will be uninitialized if the actor is off-stage The Actor has been initialized.
References Dali::GetImplementation.
void Dali::Actor::Add(Actor child)
Adds a child Actor to this Actor.
@SINCE_1_0.0 child The child This Actor (the parent) has been initialized. The child actor has been initialized. The child actor is not the same as the parent actor. The actor is not the Root actor. The child will be referenced by its parent. This means that the child will be kept alive, even if the handle passed into this method is reset or destroyed. If the child already has a parent, it will be removed from old parent and reparented to this actor. This may change child's position, color, scale etc as it now inherits them from this actor.
References Dali::GetImplementation.
Referenced by Dali::Scripting::NewActor.
void Dali::Actor::Remove(Actor child)
Removes a child Actor from this Actor.
If the actor was not a child of this actor, this is a no-op. @SINCE_1_0.0 child The child This Actor (the parent) has been initialized. The child actor is not the same as the parent actor.
References Dali::GetImplementation.
void Dali::Actor::Unparent()
Removes an actor from its parent.
If the actor has no parent, this method does nothing. @SINCE_1_0.0 The (child) actor has been initialized.
References Dali::GetImplementation.
Referenced by Dali::UnparentAndReset.
uint32_t Dali::Actor::GetChildCount() const
Retrieves the number of children held by the actor.
@SINCE_1_0.0 The number of children The Actor has been initialized.
References Dali::GetImplementation.
Referenced by Dali::Scripting::CreatePropertyMap.
Actor Dali::Actor::GetChildAt(uint32_t index) const
Retrieve and child actor by index.
@SINCE_1_0.0 index The index of the child to retrieve The actor for the given index or empty handle if children not initialized The Actor has been initialized.
References Actor, Dali::GetImplementation.
Referenced by Dali::Scripting::CreatePropertyMap.
Actor Dali::Actor::FindChildByName(Dali::StringView actorName)
Search through this actor's hierarchy for an actor with the given name.
The actor itself is also considered in the search. @SINCE_2_0.9 actorName The name of the actor to find A handle to the actor if found, or an empty handle if not The Actor has been initialized.
References Actor, Dali::GetImplementation.
Actor Dali::Actor::FindChildById(const uint32_t id)
Search through this actor's hierarchy for an actor with the given unique ID.
The actor itself is also considered in the search. @SINCE_1_0.0 id The ID of the actor to find A handle to the actor if found, or an empty handle if not The Actor has been initialized.
References Actor, Dali::GetImplementation.
Actor Dali::Actor::GetParent() const
Retrieves the actor's parent.
@SINCE_1_0.0 A handle to the actor's parent. If the actor has no parent, this handle will be invalid The actor has been initialized.
References Actor, Dali::GetImplementation.
Vector3 Dali::Actor::GetTargetSize() const
Retrieves the actor's size.
@SINCE_1_0.0 The actor's target size The actor has been initialized. This return is the value that was set using SetSize or the target size of an animation. It may not match the current value in some cases, i.e. when the animation is progressing or the maximum or minimum size is set.
References Dali::GetImplementation.
Vector3 Dali::Actor::GetNaturalSize() const
Returns the natural size of the actor.
Deriving classes stipulate the natural size and by default an actor has a ZERO natural size. @SINCE_1_0.0 The actor's natural size
References Dali::GetImplementation.
void Dali::Actor::TranslateBy(const Vector3 &distance)
Translates an actor relative to its existing position.
@SINCE_1_0.0 distance The actor will move by this distance The actor has been initialized.
References Dali::GetImplementation.
void Dali::Actor::RotateBy(const Degree &angle, const Vector3 &axis)
Applies a relative rotation to an actor.
@SINCE_1_0.0 angle The angle to the rotation to combine with the existing orientation axis The axis of the rotation to combine with the existing orientation The actor has been initialized.
void Dali::Actor::RotateBy(const Radian &angle, const Vector3 &axis)
Applies a relative rotation to an actor.
@SINCE_1_0.0 angle The angle to the rotation to combine with the existing orientation axis The axis of the rotation to combine with the existing orientation The actor has been initialized.
References Dali::GetImplementation.
void Dali::Actor::RotateBy(const Quaternion &relativeRotation)
Applies a relative rotation to an actor.
@SINCE_1_0.0 relativeRotation The rotation to combine with the existing orientation The actor has been initialized.
References Dali::GetImplementation.
void Dali::Actor::ScaleBy(const Vector3 &relativeScale)
Applies a relative scale to an actor.
@SINCE_1_0.0 relativeScale The scale to combine with the actor's existing scale The actor has been initialized.
References Dali::GetImplementation.
bool Dali::Actor::ScreenToLocal(float &localX, float &localY, float screenX, float screenY) const
Converts screen coordinates into the actor's coordinate system using the default camera.
@SINCE_1_0.0 localX On return, the X-coordinate relative to the actor localY On return, the Y-coordinate relative to the actor screenX The screen X-coordinate screenY The screen Y-coordinate True if the conversion succeeded The Actor has been initialized. The actor coordinates are relative to the top-left (0.0, 0.0, 0.5)
References Dali::GetImplementation.
void Dali::Actor::Raise()
Raise actor above the next sibling actor.
@SINCE_1_2.60 The Actor has been initialized. The Actor has been parented.
References Dali::GetImplementation.
void Dali::Actor::Lower()
Lower the actor below the previous sibling actor.
@SINCE_1_2.60 The Actor has been initialized. The Actor has been parented.
References Dali::GetImplementation.
void Dali::Actor::RaiseToTop()
Raise actor above all other sibling actors.
@SINCE_1_2.60 The Actor has been initialized. The Actor has been parented.
References Dali::GetImplementation.
void Dali::Actor::LowerToBottom()
Lower actor to the bottom of all other sibling actors.
@SINCE_1_2.60 The Actor has been initialized. The Actor has been parented.
References Dali::GetImplementation.
void Dali::Actor::RaiseAbove(Actor target)
Raises the actor above the target actor.
@SINCE_1_2.60 target The target actor The Actor has been initialized. The Actor has been parented. The target actor is a sibling.
References Dali::GetImplementation.
void Dali::Actor::LowerBelow(Actor target)
Lower the actor to below the target actor.
@SINCE_1_2.60 target The target actor The Actor has been initialized. The Actor has been parented. The target actor is a sibling.
References Dali::GetImplementation.
void Dali::Actor::SetResizePolicy(ResizePolicy::Type policy, Dimension::Type dimension)
Sets the resize policy to be used for the given dimension(s).
@SINCE_1_0.0 policy The resize policy to use dimension The dimension(s) to set policy for. Can be a bitfield of multiple dimensions
References Dali::GetImplementation.
ResizePolicy::Type Dali::Actor::GetResizePolicy(Dimension::Type dimension) const
Returns the resize policy used for a single dimension.
@SINCE_1_0.0 dimension The dimension to get policy for Return the dimension resize policy. If more than one dimension is requested, just return the first one found
References Dali::GetImplementation.
float Dali::Actor::GetHeightForWidth(float width)
Calculates the height of the actor given a width.
The natural size is used for default calculation. size 0 is treated as aspect ratio 1:1. @SINCE_1_0.0 width Width to use Return the height based on the width
References Dali::GetImplementation.
float Dali::Actor::GetWidthForHeight(float height)
Calculates the width of the actor given a height.
The natural size is used for default calculation. size 0 is treated as aspect ratio 1:1. @SINCE_1_0.0 height Height to use Return the width based on the height
References Dali::GetImplementation.
float Dali::Actor::GetRelayoutSize(Dimension::Type dimension) const
Returns the value of negotiated dimension for the given dimension.
@SINCE_1_0.0 dimension The dimension to retrieve Return the value of the negotiated dimension. If more than one dimension is requested, just return the first one found
References Dali::GetImplementation.
void Dali::Actor::SetIgnored(bool ignored)
Sets a flag to identify whether the Actor is ignored or not. If the actor is marked as ignored, it will not be rendered and will be excluded from render thread computation. So, the current properties like WorldPosition and WorldColor become inaccurate.
@SINCE_2_4.21 ignored True to make the actor be ignored.
References Dali::GetImplementation.
bool Dali::Actor::IsIgnored() const
Returns whether the Actor is ignored or not.
@SINCE_2_4.21 Return True if the Actor is ignored.
References Dali::GetImplementation.
uint32_t Dali::Actor::AddRenderer(Renderer &renderer)
Adds a renderer to this actor.
We don't allow to add duplicated renderers. If we add the same renderer twice, it will just return the index of renderer. @SINCE_1_0.0 renderer Renderer to add to the actor The index of the Renderer that was added The renderer must be initialized.
References Dali::GetImplementation.
uint32_t Dali::Actor::GetRendererCount() const
Gets the number of renderers on this actor.
@SINCE_1_0.0 The number of renderers on this actor
References Dali::GetImplementation.
Renderer Dali::Actor::GetRendererAt(uint32_t index)
Gets a Renderer by index.
@SINCE_1_0.0 index The index of the renderer to fetch The renderer at the specified index The index must be between 0 and GetRendererCount()-1
References Dali::GetImplementation.
void Dali::Actor::RemoveRenderer(Renderer &renderer)
Removes a renderer from the actor.
@SINCE_1_0.0 renderer Handle to the renderer that is to be removed
References Dali::GetImplementation.
void Dali::Actor::RemoveRenderer(uint32_t index)
Removes a renderer from the actor by index.
@SINCE_1_0.0 index Index of the renderer that is to be removed The index must be between 0 and GetRendererCount()-1
References Dali::GetImplementation.
uint32_t Dali::Actor::AddCacheRenderer(Renderer &renderer)
Add renderer drawing cached output to this Actor. @SINCE_2_3.54.
renderer Renderer to set to the Actor The index of the Renderer that was added The renderer must be initialized.
References Dali::GetImplementation.
uint32_t Dali::Actor::GetCacheRendererCount() const
Get total number of cache renderers. @SINCE_2_4.19.
The size of cache renderer container
References Dali::GetImplementation.
void Dali::Actor::RemoveCacheRenderer(Renderer &renderer)
Removes cache renderer from the Actor.
renderer Renderer to erase. @SINCE_2_3.54
References Dali::GetImplementation.
Actor::TouchEventSignalType & Dali::Actor::TouchedSignal()
This signal is emitted when touch input is received.
A callback of the following type may be connected: boolYourCallbackName(Actoractor,TouchEvent&touch); The return value of True, indicates that the touch event has been consumed. Otherwise the signal will be emitted on the next sensitive parent of the actor. @SINCE_1_9.28 The signal to connect to The Actor has been initialized.
References Dali::GetImplementation.
Actor::HoverSignalType & Dali::Actor::HoveredSignal()
This signal is emitted when hover input is received.
A callback of the following type may be connected: boolYourCallbackName(Actoractor,constHoverEvent&event); The return value of True, indicates that the hover event should be consumed. Otherwise the signal will be emitted on the next sensitive parent of the actor. @SINCE_1_0.0 The signal to connect to The Actor has been initialized.
References Dali::GetImplementation.
Actor::WheelEventSignalType & Dali::Actor::WheelEventSignal()
This signal is emitted when wheel event is received.
A callback of the following type may be connected: boolYourCallbackName(Actoractor,constWheelEvent&event); The return value of True, indicates that the wheel event should be consumed. Otherwise the signal will be emitted on the next sensitive parent of the actor. @SINCE_1_0.0 The signal to connect to The Actor has been initialized.
References Dali::GetImplementation.
Actor::OnSceneSignalType & Dali::Actor::OnSceneSignal()
This signal is emitted after the actor has been connected to the scene.
When an actor is connected, it will be directly or indirectly parented to the root Actor. @SINCE_1_9.24 The signal to connect to The root Actor is provided automatically by the Scene, and is always considered to be connected. When the parent of a set of actors is connected to the stage, then all of the children will received this callback. For the following actor tree, the callback order will be A, B, D, E, C, and finally F. A(parent) /\ BC /\\ DEF
References Dali::GetImplementation.
Actor::OffSceneSignalType & Dali::Actor::OffSceneSignal()
This signal is emitted after the actor has been disconnected from the scene.
If an actor is disconnected it either has no parent, or is parented to a disconnected actor. @SINCE_1_9.24 The signal to connect to When the parent of a set of actors is disconnected to the scene, then all of the children will received this callback, starting with the leaf actors. For the following actor tree, the callback order will be D, E, B, F, C, and finally A. A(parent) /\ BC /\\ DEF
References Dali::GetImplementation.
Actor::OnRelayoutSignalType & Dali::Actor::OnRelayoutSignal()
This signal is emitted after the size has been set on the actor during relayout.
@SINCE_1_0.0 The signal
References Dali::GetImplementation.
Actor::LayoutDirectionChangedSignalType & Dali::Actor::LayoutDirectionChangedSignal()
This signal is emitted when the layout direction property of this or a parent actor is changed.
A callback of the following type may be connected: voidYourCallbackName(Actoractor,LayoutDirection::Typetype); actor: The actor, or child of actor, whose layout direction has changed type: Whether the actor's layout direction property has changed or a parent's. @SINCE_1_2.60 The signal to connect to The Actor has been initialized.
References Dali::GetImplementation.
Actor::InheritedVisibilityChangedSignalType & Dali::Actor::InheritedVisibilityChangedSignal()
This signal is emitted when the visible property of this actor or any of its parents (right up to the root layer) changes.
A callback of the following type may be connected: voidYourCallbackName(Actoractor,boolvisible); actor: The actor whose inherited visibility has changed. visible: This is true if this actor's inherited VISIBLE property is true. If it is true, it denotes one of the 2 cases. One is VISIBLE property of this actor or only one of the parent actors were originally false and it becomes true now. Another is this actor is connected on Scene now with that the VISIBLE property of this actor and all of its parent were true. If it is false, it also denotes one of the 2 cases. One is that VISIBLE property of this actor and all of the parent actors were originally true but one of them becomes false now. Another is VISIBLE property of this actor and all of the parent actors are true and this actor is disconnected from the Scene now. @SINCE_2_3.22 The signal to connect to The Actor has been initialized. This signal is NOT emitted if the actor becomes transparent (or the reverse). For reference, an actor is only shown if it and it's parents (up to the root actor) are also visible, are not transparent, and this actor has a non-zero size.
References Dali::GetImplementation.
Actor Dali::Actor::New()
Creates an initialized Actor.
@SINCE_1_0.0 A handle to a newly allocated Dali resource
References Actor.
Actor Dali::Actor::DownCast(BaseHandle handle)
Downcasts a handle to Actor handle.
If handle points to an Actor object, the downcast produces valid handle. If not, the returned handle is left uninitialized. @SINCE_1_0.0 handle to An object handle to a Actor object or an uninitialized handle
References Actor, Dali::BaseHandle::GetObjectPtr.
Referenced by Dali::Scripting::NewActor.