Dali::WeakHandleBase
Dali::WeakHandleBase::WeakHandleBase()
Default constructor which provides an uninitialized Dali::WeakHandleBase. @SINCE_1_2.60.
Dali::WeakHandleBase::WeakHandleBase(BaseHandle &handle)
This constructor creates a weak handle of the DALi object.
@SINCE_1_2.60 handle A reference to the handle of the DALi object
Dali::WeakHandleBase::~WeakHandleBase()
Destructor to free resources. @SINCE_1_2.60.
Dali::WeakHandleBase::WeakHandleBase(const WeakHandleBase &handle)
Copy constructor.
@SINCE_1_2.60 handle A reference to the copied WeakHandleBase
References GetBaseHandle.
WeakHandleBase & Dali::WeakHandleBase::operator=(const WeakHandleBase &rhs)
Assignment operator.
It makes this WeakHandleBase point to the same internal DALi object as the copied WeakHandleBase @SINCE_1_2.60 rhs A reference to the copied WeakHandleBase A reference to this WeakHandleBase
References GetBaseHandle.
Referenced by Dali::WeakHandle< T >::operator=.
Dali::WeakHandleBase::WeakHandleBase(WeakHandleBase &&rhs) noexcept
Move constructor.
@SINCE_1_9.22 rhs A reference to the moved handle
WeakHandleBase & Dali::WeakHandleBase::operator=(WeakHandleBase &&rhs) noexcept
Move assignment operator.
@SINCE_1_9.22 rhs A reference to the moved handle A reference to this handle
bool Dali::WeakHandleBase::operator==(const WeakHandleBase &rhs) const
Equality operator overload.
@SINCE_1_2.60 rhs A reference to the compared WeakHandleBase true if the handle points to the same DALi resource, or if both are uninitialized
References DALI_LIKELY.
Referenced by Dali::WeakHandle< T >::operator==.
bool Dali::WeakHandleBase::operator!=(const WeakHandleBase &rhs) const
Inequality operator overload.
@SINCE_1_2.60 rhs A reference to the compared WeakHandleBase true if the handle points to the different DALi resources
Referenced by Dali::WeakHandle< T >::operator!=.
BaseHandle Dali::WeakHandleBase::GetBaseHandle() const
Gets the handle to the DALi object.
@SINCE_1_2.60 The handle of the DALi object pointed by this WeakHandleBase or an empty handle if the DALi object doesn't exist
Referenced by Dali::WeakHandle< T >::GetHandle, operator=, WeakHandleBase.
void Dali::WeakHandleBase::Reset()
Resets this weak handle to not point to any DALi object @SINCE_1_2.60.
References DALI_LIKELY.