Dali::CameraActor
Dali::CameraActor::CameraActor()
Creates an uninitialized CameraActor handle.
Initialize it using CameraActor::New(). Calling member functions with an uninitialized CameraActor handle is not allowed. @SINCE_1_0.0
References Dali::DownCast.
Referenced by DownCast, New, New, New3DCamera.
Dali::CameraActor::~CameraActor()
Destructor.
This is non-virtual, since derived Handle types must not contain data or virtual methods. @SINCE_1_0.0
Dali::CameraActor::CameraActor(const CameraActor &copy)
Copy constructor.
@SINCE_1_0.0 copy The actor to copy
CameraActor & Dali::CameraActor::operator=(const CameraActor &rhs)
Assignment operator.
@SINCE_1_0.0 rhs The actor to copy A reference to this
Dali::CameraActor::CameraActor(CameraActor &&rhs) noexcept
Move constructor.
@SINCE_2_2.4 rhs A reference to the actor to move
CameraActor & Dali::CameraActor::operator=(CameraActor &&rhs) noexcept
Move assignment operator.
@SINCE_2_2.4 rhs A reference to the actor to move A reference to this
void Dali::CameraActor::SetType(Dali::Camera::Type type)
Sets the camera type. The default type is Dali::Camera::FREE_LOOK @SINCE_1_0.0.
type The camera type
References Dali::GetImplementation.
Dali::Camera::Type Dali::CameraActor::GetType() const
Gets the type of the camera.
@SINCE_1_0.0 The type of camera
References Dali::GetImplementation.
void Dali::CameraActor::SetProjectionMode(Dali::Camera::ProjectionMode mode)
Sets the projection mode.
@SINCE_1_0.0 mode One of PERSPECTIVE_PROJECTION or ORTHOGRAPHIC_PROJECTION
References Dali::GetImplementation.
Dali::Camera::ProjectionMode Dali::CameraActor::GetProjectionMode() const
Gets the projection mode.
@SINCE_1_0.0 One of PERSPECTIVE_PROJECTION or ORTHOGRAPHIC_PROJECTION
References Dali::GetImplementation.
void Dali::CameraActor::SetFieldOfView(float fieldOfView)
Sets the field of view. Field of view will be used when ProjectionMode is PERSPECTIVE_PROJECTION.
@SINCE_1_0.0 fieldOfView The field of view in radians
References Dali::GetImplementation.
float Dali::CameraActor::GetFieldOfView()
Gets the field of view in Radians.
The default field of view is 45 degrees. @SINCE_1_0.0 The field of view in radians
References Dali::GetImplementation.
void Dali::CameraActor::SetAspectRatio(float aspectRatio)
Sets the aspect ratio.
@SINCE_1_0.0 aspectRatio The aspect ratio
References Dali::GetImplementation.
float Dali::CameraActor::GetAspectRatio()
Gets the aspect ratio of the camera.
The default aspect ratio is 4.0f/3.0f. @SINCE_1_0.0 The aspect ratio
References Dali::GetImplementation.
void Dali::CameraActor::SetNearClippingPlane(float nearClippingPlane)
Sets the near clipping plane distance.
@SINCE_1_0.0 nearClippingPlane Distance of the near clipping plane
References Dali::GetImplementation.
float Dali::CameraActor::GetNearClippingPlane()
Gets the near clipping plane distance.
The default near clipping plane is 800.0f, to match the default screen height. Reduce this value to see objects closer to the camera. @SINCE_1_0.0 The near clipping plane value
References Dali::GetImplementation.
void Dali::CameraActor::SetFarClippingPlane(float farClippingPlane)
Sets the far clipping plane distance.
@SINCE_1_0.0 farClippingPlane Distance of the far clipping plane
References Dali::GetImplementation.
float Dali::CameraActor::GetFarClippingPlane()
Gets the far clipping plane distance.
The default value is the default near clipping plane + (0xFFFF>>4). @SINCE_1_0.0 The far clipping plane value
References Dali::GetImplementation.
void Dali::CameraActor::SetTargetPosition(const Vector3 &targetPosition)
Sets the target position of the camera.
@SINCE_1_0.0 targetPosition The position of the target to look at Camera type is LOOK_AT_TARGET.
References Dali::GetImplementation.
Vector3 Dali::CameraActor::GetTargetPosition() const
Gets the Camera Target position.
The default target position is Vector3::ZERO. @SINCE_1_0.0 The target position of the camera Camera type is LOOK_AT_TARGET.
References Dali::GetImplementation.
void Dali::CameraActor::SetInvertYAxis(bool invertYAxis)
Requests for an inversion on the Y axis on the projection calculation.
The default value is not inverted. @SINCE_1_0.0 invertYAxis True if the Y axis should be inverted
References Dali::GetImplementation.
bool Dali::CameraActor::GetInvertYAxis()
Gets whether the Y axis is inverted.
@SINCE_1_0.0 True if the Y axis is inverted, false otherwise
References Dali::GetImplementation.
void Dali::CameraActor::SetPerspectiveProjection(const Size &size)
Sets the default camera perspective projection for the given canvas size.
Sets the near and far clipping planes, the field of view, the aspect ratio, and the Z position of the actor based on the canvas size so that 1 unit in XY (z=0) plane is 1 pixel on screen. Also, It will set orthographic size be fitted as XY plane. @SINCE_1_0.0 size The canvas size The canvas size must be greater than zero. If either of the values of size is 0.0f, then we use the default perspective projection for the size of the scene this actor is added to. This modifies the Z position property of this actor as well.
References Dali::GetImplementation.
void Dali::CameraActor::SetOrthographicProjection(const Size &size)
Sets the camera projection to use orthographic projection.
The XY plane is centered on the camera axis. The units in the X/Y plane directly equate to pixels on an equivalently sized framebuffer. The Z position of the actor, and the near and far clip planes of the bounding box match those that would be created by using SetPerspectiveProjection with the same size. @SINCE_1_0.0 size Size of XY plane (normal to camera axis)
References Dali::GetImplementation.
CameraActor Dali::CameraActor::New()
Creates a CameraActor object.
Sets the default camera perspective projection for the size of the scene this is added to. SetPerspectiveProjection(). When this actor gets added to a scene, then it's Z position will be modified according to the required perspective projection. After modified Z position, 1-world-unit become 1-pixel. @SINCE_1_0.0 The newly created camera actor
References CameraActor, Dali::Vector2::ZERO.
CameraActor Dali::CameraActor::New(const Size &size)
Creates a CameraActor object.
Sets the default camera perspective projection for the given canvas size. SetPerspectiveProjection(). @SINCE_1_0.0 size The canvas size The newly created camera actor
References CameraActor.
CameraActor Dali::CameraActor::New3DCamera()
Creates a CameraActor object initialize by 3D parameter.
Intialize default perspective camera s.t. properties as good to be used on 3D app case. Default camera positioned at +Z axis, and fit to see 1-world-unit sized cube on world origin. @SINCE_2_2.15 The newly created camera actor
References CameraActor, Dali::Vector2::ZERO.
CameraActor Dali::CameraActor::DownCast(BaseHandle handle)
Downcasts a handle to CameraActor handle.
If handle points to a CameraActor, the downcast produces valid handle. If not, the returned handle is left uninitialized. @SINCE_1_0.0 handle to An object Handle to a CameraActor or an uninitialized handle
References CameraActor, Dali::BaseHandle::GetObjectPtr.