Dali::KeyFrames
KeyFrames Dali::KeyFrames::New()
Creates an initialized KeyFrames handle.
@SINCE_1_0.0 A handle to a newly allocated Dali resource
References KeyFrames.
KeyFrames Dali::KeyFrames::DownCast(BaseHandle handle)
Downcasts a handle to KeyFrames handle.
If handle points to a KeyFrames object, the downcast produces valid handle. If not, the returned handle is left uninitialized. @SINCE_1_0.0 handle Handle to an object Handle to a KeyFrames object or an uninitialized handle
References Dali::BaseHandle::GetObjectPtr, KeyFrames.
Dali::KeyFrames::KeyFrames()
Creates an uninitialized KeyFrame handle.
This can be initialized with KeyFrame::New(). Calling member functions with an uninitialized KeyFrames handle is not allowed. @SINCE_1_0.0
Referenced by DownCast, New.
Dali::KeyFrames::~KeyFrames()
Destructor.
This is non-virtual since derived Handle types must not contain data or virtual methods. @SINCE_1_0.0
Dali::KeyFrames::KeyFrames(const KeyFrames &handle)
This copy constructor is required for (smart) pointer semantics.
@SINCE_1_0.0 handle A reference to the copied handle
KeyFrames & Dali::KeyFrames::operator=(const KeyFrames &rhs)
This assignment operator is required for (smart) pointer semantics.
@SINCE_1_0.0 rhs A reference to the copied handle A reference to this
Dali::KeyFrames::KeyFrames(KeyFrames &&rhs) noexcept
Move constructor.
@SINCE_1_9.22 rhs A reference to the moved handle
KeyFrames & Dali::KeyFrames::operator=(KeyFrames &&rhs) noexcept
Move assignment operator.
@SINCE_1_9.22 rhs A reference to the moved handle A reference to this
Property::Type Dali::KeyFrames::GetType() const
Gets the type of the key frame.
If no key frames have been added, this returns Property::NONE. @SINCE_1_0.0 The key frame property type
References Dali::GetImplementation.
void Dali::KeyFrames::Add(float progress, Property::Value value)
Adds a key frame.
The key frames should be added in time order. @SINCE_1_0.0 progress A progress value between 0.0 and 1.0 value A value
References Dali::GetImplementation.
Referenced by Add.
void Dali::KeyFrames::Add(float progress, Property::Value value, AlphaFunction alpha)
Adds a key frame.
The key frames should be added in time order. @SINCE_1_0.0 @DEPRECATED_2_4.41 progress A progress value between 0.0 and 1.0 value A value alpha The alpha function used to blend to the next keyframe
References Add.