Dali::Vector
@SINCE_1_0.0
using Dali::Vector< T, IsTrivialType >::SizeType = VectorBase::SizeType
Size type @SINCE_1_0.0.
using Dali::Vector< T, IsTrivialType >::Iterator = T*
Most simple Iterator is a pointer @SINCE_1_0.0.
using Dali::Vector< T, IsTrivialType >::ConstIterator = const T*
Const iterator @SINCE_1_0.0.
using Dali::Vector< T, IsTrivialType >::ItemType = T
Item type @SINCE_1_0.0.
Dali::Vector< T, IsTrivialType >::Vector()=default
Default constructor. Does not allocate any space. @SINCE_1_0.0.
Dali::Vector< T, IsTrivialType >::Vector(SizeType count)
Create vector with count, without initialize value.
Only able for trivial types. @SINCE_2_3.22 count The count of vector.
References Dali::Vector< T, IsTrivialType >::ResizeUninitialized.
Dali::Vector< T, IsTrivialType >::~Vector()
Destructor. Releases the allocated space. @SINCE_1_0.0.
References Dali::Vector< T, IsTrivialType >::Release.
Dali::Vector< T, IsTrivialType >::Vector(const Vector &vector)
Copy constructor.
@SINCE_1_0.0 vector Vector to copy from
References Dali::Vector< T, IsTrivialType >::operator=.
Dali::Vector< T, IsTrivialType >::Vector(Vector &&vector) noexcept
Default move constructor.
@SINCE_1_9.25 vector Vector to move
References Dali::Vector< T, IsTrivialType >::operator=.
Vector & Dali::Vector< T, IsTrivialType >::operator=(const Vector &vector)
Assignment operator.
@SINCE_1_0.0 vector Vector to assign from Reference to self for chaining
Referenced by Dali::Vector< T, IsTrivialType >::Vector, Dali::Vector< T, IsTrivialType >::Vector.
Vector & Dali::Vector< T, IsTrivialType >::operator=(Vector &&vector) noexcept
Default move assignment operator.
@SINCE_1_9.25 vector Vector to move
Iterator Dali::Vector< T, IsTrivialType >::Begin() const
Iterator to the beginning of the data. @SINCE_1_0.0.
Iterator to the beginning of the data
References Dali::VectorBase::mData.
Referenced by Dali::Vector< T, IsTrivialType >::begin, Dali::AnimationData::Clear, Dali::AnimationData::CreateAnimation, Dali::Scripting::CreatePropertyMap, Dali::Vector< T, IsTrivialType >::Erase, Dali::Vector< T, IsTrivialType >::Erase, Dali::OwnerContainer< T >::EraseIf, Dali::OwnerContainer< T >::EraseObject, Dali::Vector< T, IsTrivialType >::Insert, Dali::Vector< T, IsTrivialType >::Insert, Dali::Vector< T, IsTrivialType >::Insert, Dali::OwnerContainer< T >::MoveFrom, Dali::Vector< T, IsTrivialType >::Remove.
Iterator Dali::Vector< T, IsTrivialType >::End() const
Iterator to the end of the data (one past last element). @SINCE_1_0.0.
Iterator to the end of the data (one past last element)
References Dali::VectorBase::Count, Dali::VectorBase::mData.
Referenced by Dali::AnimationData::Clear, Dali::OwnerContainer< T >::Clear, Dali::AnimationData::CreateAnimation, Dali::Scripting::CreatePropertyMap, Dali::Vector< T, IsTrivialType >::end, Dali::Vector< T, IsTrivialType >::Erase, Dali::Vector< T, IsTrivialType >::Erase, Dali::OwnerContainer< T >::EraseIf, Dali::OwnerContainer< T >::EraseObject, Dali::Vector< T, IsTrivialType >::Insert, Dali::Vector< T, IsTrivialType >::Insert, Dali::Vector< T, IsTrivialType >::Insert, Dali::OwnerContainer< T >::MoveFrom, Dali::Vector< T, IsTrivialType >::PushBack, Dali::Vector< T, IsTrivialType >::PushBack, Dali::Vector< T, IsTrivialType >::Remove, Dali::OwnerContainer< T >::Resize.
Iterator Dali::Vector< T, IsTrivialType >::begin() const
Support for C++11 Range-based for loop: for( item : container ). @SINCE_1_2.60 The start iterator
References Dali::Vector< T, IsTrivialType >::Begin.
Referenced by Dali::OwnerContainer< T >::EraseIf.
Iterator Dali::Vector< T, IsTrivialType >::end() const
Support for C++11 Range-based for loop: for( item : container ). @SINCE_1_2.60 The end iterator
References Dali::Vector< T, IsTrivialType >::End.
Referenced by Dali::OwnerContainer< T >::Clear, Dali::OwnerContainer< T >::EraseIf, Dali::OwnerContainer< T >::MoveFrom, Dali::OwnerContainer< T >::Resize.
ItemType & Dali::Vector< T, IsTrivialType >::operator[](SizeType index)
Subscript operator. @SINCE_1_0.0.
index Index of the element Reference to the element for given index Index must be in the vector's range.
Referenced by Dali::Vector< T, IsTrivialType >::PushBack, Dali::Vector< T, IsTrivialType >::PushBack.
const ItemType & Dali::Vector< T, IsTrivialType >::operator[](SizeType index) const
Subscript operator. @SINCE_1_0.0.
index Index of the element Reference to the element for given index Index must be in the vector's range.
References Dali::VectorBase::Count, DALI_ASSERT_VECTOR, Dali::VectorBase::mData.
ItemType & Dali::Vector< T, IsTrivialType >::Front()
Get the first element of vector. @SINCE_2_5.17.
Reference to the first element Vector must not be empty.
References Dali::Vector< T, IsTrivialType >::Front.
Referenced by Dali::Vector< T, IsTrivialType >::Front.
const ItemType & Dali::Vector< T, IsTrivialType >::Front() const
Get the first element of vector. @SINCE_2_5.17.
Reference to the first element Vector must not be empty.
References DALI_ASSERT_VECTOR, Dali::VectorBase::mData.
ItemType & Dali::Vector< T, IsTrivialType >::Back()
Get the last element of vector. @SINCE_2_5.17.
Reference to the last element Vector must not be empty.
References Dali::Vector< T, IsTrivialType >::Back.
Referenced by Dali::Vector< T, IsTrivialType >::Back.
const ItemType & Dali::Vector< T, IsTrivialType >::Back() const
Get the last element of vector. @SINCE_2_5.17.
Reference to the last element Vector must not be empty.
References Dali::VectorBase::Count, DALI_ASSERT_VECTOR, Dali::VectorBase::mData.
void Dali::Vector< T, IsTrivialType >::PushBack(const ItemType &element)
Pushes back an element to the vector.
The underlying storage may be reallocated to provide space. If this occurs, all pre-existing pointers into the vector will become invalid. @SINCE_1_0.0 element Element to be added
References Dali::VectorBase::Capacity, Dali::VectorBase::Count, Dali::Vector< T, IsTrivialType >::End, Dali::Vector< T, IsTrivialType >::Insert, Dali::Vector< T, IsTrivialType >::operator[], Dali::Vector< T, IsTrivialType >::Reserve, Dali::VectorBase::SetCount.
Referenced by Dali::AnimationData::Add, Dali::FreeList::Add, Dali::OwnerContainer< T >::MoveFrom, Dali::CircularQueue< ElementType >::PushBack, Dali::Vector< T, IsTrivialType >::Resize, Dali::VariableStepCondition.
void Dali::Vector< T, IsTrivialType >::PushBack(ItemType &&element)
Pushes back an element to the vector using move semantics.
The underlying storage may be reallocated to provide space. If this occurs, all pre-existing pointers into the vector will become invalid. @SINCE_2_5.16 element Element to be moved and added
References Dali::VectorBase::Capacity, Dali::VectorBase::Count, Dali::Vector< T, IsTrivialType >::End, Dali::Vector< T, IsTrivialType >::Insert, Dali::Vector< T, IsTrivialType >::operator[], Dali::Vector< T, IsTrivialType >::Reserve, Dali::VectorBase::SetCount.
void Dali::Vector< T, IsTrivialType >::Insert(Iterator at, const ItemType &element)
Inserts an element to the vector.
Elements after at are moved one position to the right. The underlying storage may be reallocated to provide space. If this occurs, all pre-existing pointers into the vector will become invalid. @SINCE_1_0.0 at Iterator where to insert the elements into the vector element An element to be added Iterator at must be in the vector's range ( Vector::Begin(), Vector::End() ).
References Dali::Vector< T, IsTrivialType >::Begin, DALI_ASSERT_VECTOR, Dali::Vector< T, IsTrivialType >::End.
Referenced by Dali::Vector< T, IsTrivialType >::PushBack, Dali::Vector< T, IsTrivialType >::PushBack.
void Dali::Vector< T, IsTrivialType >::Insert(Iterator at, ItemType &&element)
Inserts an element to the vector using move semantics.
Elements after at are moved one position to the right. The underlying storage may be reallocated to provide space. If this occurs, all pre-existing pointers into the vector will become invalid. @SINCE_2_5.16 at Iterator where to insert the element into the vector element An element to be moved and added Iterator at must be in the vector's range ( Vector::Begin(), Vector::End() ).
References Dali::Vector< T, IsTrivialType >::Begin, DALI_ASSERT_VECTOR, Dali::Vector< T, IsTrivialType >::End.
void Dali::Vector< T, IsTrivialType >::Insert(Iterator at, Iterator from, Iterator to)
Inserts the given elements into the vector.
Elements after at are moved the number of given elements positions to the right. The underlying storage may be reallocated to provide space. If this occurs, all pre-existing pointers into the vector will become invalid. @SINCE_1_0.0 at Iterator where to insert the elements into the vector from Iterator to the first element to be inserted to Iterator to the last element to be inserted Iterator at must be in the vector's range ( Vector::Begin(), Vector::End() ). Iterators from and to must be valid iterators. Iterator from must not be grater than Iterator to.
References Dali::Vector< T, IsTrivialType >::Begin, DALI_ASSERT_VECTOR, Dali::Vector< T, IsTrivialType >::End.
void Dali::Vector< T, IsTrivialType >::Reserve(SizeType count)
Reserves space in the vector.
Reserving less than current Capacity is a no-op. @SINCE_1_0.0 count Count of elements to reserve
Referenced by Dali::CircularQueue< ElementType >::CircularQueue, Dali::OwnerContainer< T >::MoveFrom, Dali::Vector< T, IsTrivialType >::PushBack, Dali::Vector< T, IsTrivialType >::PushBack, Dali::Vector< T, IsTrivialType >::Resize, Dali::CircularQueue< ElementType >::Resize, Dali::Vector< T, IsTrivialType >::ResizeUninitialized.
void Dali::Vector< T, IsTrivialType >::Resize(SizeType count)
Resizes the vector. Does not change capacity.
@SINCE_1_0.0 count Count to resize to
References Dali::Vector< T, IsTrivialType >::Resize.
Referenced by Dali::Vector< T, IsTrivialType >::Resize, Dali::OwnerContainer< T >::Resize, Dali::CircularQueue< ElementType >::Resize.
void Dali::Vector< T, IsTrivialType >::ResizeUninitialized(SizeType count)
Resizes the vector without initializing the data.
Can be used as a data container for reading whole file content. Only able for trivial types. @SINCE_1_9.27 count Count to resize to
References Dali::Vector< T, IsTrivialType >::Reserve, Dali::VectorBase::SetCount.
Referenced by Dali::Vector< T, IsTrivialType >::Vector.
void Dali::Vector< T, IsTrivialType >::Resize(SizeType count, const ItemType &item)
Resizes the vector. Does not change capacity.
@SINCE_1_0.0 count Count to resize to item An item to insert to the new indices
References Dali::VectorBase::Count, Dali::Vector< T, IsTrivialType >::PushBack, Dali::Vector< T, IsTrivialType >::Reserve, Dali::VectorBase::SetCount.
Iterator Dali::Vector< T, IsTrivialType >::Erase(Iterator iterator)
Erases an element.
Does not change capacity. Other elements get moved. @SINCE_1_0.0 iterator Iterator pointing to the item to remove Iterator pointing to next element Iterator iterator must be within the vector's range ( Vector::Begin(), Vector::End() - 1 ).
References Dali::Vector< T, IsTrivialType >::Begin, DALI_ASSERT_VECTOR, Dali::Vector< T, IsTrivialType >::End, Dali::Vector< T, IsTrivialType >::Remove.
Referenced by Dali::OwnerContainer< T >::Erase, Dali::OwnerContainer< T >::Erase, Dali::OwnerContainer< T >::EraseIf, Dali::OwnerContainer< T >::Release, Dali::Vector< T, IsTrivialType >::Remove.
Iterator Dali::Vector< T, IsTrivialType >::Erase(Iterator first, Iterator last)
Erases a range of elements.
Does not change capacity. Other elements get moved. @SINCE_1_0.0 first Iterator to the first element to be erased last Iterator to the last element to be erased Iterator pointing to the next element of the last one Iterator first must be in the vector's range ( Vector::Begin(), Vector::End() ). Iterator last must be in the vector's range ( Vector::Begin(), Vector::End() ). Iterator first must not be grater than Iterator last.
References Dali::Vector< T, IsTrivialType >::Begin, Dali::VectorBase::Count, DALI_ASSERT_VECTOR, Dali::Vector< T, IsTrivialType >::End, Dali::VectorBase::SetCount.
void Dali::Vector< T, IsTrivialType >::Remove(Iterator iterator)
Removes an element.
Does not maintain order. Swaps the element with end and decreases size by one. This is much faster than Erase so use this in case order does not matter. Does not change capacity. @SINCE_1_0.0 iterator Iterator pointing to the item to remove Iterator iterator must be in the vector's range ( Vector::Begin(), Vector::End() - 1 ).
References Dali::Vector< T, IsTrivialType >::Begin, Dali::VectorBase::Count, DALI_ASSERT_VECTOR, Dali::Vector< T, IsTrivialType >::End, Dali::Vector< T, IsTrivialType >::Erase, Dali::VectorBase::SetCount, Dali::Swap.
Referenced by Dali::Vector< T, IsTrivialType >::Erase.
void Dali::Vector< T, IsTrivialType >::Swap(Vector &vector)
Swaps the contents of two vectors.
@SINCE_1_0.0 vector Vector to swap with
References Dali::VectorBase::Swap.
Referenced by Dali::CircularQueue< ElementType >::Resize.
void Dali::Vector< T, IsTrivialType >::Clear()
Clears the contents of the vector. Keeps its capacity. @SINCE_1_0.0.
Referenced by Dali::AnimationData::Clear, Dali::CircularQueue< ElementType >::Clear, Dali::OwnerContainer< T >::Clear, Dali::TypeInfo::GetChildPropertyIndices, Dali::TypeInfo::GetPropertyIndices.
void Dali::Vector< T, IsTrivialType >::Release()
Releases the memory that the vector holds. @SINCE_1_0.0.
Referenced by Dali::Vector< T, IsTrivialType >::~Vector.
void Dali::Vector< T, IsTrivialType >::ShrinkToFit()
Fit the capacity of vector as item counts.
@SINCE_2_3.22
References Dali::VectorBase::ShrinkToFit.
void Dali::Vector< T, IsTrivialType >::ShrinkToFitIfNeeded()
Fit the capacity of vector as item counts only if low spec memory management enabled, and the count is much smaller than capacity. It will be used when we want to remove unused memory.
@SINCE_2_3.22
References Dali::VectorBase::Capacity, Dali::VectorBase::Count, DALI_UNLIKELY, Dali::VectorBase::SHRINK_REQUIRED_RATIO, Dali::VectorBase::ShrinkToFit.