Dali::Matrix3
const Matrix3 Dali::Matrix3::IDENTITY
The identity matrix.
float Dali::Matrix3::mElements[9][9]
The elements of the matrix.
Dali::Matrix3::Matrix3()
Constructor. @SINCE_1_0.0.
References AsFloat.
Dali::Matrix3::Matrix3(const Matrix3 &m)
Copy Constructor.
@SINCE_1_0.0 m A reference to the copied 3x3 matrix
Dali::Matrix3::Matrix3(const Matrix &m)
Constructor.
@SINCE_1_0.0 m A 4x4 matrix. The translation and shear components are ignored
References Dali::Matrix::AsFloat, S00, S10, S20.
Dali::Matrix3::Matrix3(float s00, float s01, float s02, float s10, float s11, float s12, float s20, float s21, float s22)
Constructor.
@SINCE_1_0.0 s00 First element s01 Second element s02 Third element s10 Fourth element s11 Fifth element s12 Sixth element s20 Seventh element s21 Eighth element s22 Ninth element
References S00, S01, S02, S10, S11, S12, S20, S21, S22.
Dali::Matrix3::Matrix3(Matrix3 &&matrix) noexcept
Move constructor.
@SINCE_1_9.21 matrix A reference to the moved matrix
Matrix3 & Dali::Matrix3::operator=(Matrix3 &&matrix) noexcept
Move assignment operator.
@SINCE_1_9.21 matrix A reference to the moved matrix A reference to this
Matrix3 & Dali::Matrix3::operator=(const Matrix3 &matrix)
Assignment Operator. @SINCE_1_0.0.
matrix From which to copy values Reference to this object
References AsFloat.
Matrix3 & Dali::Matrix3::operator=(const Matrix &matrix)
Assignment Operator. @SINCE_1_0.0.
matrix A reference to the copied matrix A reference to this
References Dali::Matrix::AsFloat, S00, S10, S20.
bool Dali::Matrix3::operator==(const Matrix3 &rhs) const
The equality operator.
Utilizes appropriate machine epsilon values. @SINCE_1_0.0 rhs The Matrix to compare this to True if the matrices are equal
References Dali::Equals.
bool Dali::Matrix3::operator!=(const Matrix3 &rhs) const
The inequality operator.
Utilizes appropriate machine epsilon values. @SINCE_1_0.0 rhs The Matrix to compare this to true if the matrices are equal
Dali::Matrix3::~Matrix3()=default
Destructor. @SINCE_1_0.0.
void Dali::Matrix3::SetIdentity()
Sets the matrix to the identity matrix. @SINCE_1_0.0.
References S00, S11, S22.
const float * Dali::Matrix3::AsFloat() const
Returns the contents of the matrix as an array of 9 floats.
The order of the values for a matrix is: [xAxis.x,xAxis.y,xAxis.z,yAxis.x,yAxis.y,yAxis.z,zAxis.x,zAxis.y,zAxis.z] @SINCE_1_0.0 The matrix contents as an array of 9 floats
Referenced by Matrix3, Dali::operator<<, operator=.
float * Dali::Matrix3::AsFloat()
Returns the contents of the matrix as an array of 9 floats.
The order of the values for a matrix is: [xAxis.x,xAxis.y,xAxis.z,yAxis.x,yAxis.y,yAxis.z,zAxis.x,zAxis.y,zAxis.z] @SINCE_1_0.0 The matrix contents as an array of 9 floats
bool Dali::Matrix3::Invert()
Inverts the matrix.
@SINCE_1_0.0 True if successful
References Dali::EqualsZero, S00, S01, S02, S10, S11, S12, S20, S21, S22.
bool Dali::Matrix3::Transpose()
Swaps the rows to columns. @SINCE_1_0.0.
True if successful
References S01, S02, S10, S12, S20, S21.
void Dali::Matrix3::Scale(float scale)
Multiplies all elements of the matrix by the scale value.
@SINCE_1_0.0 scale The value by which to scale the whole matrix
References S00, S01, S02, S10, S11, S12, S20, S21, S22.
float Dali::Matrix3::Magnitude() const
Magnitude returns the average of the absolute values of the elements * 3.
(The Magnitude of the unit matrix is therefore 1) @SINCE_1_0.0 The magnitude - always positive
bool Dali::Matrix3::ScaledInverseTranspose()
If the matrix is invertible, then this method inverts, transposes and scales the matrix such that the resultant element values average 1.
If the matrix is not invertible, then the matrix is left unchanged. @SINCE_1_0.0 true if the matrix is invertible, otherwise false
References Dali::EqualsZero, S00, S01, S02, S10, S11, S12, S20, S21, S22.
Matrix3 Dali::Matrix3::operator*(const Matrix3 &rhs) const
Multiplication operator.
Returned Matrix = This Matrix * rhs It makes some memory allocate & copy internally. Use Matrix3::Multiply API for time critical path. @SINCE_2_1.44 rhs The Matrix to multiply this by A Matrix containing the result
Matrix3 & Dali::Matrix3::operator*=(const Matrix3 &rhs)
Multiplication assignment operator.
This Matrix *= rhs It makes some memory allocate & copy internally. @SINCE_2_1.46 rhs The Matrix to multiply this by Itself
Vector3 Dali::Matrix3::operator*(const Vector3 &rhs) const
The multiplication operator.
Returned Vector = This Matrix * rhs @SINCE_2_1.34 rhs The Vector3 to multiply this by A Vector3 containing the result
References S00, S01, S02, S10, S11, S12, S20, S21, S22, Dali::Vector3::x, Dali::Vector3::y, Dali::Vector3::z.
void Dali::Matrix3::Multiply(Matrix3 &result, const Matrix3 &lhs, const Matrix3 &rhs)
Function to multiply two matrices and store the result onto third.
Use this method in time critical path as it does not require temporaries result = rhs * lhs @SINCE_1_0.0 result Result of the multiplication lhs Matrix, this can be same matrix as result rhs Matrix, this cannot be same matrix as result