Dali::String
constexpr size_t Dali::String::StorageSize
Opaque storage sized for std::string.
constexpr size_t Dali::String::StorageAlign
Opaque storage aligned for std::string.
uint8_t Dali::String::mStorage[StorageSize][StorageSize]
Dali::String::String()
Constructor.
@SINCE_2_5.15 Creates an empty string.
Dali::String::String(const char *str)
Constructor.
@SINCE_2_5.15 str A null-terminated string
Dali::String::String(const StringView &view)
Constructor from a StringView.
@SINCE_2_5.14 view The string view to copy from
References Dali::StringView::Data, Dali::StringView::Size.
Dali::String::~String()
Destructor.
Dali::String::String(const String &other)
Copy constructor.
@SINCE_2_5.15 other The string to copy
String & Dali::String::operator=(const String &other)
Assignment operator.
@SINCE_2_5.15 other The string to copy A reference to this string
String & Dali::String::operator=(const char *other)
Assignment operator.
@SINCE_2_5.14 other The string to copy A reference to this string
Dali::String::String(String &&other) noexcept
Move constructor.
@SINCE_2_5.15 other The string to move
String & Dali::String::operator=(String &&other) noexcept
Assignment move operator.
@SINCE_2_5.15 other The string to move A reference to this string
String & Dali::String::operator=(const StringView &view)
Assignment operator from a StringView.
@SINCE_2_5.14 view The string view to copy from A reference to this string
References Dali::StringView::Data, Dali::StringView::Size.
uint32_t Dali::String::Size() const
Get the number of bytes in the string.
@SINCE_2_5.15 the number of bytes in the string
Referenced by Dali::StringView::operator==, Dali::StringView::StringView.
bool Dali::String::Empty() const
Determine if the string is empty.
@SINCE_2_5.15 true if the string has no characters
Referenced by operator==.
void Dali::String::Clear()
Clear the string as empty.
@SINCE_2_5.17
const char * Dali::String::CStr() const
Get a pointer to a null-terminated character array that is equivalent to the string content.
@SINCE_2_5.15 The zero terminated c-string
Referenced by Dali::Scripting::GetEnumerationProperty, Dali::StringView::operator==, Dali::StringView::StringView.
char & Dali::String::operator[](uint32_t position)
Get a character at the given position.
@SINCE_2_5.15 position The position in the string to index a modifiable reference to the character
const char & Dali::String::operator[](uint32_t position) const
Get a character at the given position.
@SINCE_2_5.15 position The position in the string to index an unmodifiable reference to the character
String & Dali::String::operator+=(char c)
Append operator.
@SINCE_2_5.15 c The character to append A reference to this string
String & Dali::String::operator+=(const String &other)
Append operator.
@SINCE_2_5.15 other the string to append A reference to this string
bool Dali::String::operator==(const String &other) const
Comparison equality operator.
@SINCE_2_5.15 other The string to compare True if both strings are equal
bool Dali::String::operator==(const char *other) const
Comparison equality operator.
@SINCE_2_5.14 other The string to compare True if both strings are equal
References Empty.
bool Dali::String::operator==(const StringView &other) const
Comparison equality operator.
@SINCE_2_5.18 other The string to compare True if both strings are equal
bool Dali::String::operator!=(const String &other) const
Comparison inequality operator.
@SINCE_2_5.15 other The string to compare True if both strings are not equal
bool Dali::String::operator<(const String &other) const
Comparison less than operator.
@SINCE_2_5.15 other The string to compare True if this is lexically less than the other string
bool Dali::String::operator>(const String &other) const
Comparison greater than operator.
@SINCE_2_5.15 other The string to compare True if this is lexically greater than the other string
bool Dali::String::operator<=(const String &other) const
Comparison less than or equal operator.
@SINCE_2_5.15 other The string to compare True if this is lexically less than or equal to the other string
bool Dali::String::operator>=(const String &other) const
Comparison greater than or equal operator.
@SINCE_2_5.15 other The string to compare True if this is lexically greater than or equal to the other string
DALI_CORE_API String operator+(const String &lhs, const String &rhs)
Concatenation operator.
Use of friend enables infix notation on free function, whilst retaining documentation inside the class scope. @SINCE_2_5.14 lhs The left operand string rhs The right operand string A new String containing the concatenation of lhs and rhs