Dali::SignalConnectionPool
SignalConnectionBlock* Dali::SignalConnectionPool::mFirstBlock
Head of block chain.
SignalConnectionBlock* Dali::SignalConnectionPool::mCurrentBlock
Block being filled.
void* Dali::SignalConnectionPool::mFreeHead
Intrusive free list head.
uint32_t Dali::SignalConnectionPool::mBlockCount
Number of blocks allocated.
Dali::SignalConnectionPool::SignalConnectionPool()=default
Constructor. @SINCE_2_5.17.
Dali::SignalConnectionPool::~SignalConnectionPool()
Destructor. Frees all block memory.
The caller (BaseSignal) must disconnect and free all live connections before destruction. The pool destructor only frees raw block memory. @SINCE_2_5.17
References Dali::SignalConnectionBlock::mNext.
Dali::SignalConnectionPool::SignalConnectionPool(const SignalConnectionPool &)=delete
Deleted copy constructor @SINCE_2_5.17.
Dali::SignalConnectionPool::SignalConnectionPool(SignalConnectionPool &&)=delete
Deleted move constructor @SINCE_2_5.17.
SignalConnectionPool & Dali::SignalConnectionPool::operator=(const SignalConnectionPool &)=delete
Deleted copy assignment @SINCE_2_5.17.
SignalConnectionPool & Dali::SignalConnectionPool::operator=(SignalConnectionPool &&)=delete
Deleted move assignment @SINCE_2_5.17.
SignalConnectionNode * Dali::SignalConnectionPool::Allocate(CallbackBase *callback)
Allocate a node and construct a SignalConnection with a callback.
Recycles from the free list if available, otherwise allocates from the current block (growing the pool if necessary). @SINCE_2_5.17 callback The callback to store (takes ownership) Pointer to the constructed node (stable for pool lifetime)
Referenced by Dali::BaseSignal::OnConnect, Dali::BaseSignal::OnConnect.
SignalConnectionNode * Dali::SignalConnectionPool::Allocate(ConnectionTrackerInterface *tracker, CallbackBase *callback)
Allocate a node and construct a SignalConnection with tracker and callback.
@SINCE_2_5.17 tracker The connection tracker callback The callback to store (takes ownership) Pointer to the constructed node (stable for pool lifetime)
void Dali::SignalConnectionPool::Free(SignalConnectionNode *node)
Free a node. Destructs the SignalConnectionNode and adds the slot to the free list.
@SINCE_2_5.17 node Pointer to the node to free
References Dali::SignalConnectionNode::~SignalConnectionNode.
SignalConnectionBlock * Dali::SignalConnectionPool::GetFirstBlock() const
Get the first block in the chain (for iteration). @SINCE_2_5.17.
Pointer to the first block, or nullptr if empty
Referenced by Dali::BaseSignal::~BaseSignal.
uint32_t Dali::SignalConnectionPool::GetBlockCount() const
Get the number of blocks allocated. @SINCE_2_5.17.
The block count
Referenced by Dali::BaseSignal::OnConnect, Dali::BaseSignal::OnConnect.
SignalConnectionNode * Dali::SignalConnectionPool::IndexToNode(uint32_t index) const
Convert a global node index to a node pointer. @SINCE_2_5.17.
index The node index (0xFFFF = null) Pointer to the node, or nullptr if index is invalid
References Dali::SignalConnectionNode::INVALID_INDEX, Dali::SignalConnectionBlock::Slots.
uint32_t Dali::SignalConnectionPool::NodeToIndex(const SignalConnectionNode *node) const
Convert a node pointer to its global index. @SINCE_2_5.17.
node Pointer to the node The node's index, or 0xFFFF if not found
References Dali::SignalConnectionNode::INVALID_INDEX, Dali::SignalConnectionBlock::Slots.
void Dali::SignalConnectionPool::AllocateBlock()
Allocate a new block with double the previous capacity. @SINCE_2_5.17.
void * Dali::SignalConnectionPool::AllocateRaw()
Allocate raw memory from the pool (free list or current block). @SINCE_2_5.17.
Pointer to raw memory for one SignalConnection