Dali::Texture
Texture Dali::Texture::New(TextureType::Type type, Pixel::Format format, uint32_t width, uint32_t height)
Creates a new Texture object.
@SINCE_1_1.43 type The type of the texture format The format of the pixel data width The width of the texture height The height of the texture A handle to a newly allocated Texture
References Texture.
Texture Dali::Texture::New(TextureType::Type type)
Creates a new Texture object with no informations. Texture will use Uploaded PixelData size and format. Before texture Upload is called, width, height and format return invalid values.
@SINCE_2_2.34 type The type of the texture A handle to a newly allocated Texture
References Dali::Pixel::INVALID, Texture.
Texture Dali::Texture::New(NativeImageInterface &nativeImageInterface)
Creates a new Texture object from a native image.
@SINCE_1_1.43 nativeImageInterface A native image A handle to a newly allocated Texture It is not possible to upload data to textures created from a native image using Upload methods although there might be platform specific APIs to upload data to a native image.
References Texture.
Texture Dali::Texture::DownCast(BaseHandle handle)
Downcasts to a texture. If not, the returned handle is left uninitialized.
@SINCE_1_1.43 handle Handle to an object Texture handle or an uninitialized handle
References Dali::BaseHandle::GetObjectPtr, Texture.
Dali::Texture::Texture()
Default constructor, creates an empty handle.
@SINCE_1_1.43
Referenced by DownCast, New, New, New.
Dali::Texture::~Texture()
Destructor.
@SINCE_1_1.43
Dali::Texture::Texture(const Texture &handle)
Copy constructor, creates a new handle to the same object.
@SINCE_1_1.43 handle Handle to an object
References Dali::DownCast.
Texture & Dali::Texture::operator=(const Texture &handle)
Assignment operator, changes this handle to point at the same object.
@SINCE_1_1.43 handle Handle to an object Reference to the assigned object
Dali::Texture::Texture(Texture &&rhs) noexcept
Move constructor.
@SINCE_1_9.22 rhs A reference to the moved handle
Texture & Dali::Texture::operator=(Texture &&rhs) noexcept
Move assignment operator.
@SINCE_1_9.22 rhs A reference to the moved handle A reference to this handle
bool Dali::Texture::Upload(PixelData pixelData)
Uploads data to the texture from a PixelData object.
@SINCE_1_1.43 pixelData The pixelData object True if the PixelData object has compatible pixel format and fits within the texture, false otherwise
References Dali::GetImplementation.
bool Dali::Texture::Upload(PixelData pixelData, uint32_t layer, uint32_t mipmap, uint32_t xOffset, uint32_t yOffset, uint32_t width, uint32_t height)
Uploads data to the texture from a PixelData object.
Upload does not upsample or downsample pixel data to fit the specified rectangular area in the texture. @SINCE_1_1.43 pixelData The pixelData object layer Specifies the layer of a cube map or array texture (Unused for 2D textures). CubeMapLayer mipmap Specifies the level-of-detail number. Level 0 is the base image level. Level n is the nth mipmap reduction image xOffset Specifies an horizontal offset of the rectangular area in the texture that will be updated yOffset Specifies a vertical offset of the rectangular area in the texture that will be updated width Specifies the width of the rectangular area in the texture that will be updated height Specifies the height of the rectangular area in the texture that will be updated True if the PixelData object has compatible pixel format and fits in the rectangle specified, false otherwise
References Dali::GetImplementation.
void Dali::Texture::GenerateMipmaps()
Generates mipmaps for the texture. This will auto generate all the mipmaps for the texture based on the data in the base level.
@SINCE_1_1.43
References Dali::GetImplementation.
uint32_t Dali::Texture::GetWidth() const
Returns the width of the texture.
@SINCE_1_1.43 The width, in pixels, of the texture
References Dali::GetImplementation.
uint32_t Dali::Texture::GetHeight() const
Returns the height of the texture.
@SINCE_1_1.43 The height, in pixels, of the texture
References Dali::GetImplementation.
Pixel::Format Dali::Texture::GetPixelFormat() const
Returns the pixel format of the texture.
@SINCE_2_1.29 The pixel format of the texture
References Dali::GetImplementation.
Dali::Texture::Texture(Internal::Texture *pointer)
The constructor.
Not intended for application developers. @SINCE_1_1.43 pointer A pointer to a newly allocated Texture