Dali::IntrusivePtr
T* Dali::IntrusivePtr< T >::mPtr
pointer to RefObject
Dali::IntrusivePtr< T >::IntrusivePtr()
Standard constructor to unassigned object. @SINCE_1_0.0.
Referenced by Dali::IntrusivePtr< T >::operator=, Dali::IntrusivePtr< T >::operator=, Dali::IntrusivePtr< T >::Reset, Dali::IntrusivePtr< T >::Reset.
Dali::IntrusivePtr< T >::IntrusivePtr(T *p)
Constructor to attach existing object.
@SINCE_1_0.0 p Pointer to object
Dali::IntrusivePtr< T >::IntrusivePtr(IntrusivePtr< U > const &rhs)
Copy constructor.
@SINCE_1_0.0 rhs Const reference to an IntrusivePtr U Reference counter object type
Dali::IntrusivePtr< T >::IntrusivePtr(IntrusivePtr const &rhs)
Copy constructor. @SINCE_1_0.0.
rhs Const reference to an IntrusivePtr
Dali::IntrusivePtr< T >::IntrusivePtr(IntrusivePtr< U > &&rhs) noexcept
Move constructor. @SINCE_1_9.23.
rhs Reference to an IntrusivePtr
Dali::IntrusivePtr< T >::IntrusivePtr(IntrusivePtr &&rhs) noexcept
Move constructor. @SINCE_1_9.23.
rhs Reference to an IntrusivePtr
Dali::IntrusivePtr< T >::~IntrusivePtr()
Destructor.
Object will self-destruct if reference count is zero. @SINCE_1_0.0
T * Dali::IntrusivePtr< T >::Get() const
Gets pointer to reference counted object.
@SINCE_1_0.0 Pointer to reference counted object
Referenced by Dali::BaseHandle::GetObjectPtr, Dali::PixelData::New, Dali::PixelData::New, Dali::Integration::NewPixelDataWithReleaseAfterUpload, Dali::operator!=, Dali::operator!=, Dali::operator!=, Dali::operator!=, Dali::operator!=, Dali::operator<, Dali::operator<, Dali::operator<, Dali::operator<, Dali::operator==, Dali::operator==, Dali::operator==, Dali::operator==, Dali::operator==.
T * Dali::IntrusivePtr< T >::operator->() const
Pointer operator override.
@SINCE_1_0.0 Pointer to reference counted object
T & Dali::IntrusivePtr< T >::operator*() const
Dereference operator override.
@SINCE_1_0.0 Reference to reference counted object
IntrusivePtr & Dali::IntrusivePtr< T >::operator=(IntrusivePtr const &rhs)
Assignment operator.
@SINCE_1_0.0 rhs Const reference to intrusive pointer Reference to reference counted object
References Dali::IntrusivePtr< T >::IntrusivePtr.
IntrusivePtr & Dali::IntrusivePtr< T >::operator=(T *rhs)
Assignment operator.
@SINCE_1_0.0 rhs Pointer to object to wrap A Reference to this object
References Dali::IntrusivePtr< T >::IntrusivePtr.
IntrusivePtr & Dali::IntrusivePtr< T >::operator=(IntrusivePtr &&rhs) noexcept
Move assignment operator.
@SINCE_1_9.23 rhs Reference to intrusive pointer Reference to moved intrusive pointer
IntrusivePtr & Dali::IntrusivePtr< T >::operator=(IntrusivePtr< U > &&rhs) noexcept
Move assignment operator.
@SINCE_1_9.23 rhs Reference to intrusive pointer Reference to moved intrusive pointer
void Dali::IntrusivePtr< T >::Reset()
Reset intrusive pointer. @SINCE_1_0.0.
References Dali::IntrusivePtr< T >::IntrusivePtr.
void Dali::IntrusivePtr< T >::Reset(T *rhs)
Reset intrusive pointer with reference counted object.
@SINCE_1_0.0 rhs Pointer to object
References Dali::IntrusivePtr< T >::IntrusivePtr.
Dali::IntrusivePtr< T >::operator bool() const
Converts an object handle to a bool.
This is useful for checking whether the handle is NULL. @SINCE_1_0.0
T * Dali::IntrusivePtr< T >::Detach()
Detaches pointer from intrusive ptr counting.
Use with care. @SINCE_1_0.0 Pointer to reference counted object
void Dali::IntrusivePtr< T >::Swap(IntrusivePtr &rhs)
Internal swap function. @SINCE_1_0.0.