Dali::BaseObject
Impl* Dali::BaseObject::mImpl
bool Dali::BaseObject::ConnectSignal(ConnectionTrackerInterface *connectionTracker, const Dali::StringView &signalName, T &&functor)
Connects a void() functor to a specified signal.
@SINCE_1_0.0 connectionTracker A connection tracker which can be used to disconnect signalName Name of the signal to connect to functor The functor to move True if the signal was available The signal must be available in this object.
bool Dali::BaseObject::DoAction(const Dali::StringView &actionName, const Property::Map &attributes)
Performs an action on this object with the given action name and attributes.
Usage example: - BaseHandlehandle=SomeClass::New();//InitializedwithNew()method Property::Mapattributes;//TypeisPropertyMap handle.DoAction("show",attributes); @SINCE_1_0.0 actionName The command for the action attributes The list of attributes for the action The action is performed by the object or not
References Dali::Integration::ToStdString.
Referenced by Dali::BaseHandle::DoAction.
Dali::String Dali::BaseObject::GetTypeName() const
Returns the type name for the Handle.
Will return an empty string if the typename does not exist. This will happen for types that have not registered with type-registry. @SINCE_1_0.0 The type name. Empty string if the typename does not exist
References DALI_LOG_ERROR.
Referenced by Dali::BaseHandle::GetTypeName, Dali::TypeRegistry::GetTypeName.
bool Dali::BaseObject::GetTypeInfo(Dali::TypeInfo &info) const
Returns the type info for the Handle.
@SINCE_1_0.0 info The type information true if the type info exists
Referenced by Dali::TypeRegistry::GetTypeInfo, Dali::TypeRegistry::GetTypeInfo, Dali::BaseHandle::GetTypeInfo.
bool Dali::BaseObject::DoConnectSignal(ConnectionTrackerInterface *connectionTracker, const Dali::StringView &signalName, FunctorDelegate *functorDelegate)
Not intended for application developers.
@SINCE_1_0.0 connectionTracker A connection tracker which can be used to disconnect signalName Name of the signal to connect to functorDelegate A newly allocated functor delegate (takes ownership) True if the signal was available
References Dali::Integration::ToStdString.
Dali::BaseObject::BaseObject()
Default constructor. @SINCE_1_0.0.
Dali::BaseObject::~BaseObject() override
A reference counted object may only be deleted by calling Unreference(). @SINCE_1_0.0.
void Dali::BaseObject::OnDestroy() override
Pre-destructor method for derived class. It will be called when the reference count become zero.
@SINCE_2_3.39 If Derived class override this function, derived class MUST call base class function.
References DALI_ASSERT_ALWAYS.
void Dali::BaseObject::RegisterObject()
Registers the object as created with the Object registry. @SINCE_1_0.0.
void Dali::BaseObject::UnregisterObject()
Unregisters the object from Object registry. @SINCE_1_0.0.
Dali::BaseObject::BaseObject(const BaseObject &rhs)=delete
Deleted copy constructor.
Dali::BaseObject::BaseObject(BaseObject &&rhs)=delete
Deleted move constructor.
BaseObject & Dali::BaseObject::operator=(const BaseObject &rhs)=delete
Deleted copy assignment operator.
BaseObject & Dali::BaseObject::operator=(BaseObject &&rhs)=delete
Deleted move assignment operator.