Dali::BaseHandle
IntrusivePtr<Dali::RefObject> Dali::BaseHandle::mObjectHandle
Object this handle points at.
Dali::BaseHandle::BaseHandle(Dali::BaseObject *handle)
This constructor is used by Dali New() methods.
@SINCE_1_0.0 handle A pointer to a newly allocated Dali resource
Dali::BaseHandle::BaseHandle()
This constructor provides an uninitialized Dali::BaseHandle.
This should be initialized with a Dali New() method before use. Methods called on an uninitialized Dali::BaseHandle will assert. BaseHandlehandle;//uninitialized handle.SomeMethod();//unsafe!Thiswillassert handle=SomeClass::New();//nowinitialized handle.SomeMethod();//safe @SINCE_1_0.0
Dali::BaseHandle::~BaseHandle()
Dali::BaseHandle is intended as a base class.
This is non-virtual since derived BaseHandle types must not contain data. @SINCE_1_0.0
Dali::BaseHandle::BaseHandle(const BaseHandle &handle)
This copy constructor is required for (smart) pointer semantics.
@SINCE_1_0.0 handle A reference to the copied handle
BaseHandle & Dali::BaseHandle::operator=(const BaseHandle &rhs)
This assignment operator is required for (smart) pointer semantics.
It makes this handle use the same BaseObject as the copied handle @SINCE_1_0.0 rhs A reference to the copied handle A reference to this handle
Referenced by Dali::PathConstrainer::operator=.
Dali::BaseHandle::BaseHandle(BaseHandle &&rhs) noexcept
Move constructor.
@SINCE_1_9.22 rhs A reference to the moved handle
BaseHandle & Dali::BaseHandle::operator=(BaseHandle &&rhs) noexcept
Move assignment operator.
@SINCE_1_9.22 rhs A reference to the moved handle A reference to this handle
bool Dali::BaseHandle::ConnectSignal(ConnectionTrackerInterface *connectionTracker, const Dali::StringView &signalName, T &&functor)
Connects a void() functor to a specified signal.
@SINCE_1_0.0 connectionTracker A connection tracker which can be used to disconnect signalName Name of the signal to connect to functor The functor to move True if the signal was available The signal must be available in this object.
bool Dali::BaseHandle::DoAction(const Dali::StringView &actionName, const Property::Map &attributes)
Performs an action on this object with the given action name and attributes.
Usage example: - BaseHandlehandle=SomeClass::New();//InitializedwithNew()method Property::Mapattributes;//TypeisPropertyMap handle.DoAction("show",attributes); @SINCE_1_0.0 actionName The command for the action attributes The list of attributes for the action The action is performed by the object or not
References Dali::BaseObject::DoAction, Dali::GetImplementation.
Dali::String Dali::BaseHandle::GetTypeName() const
Returns the type name for the Handle.
Will return an empty string if the typename does not exist. This will happen for types that have not registered with type-registry. @SINCE_1_0.0 The type name. Empty string if the typename does not exist
References Dali::GetImplementation, Dali::BaseObject::GetTypeName.
Referenced by Dali::Scripting::CreatePropertyMap.
bool Dali::BaseHandle::GetTypeInfo(Dali::TypeInfo &info) const
Returns the type info for the Handle.
@SINCE_1_0.0 info The type information true if the type info exists
References Dali::GetImplementation, Dali::BaseObject::GetTypeInfo.
BaseObject & Dali::BaseHandle::GetBaseObject()
Retrieves the internal Dali resource.
This is useful for checking the reference count of the internal resource. This method will not check the validity of the handle so the caller is expected to check it by using if (handle). @SINCE_1_0.0 The BaseObject which is referenced by the BaseHandle
Referenced by Dali::GetImplementation, Dali::GetImplementation.
const BaseObject & Dali::BaseHandle::GetBaseObject() const
Retrieves the internal Dali resource.
This is useful for checking the reference count of the internal resource. This method will not check the validity of the handle so the caller is expected to check it by using if (handle). @SINCE_1_0.0 The BaseObject which is referenced by the BaseHandle
void Dali::BaseHandle::Reset()
Resets the handle.
If no other handle copies exist, the internal Dali resource will be deleted. Calling this is not required i.e. it will happen automatically when a Dali::BaseHandle is destroyed. @SINCE_1_0.0
Referenced by Dali::UnparentAndReset.
Dali::BaseHandle::operator bool() const
Converts an handle to a bool.
This is useful for checking whether the handle is empty. @SINCE_1_0.0
bool Dali::BaseHandle::operator==(const BaseHandle &rhs) const
Equality operator overload.
@SINCE_1_0.0 rhs A reference to the compared handle True if the handle handles point to the same Dali resource, or if both are NULL
bool Dali::BaseHandle::operator!=(const BaseHandle &rhs) const
Inequality operator overload.
@SINCE_1_0.0 rhs A reference to the compared handle True if the handle handles point to the different Dali resources
Dali::RefObject * Dali::BaseHandle::GetObjectPtr() const
Gets the reference counted object pointer.
@SINCE_1_0.0 A pointer to the reference counted object
References Dali::IntrusivePtr< T >::Get.
Referenced by Dali::Constraint::DownCast, Dali::PathConstrainer::DownCast, Dali::DecoratedVisualRenderer::DownCast, Dali::VisualRenderer::DownCast, Dali::Integration::Scene::DownCast, Dali::Actor::DownCast, Dali::CameraActor::DownCast, Dali::CustomActor::DownCast, Dali::Layer::DownCast, Dali::Animation::DownCast, Dali::KeyFrames::DownCast, Dali::LinearConstrainer::DownCast, Dali::Path::DownCast, Dali::GestureDetector::DownCast, Dali::LongPressGestureDetector::DownCast, Dali::PanGestureDetector::DownCast, Dali::PinchGestureDetector::DownCast, Dali::RotationGestureDetector::DownCast, Dali::TapGestureDetector::DownCast, Dali::Handle::DownCast, Dali::PropertyNotification::DownCast, Dali::RenderTaskList::DownCast, Dali::RenderTask::DownCast, Dali::FrameBuffer::DownCast, Dali::Geometry::DownCast, Dali::Renderer::DownCast, Dali::Sampler::DownCast, Dali::Shader::DownCast, Dali::TextureSet::DownCast, Dali::Texture::DownCast, Dali::UniformBlock::DownCast, Dali::VertexBuffer::DownCast, Dali::WeakHandleBase::Impl::Impl, Dali::BaseObjectObserver::Impl::Impl, Dali::operator<.
bool Dali::BaseHandle::DoConnectSignal(ConnectionTrackerInterface *connectionTracker, const Dali::StringView &signalName, FunctorDelegate *functorDelegate)
Not intended for application developers.
@SINCE_1_0.0 connectionTracker A connection tracker which can be used to disconnect signalName Name of the signal to connect to functorDelegate A newly allocated functor delegate (takes ownership) True if the signal was available