Dali::Quaternion
const Quaternion Dali::Quaternion::IDENTITY
(0.0f,0.0f,0.0f,1.0f)
Vector4 Dali::Quaternion::mVector
w component is s ( = cos(theta/2.0) )
Referenced by AngleBetween, AsVector, Conjugate, Dot, EulerAngles, Exp, Dali::Matrix::GetTransformComponents, IsIdentity, Length, LengthSquared, Log, operator*, operator*, operator*, operator*=, Dali::Vector3::operator*=, operator*=, operator+, operator+=, operator-, operator-, operator-=, operator/, operator/=, operator==, Quaternion, Quaternion, Rotate, SetEuler, Dali::Matrix::SetInverseTransformComponents, Dali::Matrix::SetTransformComponents, ToAxisAngle.
Dali::Quaternion::Quaternion()
Default Constructor. @SINCE_1_0.0.
Default Constructor
Referenced by operator*, operator*, operator+, operator-, operator-, operator/.
Dali::Quaternion::Quaternion(float cosThetaBy2, float iBySineTheta, float jBySineTheta, float kBySineTheta)
Constructs from a quaternion represented by floats.
@SINCE_1_0.0 cosThetaBy2 iBySineTheta jBySineTheta kBySineTheta
constexpr Dali::Quaternion::Quaternion(const Vector4 &vector)
Constructs from a quaternion represented by a vector.
@SINCE_1_0.0 vector x,y,z fields represent i,j,k coefficients, w represents cos(theta/2)
Dali::Quaternion::Quaternion(Radian angle, const Vector3 &axis)
Constructor from an axis and angle.
@SINCE_1_0.0 angle The angle around the axis axis The vector of the axis
References mVector, Dali::Vector3::Normalize, Dali::Radian::radian, Dali::Vector4::w, Dali::Vector3::x, Dali::Vector4::x, Dali::Vector3::y, Dali::Vector4::y, Dali::Vector3::z, Dali::Vector4::z.
Dali::Quaternion::Quaternion(Radian pitch, Radian yaw, Radian roll)
Constructs from Euler angles.
@SINCE_1_0.0 pitch yaw roll
References SetEuler.
Dali::Quaternion::Quaternion(const Matrix &matrix)
Constructs from a matrix.
@SINCE_1_0.0 matrix
References Dali::Matrix::GetXAxis, Dali::Matrix::GetYAxis, Dali::Matrix::GetZAxis.
Dali::Quaternion::Quaternion(const Vector3 &xAxis, const Vector3 &yAxis, const Vector3 &zAxis)
Constructs from 3 orthonormal axes.
@SINCE_1_0.0 xAxis The X axis yAxis The Y axis zAxis The Z axis
Dali::Quaternion::Quaternion(const Vector3 &v0, const Vector3 &v1)
Constructs quaternion which describes minimum rotation to align v0 with v1. @SINCE_1_0.0.
v0 First normalized vector v1 Second normalized vector v0 and v1 should be normalized
References Dali::Vector3::Cross, Dali::Vector3::Dot, Dali::Math::MACHINE_EPSILON_1, mVector, Normalize, Dali::Vector4::w, Dali::Vector3::x, Dali::Vector4::x, Dali::Vector3::y, Dali::Vector4::y, Dali::Vector3::z, Dali::Vector4::z.
Dali::Quaternion::~Quaternion()=default
Destructor, nonvirtual as this is not a base class.
@SINCE_1_0.0
bool Dali::Quaternion::IsIdentity() const
Helper to check if this is an identity quaternion.
@SINCE_1_0.0 True if this is identity quaternion
References Dali::Math::MACHINE_EPSILON_10, mVector, Dali::Vector4::w, Dali::Vector4::x, Dali::Vector4::y, Dali::Vector4::z.
Referenced by Dali::Matrix::SetInverseTransformComponents, Dali::Matrix::SetTransformComponents.
bool Dali::Quaternion::ToAxisAngle(Vector3 &axis, Radian &angle) const
Converts the quaternion to an axis/angle pair.
@SINCE_1_0.0 axis angle Angle in radians True if converted correctly
References Dali::Clamp, Dali::EqualsZero, mVector, Dali::Radian::radian, Dali::Vector4::w, Dali::Vector3::x, Dali::Vector4::x, Dali::Vector3::y, Dali::Vector4::y, Dali::Vector3::z, Dali::Vector4::z.
Referenced by Dali::operator<<.
const Vector4 & Dali::Quaternion::AsVector() const
Returns the quaternion as a vector.
@SINCE_1_0.0 The vector representation of the quaternion
References mVector.
void Dali::Quaternion::SetEuler(Radian pitch, Radian yaw, Radian roll)
SetEuler sets the quaternion from the Euler angles applied in x, y, z order.
@SINCE_1_0.0 pitch yaw roll
References mVector, Dali::Radian::radian, Dali::Vector4::w, Dali::Vector4::x, Dali::Vector4::y, Dali::Vector4::z.
Referenced by Quaternion.
Vector4 Dali::Quaternion::EulerAngles() const
Returns the Euler angles from a rotation Quaternion.
@SINCE_1_0.0 A vector of Euler angles (x == pitch, y == yaw, z == roll)
References Dali::Clamp, mVector, Dali::Vector4::w, Dali::Vector4::x, Dali::Vector4::y, Dali::Vector4::z.
const Quaternion Dali::Quaternion::operator+(const Quaternion &other) const
Addition operator.
@SINCE_1_0.0 other The quaternion to add A quaternion containing the result of the addition
References mVector, Quaternion.
const Quaternion Dali::Quaternion::operator-(const Quaternion &other) const
Subtraction operator.
@SINCE_1_0.0 other The quaternion to subtract A quaternion containing the result of the subtract
References mVector, Quaternion.
const Quaternion Dali::Quaternion::operator*(const Quaternion &other) const
Multiplication operator.
@SINCE_1_0.0 other The quaternion to multiply A quaternion containing the result
References Dali::Vector4::Dot3, mVector, Quaternion, Dali::Vector4::w, Dali::Vector4::x, Dali::Vector4::y, Dali::Vector4::z.
Vector3 Dali::Quaternion::operator*(const Vector3 &other) const
Multiplication operator.
@SINCE_1_0.0 other The vector to multiply A vector containing the result of the multiplication
References Dali::Vector3::Cross, mVector, Dali::Vector4::w, Dali::Vector4::x, Dali::Vector4::y, Dali::Vector4::z.
const Quaternion Dali::Quaternion::operator/(const Quaternion &other) const
Division operator.
@SINCE_1_0.0 other A quaternion to divide by A quaternion containing the result
References Invert.
const Quaternion Dali::Quaternion::operator*(float scale) const
Scale operator.
@SINCE_1_0.0 scale A value to scale by A quaternion containing the result
References mVector, Quaternion.
const Quaternion Dali::Quaternion::operator/(float scale) const
Scale operator.
@SINCE_1_0.0 scale A value to scale by A quaternion containing the result
References mVector, Quaternion.
Quaternion Dali::Quaternion::operator-() const
Unary Negation operator.
@SINCE_1_0.0 A quaternion containing the negated result
References mVector, Quaternion, Dali::Vector4::w, Dali::Vector4::x, Dali::Vector4::y, Dali::Vector4::z.
const Quaternion & Dali::Quaternion::operator+=(const Quaternion &other)
Addition with Assignment operator.
@SINCE_1_0.0 other The quaternion to add A reference to this
References mVector.
const Quaternion & Dali::Quaternion::operator-=(const Quaternion &other)
Subtraction with Assignment operator.
@SINCE_1_0.0 other The quaternion to subtract A reference to this
References mVector.
const Quaternion & Dali::Quaternion::operator*=(const Quaternion &other)
Multiplication with Assignment operator.
@SINCE_1_0.0 other The quaternion to multiply A reference to this
References Dali::Vector4::Dot3, mVector, Dali::Vector4::w, Dali::Vector4::x, Dali::Vector4::y, Dali::Vector4::z.
const Quaternion & Dali::Quaternion::operator*=(float scale)
Scale with Assignment operator.
@SINCE_1_0.0 scale the value to scale by A reference to this
References mVector.
const Quaternion & Dali::Quaternion::operator/=(float scale)
Scale with Assignment operator.
@SINCE_1_0.0 scale The value to scale by A reference to this
References mVector.
bool Dali::Quaternion::operator==(const Quaternion &rhs) const
Equality operator.
@SINCE_1_0.0 rhs The quaternion to compare with True if the quaternions are equal
References Dali::Math::MACHINE_EPSILON_1, mVector, Dali::Vector4::w, Dali::Vector4::x, Dali::Vector4::y, Dali::Vector4::z.
Referenced by operator!=.
bool Dali::Quaternion::operator!=(const Quaternion &rhs) const
Inequality operator.
@SINCE_1_0.0 rhs The quaternion to compare with True if the quaternions are not equal
References operator==.
float Dali::Quaternion::Length() const
Returns the length of the quaternion.
@SINCE_1_0.0 The length of the quaternion
References Dali::Vector4::Length, mVector.
Referenced by Normalize, Normalized.
float Dali::Quaternion::LengthSquared() const
Returns the squared length of the quaternion.
@SINCE_1_0.0 The squared length of the quaternion
References Dali::Vector4::LengthSquared, mVector.
Referenced by Invert.
void Dali::Quaternion::Normalize()
Normalizes this to unit length.
@SINCE_1_0.0
References Length.
Referenced by AngleBetween, Quaternion.
Quaternion Dali::Quaternion::Normalized() const
Normalized.
@SINCE_1_0.0 A normalized version of this quaternion
References Length.
Referenced by Lerp, Slerp.
void Dali::Quaternion::Conjugate()
Conjugates this quaternion.
@SINCE_1_0.0
References mVector, Dali::Vector4::x, Dali::Vector4::y, Dali::Vector4::z.
Referenced by Invert, Rotate, Rotate.
void Dali::Quaternion::Invert()
Inverts this quaternion.
@SINCE_1_0.0
References Conjugate, LengthSquared.
Referenced by operator/, Dali::Matrix::SetInverseTransformComponents.
Quaternion Dali::Quaternion::Log() const
Performs the logarithm of a Quaternion = v*a where q = (cos(a),v*sin(a)).
@SINCE_1_0.0 A quaternion representing the logarithm
References Dali::Clamp, Dali::Math::MACHINE_EPSILON_1, mVector, Dali::Vector4::w, Dali::Vector4::x, Dali::Vector4::y, Dali::Vector4::z.
Quaternion Dali::Quaternion::Exp() const
Performs an exponent e^Quaternion = Exp(v*a) = (cos(a),vsin(a)).
@SINCE_1_0.0 A quaternion representing the exponent
References DALI_ASSERT_ALWAYS, Dali::EqualsZero, Dali::Vector4::Length3, Dali::Math::MACHINE_EPSILON_1, mVector, Dali::Vector4::w, Dali::Vector4::x, Dali::Vector4::y, Dali::Vector4::z.
Vector4 Dali::Quaternion::Rotate(const Vector4 &vector) const
Rotates v by this Quaternion (Quaternion must be unit).
@SINCE_1_0.0 vector A vector to rotate The rotated vector
References Conjugate, Dali::Vector4::x, Dali::Vector4::y, Dali::Vector4::z.
Referenced by Dali::LookAt, Dali::Matrix::SetInverseTransformComponents.
Vector3 Dali::Quaternion::Rotate(const Vector3 &vector) const
Rotates v by this Quaternion (Quaternion must be unit).
@SINCE_1_0.0 vector A vector to rotate The rotated vector
References Conjugate, mVector, Dali::Vector3::x, Dali::Vector3::y, Dali::Vector3::z.
Dali::Quaternion::Quaternion(const Quaternion &)=default
Default copy constructor.
Dali::Quaternion::Quaternion(Quaternion &&) noexcept=default
Default move constructor.
Quaternion & Dali::Quaternion::operator=(const Quaternion &)=default
Default copy assignment operator.
Quaternion & Dali::Quaternion::operator=(Quaternion &&) noexcept=default
Default move assignment operator.
float Dali::Quaternion::Dot(const Quaternion &q1, const Quaternion &q2)
Returns the dot product of two quaternions.
@SINCE_1_0.0 q1 The first quaternion q2 The second quaternion The dot product of the two quaternions
References Dali::Vector4::Dot, mVector.
Referenced by Slerp, SlerpNoInvert.
Quaternion Dali::Quaternion::Lerp(const Quaternion &q1, const Quaternion &q2, float t)
Linear Interpolation (using a straight line between the two quaternions).
@SINCE_1_0.0 q1 The start quaternion q2 The end quaternion t A progress value between 0 and 1 The interpolated quaternion
References Normalized.
Referenced by SlerpNoInvert.
Quaternion Dali::Quaternion::Slerp(const Quaternion &q1, const Quaternion &q2, float progress)
Spherical Linear Interpolation (using the shortest arc of a great circle between the two quaternions).
@SINCE_1_0.0 q1 The start quaternion q2 The end quaternion progress A progress value between 0 and 1 The interpolated quaternion
References Dot, Normalized.
Quaternion Dali::Quaternion::SlerpNoInvert(const Quaternion &q1, const Quaternion &q2, float t)
This version of Slerp, used by Squad, does not check for theta > 90.
@SINCE_1_0.0 q1 The start quaternion q2 The end quaternion t A progress value between 0 and 1 The interpolated quaternion
References Dali::Clamp, Dot, Lerp.
Referenced by Squad.
Quaternion Dali::Quaternion::Squad(const Quaternion &start, const Quaternion &end, const Quaternion &ctrl1, const Quaternion &ctrl2, float t)
Spherical Cubic Interpolation.
@SINCE_1_0.0 start The start quaternion end The end quaternion ctrl1 The control quaternion for q1 ctrl2 The control quaternion for q2 t A progress value between 0 and 1 The interpolated quaternion
References SlerpNoInvert.
float Dali::Quaternion::AngleBetween(const Quaternion &q1, const Quaternion &q2)
Returns the shortest angle between two quaternions in Radians.
@SINCE_1_0.0 q1 The first quaternion q2 The second quaternion The angle between the two quaternions
References Dali::Clamp, Dali::Vector4::Dot, mVector, Normalize.