Dali::AddOn::AddOnBinder
Dali::Integration::AddOnManager * Dali::AddOn::AddOnBinder::mAddOnManager
Pointer to the AddOn manager.
Referenced by AddOnBinder, AddOnBinder, ConvertFunction, GetGlobalProc, GetInstanceProc.
Dali::AddOnLibrary Dali::AddOn::AddOnBinder::mAddOnHandle
Handle to the AddOn library.
Referenced by AddOnBinder, AddOnBinder, ConvertFunction, GetGlobalProc, GetHandle, GetInstanceProc.
Dali::AddOnInfo Dali::AddOn::AddOnBinder::mAddOnInfo
Stored AddOnInfo structure.
Referenced by AddOnBinder, AddOnBinder, GetAddOnInfo.
Dali::AddOn::AddOnBinder::AddOnBinder(const char *addonName, uint32_t version=0u)
Constructor. Opens an AddOn and creates interface.
addonName Name of AddOn version Version of AddOn
References Dali::Integration::AddOnManager::Get, Dali::Integration::AddOnManager::GetAddOn, GetAddOnInfo, Dali::Integration::AddOnManager::GetAddOnInfo, mAddOnHandle, mAddOnInfo, mAddOnManager.
Dali::AddOn::AddOnBinder::AddOnBinder(const char *addonName, const char *libraryName, uint32_t version=0u)
Constructor. Opens an AddOn and creates interface.
addonName Name of AddOn libraryName Name of the library to load addon from. version Version of AddOn
References Dali::Integration::AddOnManager::Get, GetAddOnInfo, Dali::Integration::AddOnManager::GetAddOnInfo, Dali::Integration::AddOnManager::LoadAddOn, mAddOnHandle, mAddOnInfo, mAddOnManager.
virtual Dali::AddOn::AddOnBinder::~AddOnBinder()=default
Destructor.
T * Dali::AddOn::AddOnBinder::ConvertFunction(const std::string &funcName)
Looks up and converts c-style void* function into pointer of type T.
funcName name of the function Returns a new pointer
References GetAddOnInfo, Dali::Integration::AddOnManager::GetGlobalProc, mAddOnHandle, mAddOnManager.
Dali::AddOnLibrary Dali::AddOn::AddOnBinder::GetHandle()
Returns a handle to the AddOn library.
Handle object
References mAddOnHandle.
Referenced by IsValid.
void * Dali::AddOn::AddOnBinder::GetGlobalProc(const char *name)
Returns pointer to the global AddOn function.
name Name of the function Valid pointer or nullptr
References Dali::Integration::AddOnManager::GetGlobalProc, mAddOnHandle, mAddOnManager.
void * Dali::AddOn::AddOnBinder::GetInstanceProc(const char *name)
Returns pointer to the instance AddOn function.
name Name of the function Valid pointer or nullptr
References Dali::Integration::AddOnManager::GetInstanceProc, mAddOnHandle, mAddOnManager.
virtual bool Dali::AddOn::AddOnBinder::IsValid()
Tests whether the interface is valid.
True if valid, false otherwise
References GetHandle.
const AddOnInfo & Dali::AddOn::AddOnBinder::GetAddOnInfo() const
Returns AddOn info structure.
AddOn info structure.
References mAddOnInfo.
Referenced by AddOnBinder, AddOnBinder, ConvertFunction.