Dali::OwnerContainer
using Dali::OwnerContainer< T >::SizeType = typename Dali::Vector<T>::SizeType
using Dali::OwnerContainer< T >::Iterator = typename Vector<T>::Iterator
using Dali::OwnerContainer< T >::ConstIterator = typename Vector<T>::ConstIterator
Dali::OwnerContainer< T >::OwnerContainer()=default
Create a pointer-container.
Dali::OwnerContainer< T >::~OwnerContainer()
Non-virtual destructor; OwnerContainer<T> is not suitable as base class.
References Dali::OwnerContainer< T >::Clear, Dali::VectorBase::Release.
Dali::OwnerContainer< T >::OwnerContainer(const OwnerContainer &)=delete
Deleted copy constructor.
Dali::OwnerContainer< T >::OwnerContainer(OwnerContainer &&)=delete
Deleted move constructor.
OwnerContainer & Dali::OwnerContainer< T >::operator=(const OwnerContainer &)=delete
Deleted copy assignment operator.
OwnerContainer & Dali::OwnerContainer< T >::operator=(OwnerContainer &&)=delete
Deleted move assignment operator.
bool Dali::OwnerContainer< T >::IsEmpty() const
Test whether the container is empty. True if the container is empty
References Dali::VectorBase::Count.
Referenced by Dali::OwnerContainer< T >::MoveFrom.
Iterator Dali::OwnerContainer< T >::Erase(Iterator position)
Erase an object from the container (delete from heap). position A dereferencable iterator to an element in mContainer. iterator pointing to next element
References Dali::Vector< T, IsTrivialType >::Erase.
Referenced by Dali::OwnerContainer< T >::EraseObject.
void Dali::OwnerContainer< T >::EraseIf(Predicate predicate)
Erases all elements that satisfy the predicate from the OwnerContainer.
predicate The predicate
References Dali::Vector< T, IsTrivialType >::Begin, Dali::Vector< T, IsTrivialType >::begin, Dali::Vector< T, IsTrivialType >::End, Dali::Vector< T, IsTrivialType >::end, Dali::Vector< T, IsTrivialType >::Erase.
Iterator Dali::OwnerContainer< T >::Erase(Iterator first, Iterator last)
Erases a range of elements.(delete from heap).
References Dali::Vector< T, IsTrivialType >::Erase.
void Dali::OwnerContainer< T >::EraseObject(T object)
Erase an object from OwnerContainer object to remove
References Dali::Vector< T, IsTrivialType >::Begin, DALI_ASSERT_DEBUG, Dali::Vector< T, IsTrivialType >::End, Dali::OwnerContainer< T >::Erase.
T Dali::OwnerContainer< T >::Release(Iterator position)
Release the ownership of an object, without deleting it. position A dereferencable iterator to an element in mContainer. iterators are invalidated by this method. pointer to the released item
References Dali::Vector< T, IsTrivialType >::Erase.
void Dali::OwnerContainer< T >::Clear()
Destroy all of the elements in the container.
References Dali::Vector< T, IsTrivialType >::Clear, Dali::Vector< T, IsTrivialType >::End, Dali::Vector< T, IsTrivialType >::end.
Referenced by Dali::OwnerContainer< T >::~OwnerContainer.
void Dali::OwnerContainer< T >::Resize(SizeType size)
Resizes the container to hold specific amount of elements size to resize to
References Dali::VectorBase::Count, Dali::Vector< T, IsTrivialType >::End, Dali::Vector< T, IsTrivialType >::end, Dali::Vector< T, IsTrivialType >::Resize.
void Dali::OwnerContainer< T >::MoveFrom(OwnerContainer &source)
Move the ownership of objects from another OwnerContainer to this one without deleting them. It will keep the original items here as well. source where to move elements from to this OwnerContainer
References Dali::Vector< T, IsTrivialType >::Begin, Dali::VectorBase::Count, Dali::Vector< T, IsTrivialType >::End, Dali::Vector< T, IsTrivialType >::end, Dali::OwnerContainer< T >::IsEmpty, Dali::Vector< T, IsTrivialType >::PushBack, Dali::Vector< T, IsTrivialType >::Reserve, Dali::VectorBase::Swap.
void Dali::OwnerContainer< T >::Delete(T pointer)
delete the contents of the pointer Function provided to allow classes to provide a custom destructor through template specialisation
pointer to the object