Dali::StringView
constexpr size_t Dali::StringView::StorageSize
Opaque storage sized for std::string_view.
constexpr size_t Dali::StringView::StorageAlign
Opaque storage aligned for std::string_view.
uint8_t Dali::StringView::mStorage[StorageSize][StorageSize]
Dali::StringView::StringView()
Constructor.
Creates an empty string view. @SINCE_2_5.15
Dali::StringView::StringView(const char *str)
Constructor from a null-terminated string.
@SINCE_2_5.15 str A null-terminated string
Dali::StringView::StringView(const char *str, uint32_t length)
Constructor from a pointer and length.
@SINCE_2_5.15 str A pointer to character data (not necessarily null-terminated) length The number of characters
Dali::StringView::StringView(const String &str)
Constructor from a Dali::String.
@SINCE_2_5.15 str The string to view
References Dali::String::CStr, Dali::String::Size.
Dali::StringView::~StringView()
Destructor.
Dali::StringView::StringView(const StringView &other)
Copy constructor.
@SINCE_2_5.15 other The string view to copy
StringView & Dali::StringView::operator=(const StringView &other)
Assignment operator.
@SINCE_2_5.15 other The string view to copy A reference to this string view
uint32_t Dali::StringView::Size() const
Get the number of bytes in the view.
@SINCE_2_5.15 The number of bytes in the view
Referenced by Dali::String::operator=, Dali::String::String, Dali::Integration::ToStdString, Dali::Integration::ToStdStringView.
bool Dali::StringView::Empty() const
Determine if the view is empty.
@SINCE_2_5.15 true if the view has no characters
const char * Dali::StringView::Data() const
Get a pointer to the character data.
The returned pointer is not guaranteed to be null-terminated. @SINCE_2_5.15 A pointer to the character data
Referenced by Dali::String::operator=, Dali::String::String, Dali::Integration::ToStdString, Dali::Integration::ToStdStringView.
bool Dali::StringView::operator==(const StringView &other) const
Comparison equality operator.
@SINCE_2_5.15 other The string to compare True if both strings are equal
bool Dali::StringView::operator==(const char *other) const
Comparison equality operator.
@SINCE_2_5.15 other The string to compare True if both strings are equal
bool Dali::StringView::operator==(const String &other) const
Comparison equality operator.
@SINCE_2_5.18 other The string to compare True if both strings are equal
References Dali::String::CStr, Dali::String::Size.