Dali::ConditionalWait::ScopedLock
ScopedLockImpl* Dali::ConditionalWait::ScopedLock::mImpl
Referenced by Dali::ConditionalWait::Wait, Dali::ConditionalWait::Wait, Dali::ConditionalWait::WaitUntil.
Dali::ConditionalWait::ScopedLock::ScopedLock(ConditionalWait &wait)
Will acquire the internal mutex of the ConditionalWait object passed in.
Constructor wait The ConditionalWait object to lock.
Dali::ConditionalWait::ScopedLock::~ScopedLock()
Will release the internal mutex of the ConditionalWait object passed in.
Destructor
ConditionalWait & Dali::ConditionalWait::ScopedLock::GetLockedWait() const
Getter for the ConditionalWait locked for this instance's lifetime. the ConditionalWait object currently locked.
Referenced by Dali::ConditionalWait::Notify, Dali::ConditionalWait::Wait, Dali::ConditionalWait::WaitUntil.
Dali::ConditionalWait::ScopedLock::ScopedLock(const ScopedLock &)
const ScopedLock & Dali::ConditionalWait::ScopedLock::operator=(const ScopedLock &)