Dali::Any
using Dali::Any::CloneFunc = AnyContainerBase* (*)(const AnyContainerBase&)
using Dali::Any::DeleteFunc = void (*)(const AnyContainerBase*)
AnyContainerBase* Dali::Any::mContainer
Dali::Any::Any()
Default constructor. @SINCE_1_0.0.
Dali::Any::~Any()
Destructor. Free resources. @SINCE_1_0.0.
References Dali::Any::AnyContainerBase::mDeleteFunc.
Dali::Any::Any(const Type &value)
Constructs a Any type with the given value.
@SINCE_1_0.0 value The given value
Dali::Any::Any(const Any &any)
Copy Constructor. @SINCE_1_0.0.
any Any to be copied
References Dali::Any::AnyContainerBase::mCloneFunc.
Dali::Any::Any(Any &&any) noexcept
Move Constructor. @SINCE_2_1.44.
any Any to be moved
Any & Dali::Any::operator=(const Type &value)
Assigns a given value to the Any type.
@SINCE_1_0.0 value The given value A reference to this If the types are different, then the current container will be re-created.
References Dali::Any::AnyContainerBase::GetType, Dali::Any::AnyContainerBase::mDeleteFunc.
Any & Dali::Any::operator=(const Any &any)
Assignment operator.
@SINCE_1_0.0 any Any to be assigned which contains a value of identical type to current contents. A reference to this DaliException If parameter any is of a different type.
References AssertAlways, GetType, Dali::Any::AnyContainerBase::GetType, Dali::Any::AnyContainerBase::mCloneFunc, Dali::Any::AnyContainerBase::mDeleteFunc.
Any & Dali::Any::operator=(Any &&any) noexcept
Move assignment operator.
@SINCE_2_1.44 any Any to be moved which contains a value of identical type to current contents. A reference to this
void Dali::Any::Get(Type &type) const
Gets a value of type Type from container.
@SINCE_1_0.0 type destination of type Type to write to
Referenced by Dali::AnyCast, Dali::AnyCast, Dali::AnyCastReference, Dali::AnyCastReference.
const std::type_info & Dali::Any::GetType() const
Returns the type info of the stored value.
@SINCE_1_0.0 The std::type_info of the stored value or the type info of the void type if there is no value stored
References Dali::Any::AnyContainerBase::GetType.
Referenced by operator=.
const Type & Dali::Any::Get() const
Retrieves the stored value in the Any type.
@SINCE_1_0.0 The stored value
References AssertAlways, Dali::Any::AnyContainerBase::GetType.
Type * Dali::Any::GetPointer()
Returns pointer of Type to the value stored.
@SINCE_1_0.0 pointer to the value, or NULL if no value is contained
References AssertAlways, Dali::Any::AnyContainerBase::GetType.
Referenced by Dali::AnyCast, Dali::AnyCast.
const Type * Dali::Any::GetPointer() const
Returns pointer of Type to the value stored.
@SINCE_1_0.0 pointer to the value, or NULL if no value is contained
References AssertAlways, Dali::Any::AnyContainerBase::GetType.
bool Dali::Any::Empty() const
Returns whether container holds a value.
@SINCE_1_0.0 true if the container is empty, else false
void Dali::Any::AssertAlways(const char *assertMessage)
Passes Assert message.
@SINCE_1_0.0 assertMessage Assert message to report
References DALI_LOG_ERROR_NOFN.
Referenced by Get, GetPointer, GetPointer, operator=.