Dali::Internal::StringImpl
constexpr size_t Dali::Internal::StringImpl::StorageSize
Storage size for std::string.
constexpr size_t Dali::Internal::StringImpl::StorageAlign
Storage alignment for std::string.
char Dali::Internal::StringImpl::mStorage[StorageSize][StorageSize]
Dali::Internal::StringImpl::StringImpl(String &&daliString) noexcept
Move constructor from Dali::String.
Constructs a StringImpl by moving the contents from a Dali::String. The source Dali::String will be left in a destructed state. daliString The Dali::String to move from
Dali::Internal::StringImpl::~StringImpl()
Destructor.
std::string Dali::Internal::StringImpl::Extract() noexcept
Extract the underlying std::string by moving.
A std::string containing the moved data
Referenced by Dali::Integration::GetStdString, Dali::Integration::ToStdString, Dali::Integration::ToStdString.
std::string & Dali::Internal::StringImpl::GetString() noexcept
Get a reference to the underlying std::string.
A reference to the internal std::string
const std::string & Dali::Internal::StringImpl::GetString() const noexcept
Get a const reference to the underlying std::string.
A const reference to the internal std::string
String Dali::Internal::StringImpl::ToDaliString(std::string &&stdString) noexcept
Create a Dali::String by moving from a std::string.
This is a static factory method that efficiently moves the contents of a std::string into a new Dali::String without copying. stdString The std::string to move from A Dali::String containing the moved data
Referenced by Dali::Integration::ToDaliString.