Dali::TypeRegistry
TypeRegistry Dali::TypeRegistry::Get()
Gets Type Registry handle.
@SINCE_1_0.0 TypeRegistry handle
References TypeRegistry.
Referenced by Dali::Scripting::NewActor.
Dali::TypeRegistry::TypeRegistry()
Allows the creation of an empty typeRegistry handle. @SINCE_1_0.0.
Referenced by Get.
Dali::TypeRegistry::~TypeRegistry()
Destructor. @SINCE_1_0.0.
Dali::TypeRegistry::TypeRegistry(const TypeRegistry &handle)
This copy constructor is required for (smart) pointer semantics.
@SINCE_1_0.0 handle A reference to the copied handle
TypeRegistry & Dali::TypeRegistry::operator=(const TypeRegistry &rhs)
This assignment operator is required for (smart) pointer semantics.
@SINCE_1_0.0 rhs A reference to the copied handle A reference to this
Dali::TypeRegistry::TypeRegistry(TypeRegistry &&rhs) noexcept
Move constructor.
@SINCE_1_9.22 rhs A reference to the moved handle
TypeRegistry & Dali::TypeRegistry::operator=(TypeRegistry &&rhs) noexcept
Move assignment operator.
@SINCE_1_9.22 rhs A reference to the moved handle A reference to this handle
Dali::TypeInfo Dali::TypeRegistry::GetTypeInfo(const Dali::StringView &uniqueTypeName)
Gets TypeInfo for a registered type.
@SINCE_1_0.0 uniqueTypeName A unique type name TypeInfo if the type exists, otherwise an empty handle
References Dali::GetImplementation, Dali::BaseObject::GetTypeInfo.
Referenced by Dali::Scripting::NewActor.
Dali::TypeInfo Dali::TypeRegistry::GetTypeInfo(const std::type_info &registerType)
Gets TypeInfo for a registered type.
@SINCE_1_0.0 registerType The registered type info TypeInfo if the type exists, otherwise an empty handle
References Dali::GetImplementation, Dali::BaseObject::GetTypeInfo.
size_t Dali::TypeRegistry::GetTypeNameCount() const
Gets type name count.
@SINCE_1_0.0 The count
References Dali::GetImplementation.
const Dali::String & Dali::TypeRegistry::GetTypeName(size_t index) const
Gets type names by index.
@SINCE_1_0.0 index The index to get the type name The type name or an empty string when index is not valid
References Dali::GetImplementation, Dali::BaseObject::GetTypeName.