Dali::CircularQueue
typedef Dali::Vector<ElementType> Dali::CircularQueue< ElementType >::Queue
Queue Dali::CircularQueue< ElementType >::mQueue
The queue of elements.
uint32_t Dali::CircularQueue< ElementType >::mMaximumSize
maximum size of queue
uint32_t Dali::CircularQueue< ElementType >::mStartMarker
Index of the first element in the queue.
uint32_t Dali::CircularQueue< ElementType >::mEndMarker
Index of the push back available element in the queue.
uint32_t Dali::CircularQueue< ElementType >::mNumberOfElements
Number of valid elements in the queue.
Dali::CircularQueue< ElementType >::CircularQueue(uint32_t maximumSize)
Constructor maximumSize The maximum number of elements that the queue can contain
References Dali::Vector< T, IsTrivialType >::Reserve.
void Dali::CircularQueue< ElementType >::Resize(uint32_t maximumSize)
Resize capacity. The elements will be auto clamped by the new maximum size.
Performance note : We will copy whole data during capacity change. maximumSize The maximum number of elements that the queue can contain
References Dali::Vector< T, IsTrivialType >::Reserve, Dali::Vector< T, IsTrivialType >::Resize, Dali::Vector< T, IsTrivialType >::Swap.
void Dali::CircularQueue< ElementType >::Clear()
Clear the queue.
References Dali::Vector< T, IsTrivialType >::Clear.
ElementType & Dali::CircularQueue< ElementType >::operator[](uint32_t index)
Index operator.
index The index to lookup. This method asserts if the user attempts to read outside the range of elements.
References DALI_ASSERT_ALWAYS.
const ElementType & Dali::CircularQueue< ElementType >::operator[](uint32_t index) const
References DALI_ASSERT_ALWAYS.
void Dali::CircularQueue< ElementType >::PushBack(const ElementType &element)
Push back an element into the queue.
element The element to push to the back of the queue This method asserts if the user attempts to push more elements than the maximum size specified in the constructor
References DALI_ASSERT_ALWAYS, Dali::CircularQueue< ElementType >::IsFull, Dali::Vector< T, IsTrivialType >::PushBack.
ElementType Dali::CircularQueue< ElementType >::PopFront()
Pops an element off the front of the queue.
A copy of the element at the front of the queue This method asserts if the queue is empty
References DALI_ASSERT_ALWAYS, Dali::CircularQueue< ElementType >::IsEmpty.
ElementType & Dali::CircularQueue< ElementType >::Front()
References DALI_ASSERT_ALWAYS, Dali::CircularQueue< ElementType >::IsEmpty.
const ElementType & Dali::CircularQueue< ElementType >::Front() const
References DALI_ASSERT_ALWAYS, Dali::CircularQueue< ElementType >::IsEmpty.
ElementType & Dali::CircularQueue< ElementType >::Back()
References DALI_ASSERT_ALWAYS, Dali::CircularQueue< ElementType >::IsEmpty.
const ElementType & Dali::CircularQueue< ElementType >::Back() const
References DALI_ASSERT_ALWAYS, Dali::CircularQueue< ElementType >::IsEmpty.
bool Dali::CircularQueue< ElementType >::IsEmpty() const
Predicate to determine if the queue is empty.
true if the queue is empty
Referenced by Dali::CircularQueue< ElementType >::Back, Dali::CircularQueue< ElementType >::Back, Dali::CircularQueue< ElementType >::Front, Dali::CircularQueue< ElementType >::Front, Dali::CircularQueue< ElementType >::PopFront.
bool Dali::CircularQueue< ElementType >::IsFull() const
Predicate to determine if the queue is full.
true if the queue is full
Referenced by Dali::CircularQueue< ElementType >::PushBack.
uint32_t Dali::CircularQueue< ElementType >::Count() const
Get a count of the elements in the queue.
the number of elements in the queue.
uint32_t Dali::CircularQueue< ElementType >::GetBackIndex() const