Dali::Matrix
const Matrix Dali::Matrix::IDENTITY
The identity matrix.
float Dali::Matrix::mMatrix[16][16]
The elements of the matrix.
Dali::Matrix::Matrix()
Constructor.
Zero initializes the matrix. @SINCE_1_0.0
Dali::Matrix::Matrix(bool initialize)
Constructor.
@SINCE_1_0.0 initialize True for initialization by zero or otherwise
Dali::Matrix::Matrix(const float *array)
Constructor.
The matrix is initialized with the contents of 'array' which must contain 16 floats. The order of the values for a transform matrix is: [xAxis.x,xAxis.y,xAxis.z,0.0f,yAxis.x,yAxis.y,yAxis.z,0.0f,zAxis.x,zAxis.y,zAxis.z,0.0f,trans.x,trans.y,trans.z,1.0f] @SINCE_1_0.0 array Pointer of 16 floats data
Dali::Matrix::Matrix(const Quaternion &rotation)
Constructs a matrix from quaternion.
@SINCE_1_0.0 rotation Rotation as quaternion
Dali::Matrix::Matrix(const Matrix &matrix)
Copy constructor.
@SINCE_1_0.0 matrix A reference to the copied matrix
Matrix & Dali::Matrix::operator=(const Matrix &matrix)
Assignment operator.
@SINCE_1_0.0 matrix A reference to the copied matrix A reference to this
Dali::Matrix::Matrix(Matrix &&matrix) noexcept
Move constructor.
@SINCE_1_9.21 matrix A reference to the moved matrix
Matrix & Dali::Matrix::operator=(Matrix &&matrix) noexcept
Move assignment operator.
@SINCE_1_9.21 matrix A reference to the moved matrix A reference to this
void Dali::Matrix::SetIdentity()
Sets this matrix to be an identity matrix. @SINCE_1_0.0.
References Dali::identityArray.
void Dali::Matrix::SetIdentityAndScale(const Vector3 &scale)
Sets this matrix to be an identity matrix with scale.
@SINCE_1_0.0 scale Scale to set on top of identity matrix
References Dali::Vector3::x, Dali::Vector3::y, Dali::Vector3::z.
void Dali::Matrix::InvertTransform(Matrix &result) const
Inverts a transform Matrix.
Any Matrix representing only a rotation and/or translation can be inverted using this function. It is faster and more accurate then using Invert(). @SINCE_1_0.0 result The inverse of this matrix
References AsFloat, DALI_ASSERT_ALWAYS, Dali::Equals, Dali::EqualsZero.
bool Dali::Matrix::Invert()
Generic brute force Matrix Invert.
Using the Matrix invert function for the specific type of matrix you are dealing with is faster, more accurate. @SINCE_1_0.0 True if successful
References AsFloat, Dali::InvertMatrix.
void Dali::Matrix::Transpose()
Swaps the rows to columns. @SINCE_1_0.0.
Vector3 Dali::Matrix::GetXAxis() const
Returns the xAxis from a Transform matrix.
@SINCE_1_0.0 The x axis
Referenced by OrthoNormalize, Dali::Quaternion::Quaternion.
Vector3 Dali::Matrix::GetYAxis() const
Returns the yAxis from a Transform matrix.
@SINCE_1_0.0 The y axis
Referenced by OrthoNormalize, Dali::Quaternion::Quaternion.
Vector3 Dali::Matrix::GetZAxis() const
Returns the zAxis from a Transform matrix.
@SINCE_1_0.0 The z axis
Referenced by OrthoNormalize, Dali::Quaternion::Quaternion.
void Dali::Matrix::SetXAxis(const Vector3 &axis)
Sets the x axis.
This assumes the matrix is a transform matrix. @SINCE_1_0.0 axis The values to set the axis to
References Dali::Vector3::x, Dali::Vector3::y, Dali::Vector3::z.
void Dali::Matrix::SetYAxis(const Vector3 &axis)
Sets the y axis.
This assumes the matrix is a transform matrix. @SINCE_1_0.0 axis The values to set the axis to
References Dali::Vector3::x, Dali::Vector3::y, Dali::Vector3::z.
void Dali::Matrix::SetZAxis(const Vector3 &axis)
Sets the z axis.
This assumes the matrix is a transform matrix. @SINCE_1_0.0 axis The values to set the axis to
References Dali::Vector3::x, Dali::Vector3::y, Dali::Vector3::z.
const Vector4 & Dali::Matrix::GetTranslation() const
Gets the translation.
This assumes the matrix is a transform matrix. @SINCE_1_0.0 The translation inlined for performance reasons (generates less code than a function call)
const Vector3 & Dali::Matrix::GetTranslation3() const
Gets the x,y and z components of the translation as a Vector3.
This assumes the matrix is a transform matrix. @SINCE_1_0.0 The translation inlined for performance reasons (generates less code than a function call)
Referenced by GetTransformComponents.
Vector3 Dali::Matrix::GetScale() const
Gets the x,y and z components of the scale as a Vector3. Note that transform scale always has positive components.
This assumes the matrix is a transform matrix. @SINCE_2_2.17 The scale
Referenced by GetTransformComponents.
Vector2 Dali::Matrix::GetScaleXY() const
Gets the x,y components of the scale as a Vector2. Note that transform scale always has positive components.
This assumes the matrix is a transform matrix. @SINCE_2_4.19 The scale of xy components
void Dali::Matrix::SetTranslation(const Vector4 &translation)
Sets the translation.
This assumes the matrix is a transform matrix. @SINCE_1_0.0 translation The translation
Referenced by SetInverseTransformComponents.
void Dali::Matrix::SetTranslation(const Vector3 &translation)
Sets the x,y and z components of the translation from a Vector3.
This assumes the matrix is a transform matrix. @SINCE_1_0.0 translation The translation
void Dali::Matrix::OrthoNormalize()
Makes the axes of the matrix orthogonal to each other and of unit length.
This function is used to correct floating point errors which would otherwise accumulate as operations are applied to the matrix. This function assumes the matrix is a transform matrix. @SINCE_1_0.0
References Dali::Vector4::Cross, GetXAxis, GetYAxis, GetZAxis, Dali::Vector4::Normalize.
const float * Dali::Matrix::AsFloat() const
Returns the contents of the matrix as an array of 16 floats.
The order of the values for a transform matrix is: [xAxis.x,xAxis.y,xAxis.z,0.0f,yAxis.x,yAxis.y,yAxis.z,0.0f,zAxis.x,zAxis.y,zAxis.z,0.0f,trans.x,trans.y,trans.z,1.0f] @SINCE_1_0.0 The matrix contents as an array of 16 floats inlined for performance reasons (generates less code than a function call)
Referenced by Invert, InvertTransform, Dali::Matrix3::Matrix3, Dali::operator<<, Dali::Matrix3::operator=.
float * Dali::Matrix::AsFloat()
Returns the contents of the matrix as an array of 16 floats.
The order of the values for a transform matrix is: [xAxis.x,xAxis.y,xAxis.z,0.0f,yAxis.x,yAxis.y,yAxis.z,0.0f,zAxis.x,zAxis.y,zAxis.z,0.0f,trans.x,trans.y,trans.z,1.0f] @SINCE_1_0.0 The matrix contents as an array of 16 floats inlined for performance reasons (generates less code than a function call)
Matrix Dali::Matrix::operator*(const Matrix &rhs) const
Multiplication operator.
Returned Matrix = This Matrix * rhs It makes some memory allocate & copy internally. Use Matrix::Multiply API for time critical path. @SINCE_2_1.44 rhs The Matrix to multiply this by A Matrix containing the result
Matrix & Dali::Matrix::operator*=(const Matrix &rhs)
Multiplication assignment operator.
This Matrix *= rhs It makes some memory allocate & copy internally. @SINCE_2_1.46 rhs The Matrix to multiply this by Itself
Vector4 Dali::Matrix::operator*(const Vector4 &rhs) const
The multiplication operator.
Returned Vector = This Matrix * rhs @SINCE_1_0.0 rhs The Vector4 to multiply this by A Vector4 containing the result
References Dali::Vector4::AsFloat, Dali::Vector4::w, Dali::Vector4::x, Dali::Vector4::y, Dali::Vector4::z.
bool Dali::Matrix::operator==(const Matrix &rhs) const
The equality operator.
Utilizes appropriate machine epsilon values. @SINCE_1_0.0 rhs The Matrix to compare this to true if the matrices are equal
References Dali::GetRangedEpsilon.
bool Dali::Matrix::operator!=(const Matrix &rhs) const
The inequality operator.
Utilizes appropriate machine epsilon values. @SINCE_1_0.0 rhs The Matrix to compare this to true if the matrices are not equal.
void Dali::Matrix::SetTransformComponents(const Vector3 &scale, const Quaternion &rotation, const Vector3 &translation)
Sets this matrix to contain the position, scale and rotation components.
Performs scale, rotation, then translation @SINCE_1_0.0 scale Scale to apply rotation Rotation to apply translation Translation to apply
References Dali::Quaternion::IsIdentity, Dali::Quaternion::mVector, Dali::Vector4::w, Dali::Vector3::x, Dali::Vector4::x, Dali::Vector3::y, Dali::Vector4::y, Dali::Vector3::z, Dali::Vector4::z.
void Dali::Matrix::SetInverseTransformComponents(const Vector3 &scale, const Quaternion &rotation, const Vector3 &translation)
Sets this matrix to contain the inverse of the position, scale and rotation components.
Performs translation, then rotation, then scale. @SINCE_1_0.0 scale Scale to apply rotation Rotation to apply translation Translation to apply
References Dali::Quaternion::Invert, Dali::Quaternion::IsIdentity, Dali::Quaternion::mVector, Dali::Quaternion::Rotate, Dali::Vector4::w, Dali::Vector3::x, Dali::Vector4::x, Dali::Vector3::y, Dali::Vector4::y, Dali::Vector3::z, Dali::Vector4::z.
void Dali::Matrix::SetInverseTransformComponents(const Vector3 &xAxis, const Vector3 &yAxis, const Vector3 &zAxis, const Vector3 &translation)
Sets this matrix to contain the inverse of the orthonormal basis and position components.
Performs translation, then rotation. @SINCE_1_0.0 xAxis The X axis of the basis yAxis The Y axis of the basis zAxis The Z axis of the basis translation Translation to apply
References SetTranslation, Dali::Vector4::w, Dali::Vector3::x, Dali::Vector3::y, Dali::Vector3::z.
void Dali::Matrix::GetTransformComponents(Vector3 &position, Quaternion &rotation, Vector3 &scale) const
Gets the position, scale and rotation components from the given transform matrix.
@SINCE_1_0.0 position Position to set rotation Rotation to set - only valid if the transform matrix has not been skewed or sheared scale Scale to set - only valid if the transform matrix has not been skewed or sheared This matrix must not contain skews or shears.
References GetScale, GetTranslation3, Dali::Quaternion::mVector, Dali::Vector3::ONE, Dali::Vector3::x, Dali::Vector4::x, Dali::Vector3::y, Dali::Vector4::y, Dali::Vector3::z, Dali::Vector4::z.
void Dali::Matrix::Multiply(Matrix &result, const Matrix &lhs, const Matrix &rhs)
Function to multiply two matrices and store the result onto third.
Use this method in time critical path as it does not require temporaries. result = rhs * lhs @SINCE_1_0.0 result Result of the multiplication lhs Matrix, this can be same matrix as result rhs Matrix, this cannot be same matrix as result
void Dali::Matrix::Multiply(Matrix &result, const Matrix &lhs, const Quaternion &rhs)
Function to multiply a matrix and quaternion and store the result onto third.
Use this method in time critical path as it does not require temporaries. @SINCE_1_0.0 result Result of the multiplication lhs Matrix, this can be same matrix as result rhs Quaternion