Dali::Integration::TimeChecker::ThresholdFilter
using Dali::Integration::TimeChecker::ThresholdFilter::Milliseconds = uint32_t
Milliseconds Dali::Integration::TimeChecker::ThresholdFilter::mThresholdMilliSeconds
std::unique_ptr<Impl> Dali::Integration::TimeChecker::ThresholdFilter::mImpl
ThresholdFilter * Dali::Integration::TimeChecker::ThresholdFilter::New(ThresholdFilter::Milliseconds thresholdMilliSeconds, const char *environmentVariableName)
Create new filter object. The ownership of memory hold in global static list. It will be released when thread joined.
New allocated filter with threshold and environment.
bool Dali::Integration::TimeChecker::ThresholdFilter::IsEnabled()
Check whether this filter is enabled or not.
True if threshold is valid value. False if threshold is -1 (==std::numeric_limits<uint32_t>::max())
Referenced by Dali::Integration::TimeChecker::ScopeTracer::ScopeTracer, Dali::Integration::TimeChecker::ScopeTracer::~ScopeTracer.
void Dali::Integration::TimeChecker::ThresholdFilter::BeginTimeCheck()
Begin time checker.
EndTimeCheck() should be called after.
References DALI_LIKELY.
Referenced by Dali::Integration::TimeChecker::ScopeTracer::ScopeTracer.
void Dali::Integration::TimeChecker::ThresholdFilter::EndTimeCheck(const char *messagePrefix, const char *module, const char *function, const int line)
End time checker. Print log if duration is greater of equal than threshold.
messagePrefix Prefix of message. module The name of module who call this checker fuction The name of function who call this checker line The line number of function who call this checker. BeginTimeCheck() should be called before.
References DALI_LIKELY, DALI_LOG_FORMAT_PREFIX, Dali::Integration::Log::INFO, Dali::Integration::Log::LogMessage.
Referenced by Dali::Integration::TimeChecker::ScopeTracer::~ScopeTracer.
Dali::Integration::TimeChecker::ThresholdFilter::ThresholdFilter(Milliseconds thresholdMilliSeconds)