Dali::AddOns::AddOnBase
AddOnBase* Dali::AddOns::AddOnBase::mSingleton
Dali::AddOns::AddOnBase::AddOnBase()
Constructor.
virtual Dali::AddOns::AddOnBase::~AddOnBase()=default
Destructor.
virtual void Dali::AddOns::AddOnBase::GetAddOnInfo(Dali::AddOnInfo &addonInfo)=0
Retrieves AddOn info.
addonInfo AddOnInfo structure to fill by the function
virtual DispatchTable * Dali::AddOns::AddOnBase::GetGlobalDispatchTable()=0
Returns a dispatch table for global functions.
Valid dispatch table object or nullptr
virtual DispatchTable * Dali::AddOns::AddOnBase::GetInstanceDispatchTable()=0
Returns a dispatch table for instance functions.
Valid dispatch table object or nullptr
virtual void Dali::AddOns::AddOnBase::OnStart()
OnStart event. It's optional and should be implemented by the AddOn when it's required to handle the event.
virtual void Dali::AddOns::AddOnBase::OnResume()
OnResume event. It's optional and should be implemented by the AddOn when it's required to handle the event.
virtual void Dali::AddOns::AddOnBase::OnPause()
OnPause event. It's optional and should be implemented by the AddOn when it's required to handle the event.
virtual void Dali::AddOns::AddOnBase::OnStop()
OnStop event. It's optional and should be implemented by the AddOn when it's required to handle the event.
static AddOnBase * Dali::AddOns::AddOnBase::Get()
Getter of static singleton.
Returns valid singleton pointer
Referenced by Dali::AddOns::GetAddOnInfo, Dali::AddOns::GetGlobalProc, Dali::AddOns::GetInstanceProc, Dali::AddOns::OnPause, Dali::AddOns::OnResume, Dali::AddOns::OnStart, Dali::AddOns::OnStop.