Dali::FrameBuffer
FrameBuffer Dali::FrameBuffer::New(uint32_t width, uint32_t height)
Creates a new FrameBuffer, which attaches only COLOR texture.
@SINCE_1_4.0 Call GetColorTexture() to get the COLOR texture width The width of the FrameBuffer and the color texture height The height of the FrameBuffer and the color texture A handle to a newly allocated FrameBuffer
References Dali::FrameBuffer::Attachment::COLOR, New.
Referenced by New.
FrameBuffer Dali::FrameBuffer::New(uint32_t width, uint32_t height, Attachment::Mask attachments)
Creates a new FrameBuffer with specific attachments.
@SINCE_1_4.0 width The width of the FrameBuffer and the attachments height The height of the FrameBuffer and the attachments attachments Enumeration of the attachments to create A handle to a newly allocated FrameBuffer
References Dali::FrameBuffer::Attachment::AUTO, Dali::FrameBuffer::Attachment::COLOR, FrameBuffer, Dali::Pixel::RGB888, Dali::TextureType::TEXTURE_2D.
FrameBuffer Dali::FrameBuffer::DownCast(BaseHandle handle)
Downcasts to a FrameBuffer. If not, the returned handle is left uninitialized. @SINCE_1_1.43.
handle Handle to an object FrameBuffer handle or an uninitialized handle
References FrameBuffer, Dali::BaseHandle::GetObjectPtr.
Dali::FrameBuffer::FrameBuffer()
Default constructor, creates an empty handle.
Referenced by DownCast, New.
Dali::FrameBuffer::~FrameBuffer()
Destructor. @SINCE_1_1.43.
Dali::FrameBuffer::FrameBuffer(const FrameBuffer &handle)
Copy constructor, creates a new handle to the same object.
@SINCE_1_1.43 handle Handle to an object
References Dali::DownCast.
FrameBuffer & Dali::FrameBuffer::operator=(const FrameBuffer &handle)
Assignment operator, changes this handle to point at the same object.
@SINCE_1_1.43 handle Handle to an object Reference to the assigned object
Dali::FrameBuffer::FrameBuffer(FrameBuffer &&rhs) noexcept
Move constructor.
@SINCE_1_9.22 rhs A reference to the moved handle
FrameBuffer & Dali::FrameBuffer::operator=(FrameBuffer &&rhs) noexcept
Move assignment operator.
@SINCE_1_9.22 rhs A reference to the moved handle A reference to this handle
void Dali::FrameBuffer::AttachColorTexture(Texture &texture)
Attach the base LOD of a 2D texture to the framebuffer for color rendering.
This causes a color attachment to be added. Repeated calls to this method add textures as subsequent color attachments. A maximum of 8 color attachments are supported. @SINCE_1_1.43 texture The texture that will be used as output when rendering The texture has to have same size as that of FrameBuffer otherwise it won't be attached.
References AttachColorTexture.
Referenced by AttachColorTexture.
void Dali::FrameBuffer::AttachColorTexture(Texture &texture, uint32_t mipmapLevel, uint32_t layer)
Attach a texture to the framebuffer for color rendering.
This causes a color attachment to be added. Repeated calls to this method add textures as subsequent color attachments. A maximum of 8 color attachments are supported. @SINCE_1_1.43 texture The texture that will be used as output when rendering mipmapLevel The mipmap of the texture to be attached layer Indicates which layer of a cube map or array texture to attach. Unused for 2D textures The mipmapped texture has to have same size as that of FrameBuffer otherwise it won't be attached.
References Dali::GetImplementation.
Texture Dali::FrameBuffer::GetColorTexture()
Gets the first color texture used as output in the FrameBuffer.
@SINCE_1_1.43 A handle to the texture used as color output, or an uninitialized handle
References Dali::GetImplementation.
Dali::FrameBuffer::FrameBuffer(Internal::FrameBuffer *pointer)
The constructor.
Not intended for application developers. @SINCE_1_1.43 pointer A pointer to a newly allocated FrameBuffer