Dali::Shader
Shader Dali::Shader::New(Dali::StringView vertexShader, Dali::StringView fragmentShader, Hint::Value hints=Hint::NONE, Dali::StringView shaderName="")
Creates Shader.
@SINCE_1_1.43 vertexShader Vertex shader code for the effect. fragmentShader Fragment Shader code for the effect. hints Hints to define the geometry of the rendered object shaderName The name of this shader. (optional) A handle to a shader effect
References Shader.
Shader Dali::Shader::New(Dali::Property::Value shaderMap)
Creates Shader.
@SINCE_2_2.31 shaderMap Property::Map of shader data or Property::Array of Property::Map. Property::Map format is {"renderPassTag":"", "vertex":"", "fragment":"", "hints":""} shaderMap can be Property::Array of Property::Map for multi pass shading. A handle to a shader effect
References Shader.
Shader Dali::Shader::DownCast(BaseHandle handle)
Downcasts to a shader handle. If not, a shader the returned shader handle is left uninitialized.
@SINCE_1_1.43 handle Handle to an object Shader handle or an uninitialized handle
References Dali::BaseHandle::GetObjectPtr, Shader.
uint32_t Dali::Shader::GetShaderLanguageVersion()
Get the number of shading language version.
This can potentially block until GL has been initialized when the first time any DALi application is launched in the system. @SINCE_2_3.11 shader languange version as integer.
Dali::String Dali::Shader::GetShaderVersionPrefix()
Get shader preprocessor of shading language version.
This can potentially block until GL has been initialized when the first time any DALi application is launched in the system. @SINCE_1_9.36 shader preprocessor string.
Dali::String Dali::Shader::GetVertexShaderPrefix()
Get vertex shader preprocessor that includes shading language version.
This can potentially block until GL has been initialized when the first time any DALi application is launched in the system. @SINCE_1_9.36 Vertex shader preprocessor string.
Dali::String Dali::Shader::GetFragmentShaderPrefix()
Get fragment shader preprocessor that includes shading language version.
This can potentially block until GL has been initialized when the first time any DALi application is launched in the system. @SINCE_1_9.36 Fragment shader preprocessor string.
Dali::Shader::Shader()
Default constructor, creates an empty handle.
@SINCE_1_1.43
Referenced by DownCast, New, New.
Dali::Shader::~Shader()
Destructor. This is non-virtual since derived Handle types must not contain data or virtual methods.
@SINCE_1_1.43
Dali::Shader::Shader(const Shader &handle)
Copy constructor.
@SINCE_1_1.43 handle A handle to a Shader object
References Dali::DownCast.
Shader & Dali::Shader::operator=(const Shader &handle)
Assignment operator, changes this handle to point at the same object.
@SINCE_1_1.43 handle Handle to an object Reference to the assigned object
Dali::Shader::Shader(Shader &&rhs) noexcept
Move constructor.
@SINCE_1_9.22 rhs A reference to the moved handle
Shader & Dali::Shader::operator=(Shader &&rhs) noexcept
Move assignment operator.
@SINCE_1_9.22 rhs A reference to the moved handle A reference to this
Dali::Shader::Shader(Internal::Shader *effect)
This constructor is used by Dali New() methods.
Not intended for application developers. @SINCE_1_1.43 effect A pointer to a newly allocated Dali resource.