dali_core_math
using Dali::Size = typedef Vector2
Size is an alias of Dali::Vector2. @SINCE_1_0.0.
using Dali::Position = typedef Vector2
Position is an alias of Dali::Vector2. @SINCE_2_5.18.
using Dali::Scale = typedef Vector2
Scale is an alias of Dali::Vector2. @SINCE_2_5.18.
using Dali::Viewport = typedef Rect<int32_t>
Typedef for a viewport ( a rectangle representing a screen area ). @SINCE_1_0.0.
bool Dali::operator==(const Dali::AngleAxis &lhs, const Dali::AngleAxis &rhs)
Compares two angle axis for equality.
@SINCE_1_0.0 lhs angle axis rhs angle axis True if they are equal
bool Dali::operator==(const Degree &lhs, const Degree &rhs)
Compares equality between two degrees.
@SINCE_1_0.0 lhs Degree to compare rhs Degree to compare to True if the values are identical
References Dali::Math::MACHINE_EPSILON_1000.
bool Dali::operator!=(const Degree &lhs, const Degree &rhs)
Compares inequality between two degrees.
@SINCE_1_0.0 lhs Degree to compare rhs Degree to compare to True if the values are not identical
References Dali::operator==.
Degree Dali::Clamp(Degree angle, float min, float max)
Clamps a radian value. @SINCE_1_0.0.
angle to clamp min value max value The resulting radian
References Dali::Degree::Degree, Dali::Degree::degree.
Referenced by Dali::Quaternion::AngleBetween, Dali::Quaternion::EulerAngles, Dali::GenerateDistanceFieldMap, Dali::Lerp, Dali::Quaternion::Log, Dali::Quaternion::SlerpNoInvert, Dali::Quaternion::ToAxisAngle.
constexpr uint32_t Dali::NextPowerOfTwo(uint32_t i)
Returns the next power of two.
In case of numbers which are already a power of two this function returns the original number. If i is zero returns 1. @SINCE_1_0.0 i Input number The next power of two or i itself in case it's a power of two
References DALI_ASSERT_ALWAYS.
constexpr bool Dali::IsPowerOfTwo(uint32_t i)
Whether a number is power of two.
@SINCE_1_0.0 i Input number True if i is power of two.
constexpr const T & Dali::Clamp(const T &value, const T &min, const T &max)
Clamp a value.
@SINCE_1_0.0 value The value to clamp. min The minimum allowed value. max The maximum allowed value. T the clamped value
constexpr void Dali::ClampInPlace(T &value, const T &min, const T &max)
Clamp a value directly.
@SINCE_1_0.0 value The value that will be clamped. min The minimum allowed value. max The maximum allowed value.
constexpr const T Dali::Lerp(const float offset, const T &low, const T &high)
Linear interpolation between two values.
@SINCE_1_0.0 offset The offset through the range low to high. This value is clamped between 0 and 1. low Lowest value in range high Highest value in range A value between low and high.
References Dali::Clamp.
constexpr float Dali::GetRangedEpsilon(float a, float b)
Get an epsilon that is valid for the given range.
@SINCE_1_0.0 a the first value in the range b the second value in the range. a suitable epsilon
References Dali::Math::MACHINE_EPSILON_0, Dali::Math::MACHINE_EPSILON_1, Dali::Math::MACHINE_EPSILON_10, Dali::Math::MACHINE_EPSILON_100, Dali::Math::MACHINE_EPSILON_1000, Dali::Math::MACHINE_EPSILON_10000.
Referenced by Dali::Equals, Dali::Rect< T >::IsEmpty, Dali::Matrix::operator==, Dali::operator==, Dali::Vector2::operator==, Dali::Vector3::operator==, Dali::Vector4::operator==.
constexpr bool Dali::EqualsZero(float value)
Helper function to compare equality of a floating point value with zero.
@SINCE_1_0.0 value the value to compare true if the value is equal to zero
Referenced by Dali::Property::Value::Impl::ConvertType, Dali::Quaternion::Exp, Dali::Matrix3::Invert, Dali::InvertMatrix, Dali::Matrix::InvertTransform, Dali::Vector2::Normalize, Dali::Vector3::Normalize, Dali::Vector4::Normalize, Dali::Vector4::Normalize3, Dali::Matrix3::ScaledInverseTranspose, Dali::Quaternion::ToAxisAngle.
constexpr bool Dali::Equals(float a, float b)
Helper function to compare equality of two floating point values.
@SINCE_1_0.0 a the first value to compare b the second value to compare true if the values are equal within a minimal epsilon for their values
References Dali::GetRangedEpsilon.
Referenced by Dali::Matrix::InvertTransform, Dali::Property::Value::Impl::operator==, Dali::Matrix3::operator==.
constexpr bool Dali::Equals(float a, float b, float epsilon)
Helper function to compare equality of two floating point values.
@SINCE_1_0.0 a the first value to compare b the second value to compare epsilon the minimum epsilon value that will be used to consider the values different true if the difference between the values is less than the epsilon
constexpr float Dali::Round(float value, int32_t pos)
Get an float that is rounded at specified place of decimals.
@SINCE_1_0.0 value float value pos decimal place a rounded float
constexpr float Dali::WrapInDomain(float x, float start, float end)
Wrap x in domain (start) to (end).
This works like a floating point version of the % modulo operation. But with an offset (start). For instance a domain is specified as: start: 2 end: 8 28 (\/start)(\/end) |----x| The value x will be confined to this domain. If x is below 2 e.g. 0, then it is wrapped to 6. If x is above or equal to 8 e.g. 8.1 then it is wrapped to 2.1. Domain wrapping is useful for various problems from calculating positions in a space that repeats, to computing angles that range from 0 to 360. @SINCE_1_0.0 x the point to be wrapped within the domain start The start of the domain end The end of the domain the wrapped value over the domain (start) (end) If start = end (i.e. size of domain 0), then wrapping will not occur and result will always be equal to start.
References Dali::Math::MACHINE_EPSILON_1.
constexpr float Dali::ShortestDistanceInDomain(float a, float b, float start, float end)
Find the shortest distance (magnitude) and direction (sign) from (a) to (b) in domain (start) to (end).
(\/start)(\/end) |-ab<----| Knowing the shortest distance is useful with wrapped domains to solve problems such as determining the closest object to a given point, or determining whether turning left or turning right is the shortest route to get from angle 10 degrees to angle 350 degrees (clearly in a 0-360 degree domain, turning left 20 degrees is quicker than turning right 340 degrees). The value returned holds the distance and the direction from value a to value b. For instance in the above example it would return -20. i.e. subtract 20 from current value (10) to reach target wrapped value (350). @SINCE_1_0.0 a the current value b the target value start the start of the domain end the end of the domain the shortest direction (the sign) and distance (the magnitude) Assumes both (a) and (b) are already within the domain (start) to (end).
constexpr int32_t Dali::Sign(T value)
Extracts the sign of a number.
@SINCE_1_0.0 value The value we want to extract the sign -1 for negative values, +1 for positive values and 0 if value is 0
bool Dali::operator==(Radian lhs, Radian rhs)
Compares equality between two radians.
@SINCE_1_0.0 lhs Radian to compare rhs Radian to compare to True if the values are identical
References Dali::Math::MACHINE_EPSILON_10.
bool Dali::operator!=(Radian lhs, Radian rhs)
Compares inequality between two radians.
@SINCE_1_0.0 lhs Radian to compare rhs Radian to compare to True if the values are not identical
References Dali::operator==.
bool Dali::operator==(Radian lhs, Degree rhs)
Compares equality between a radian and degree.
@SINCE_1_0.0 lhs Radian to compare rhs Degree to compare to True if the values are identical
References Dali::Math::MACHINE_EPSILON_100, Dali::Radian::radian.
bool Dali::operator!=(Radian lhs, Degree rhs)
Compares inequality between a radian and a degree.
@SINCE_1_0.0 lhs Radian to compare rhs Degree to compare to True if the values are not identical
References Dali::operator==.
bool Dali::operator==(Degree lhs, Radian rhs)
Compares equality between a degree and a radian.
@SINCE_1_0.0 lhs Degree to compare rhs Radian to compare to True if the values are identical
References Dali::Math::MACHINE_EPSILON_100, Dali::Radian::Radian, Dali::Radian::radian.
bool Dali::operator!=(Degree lhs, Radian rhs)
Compares inequality between a degree and a radian.
@SINCE_1_0.0 lhs Degree to compare rhs Radian to compare to True if the values are not identical
References Dali::operator==.
bool Dali::operator>(Radian lhs, Radian rhs)
Compares greater than between two radians.
@SINCE_1_0.0 lhs Radian to compare rhs Radian to compare to True if lhs is greater than rhs
References Dali::Radian::radian.
bool Dali::operator>(Radian lhs, Degree rhs)
Compares greater than between a radian and a degree.
@SINCE_1_0.0 lhs Radian to compare rhs Degree to compare to True if lhs is greater than rhs
References Dali::Radian::Radian, Dali::Radian::radian.
bool Dali::operator>(Degree lhs, Radian rhs)
Compares greater than between a radian and a degree.
@SINCE_1_0.0 lhs Radian to compare rhs Degree to compare to True if lhs is greater than rhs
References Dali::Radian::Radian, Dali::Radian::radian.
bool Dali::operator<(Radian lhs, Radian rhs)
Compares less than between two radians.
@SINCE_1_0.0 lhs Radian to compare rhs Radian to compare to True if lhs is less than rhs
References Dali::Radian::radian.
bool Dali::operator<(Radian lhs, Degree rhs)
Compares less than between a radian and a degree.
@SINCE_1_0.0 lhs Radian to compare rhs Degree to compare to True if lhs is less than rhs
References Dali::Radian::Radian, Dali::Radian::radian.
bool Dali::operator<(Degree lhs, Radian rhs)
Compares less than between a degree and a radian.
@SINCE_1_0.0 lhs Degree to compare rhs Radian to compare to True if lhs is less than rhs
References Dali::Radian::Radian, Dali::Radian::radian.
Radian Dali::operator*(Radian lhs, float rhs)
Multiplies Radian with a float.
@SINCE_1_0.0 lhs Radian to multiply rhs float to multiply Result of the multiplication
References Dali::Radian::Radian, Dali::Radian::radian.
Radian Dali::operator-(Radian in)
Negates the radian. @SINCE_1_0.0.
in Radian to negate The negative angle
References Dali::Radian::Radian, Dali::Radian::radian.
Radian Dali::Clamp(Radian angle, float min, float max)
Clamps a radian value. @SINCE_1_0.0.
angle to clamp min value max value The resulting radian
References Dali::Radian::Radian, Dali::Radian::radian.
constexpr Radian Dali::ANGLE_360(Math::PI *2.f)
constexpr Radian Dali::ANGLE_315(Math::PI *1.75f)
constexpr Radian Dali::ANGLE_270(Math::PI *1.5f)
constexpr Radian Dali::ANGLE_225(Math::PI *1.25f)
constexpr Radian Dali::ANGLE_180(Math::PI)
constexpr Radian Dali::ANGLE_135(Math::PI *0.75f)
constexpr Radian Dali::ANGLE_120(Math::PI *2.f/3.f)
constexpr Radian Dali::ANGLE_90(Math::PI_2)
constexpr Radian Dali::ANGLE_60(Math::PI/3.f)
constexpr Radian Dali::ANGLE_45(Math::PI_4)
constexpr Radian Dali::ANGLE_30(Math::PI/6.f)
constexpr Radian Dali::ANGLE_0(0.0f)
bool Dali::operator==(const Rect< T > &lhs, const Rect< T > &rhs)
Equality operator.
@SINCE_1_0.0 lhs First operand rhs Second operand True if boxes are exactly same
References Dali::Rect< T >::height, Dali::Rect< T >::width, Dali::Rect< T >::x, Dali::Rect< T >::y.
bool Dali::operator!=(const Rect< T > &lhs, const Rect< T > &rhs)
Inequality operator.
@SINCE_1_0.0 lhs The first rectangle rhs The second rectangle True if rectangles are not identical
bool Dali::operator==(const Rect< float > &lhs, const Rect< float > &rhs)
Equality operator specialization for float.
@SINCE_1_0.0 lhs The first rectangle rhs The second rectangle True if rectangles are exactly same
References Dali::GetRangedEpsilon, Dali::Rect< T >::height, Dali::Rect< T >::width, Dali::Rect< T >::x, Dali::Rect< T >::y.
Vector2 Dali::Min(const Vector2 &a, const Vector2 &b)
Returns a vector with components set to the minimum of the corresponding component in a and b.
If a=0,1 and b=1,0 returns a vector of 0,0. @SINCE_1_0.0 a A vector b A vector A vector containing the minimum of each component from a and b
References Dali::Vector2::x, Dali::Vector2::y.
Vector2 Dali::Max(const Vector2 &a, const Vector2 &b)
Returns a vector with components set to the maximum of the corresponding component in a and b.
If a=0,1 and b=1,0 returns a vector of 1,1. @SINCE_1_0.0 a A vector b A vector A vector containing the maximum of each component from a and b
References Dali::Vector2::x, Dali::Vector2::y.
DALI_CORE_API Vector2 Dali::Clamp(const Vector2 &v, const float &min, const float &max)
Clamps each of vector v's components between minimum and maximum values.
@SINCE_1_0.0 v A vector min The minimum value max The maximum value A vector containing the clamped components of v
References Dali::Vector2::Clamp.
Vector3 Dali::Min(const Vector3 &a, const Vector3 &b)
Returns a vector with components set to the minimum of the corresponding component in a and b.
If a=0,1,2 and b=2,1,0 returns a vector of 2,1,2. @SINCE_1_0.0 a A vector b A vector A vector containing the minimum of each component from a and b
Vector3 Dali::Max(const Vector3 &a, const Vector3 &b)
Returns a vector with components set to the maximum of the corresponding component in a and b.
If a=0,1 and b=1,0 returns a vector of 1,1. @SINCE_1_0.0 a A vector b A vector A vector containing the maximum of each component from a and b
References Dali::Max, Dali::Vector3::x, Dali::Vector3::y, Dali::Vector3::z.
DALI_CORE_API Vector3 Dali::Clamp(const Vector3 &v, const float &min, const float &max)
Clamps each of vector v's components between minimum and maximum values.
@SINCE_1_0.0 v A vector min The minimum value max The maximum value A vector containing the clamped components of v
References Dali::Vector3::Clamp.
Vector4 Dali::Min(const Vector4 &a, const Vector4 &b)
Returns a vector with components set to the minimum of the corresponding component in a and b.
If a=0,1,2,3 and b=4,0,1,2 returns a vector of 0,0,1,2. @SINCE_1_0.0 a A vector b A vector A vector containing the minimum of each component from a and b
Vector4 Dali::Max(const Vector4 &a, const Vector4 &b)
Returns a vector with components set to the maximum of the corresponding component in a and b.
If a=0,1,2,3 and b=4,0,1,2 returns a vector of 4,1,2,3. @SINCE_1_0.0 a A vector b A vector A vector containing the maximum of each component from a and b
References Dali::Max, Dali::Vector4::w, Dali::Vector4::x, Dali::Vector4::y, Dali::Vector4::z.
DALI_CORE_API Vector4 Dali::Clamp(const Vector4 &v, const float &min, const float &max)
Clamps each of vector v's components between minimum and maximum values.
@SINCE_1_0.0 v A vector min The minimum value max The maximum value A vector containing the clamped components of v
References Dali::Vector4::Clamp.
DALI_CORE_API std::ostream & Dali::operator<<(std::ostream &o, const Rect< int32_t > &rectangle)
Print Dali::Rect<int32_t>.
@SINCE_1_0.0 stream The output stream operator rectangle the rectangle to output The output stream operator
References Dali::Rect< T >::height, Dali::Rect< T >::width, Dali::Rect< T >::x, Dali::Rect< T >::y.
DALI_CORE_API std::ostream & Dali::operator<<(std::ostream &o, const Rect< float > &rectangle)
Print Dali::Rect<float>.
@SINCE_1_0.0 stream The output stream operator rectangle the rectangle to output The output stream operator
References Dali::Rect< T >::height, Dali::Rect< T >::width, Dali::Rect< T >::x, Dali::Rect< T >::y.
DALI_CORE_API std::ostream & Dali::operator<<(std::ostream &o, const Vector2 &vector)
Print a Vector2.
@SINCE_1_0.0 o The output stream operator vector The vector to print The output stream operator
References Dali::Vector2::x, Dali::Vector2::y.
DALI_CORE_API std::ostream & Dali::operator<<(std::ostream &o, const Vector3 &vector)
Prints a Vector3.
@SINCE_1_0.0 o The output stream operator vector The vector to print The output stream operator
References Dali::Vector3::x, Dali::Vector3::y, Dali::Vector3::z.
DALI_CORE_API std::ostream & Dali::operator<<(std::ostream &o, const Vector4 &vector)
Print a Vector4.
@SINCE_1_0.0 o The output stream operator vector The vector to print The output stream operator
References Dali::Vector4::w, Dali::Vector4::x, Dali::Vector4::y, Dali::Vector4::z.
DALI_CORE_API std::ostream & Dali::operator<<(std::ostream &o, const Quaternion &quaternion)
Prints a Quaternion.
@SINCE_1_0.0 o The output stream operator quaternion The quaternion to print The output stream operator
References Dali::Degree::degree, Dali::Quaternion::ToAxisAngle, Dali::Vector3::x, Dali::Vector3::y, Dali::Vector3::z.
DALI_CORE_API std::ostream & Dali::operator<<(std::ostream &o, const Matrix3 &matrix)
Prints a 3x3 matrix.
@SINCE_1_0.0 o The output stream operator matrix The matrix to print The output stream operator
References Dali::Matrix3::AsFloat.
DALI_CORE_API std::ostream & Dali::operator<<(std::ostream &o, const Matrix &matrix)
Prints a 4x4 matrix.
@SINCE_1_0.0 o The output stream operator matrix The matrix to print The output stream operator
References Dali::Matrix::AsFloat.
std::ostream & Dali::operator<<(std::ostream &o, const Dali::AngleAxis &angleAxis)
Prints an angle axis.
@SINCE_1_1.33 o The output stream operator angleAxis The angle axis to print The output stream operator
References Dali::AngleAxis::angle, Dali::AngleAxis::axis, Dali::Degree::degree, Dali::Vector3::x, Dali::Vector3::y, Dali::Vector3::z.