dali_core_signals
bool Dali::operator==(const CallbackBase &lhs, const CallbackBase &rhs)
Non-member equality operator. @SINCE_1_0.0.
lhs A reference to compare rhs A reference to compare to True if lhs is same as rhs
References Dali::CallbackBase::mImpl, Dali::CallbackBase::Impl::mObjectPointer, Dali::CallbackBase::mStaticFunction.
CallbackBase * Dali::MakeCallback(void(*function)(Args... args))
Creates a callback from a free function with parameter pack.
@SINCE_2_5.14 function The function to call A newly allocated Callback object, ownership transferred to caller
Referenced by Dali::Signal< Ret()>::Connect, Dali::Signal< Ret(Arg0)>::Connect, Dali::Signal< Ret(Arg0, Arg1)>::Connect, Dali::Signal< Ret(Arg0, Arg1, Arg2)>::Connect, Dali::Signal< Ret()>::Connect, Dali::Signal< Ret(Arg0)>::Connect, Dali::Signal< Ret(Arg0, Arg1)>::Connect, Dali::Signal< Ret(Arg0, Arg1, Arg2)>::Connect, Dali::Signal< void()>::Connect, Dali::Signal< void(Arg0)>::Connect, Dali::Signal< void(Arg0, Arg1)>::Connect, Dali::Signal< void(Arg0, Arg1, Arg2)>::Connect, Dali::SignalDelegate::Connect, Dali::Signal< void()>::Connect, Dali::Signal< void(Arg0)>::Connect, Dali::Signal< void(Arg0, Arg1)>::Connect, Dali::Signal< void(Arg0, Arg1, Arg2)>::Connect, Dali::Signal< Ret()>::Connect, Dali::Signal< Ret(Arg0)>::Connect, Dali::Signal< Ret(Arg0, Arg1)>::Connect, Dali::Signal< Ret(Arg0, Arg1, Arg2)>::Connect, Dali::Signal< void()>::Connect, Dali::Signal< void(Arg0)>::Connect, Dali::Signal< void(Arg0, Arg1)>::Connect, Dali::Signal< void(Arg0, Arg1, Arg2)>::Connect, Dali::Signal< Ret()>::Disconnect, Dali::Signal< Ret(Arg0)>::Disconnect, Dali::Signal< Ret(Arg0, Arg1)>::Disconnect, Dali::Signal< Ret(Arg0, Arg1, Arg2)>::Disconnect, Dali::Signal< Ret()>::Disconnect, Dali::Signal< Ret(Arg0)>::Disconnect, Dali::Signal< Ret(Arg0, Arg1)>::Disconnect, Dali::Signal< Ret(Arg0, Arg1, Arg2)>::Disconnect, Dali::Signal< void()>::Disconnect, Dali::Signal< void(Arg0)>::Disconnect, Dali::Signal< void(Arg0, Arg1)>::Disconnect, Dali::Signal< void(Arg0, Arg1, Arg2)>::Disconnect, Dali::Signal< void()>::Disconnect, Dali::Signal< void(Arg0)>::Disconnect, Dali::Signal< void(Arg0, Arg1)>::Disconnect, Dali::Signal< void(Arg0, Arg1, Arg2)>::Disconnect, Dali::Signal< Ret()>::Disconnect, Dali::Signal< Ret(Arg0)>::Disconnect, Dali::Signal< Ret(Arg0, Arg1)>::Disconnect, Dali::Signal< Ret(Arg0, Arg1, Arg2)>::Disconnect, Dali::Signal< void()>::Disconnect, Dali::Signal< void(Arg0)>::Disconnect, Dali::Signal< void(Arg0, Arg1)>::Disconnect, Dali::Signal< void(Arg0, Arg1, Arg2)>::Disconnect, Dali::VertexBufferUpdateCallback::New, Dali::RenderCallback::RenderCallback.
CallbackBase * Dali::MakeCallback(R(*function)(Args... args))
Creates a callback from a free function with parameter pack.
@SINCE_1_9.33 function The function to call A newly allocated Callback object, ownership transferred to caller
CallbackBase * Dali::MakeCallback(T *object, void(T::*function)(void))
Creates a callback from a class member function with no parameters.
Requires the function to be member of the same class. @SINCE_1_0.0 object The object to call function The member function to call A newly allocated Callback object, ownership transferred to caller
CallbackBase * Dali::MakeCallback(T *object, void(T::*function)(P1))
Creates a callback from a class member function with one parameter.
Requires the function to be member of the same class. @SINCE_1_0.0 object The object to call function The member function to call A newly allocated Callback object, ownership transferred to caller
CallbackBase * Dali::MakeCallback(T *object, void(T::*function)(P1, P2))
Creates a callback from a class member function with two parameters.
Requires the function to be member of the same class. @SINCE_1_0.0 object The object to call function The member function to call A newly allocated Callback object, ownership transferred to caller
CallbackBase * Dali::MakeCallback(T *object, void(T::*function)(P1, P2, P3))
Creates a callback from a class member function with three parameters.
Requires the function to be member of the same class. @SINCE_1_0.0 object The object to call function The member function to call A newly allocated Callback object, ownership transferred to caller
CallbackBase * Dali::MakeCallback(T *object, R(T::*function)())
Creates a callback from a class member function with no parameters and a return type.
Requires the function to be member of the same class. @SINCE_1_0.0 object The object to call function The member function to call A newly allocated Callback object, ownership transferred to caller
CallbackBase * Dali::MakeCallback(T *object, R(T::*function)(P1))
Creates a callback from a class member function with one parameter and a return type.
Requires the function to be member of the same class. @SINCE_1_0.0 object The object to call function The member function to call A newly allocated Callback object, ownership transferred to caller
CallbackBase * Dali::MakeCallback(T *object, R(T::*function)(P1, P2))
Creates a callback from a class member function with two parameters and a return type.
Requires the function to be member of the same class. @SINCE_1_0.0 object The object to call function The member function to call A newly allocated Callback object, ownership transferred to caller
CallbackBase * Dali::MakeCallback(T *object, R(T::*function)(P1, P2, P3))
Creates a callback from a class member function with three parameters and a return type.
Requires the function to be member of the same class. @SINCE_1_0.0 object The object to call function The member function to call A newly allocated Callback object, ownership transferred to caller
CallbackBase * Dali::MakeCallback(T *object, void(Base::*function)(void))
Creates a callback from a class's parent member function with no parameters.
Requires the function to be member of the same class. @SINCE_1_0.0 object The object to call function The member function to call A newly allocated Callback object, ownership transferred to caller
CallbackBase * Dali::MakeCallback(T &object, void(Base::*function)(void))
Creates a callback from a class's parent member function with no parameters.
Requires the function to be member of the same class. @SINCE_1_0.0 object The object to call function The member function to call A newly allocated Callback object, ownership transferred to caller