dali_core_object
PropertyRanges
For all objects deriving from Handle (including Actors). @SINCE_1_0.0.
typedef Pair< Property::Key, Property::Value > Dali::KeyValuePair
using Dali::StringValuePair = typedef Pair<Dali::String, Property::Value>
using Dali::PropertyNotifySignalType = typedef Signal<void(PropertyNotification&)>
Signal type for Dali::PropertyNotification::NotifySignal(). @SINCE_1_0.0.
Type * Dali::AnyCast(Any *any)
Extracts a pointer to the held type of an Any object from a pointer to that Any object (NULL if empty).
AnyCast helper functions @SINCE_1_0.0 any Pointer to an Any object Pointer to the Type held
References Dali::Any::GetPointer.
const Type * Dali::AnyCast(const Any *any)
Extracts a const pointer to the held type of an Any object from a pointer to that Any object (NULL if empty).
@SINCE_1_0.0 any const Pointer to an Any object const Pointer to the Type held
References Dali::Any::GetPointer.
Type Dali::AnyCast(Any &any)
Extracts a held value of type Type from an Any object from a reference to that Any object.
@SINCE_1_0.0 any The reference to an Any object Type value of type Type
References Dali::Any::Get.
Type Dali::AnyCast(const Any &any)
Extracts a held value of type Type from an Any object from a const reference to that Any object.
@SINCE_1_0.0 any The reference to an Any object Type value of type Type
References Dali::Any::Get.
Type & Dali::AnyCastReference(Any &any)
Extracts a reference to the held value of type Type from an Any object from a reference to that Any object.
@SINCE_1_0.0 any The reference to an Any object A reference to the Type value of type Type
References Dali::Any::Get.
const Type & Dali::AnyCastReference(const Any &any)
Extracts a const reference to the held value of type Type from an Any object from a const reference to that Any object.
@SINCE_1_0.0 any The reference to an Any object A const reference to the Type value of type Type
References Dali::Any::Get.
T Dali::DownCast(BaseHandle handle)
Template wrapper to downcast a base object handle to derived class handle.
@SINCE_1_0.0 handle Handle to a base object Handle pointer to either a valid deriving handle or an uninitialized handle The BaseHandle has been initialized.
Referenced by Dali::Actor::Actor, Dali::Animation::Animation, Dali::CameraActor::CameraActor, Dali::CustomActor::CustomActor, Dali::DecoratedVisualRenderer::DecoratedVisualRenderer, Dali::FrameBuffer::FrameBuffer, Dali::Geometry::Geometry, Dali::GestureDetector::GestureDetector, Dali::Layer::Layer, Dali::LongPressGestureDetector::LongPressGestureDetector, Dali::Constraint::operator=, Dali::Handle::operator=, Dali::UniformBlock::operator=, Dali::PanGestureDetector::PanGestureDetector, Dali::PinchGestureDetector::PinchGestureDetector, Dali::PropertyNotification::PropertyNotification, Dali::Renderer::Renderer, Dali::RenderTask::RenderTask, Dali::RenderTaskList::RenderTaskList, Dali::RotationGestureDetector::RotationGestureDetector, Dali::Sampler::Sampler, Dali::Shader::Shader, Dali::TapGestureDetector::TapGestureDetector, Dali::Texture::Texture, Dali::TextureSet::TextureSet, Dali::VertexBuffer::VertexBuffer, Dali::VisualRenderer::VisualRenderer.
bool Dali::operator==(const BaseHandle &lhs, const T &rhs)
Equality operator. @SINCE_1_0.0.
lhs A reference to compare rhs A reference to compare to True if the handle handles point to the same Dali resource, or if both are NULL
bool Dali::operator!=(const BaseHandle &lhs, const T &rhs)
Equality operator. @SINCE_1_0.0.
lhs A reference to compare rhs A reference to compare to True if the handle handles point to the different Dali resources
bool Dali::operator<(const BaseHandle &lhs, const BaseHandle &rhs)
Less than operator. @SINCE_1_0.0.
lhs A reference to compare rhs A reference to compare to True if lhs less than rhs
References Dali::BaseHandle::GetObjectPtr.
BaseObject & Dali::GetImplementation(Dali::BaseHandle &handle)
Gets the implementation of a handle.
@SINCE_1_0.0 handle The handle A reference to the object the handle points at
References DALI_ASSERT_ALWAYS, Dali::BaseHandle::GetBaseObject.
Referenced by Dali::Stage::Add, Dali::Integration::Scene::Add, Dali::Actor::Add, Dali::KeyFrames::Add, Dali::PanGestureDetector::AddAngle, Dali::Actor::AddCacheRenderer, Dali::Path::AddControlPoint, Dali::PanGestureDetector::AddDirection, Dali::DevelRenderer::AddDrawCommand, Dali::DevelStage::AddFrameCallback, Dali::Integration::Scene::AddFramePresentedCallback, Dali::Integration::Scene::AddFrameRenderedCallback, Dali::Path::AddPoint, Dali::Handle::AddPropertyNotification, Dali::Handle::AddPropertyNotification, Dali::Actor::AddRenderer, Dali::Constraint::AddSource, Dali::Geometry::AddVertexBuffer, Dali::Animation::Animate, Dali::Animation::Animate, Dali::Animation::Animate, Dali::Animation::Animate, Dali::Animation::AnimateBetween, Dali::Animation::AnimateBetween, Dali::Animation::AnimateBetween, Dali::Animation::AnimateBetween, Dali::Animation::AnimateBetween, Dali::Animation::AnimateBetween, Dali::Animation::AnimateBetween, Dali::Animation::AnimateBetween, Dali::Animation::AnimateBy, Dali::Animation::AnimateBy, Dali::Animation::AnimateBy, Dali::Animation::AnimateBy, Dali::Animation::AnimateTo, Dali::Animation::AnimateTo, Dali::Animation::AnimateTo, Dali::Animation::AnimateTo, Dali::Constraint::Apply, Dali::PathConstrainer::Apply, Dali::LinearConstrainer::Apply, Dali::DevelTexture::ApplyNativeFragmentShader, Dali::Constraint::ApplyPost, Dali::GestureDetector::Attach, Dali::FrameBuffer::AttachColorTexture, Dali::DevelFrameBuffer::AttachDepthStencilTexture, Dali::DevelFrameBuffer::AttachDepthTexture, Dali::HitTestAlgorithm::BuildPickingRay, Dali::DevelActor::CalculateCurrentScreenExtents, Dali::DevelActor::CalculateScreenExtents, Dali::DevelActor::CalculateScreenPosition, Dali::GestureDetector::CancelAllOtherGestureDetectors, Dali::DevelActor::ChildAddedSignal, Dali::DevelActor::ChildOrderChangedSignal, Dali::DevelActor::ChildRemovedSignal, Dali::Animation::Clear, Dali::PanGestureDetector::ClearAngles, Dali::RenderTask::ClearRenderResult, Dali::DevelVertexBuffer::ClearVertexBufferUpdateCallback, Dali::Constraint::Clone, Dali::UniformBlock::ConnectToShader, Dali::Integration::ConstraintSetInternalTag, Dali::Stage::ContextLostSignal, Dali::Stage::ContextRegainedSignal, Dali::TypeInfo::CreateInstance, Dali::RenderTaskList::CreateTask, Dali::Integration::RenderTaskList::CreateTask, Dali::GestureDetector::Detach, Dali::GestureDetector::DetachAll, Dali::LongPressGestureDetector::DetectedSignal, Dali::PanGestureDetector::DetectedSignal, Dali::PinchGestureDetector::DetectedSignal, Dali::RotationGestureDetector::DetectedSignal, Dali::TapGestureDetector::DetectedSignal, Dali::Integration::Scene::Discard, Dali::UniformBlock::DisconnectFromShader, Dali::BaseHandle::DoAction, Dali::Handle::DoesCustomPropertyExist, Dali::Stage::EventProcessingFinishedSignal, Dali::Integration::Scene::EventProcessingFinishedSignal, Dali::Actor::FindChildById, Dali::Actor::FindChildByName, Dali::Animation::FinishedSignal, Dali::RenderTask::FinishedSignal, Dali::Path::GenerateControlPoints, Dali::Texture::GenerateMipmaps, Dali::Integration::Scene::Get, Dali::TypeInfo::GetActionCount, Dali::TypeInfo::GetActionName, Dali::PanGestureDetector::GetAngle, Dali::TouchEvent::GetAngle, Dali::PanGestureDetector::GetAngleCount, Dali::Animation::GetAnimationId, Dali::Constraint::GetApplyRate, Dali::PropertyCondition::GetArgument, Dali::PropertyCondition::GetArgumentCount, Dali::CameraActor::GetAspectRatio, Dali::GestureDetector::GetAttachedActor, Dali::GestureDetector::GetAttachedActorCount, Dali::Stage::GetBackgroundColor, Dali::Integration::Scene::GetBackgroundColor, Dali::TypeInfo::GetBaseName, Dali::Animation::GetBlendPoint, Dali::Actor::GetCacheRendererCount, Dali::RenderTask::GetCameraActor, Dali::Actor::GetChildAt, Dali::Actor::GetChildCount, Dali::TypeInfo::GetChildPropertyIndex, Dali::TypeInfo::GetChildPropertyIndices, Dali::TypeInfo::GetChildPropertyName, Dali::TypeInfo::GetChildPropertyType, Dali::RenderTask::GetClearColor, Dali::RenderTask::GetClearEnabled, Dali::DevelFrameBuffer::GetColorAttachmentCount, Dali::FrameBuffer::GetColorTexture, Dali::DevelFrameBuffer::GetColorTexture, Dali::KeyEvent::GetCompose, Dali::PropertyNotification::GetCondition, Dali::PropertyNotification::GetCondition, Dali::Path::GetControlPoint, Dali::TypeInfo::GetCreator, Dali::RenderTask::GetCullMode, Dali::Animation::GetCurrentLoop, Dali::Animation::GetCurrentProgress, Dali::Handle::GetCurrentProperty, Dali::Integration::Scene::GetCurrentScreenOrientation, Dali::Integration::Scene::GetCurrentSurfaceOrientation, Dali::Integration::Scene::GetCurrentSurfaceRect, Dali::RenderTask::GetCurrentViewportPosition, Dali::RenderTask::GetCurrentViewportSize, Dali::Animation::GetDefaultAlphaFunction, Dali::WheelEvent::GetDelta, Dali::DevelFrameBuffer::GetDepthStencilTexture, Dali::DevelFrameBuffer::GetDepthTexture, Dali::KeyEvent::GetDeviceClass, Dali::HoverEvent::GetDeviceClass, Dali::TouchEvent::GetDeviceClass, Dali::HoverEvent::GetDeviceId, Dali::TouchEvent::GetDeviceId, Dali::KeyEvent::GetDeviceName, Dali::HoverEvent::GetDeviceName, Dali::TouchEvent::GetDeviceName, Dali::KeyEvent::GetDeviceSubclass, Dali::HoverEvent::GetDeviceSubclass, Dali::TouchEvent::GetDeviceSubclass, Dali::WheelEvent::GetDirection, Dali::Animation::GetDisconnectAction, Dali::PanGesture::GetDisplacement, Dali::PanGesture::GetDistance, Dali::VertexBuffer::GetDivisor, Dali::Stage::GetDpi, Dali::Integration::Scene::GetDpi, Dali::Animation::GetDuration, Dali::TouchEvent::GetEllipseRadius, Dali::Animation::GetEndAction, Dali::CameraActor::GetFarClippingPlane, Dali::CameraActor::GetFieldOfView, Dali::RenderTask::GetFrameBuffer, Dali::Integration::Scene::GetFramePresentedCallback, Dali::Integration::Scene::GetFrameRenderedCallback, Dali::Renderer::GetGeometry, Dali::PixelData::GetHeight, Dali::Texture::GetHeight, Dali::Actor::GetHeightForWidth, Dali::HoverEvent::GetHitActor, Dali::TouchEvent::GetHitActor, Dali::RenderTask::GetInputEnabled, Dali::CameraActor::GetInvertYAxis, Dali::KeyEvent::GetKeyCode, Dali::DevelKeyFrames::GetKeyFrame, Dali::DevelKeyFrames::GetKeyFrameCount, Dali::KeyEvent::GetKeyModifier, Dali::KeyEvent::GetKeyName, Dali::KeyEvent::GetKeyString, Dali::Integration::Scene::GetLastPanGestureState, Dali::Actor::GetLayer, Dali::Stage::GetLayer, Dali::Integration::Scene::GetLayer, Dali::Stage::GetLayerCount, Dali::Integration::Scene::GetLayerCount, Dali::PinchGesture::GetLocalCenterPoint, Dali::RotationGesture::GetLocalCenterPoint, Dali::LongPressGesture::GetLocalPoint, Dali::TapGesture::GetLocalPoint, Dali::HoverEvent::GetLocalPosition, Dali::TouchEvent::GetLocalPosition, Dali::KeyEvent::GetLogicalKey, Dali::Animation::GetLoopCount, Dali::Animation::GetLoopingMode, Dali::DevelFrameBuffer::GetMask, Dali::PanGestureDetector::GetMaximumMotionEventAge, Dali::TapGestureDetector::GetMaximumTapsRequired, Dali::LongPressGestureDetector::GetMaximumTouchesRequired, Dali::PanGestureDetector::GetMaximumTouchesRequired, Dali::DevelLongPressGestureDetector::GetMinimumHoldingTime, Dali::TapGestureDetector::GetMinimumTapsRequired, Dali::LongPressGestureDetector::GetMinimumTouchesRequired, Dali::PanGestureDetector::GetMinimumTouchesRequired, Dali::WheelEvent::GetModifiers, Dali::TouchEvent::GetMouseButton, Dali::DevelFrameBuffer::GetMultiSamplingLevel, Dali::TypeInfo::GetName, Dali::Integration::Scene::GetNativeId, Dali::Actor::GetNaturalSize, Dali::CameraActor::GetNearClippingPlane, Dali::PropertyNotification::GetNotifyMode, Dali::PropertyNotification::GetNotifyResult, Dali::TapGesture::GetNumberOfTaps, Dali::LongPressGesture::GetNumberOfTouches, Dali::PanGesture::GetNumberOfTouches, Dali::TapGesture::GetNumberOfTouches, Dali::Geometry::GetNumberOfVertexBuffers, Dali::RenderTask::GetOrderIndex, Dali::Integration::Scene::GetOverlayLayer, Dali::RenderTaskList::GetOverlayTask, Dali::Actor::GetParent, Dali::Integration::GetPixelDataBuffer, Dali::PixelData::GetPixelFormat, Dali::Texture::GetPixelFormat, Dali::Animation::GetPlayRange, Dali::WheelEvent::GetPoint, Dali::Path::GetPoint, Dali::Path::GetPointCount, Dali::HoverEvent::GetPointCount, Dali::TouchEvent::GetPointCount, Dali::PanGesture::GetPosition, Dali::TouchEvent::GetPressure, Dali::DevelAnimation::GetProgressNotification, Dali::CameraActor::GetProjectionMode, Dali::Handle::GetProperties, Dali::Handle::GetProperty, Dali::TypeInfo::GetPropertyCount, Dali::Handle::GetPropertyCount, Dali::Handle::GetPropertyIndex, Dali::TypeInfo::GetPropertyIndices, Dali::Handle::GetPropertyIndices, Dali::TypeInfo::GetPropertyName, Dali::Handle::GetPropertyName, Dali::Handle::GetPropertyType, Dali::TouchEvent::GetRadius, Dali::KeyEvent::GetReceiveTime, Dali::RenderTask::GetRefreshRate, Dali::Actor::GetRelayoutSize, Dali::Constraint::GetRemoveAction, Dali::RenderTask::GetRenderedScaleFactor, Dali::Actor::GetRendererAt, Dali::Actor::GetRendererCount, Dali::DevelStage::GetRenderingBehavior, Dali::RenderTask::GetRenderPassTag, Dali::RenderTask::GetRenderResult, Dali::TouchEvent::GetRenderTask, Dali::RenderTask::GetRenderTaskId, Dali::Stage::GetRenderTaskList, Dali::Integration::Scene::GetRenderTaskList, Dali::Actor::GetResizePolicy, Dali::Stage::GetRootLayer, Dali::Integration::Scene::GetRootLayer, Dali::RotationGesture::GetRotation, Dali::TextureSet::GetSampler, Dali::PinchGesture::GetScale, Dali::PinchGesture::GetScreenCenterPoint, Dali::RotationGesture::GetScreenCenterPoint, Dali::PanGesture::GetScreenDisplacement, Dali::PanGesture::GetScreenDistance, Dali::LongPressGesture::GetScreenPoint, Dali::TapGesture::GetScreenPoint, Dali::PanGesture::GetScreenPosition, Dali::HoverEvent::GetScreenPosition, Dali::TouchEvent::GetScreenPosition, Dali::PanGesture::GetScreenSpeed, Dali::RenderTask::GetScreenToFrameBufferFunction, Dali::RenderTask::GetScreenToFrameBufferMappingActor, Dali::PanGesture::GetScreenVelocity, Dali::Renderer::GetShader, Dali::TypeInfo::GetSignalCount, Dali::TypeInfo::GetSignalName, Dali::SingletonService::GetSingleton, Dali::Stage::GetSize, Dali::Integration::Scene::GetSize, Dali::VertexBuffer::GetSize, Dali::DevelFrameBuffer::GetSize, Dali::RenderTask::GetSourceActor, Dali::Constraint::GetSourceAt, Dali::Constraint::GetSourceCount, Dali::Gesture::GetSourceData, Dali::Gesture::GetSourceType, Dali::PanGesture::GetSpeed, Dali::PinchGesture::GetSpeed, Dali::Animation::GetSpeedFactor, Dali::Animation::GetState, Dali::Constraint::GetState, Dali::Gesture::GetState, Dali::KeyEvent::GetState, Dali::HoverEvent::GetState, Dali::TouchEvent::GetState, Dali::RenderTask::GetStopperActor, Dali::PixelData::GetStride, Dali::PixelData::GetStrideBytes, Dali::Integration::Scene::GetSurfaceRectChangedCount, Dali::Constraint::GetTag, Dali::PropertyNotification::GetTarget, Dali::Constraint::GetTargetObject, Dali::CameraActor::GetTargetPosition, Dali::Constraint::GetTargetProperty, Dali::PropertyNotification::GetTargetProperty, Dali::Actor::GetTargetSize, Dali::RenderTaskList::GetTask, Dali::RenderTaskList::GetTaskCount, Dali::TextureSet::GetTexture, Dali::TextureSet::GetTextureCount, Dali::Integration::GetTextureResourceId, Dali::Renderer::GetTextures, Dali::Integration::GetTextureType, Dali::Gesture::GetTime, Dali::HoverEvent::GetTime, Dali::KeyEvent::GetTime, Dali::TouchEvent::GetTime, Dali::WheelEvent::GetTime, Dali::Integration::Scene::GetTouchPropagationType, Dali::DevelActor::GetTouchRequired, Dali::CameraActor::GetType, Dali::KeyFrames::GetType, Dali::Gesture::GetType, Dali::WheelEvent::GetType, Dali::Geometry::GetType, Dali::TypeRegistry::GetTypeInfo, Dali::TypeRegistry::GetTypeInfo, Dali::BaseHandle::GetTypeInfo, Dali::BaseHandle::GetTypeName, Dali::TypeRegistry::GetTypeName, Dali::TypeRegistry::GetTypeNameCount, Dali::UniformBlock::GetUniformBlockName, Dali::PanGesture::GetVelocity, Dali::RenderTask::GetViewport, Dali::RenderTask::GetViewportGuideActor, Dali::PixelData::GetWidth, Dali::Texture::GetWidth, Dali::Actor::GetWidthForHeight, Dali::KeyEvent::GetWindowId, Dali::DevelActor::GetWorldColor, Dali::DevelActor::GetWorldTransform, Dali::GreaterThanCondition, Dali::GestureDetector::HandleEvent, Dali::Integration::HandleRemoveAllConstraints, Dali::Integration::HandleRemoveConstraints, Dali::Integration::HandleRemoveConstraints, Dali::Integration::Scene::Hide, Dali::Animation::Hide, Dali::HitTestAlgorithm::HitTest, Dali::DevelActor::HitTestResultSignal, Dali::Actor::HoveredSignal, Dali::Actor::InheritedVisibilityChangedSignal, Dali::InsideCondition, Dali::Integration::Scene::InterceptKeyEventSignal, Dali::DevelActor::InterceptTouchedSignal, Dali::DevelActor::InterceptWheelSignal, Dali::DevelRenderer::IsAdvancedBlendEquationApplied, Dali::KeyEvent::IsAltModifier, Dali::WheelEvent::IsAltModifier, Dali::KeyEvent::IsCtrlModifier, Dali::WheelEvent::IsCtrlModifier, Dali::DevelActor::IsEffectivelyVisible, Dali::RenderTask::IsExclusive, Dali::Integration::Scene::IsGeometryHittestEnabled, Dali::DevelActor::IsHittable, Dali::Actor::IsIgnored, Dali::Animation::IsLooping, Dali::DevelTexture::IsNative, Dali::KeyEvent::IsNoInterceptModifier, Dali::Integration::Scene::IsPartialUpdateEnabled, Dali::Integration::IsPixelDataReleaseAfterUpload, Dali::Handle::IsPropertyAConstraintInput, Dali::Handle::IsPropertyAnimatable, Dali::Handle::IsPropertyWritable, Dali::KeyEvent::IsRepeat, Dali::Integration::Scene::IsRotationCompletedAcknowledgementSet, Dali::KeyEvent::IsShiftModifier, Dali::WheelEvent::IsShiftModifier, Dali::Integration::Scene::IsVisible, Dali::Stage::KeepRendering, Dali::Integration::Scene::KeepRendering, Dali::RenderTask::KeepRenderResult, Dali::Integration::Scene::KeyEventGeneratedSignal, Dali::DevelStage::KeyEventGeneratedSignal, Dali::Integration::Scene::KeyEventMonitorSignal, Dali::Stage::KeyEventSignal, Dali::Integration::Scene::KeyEventSignal, Dali::Actor::LayoutDirectionChangedSignal, Dali::LessThanCondition, Dali::DevelActor::LookAt, Dali::Actor::Lower, Dali::Layer::Lower, Dali::Actor::LowerBelow, Dali::Layer::LowerBelow, Dali::Actor::LowerToBottom, Dali::Layer::LowerToBottom, Dali::Layer::MoveAbove, Dali::Layer::MoveBelow, Dali::DecoratedVisualRenderer::New, Dali::VisualRenderer::New, Dali::Renderer::New, Dali::DevelStage::NotifyFrameCallback, Dali::PropertyNotification::NotifySignal, Dali::ObjectRegistry::ObjectCreatedSignal, Dali::ObjectRegistry::ObjectDestroyedSignal, Dali::Actor::OffSceneSignal, Dali::Actor::OnRelayoutSignal, Dali::Actor::OnSceneSignal, Dali::DevelKeyFrames::OptimizeKeyFramesLinear, Dali::OutsideCondition, Dali::Animation::Pause, Dali::Animation::Play, Dali::Animation::PlayAfter, Dali::Animation::PlayFrom, Dali::Integration::Scene::ProcessEvents, Dali::DevelAnimation::ProgressReachedSignal, Dali::Handle::PropertySetSignal, Dali::Integration::Scene::QueueEvent, Dali::Actor::Raise, Dali::Layer::Raise, Dali::Actor::RaiseAbove, Dali::Layer::RaiseAbove, Dali::Actor::RaiseToTop, Dali::Layer::RaiseToTop, Dali::TapGestureDetector::ReceiveAllTapEvents, Dali::SingletonService::Register, Dali::Handle::RegisterProperty, Dali::Handle::RegisterProperty, Dali::Handle::RegisterProperty, Dali::Handle::RegisterUniqueProperty, Dali::Handle::RegisterUniqueProperty, Dali::Integration::ReleasePixelDataBuffer, Dali::Constraint::Remove, Dali::Stage::Remove, Dali::Integration::Scene::Remove, Dali::Actor::Remove, Dali::PathConstrainer::Remove, Dali::LinearConstrainer::Remove, Dali::PanGestureDetector::RemoveAngle, Dali::Actor::RemoveCacheRenderer, Dali::Handle::RemoveConstraints, Dali::Handle::RemoveConstraints, Dali::PanGestureDetector::RemoveDirection, Dali::DevelStage::RemoveFrameCallback, Dali::Renderer::RemoveGeometry, Dali::Handle::RemovePropertyNotification, Dali::Handle::RemovePropertyNotifications, Dali::Actor::RemoveRenderer, Dali::Actor::RemoveRenderer, Dali::Integration::Scene::RemoveSceneObject, Dali::Renderer::RemoveShader, Dali::RenderTaskList::RemoveTask, Dali::Renderer::RemoveTextures, Dali::Geometry::RemoveVertexBuffer, Dali::RenderTask::RenderUntil, Dali::Integration::Scene::RequestFullUpdate, Dali::Handle::ReserveCustomProperties, Dali::RenderTask::ResetViewportGuideActor, Dali::Actor::RotateBy, Dali::Actor::RotateBy, Dali::DevelCameraActor::RotateProjection, Dali::Path::Sample, Dali::Actor::ScaleBy, Dali::Stage::SceneCreatedSignal, Dali::Actor::ScreenToLocal, Dali::Constraint::SetApplyRate, Dali::CameraActor::SetAspectRatio, Dali::Integration::Scene::SetBackgroundColor, Dali::Stage::SetBackgroundColor, Dali::Animation::SetBlendPoint, Dali::RenderTask::SetCameraActor, Dali::RenderTask::SetClearColor, Dali::RenderTask::SetClearEnabled, Dali::RenderTask::SetCullMode, Dali::Animation::SetCurrentProgress, Dali::VertexBuffer::SetData, Dali::Animation::SetDefaultAlphaFunction, Dali::Animation::SetDisconnectAction, Dali::DevelPanGesture::SetDisplacement, Dali::VertexBuffer::SetDivisor, Dali::Integration::Scene::SetDpi, Dali::Animation::SetDuration, Dali::Animation::SetEndAction, Dali::RenderTask::SetExclusive, Dali::CameraActor::SetFarClippingPlane, Dali::CameraActor::SetFieldOfView, Dali::Sampler::SetFilterMode, Dali::Stage::SetForceRendering, Dali::Integration::Scene::SetForceRendering, Dali::RenderTask::SetFrameBuffer, Dali::Renderer::SetGeometry, Dali::Integration::Scene::SetGeometryHittestEnabled, Dali::Actor::SetIgnored, Dali::Geometry::SetIndexBuffer, Dali::Geometry::SetIndexBuffer, Dali::RenderTask::SetInputEnabled, Dali::CameraActor::SetInvertYAxis, Dali::DevelKeyEvent::SetKeyCode, Dali::DevelKeyFrames::SetKeyFrameValue, Dali::DevelKeyEvent::SetKeyModifier, Dali::DevelKeyEvent::SetKeyName, Dali::DevelKeyEvent::SetKeyString, Dali::Animation::SetLoopCount, Dali::Animation::SetLooping, Dali::Animation::SetLoopingMode, Dali::PanGestureDetector::SetMaximumMotionEventAge, Dali::TapGestureDetector::SetMaximumTapsRequired, Dali::PanGestureDetector::SetMaximumTouchesRequired, Dali::TapGestureDetector::SetMinimumTapsRequired, Dali::PanGestureDetector::SetMinimumTouchesRequired, Dali::DevelFrameBuffer::SetMultiSamplingLevel, Dali::Integration::Scene::SetNativeId, Dali::CameraActor::SetNearClippingPlane, Dali::DevelActor::SetNeedGesturePropagation, Dali::DevelKeyEvent::SetNoInterceptModifier, Dali::PropertyNotification::SetNotifyMode, Dali::DevelPanGesture::SetNumberOfTouches, Dali::RenderTask::SetOrderIndex, Dali::CameraActor::SetOrthographicProjection, Dali::Integration::Scene::SetPartialUpdateEnabled, Dali::CameraActor::SetPerspectiveProjection, Dali::Animation::SetPlayRange, Dali::DevelPanGesture::SetPosition, Dali::DevelAnimation::SetProgressNotification, Dali::CameraActor::SetProjectionMode, Dali::Handle::SetProperties, Dali::Handle::SetProperty, Dali::RenderTask::SetRefreshRate, Dali::Constraint::SetRemoveAction, Dali::Renderer::SetRenderCallback, Dali::RenderTask::SetRenderedScaleFactor, Dali::DevelStage::SetRenderingBehavior, Dali::RenderTask::SetRenderPassTag, Dali::DevelKeyEvent::SetRepeat, Dali::Actor::SetResizePolicy, Dali::Integration::Scene::SetRotationCompletedAcknowledgement, Dali::TextureSet::SetSampler, Dali::DevelPanGesture::SetScreenDisplacement, Dali::DevelPanGesture::SetScreenPosition, Dali::RenderTask::SetScreenToFrameBufferFunction, Dali::RenderTask::SetScreenToFrameBufferMappingActor, Dali::DevelPanGesture::SetScreenVelocity, Dali::Renderer::SetShader, Dali::Layer::SetSortFunction, Dali::RenderTask::SetSourceActor, Dali::Animation::SetSpeedFactor, Dali::DevelKeyEvent::SetState, Dali::Integration::Scene::SetSurfaceRenderTarget, Dali::Constraint::SetTag, Dali::CameraActor::SetTargetPosition, Dali::TextureSet::SetTexture, Dali::Integration::SetTexturePixelFormat, Dali::Renderer::SetTextures, Dali::Integration::SetTextureSize, Dali::DevelPanGesture::SetTime, Dali::DevelKeyEvent::SetTime, Dali::DevelTouchEvent::SetTime, Dali::LongPressGestureDetector::SetTouchesRequired, Dali::LongPressGestureDetector::SetTouchesRequired, Dali::CameraActor::SetType, Dali::Geometry::SetType, Dali::DevelHandle::SetTypeInfo, Dali::DevelPanGesture::SetVelocity, Dali::DevelVertexBuffer::SetVertexBufferUpdateCallback, Dali::RenderTask::SetViewport, Dali::RenderTask::SetViewportGuideActor, Dali::RenderTask::SetViewportPosition, Dali::RenderTask::SetViewportSize, Dali::DevelKeyEvent::SetWindowId, Dali::Sampler::SetWrapMode, Dali::Sampler::SetWrapMode, Dali::Integration::Scene::Show, Dali::Animation::Show, Dali::StepCondition, Dali::Animation::Stop, Dali::Handle::Supports, Dali::Integration::Scene::SurfaceReplaced, Dali::Integration::Scene::SurfaceResized, Dali::Integration::Scene::SurfaceRotated, Dali::DevelActor::SwitchParent, Dali::Renderer::TerminateRenderCallback, Dali::Integration::TextureUploadWithContent, Dali::Stage::TouchedSignal, Dali::Integration::Scene::TouchedSignal, Dali::Actor::TouchedSignal, Dali::Actor::TranslateBy, Dali::Actor::Unparent, Dali::SingletonService::UnregisterAll, Dali::Texture::Upload, Dali::Texture::Upload, Dali::DevelTexture::UploadSubPixelData, Dali::DevelTexture::UploadSubPixelData, Dali::VariableStepCondition, Dali::RenderTask::ViewportToLocal, Dali::DevelActor::VisibilityChangedSignal, Dali::Integration::Scene::WheelEventGeneratedSignal, Dali::Stage::WheelEventSignal, Dali::Integration::Scene::WheelEventSignal, Dali::Actor::WheelEventSignal, Dali::RenderTask::WorldToViewport, Dali::CustomActor::~CustomActor.
const BaseObject & Dali::GetImplementation(const Dali::BaseHandle &handle)
Gets the implementation of a handle.
@SINCE_1_0.0 handle The handle A reference to the object the handle points at
References DALI_ASSERT_ALWAYS, Dali::BaseHandle::GetBaseObject.
DALI_CORE_API PropertyCondition Dali::LessThanCondition(float arg)
LessThanCondition compares whether property is less than arg.
property type: bool (false = 0.0f, true = 1.0f) float (float) vector2 (the 2D length) vector3 (the 3D length) vector4 (the 4D length) @SINCE_1_0.0 arg The argument for the condition A property condition function object
References Dali::GetImplementation.
DALI_CORE_API PropertyCondition Dali::GreaterThanCondition(float arg)
GreaterThanCondition compares whether property is greater than arg.
property type: bool (false = 0.0f, true = 1.0f) float (float) vector2 (the 2D length) vector3 (the 3D length) vector4 (the 4D length) @SINCE_1_0.0 arg The argument for the condition A property condition function object
References Dali::GetImplementation.
DALI_CORE_API PropertyCondition Dali::InsideCondition(float arg0, float arg1)
InsideCondition compares whether property is greater than arg0 and less than arg1.
property type: bool (false = 0.0f, true = 1.0f) float (float) vector2 (the 2D length) vector3 (the 3D length) vector4 (the 4D length) @SINCE_1_0.0 arg0 The first argument for the condition arg1 The second argument for the condition A property condition function object
References Dali::GetImplementation.
DALI_CORE_API PropertyCondition Dali::OutsideCondition(float arg0, float arg1)
OutsideCondition compares whether property is less than arg0 or greater than arg1.
property type: bool (false = 0.0f, true = 1.0f) float (float) vector2 (the 2D length) vector3 (the 3D length) vector4 (the 4D length) @SINCE_1_0.0 arg0 The first argument for the condition arg1 The second argument for the condition A property condition function object
References Dali::GetImplementation.
DALI_CORE_API PropertyCondition Dali::StepCondition(float stepAmount, float initialValue=0.0f)
Detects when a property changes by stepAmount from initialValue, in both positive and negative directions. This will continue checking for multiples of stepAmount.
property type: float (float) vector2 (the 2D length) vector3 (the 3D length) vector4 (the 4D length) quaternion (the 3D length of eular angle) @SINCE_1_0.0 stepAmount The step size required to trigger condition initialValue The initial value to step from A property condition function object
References Dali::GetImplementation.
DALI_CORE_API PropertyCondition Dali::VariableStepCondition(const Dali::Vector< float > &steps)
Receives notifications as a property goes above/below the inputted values. Values must be ordered and can be either ascending or descending.
property type: float (float) vector2 (the 2D length) vector3 (the 3D length) vector4 (the 4D length) @SINCE_1_0.0 steps List of values to receive notifications for as a property crosses them A property condition function object
References Dali::GetImplementation, Dali::Vector< T, IsTrivialType >::PushBack.
DALI_CORE_API std::ostream & Dali::operator<<(std::ostream &ouputStream, const Property::Value &value)
Converts the value of the property into a string and appends to an output stream.
@SINCE_1_0.0 ouputStream The output stream operator value The value to insert The output stream operator
References Dali::Property::ARRAY, Dali::Property::BOOLEAN, Dali::Property::EXTENTS, Dali::Property::FLOAT, Dali::Property::INTEGER, Dali::Property::MAP, Dali::Property::MATRIX, Dali::Property::MATRIX3, Dali::Property::NONE, Dali::Property::RECTANGLE, Dali::Property::ROTATION, Dali::Property::STRING, Dali::Property::VECTOR2, Dali::Property::VECTOR3, Dali::Property::VECTOR4.
DALI_CORE_API std::ostream & Dali::operator<<(std::ostream &stream, const Property::Map &map)
Converts the key/value pairs of the property map into a string and append to an output stream.
@SINCE_1_1.28 stream The output stream operator map The map to insert The output stream operator
DALI_CORE_API std::ostream & Dali::operator<<(std::ostream &stream, const Property::Array &array)
Converts the values of the property array into a string and append to an output stream.
@SINCE_1_1.28 stream The output stream operator array The array to insert The output stream operator
Referenced by Dali::operator<<.
DALI_CORE_API std::ostream & Dali::operator<<(std::ostream &stream, const Property::Key &key)
Convert the key into a string and append to an output stream.
@SINCE_1_2.7 stream The output stream operator. key the key to convert The output stream operator.
References Dali::operator<<.