dali_core_common
constexpr Vector4 Dali::DEFAULT_BACKGROUND_COLOR
static constexpr Vector4 Dali::DEBUG_BACKGROUND_COLOR(0.2f, 0.5f, 0.2f, 1.0f)
Dark green, useful for debugging visuals (texture / shader issues / culling etc.).
DALI_CORE_API void Dali::DaliAssertMessage(const char *location, const char *condition)
Method to log assertion message in DALI_ASSERT_ALWAYS macro below.
@SINCE_1_0.0 location Where the assertion occurred condition The assertion condition
References DALI_LOG_ERROR_NOFN.
DALI_CORE_API void Dali::DaliPrintBackTrace()
Print backtrace log if required.
Do nothing if ENABLE_BACKTRACE option off. @SINCE_2_3.2
Pair< typename DecayType< T1 >::type, typename DecayType< T2 >::type > Dali::MakePair(T1 &&t1, T2 &&t2)
Creates a Pair from two values.
It constructs a Pair efficiently with decayed types (removes references, const, volatile) T1 The type of the first value T2 The type of the second value t1 The first value t2 The second value A Pair containing the two values with decayed types @SINCE_2_5.16
void Dali::Swap(Pair< T1, T2 > &lhs, Pair< T1, T2 > &rhs)
Swap function for Pair (enables ADL lookup). @SINCE_2_5.16.
lhs First pair to swap rhs Second pair to swap
References Dali::Pair< T1, T2 >::Swap.
Referenced by Dali::Vector< T, IsTrivialType >::Remove, Dali::Pair< T1, T2 >::Swap.
DALI_CORE_API bool Dali::operator==(const char *other, const StringView &rhs)
Referenced by Dali::operator!=, Dali::operator!=, Dali::operator!=, Dali::operator!=.
DALI_CORE_API bool Dali::operator!=(const char *other, const StringView &rhs)
Referenced by Dali::Extents::operator=.
DALI_CORE_API bool Dali::operator==(const char *other, const String &rhs)
DALI_CORE_API bool Dali::operator!=(const char *other, const String &rhs)
constexpr const T & Dali::Min(const T &lhs, const T &rhs)
Get the smaller value.
@SINCE_2_5.8 lhs The first value. rhs The second value. T the smaller value.
Referenced by Dali::Rect< T >::Intersect, Dali::Rect< T >::Merge.
constexpr const T & Dali::Max(const T &lhs, const T &rhs)
Get the bigger value.
@SINCE_2_5.8 lhs The first value. rhs The second value. T the bigger value.
Referenced by Dali::Rect< T >::Intersect, Dali::Max, Dali::Max, Dali::Rect< T >::Merge.
constexpr void Dali::Swap(T &lhs, T &rhs)
Swap the value between left-hand-side and right-hand-side. It need move constructor and move assign.
@SINCE_2_5.10 lhs The first value. rhs The second value.
bool Dali::operator==(IntrusivePtr< T > const &lhs, IntrusivePtr< U > const &rhs)
Comparison overrides of objects wrapped by intrusive pointers.
@SINCE_1_0.0 lhs Intrusive pointer to compare with rhs Intrusive pointer to compare against True if the pointers point at the same object
References Dali::IntrusivePtr< T >::Get.
bool Dali::operator!=(IntrusivePtr< T > const &lhs, IntrusivePtr< U > const &rhs)
Comparison overrides of objects wrapped by intrusive pointers.
@SINCE_1_0.0 lhs Intrusive pointer to compare with rhs Intrusive pointer to compare against True if the pointers point at different objects
References Dali::IntrusivePtr< T >::Get.
bool Dali::operator==(IntrusivePtr< T > const &lhs, U *rhs)
Comparison overrides of objects wrapped by intrusive pointers.
@SINCE_1_0.0 lhs Intrusive pointer to compare with rhs Object to compare against True if the intrusive pointer points at the specified object
References Dali::IntrusivePtr< T >::Get.
bool Dali::operator!=(IntrusivePtr< T > const &lhs, U *rhs)
Comparison overrides of objects wrapped by intrusive pointers.
@SINCE_1_0.0 lhs Intrusive pointer to compare with rhs Intrusive pointer to compare against True if the intrusive pointer doesn't point at the specified object
References Dali::IntrusivePtr< T >::Get.
bool Dali::operator==(T *lhs, IntrusivePtr< U > const &rhs)
Comparison overrides of objects wrapped by intrusive pointers.
@SINCE_1_0.0 lhs Object to compare with rhs Intrusive pointer to compare against True if the intrusive pointer points at the specified object
References Dali::IntrusivePtr< T >::Get.
bool Dali::operator!=(T *lhs, IntrusivePtr< U > const &rhs)
Comparison overrides of objects wrapped by intrusive pointers.
@SINCE_1_0.0 lhs Object to compare with rhs Intrusive pointer to compare against True if the intrusive pointer doesn't point at the specified object
References Dali::IntrusivePtr< T >::Get.
bool Dali::operator==(IntrusivePtr< T > const &lhs, decltype(nullptr) rhs)
Comparison overrides of objects with nullptr_t.
@SINCE_2_1.12 lhs Intrusive pointer to compare with rhs nullptr True if the pointers is nullptr
References Dali::IntrusivePtr< T >::Get.
bool Dali::operator!=(IntrusivePtr< T > const &lhs, decltype(nullptr) rhs)
Comparison overrides of objects with nullptr_t.
@SINCE_2_1.12 lhs Intrusive pointer to compare with rhs nullptr True if the pointers is not nullptr
References Dali::IntrusivePtr< T >::Get.
bool Dali::operator==(decltype(nullptr) lhs, IntrusivePtr< T > const &rhs)
Comparison overrides of objects with nullptr_t.
@SINCE_2_1.12 lhs nullptr rhs Intrusive pointer to compare against True if the pointers is nullptr
References Dali::IntrusivePtr< T >::Get.
bool Dali::operator!=(decltype(nullptr) lhs, IntrusivePtr< T > const &rhs)
Comparison overrides of objects with nullptr_t.
@SINCE_2_1.12 lhs nullptr rhs Intrusive pointer to compare against True if the pointers is not nullptr
References Dali::IntrusivePtr< T >::Get.
bool Dali::operator<(IntrusivePtr< T > const &lhs, IntrusivePtr< U > const &rhs)
Comparison overrides of objects wrapped by intrusive pointers.
@SINCE_2_3.35 lhs Intrusive pointer to compare with rhs Intrusive pointer to compare against True if the pointers point of rhs is bigger than lhs
References Dali::IntrusivePtr< T >::Get.
bool Dali::operator<(T *lhs, IntrusivePtr< U > const &rhs)
Comparison overrides of objects wrapped by intrusive pointers.
@SINCE_2_3.35 lhs Object to compare with rhs Intrusive pointer to compare against True if the pointers point of rhs is bigger than lhs
References Dali::IntrusivePtr< T >::Get.
bool Dali::operator<(IntrusivePtr< T > const &lhs, U *rhs)
Comparison overrides of objects wrapped by intrusive pointers.
@SINCE_2_3.35 lhs Intrusive pointer to compare with rhs Object to compare against True if the pointers point of rhs is bigger than lhs
References Dali::IntrusivePtr< T >::Get.
bool Dali::operator<(decltype(nullptr) lhs, IntrusivePtr< T > const &rhs)
Comparison overrides of objects wrapped by intrusive pointers.
@SINCE_2_3.35 lhs nullptr rhs Intrusive pointer to compare against True if the pointers point of rhs is bigger than lhs
References Dali::IntrusivePtr< T >::Get.
bool Dali::operator<(IntrusivePtr< T > const &lhs, decltype(nullptr) rhs)
Comparison overrides of objects wrapped by intrusive pointers.
@SINCE_2_3.35 lhs Intrusive pointer to compare with rhs nullptr True if the pointers point of rhs is bigger than lhs
SharedPtr< Type > Dali::MakeShared(Args &&... args)
Creates a SharedPtr that manages a new object. @SINCE_2_5.16.
Type The type of the object to construct Args The types of arguments to forward to the constructor args The arguments to forward to the constructor of Type SharedPtr<Type> managing the newly created object
bool Dali::operator==(const SharedPtr< Type > &lhs, const SharedPtr< Type > &rhs) noexcept
Equality comparison operator for SharedPtr objects.
@SINCE_2_5.16 Type The type of object managed by the SharedPtr lhs The left-hand side SharedPtr to compare rhs The right-hand side SharedPtr to compare true if both SharedPtr objects are null or own the same pointer, false otherwise This comparison is based on pointer address equality, not value equality of the managed objects.
bool Dali::operator!=(const SharedPtr< Type > &lhs, const SharedPtr< Type > &rhs) noexcept
Inequality comparison operator for SharedPtr objects.
@SINCE_2_5.16 Type The type of object managed by the SharedPtr lhs The left-hand side SharedPtr to compare rhs The right-hand side SharedPtr to compare true if the SharedPtr objects manage different pointers, false otherwise
bool Dali::operator<(const SharedPtr< Type > &lhs, const SharedPtr< Type > &rhs) noexcept
Less-than comparison operator for SharedPtr objects.
Enables use of SharedPtr in ordered containers (e.g., map, set). @SINCE_2_5.16 Type The type of object managed by the SharedPtr lhs The left-hand side SharedPtr to compare rhs The right-hand side SharedPtr to compare true if lhs.Get() < rhs.Get(), false otherwise
bool Dali::operator<=(const SharedPtr< Type > &lhs, const SharedPtr< Type > &rhs) noexcept
Less-than-or-equal comparison operator for SharedPtr objects.
@SINCE_2_5.16 Type The type of object managed by the SharedPtr lhs The left-hand side SharedPtr to compare rhs The right-hand side SharedPtr to compare true if lhs.Get() <= rhs.Get(), false otherwise
bool Dali::operator>(const SharedPtr< Type > &lhs, const SharedPtr< Type > &rhs) noexcept
Greater-than comparison operator for SharedPtr objects.
@SINCE_2_5.16 Type The type of object managed by the SharedPtr. lhs The left-hand side SharedPtr to compare. rhs The right-hand side SharedPtr to compare. true if lhs.Get() > rhs.Get(), false otherwise.
bool Dali::operator>=(const SharedPtr< Type > &lhs, const SharedPtr< Type > &rhs) noexcept
Greater-than-or-equal comparison operator for SharedPtr objects.
@SINCE_2_5.16 Type The type of object managed by the SharedPtr. lhs The left-hand side SharedPtr to compare. rhs The right-hand side SharedPtr to compare. true if lhs.Get() >= rhs.Get(), false otherwise.
Type && Dali::Forward(typename RemoveReference< Type >::type &arg) noexcept
Perfect forwarding helper function.
Preserves the value category (lvalue/rvalue) of the argument when forwarding it to another function. This is a custom implementation of std::forward that doesn't depend on the standard library. For lvalue references (Type&), the argument is forwarded as an lvalue. For rvalue references (Type&&), the argument is forwarded as an rvalue. Type The type of the forwarding reference arg The argument to forward The argument with its value category preserved @SINCE_2_5.11 Example usage: template<typenameT> voidWrapper(T&&arg){ //ForwardargtoProcess,preservingwhetherit'sanlvalueorrvalue Process(Forward<T>(arg)); } intx=10; Wrapper(x);//Forward<int&>(x)-forwardsaslvalue Wrapper(20);//Forward<int>(20)-forwardsasrvalue
Type && Dali::Forward(typename RemoveReference< Type >::type &&arg) noexcept
Perfect forwarding helper function for rvalue references.
Overload for rvalue references. When called with an rvalue argument, this overload is selected and forwards it as an rvalue. Type The type of the forwarding reference arg The argument to forward The argument forwarded as an rvalue reference @SINCE_2_5.11
UniquePtr< Type > Dali::MakeUnique(Args &&... args)
Creates a UniquePtr that manages a new object. @SINCE_2_5.11.
Type The type of the object to construct Args The types of arguments to forward to the constructor args The arguments to forward to the constructor of Type UniquePtr<Type> managing the newly created object
bool Dali::operator==(const UniquePtr< Type, Deleter > &lhs, const UniquePtr< Type, Deleter > &rhs) noexcept
Equality comparison operator for UniquePtr objects.
@SINCE_2_5.11 Type The type of object managed by the UniquePtr Deleter The deleter type lhs The left-hand side UniquePtr to compare rhs The right-hand side UniquePtr to compare true if both UniquePtr objects are null or own the same pointer, false otherwise This comparison is based on pointer address equality, not value equality of the managed objects.
bool Dali::operator!=(const UniquePtr< Type, Deleter > &lhs, const UniquePtr< Type, Deleter > &rhs) noexcept
Inequality comparison operator for UniquePtr objects.
@SINCE_2_5.11 Type The type of object managed by the UniquePtr Deleter The deleter type lhs The left-hand side UniquePtr to compare rhs The right-hand side UniquePtr to compare true if the UniquePtr objects manage different pointers, false otherwise
bool Dali::operator<(const UniquePtr< Type, Deleter > &lhs, const UniquePtr< Type, Deleter > &rhs) noexcept
Less-than comparison operator for UniquePtr objects.
Enables use of UniquePtr in ordered containers (e.g., map, set). @SINCE_2_5.11 Type The type of object managed by the UniquePtr Deleter The deleter type lhs The left-hand side UniquePtr to compare rhs The right-hand side UniquePtr to compare true if lhs.Get() < rhs.Get(), false otherwise
bool Dali::operator<=(const UniquePtr< Type, Deleter > &lhs, const UniquePtr< Type, Deleter > &rhs) noexcept
Less-than-or-equal comparison operator for UniquePtr objects.
@SINCE_2_5.11 Type The type of object managed by the UniquePtr Deleter The deleter type lhs The left-hand side UniquePtr to compare rhs The right-hand side UniquePtr to compare true if lhs.Get() <= rhs.Get(), false otherwise
bool Dali::operator>(const UniquePtr< Type, Deleter > &lhs, const UniquePtr< Type, Deleter > &rhs) noexcept
Greater-than comparison operator for UniquePtr objects.
@SINCE_2_5.11 Type The type of object managed by the UniquePtr. Deleter The deleter type. lhs The left-hand side UniquePtr to compare. rhs The right-hand side UniquePtr to compare. true if lhs.Get() > rhs.Get(), false otherwise.
bool Dali::operator>=(const UniquePtr< Type, Deleter > &lhs, const UniquePtr< Type, Deleter > &rhs) noexcept
Greater-than-or-equal comparison operator for UniquePtr objects.
@SINCE_2_5.11 Type The type of object managed by the UniquePtr. Deleter The deleter type. lhs The left-hand side UniquePtr to compare. rhs The right-hand side UniquePtr to compare. true if lhs.Get() >= rhs.Get(), false otherwise.
DALI_CORE_API std::ostream & Dali::operator<<(std::ostream &outStream, const String &string)
Print a String.
@SINCE_2.5.15 o The output stream operator string The string to print The output stream operator
References Dali::Integration::ToStdStringView.
DALI_CORE_API std::ostream & Dali::operator<<(std::ostream &outStream, const StringView &stringView)
Print a StringView.
@SINCE_2.5.19 o The output stream operator stringView The string view to print The output stream operator
References Dali::Integration::ToStdStringView.
DALI_CORE_API std::ostream & Dali::operator<<(std::ostream &stream, const Extents &extents)
Converts the value of the extents into a string and insert in to an output stream.
@SINCE_1_2.62 stream The output stream operator extents The Extents to output The output stream operator
References Dali::Extents::bottom, Dali::Extents::end, Dali::Extents::start, Dali::Extents::top.