Dali::Scripting
DALI_CORE_API bool Dali::Scripting::EnumStringToInteger(const char *const value, const StringEnum *const table, uint32_t tableCount, int &integerEnum)
Find the enum as an integer from the table.
@SINCE_1_1.12 value The string equivalent (case-insensitive, comma separate to OR values). table A pointer to an array with the enumeration to string equivalents. tableCount Number of items in the array. integerEnum The value of the enum. true if one or more enums in value.
References DALI_LOG_ERROR, Dali::Scripting::StringEnum::string, Dali::Scripting::StringEnum::value.
Referenced by GetEnumeration, GetEnumerationProperty.
DALI_CORE_API uint32_t Dali::Scripting::FindEnumIndex(const char *value, const StringEnum *table, uint32_t tableCount)
Find the given enum index from the table.
value The string equivalent (case-insensitive). table A pointer to an array with the enumeration to string equivalents. tableCount Number of items in the array. The index of the enumeration. If enumeration is not found, logs an error and returns tableCount.
References DALI_LOG_ERROR, Dali::Scripting::StringEnum::string.
DALI_CORE_API Actor Dali::Scripting::NewActor(const Property::Map &map)
Creates an actor with the date from the property value map.
map The property value map with the properties (and hierarchy) of the actor required For example: { "type":"Actor", "position":[100,100,0], "actors": [ { "type":"Actor", "position":[0,0,0] } ] } A handle to the newly created actor.
References Dali::Actor::Add, Dali::TypeInfo::CreateInstance, DALI_LOG_ERROR, Dali::Actor::DownCast, Dali::Pair< T1, T2 >::first, Dali::TypeRegistry::Get, Dali::Handle::GetPropertyIndex, Dali::TypeRegistry::GetTypeInfo, Dali::Property::INVALID_INDEX, NewActor, Dali::Pair< T1, T2 >::second, Dali::Handle::SetProperty.
Referenced by NewActor.
DALI_CORE_API void Dali::Scripting::CreatePropertyMap(Actor actor, Property::Map &map)
Creates a Property::Map from the actor provided.
actor The base-actor from which a Property::Map should be created map This map is cleared and a property map of actor and its children is filled in
References Dali::Vector< T, IsTrivialType >::Begin, CreatePropertyMap, Dali::Vector< T, IsTrivialType >::End, Dali::Actor::GetChildAt, Dali::Actor::GetChildCount, Dali::Handle::GetProperty, Dali::Handle::GetPropertyIndices, Dali::Handle::GetPropertyName, Dali::BaseHandle::GetTypeName.
Referenced by CreatePropertyMap.
DALI_CORE_API void Dali::Scripting::NewAnimation(const Property::Map &map, Dali::AnimationData &outputAnimationData)
Creates description data required to create an Animation object from a property map.
map The property value map containing the animation description outputAnimationData Resultant data retrieved from the property map is written here
References Dali::AnimationData::AnimationDataElement::actor, Dali::AnimationData::Add, Dali::AnimationData::AnimationDataElement::alphaFunction, Dali::AlphaFunction::BOUNCE, Dali::AlphaFunction::EASE_IN, Dali::AlphaFunction::EASE_IN_OUT, Dali::AlphaFunction::EASE_IN_OUT_SINE, Dali::AlphaFunction::EASE_IN_SINE, Dali::AlphaFunction::EASE_IN_SQUARE, Dali::AlphaFunction::EASE_OUT, Dali::AlphaFunction::EASE_OUT_BACK, Dali::AlphaFunction::EASE_OUT_SINE, Dali::AlphaFunction::EASE_OUT_SQUARE, Dali::Pair< T1, T2 >::first, Dali::AlphaFunction::LINEAR, Dali::AnimationData::AnimationDataElement::property, Dali::AlphaFunction::REVERSE, Dali::Pair< T1, T2 >::second, Dali::AlphaFunction::SIN, Dali::AnimationData::AnimationDataElement::timePeriodDelay, Dali::AnimationData::AnimationDataElement::timePeriodDuration, Dali::AnimationData::AnimationDataElement::value.
bool Dali::Scripting::GetEnumeration(const char *value, const StringEnum *table, uint32_t tableCount, T &result)
Chooses the appropriate enumeration for the provided string from the given table.
value The string equivalent (case-insensitive, comma separate to OR values). table A pointer to an array with the enumeration to string equivalents. tableCount Number of items in the array. result The enum value True if the value was found from the table
References EnumStringToInteger.
bool Dali::Scripting::GetEnumerationProperty(const Property::Value &propertyValue, const StringEnum *table, uint32_t tableCount, T &result)
Gets the enumeration value from an enumeration property. An enumeration property is a property that can be set with either an INTEGER or STRING.
propertyValue The property containing the int or string value. table A pointer to an array with the enumeration to string equivalents. tableCount Number of items in the array. result The enum value. This is not modified if the enumeration could not be converted. True if the value was found successfully AND the value has changed. This is to allow the caller to do nothing if there is no change.
References Dali::String::CStr, EnumStringToInteger, Dali::Property::INTEGER, Dali::Property::STRING.
Referenced by GetBitmaskEnumerationProperty.
bool Dali::Scripting::GetBitmaskEnumerationProperty(const Property::Value &propertyValue, const Scripting::StringEnum *table, uint32_t tableCount, T &result)
Gets the enumeration value from a bitmask enumeration property. An enumeration property is a property that can be set with either an INTEGER, STRING or an ARRAY of STRING.
propertyValue The property containing the int, string or and array of string values. table A pointer to an array with the enumeration to string equivalents. tableCount Number of items in the array. result The enum value. This is not modified if the enumeration could not be converted. True if the value was found successfully AND the value has changed. This is to allow the caller to do nothing if there is no change.
References Dali::Property::ARRAY, GetEnumerationProperty.
const char * Dali::Scripting::GetEnumerationName(T value, const StringEnum *table, uint32_t tableCount)
Chooses the appropriate string for the provided enumeration from the given table.
value The enumeration. table A pointer to an array with the enumeration to string equivalents. tableCount Number of items in the array. The equivalent enumeration for the given string. Will return NULL if the value does not exist The caller is NOT responsible for cleaning up the returned pointer as it is statically allocated.
References Dali::Scripting::StringEnum::string.
const char * Dali::Scripting::GetLinearEnumerationName(T value, const StringEnum *table, uint32_t tableCount)
Chooses the appropriate string for the provided enumeration from the given table. This is an optimised version that handles enumerations that start at 0 and are linear only.
value The enumeration. table A pointer to an array with the enumeration to string equivalents. tableCount Number of items in the array. The equivalent enumeration for the given string. Will return NULL if the value does not exist The caller is NOT responsible for cleaning up the returned pointer as it is statically allocated.
References Dali::Scripting::StringEnum::string.