Dali::AddOns
Dali::AddOns::AddOnBase * Dali::AddOns::CreateAddOn()
The function is automatically added to the AddOn code with use of REGISTER_ADDON_CLASS() macro.
The valid pointer to the AddOnBase interface
Referenced by AddOnConstructorInternal.
void Dali::AddOns::GetAddOnInfo(Dali::AddOnInfo &info)
Fills AddOnInfo structure. info Reference to AddOnInfo structure
References Dali::AddOns::AddOnBase::Get.
Referenced by AddOnConstructorInternal, Dali::AddOns::DispatchTable::Find, Dali::AddOns::DispatchTable::Entry::operator=, Dali::AddOns::DispatchTable::operator[].
void * Dali::AddOns::GetGlobalProc(const char *funcname)
Returns pointer to AddOn's global function funcname Name of function Valid pointer or nullptr if function not found.
References Dali::AddOns::DispatchTable::Find, Dali::AddOns::AddOnBase::Get.
void * Dali::AddOns::GetInstanceProc(const char *funcname)
Returns pointer to AddOn's instance function funcname Name of function Valid pointer or nullptr if function not found.
References Dali::AddOns::DispatchTable::Find, Dali::AddOns::AddOnBase::Get.
void Dali::AddOns::OnStart()
Lifecycle functions to export. They will be instantiated only if macro REGISTER_ADDON_CLASS is used
References Dali::AddOns::AddOnBase::Get.
void Dali::AddOns::OnPause()
References Dali::AddOns::AddOnBase::Get.
void Dali::AddOns::OnResume()
References Dali::AddOns::AddOnBase::Get.
void Dali::AddOns::OnStop()
References Dali::AddOns::AddOnBase::Get.
void Dali::AddOns::AddOnConstructorInternal()
AddOn library internal constructor.
References CreateAddOn, Dali::Integration::AddOnManager::Get, GetAddOnInfo, Dali::AddOnDispatchTable::GetAddOnInfo, Dali::AddOnDispatchTable::GetGlobalProc, Dali::AddOnDispatchTable::GetInstanceProc, Dali::AddOnDispatchTable::name, Dali::AddOnDispatchTable::OnPause, Dali::AddOnDispatchTable::OnResume, Dali::AddOnDispatchTable::OnStart, Dali::AddOnDispatchTable::OnStop, Dali::Integration::AddOnManager::RegisterAddOnDispatchTable.