Dali::Integration::Log
DebugPriority
using Dali::Integration::Log::LogFunction = typedef void (*)(DebugPriority, std::string&)
typedef for the logging function.
thread_local LogFunction Dali::Integration::Log::gthreadLocalLogFunction
Referenced by InstallLogFunction, LogMessage, UninstallLogFunction.
std::string Dali::Integration::Log::FormatToString(const char *format,...)
References ArgListToString, FormatToString.
Referenced by FormatToString.
std::string Dali::Integration::Log::ArgListToString(const char *format, va_list args)
References ArgListToString.
Referenced by ArgListToString, FormatToString, LogMessage.
DALI_CORE_API void Dali::Integration::Log::LogMessage(DebugPriority priority, const char *format,...)
Used by logging macros to log a message level debug level format string format
References ArgListToString, DALI_UNLIKELY, gthreadLocalLogFunction.
Referenced by Dali::Integration::TimeChecker::ThresholdFilter::EndTimeCheck.
DALI_CORE_API void Dali::Integration::Log::InstallLogFunction(const LogFunction &logFunction)
A log function has to be installed for every thread that wants to use logging. This should be done by the adaptor. The log function can be different for each thread. If a log function is not installed, the log message will be print at stderr. logFunction the log function to install logOpts the log options to save in thread
References gthreadLocalLogFunction.
DALI_CORE_API void Dali::Integration::Log::UninstallLogFunction()
A log function has to be uninstalled for every thread that wants to use logging. The log function can be different for each thread.
References gthreadLocalLogFunction.
void Dali::Integration::Log::GetNanoseconds(uint64_t &timeInNanoseconds)
References GetNanoseconds.
Referenced by GetNanoseconds.