Dali::Integration
RenderToFrameBuffer
DepthBufferAvailable
StencilBufferAvailable
PartialUpdateAvailable
CorePolicyFlags
Zero means that no additional policy is set.
ProfilingType
using Dali::Integration::PointContainer = typedef std::vector<Point>
Container of points.
using Dali::Integration::PointContainerIterator = typedef PointContainer::iterator
Iterator for Dali::Integration::PointContainer.
using Dali::Integration::PointContainerConstIterator = typedef PointContainer::const_iterator
Const iterator for Dali::Integration::PointContainer.
DALI_CORE_API void Dali::Integration::ConstraintSetInternalTag(Dali::Constraint &constraint, const uint32_t tag)
Set tag number for given constraint. It should be called only for internal repositories. Have exclusive relation with SetTag().
Assert if we set internal tags which alread set some custom tag by application. @SINCE_2_4.14 constraint The constraint that want to set tag. tag The tag number.
References DALI_ASSERT_ALWAYS, Dali::GetImplementation, Dali::INTERNAL_CONSTRAINT_TAG_MAX, Dali::INTERNAL_CONSTRAINT_TAG_START.
DALI_CORE_API void Dali::Integration::HandleRemoveAllConstraints(Dali::Handle &handle)
Removes all the constraint from the Object include custom and internal. It should be called only for internal repositories.
@SINCE_2_4.14 handle The handle that want to remove all constraints.
References Dali::GetImplementation.
DALI_CORE_API void Dali::Integration::HandleRemoveConstraints(Dali::Handle &handle, uint32_t tag)
Removes all the constraint from the Object with a matching tag. It should be called only for internal repositories.
@SINCE_2_4.14 handle The handle that want to remove constraint by tag. tag The tag of the constraints which will be removed. Only internal tag be allowed.
References DALI_ASSERT_ALWAYS, Dali::GetImplementation, Dali::INTERNAL_CONSTRAINT_TAG_MAX, Dali::INTERNAL_CONSTRAINT_TAG_START.
DALI_CORE_API void Dali::Integration::HandleRemoveConstraints(Dali::Handle &handle, uint32_t tagBegin, uint32_t tagEnd)
Removes all the constraint from the Object with a range of tags [tagBegin tagEnd). It should be called only for internal repositories.
@SINCE_2_4.14 handle The handle that want to remove constraint by tag. tagBegin The begin tag of the constraints which will be removed. Only internal tag be allowed. (include) tagEnd The end tag of the constraints which will be removed. Only internal tag be allowed. (exclusived)
References DALI_ASSERT_ALWAYS, Dali::GetImplementation, Dali::INTERNAL_CONSTRAINT_TAG_MAX, Dali::INTERNAL_CONSTRAINT_TAG_START.
DALI_CORE_API Dali::TouchEvent Dali::Integration::NewTouchEvent(uint32_t timeStamp, const TouchPoint &point)
Create a new touch data handle from timestamp and touch point. timeStamp The time stamp of the touch event. point The point on screen where the touch occurred. A new touch data handle.
References NewTouchEvent.
Referenced by NewTouchEvent.
DALI_CORE_API Dali::TouchEvent Dali::Integration::NewTouchEvent(uint32_t timeStamp, const Dali::Integration::Point &point)
Create a new touch data handle from timestamp and point. timeStamp The time stamp of the touch event. point The point on screen where the touch occurred. A new touch data handle.
DALI_CORE_API Dali::HoverEvent Dali::Integration::NewHoverEvent(uint32_t timeStamp, const TouchPoint &point)
Create a new hover data handle from timestamp and point. timeStamp The time stamp of the hover event. point The point on screen where the hover occurred. A new hover data handle.
References NewHoverEvent.
Referenced by NewHoverEvent.
DALI_CORE_API Dali::HoverEvent Dali::Integration::NewHoverEvent(uint32_t timeStamp, const Dali::Integration::Point &point)
Create a new hover data handle from timestamp and point. timeStamp The time stamp of the hpver event. point The point on screen where the hover occurred. A new hover data handle.
DALI_CORE_API void Dali::Integration::SetPanGesturePredictionMode(int mode)
Called by adaptor to set the pan gesture prediction mode from an environment variable.
Should be called after Core creation. mode The pan gesture prediction mode.
DALI_CORE_API void Dali::Integration::SetPanGesturePredictionAmount(unsigned int amount)
Called by adaptor to set the prediction amount of the pan gesture from an environment variable.
amount The prediction amount in milliseconds
DALI_CORE_API void Dali::Integration::SetPanGestureMaximumPredictionAmount(unsigned int amount)
Sets the upper bound of the prediction amount for clamping from an environment variable.
amount The prediction amount in milliseconds
DALI_CORE_API void Dali::Integration::SetPanGestureMinimumPredictionAmount(unsigned int amount)
Sets the lower bound of the prediction amount for clamping from an environment variable.
amount The prediction amount in milliseconds
DALI_CORE_API void Dali::Integration::SetPanGesturePredictionAmountAdjustment(unsigned int amount)
Sets the prediction amount to adjust when the pan velocity is changed from an environment variable. If the pan velocity is accelerating, the prediction amount will be increased by the specified amount until it reaches the upper bound. If the pan velocity is decelerating, the prediction amount will be decreased by the specified amount until it reaches the lower bound.
amount The prediction amount in milliseconds
DALI_CORE_API void Dali::Integration::SetPanGestureSmoothingMode(int mode)
Called to set how pan gestures smooth input.
mode The smoothing mode to use
DALI_CORE_API void Dali::Integration::SetPanGestureSmoothingAmount(float amount)
Sets the smoothing amount of the pan gesture.
amount The smoothing amount [0.0f,1.0f] - 0.0f would be no smoothing, 1.0f maximum smoothing
DALI_CORE_API void Dali::Integration::SetPanGestureUseActualTimes(bool value)
Sets whether to use actual times of the real gesture and frames or not.
value True = use actual times, False = use perfect values
DALI_CORE_API void Dali::Integration::SetPanGestureInterpolationTimeRange(int value)
Sets the interpolation time range (ms) of past points to use (with weights) when interpolating.
value Time range in ms
DALI_CORE_API void Dali::Integration::SetPanGestureScalarOnlyPredictionEnabled(bool value)
Sets whether to use scalar only prediction, which when enabled, ignores acceleration.
value True = use scalar prediction only
DALI_CORE_API void Dali::Integration::SetPanGestureTwoPointPredictionEnabled(bool value)
Sets whether to use two point prediction. This combines two interpolated points to get more steady acceleration and velocity values.
value True = use two point prediction
DALI_CORE_API void Dali::Integration::SetPanGestureTwoPointInterpolatePastTime(int value)
Sets the time in the past to interpolate the second point when using two point interpolation.
value Time in past in ms
DALI_CORE_API void Dali::Integration::SetPanGestureTwoPointVelocityBias(float value)
Sets the two point velocity bias. This is the ratio of first and second points to use for velocity.
value 0.0f = 100% first point. 1.0f = 100% of second point.
DALI_CORE_API void Dali::Integration::SetPanGestureTwoPointAccelerationBias(float value)
Sets the two point acceleration bias. This is the ratio of first and second points to use for acceleration.
value 0.0f = 100% first point. 1.0f = 100% of second point.
DALI_CORE_API void Dali::Integration::SetPanGestureMultitapSmoothingRange(int value)
Sets the range of time (ms) of points in the history to perform multitap smoothing with (if enabled).
value Time in past in ms
DALI_CORE_API void Dali::Integration::SetPanGestureMinimumDistance(int value)
Sets the minimum distance required to start a pan gesture.
value Distance to move
DALI_CORE_API void Dali::Integration::SetPanGestureMinimumPanEvents(int value)
Sets the minimum number of touch events to start a pan.
value Number of pan events
DALI_CORE_API void Dali::Integration::SetPinchGestureMinimumDistance(float value)
Sets the minimum distance required to start a pinch gesture.
value Distance to move in pixels
DALI_CORE_API void Dali::Integration::SetPinchGestureMinimumTouchEvents(uint32_t value)
Sets the minimum touch events required before a pinch can be started.
value The number of touch events
DALI_CORE_API void Dali::Integration::SetPinchGestureMinimumTouchEventsAfterStart(uint32_t value)
Sets the minimum touch events required after a pinch started.
value The number of touch events
DALI_CORE_API void Dali::Integration::SetRotationGestureMinimumTouchEvents(uint32_t value)
Sets the minimum touch events required before a rotation can be started.
value The number of touch events
DALI_CORE_API void Dali::Integration::SetRotationGestureMinimumTouchEventsAfterStart(uint32_t value)
Sets the minimum touch events required after a rotation started.
value The number of touch events
DALI_CORE_API void Dali::Integration::SetLongPressMinimumHoldingTime(unsigned int value)
Sets the minimum holding time required to be recognized as a long press gesture.
value The time value in milliseconds
DALI_CORE_API void Dali::Integration::SetTapMaximumAllowedTime(uint32_t time)
Sets the maximum allowed time required to be recognized as a multi tap gesture (millisecond)
This is the maximum allowable time interval to recognize as multi-tap. If taps come in within this time, they are recognized as multi-tap. If it's a double tap, it's like this: |(touch down <recognizerTime--> touch up) < wihtin maximumAllowedTime --> (touch down <recognizerTime--> touch up)| SetTapRecognizerTime() time The time value in milliseconds
DALI_CORE_API void Dali::Integration::SetTapRecognizerTime(uint32_t time)
Sets the recognizer time required to be recognized as a tap gesture (millisecond)
This time is from touch down to touch up to recognize the tap gesture. The tab is like below: touch down <recognizerTime--> touch up If the time between touch down and touch up is longer than recognizer time, it is not recognized as a tap gesture. SetTapMaximumAllowedTime() time The time value in milliseconds
DALI_CORE_API void Dali::Integration::SetTapMaximumMotionAllowedDistance(float distance)
Sets the recognizer distance required to be recognized as a tap gesture.
This distance is from touch down to touch up to recognize the tap gesture. The tab is like below: touch down <distance--> touch up If the distance between touch down and touch up is longer than distance, it is not recognized as a tap gesture. Default value is 20 SetTapMaximumMotionAllowedDistance() distance The distance
DALI_CORE_API void Dali::Integration::ReleasePixelDataBuffer(Dali::PixelData pixelData)
Release the buffer from a pixel data object, zero it in the pixel data object. pixelData The pixel data object to take the buffer from
References Dali::GetImplementation.
DALI_CORE_API PixelDataBuffer Dali::Integration::GetPixelDataBuffer(const Dali::PixelData &pixelData)
Get the buffer from a pixel data object. pixelData The pixel data object to get the buffer from the buffer of pixelData.
References Dali::GetImplementation.
DALI_CORE_API Dali::PixelData Dali::Integration::NewPixelDataWithReleaseAfterUpload(uint8_t *buffer, uint32_t bufferSize, uint32_t width, uint32_t height, uint32_t strideBytes, Pixel::Format pixelFormat, PixelData::ReleaseFunction releaseFunction)
Creates a PixelData object which will release the buffer automatically after upload to texture. The pixel data object.
References Dali::IntrusivePtr< T >::Get.
DALI_CORE_API bool Dali::Integration::IsPixelDataReleaseAfterUpload(const Dali::PixelData &pixelData)
Get whether we need to release pixel data after texture upload or not. This function can be called from another thread. Be careful about thread safety. pixelData The pixel data object to get the release policy. True if we need to release pixel data after texture upload. False otherwise.
References Dali::GetImplementation.
DALI_CORE_API void Dali::Integration::EnableProfiling(ProfilingType type)
Called by adaptor to provide profiling information. Should be called after Core creation. type The type of profiling information to output.
References PROFILING_TYPE_END, PROFILING_TYPE_PAN_GESTURE.
DALI_CORE_API Dali::Shader Dali::Integration::ShaderNewWithUniformBlock(Dali::StringView vertexShader, Dali::StringView fragmentShader, Shader::Hint::Value hints, Dali::StringView shaderName, std::vector< Dali::UniformBlock > uniformBlocks, bool strongConnection=false)
Creates Shader and connect by given uniform blocks.
@SINCE_2_4.14 vertexShader Vertex shader code for the effect. fragmentShader Fragment Shader code for the effect. hints Hints to define the geometry of the rendered object shaderName The name of this shader. uniformBlocks Uniform blocks to be connected to shader. strongConnection Whether we connect uniform blocks to shader strong or weak. A handle to a shader effect
DALI_CORE_API Dali::Shader Dali::Integration::ShaderNewWithUniformBlock(Dali::Property::Value shaderMap, std::vector< Dali::UniformBlock > uniformBlocks, bool strongConnection=false)
Creates Shader and connect by given uniform blocks.
@SINCE_2_4.31 shaderMap Property::Map of shader data or Property::Array of Property::Map. Property::Map format is {"renderPassTag":"", "vertex":"", "fragment":"", "hints":""} shaderMap can be Property::Array of Property::Map for multi pass shading. uniformBlocks Uniform blocks to be connected to shader. strongConnection Whether we connect uniform blocks to shader strong or weak. A handle to a shader effect
DALI_CORE_API std::string Dali::Integration::GenerateTaggedShaderPrefix(const std::string &shaderPrefix)
Generates tag 'legacy-prefix-end' with end position of prefix text to make shader code parsing easier.
@SINCE_2_3.43 Generated string with tag.
DALI_CORE_API std::string Dali::Integration::ToStdString(String &&string)
Convert a Dali::String to a std::string by moving.
This moves the string data without copying. The source Dali::String will be left in a valid but empty state. For internal use where the implementation needs to work with std::string efficiently. string The Dali::String to move from A std::string containing the moved data
References Dali::Internal::StringImpl::Extract, ToStdString.
Referenced by Dali::BaseObject::DoAction, Dali::BaseObject::DoConnectSignal, TextureUploadWithContent, ToStdString, ToStdString, ToStdString, ToStdString.
DALI_CORE_API std::string Dali::Integration::ToStdString(const Property::Value &value)
Convert a Dali::Property::Value to a std::string.
Extracts the string from a Property::Value without copying the Property::Value wrapper itself. The string data is still copied internally (no const-ref getter exists on Property::Value). value The Property::Value (must be of type STRING) A std::string containing the same data
References DALI_ASSERT_DEBUG, Dali::Internal::StringImpl::Extract, Dali::Property::STRING, ToStdString.
DALI_CORE_API bool Dali::Integration::GetStdString(const Property::Value &value, std::string &out)
Extract a std::string from a Property::Value conditionally.
Restores the one-liner if(value.Get(str)) pattern that existed before the Dali::String migration. Returns true if the value was a string and was extracted successfully. value The Property::Value to extract from out The std::string to write to on success true if the value was a string and was extracted
References Dali::Internal::StringImpl::Extract.
DALI_CORE_API String Dali::Integration::ToDaliString(std::string &&string)
Convert a std::string to a Dali::String by moving.
This moves the string data without copying. The source std::string will be left in a valid but empty state. string The std::string to move from A Dali::String containing the moved data
References Dali::Internal::StringImpl::ToDaliString, ToDaliString.
Referenced by ToDaliString, ToDaliString, ToDaliString, ToDaliString.
std::string Dali::Integration::ToStdString(const String &string)
Convert a Dali::String to a std::string.
This creates a copy of the string data. For internal use where the implementation needs to work with std::string. string The Dali::String A std::string containing the same data
References ToStdString.
std::string Dali::Integration::ToStdString(const StringView &view)
Convert a Dali::StringView to a std::string.
This creates a copy of the viewed data. For internal use where the implementation needs to work with std::string. view The Dali::StringView A std::string containing the same data
References Dali::StringView::Data, Dali::StringView::Size, ToStdString.
Property::Value Dali::Integration::ToPropertyValue(std::string str)
Convert a std::string to a Dali::Property::Value of type STRING.
This creates a Dali::String from the std::string and wraps it in a Property::Value. For internal use where the implementation needs to produce Property::Value from std::string. str The std::string to convert A Property::Value containing the string data
Property::Array & Dali::Integration::AddToArray(Property::Array &array, const std::string &str)
Add a std::string to a Property::Array.
Wraps the recurring array.Add(ToDaliStringView(str)) pattern. array The array to append to str The std::string to add A reference to the array
Property::Map & Dali::Integration::InsertToMap(Property::Map &map, const std::string &key, const std::string &value)
Add string key, string value pair to a Property::Map.
This converts the key and the value to a String type, and adds them to the map. map The map to modify. key The string key to use value The string to use as a value A reference to the map
Property::Map & Dali::Integration::InsertToMap(Property::Map &map, const std::string &key, Property::Value value)
Add string key, string value pair to a Property::Map.
This converts the key and the value to a String type, and adds them to the map. map The map to modify. key The string key to use value The string to use as a value A reference to the map
Property::Map & Dali::Integration::InsertToMap(Property::Map &map, std::string_view key, const std::string &value)
Add string_view key, string value pair to a Property::Map.
Overload for std::string_view keys. Useful when keys are compile-time constants or std::string_view variables. map The map to modify. key The string_view key to use value The string to use as a value A reference to the map
Property::Map & Dali::Integration::InsertToMap(Property::Map &map, std::string_view key, Property::Value value)
Add string_view key, Property::Value pair to a Property::Map.
Overload for std::string_view keys. Useful when keys are compile-time constants or std::string_view variables. map The map to modify. key The string_view key to use value The Property::Value to insert A reference to the map
std::string_view Dali::Integration::ToStdStringView(const StringView &view)
Convert a Dali::StringView to a std::string_view.
This is a lightweight operation that creates a view over the same data without copying. view The Dali::StringView A std::string_view over the same data
References Dali::StringView::Data, Dali::StringView::Size, ToStdStringView.
Referenced by Dali::Property::Value::Impl::GetHash, Dali::operator<<, Dali::operator<<, ToStdStringView, ToStdStringView.
std::string_view Dali::Integration::ToStdStringView(const String &string)
Convert a Dali::String to a std::string_view.
This is a lightweight operation that creates a view over the String's data without copying. string The Dali::String A std::string_view over the string's data
References ToStdStringView.
StringView Dali::Integration::ToDaliStringView(const std::string &string)
Create a Dali::StringView from a std::string.
This is a lightweight operation that creates a view over the std::string's data without copying. string The std::string A Dali::StringView over the string's data
References ToDaliStringView.
Referenced by ToDaliStringView, ToDaliStringView.
StringView Dali::Integration::ToDaliStringView(std::string_view view)
Create a Dali::StringView from a std::string_view.
This is a lightweight operation that creates a view over the same data without copying. view The std::string_view A Dali::StringView over the same data
References ToDaliStringView.
String Dali::Integration::ToDaliString(const std::string &string)
Convert a std::string to a Dali::String.
This creates a copy of the string data. string The std::string A Dali::String containing the same data
References ToDaliString.
String Dali::Integration::ToDaliString(std::string_view view)
Convert a std::string_view to a Dali::String.
This creates a copy of the viewed data. view The std::string_view A Dali::String containing the same data
References ToDaliString.
String Dali::Integration::ToDaliString(const String &str)
Copy a Dali::String (no-op conversion for convenience).
This is a convenience overload that allows code to work with Dali::String without checking if conversion is needed. str The Dali::String A copy of the Dali::String
References ToDaliString.
DALI_CORE_API Dali::Texture Dali::Integration::NewTextureWithResourceId(Dali::TextureType::Type type, uint32_t resourceId)
Create new Dali::Texture with resourceId that Graphics::Controller can use.
type The type of the texture resourceId The unique id of this texture combinded with Graphics::Controller. A handle to a newly allocated Texture
DALI_CORE_API uint32_t Dali::Integration::GetTextureResourceId(Dali::Texture texture)
Get the resource id for this texture.
texture The texture to get resource id. The resource id what given texture has.
References Dali::GetImplementation.
DALI_CORE_API Dali::TextureType::Type Dali::Integration::GetTextureType(Dali::Texture texture)
Get the type for this texture.
texture The texture to get texture type. The texture type what given texture has.
References Dali::GetImplementation.
DALI_CORE_API void Dali::Integration::SetTextureSize(Dali::Texture texture, uint16_t width, uint16_t height)
Set the size of texture.
texture The texture to set size. width The width of texture to set. height The height of texture to set.
References Dali::GetImplementation.
DALI_CORE_API void Dali::Integration::SetTexturePixelFormat(Dali::Texture texture, Dali::Pixel::Format format)
Set the pixel format of texture.
texture The texture to set format. format The format of texture to set.
References Dali::GetImplementation.
DALI_CORE_API bool Dali::Integration::TextureUploadWithContent(Dali::Texture texture, Dali::PixelData pixelData, Dali::String context, TextureContextTypeHint::Type typeHint=TextureContextTypeHint::UNKNOWN)
Uploads data to the texture from a PixelData object, include context informations for profiling.
If texture is native or fast track case, we don't actual upload. Just update the context. In that case, pixelData only be used for get BytesPerPixel value. texture The texture to upload data to. pixelData The pixelData object context The context of the uploaded data typeHint Specifies hint for the texture which kind of image uploaded (optional) True if the PixelData object has compatible pixel format and fits within the texture, false otherwise
References Dali::GetImplementation, ToStdString.