Dali::Radian
float Dali::Radian::radian
The value in radians.
Referenced by Dali::Clamp, operator float, Dali::operator*, Dali::operator-, Dali::operator<, Dali::operator<, Dali::operator<, operator=, operator=, Dali::operator==, Dali::operator==, Dali::operator>, Dali::operator>, Dali::operator>, Dali::Quaternion::Quaternion, Dali::Quaternion::SetEuler, Dali::Quaternion::ToAxisAngle.
Dali::Radian::Radian()
Default constructor, initializes to 0. @SINCE_1_0.0.
Referenced by Dali::Clamp, Dali::operator*, Dali::operator-, Dali::operator<, Dali::operator<, Dali::operator==, Dali::operator>, Dali::operator>.
constexpr Dali::Radian::Radian(float value)
Creates an angle in radians.
@SINCE_1_0.0 value The initial value in radians
Dali::Radian::Radian(Degree degree)
Creates an angle in radians from an angle in degrees.
@SINCE_1_0.0 degree The initial value in degrees
Radian & Dali::Radian::operator=(float value)
Assigns an angle from a float value.
@SINCE_1_0.0 value Float value in radians A reference to this
References radian.
Radian & Dali::Radian::operator=(Degree degree)
Assigns an angle from a Degree value.
@SINCE_1_0.0 degree The value in degrees A reference to this
References Dali::Degree::degree, Dali::Math::PI_OVER_180, radian.
Dali::Radian::operator float() const
Conversion to float. @SINCE_1_0.0.
The float value of this Radian
References radian.
Dali::Radian::Radian(const Radian &)=default
Default copy constructor.
Dali::Radian::Radian(Radian &&) noexcept=default
Default move constructor.
Radian & Dali::Radian::operator=(const Radian &)=default
Default copy assignment operator.
Radian & Dali::Radian::operator=(Radian &&) noexcept=default
Default move assignment operator.