Dali::BaseSignal::EmitGuard
bool* Dali::BaseSignal::EmitGuard::mFlag
Pointer to the emit guard flag.
Referenced by Dali::BaseSignal::Emit, EmitGuard, Dali::BaseSignal::EmitReturn, Dali::BaseSignal::EmitReturnOr.
Dali::BaseSignal::EmitGuard::EmitGuard(bool &flag)
Creates the guard.
@SINCE_1_0.0 flag This flag will be set to true during Emit() calls
References DALI_LOG_ERROR, mFlag.
Dali::BaseSignal::EmitGuard::~EmitGuard()
Non-virtual destructor.
@SINCE_1_0.0
bool Dali::BaseSignal::EmitGuard::ErrorOccurred()
Determines if an error occurred.
@SINCE_1_0.0 True if an error occurred i.e. if Emit() was called during Emit()
Referenced by Dali::BaseSignal::Emit, Dali::BaseSignal::EmitReturn, Dali::BaseSignal::EmitReturnOr.