Dali::Any::AnyContainerBase
const ::std::type_info& Dali::Any::AnyContainerBase::mType
Referenced by GetType.
CloneFunc Dali::Any::AnyContainerBase::mCloneFunc
Referenced by Dali::Any::Any, Dali::Any::operator=.
DeleteFunc Dali::Any::AnyContainerBase::mDeleteFunc
Referenced by Dali::Any::operator=, Dali::Any::operator=, Dali::Any::~Any.
Dali::Any::AnyContainerBase::AnyContainerBase(const std::type_info &type, CloneFunc cloneFunc, DeleteFunc deleteFunc)
Constructor of base container.
@SINCE_1_0.0 type typeid of container cloneFunc Cloning function to replicate this container type deleteFunc Deleting function to destroy this container type
const std::type_info & Dali::Any::AnyContainerBase::GetType() const
Gets the typeid of this container.
@SINCE_1_0.0 Type
References mType.
Referenced by Dali::Any::Get, Dali::Any::GetPointer, Dali::Any::GetPointer, Dali::Any::GetType, Dali::Any::operator=, Dali::Any::operator=.