Dali::Integration::Point
TouchPoint Dali::Integration::Point::mTouchPoint
Stores screen position, device Id, local & screen positions and the hit-actor.
TouchPoint
Vector2 Dali::Integration::Point::mEllipseRadius
Radius of both the horizontal and vertical radius (useful if an ellipse).
Degree Dali::Integration::Point::mAngle
The angle of the press point, relative to the Y-Axis.
Device::Class::Type Dali::Integration::Point::mDeviceClass
Device::Subclass::Type Dali::Integration::Point::mDeviceSubclass
float Dali::Integration::Point::mPressure
The touch pressure.
float Dali::Integration::Point::mRadius
Radius of the press point, an average of the ellipse radius.
MouseButton::Type Dali::Integration::Point::mMouseButton
mouse button value.
Dali::String Dali::Integration::Point::mDeviceName
device name string.
Dali::Integration::Point::Point()
Default Constructor.
Dali::Integration::Point::Point(const TouchPoint &touchPoint)
Constructor which creates a Point instance from a TouchPoint.
touchPoint The touch-point to copy from.
Dali::Integration::Point::~Point()
Destructor.
void Dali::Integration::Point::SetDeviceId(int32_t deviceId)
Set the Unique Device ID.
Each touch point has a unique device ID which specifies the touch device for that point. deviceId The Unique Device ID.
References Dali::TouchPoint::deviceId.
void Dali::Integration::Point::SetState(PointState::Type state)
Set the state of the point.
state The state of the point.
References Dali::TouchPoint::state.
Referenced by Dali::Integration::TouchEventCombiner::GetNextTouchEvent.
void Dali::Integration::Point::SetScreenPosition(const Vector2 &screenPosition)
Set the screen position of the point from the top-left of the screen.
screenPosition The screen position of the point from the top-left of the screen.
References Dali::TouchPoint::screen.
void Dali::Integration::Point::SetRadius(float radius)
Set the radius of the press point.
This is the average of both the horizontal and vertical radii of the press point. radius The average of both the horizontal and vertical radii.
References Dali::Vector2::x, Dali::Vector2::y.
void Dali::Integration::Point::SetRadius(float radius, Vector2 ellipseRadius)
Set the radius of the press point as an ellipse.
radius The average of both the horizontal and vertical radii. ellipseRadius The horizontal and vertical radii of the press point (different if an ellipse).
void Dali::Integration::Point::SetPressure(float pressure)
Sets the touch pressure.
The pressure range starts at 0.0f. Normal pressure is defined as 1.0f. A value between 0.0f and 1.0f means light pressure has been applied. A value greater than 1.0f means more pressure than normal has been applied. pressure The touch pressure.
void Dali::Integration::Point::SetAngle(Degree angle)
Sets the angle of the press point relative to the Y-Axis.
angle The angle of the press point relative to the Y-Axis.
void Dali::Integration::Point::SetDeviceClass(Device::Class::Type deviceClass)
Sets the class of the device for the event.
deviceClass The class of the device.
void Dali::Integration::Point::SetDeviceSubclass(Device::Subclass::Type deviceSubclass)
Sets the subclass of the device for the event.
deviceSubclass The subclass of the device.
int Dali::Integration::Point::GetDeviceId() const
Retrieve the Unique Device ID of the point.
The Unique Device ID of the point.
References Dali::TouchPoint::deviceId.
Referenced by Dali::Integration::TouchEventCombiner::GetNextTouchEvent.
PointState::Type Dali::Integration::Point::GetState() const
Retrieve the state of the point.
The state of the point.
References Dali::TouchPoint::state.
Referenced by Dali::Integration::TouchEventCombiner::GetNextTouchEvent.
const Vector2 & Dali::Integration::Point::GetScreenPosition() const
Retrieve the screen position from the top-left of the screen.
The screen position from the top-left of the screen.
References Dali::TouchPoint::screen.
Referenced by Dali::Integration::TouchEventCombiner::GetNextTouchEvent.
float Dali::Integration::Point::GetRadius() const
Retrieve the radius of the press point.
The radius of the press point. SetRadius(float) SetRadius(float,Vector2)
const Vector2 & Dali::Integration::Point::GetEllipseRadius() const
Retrieve BOTH the horizontal and the vertical radii of the press point.
The radius of the press point. SetRadius(float) SetRadius(float,Vector2)
float Dali::Integration::Point::GetPressure() const
Retrieves the touch pressure.
The touch pressure. SetPressure()
Degree Dali::Integration::Point::GetAngle() const
Retrieve the angle of the press point relative to the Y-Axis.
The angle of the press point.
Device::Class::Type Dali::Integration::Point::GetDeviceClass() const
Retrieve the class of the device for the event.
The class of the device
Referenced by Dali::Integration::TouchEventCombiner::GetNextTouchEvent.
Device::Subclass::Type Dali::Integration::Point::GetDeviceSubclass() const
Retrieve the subclass of the device for the event.
The subclass of the device
MouseButton::Type Dali::Integration::Point::GetMouseButton() const
Get Mouse Button value. (ex: right/left button)
The mouse button value.
Referenced by Dali::Integration::TouchEventCombiner::GetNextTouchEvent.
void Dali::Integration::Point::SetMouseButton(MouseButton::Type button)
Set Mouse Button value. (ex: right/left button)
Referenced by Dali::Integration::TouchEventCombiner::GetNextTouchEvent.
const Dali::String & Dali::Integration::Point::GetDeviceName() const
Gets the device name the event originated from.
The device name.
void Dali::Integration::Point::SetDeviceName(Dali::String &deviceName)
Sets the device name the event originated from.
void Dali::Integration::Point::SetHitActor(Actor hitActor)
Sets the hit actor under this point.
hitActor The hit actor.
References Dali::TouchPoint::hitActor.
void Dali::Integration::Point::SetLocalPosition(const Vector2 &localPosition)
Set the co-ordinates relative to the top-left of the hit-actor.
localPosition The local position. The top-left of an actor is (0.0, 0.0, 0.5).
References Dali::TouchPoint::local.
Actor Dali::Integration::Point::GetHitActor() const
Retrieve the Hit Actor.
The hit actor.
References Dali::TouchPoint::hitActor.
const Vector2 & Dali::Integration::Point::GetLocalPosition() const
Retrieve the local position relative to the top-left of the hit-actor.
The local position. The top-left of an actor is (0.0, 0.0, 0.5).
References Dali::TouchPoint::local.
const TouchPoint & Dali::Integration::Point::GetTouchPoint() const
Retrieve the touch point equivalent of this point for old API.
The touch point equivalent.