Dali::Integration::OpenHashMapTraits
static Key Dali::Integration::OpenHashMapTraits< Key >::Empty()
Key value representing an empty slot (never occupied).
Referenced by Dali::Integration::OpenHashMap< Key, Value, Hash, KeyEqual >::Erase, Dali::Integration::OpenHashMap< Key, Value, Hash, KeyEqual >::Find, Dali::Integration::OpenHashMap< Key, Value, Hash, KeyEqual >::ForEach, Dali::Integration::OpenHashMap< Key, Value, Hash, KeyEqual >::ForEach, Dali::Integration::OpenHashMap< Key, Value, Hash, KeyEqual >::Insert.
static Key Dali::Integration::OpenHashMapTraits< Key >::Tombstone()
Key value representing a deleted slot (tombstone). Must differ from Empty() and from any valid key.
Referenced by Dali::Integration::OpenHashMap< Key, Value, Hash, KeyEqual >::Erase, Dali::Integration::OpenHashMap< Key, Value, Hash, KeyEqual >::Find, Dali::Integration::OpenHashMap< Key, Value, Hash, KeyEqual >::ForEach, Dali::Integration::OpenHashMap< Key, Value, Hash, KeyEqual >::ForEach, Dali::Integration::OpenHashMap< Key, Value, Hash, KeyEqual >::Insert.