Dali::Property::Value::Impl
Data Dali::Property::Value::Impl::mData
static Impl * Dali::Property::Value::Impl::New(Property::Value::Storage &buffer, Args... args)
static void Dali::Property::Value::Impl::Delete(Property::Value::Impl &impl)
Dali::Property::Value::Impl::~Impl()
Dali::Property::Value::Impl::Impl(const Impl &)=delete
Dali::Property::Value::Impl::Impl(Impl &&)=delete
Impl & Dali::Property::Value::Impl::operator=(Impl &&)=delete
Dali::Property::Value::Impl::Impl()
References SetType.
Dali::Property::Value::Impl::Impl(bool booleanValue)
References SetType.
Dali::Property::Value::Impl::Impl(float floatValue)
References SetType.
Dali::Property::Value::Impl::Impl(int32_t integerValue)
References SetType.
Dali::Property::Value::Impl::Impl(Vector2 vectorValue)
References SetType.
Dali::Property::Value::Impl::Impl(Vector3 vectorValue)
References SetType.
Dali::Property::Value::Impl::Impl(Extents extentsValue)
References SetType.
Dali::Property::Value::Impl::Impl(Property::Map mapValue)
References SetType.
Dali::Property::Value::Impl::Impl(Property::Array arrayValue)
References SetType.
Dali::Property::Value::Impl::Impl(Dali::String stringValue)
References SetType.
Dali::Property::Value::Impl::Impl(Rect< int32_t > rectValue)
References SetType.
Dali::Property::Value::Impl::Impl(Vector4 vectorValue)
References SetType.
Dali::Property::Value::Impl::Impl(Matrix3 matrixValue)
References SetType.
Dali::Property::Value::Impl::Impl(Matrix matrixValue)
References SetType.
Dali::Property::Value::Impl::Impl(AngleAxis angleAxisValue)
References SetType.
Type Dali::Property::Value::Impl::GetType() const
Referenced by GetHash, operator=, operator==.
bool Dali::Property::Value::Impl::GetBool() const
Referenced by operator=.
int32_t Dali::Property::Value::Impl::GetInt() const
Referenced by operator=.
float Dali::Property::Value::Impl::GetFloat() const
Referenced by operator=.
const Extents & Dali::Property::Value::Impl::GetExtents() const
Referenced by operator=.
const Vector2 & Dali::Property::Value::Impl::GetVector2() const
Referenced by operator=.
const Vector3 & Dali::Property::Value::Impl::GetVector3() const
Referenced by operator=.
const Property::Map & Dali::Property::Value::Impl::GetMap() const
Referenced by operator=.
const Property::Array & Dali::Property::Value::Impl::GetArray() const
Referenced by operator=.
const Vector4 & Dali::Property::Value::Impl::GetVector4() const
Referenced by operator=.
const Matrix3 & Dali::Property::Value::Impl::GetMatrix3() const
Referenced by operator=.
const Matrix & Dali::Property::Value::Impl::GetMatrix() const
Referenced by operator=.
const AngleAxis & Dali::Property::Value::Impl::GetAngleAxis() const
Referenced by operator=.
const Dali::String & Dali::Property::Value::Impl::GetString() const
Referenced by operator=.
const Rect< int32_t > & Dali::Property::Value::Impl::GetRect() const
Referenced by operator=.
Property::Map * Dali::Property::Value::Impl::GetMapPtr()
const Property::Map * Dali::Property::Value::Impl::GetMapPtr() const
Property::Array * Dali::Property::Value::Impl::GetArrayPtr()
const Property::Array * Dali::Property::Value::Impl::GetArrayPtr() const
Impl & Dali::Property::Value::Impl::operator=(const Impl &other)
References GetAngleAxis, GetArray, GetBool, GetExtents, GetFloat, GetInt, GetMap, GetMatrix, GetMatrix3, GetRect, GetString, GetType, GetVector2, GetVector3, GetVector4, SetType.
bool Dali::Property::Value::Impl::operator==(const Impl &other) const
References Dali::Equals, GetType.
void Dali::Property::Value::Impl::SetType(Type typeValue)
Referenced by ConvertType, Impl, Impl, Impl, Impl, Impl, Impl, Impl, Impl, Impl, Impl, Impl, Impl, Impl, Impl, Impl, operator=.
bool Dali::Property::Value::Impl::ConvertType(const Property::Type targetType)
References Dali::EqualsZero, SetType.
std::size_t Dali::Property::Value::Impl::GetHash() const
References GetType, Dali::Integration::ToStdStringView.
void Dali::Property::Value::Impl::ConstructInplace(Tp &member, Tp &&val)
This helper function takes a typed(Tp) memory location( member) and a object of same type( val ) and move constructs a new object of same type(Tp) in the memory location( member) using placement new. after this function call member location will have a object of type Tp.
void Dali::Property::Value::Impl::Destroy()
Destroy the object created in the Data union memory by probing the type and calling the appropriate destructor. and also reset the type and memory location to reflect that .