Dali::Vector4
const Vector4 Dali::Vector4::ONE
(1.0f,1.0f,1.0f,1.0f)
const Vector4 Dali::Vector4::XAXIS
(1.0f,0.0f,0.0f,0.0f)
const Vector4 Dali::Vector4::YAXIS
(0.0f,1.0f,0.0f,0.0f)
const Vector4 Dali::Vector4::ZAXIS
(0.0f,0.0f,1.0f,0.0f)
const Vector4 Dali::Vector4::ZERO
(0.0f, 0.0f, 0.0f, 0.0f)
Referenced by Dali::Random::Axis, Dali::AlphaFunction::GetBezierControlPoints.
float Dali::Vector4::x
x component
Referenced by Dali::Random::Axis, Dali::HitTestAlgorithm::BuildPickingRay, Clamp, Dali::Quaternion::Conjugate, Cross, Dot, Dot, Dot3, Dali::Quaternion::EulerAngles, Dali::Quaternion::Exp, Dali::Matrix::GetTransformComponents, Dali::Quaternion::IsIdentity, Length, Length3, LengthSquared, LengthSquared3, Dali::Quaternion::Log, Dali::Max, Normalize, Normalize3, Dali::Quaternion::operator*, Dali::Quaternion::operator*, Dali::Matrix::operator*, Dali::Quaternion::operator*=, Dali::Vector3::operator*=, operator*=, operator+=, Dali::Quaternion::operator-, operator-=, operator/=, Dali::operator<<, operator=, operator=, Dali::Vector2::operator=, Dali::Vector3::operator=, Dali::Rect< T >::operator=, Dali::Quaternion::operator==, operator==, Dali::Quaternion::Quaternion, Dali::Quaternion::Quaternion, Dali::Quaternion::Rotate, Dali::Quaternion::SetEuler, Dali::Matrix::SetInverseTransformComponents, Dali::Matrix::SetTransformComponents, Dali::Quaternion::ToAxisAngle.
float Dali::Vector4::r
red component
float Dali::Vector4::s
s component
union Dali::Vector4 Dali::Vector4
float Dali::Vector4::y
y component
Referenced by Dali::Random::Axis, Dali::HitTestAlgorithm::BuildPickingRay, Clamp, Dali::Quaternion::Conjugate, Cross, Dot, Dot, Dot3, Dali::Quaternion::EulerAngles, Dali::Quaternion::Exp, Dali::Matrix::GetTransformComponents, Dali::Quaternion::IsIdentity, Length, Length3, LengthSquared, LengthSquared3, Dali::Quaternion::Log, Dali::Max, Normalize, Normalize3, Dali::Quaternion::operator*, Dali::Quaternion::operator*, Dali::Matrix::operator*, Dali::Quaternion::operator*=, Dali::Vector3::operator*=, operator*=, operator+=, Dali::Quaternion::operator-, operator-=, operator/=, Dali::operator<<, operator=, operator=, Dali::Vector2::operator=, Dali::Vector3::operator=, Dali::Rect< T >::operator=, Dali::Quaternion::operator==, operator==, Dali::Quaternion::Quaternion, Dali::Quaternion::Quaternion, Dali::Quaternion::Rotate, Dali::Quaternion::SetEuler, Dali::Matrix::SetInverseTransformComponents, Dali::Matrix::SetTransformComponents, Dali::Quaternion::ToAxisAngle.
float Dali::Vector4::g
green component
float Dali::Vector4::t
t component
union Dali::Vector4 Dali::Vector4
float Dali::Vector4::z
z component
Referenced by Dali::Random::Axis, Dali::HitTestAlgorithm::BuildPickingRay, Clamp, Dali::Quaternion::Conjugate, Cross, Dot, Dot, Dot3, Dali::Quaternion::EulerAngles, Dali::Quaternion::Exp, Dali::Matrix::GetTransformComponents, Dali::Quaternion::IsIdentity, Length, Length3, LengthSquared, LengthSquared3, Dali::Quaternion::Log, Dali::Max, Normalize, Normalize3, Dali::Quaternion::operator*, Dali::Quaternion::operator*, Dali::Matrix::operator*, Dali::Quaternion::operator*=, Dali::Vector3::operator*=, operator*=, operator+=, Dali::Quaternion::operator-, operator-=, operator/=, Dali::operator<<, operator=, operator=, Dali::Vector3::operator=, Dali::Rect< T >::operator=, Dali::Quaternion::operator==, operator==, Dali::Quaternion::Quaternion, Dali::Quaternion::Quaternion, Dali::Quaternion::Rotate, Dali::Quaternion::SetEuler, Dali::Matrix::SetInverseTransformComponents, Dali::Matrix::SetTransformComponents, Dali::Quaternion::ToAxisAngle.
float Dali::Vector4::b
blue component
float Dali::Vector4::p
p component
union Dali::Vector4 Dali::Vector4
float Dali::Vector4::w
w component
Referenced by Dali::Random::Axis, Clamp, Dot, Dali::Quaternion::EulerAngles, Dali::Quaternion::Exp, Dali::Quaternion::IsIdentity, Length, LengthSquared, Dali::Quaternion::Log, Dali::Max, Normalize, Dali::Quaternion::operator*, Dali::Quaternion::operator*, Dali::Matrix::operator*, Dali::Quaternion::operator*=, Dali::Vector3::operator*=, operator*=, operator+=, Dali::Quaternion::operator-, operator-=, operator/=, Dali::operator<<, operator=, operator=, Dali::Rect< T >::operator=, Dali::Quaternion::operator==, operator==, Dali::Quaternion::Quaternion, Dali::Quaternion::Quaternion, Dali::Quaternion::SetEuler, Dali::Matrix::SetInverseTransformComponents, Dali::Matrix::SetInverseTransformComponents, Dali::Matrix::SetTransformComponents, Dali::Quaternion::ToAxisAngle.
float Dali::Vector4::a
alpha component
float Dali::Vector4::q
q component
union Dali::Vector4 Dali::Vector4
Dali::Vector4::Vector4()
Default constructor, initializes the vector to 0. @SINCE_1_0.0.
Referenced by Cross.
constexpr Dali::Vector4::Vector4(float x, float y, float z, float w)
Conversion constructor from four floats.
@SINCE_1_0.0 x x (or r/s) component y y (or g/t) component z z (or b/p) component w w (or a/q) component
Dali::Vector4::Vector4(const float *array)
Conversion constructor from an array of four floats.
@SINCE_1_0.0 array Array of either xyzw/rgba/stpq
Dali::Vector4::Vector4(const Vector2 &vec2)
Conversion constructor from Vector2.
@SINCE_1_0.0 vec2 Vector2 to copy from, z and w are initialized to 0
Dali::Vector4::Vector4(const Vector3 &vec3)
Conversion constructor from Vector3.
@SINCE_1_0.0 vec3 Vector3 to copy from, w is initialized to 0
Dali::Vector4::Vector4(const Vector3 &vec3, float w)
Conversion constructor from Vector3 and float.
@SINCE_2_4.19 vec3 Vector3 to copy from w w (or a/q) component
Vector4 & Dali::Vector4::operator=(const float *array)
Assignment operator.
@SINCE_1_0.0 array Array of floats Itself
Vector4 & Dali::Vector4::operator=(const Vector2 &vec2)
Assignment operator.
Only sets x and y. z and w are left as they were. @SINCE_1_0.0 vec2 A reference to assign from Itself
References w, Dali::Vector2::x, x, Dali::Vector2::y, y, z.
Vector4 & Dali::Vector4::operator=(const Vector3 &vec3)
Assignment operator.
Only sets x and y and z. w is left as it was. @SINCE_1_0.0 vec3 A reference to assign from Itself
References w, Dali::Vector3::x, x, Dali::Vector3::y, y, Dali::Vector3::z, z.
Vector4 Dali::Vector4::operator+(const Vector4 &rhs) const
Addition operator.
@SINCE_1_0.0 rhs Vector to add A vector containing the result of the addition
Vector4 & Dali::Vector4::operator+=(const Vector4 &rhs)
Addition assignment operator.
@SINCE_1_0.0 rhs Vector to add Itself
References w, x, y, z.
Vector4 Dali::Vector4::operator-(const Vector4 &rhs) const
Subtraction operator.
@SINCE_1_0.0 rhs The vector to subtract A vector containing the result of the subtraction
Vector4 & Dali::Vector4::operator-=(const Vector4 &rhs)
Subtraction assignment operator.
@SINCE_1_0.0 rhs The vector to subtract Itself
References w, x, y, z.
Vector4 Dali::Vector4::operator*(const Vector4 &rhs) const
Multiplication operator.
@SINCE_1_0.0 rhs The vector to multiply A vector containing the result of the multiplication
Vector4 Dali::Vector4::operator*(float rhs) const
Multiplication operator.
@SINCE_1_0.0 rhs The float value to scale the vector A vector containing the result of the scaling
Vector4 & Dali::Vector4::operator*=(const Vector4 &rhs)
Multiplication assignment operator.
@SINCE_1_0.0 rhs The vector to multiply Itself
References w, x, y, z.
Vector4 & Dali::Vector4::operator*=(float rhs)
Multiplication assignment operator.
@SINCE_1_0.0 rhs The float value to scale the vector Itself
Vector4 Dali::Vector4::operator/(const Vector4 &rhs) const
Division operator.
@SINCE_1_0.0 rhs The vector to divide A vector containing the result of the division
Vector4 Dali::Vector4::operator/(float rhs) const
Division operator.
@SINCE_1_0.0 rhs The float value to scale the vector by A vector containing the result of the scaling
Vector4 & Dali::Vector4::operator/=(const Vector4 &rhs)
Division assignment operator.
@SINCE_1_0.0 rhs The vector to divide Itself
References w, x, y, z.
Vector4 & Dali::Vector4::operator/=(float rhs)
Division assignment operator.
@SINCE_1_0.0 rhs The float value to scale the vector by Itself
Vector4 Dali::Vector4::operator-() const
Unary negation operator.
@SINCE_1_0.0 The negative value
bool Dali::Vector4::operator==(const Vector4 &rhs) const
Equality operator.
Utilizes appropriate machine epsilon values. @SINCE_1_0.0 rhs The vector to test against True if the vectors are equal
References Dali::GetRangedEpsilon, w, x, y, z.
bool Dali::Vector4::operator!=(const Vector4 &rhs) const
Inequality operator.
Utilizes appropriate machine epsilon values. @SINCE_1_0.0 rhs The vector to test against True if the vectors are not equal
const float & Dali::Vector4::operator[](const uint32_t index) const
Const array subscript operator overload.
Asserts if index is out of range. Should be 0, 1, 2 or 3. @SINCE_1_0.0 index Subscript index The float at the given index
References DALI_ASSERT_ALWAYS.
float & Dali::Vector4::operator[](const uint32_t index)
Mutable array subscript operator overload.
Asserts if index is out of range. Should be 0, 1, 2 or 3. @SINCE_1_0.0 index Subscript index The float at the given index
References DALI_ASSERT_ALWAYS.
float Dali::Vector4::Dot(const Vector3 &other) const
Returns the dot product of this vector (4d) and another vector (3d).
The dot product is the length of one vector in the direction of another vector. This is great for lighting, threshold testing the angle between two unit vectors, calculating the distance between two points in a particular direction. @SINCE_1_0.0 other The other vector The dot product
References Dali::Vector3::x, x, Dali::Vector3::y, y, Dali::Vector3::z, z.
Referenced by Dali::Quaternion::AngleBetween, Dali::Quaternion::Dot, Dot4.
float Dali::Vector4::Dot(const Vector4 &other) const
Returns the dot product of this vector and another vector.
@SINCE_1_0.0 It will consider w parameter After 2.4.19 other The other vector The dot product
References w, x, y, z.
float Dali::Vector4::Dot3(const Vector4 &other) const
Returns the dot product of this vector and another vector.
The dot product is the length of one vector in the direction of another vector. This is great for lighting, threshold testing the angle between two unit vectors, calculating the distance between two points in a particular direction. @SINCE_2_4.19 other The other vector The dot product
References x, y, z.
Referenced by Dali::Quaternion::operator*, Dali::Quaternion::operator*=.
float Dali::Vector4::Dot4(const Vector4 &other) const
Returns the 4d dot product of this vector and another vector.
@SINCE_1_0.0 @DEPRECATED_2_4.19 Use Dot instead. other The other vector The dot product
References Dot.
Vector4 Dali::Vector4::Cross(const Vector4 &other) const
Returns the cross produce of this vector and another vector.
The cross produce of two vectors is a vector which is perpendicular to the plane of the two vectors. This is great for calculating normals and making matrices orthogonal. @SINCE_1_0.0 other The other vector A vector containing the cross product
References Vector4, x, y, z.
Referenced by Dali::Matrix::OrthoNormalize.
float Dali::Vector4::Length() const
Returns the length of the vector.
@SINCE_1_0.0 It will consider w parameter After 2.4.19 The length
References w, x, y, z.
Referenced by Dali::Quaternion::Length, Normalize.
float Dali::Vector4::Length3() const
Returns the length of the xyz components of vector.
@SINCE_2_4.19 The length
References x, y, z.
Referenced by Dali::Quaternion::Exp, Normalize3.
float Dali::Vector4::LengthSquared() const
Returns the length of the vector squared.
This is faster than using Length() when performing threshold checks as it avoids use of the square root. @SINCE_1_0.0 The length of the vector squared
References w, x, y, z.
Referenced by Dali::Quaternion::LengthSquared.
float Dali::Vector4::LengthSquared3() const
Returns the length of the xyz components of vector squared.
This is faster than using Length3() when performing threshold checks as it avoids use of the square root. @SINCE_2_4.19 The length of the vector squared
References x, y, z.
void Dali::Vector4::Normalize()
Normalizes the vector.
Sets the vector to unit length whilst maintaining its direction. @SINCE_1_0.0 It will consider w parameter After 2.4.19
References Dali::EqualsZero, Length, w, x, y, z.
Referenced by Dali::Matrix::OrthoNormalize.
void Dali::Vector4::Normalize3()
Normalizes the xyz components of vector. w component not be changed.
Sets the vector to unit length whilst maintaining its direction. @SINCE_2_4.19
References Dali::EqualsZero, Length3, x, y, z.
Referenced by Dali::Random::Axis.
void Dali::Vector4::Clamp(const Vector4 &min, const Vector4 &max)
Clamps the vector between minimum and maximum vectors.
@SINCE_1_0.0 min The minimum vector max The maximum vector
References w, x, y, z.
Referenced by Dali::Clamp.
const float * Dali::Vector4::AsFloat() const
Returns the contents of the vector as an array of 4 floats.
Theorderofthevaluesinthisarrayareasfollows: 0:x(orr,ors) 1:y(org,ort) 2:z(orb,orp) 3:w(ora,orq) @SINCE_1_0.0 The vector contents as an array of 4 floats inlined for performance reasons (generates less code than a function call)
Referenced by Dali::Matrix::operator*.
float * Dali::Vector4::AsFloat()
Returns the contents of the vector as an array of 4 floats.
Theorderofthevaluesinthisarrayareasfollows: 0:x(orr,ors) 1:y(org,ort) 2:z(orb,orp) 3:w(ora,orq) @SINCE_1_0.0 The vector contents as an array of 4 floats inlined for performance reasons (generates less code than a function call)
Dali::Vector4::Vector4(const Vector4 &)=default
Default copy constructor.
Dali::Vector4::Vector4(Vector4 &&) noexcept=default
Default move constructor.
Vector4 & Dali::Vector4::operator=(const Vector4 &)=default
Default copy assignment operator.
Vector4 & Dali::Vector4::operator=(Vector4 &&) noexcept=default
Default move assignment operator.