Dali::Vector2
const Vector2 Dali::Vector2::ONE
(1.0f,1.0f)
const Vector2 Dali::Vector2::XAXIS
Vector representing the X axis.
const Vector2 Dali::Vector2::YAXIS
Vector representing the Y axis.
const Vector2 Dali::Vector2::NEGATIVE_XAXIS
Vector representing the negative X axis.
const Vector2 Dali::Vector2::NEGATIVE_YAXIS
Vector representing the negative Y axis.
const Vector2 Dali::Vector2::ZERO
(0.0f, 0.0f)
Referenced by Dali::CameraActor::New, Dali::CameraActor::New3DCamera.
float Dali::Vector2::x
x component
Referenced by Dali::HitTestAlgorithm::BuildPickingRay, Clamp, Dali::Integration::TouchEventCombiner::GetNextTouchEvent, LengthSquared, Dali::Max, Dali::Min, Normalize, operator*, operator*=, operator+=, operator-=, operator/, operator/=, Dali::operator<<, Dali::Vector3::operator=, Dali::Vector4::operator=, operator=, operator=, operator==, Dali::Integration::TouchEventCombiner::SetMinimumMotionDistanceThreshold, Dali::Integration::TouchEventCombiner::SetMinimumMotionDistanceThreshold, Dali::Integration::TouchEventCombiner::SetMinimumMotionDistanceThreshold, Dali::Integration::Point::SetRadius, Dali::Integration::TouchEventCombiner::TouchEventCombiner.
float Dali::Vector2::width
width
Referenced by Dali::GenerateDistanceFieldMap.
union Dali::Vector2 Dali::Vector2
float Dali::Vector2::y
y component
Referenced by Dali::HitTestAlgorithm::BuildPickingRay, Clamp, Dali::Integration::TouchEventCombiner::GetNextTouchEvent, LengthSquared, Dali::Max, Dali::Min, Normalize, operator*, operator*=, operator+=, operator-=, operator/, operator/=, Dali::operator<<, Dali::Vector3::operator=, Dali::Vector4::operator=, operator=, operator=, operator==, Dali::Integration::TouchEventCombiner::SetMinimumMotionDistanceThreshold, Dali::Integration::TouchEventCombiner::SetMinimumMotionDistanceThreshold, Dali::Integration::TouchEventCombiner::SetMinimumMotionDistanceThreshold, Dali::Integration::Point::SetRadius, Dali::Integration::TouchEventCombiner::TouchEventCombiner.
float Dali::Vector2::height
height
Referenced by Dali::GenerateDistanceFieldMap.
union Dali::Vector2 Dali::Vector2
Dali::Vector2::Vector2()
Constructor. @SINCE_1_0.0.
constexpr Dali::Vector2::Vector2(float x, float y)
Constructor.
@SINCE_1_0.0 x x or width component y y or height component
Dali::Vector2::Vector2(const float *array)
Conversion constructor from an array of two floats.
@SINCE_1_0.0 array Array of xy
Dali::Vector2::Vector2(const Vector3 &vec3)
Constructor.
@SINCE_1_0.0 vec3 Vector3 to create this vector from
Dali::Vector2::Vector2(const Vector4 &vec4)
Constructor.
@SINCE_1_0.0 vec4 Vector4 to create this vector from
Dali::Vector2::Vector2(const Uint16Pair &pair)
Conversion constructor from a Uint16Pair.
@SINCE_1_9.21 pair The Uint16Pair to create this vector from
Vector2 & Dali::Vector2::operator=(const float *array)
Assignment operator.
@SINCE_1_0.0 array Array of floats Itself
Vector2 & Dali::Vector2::operator=(const Vector3 &rhs)
Assignment operator.
@SINCE_1_0.0 rhs Vector to assign Itself
References x, Dali::Vector3::x, y, Dali::Vector3::y.
Vector2 & Dali::Vector2::operator=(const Vector4 &rhs)
Assignment operator.
@SINCE_1_0.0 rhs Vector to assign Itself
References x, Dali::Vector4::x, y, Dali::Vector4::y.
Vector2 Dali::Vector2::operator+(const Vector2 &rhs) const
Addition operator.
@SINCE_1_0.0 rhs Vector to add A vector containing the result of the addition
Vector2 & Dali::Vector2::operator+=(const Vector2 &rhs)
Addition assignment operator.
@SINCE_1_0.0 rhs Vector to add Itself
References x, y.
Vector2 Dali::Vector2::operator-(const Vector2 &rhs) const
Subtraction operator.
@SINCE_1_0.0 rhs The vector to subtract A vector containing the result of the subtraction
Vector2 & Dali::Vector2::operator-=(const Vector2 &rhs)
Subtraction assignment operator.
@SINCE_1_0.0 rhs The vector to subtract Itself
References x, y.
Vector2 Dali::Vector2::operator*(const Vector2 &rhs) const
Multiplication operator.
@SINCE_1_0.0 rhs The vector to multiply A vector containing the result of the multiplication
References x, y.
Vector2 Dali::Vector2::operator*(float rhs) const
Multiplication operator.
@SINCE_1_0.0 rhs The float value to scale the vector A vector containing the result of the scaling
Vector2 & Dali::Vector2::operator*=(const Vector2 &rhs)
Multiplication assignment operator.
@SINCE_1_0.0 rhs The vector to multiply Itself
References x, y.
Vector2 & Dali::Vector2::operator*=(float rhs)
Multiplication assignment operator.
@SINCE_1_0.0 rhs The float value to scale the vector Itself
Vector2 Dali::Vector2::operator/(const Vector2 &rhs) const
Division operator.
@SINCE_1_0.0 rhs The vector to divide A vector containing the result of the division
References x, y.
Vector2 Dali::Vector2::operator/(float rhs) const
Division operator.
@SINCE_1_0.0 rhs The float value to scale the vector by A vector containing the result of the scaling
Vector2 & Dali::Vector2::operator/=(const Vector2 &rhs)
Division assignment operator.
@SINCE_1_0.0 rhs The vector to divide Itself
References x, y.
Vector2 & Dali::Vector2::operator/=(float rhs)
Division assignment operator.
@SINCE_1_0.0 rhs The float value to scale the vector by Itself
Vector2 Dali::Vector2::operator-() const
Unary negation operator.
@SINCE_1_0.0 A vector containing the negation
bool Dali::Vector2::operator==(const Vector2 &rhs) const
Equality operator.
Utilizes appropriate machine epsilon values. @SINCE_1_0.0 rhs The vector to test against true if the vectors are equal
References Dali::GetRangedEpsilon, x, y.
bool Dali::Vector2::operator!=(const Vector2 &rhs) const
Inequality operator.
Utilizes appropriate machine epsilon values. @SINCE_1_0.0 rhs The vector to test against true if the vectors are not equal
const float & Dali::Vector2::operator[](const uint32_t index) const
Const array subscript operator overload.
Asserts if index is out of range. Should be 0 or 1. @SINCE_1_0.0 index Subscript index The float at the given index
References DALI_ASSERT_ALWAYS.
float & Dali::Vector2::operator[](const uint32_t index)
Mutable array subscript operator overload.
Asserts if index is out of range. Should be 0 or 1. @SINCE_1_0.0 index Subscript index The float at the given index
References DALI_ASSERT_ALWAYS.
float Dali::Vector2::Length() const
Returns the length of the vector.
@SINCE_1_0.0 The length of the vector
References LengthSquared.
Referenced by Normalize.
float Dali::Vector2::LengthSquared() const
Returns the length of the vector squared.
This is more efficient than Length() for threshold testing as it avoids the use of a square root. @SINCE_1_0.0 The length of the vector squared
References x, y.
Referenced by Length.
void Dali::Vector2::Normalize()
Sets the vector to be unit length, whilst maintaining its direction.
@SINCE_1_0.0
References Dali::EqualsZero, Length, x, y.
void Dali::Vector2::Clamp(const Vector2 &min, const Vector2 &max)
Clamps the vector between minimum and maximum vectors.
@SINCE_1_0.0 min The minimum vector max The maximum vector
References x, y.
Referenced by Dali::Clamp.
const float * Dali::Vector2::AsFloat() const
Returns the contents of the vector as an array of 2 floats.
The order of the values in this array are as follows: 0: x (or width) 1: y (or height) @SINCE_1_0.0 The vector contents as an array of 2 floats inlined for performance reasons (generates less code than a function call)
float * Dali::Vector2::AsFloat()
Returns the contents of the vector as an array of 2 floats.
The order of the values in this array are as follows: 0: x (or width) 1: y (or height) @SINCE_1_0.0 The vector contents as an array of 2 floats inlined for performance reasons (generates less code than a function call)
Dali::Vector2::Vector2(const Vector2 &)=default
Default copy constructor.
Dali::Vector2::Vector2(Vector2 &&) noexcept=default
Default move constructor.
Vector2 & Dali::Vector2::operator=(const Vector2 &)=default
Default copy assignment operator.
Vector2 & Dali::Vector2::operator=(Vector2 &&) noexcept=default
Default move assignment operator.