Dali::SignalConnectionBlock
SignalConnectionBlock* Dali::SignalConnectionBlock::mNext
Next block in chain.
Referenced by Dali::SignalConnectionPool::~SignalConnectionPool.
uint32_t Dali::SignalConnectionBlock::mCapacity
Number of slots in this block.
uint32_t Dali::SignalConnectionBlock::mHighWaterMark
Number of slots ever used (iteration bound)
SignalConnectionNode * Dali::SignalConnectionBlock::Slots()
Access the slot array that follows this header in memory. @SINCE_2_5.17.
Pointer to the first SignalConnectionNode slot
Referenced by Dali::SignalConnectionPool::IndexToNode, Dali::SignalConnectionPool::NodeToIndex, Dali::BaseSignal::~BaseSignal.
const SignalConnectionNode * Dali::SignalConnectionBlock::Slots() const
Access the slot array (const). @SINCE_2_5.17.
Const pointer to the first SignalConnectionNode slot