Dali::Vector3
const Vector3 Dali::Vector3::ONE
(1.0f,1.0f,1.0f)
Referenced by Dali::Matrix::GetTransformComponents.
const Vector3 Dali::Vector3::XAXIS
Vector representing the X axis.
const Vector3 Dali::Vector3::YAXIS
Vector representing the Y axis.
Referenced by Dali::LookAt.
const Vector3 Dali::Vector3::ZAXIS
Vector representing the Z axis.
const Vector3 Dali::Vector3::NEGATIVE_XAXIS
Vector representing the negative X axis.
const Vector3 Dali::Vector3::NEGATIVE_YAXIS
Vector representing the negative Y axis.
const Vector3 Dali::Vector3::NEGATIVE_ZAXIS
Vector representing the negative Z axis.
const Vector3 Dali::Vector3::ZERO
(0.0f, 0.0f, 0.0f)
float Dali::Vector3::x
x component
Referenced by Clamp, Cross, Dot, Dali::Vector4::Dot, Dali::Matrix::GetTransformComponents, Length, LengthSquared, Dali::Max, Normalize, Dali::Matrix3::operator*, operator*=, operator*=, operator+=, operator-=, operator/=, Dali::operator<<, Dali::operator<<, Dali::operator<<, operator=, Dali::Vector2::operator=, Dali::Vector4::operator=, operator=, operator==, Dali::Quaternion::Quaternion, Dali::Quaternion::Quaternion, Dali::Quaternion::Rotate, Dali::Matrix::SetIdentityAndScale, Dali::Matrix::SetInverseTransformComponents, Dali::Matrix::SetInverseTransformComponents, Dali::Matrix::SetTransformComponents, Dali::Matrix::SetXAxis, Dali::Matrix::SetYAxis, Dali::Matrix::SetZAxis, Dali::Quaternion::ToAxisAngle.
float Dali::Vector3::width
width component
float Dali::Vector3::r
red component
union Dali::Vector3 Dali::Vector3
float Dali::Vector3::y
y component
Referenced by Clamp, Cross, Dot, Dali::Vector4::Dot, Dali::Matrix::GetTransformComponents, Length, LengthSquared, Dali::Max, Normalize, Dali::Matrix3::operator*, operator*=, operator*=, operator+=, operator-=, operator/=, Dali::operator<<, Dali::operator<<, Dali::operator<<, operator=, Dali::Vector2::operator=, Dali::Vector4::operator=, operator=, operator==, Dali::Quaternion::Quaternion, Dali::Quaternion::Quaternion, Dali::Quaternion::Rotate, Dali::Matrix::SetIdentityAndScale, Dali::Matrix::SetInverseTransformComponents, Dali::Matrix::SetInverseTransformComponents, Dali::Matrix::SetTransformComponents, Dali::Matrix::SetXAxis, Dali::Matrix::SetYAxis, Dali::Matrix::SetZAxis, Dali::Quaternion::ToAxisAngle.
float Dali::Vector3::height
height component
float Dali::Vector3::g
green component
union Dali::Vector3 Dali::Vector3
float Dali::Vector3::z
z component
Referenced by Clamp, Cross, Dot, Dali::Vector4::Dot, Dali::Matrix::GetTransformComponents, Length, LengthSquared, Dali::Max, Normalize, Dali::Matrix3::operator*, operator*=, operator*=, operator+=, operator-=, operator/=, Dali::operator<<, Dali::operator<<, Dali::operator<<, operator=, Dali::Vector4::operator=, operator=, operator==, Dali::Quaternion::Quaternion, Dali::Quaternion::Quaternion, Dali::Quaternion::Rotate, Dali::Matrix::SetIdentityAndScale, Dali::Matrix::SetInverseTransformComponents, Dali::Matrix::SetInverseTransformComponents, Dali::Matrix::SetTransformComponents, Dali::Matrix::SetXAxis, Dali::Matrix::SetYAxis, Dali::Matrix::SetZAxis, Dali::Quaternion::ToAxisAngle.
float Dali::Vector3::depth
depth component
float Dali::Vector3::b
blue component
union Dali::Vector3 Dali::Vector3
Dali::Vector3::Vector3()
Constructor. @SINCE_1_0.0.
Referenced by Cross.
constexpr Dali::Vector3::Vector3(float x, float y, float z)
Constructor.
@SINCE_1_0.0 x (or width) component y (or height) component z (or depth) component
Dali::Vector3::Vector3(const float *array)
Conversion constructor from an array of three floats.
@SINCE_1_0.0 array Array of xyz
Dali::Vector3::Vector3(const Vector2 &vec2)
Constructor.
@SINCE_1_0.0 vec2 Vector2 to create this vector from
Dali::Vector3::Vector3(const Vector4 &vec4)
Constructor.
@SINCE_1_0.0 vec4 Vector4 to create this vector from
Vector3 & Dali::Vector3::operator=(const float *array)
Assignment operator.
@SINCE_1_0.0 array Array of floats Itself
Vector3 & Dali::Vector3::operator=(const Vector2 &rhs)
Assignment operator.
@SINCE_1_0.0 rhs Vector to assign Itself
References Dali::Vector2::x, x, Dali::Vector2::y, y, z.
Vector3 & Dali::Vector3::operator=(const Vector4 &rhs)
Assignment operator.
@SINCE_1_0.0 rhs Vector to assign Itself
References x, Dali::Vector4::x, y, Dali::Vector4::y, z, Dali::Vector4::z.
Vector3 Dali::Vector3::operator+(const Vector3 &rhs) const
Addition operator.
@SINCE_1_0.0 rhs Vector to add A vector containing the result of the addition
Vector3 & Dali::Vector3::operator+=(const Vector3 &rhs)
Addition assignment operator.
@SINCE_1_0.0 rhs Vector to add Itself
References x, y, z.
Vector3 Dali::Vector3::operator-(const Vector3 &rhs) const
Subtraction operator.
@SINCE_1_0.0 rhs The vector to subtract A vector containing the result of the subtraction
Vector3 & Dali::Vector3::operator-=(const Vector3 &rhs)
Subtraction assignment operator.
@SINCE_1_0.0 rhs The vector to subtract Itself
References x, y, z.
Vector3 Dali::Vector3::operator*(const Vector3 &rhs) const
Multiplication operator.
@SINCE_1_0.0 rhs The vector to multiply A vector containing the result of the multiplication
Vector3 Dali::Vector3::operator*(float rhs) const
Multiplication operator.
@SINCE_1_0.0 rhs The float value to scale the vector A vector containing the result of the scaling
Vector3 & Dali::Vector3::operator*=(const Vector3 &rhs)
Multiplication assignment operator.
@SINCE_1_0.0 rhs The vector to multiply Itself
References x, y, z.
Vector3 & Dali::Vector3::operator*=(float rhs)
Multiplication assignment operator.
@SINCE_1_0.0 rhs The float value to scale the vector Itself
Vector3 & Dali::Vector3::operator*=(const Quaternion &rhs)
Multiplication assignment operator.
@SINCE_1_0.0 rhs The Quaternion value to multiply the vector by Itself
References Dali::Quaternion::mVector, Dali::Vector4::w, x, Dali::Vector4::x, y, Dali::Vector4::y, z, Dali::Vector4::z.
Vector3 Dali::Vector3::operator/(const Vector3 &rhs) const
Division operator.
@SINCE_1_0.0 rhs The vector to divide A vector containing the result of the division
Vector3 Dali::Vector3::operator/(float rhs) const
Division operator.
@SINCE_1_0.0 rhs The float value to scale the vector by A vector containing the result of the scaling
Vector3 & Dali::Vector3::operator/=(const Vector3 &rhs)
Division assignment operator.
@SINCE_1_0.0 rhs The vector to divide Itself
References x, y, z.
Vector3 & Dali::Vector3::operator/=(float rhs)
Division assignment operator.
@SINCE_1_0.0 rhs The float value to scale the vector by Itself
Vector3 Dali::Vector3::operator-() const
Unary negation operator.
@SINCE_1_0.0 A vector containing the negation
bool Dali::Vector3::operator==(const Vector3 &rhs) const
Equality operator.
Utilizes appropriate machine epsilon values. @SINCE_1_0.0 rhs The vector to test against True if the vectors are equal
References Dali::GetRangedEpsilon, x, y, z.
bool Dali::Vector3::operator!=(const Vector3 &rhs) const
Inequality operator.
Utilizes appropriate machine epsilon values. @SINCE_1_0.0 rhs The vector to test against True if the vectors are not equal
const float & Dali::Vector3::operator[](const uint32_t index) const
Const array subscript operator overload.
Asserts if index is out of range. Should be 0, 1 or 2. @SINCE_1_0.0 index Subscript index The float at the given index
References DALI_ASSERT_ALWAYS.
float & Dali::Vector3::operator[](const uint32_t index)
Mutable array subscript operator overload.
Asserts if index is out of range. Should be 0, 1 or 2. @SINCE_1_0.0 index Subscript index The float at the given index
References DALI_ASSERT_ALWAYS.
float Dali::Vector3::Dot(const Vector3 &other) const
Returns the dot product of this vector and another vector.
The dot product is the length of one vector in the direction of another vector. This is great for lighting, threshold testing the angle between two unit vectors, calculating the distance between two points in a particular direction. @SINCE_1_0.0 other The other vector The dot product
References x, y, z.
Referenced by Dali::Quaternion::Quaternion.
Vector3 Dali::Vector3::Cross(const Vector3 &other) const
Returns the cross produce of this vector and another vector.
The cross produce of two vectors is a vector which is perpendicular to the plane of the two vectors. This is great for calculating normals and making matrices orthogonal. @SINCE_1_0.0 other The other vector The cross product
References Vector3, x, y, z.
Referenced by Dali::LookAt, Dali::Quaternion::operator*, Dali::Quaternion::Quaternion.
float Dali::Vector3::Length() const
Returns the length of the vector.
@SINCE_1_0.0 The length of the vector
References x, y, z.
Referenced by Normalize.
float Dali::Vector3::LengthSquared() const
Returns the length of the vector squared.
This is more efficient than Length() for threshold testing as it avoids the use of a square root. @SINCE_1_0.0 The length of the vector squared
References x, y, z.
void Dali::Vector3::Normalize()
Sets the vector to be unit length, whilst maintaining its direction.
@SINCE_1_0.0
References Dali::EqualsZero, Length, x, y, z.
Referenced by Dali::LookAt, Dali::Quaternion::Quaternion.
void Dali::Vector3::Clamp(const Vector3 &min, const Vector3 &max)
Clamps the vector between minimum and maximum vectors.
@SINCE_1_0.0 min The minimum vector max The maximum vector
References x, y, z.
Referenced by Dali::Clamp.
const float * Dali::Vector3::AsFloat() const
Returns the contents of the vector as an array of 3 floats.
The order of the values in this array are as follows: 0: x (or width, or r) 1: y (or height, or g) 2: z (or depth, or b) @SINCE_1_0.0 The vector contents as an array of 3 floats inlined for performance reasons (generates less code than a function call)
float * Dali::Vector3::AsFloat()
Returns the contents of the vector as an array of 3 floats.
The order of the values in this array are as follows: 0: x (or width, or r) 1: y (or height, or g) 2: z (or depth, or b) @SINCE_1_0.0 The vector contents as an array of 3 floats inlined for performance reasons (generates less code than a function call)
const Vector2 & Dali::Vector3::GetVectorXY() const
Returns the x & y components (or width & height, or r & g) as a Vector2.
@SINCE_1_0.0 The partial vector contents as Vector2 (x,y) inlined for performance reasons (generates less code than a function call)
Vector2 & Dali::Vector3::GetVectorXY()
Returns the x & y components (or width & height, or r & g) as a Vector2.
@SINCE_1_0.0 The partial vector contents as Vector2 (x,y) inlined for performance reasons (generates less code than a function call)
const Vector2 & Dali::Vector3::GetVectorYZ() const
Returns the y & z components (or height & depth, or g & b) as a Vector2.
@SINCE_1_0.0 The partial vector contents as Vector2 (y,z) inlined for performance reasons (generates less code than a function call)
Vector2 & Dali::Vector3::GetVectorYZ()
Returns the y & z components (or height & depth, or g & b) as a Vector2.
@SINCE_1_0.0 The partial vector contents as Vector2 (y,z) inlined for performance reasons (generates less code than a function call)
Dali::Vector3::Vector3(const Vector3 &)=default
Default copy constructor.
Dali::Vector3::Vector3(Vector3 &&) noexcept=default
Default move constructor.
Vector3 & Dali::Vector3::operator=(const Vector3 &)=default
Default copy assignment operator.
Vector3 & Dali::Vector3::operator=(Vector3 &&) noexcept=default
Default move assignment operator.