Dali::ConnectionTracker::Impl
constexpr uint32_t Dali::ConnectionTracker::Impl::INLINE_CAPACITY
Referenced by Insert.
union Dali::ConnectionTracker::Impl::Storage Dali::ConnectionTracker::Impl::mStorage
Referenced by DisconnectAllAndReset, Erase, GetSize, Insert, ~Impl.
bool Dali::ConnectionTracker::Impl::mUsingMap
Referenced by DisconnectAllAndReset, Erase, GetSize, Insert, ~Impl.
Dali::ConnectionTracker::Impl::~Impl()
References Dali::ConnectionTracker::Impl::Storage::mMap, mStorage, mUsingMap.
uint32_t Dali::ConnectionTracker::Impl::GetSize() const
References Dali::ConnectionTracker::Impl::Storage::mInline, Dali::ConnectionTracker::Impl::Storage::mMap, mStorage, mUsingMap, Dali::ConnectionTracker::Impl::Storage::size.
Referenced by Dali::ConnectionTracker::GetConnectionCount.
void Dali::ConnectionTracker::Impl::Insert(CallbackBase *callback, SlotObserver *observer)
References INLINE_CAPACITY, Dali::ConnectionTracker::Impl::Storage::mInline, Dali::ConnectionTracker::Impl::Storage::mMap, mStorage, mUsingMap, Dali::ConnectionTracker::Impl::Storage::pairs, Dali::ConnectionTracker::Impl::Storage::size.
Referenced by Dali::ConnectionTracker::SignalConnected.
bool Dali::ConnectionTracker::Impl::Erase(CallbackBase *callback)
References Dali::ConnectionTracker::Impl::Pair::callback, Dali::ConnectionTracker::Impl::Storage::mInline, Dali::ConnectionTracker::Impl::Storage::mMap, mStorage, mUsingMap, Dali::ConnectionTracker::Impl::Storage::pairs, Dali::ConnectionTracker::Impl::Storage::size.
Referenced by Dali::ConnectionTracker::SignalDisconnected.
void Dali::ConnectionTracker::Impl::DisconnectAllAndReset()
References Dali::ConnectionTracker::Impl::Pair::callback, Dali::ConnectionTracker::Impl::Storage::mInline, Dali::ConnectionTracker::Impl::Storage::mMap, mStorage, mUsingMap, Dali::ConnectionTracker::Impl::Pair::observer, Dali::ConnectionTracker::Impl::Storage::pairs, Dali::ConnectionTracker::Impl::Storage::size, Dali::SlotObserver::SlotDisconnected.
Referenced by Dali::ConnectionTracker::DisconnectAll.