repos:
  dali-core:
    path: "/home/bshsqa/Shared/DALi/dali-core"
    branch: "master"
    api_dirs:
      - "dali/public-api"
      - "dali/devel-api"
      - "dali/integration-api"
  dali-adaptor:
    path: "/home/bshsqa/Shared/DALi/dali-adaptor"
    branch: "master"
    api_dirs:
      - "dali/public-api"
      - "dali/devel-api"
      - "dali/integration-api"
  dali-ui:
    path: "/home/bshsqa/Shared/DALi/dali-ui"
    branch: "devel"
    api_dirs:
      - "dali-ui-foundation/public-api"
      - "dali-ui-foundation/devel-api"
      - "dali-ui-foundation/integration-api"
      - "dali-ui-components/public-api"
      - "dali-ui-components/integration-api"
