repos:
  dali-core:
    url: "https://github.com/dalihub/dali-core.git"
    path: "repos/dali-core"
    branch: "master"
    api_dirs:
      - "dali/public-api"
      - "dali/devel-api"
      - "dali/integration-api"
  dali-adaptor:
    url: "https://github.com/dalihub/dali-adaptor.git"
    path: "repos/dali-adaptor"
    branch: "master"
    api_dirs:
      - "dali/public-api"
      - "dali/devel-api"
      - "dali/integration-api"
  dali-ui:
    url: "https://github.com/dalihub/dali-ui.git"
    path: "repos/dali-ui"
    branch: "devel"
    api_dirs:
      - "dali-ui-foundation/public-api"
      - "dali-ui-foundation/devel-api"
      - "dali-ui-foundation/integration-api"
      - "dali-ui-components/public-api"
      - "dali-ui-components/integration-api"
